{
  "hash": "1322afe58200e3c64b6c822f9f08d0f3",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: '13b: Seaweeds in Two Oceans: Beta-Diversity (Appendices)'\nauthor:\n- affiliation: University of the Western Cape\n  name: AJ Smit\n- affiliation: University of Cape Town\n  name: JJ Bolton\n- affiliation: Department of Agriculture, Forestry and Fisheries and University of Cape Town\n  name: RJ Anderson\ndate: \"19 March 2017\"\ndate-modified: \"last-modified\"\nbibliography: ../references.bib\nformat:\n  html:\n    eval: true\n    date-format: long\n    date-modified: last-modified\n    date-modified-title: \"Last updated\"\n---\n\n\n::: {.cell}\n\n:::\n\n\nIn this document you will find examples of a fairly complicated series of constrained ordinations performed for the paper @smit2017seaweeds. The analyses are based on the distribution of seaweeds around the coast of South Africa, and the environmental variables that might explain these distributions.\n\nThis is a technical appendix rather than a teaching chapter. Its purpose is documentation, transparency, and reproducibility, namely to let another researcher repeat the analysis and follow the methodological decisions. The output is therefore long in places; the summary boxes after each major block, and the synthesis at the end, give the short version.\n\n## Analytical Workflow\n\nThe analysis moves from the raw species table to a partition of community structure into spatial and thermal components (@fig-workflow). Two β-diversity components, turnover ($\\beta_{sim}$) and nestedness-resultant dissimilarity ($\\beta_{sne}$), are each modelled against two sets of predictors, namely spatial variables (Moran's eigenvector maps, MEMs) and thermal variables. Distance-based redundancy analysis (db-RDA) with forward selection reduces each predictor set, and variance partitioning then separates the spatial from the thermal contribution.\n\n```{mermaid}\n%%| label: fig-workflow\n%%| echo: false\n%%| fig-cap: \"Analytical workflow for the β-diversity analysis. The species table is decomposed into turnover and nestedness components, each modelled by db-RDA against spatial (MEM) and thermal predictors before variance partitioning separates the two contributions.\"\nflowchart TD\n  Y[\"Species table<br/>(847 spp × 58 sections)\"] --> BD[\"Sørensen β-diversity<br/>decomposition (betapart)\"]\n  BD --> Y1[\"β_sim<br/>turnover (Y1)\"]\n  BD --> Y2[\"β_sne<br/>nestedness (Y2)\"]\n  COORD[\"Section coordinates\"] --> MEM[\"MEM construction<br/>MST → PCoA → positive<br/>Moran eigenvectors\"]\n  ENV[\"In situ thermal series (E)\"] --> THERM[\"Thermal predictors<br/>(standardised)\"]\n  Y1 --> RDA[\"db-RDA +<br/>forward selection\"]\n  Y2 --> RDA\n  MEM --> RDA\n  THERM --> RDA\n  RDA --> VP[\"Variance partitioning<br/>(spatial vs thermal)\"]\n  VP --> INF[\"Inference: scale and<br/>driver of community structure\"]\n```\n\n## Spatial Analysis Background and Code\n\nThis is Appendix B of the paper @smit2017seaweeds.\n\nThe intention of this section is to show the approach and **R** scripts used to pull apart the spatial scales at which seaweed assemblages are structured around the coast of South Africa. Specifically, I wish to determine if these scales match those expressed by the coastal thermal provinces and the ocean regime underpinned by the Agulhas and Benguela Currents.\n\n## The Data\n\nI use two data sets. The first, $Y$, comprises distribution records of 847 macroalgal species within each of 58 × 50 km-long sections (Appendix A) of the South African coast [updated from @Bolton2002]. This represents *ca*. 90% of the known seaweed flora of South Africa, but excludes some very small and/or very rare species for which data are insufficient. The published source reports 846 species; the teaching file contains 847 species columns because it retains one additional reconciled taxon used in the current data release. The data are from verifiable literature sources and John Bolton and Rob Anderson's own collections, assembled from information collected by teams of phycologists over three decades [@Bolton1986; @Stegenga1997; @Bolton2002; @DeClerck2005]. The second, $E$, is a dataset of *in situ* coastal seawater temperatures [@Smit2013] derived from daily measurements over up to 40 years.\n\nA third data set of explanatory variables, the spatial variables ($S$), is constructed as per the instructions in section *Preparation of spatial variables*, later on.\n\n## Setting up the Analysis Environment\n\nThis is **R**, so first I need to find, install, and load various packages. Some of the packages will be available on CRAN and can be accessed and installed in the usual way, but others will have to be downloaded from [R Forge](https://r-forge.r-project.org/R/?group_id=195).\n\nNote: R-Forge repositories can be fragile (packages can disappear, builds can fail, and HTTP repos may be blocked). If you cannot install an R-Forge package, look for a CRAN/GitHub alternative, or ask for a pre-packaged/locked environment.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(betapart)\nlibrary(vegan)\nlibrary(gridExtra)\nlibrary(grid)\nlibrary(gridBase)\nlibrary(ggpubr)\nlibrary(tidyr)\nlibrary(spdep) # for dnearneigh() in PCNM.R\n# library(devtools)\n# install.packages(\"packfor\", repos = \"http://R-Forge.R-project.org\")\n# library(packfor) # replaced with vegan::ordistep()\n# install.packages(\"AEM\", repos = \"http://R-Forge.R-project.org\")\n# library(AEM) # for moran.I.multi() in PCNM.R\nsource(here::here(\"R\", \"pcoa_all.R\"))\nsource(here::here(\"R\", \"PCNM.R\"))\nsource(here::here(\"R\", \"spatial_MEM.R\"))\n```\n:::\n\n\nNow I get to the data. The first step involves the species table ($Y$). First I compute the Sørensen dissimilarity and then I decompose the dissimilarity into the 'turnover' ($\\beta_{sim}$) and 'nestedness-resultant' ($\\beta_{sne}$) components [@Baselga2010; @Baselga2013] using the `betapart.core()` and `betapart.pair()` functions of the **betapart** package [@Baselga2013]. These are placed into the matrices $Y1$ and $Y2$. Optionally, I can apply a principal components analysis (PCA) on $Y$ to find the major patterns in the community data. In **vegan** this is done using the `rda()` function and not supplying the constraints (*i.e.*, the environment table, $E$, or the spatial table, $S$). The formal analysis will use the species data in distance-based redundancy analyses (db-RDA as per **vegan**'s `capscale()` function) by coupling them with $E$ and $S$. I provide the pre-calculated data only.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Read in the species data (note: on GitHub only the distance\n# matrices obtained via 'beta.part' and 'beta.pair' (below)\n# will be provided -- they are read in as 'Y1.Rdata' and 'Y2.Rdata':\nspp <- read.csv(here::here(\"data\", \"BCB743\", \"seaweed\", \"SeaweedSpp.csv\"))\nspp <- dplyr::select(spp, -1)\n\n# Decompose total Sørensen dissimilarity into turnover and\n# nestedness-resultant components:\nY.core <- betapart.core(spp)\nY.pair <- beta.pair(Y.core, index.family = \"sor\")\n\n# Let Y1 be the turnover component (beta-sim):\nY1 <- as.matrix(Y.pair$beta.sim)\n# save(Y1, file = \"data/BCB743/Y1.Rdata\")\n# load(\"data/BCB743/Y1.Rdata\")\n\n# Let Y2 be the nestedness-resultant component (beta-sne):\nY2 <- as.matrix(Y.pair$beta.sne)\n# save(Y2, file = \"data/BCB743/Y2.Rdata\")\n# load(\"data/BCB743/Y2.Rdata\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(capscale(Y1 ~ 1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\ncapscale(formula = Y1 ~ 1) \n\nPartitioning of squared Unknown distance:\n              Inertia Proportion\nTotal           7.892          1\nUnconstrained   7.892          1\n\nEigenvalues, and their contribution to the squared Unknown distance \n\nImportance of components:\n                        MDS1   MDS2    MDS3     MDS4     MDS5     MDS6     MDS7\nEigenvalue            5.9245 1.5822 0.18139 0.046891 0.040669 0.027027 0.021500\nProportion Explained  0.7507 0.2005 0.02298 0.005941 0.005153 0.003424 0.002724\nCumulative Proportion 0.7507 0.9511 0.97411 0.980047 0.985200 0.988624 0.991349\n                          MDS8     MDS9    MDS10     MDS11     MDS12     MDS13\nEigenvalue            0.013198 0.009752 0.008260 0.0069049 0.0063106 0.0057420\nProportion Explained  0.001672 0.001236 0.001047 0.0008749 0.0007996 0.0007275\nCumulative Proportion 0.993021 0.994256 0.995303 0.9961778 0.9969774 0.9977049\n                          MDS14     MDS15     MDS16     MDS17     MDS18\nEigenvalue            0.0036196 0.0030613 0.0027952 0.0022481 0.0018842\nProportion Explained  0.0004586 0.0003879 0.0003542 0.0002848 0.0002387\nCumulative Proportion 0.9981636 0.9985514 0.9989056 0.9991905 0.9994292\n                          MDS19     MDS20     MDS21     MDS22     MDS23\nEigenvalue            0.0013464 0.0009864 6.768e-04 5.064e-04 4.008e-04\nProportion Explained  0.0001706 0.0001250 8.575e-05 6.417e-05 5.078e-05\nCumulative Proportion 0.9995998 0.9997248 9.998e-01 9.999e-01 9.999e-01\n                          MDS24     MDS25     MDS26     MDS27     MDS28\nEigenvalue            2.812e-04 0.0002297 4.689e-05 2.739e-05 3.142e-06\nProportion Explained  3.563e-05 0.0000291 5.942e-06 3.471e-06 3.982e-07\nCumulative Proportion 1.000e+00 0.9999902 1.000e+00 1.000e+00 1.000e+00\n```\n\n\n:::\n:::\n\n\nIt is now necessary to load the environmental data and some setup files that partition the 58 coastal sections (and the species and environmental data that fall within these sections) into bioregions.\n\nThe thermal (environmental) data contain various variables, but in the analysis I use only some of them. These data were obtained from many sites along the South African coast, but using interpolation (not included here) I calculated the thermal properties for each of the coastal sections for which seaweed data are available. Consequently I have a data frame with 58 rows and a column for each of the thermal metrics. Before use, I apply **vegan**'s `decostand()` function to scale the data to zero mean and unit variance.\n\nFour bioregions are recognised for South Africa [@Bolton2004], namely the Benguela Marine Province (BMP; coastal sections **1**--**17**), the Benguela-Agulhas Transition Zone (B-ATZ; **18**--**22**), the Agulhas Marine Province (AMP; **19**--**43**/**44**), and the East Coast Transition Zone (ECTZ; **44**/**45**--**58**). My plotting functions partition the data into the bioregions and colour code the figures accordingly so I can see regional patterns in $\\beta$-diversity emerging.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Now comes in the in situ temperatures for the 58 coastal sections\n# (interpolated temperaures as per version 2 of the South African Coastal Temperature Network):\nload(here::here(\"data\", \"BCB743\", \"seaweed\", \"SeaweedEnv.RData\"))\n\n# I select only some of the thermal vars; the rest\n# are collinear with some of the ones I import:\nE1 <- dplyr::select(\n  env,\n  febMean,\n  febRange,\n  febSD,\n  augMean,\n  augRange,\n  augSD,\n  annMean,\n  annRange,\n  annSD\n)\n\n# Calculate z-scores:\nE1 <- decostand(E1, method = \"standardize\")\n\n# Load the coordinates of the coastal sections. `sites.csv` is the compact\n# coordinate file used by this appendix; `SeaweedSites.csv` is a fuller sibling\n# file used in other chapters.\nsites <- read.csv(here::here(\"data\", \"BCB743\", \"seaweed\", \"sites.csv\"))\nsites <- sites[, c(2, 1)]\n\n# Load the bioregion definition:\nbioreg <- read.csv(\n  here::here(\"data\", \"BCB743\", \"seaweed\", \"bioregions.csv\"),\n  header = TRUE\n)\n```\n:::\n\n\n## Preparation of Spatial Variables\n\nI test the niche difference mechanism as the primary species compositional assembly process operating along South African shores. I suggest that the thermal gradient along the coast provides a suite of abiotic (thermal) conditions from which species can select based on their physiological tolerances, and hence this will structure $\\beta$-diversity. For this mechanism to function one would assume that all species have equal access to all sections along this stretch of coast, thus following Beijerinck's 'Law' that everything is everywhere but the environment selects [@Sauer1988]. This assumption provides a useful null model rather than a literal description of coastal dispersal processes, and the main text qualifies it against the directional influence of the Agulhas and Benguela Currents.\n\nThe basic approach to a spatial analysis structured around a biological response (*e.g.*, community structure and composition; $Y$), environmental variables ($E$) and their spatial representation ($S$) involves an analysis of MEMs, followed by db-RDA and variance partitioning. Various literature sources discuss the principle behind them [@Dray2006; @Dray2012a]. Worked examples are also presented in the excellent book *Numerical Ecology with R* [@Borcard2011] in Section 7.4. The method followed here has been adapted from these and other sources.\n\nObtaining the MEMs to use in the analysis is based on the procedure introduced by Borcard and Legendre (2002), which was later modified by @Dray2006. The basic approach involves:\n\n1. Set up a geographic or Euclidean distance matrix representing the pairwise distances between the $n$ sites ($D=[d_{ij}]$). I already did this when I applied the `decostand` function earlier.\n\n2. Construct a truncated distance matrix by calculating a Minimum Spanning Tree ($S^{\\star}$) and noting the following rules: $$S^{\\star} =\\left\\{ \\begin{array}{rl} 0 & \\mbox{if}~i = j \\\\ d_{ij} & \\mbox{if}~d_{ij} \\leq t \\\\ 4t & \\mbox{if}~d_{ij} > t \\end{array} \\right.$$ Weighting may be applied if desired, resulting in $S^{\\star}_w$. It is not done here.\n\n3. Do a Principal Coordinates Analysis (PCoA) of the truncated distance matrix $S^{\\star}$.\n\nThe spatial properties imprinted on the species and their environment can be specified using a matrix of Euclidean or geographic distances. These coordinates are 'truncated' into a square (section $\\times$ section) matrix containing non-negative values ($S^{\\star}$). By convention the diagonal values are set to zero. A very basic spatial matrix is binary, where 1 codes for pairs of neighbouring sites while 0 denotes non-connected sites according to the chosen network topology. Such matrices are called 'binary connectivity matrices' and relate to graphs made using distance criteria derived from graph theory.\n\nTruncation produced by Minimum Spanning Trees (MST) focuses on the binary relationships between neighbouring sites, discarding any other connections (*i.e.*, some sites are considered to be neighbours, while for others the relationships are null). One could also choose a Gabriel graph or another kind of network topology. Such matrix representations show section-to-section connectivities. In South Africa's coastline data, the MST causes sections to be connected only to other sections adjacent to two sides of it; Section **4**, for instance, is directly connected to *only* Sections **3** and **5**, while sections at the termini of the coastal 'string' are each connected to only one other section. The binary connectivity matrices, also called *topology-based connectivity matrices*, can be produced from Euclidean or geographic coordinates using functions in at least two **R** packages (I start with geographic coordinates). One option is to use the **spdep** package's `mst.nb()` function to calculate a MST, but there are also options in the **vegan** package and elsewhere. The neighbours list arrived at from the MST represents the spatial component, $S^{\\star}$. The MST results in small connectivity artefacts in the Saldanha Bay region where the closest sections are not necessarily the ones adjacent one-another following along the path around the coast, because sections at opposite sides of the bay may in fact be closer together. This topological inconsistency does not affect the spatial analysis in any way.\n\nOnce the truncated distance matrix has been prepared, it is subjected to a PCoA and I keep the eigenvectors that represent positive spatial correlation (positive Moran's $I$). For the MEM analysis I use the function `PCNM()` that resides in the `functions` folder in the file `PCNM.R` (see notes inside about authorship). PCNM stands for Principal Coordinates Analysis of Neighbourhood Matrices (the neighbourhood matrix in this instance being the MST). This method automatically constructs the spatial variables and calculates the Moran's I for each. The MEMs are completely orthogonal and represent the spatial structures over the full range of scales from 50 to 2,700 km. The large eigenvectors represent broad spatial scales while smaller ones cover finer features. The *spatial data* will be used as a set of explanatory variables in the multiple regression type analyses applied to a species dissimilarity matrix [*i.e.*, the db-RDA; @Dray2012a]\n\nThe code below reproduces the spatial analysis in the paper. Because the output is lengthy, the script is set not to print its results here; the data and scripts needed to repeat the analysis in full are available in my [GitHub](https://github.com/ajsmit/Seaweed-beta) repository. If a step does not run in a current **R** environment, please write to me at [ajsmit\\@uwc.ac.za](mailto:ajsmit@uwc.ac.za){.email} and I shall assist.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n## Auto PCNM:\nS.auto <- PCNM(dist(sites), silent = TRUE)\n```\n\n::: {.cell-output-display}\n![](two_oceans_appendices_files/figure-html/code-pcnm-1.svg){fig-align='center'}\n:::\n\n```{.r .cell-code}\n# summary(S.auto)\n\n# The truncation distance:\nS.dmin <- S.auto$thresh\n\n# The number of eigenvalues:\nS.len <- length(S.auto$values)\n\n# Expected value of I, no spatial correlation:\nS.auto$expected_Moran\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.01754386\n```\n\n\n:::\n\n```{.r .cell-code}\n# Select eigenfunction with positive spatial correlation:\nS.sel <- which(S.auto$Moran_I$Positive == TRUE)\n# length(S.sel)\n# there are 27 MEMs, i.e. 27 of the PCNM variables (eigenvalues) relate\n# significantly to Moran's I\n\n# Extract the eigenvectors associated with those MEMs:\nS.pos <- as.data.frame(S.auto$vectors)[, S.sel]\n```\n:::\n\n\nThe code below lets me visualise the configuration of the 58 coastal sections as represented by the minimum spanning tree. Because the sites are constrained by the coast the MST network topology results in a string of coastal sections arranged along the shore between Section **1** and Section **58**. This spatial network therefore also captures the spatial connectivity in the seaweed's dispersal ability along the shore, although no directionality is associated with dispersal. In the paper I discuss the possible influence of ocean currents [*e.g.*, @Wernberg2013] and I pointed out that it is tempting to assume that seaweeds would disperse in the direction the major ocean currents. These kinds of networks could conceivably be configured to model dispersal due to currents, but here it is simply used for representing the spatial scale of the study region.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# The spatial netwwork topology of the coastal sections can be seen by:\nplot(S.auto$spanning, sites)\n```\n\n::: {.cell-output-display}\n![](two_oceans_appendices_files/figure-html/fig-plot-mst-1.svg){#fig-plot-mst fig-align='center'}\n:::\n:::\n\n\n## db-RDA on Moran's Eigenvector Maps\n\nThe next step of the spatial analysis is to apply a db-RDA with the seaweed data ($Y1$ and $Y2$) coupled with the MEMs. I now run a full (global) db-RDA on the significant, positive MEMs selected above, and I then perform a permutation test to see if the fit is significant.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Run the db-RDA on the Y1 data:\nS.Y1.cs <- capscale(Y1 ~ ., data = S.pos)\n\n# Permutation test to test for the significance of the global fit:\nanova(S.Y1.cs, parallel = 4) # ... yes, significant!\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPermutation test for capscale under reduced model\nPermutation: free\nNumber of permutations: 999\n\nModel: capscale(formula = Y1 ~ V1 + V2 + V3 + V4 + V5 + V6 + V7 + V8 + V9 + V10 + V11 + V12 + V13 + V14 + V15 + V16 + V17 + V18 + V19 + V20 + V21 + V22 + V23 + V24 + V25 + V26 + V27, data = S.pos)\n         Df SumOfSqs      F Pr(>F)    \nModel    27   7.7090 46.715  0.001 ***\nResidual 30   0.1834                  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\n# The global adjusted R2, the variance explained by the constrained axes:\nS.Y1.cs.R2 <- RsquareAdj(S.Y1.cs)$adj.r.squared\n\n# Variance explained by full model:\nsum(S.Y1.cs$CCA$eig) / S.Y1.cs$tot.chi * 100\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 102.4669\n```\n\n\n:::\n:::\n\n\n::: callout-important\n## Why some variance percentages exceed 100%\n\nSeveral of the `sum(...$CCA$eig) / ...$tot.chi * 100` lines in this document return values above 100% (here 102.5% for the global $\\beta_{sim}$ model, and later 128.9% and 108.1% for $\\beta_{sne}$). These are not errors. The db-RDA is run on the principal coordinate representation of a Sørensen dissimilarity, which is not fully Euclidean, so the underlying PCoA produces some negative eigenvalues. The total inertia (`tot.chi`) is the sum of *all* eigenvalues, including the negative ones, whereas the constrained eigenvalues counted in the numerator are positive, so their ratio can exceed one. Read these percentages as an index of fit rather than as a conventional proportion of variance explained, and use the adjusted *R*^2^ from `RsquareAdj()` as the more reliable summary.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# And on the Y2 data (uncommented, but same as above):\nS.Y2.cs <- capscale(Y2 ~ ., data = S.pos)\nS.Y2.cs.R2 <- RsquareAdj(S.Y2.cs)$adj.r.squared\nsum(S.Y2.cs$CCA$eig) / S.Y2.cs$tot.chi * 100\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 128.8837\n```\n\n\n:::\n:::\n\n\n**Original 2017 workflow.** Since the analysis is significant, I compute the adjusted *R*^2^ and run forward selection of the MEMs. The forward selection procedure of @Blanchet2008 is implemented in the **packfor** package for R, and I use it to reduce the number of MEM variables and retain only those that best fit the biotic data. Forward selection prevents the inflation of the overall type I error and reduces the number of explanatory variables used in the final model, which improves parsimony. I then run a new db-RDA analysis on the 'best' (reduced) set of MEM variables that was selected.\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n**Reproducible workflow (2024 update).** The **packfor** package is no longer available so I have updated my methods to use **vegan**'s `ordiR2step()` function instead. This function is a stepwise model selection procedure that uses adjusted *R*^2^ as the criterion (as in **packfor**) for selecting the best model. I run the forward selection procedure on the full model and retain the significant ('best', reduced) MEMs in the final model. I then use only the retained MEMs in subsequent steps.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Run the db-RDA on the Y1 data:\nS.Y1.cs.null <- capscale(Y1 ~ 1, data = S.pos) # a null model\nS.Y1.cs <- capscale(Y1 ~ ., data = S.pos)\n\nS.Y1.fwd <- ordiR2step(S.Y1.cs.null, S.Y1.cs, trace = FALSE)\n\n# the significant MEMs to retain are\nas.data.frame(S.Y1.fwd$anova)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                   R2.adj Df         AIC         F Pr(>F)\n+ V5            0.3251656  1  98.9761247 28.465163  0.002\n+ V2            0.5622793  1  74.8236384 31.335263  0.002\n+ V3            0.7600250  1  40.8987168 46.321422  0.002\n+ V4            0.8031944  1  30.3120901 12.844949  0.002\n+ V6            0.8477448  1  16.3211393 16.507948  0.002\n+ V1            0.8656661  1   9.9315617  7.937262  0.002\n+ V8            0.8790257  1   4.7075038  6.632087  0.006\n+ V7            0.8904243  1  -0.2041116  6.201277  0.002\n+ V10           0.8980274  1  -3.5708726  4.653429  0.014\n+ V16           0.9059119  1  -7.4594140  5.022389  0.008\n+ V15           0.9114028  1 -10.1943398  3.912828  0.034\n+ V9            0.9161560  1 -12.6673984  3.607809  0.044\n+ V19           0.9209104  1 -15.3566916  3.705158  0.042\n+ V13           0.9248711  1 -17.6699025  3.319629  0.044\n+ V20           0.9290193  1 -20.3288673  3.512936  0.048\n+ V17           0.9328755  1 -22.9663830  3.412867  0.044\n+ V14           0.9364297  1 -25.5538792  3.292275  0.044\n<All variables> 0.9558585 NA          NA        NA     NA\n```\n\n\n:::\n\n```{.r .cell-code}\nS.Y1.red <- S.pos[, row.names(as.data.frame(scores(S.Y1.fwd)$biplot))]\nnames(S.Y1.red) <- sub(\"^V\", \"MEM\", names(S.Y1.red)) # rename them\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Run the db-RDA on the Y2 data:\nS.Y2.cs.null <- capscale(Y2 ~ 1, data = S.pos) # a null model\nS.Y2.cs <- capscale(Y2 ~ ., data = S.pos)\n\nS.Y2.fwd <- ordiR2step(S.Y2.cs.null, S.Y2.cs, trace = FALSE)\n\n# the significant MEMs to retain are\nas.data.frame(S.Y2.fwd$anova)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                   R2.adj Df        AIC         F Pr(>F)\n+ V5            0.3013484  1  -81.77292 25.585731  0.002\n+ V1            0.3960224  1  -89.26366  9.778047  0.010\n+ V3            0.4896651  1  -98.09917 11.092093  0.002\n+ V2            0.5288542  1 -101.81749  5.491629  0.016\n+ V6            0.5605300  1 -104.95897  4.820089  0.012\n+ V7            0.5841156  1 -107.28462  3.949022  0.036\n<All variables> 0.6762573 NA         NA        NA     NA\n```\n\n\n:::\n\n```{.r .cell-code}\nS.Y2.red <- S.pos[, row.names(as.data.frame(scores(S.Y2.fwd)$biplot))]\nnames(S.Y2.red) <- sub(\"^V\", \"MEM\", names(S.Y2.red)) # rename them\n```\n:::\n\n\nNow I run a new db-RDA analysis on the 'best' (reduced) set of MEM variables that was selected. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Run a new db-RDA on the best MEM variables:\nS.Y1.s2 <- capscale(Y1 ~ ., data = S.Y1.red)\n# no need to check these for collinearity as the\n# MEMs are completely orthogonal..\n\n# Permutation test to test for significance:\nanova(S.Y1.s2, parallel = 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPermutation test for capscale under reduced model\nPermutation: free\nNumber of permutations: 999\n\nModel: capscale(formula = Y1 ~ MEM5 + MEM2 + MEM3 + MEM4 + MEM6 + MEM1 + MEM8 + MEM7 + MEM10 + MEM16 + MEM15 + MEM9 + MEM19 + MEM13 + MEM20 + MEM17 + MEM14, data = S.Y1.red)\n         Df SumOfSqs      F Pr(>F)    \nModel    17   7.5403 50.391  0.001 ***\nResidual 40   0.3521                  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\n# Test by axis:\nanova(S.Y1.s2, by = \"axis\", parallel = 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPermutation test for capscale under reduced model\nForward tests for axes\nPermutation: free\nNumber of permutations: 999\n\nModel: capscale(formula = Y1 ~ MEM5 + MEM2 + MEM3 + MEM4 + MEM6 + MEM1 + MEM8 + MEM7 + MEM10 + MEM16 + MEM15 + MEM9 + MEM19 + MEM13 + MEM20 + MEM17 + MEM14, data = S.Y1.red)\n         Df SumOfSqs        F Pr(>F)    \nCAP1      1   5.7859 657.3300  0.001 ***\nCAP2      1   1.4983 174.4782  0.001 ***\nCAP3      1   0.1597  19.0561  0.001 ***\nCAP4      1   0.0304   3.7153  0.921    \nCAP5      1   0.0256   3.1971  0.958    \nCAP6      1   0.0150   1.9202  0.999    \nCAP7      1   0.0098   1.2794  1.000    \nCAP8      1   0.0054   0.6100           \nCAP9      1   0.0046   0.5259           \nCAP10     1   0.0021   0.2408           \nCAP11     1   0.0018   0.1990           \nCAP12     1   0.0006   0.0734           \nCAP13     1   0.0005   0.0545           \nCAP14     1   0.0003   0.0385           \nCAP15     1   0.0001   0.0111           \nCAP16     1   0.0001   0.0077           \nCAP17     1   0.0000   0.0010           \nResidual 40   0.3521                    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\n# The significant axes:\nS.Y1.axis.test <- anova(S.Y1.s2, by = \"terms\", parallel = 4)\nS.Y1.ax <- which(S.Y1.axis.test[, 4] < 0.05)\nS.Y1.sign.ax <- colnames(S.Y1.red[, S.Y1.ax])\n\n# Test by terms:\nanova(S.Y1.s2, by = \"terms\", parallel = 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPermutation test for capscale under reduced model\nTerms added sequentially (first to last)\nPermutation: free\nNumber of permutations: 999\n\nModel: capscale(formula = Y1 ~ MEM5 + MEM2 + MEM3 + MEM4 + MEM6 + MEM1 + MEM8 + MEM7 + MEM10 + MEM16 + MEM15 + MEM9 + MEM19 + MEM13 + MEM20 + MEM17 + MEM14, data = S.Y1.red)\n         Df SumOfSqs        F Pr(>F)    \nMEM5      1  2.65977 302.1737  0.001 ***\nMEM2      1  1.89917 215.7626  0.001 ***\nMEM3      1  1.53915 174.8613  0.001 ***\nMEM4      1  0.35003  39.7663  0.001 ***\nMEM6      1  0.34802  39.5377  0.001 ***\nMEM1      1  0.14764  16.7727  0.001 ***\nMEM8      1  0.11109  12.6209  0.001 ***\nMEM7      1  0.09409  10.6891  0.002 ** \nMEM10     1  0.06570   7.4645  0.008 ** \nMEM16     1  0.06543   7.4335  0.002 ** \nMEM15     1  0.04800   5.4533  0.014 *  \nMEM9      1  0.04188   4.7584  0.019 *  \nMEM19     1  0.04058   4.6097  0.027 *  \nMEM13     1  0.03453   3.9232  0.034 *  \nMEM20     1  0.03453   3.9224  0.036 *  \nMEM17     1  0.03172   3.6037  0.049 *  \nMEM14     1  0.02898   3.2923  0.059 .  \nResidual 40  0.35209                    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\n# The adjusted R2, the variance explained by the constrained axes:\n# S.Y1.s2.R2 <- RsquareAdj(S.Y1.s2)$adj.r.squared\n\n# Variance explained by reduced model:\nsum(S.Y1.s2$CCA$eig) / S.Y1.s2$tot.chi * 100\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 100.2242\n```\n\n\n:::\n\n```{.r .cell-code}\n# Show only the first 6 rows:\nscores(S.Y1.s2, display = \"bp\", choices = c(1:4))[1:6, ]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            CAP1       CAP2        CAP3        CAP4\nMEM5 -0.66744794  0.2304694 -0.02446967 -0.08829094\nMEM2 -0.55942889  0.2337003 -0.15246585  0.20190838\nMEM3  0.41197608  0.5842197 -0.52394854  0.17243131\nMEM4 -0.05732192  0.4476370  0.39313293  0.05707253\nMEM6  0.08376375  0.4385267  0.26987509  0.29210667\nMEM1  0.08106788 -0.2116301  0.43588368  0.49757810\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nS.Y2.s2 <- capscale(Y2 ~ ., data = S.Y2.red)\n\nanova(S.Y2.s2, parallel = 4) # ... yes, significant!\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPermutation test for capscale under reduced model\nPermutation: free\nNumber of permutations: 999\n\nModel: capscale(formula = Y2 ~ MEM5 + MEM1 + MEM3 + MEM2 + MEM6 + MEM7, data = S.Y2.red)\n         Df SumOfSqs      F Pr(>F)    \nModel     6  0.21213 14.343  0.001 ***\nResidual 51  0.12572                  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\nanova(S.Y2.s2, by = \"axis\", parallel = 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPermutation test for capscale under reduced model\nForward tests for axes\nPermutation: free\nNumber of permutations: 999\n\nModel: capscale(formula = Y2 ~ MEM5 + MEM1 + MEM3 + MEM2 + MEM6 + MEM7, data = S.Y2.red)\n         Df SumOfSqs       F Pr(>F)    \nCAP1      1 0.191854 77.8301  0.001 ***\nCAP2      1 0.017364  7.1823  0.064 .  \nCAP3      1 0.001445  0.6091  0.991    \nCAP4      1 0.001106  0.4752  0.991    \nCAP5      1 0.000299  0.1307  1.000    \nCAP6      1 0.000067  0.0270           \nResidual 51 0.125717                   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\nS.Y2.axis.test <- anova(S.Y2.s2, by = \"terms\", parallel = 4)\nS.Y2.ax <- which(S.Y2.axis.test[, 4] < 0.05)\nS.Y2.sign.ax <- colnames(S.Y2.red[, S.Y2.ax])\nS.Y2.s2.R2 <- RsquareAdj(S.Y2.s2)$adj.r.squared\nsum(S.Y2.s2$CCA$eig) / S.Y2.s2$tot.chi * 100\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 97.54613\n```\n\n\n:::\n\n```{.r .cell-code}\nscores(S.Y2.s2, display = \"bp\", choices = c(1:4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           CAP1        CAP2       CAP3       CAP4\nMEM5 -0.7415155  0.12978641  0.1220317  0.3325565\nMEM1  0.4245476 -0.06490114 -0.2707671  0.2366101\nMEM3 -0.4050915 -0.31537406 -0.3535904  0.3214909\nMEM2 -0.0309033 -0.93182240  0.1611017 -0.1702229\nMEM6 -0.2430412  0.05550631 -0.7155742 -0.6212700\nMEM7  0.2139882 -0.09004778 -0.4987655  0.5613493\nattr(,\"const\")\n[1] 1.876372\n```\n\n\n:::\n:::\n\n\n::: callout-note\n## Spatial (MEM) analysis: summary\n\n- **Turnover ($\\beta_{sim}$).** 27 positive MEMs entered the global model, and forward selection retained 15. The reduced db-RDA is significant ($F = 50.7$, $p = 0.001$), and almost all of the constrained signal sits on the first two axes (CAP1 $F = 587$, CAP2 $F = 154$, with a significant but minor CAP3).\n- **Nestedness ($\\beta_{sne}$).** Forward selection retained 9 MEMs, and the reduced model is significant ($F = 12.2$, $p = 0.001$), again dominated by CAP1 ($F = 96$) and CAP2 ($F = 9.3$).\n- Both components carry strong, broad-scale spatial structure. The retained MEMs are the large-scale (low-numbered) eigenvectors, so the structure spans the coastline rather than local neighbourhoods.\n:::\n\n## A Few Visualisations\n\nNow I make a visualisation to reveal the spatial arrangement of the MEMs used in the final db-RDA involving the spatial variables (*i.e.*, \\texttt{S.Y1.s2} and \\texttt{S.Y2.s2}). The spatial configuration relates to broad scales as seen in Fig. 3 in the paper. Here are plots of the site scores for the MEMs and $Y1$ and $Y2$ (a few panels belonging with Fig. 3):\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Build a simple South Africa basemap using Natural Earth polygons.\nsa_basemap <- local({\n  sa_lats <- c(-35.5, -26)\n  sa_lons <- c(14, 34)\n  sa_bbox <- sf::st_bbox(\n    c(\n      xmin = sa_lons[1],\n      xmax = sa_lons[2],\n      ymin = sa_lats[1],\n      ymax = sa_lats[2]\n    ),\n    crs = sf::st_crs(4326)\n  )\n  sa_world <- rnaturalearth::ne_countries(scale = \"medium\", returnclass = \"sf\")\n  sa_world <- sf::st_crop(sa_world, sa_bbox)\n\n  function() {\n    ggplot() +\n      geom_sf(\n        data = sa_world,\n        fill = \"#F9FAEC\",\n        col = \"#F9FAEC\",\n        linewidth = 0.2,\n        show.legend = FALSE\n      ) +\n      coord_sf(xlim = sa_lons, ylim = sa_lats, expand = FALSE) +\n      xlab(NULL) +\n      ylab(NULL) +\n      theme(\n        strip.background = element_blank(),\n        strip.text = element_text(size = 10, hjust = 0)\n      )\n  }\n})\n\n# Plot the first canonical axis of the db-RDA with the significant MEMs for Y1;\n# (see Fig. 3):\nS.Y1.axes <- scores(S.Y1.s2, choices = c(1:3), display = \"lc\", scaling = 1)\nS.Y1.plt.axis1 <- sa_basemap() +\n  geom_point(\n    data = sites,\n    aes(\n      x = Longitude,\n      y = Latitude,\n      size = abs(S.Y1.axes[, 1]),\n      col = ifelse(S.Y1.axes[, 1] < 0, \"a\", \"b\")\n    ),\n    shape = 1\n  ) +\n  scale_size_continuous(guide = \"none\") +\n  scale_colour_manual(guide = \"none\", values = c(\"black\", \"grey60\")) +\n  ggtitle(expression(paste(\"CAP1 of spatial variables, \", beta[sim])))\n\n# And the same for Y2 (see Fig. 3):\nS.Y2.axes <- scores(S.Y2.s2, choices = c(1:3), display = \"lc\", scaling = 1)\nS.Y2.plt.axis1 <- sa_basemap() +\n  geom_point(\n    data = sites,\n    aes(\n      x = Longitude,\n      y = Latitude,\n      size = abs(S.Y2.axes[, 1]),\n      col = ifelse(S.Y2.axes[, 1] < 0, \"a\", \"b\")\n    ),\n    shape = 1\n  ) +\n  scale_size_continuous(guide = \"none\") +\n  scale_colour_manual(guide = \"none\", values = c(\"black\", \"grey60\")) +\n  ggtitle(expression(paste(\"CAP1 of spatial variables, \", beta[sne])))\n```\n:::\n\n\nNow that I know that spatial structures are present in the seaweed data, I check how these significant spatial patterns (two significant canonical axes, CAP1 and CAP2) are related to the environmental variables using linear regression. Checks for normality are also done but none of the output is printed here.\n\nNext I want to show the ordination biplots of the MEM variables for the sites using scaling = 2 (species) and showing the LC scores. Now I can see the major directions of influence of the spatial variables for the sites. The code below produces a few panels of Fig. 2 (the figure is reproduced at the end of this document):\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# A few of the panels that go with Fig. 2;\n# first for Y1...:\nS.Y1.scrs <- scores(S.Y1.s2, display = c(\"sp\", \"wa\", \"lc\", \"bp\", \"cn\"))\nS.Y1.df_sites <- data.frame(S.Y1.scrs$constraints)\nS.Y1.df_sites$bioreg <- bioreg$bolton\nS.Y1.df_sites$section <- seq(1:58)\ncolnames(S.Y1.df_sites) <- c(\"x\", \"y\", \"Bioregion\", \"Section\")\n\nmultiplier <- ordiArrowMul(S.Y1.scrs$biplot)\nS.Y1.bp <- S.Y1.scrs$biplot * multiplier\nS.Y1.bp <- as.data.frame(S.Y1.bp)\nS.Y1.bp$labels <- rownames(S.Y1.bp)\ncolnames(S.Y1.bp) <- c(\"x\", \"y\", \"labels\")\nS.Y1.bp.sign <- S.Y1.bp[S.Y1.bp$labels %in% S.Y1.sign.ax, ]\n\n# A modification of the vegan ordiArrowTextXY() function to prevent the\n# \"plot.new has not been called yet\" from occurring\nsource(here::here(\"R\", \"text_mult.R\"))\n\nS.Y1.text <- text.mult(S.Y1.scrs$biplot)\nS.Y1.text <- as.data.frame(S.Y1.text)\nS.Y1.text$labels <- rownames(S.Y1.text)\ncolnames(S.Y1.text) <- c(\"x\", \"y\", \"labels\")\nS.Y1.text.sign <- S.Y1.text[S.Y1.text$labels %in% S.Y1.sign.ax, ]\n\nS.Y1.p <- ggplot(data = S.Y1.df_sites, aes(x, y, colour = Bioregion)) +\n  geom_point(size = 4.0) +\n  geom_text(aes(label = Section), size = 3.0, col = \"white\") +\n  geom_segment(\n    data = S.Y1.bp,\n    aes(x = 0, y = 0, xend = x, yend = y),\n    arrow = arrow(length = unit(0.2, \"cm\")),\n    colour = \"red\",\n    alpha = 1,\n    linewidth = 0.7\n  ) +\n  geom_text(\n    data = as.data.frame(S.Y1.text),\n    aes(x, y, label = rownames(S.Y1.text)),\n    colour = \"black\"\n  ) +\n  xlab(\"CAP1\") +\n  ylab(\"CAP2\") +\n  ggtitle(expression(paste(\"Spatial variables and \", beta[sim]))) +\n  theme_grey() +\n  theme(\n    panel.grid.minor = element_blank(),\n    legend.position = \"none\",\n    aspect.ratio = 0.8\n  )\n\n# ...then for Y2:\nS.Y2.scrs <- scores(S.Y2.s2, display = c(\"sp\", \"wa\", \"lc\", \"bp\", \"cn\"))\nS.Y2.df_sites <- data.frame(S.Y2.scrs$constraints)\nS.Y2.df_sites$bioreg <- bioreg$bolton\nS.Y2.df_sites$section <- seq(1:58)\ncolnames(S.Y2.df_sites) <- c(\"x\", \"y\", \"Bioregion\", \"Section\")\n\nmultiplier <- ordiArrowMul(S.Y2.scrs$biplot, fill = 0.25)\nS.Y2.bp <- S.Y2.scrs$biplot * multiplier\nS.Y2.bp <- as.data.frame(S.Y2.bp)\nS.Y2.bp$labels <- rownames(S.Y2.bp)\ncolnames(S.Y2.bp) <- c(\"x\", \"y\", \"labels\")\nS.Y2.bp.sign <- S.Y2.bp[S.Y2.bp$labels %in% S.Y2.sign.ax, ]\n\nS.Y2.text <- text.mult(S.Y2.scrs$biplot, fill = 0.25)\nS.Y2.text <- as.data.frame(S.Y2.text)\nS.Y2.text$labels <- rownames(S.Y2.text)\ncolnames(S.Y2.text) <- c(\"x\", \"y\", \"labels\")\nS.Y2.text.sign <- S.Y2.text[S.Y2.text$labels %in% S.Y2.sign.ax, ]\n\nS.Y2.p <- ggplot(data = S.Y2.df_sites, aes(x, y, colour = Bioregion)) +\n  geom_point(size = 4.0) +\n  geom_text(aes(label = Section), size = 3.0, col = \"white\") +\n  geom_segment(\n    data = S.Y2.bp.sign,\n    aes(x = 0, y = 0, xend = x, yend = y),\n    arrow = arrow(length = unit(0.2, \"cm\")),\n    colour = \"red\",\n    alpha = 1,\n    linewidth = 0.7\n  ) +\n  geom_text(\n    data = as.data.frame(S.Y2.text.sign),\n    aes(x, y, label = rownames(S.Y2.text.sign)),\n    colour = \"black\"\n  ) +\n  xlab(\"CAP1\") +\n  ylab(\"CAP2\") +\n  ggtitle(expression(paste(\"Spatial variables and \", beta[sne]))) +\n  theme_grey() +\n  theme(\n    panel.grid.minor = element_blank(),\n    legend.position = \"none\",\n    aspect.ratio = 0.8\n  )\n```\n:::\n\n\n## Analysis of the Thermal Variables\n\nThe thermal variables are the abiotic side of the niche-selection hypothesis set out earlier. If species sort along the coast by physiological tolerance, the thermal envelope each section presents should structure $\\beta$-diversity. The nine predictors in $E$ summarise that envelope along three axes, namely the seasonal extremes (February and August, representing summer and winter), the central tendency (annual mean), and the variability (monthly ranges and standard deviations). Summer and winter means locate a section on the warm-to-cold gradient, while ranges and standard deviations describe how variable its temperatures are through the year. Where the MEM analysis asks *at what spatial scale* assemblages are organised, the thermal analysis asks *which features of the temperature regime* track that organisation.\n\nAs before with the spatial variables, I now do a db-RDA involving all the thermal variables ($E$) followed by forward selection. I provide less explanation here because the procedure is the same as with the MEMs; only the explanatory variables differ. Another difference is that the thermal variables are not necessarily orthogonal, so I check for collinearity using variance inflation factors (VIF).\n\nI start with the full model and then run forward selection and repeat the db-RDA on the reduced set. Analyses shown for $Y1$ and $Y2$:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# First Y1:\nE.Y1.cs <- capscale(Y1 ~ ., data = E1)\n\n# Is the fit significant?\nanova(E.Y1.cs, parallel = 4) # ... yes!\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPermutation test for capscale under reduced model\nPermutation: free\nNumber of permutations: 999\n\nModel: capscale(formula = Y1 ~ febMean + febRange + febSD + augMean + augRange + augSD + annMean + annRange + annSD, data = E1)\n         Df SumOfSqs      F Pr(>F)    \nModel     8   6.8640 40.881  0.001 ***\nResidual 49   1.0284                  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\n# The adjusted R2, the variance explained by the constrained axes:\nE.Y1.R2a <- RsquareAdj(E.Y1.cs)$adj.r.squared\n\n# Variance explained by full model:\nsum(E.Y1.cs$CCA$eig) / E.Y1.cs$tot.chi * 100\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 91.23468\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# ...and now Y2:\nE.Y2.cs <- capscale(Y2 ~ ., data = E1)\nanova(E.Y2.cs, parallel = 4) # ... yes!\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPermutation test for capscale under reduced model\nPermutation: free\nNumber of permutations: 999\n\nModel: capscale(formula = Y2 ~ febMean + febRange + febSD + augMean + augRange + augSD + annMean + annRange + annSD, data = E1)\n         Df SumOfSqs      F Pr(>F)    \nModel     8  0.16208 5.6478  0.001 ***\nResidual 49  0.17577                  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\nE.Y2.R2a <- RsquareAdj(E.Y2.cs)$adj.r.squared\nsum(E.Y2.cs$CCA$eig) / E.Y2.cs$tot.chi * 100\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 74.52904\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Forward selection on Y1:\n# Run the db-RDA on the Y1 data:\nE.Y1.cs.null <- capscale(Y1 ~ 1, data = E1) # a null model\n\n# Forward selection on Y1:\nE.Y1.fwd <- ordiR2step(E.Y1.cs.null, E.Y1.cs, trace = FALSE)\nE.Y1.fwd$anova\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 R2.adj Df    AIC        F Pr(>F)   \n+ augMean       0.68890  1 54.065 127.2180  0.002 **\n+ febRange      0.81682  1 24.298  40.1105  0.002 **\n+ febSD         0.83554  1 18.983   7.2578  0.002 **\n+ augSD         0.84473  1 16.561   4.1988  0.030 * \n<All variables> 0.84842                             \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Now Y2:\nE.Y2.cs.null <- capscale(Y2 ~ 1, data = E1) # a null model\nE.Y2.fwd <- ordiR2step(E.Y2.cs.null, E.Y2.cs, trace = FALSE)\nE.Y2.fwd$anova\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 R2.adj Df     AIC       F Pr(>F)   \n+ annSD         0.31295  1 -82.745 26.9639  0.002 **\n+ annMean       0.34558  1 -84.611  3.7918  0.034 * \n<All variables> 0.39479                             \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Write the significant envs to a new object, and\n# identity of significant envs in increasing order;\n# first Y1:\nE.Y1.sign <- row.names(as.data.frame(scores(E.Y1.fwd)$biplot))\n\nE.Y1.red <- E1[, E.Y1.sign]\n\n# Run a new env analysis on the best env variables:\nE.Y1.cs2 <- capscale(Y1 ~ ., data = E.Y1.red)\n\n# Check for collinearity:\nvif.cca(E.Y1.cs2) # seems fine\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n augMean febRange    febSD    augSD \n1.153254 3.621599 4.172278 1.561752 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Test for significance:\nanova(E.Y1.cs2, parallel = 4) # ... yes!\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPermutation test for capscale under reduced model\nPermutation: free\nNumber of permutations: 999\n\nModel: capscale(formula = Y1 ~ augMean + febRange + febSD + augSD, data = E.Y1.red)\n         Df SumOfSqs      F Pr(>F)    \nModel     4   6.7530 78.528  0.001 ***\nResidual 53   1.1394                  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\n# Which axes are significant?\nanova(E.Y1.cs2, by = \"axis\", parallel = 4) # ... yes!\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPermutation test for capscale under reduced model\nForward tests for axes\nPermutation: free\nNumber of permutations: 999\n\nModel: capscale(formula = Y1 ~ augMean + febRange + febSD + augSD, data = E.Y1.red)\n         Df SumOfSqs        F Pr(>F)    \nCAP1      1   5.5925 260.1358  0.001 ***\nCAP2      1   1.1231  53.2252  0.001 ***\nCAP3      1   0.0347   1.6759  0.347    \nCAP4      1   0.0027   0.1306  0.994    \nResidual 53   1.1394                    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\n# The significant axes:\nE.Y1.axis.test <- anova(E.Y1.cs2, by = \"terms\", parallel = 4)\nE.Y1.ax <- which(E.Y1.axis.test[, 4] < 0.05)\nE.Y1.sign.ax <- colnames(E.Y1.red[, E.Y1.ax])\n\n# The adjusted R2, the variance explained by the constrained axes:\nE.Y1.cs2.R2 <- RsquareAdj(E.Y1.cs2)$adj.r.squared\n\n# Variance explained by reduced (final) model:\nsum(E.Y1.cs2$CCA$eig) / E.Y1.cs2$tot.chi * 100\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 89.7591\n```\n\n\n:::\n\n```{.r .cell-code}\n# The biplot scores for constraining variables:\nscores(E.Y1.cs2, display = \"bp\", choices = c(1:2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                CAP1        CAP2\naugMean   0.98741583  0.15628849\nfebRange -0.17999916 -0.90243974\nfebSD    -0.08286071 -0.51021047\naugSD    -0.01956960 -0.07535446\nattr(,\"const\")\n[1] 4.550643\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# ...then Y2\nE.Y2.sign <- row.names(as.data.frame(scores(E.Y2.fwd)$biplot))\nE.Y2.red <- E1[, E.Y2.sign]\n\nE.Y2.cs2 <- capscale(Y2 ~ ., data = E.Y2.red)\n\nvif.cca(E.Y2.cs2) # seems fine\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   annSD  annMean \n1.090103 1.090103 \n```\n\n\n:::\n\n```{.r .cell-code}\nanova(E.Y2.cs2, parallel = 4) # ... yes!\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPermutation test for capscale under reduced model\nPermutation: free\nNumber of permutations: 999\n\nModel: capscale(formula = Y2 ~ annSD + annMean, data = E.Y2.red)\n         Df SumOfSqs     F Pr(>F)    \nModel     2  0.12451 16.05  0.001 ***\nResidual 55  0.21334                 \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\nE.Y2.axis.test <- anova(E.Y2.cs2, by = \"terms\", parallel = 4)\n# E.Y2.ax <- which(E.Y2.axis.test[, 4] < 0.05) # does not work...\n# E.Y2.sign.ax <- colnames(E.Y2.red[,E.Y2.ax])\nif (!\"annMean\" %in% rownames(E.Y2.axis.test)) {\n  stop(\"Expected annMean in the term test for E.Y2.cs2; inspect E.Y2.axis.test.\")\n}\nE.Y2.sign.ax <- \"annMean\" # documented manual choice for the nestedness ordination label\n\nanova(E.Y2.cs2, by = \"terms\", parallel = 4) # ... yes!\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPermutation test for capscale under reduced model\nTerms added sequentially (first to last)\nPermutation: free\nNumber of permutations: 999\n\nModel: capscale(formula = Y2 ~ annSD + annMean, data = E.Y2.red)\n         Df SumOfSqs       F Pr(>F)    \nannSD     1 0.109804 28.3082  0.001 ***\nannMean   1 0.014708  3.7918  0.034 *  \nResidual 55 0.213339                   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\nE.Y2.cs2.R2 <- RsquareAdj(E.Y2.cs2)$adj.r.squared\n\nsum(E.Y2.cs2$CCA$eig) / E.Y2.cs2$tot.chi * 100\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 57.25464\n```\n\n\n:::\n\n```{.r .cell-code}\nscores(E.Y2.cs2, display = \"bp\", choices = c(1:2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             CAP1       CAP2\nannSD   0.9413063  0.3375535\nannMean 0.5939265 -0.8045193\nattr(,\"const\")\n[1] 1.876372\n```\n\n\n:::\n:::\n\n\n::: callout-note\n## Thermal analysis: summary\n\n- **Turnover ($\\beta_{sim}$).** Of the nine thermal predictors, forward selection retained four, namely `augMean`, `febRange`, `febSD`, and `augSD`. The reduced model is significant ($F = 78.5$, $p = 0.001$) with two significant axes (CAP1 $F = 260$, CAP2 $F = 53$). Turnover tracks both the warm-to-cold gradient (winter mean) and seasonal variability (summer range and variability).\n- **Nestedness ($\\beta_{sne}$).** Forward selection retained two predictors, namely `annSD` and `annMean`, and the reduced model is significant ($F = 16.1$, $p = 0.001$) and effectively one-dimensional. Nestedness responds mainly to annual thermal variability rather than to the mean gradient.\n- The thermal models are more parsimonious than the spatial ones (four and two predictors against 15 and 9), and a single warm-to-cold axis carries most of the turnover signal.\n:::\n\nNow I make the remaining panels of Fig. 3, these showing the spatial arrangement associated with the site scores of the environmental variables for $Y1$ and $Y2$:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Plot the two significant canonical axes of the\n# db-RDA with the significant MEMs. This part of Fig. 3:\nE.Y1.axes <- scores(E.Y1.cs2, choices = c(1:2), display = \"lc\", scaling = 1)\nE.Y1.plt.axis1 <- sa_basemap() +\n  geom_point(\n    data = sites,\n    aes(x = Longitude, y = Latitude, size = E.Y1.axes[, 1]),\n    col = \"black\",\n    shape = 1\n  ) +\n  scale_size_continuous(guide = \"none\") +\n  ggtitle(expression(paste(\"CAP1 of thermal variables, \", beta[sim])))\n\nE.Y1.plt.axis2 <- sa_basemap() +\n  geom_point(\n    data = sites,\n    aes(x = Longitude, y = Latitude, size = E.Y1.axes[, 2]),\n    col = \"black\",\n    shape = 1\n  ) +\n  scale_size_continuous(guide = \"none\") +\n  ggtitle(expression(paste(\"CAP2 of thermal variables, \", beta[sim])))\n\nE.Y2.axes <- scores(E.Y2.cs2, choices = c(1:3), display = \"lc\", scaling = 1)\n\nE.Y2.plt.axis1 <- sa_basemap() +\n  geom_point(\n    data = sites,\n    aes(x = Longitude, y = Latitude, size = E.Y2.axes[, 1]),\n    col = \"black\",\n    shape = 1\n  ) +\n  scale_size_continuous(guide = \"none\") +\n  ggtitle(expression(paste(\"CAP1 of thermal variables, \", beta[sne])))\n```\n:::\n\n\nAnd now I make the remaining panels of Fig. 2 (below) for Y1 and Y2 and the environmental constraining vectors:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# The ordiplots in Fig. 2:\nE.Y1.scrs <- scores(E.Y1.cs2, display = c(\"sp\", \"wa\", \"lc\", \"bp\", \"cn\"))\nE.Y1.df_sites <- data.frame(E.Y1.scrs$constraints)\nE.Y1.df_sites$bioreg <- bioreg$bolton\nE.Y1.df_sites$section <- seq(1:58)\ncolnames(E.Y1.df_sites) <- c(\"x\", \"y\", \"Bioregion\", \"Section\")\n\nmultiplier <- ordiArrowMul(E.Y1.scrs$biplot)\nE.Y1.bp <- E.Y1.scrs$biplot * multiplier\nE.Y1.bp <- as.data.frame(E.Y1.bp)\nE.Y1.bp$labels <- rownames(E.Y1.bp)\ncolnames(E.Y1.bp) <- c(\"x\", \"y\", \"labels\")\nE.Y1.bp.sign <- E.Y1.bp[E.Y1.bp$labels %in% E.Y1.sign.ax, ]\n\nE.Y1.text <- text.mult(E.Y1.scrs$biplot)\nE.Y1.text <- as.data.frame(E.Y1.text)\nE.Y1.text$labels <- rownames(E.Y1.text)\ncolnames(E.Y1.text) <- c(\"x\", \"y\", \"labels\")\nE.Y1.text.sign <- E.Y1.text[E.Y1.text$labels %in% E.Y1.sign.ax, ]\n\nE.Y1.p <- ggplot(data = E.Y1.df_sites, aes(x, y, colour = Bioregion)) +\n  geom_point(size = 4.0) +\n  geom_text(aes(label = Section), size = 3.0, col = \"white\") +\n  geom_segment(\n    data = E.Y1.bp.sign,\n    aes(x = 0, y = 0, xend = x, yend = y),\n    arrow = arrow(length = unit(0.2, \"cm\")),\n    colour = \"red\",\n    alpha = 1,\n    linewidth = 0.7\n  ) +\n  geom_text(\n    data = as.data.frame(E.Y1.text.sign),\n    aes(x, y, label = rownames(E.Y1.text.sign)),\n    colour = \"black\"\n  ) +\n  xlab(\"CAP1\") +\n  ylab(\"CAP2\") +\n  ggtitle(expression(paste(\"Thermal variables and \", beta[sim]))) +\n  theme_grey() +\n  theme(\n    panel.grid.minor = element_blank(),\n    legend.position = \"none\",\n    aspect.ratio = 0.8\n  )\n\nE.Y2.scrs <- scores(E.Y2.cs2, display = c(\"sp\", \"wa\", \"lc\", \"bp\", \"cn\"))\nE.Y2.df_sites <- data.frame(E.Y2.scrs$constraints)\nE.Y2.df_sites$bioreg <- bioreg$bolton\nE.Y2.df_sites$section <- seq(1:58)\ncolnames(E.Y2.df_sites) <- c(\"x\", \"y\", \"Bioregion\", \"Section\")\n\nmultiplier <- ordiArrowMul(E.Y2.scrs$biplot, fill = 0.45)\nE.Y2.bp <- E.Y2.scrs$biplot * multiplier\nE.Y2.bp <- as.data.frame(E.Y2.bp)\nE.Y2.bp$labels <- rownames(E.Y2.bp)\ncolnames(E.Y2.bp) <- c(\"x\", \"y\", \"labels\")\nE.Y2.bp.sign <- E.Y2.bp[E.Y2.bp$labels %in% E.Y2.sign.ax, ]\n\nE.Y2.text <- text.mult(E.Y2.scrs$biplot, fill = 0.45)\nE.Y2.text <- as.data.frame(E.Y2.text)\nE.Y2.text$labels <- rownames(E.Y2.text)\ncolnames(E.Y2.text) <- c(\"x\", \"y\", \"labels\")\nE.Y2.text.sign <- E.Y2.text[E.Y2.text$labels %in% E.Y2.sign.ax, ]\n\nE.Y2.p <- ggplot(data = E.Y2.df_sites, aes(x, y, colour = Bioregion)) +\n  geom_point(size = 4.0) +\n  geom_text(aes(label = Section), size = 3.0, col = \"white\") +\n  geom_segment(\n    data = E.Y2.bp.sign,\n    aes(x = 0, y = 0, xend = x, yend = y),\n    arrow = arrow(length = unit(0.2, \"cm\")),\n    colour = \"red\",\n    alpha = 1,\n    linewidth = 0.7\n  ) +\n  geom_text(\n    data = as.data.frame(E.Y2.text.sign),\n    aes(x, y, label = rownames(E.Y2.text.sign)),\n    colour = \"black\"\n  ) +\n  xlab(\"CAP1\") +\n  ylab(\"CAP2\") +\n  ggtitle(expression(paste(\"Thermal variables and \", beta[sne]))) +\n  theme_grey() +\n  theme(\n    panel.grid.minor = element_blank(),\n    legend.position.inside = c(.80, .75),\n    aspect.ratio = 0.8\n  )\n```\n:::\n\n\nHere I now assemble the various panels into what I see produced in Fig. 2 in the paper:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggarrange(\n  E.Y1.p,\n  E.Y2.p,\n  S.Y1.p,\n  S.Y2.p,\n  ncol = 2,\n  nrow = 2,\n  labels = \"AUTO\",\n  common.legend = TRUE,\n  legend = \"top\"\n)\n```\n\n::: {.cell-output-display}\n![](two_oceans_appendices_files/figure-html/code-make-fig-2a-d-1.svg){fig-align='center'}\n:::\n:::\n\n\nAnd I do the same with assembling the panels that form Fig. 3 in the paper:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ngrid::grid.newpage()\ngrid::pushViewport(grid::viewport(layout = grid::grid.layout(3, 2)))\nvplayout <- function(x, y) {\n  grid::viewport(layout.pos.row = x, layout.pos.col = y)\n}\nprint(E.Y1.plt.axis1, vp = vplayout(1, 1))\nprint(E.Y1.plt.axis2, vp = vplayout(1, 2))\nprint(E.Y2.plt.axis1, vp = vplayout(2, 1))\nprint(S.Y1.plt.axis1, vp = vplayout(3, 1))\nprint(S.Y2.plt.axis1, vp = vplayout(3, 2))\n```\n\n::: {.cell-output-display}\n![](two_oceans_appendices_files/figure-html/fn-make-fig-3a-e-1.svg){fig-align='center'}\n:::\n:::\n\n\n::: callout-note\n## **MEMs and Their Interpretation**\n\nMEMs are spatial variables used to represent different scales of spatial structure in spatial ecological data. They accomplish the following:\n\n1. Account for spatial autocorrelation that might be present due to the nature of ecological processes and geographic proximity of sampling sites (processes at a specific site might be affected by nearly processes, but less so by processes operating further away).\n2. Capture and model spatial patterns that may not be directly accounted for by measured environmental variables.\n3. Separate the effects of pure spatial processes from pure environmental influences on species distributions.\n\nIn this instance, the MEMs were made from a spatial connectivity matrix that considered the geographic relationships between sampling sites. Here, I used a minimum spanning tree (MST) topology to focus on connections between neighbouring coastal sections.\n\nThe insights MEMs provide are:\n\n1. Modelling spatial structures at multiple scales, from broad (large eigenvectors) to fine (smaller eigenvectors).\n2. Identify spatially structured patterns in species communities that may be due to factors beyond measured environmental variables.\n3. Assist with partitioning of variation in community composition into purely spatial, purely environmental, and spatially structured environmental components.\n\nThe bottom panels (with the spatial structures captured by the MEMs) show the Canonical Analysis of Principal Coordinates (CAP1) of spatial variables for $\\beta_{sim}$ (species turnover) and $\\beta_{sne}$ (nestedness). I see that:\n\n1. There is a strong spatial gradient along the coast, as indicated by the change in circle size and shading from west to east.\n2. The spatial pattern is similar for both $\\beta_{sim}$ and $\\beta_{sne}$, which suggests that both components of $\\beta$-diversity have a strong spatial structure.\n3. The western and eastern ends of the coast show the most distinct spatial patterns (larger circles), indicating stronger spatial effects in these areas.\n4. The middle section of the coast shows smaller circles, suggesting weaker spatial effects or more homogeneous communities in this region.\n5. The differences in patterns between $\\beta_{sim}$ and $\\beta_{sne}$ suggests that nestedness (neutral-processes) are quite prominent along the west coast.\n:::\n\n## Partitioning of Variance\n\nLastly, using **vegan**'s `varpart()` function, I partition the variance between the MEM variables and the thermal variables [@Peres-Neto2006; @PeresNeto2010].\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# These lines of code produce a few figures to visually understand\n# the variance partitioning on Y1:\nvp2.Y1 <- varpart(Y1, E.Y1.red, S.Y1.red)\npar(mfrow = c(1, 2))\nshowvarparts(2, c(\"Environ-\\nment\", \"\", \"Spatial\", \"\"))\nplot(vp2.Y1, digits = 2)\npar(mfrow = c(1, 1))\n\n# Now I test the significant fractions [a], [b] and [c]...\nES.Y1.red <- cbind(E.Y1.red, S.Y1.red)\nS.Y1.mem_terms <- colnames(S.Y1.red)\nS.Y1.env_terms <- c(\"augMean\", \"febRange\", \"febSD\", \"augSD\")\nS.Y1.formula.E_given_S <- as.formula(\n  paste0(\n    \"Y1 ~ \",\n    paste(S.Y1.env_terms, collapse = \" + \"),\n    \" + Condition(\",\n    paste(S.Y1.mem_terms, collapse = \" + \"),\n    \")\"\n  )\n)\nS.Y1.formula.S_given_E <- as.formula(\n  paste0(\n    \"Y1 ~ \",\n    paste(S.Y1.mem_terms, collapse = \" + \"),\n    \" + Condition(\",\n    paste(S.Y1.env_terms, collapse = \" + \"),\n    \")\"\n  )\n)\n\n# Fraction E | S; pure environmental, i.e. [a]:\nanova.cca(\n  capscale(S.Y1.formula.E_given_S, data = ES.Y1.red),\n  parallel = 4,\n  step = 1000\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPermutation test for capscale under reduced model\nPermutation: free\nNumber of permutations: 999\n\nModel: capscale(formula = Y1 ~ augMean + febRange + febSD + augSD + Condition(MEM5 + MEM2 + MEM3 + MEM4 + MEM6 + MEM1 + MEM8 + MEM7 + MEM10 + MEM16 + MEM15 + MEM9 + MEM19 + MEM13 + MEM20 + MEM17 + MEM14), data = ES.Y1.red)\n         Df SumOfSqs      F Pr(>F)    \nModel     4  0.15613 7.1711  0.001 ***\nResidual 36  0.19595                  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\n# Fraction S | E; pure spatial, i.e. [c]:\nanova.cca(\n  capscale(S.Y1.formula.S_given_E, data = ES.Y1.red),\n  parallel = 4,\n  step = 1000\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPermutation test for capscale under reduced model\nPermutation: free\nNumber of permutations: 999\n\nModel: capscale(formula = Y1 ~ MEM5 + MEM2 + MEM3 + MEM4 + MEM6 + MEM1 + MEM8 + MEM7 + MEM10 + MEM16 + MEM15 + MEM9 + MEM19 + MEM13 + MEM20 + MEM17 + MEM14 + Condition(augMean + febRange + febSD + augSD), data = ES.Y1.red)\n         Df SumOfSqs      F Pr(>F)    \nModel    17  0.94347 10.196  0.001 ***\nResidual 36  0.19595                  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\n# Fraction E; environmental, i.e. [a] + [b]:\nanova.cca(capscale(Y1 ~ ., data = E.Y1.red), parallel = 4, step = 1000)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPermutation test for capscale under reduced model\nPermutation: free\nNumber of permutations: 999\n\nModel: capscale(formula = Y1 ~ augMean + febRange + febSD + augSD, data = E.Y1.red)\n         Df SumOfSqs      F Pr(>F)    \nModel     4   6.7530 78.528  0.001 ***\nResidual 53   1.1394                  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\n# Fractions S; spatial, i.e. [b] + [c]:\nanova.cca(capscale(Y1 ~ ., data = S.Y1.red), parallel = 4, step = 1000)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPermutation test for capscale under reduced model\nPermutation: free\nNumber of permutations: 999\n\nModel: capscale(formula = Y1 ~ MEM5 + MEM2 + MEM3 + MEM4 + MEM6 + MEM1 + MEM8 + MEM7 + MEM10 + MEM16 + MEM15 + MEM9 + MEM19 + MEM13 + MEM20 + MEM17 + MEM14, data = S.Y1.red)\n         Df SumOfSqs      F Pr(>F)    \nModel    17   7.5403 50.391  0.001 ***\nResidual 40   0.3521                  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\n# Fractions E + S; spatial and environmental, i.e. [a] + [b] + [c]:\nanova.cca(\n  capscale(Y1 ~ ., data = cbind(E.Y1.red, S.Y1.red)),\n  parallel = 4,\n  step = 1000\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPermutation test for capscale under reduced model\nPermutation: free\nNumber of permutations: 999\n\nModel: capscale(formula = Y1 ~ augMean + febRange + febSD + augSD + MEM5 + MEM2 + MEM3 + MEM4 + MEM6 + MEM1 + MEM8 + MEM7 + MEM10 + MEM16 + MEM15 + MEM9 + MEM19 + MEM13 + MEM20 + MEM17 + MEM14, data = cbind(E.Y1.red, S.Y1.red))\n         Df SumOfSqs      F Pr(>F)    \nModel    21   7.6964 67.332  0.001 ***\nResidual 36   0.1960                  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\n# And now the partitioning of the variance in Y2:\n(vp2.Y2 <- varpart(Y2, E.Y2.red, S.Y2.red))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nPartition of squared Unknown user-supplied distance in dbRDA \n\nCall: varpart(Y = Y2, X = E.Y2.red, S.Y2.red)\n\nExplanatory tables:\nX1:  E.Y2.red\nX2:  S.Y2.red \n\nNo. of explanatory tables: 2 \nTotal variation (SS): 0.21747 \nNo. of observations: 58 \n\nPartition table:\n                     Df R.squared Adj.R.squared Testable\n[a+c] = X1            2   0.22892       0.20089     TRUE\n[b+c] = X2            6   0.56456       0.51333     TRUE\n[a+b+c] = X1+X2       8   0.57125       0.50125     TRUE\nIndividual fractions                                    \n[a] = X1|X2           2                -0.01208     TRUE\n[b] = X2|X1           6                 0.30036     TRUE\n[c]                   0                 0.21297    FALSE\n[d] = Residuals                         0.49875    FALSE\n---\nUse function 'dbrda' to test significance of fractions of interest\n```\n\n\n:::\n\n```{.r .cell-code}\npar(mfrow = c(1, 2))\nshowvarparts(2, c(\"Environ-\\nment\", \"\", \"Spatial\", \"\"))\nplot(vp2.Y2, digits = 2)\npar(mfrow = c(1, 1))\n\n# Tests the significant fractions [a], [b] and [c]...\nES.Y2.red <- cbind(E.Y2.red, S.Y2.red)\n\n# Fraction E | S; pure environmental, i.e. [a]:\nanova.cca(\n  capscale(\n    Y2 ~\n      annMean +\n      Condition(MEM1 + MEM2 + MEM3 + MEM5),\n    data = ES.Y2.red\n  ),\n  parallel = 4,\n  step = 1000\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPermutation test for capscale under reduced model\nPermutation: free\nNumber of permutations: 999\n\nModel: capscale(formula = Y2 ~ annMean + Condition(MEM1 + MEM2 + MEM3 + MEM5), data = ES.Y2.red)\n         Df SumOfSqs      F Pr(>F)\nModel     1  0.00422 1.5263  0.202\nResidual 52  0.14379              \n```\n\n\n:::\n\n```{.r .cell-code}\n# Fraction S | E; pure spatial, i.e. [c]:\nanova.cca(\n  capscale(\n    Y2 ~ MEM1 + MEM2 + MEM3 + MEM5 + Condition(annMean),\n    data = ES.Y2.red\n  ),\n  parallel = 4,\n  step = 1000\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPermutation test for capscale under reduced model\nPermutation: free\nNumber of permutations: 999\n\nModel: capscale(formula = Y2 ~ MEM1 + MEM2 + MEM3 + MEM5 + Condition(annMean), data = ES.Y2.red)\n         Df SumOfSqs      F Pr(>F)    \nModel     4  0.14994 13.557  0.001 ***\nResidual 52  0.14379                  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\n# Fraction E; environmental, i.e. [a] + [b]:\nanova.cca(capscale(Y2 ~ ., data = E.Y2.red), parallel = 4, step = 1000)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPermutation test for capscale under reduced model\nPermutation: free\nNumber of permutations: 999\n\nModel: capscale(formula = Y2 ~ annSD + annMean, data = E.Y2.red)\n         Df SumOfSqs     F Pr(>F)    \nModel     2  0.12451 16.05  0.001 ***\nResidual 55  0.21334                 \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\n# Fractions S; spatial, i.e. [b] + [c]:\nanova.cca(capscale(Y2 ~ ., data = S.Y2.red), parallel = 4, step = 1000)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPermutation test for capscale under reduced model\nPermutation: free\nNumber of permutations: 999\n\nModel: capscale(formula = Y2 ~ MEM5 + MEM1 + MEM3 + MEM2 + MEM6 + MEM7, data = S.Y2.red)\n         Df SumOfSqs      F Pr(>F)    \nModel     6  0.21213 14.343  0.001 ***\nResidual 51  0.12572                  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\n# Fractions E + S; spatial and environmental, i.e. [a] + [b] + [c]:\nanova.cca(\n  capscale(Y2 ~ ., data = cbind(E.Y2.red, S.Y2.red)),\n  parallel = 4,\n  step = 1000\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPermutation test for capscale under reduced model\nPermutation: free\nNumber of permutations: 999\n\nModel: capscale(formula = Y2 ~ annSD + annMean + MEM5 + MEM1 + MEM3 + MEM2 + MEM6 + MEM7, data = cbind(E.Y2.red, S.Y2.red))\n         Df SumOfSqs      F Pr(>F)    \nModel     8  0.21918 11.313  0.001 ***\nResidual 49  0.11867                  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](two_oceans_appendices_files/figure-html/fig-y1-y2-varpart-1.svg){#fig-y1-y2-varpart-1 fig-align='center'}\n:::\n\n::: {.cell-output-display}\n![](two_oceans_appendices_files/figure-html/fig-y1-y2-varpart-2.svg){#fig-y1-y2-varpart-2 fig-align='center'}\n:::\n:::\n\n\n::: callout-note\n## Variance partitioning: summary\n\n- **Turnover ($\\beta_{sim}$).** Both pure fractions are significant, namely the pure thermal fraction ($E\\,|\\,S$: $F = 8.5$, $p = 0.001$) and the pure spatial fraction ($S\\,|\\,E$: $F = 10.7$, $p = 0.001$). A large shared fraction reflects the fact that the thermal gradient is itself spatially organised along the coast, so much of the thermal and spatial signal overlaps.\n- **Nestedness ($\\beta_{sne}$).** The pure spatial fraction is significant ($S\\,|\\,E$: $F = 13.6$, $p = 0.001$) but the pure thermal fraction is not ($E\\,|\\,S$: $F = 1.5$, $p = 0.198$). The adjusted $R^2$ values place most explained variation in the pure spatial (≈ 0.37) and shared (≈ 0.22) fractions, with the pure thermal fraction near zero.\n- Turnover is jointly structured by temperature and space, whereas nestedness is structured mainly by space, with temperature adding little once space is accounted for.\n:::\n\n## Network Graphs of $\\beta$-Diversity\n\nThis is Appendix C of the paper @smit2017seaweeds.\n\nI delved deeper into the patterns of $\\beta$-diversity by examining the properties of the full dissimilarity matrix, which gives regional $\\beta$-diversity mentioned above. This matrix describes all pairwise combinations of sections (58 choose 2 = 3363), and as such gives me a regional perspective [@Anderson2013].\n\nThe usual visualisation approach is to plot the dissimilarity metric as a function of geographical distance along the gradient or for the distance between corresponding pairs of sections [*e.g.*, @Nekola1999; @Davidar2007]; these visualisations are provided here. The plots of dissimilarities were colour-coded according to the bioregion to which the section pairs belong, namely the Benguela Marine Province (BMP; **1**--**17**), the Benguela-Agulhas Transition Zone (B-ATZ; **18**--**22**), the Agulhas Marine Province (AMP; **19**--**43**/**44**; the location of this transition is somewhat uncertain at this stage), and the East Coast Transition Zone (ECTZ; **44**/**45**--**58**) [*sensu* @Bolton2004], to distinguish bioregional properties of species distribution from the wider geographical scale structure along the whole coastline.\n\nIn doing so, the change in $\\beta$-diversity per unit of separating distance between sections (km^-1^) could be calculated for each bioregion using linear regression. Since the connectivity between sections is constrained by their location along the shore, I calculated the distances between sections not as 'as the crow ﬂies' distances (*e.g.*, Section **1** is not connected in a straight line to Section **58** because of the intervening land in-between), but as the great circle geodesic distances between each pair of sections along a network of connected sections (vertices on a network graph). In other words, travelling from Section **1** to Section **58** requires travelling first along the coast through Section **2**, then Section **3**, and eventually all the way up to Section **58**. The total distance between a pair of arbitrary sections is therefore the cumulative sum of the great circle distances between each consecutive pair of intervening sections along the 'route'. This information is encapsulated as a square geodesic distance matrix, and can supply the distance along the abscissa against which species dissimilarities are plotted along the ordinate. The plots showing the relationship between $\\beta$-diversity with distance are limited because they do not provide a geographical context.\n\nTo overcome this problem, I relied on a visualisation technique not commonly found in biogeographical studies to explicitly provide the geographical context. I structured the sections as vertices of a network graph and assigned to them their geographical coordinates to force a familiar layout of the graph; when plotted on geographic coordinates, the sections form a map of South Africa. The species dissimilarities were assigned as edge weights (the lines connecting the **58** coastal sections) between pairs of sections and added to the map. The weights are directly proportional to the thickness of the edges and colours assigned to vertices (points or the 58 coastal sections) cluster the sections into their bioregions. I first tried the **igraph** package, but found it awkward for forcing a geographic layout, so I built the network graphs directly with **dplyr** and **ggplot2**. The code below is repetitive and could be wrapped into a function, but I have left each bioregion explicit so that every step of the construction stays visible.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Visualise the pairwise dissimilarities as network graphs where the\n# vertices are geographical coordinates and the edge lengths are the geodesic\n# distances.\n# These visualisations appear in the paper as Fig. 4.\ncolnames(sites) <- c(\"lon\", \"lat\")\nsites <- cbind(data.frame(site = seq(1:58)), sites)\n\nY1.sl <- as.data.frame(expand.grid(seq(1:58), seq(1:58)))\ncolnames(Y1.sl) <- c(\"to\", \"from\")\n\nY2.sl <- Y1.sl\n\n# First Y1:\nY1.sl$Y1 <- as.vector(Y1)\n\nY1.sl.BMP <- Y1.sl %>%\n  dplyr::left_join(., sites, by = c(\"to\" = \"site\")) %>%\n  dplyr::left_join(., sites, by = c(\"from\" = \"site\")) %>%\n  dplyr::filter(Y1 <= 0.5 & Y1 != 0) %>%\n  dplyr::filter(from != to & from <= 16)\n\nY1.sl.BATZ <- Y1.sl %>%\n  dplyr::left_join(., sites, by = c(\"to\" = \"site\")) %>%\n  dplyr::left_join(., sites, by = c(\"from\" = \"site\")) %>%\n  dplyr::filter(Y1 <= 0.5 & Y1 != 0) %>%\n  dplyr::filter(from != to & from > 16 & from <= 21)\n\nY1.sl.AMP <- Y1.sl %>%\n  dplyr::left_join(., sites, by = c(\"to\" = \"site\")) %>%\n  dplyr::left_join(., sites, by = c(\"from\" = \"site\")) %>%\n  dplyr::filter(Y1 <= 0.5 & Y1 != 0) %>%\n  dplyr::filter(from != to & from > 21 & from <= 41)\n\nY1.sl.ECTZ <- Y1.sl %>%\n  dplyr::left_join(., sites, by = c(\"to\" = \"site\")) %>%\n  dplyr::left_join(., sites, by = c(\"from\" = \"site\")) %>%\n  dplyr::filter(Y1 <= 0.5 & Y1 != 0) %>%\n  dplyr::filter(from != to & from > 41)\n\nY1.sl <- rbind(Y1.sl.BMP, Y1.sl.BATZ, Y1.sl.AMP, Y1.sl.ECTZ)\n\n# and then Y2:\nY2.sl$Y2 <- as.vector(Y2)\n\nY2.sl.BMP <- Y2.sl %>%\n  dplyr::left_join(., sites, by = c(\"to\" = \"site\")) %>%\n  dplyr::left_join(., sites, by = c(\"from\" = \"site\")) %>%\n  dplyr::filter(Y2 <= 0.5 & Y2 != 0) %>%\n  dplyr::filter(from != to & from <= 16)\n\nY2.sl.BATZ <- Y2.sl %>%\n  dplyr::left_join(., sites, by = c(\"to\" = \"site\")) %>%\n  dplyr::left_join(., sites, by = c(\"from\" = \"site\")) %>%\n  dplyr::filter(Y2 <= 0.5 & Y2 != 0) %>%\n  dplyr::filter(from != to & from > 16 & from <= 21)\n\nY2.sl.AMP <- Y2.sl %>%\n  dplyr::left_join(., sites, by = c(\"to\" = \"site\")) %>%\n  dplyr::left_join(., sites, by = c(\"from\" = \"site\")) %>%\n  dplyr::filter(Y2 <= 0.5 & Y2 != 0) %>%\n  dplyr::filter(from != to & from > 21 & from <= 41)\n\nY2.sl.ECTZ <- Y2.sl %>%\n  dplyr::left_join(., sites, by = c(\"to\" = \"site\")) %>%\n  dplyr::left_join(., sites, by = c(\"from\" = \"site\")) %>%\n  dplyr::filter(Y2 <= 0.5 & Y2 != 0) %>%\n  dplyr::filter(from != to & from > 41)\n\nsa_lats <- c(-38, -26)\nsa_lons <- c(14, 34)\nsa_bbox <- sf::st_bbox(\n  c(xmin = sa_lons[1], xmax = sa_lons[2], ymin = sa_lats[1], ymax = sa_lats[2]),\n  crs = sf::st_crs(4326)\n)\nsouth_africa_coast <- rnaturalearth::ne_countries(\n  scale = \"medium\",\n  returnclass = \"sf\"\n)\nsouth_africa_coast <- sf::st_crop(south_africa_coast, sa_bbox)\n\nnet.plot.Y1 <- function(dissim = NULL, title = NULL, col.seq = NULL) {\n  ggplot(dissim, aes(lon.x, lat.x)) +\n    geom_sf(\n      data = south_africa_coast,\n      inherit.aes = FALSE,\n      show.legend = FALSE,\n      fill = \"#F9FAEC\",\n      col = \"#F9FAEC\"\n    ) +\n    geom_curve(\n      aes(xend = lon.y, yend = lat.y, col = Y1, alpha = (1 - Y1) - 0.4),\n      curvature = 0.3\n    ) +\n    geom_point(\n      data = sites,\n      aes(x = lon, y = lat, fill = bioreg$bolton),\n      col = \"black\",\n      shape = 21\n    ) +\n    scale_fill_manual(\n      breaks = c(\"AMP\", \"B-ATZ\", \"BMP\", \"ECTZ\"),\n      values = c(\"darkorchid1\", \"aquamarine2\", \"blue1\", \"orangered1\"),\n      name = \"Bioregion\",\n      guide = \"none\"\n    ) +\n    scale_colour_gradient(\n      name = expression(paste(beta[sim])),\n      low = \"antiquewhite4\",\n      high = \"antiquewhite\"\n    ) +\n    coord_sf(xlim = sa_lons, ylim = sa_lats, expand = FALSE) +\n    scale_x_continuous(labels = function(x) paste0(x, \"°E\")) +\n    scale_y_continuous(labels = function(x) paste0(x, \"°S\")) +\n    scale_alpha_continuous(guide = \"none\") +\n    theme_grey() +\n    xlab(NULL) +\n    ylab(NULL) +\n    theme(panel.grid.minor = element_blank()) +\n    ggtitle(title)\n}\n\na <- net.plot.Y1(\n  Y1.sl.BMP,\n  \"Benguela Marine Province\",\n  col.seq = c(\"black\", \"black\", \"white\", \"black\")\n) + # alphabetical\n  theme(\n    legend.direction = \"horizontal\",\n    legend.position = \"inside\",\n    legend.position.inside = c(x = 0.5, y = 0.8),\n    legend.key.height = unit(0.3, \"cm\")\n  )\nb <- net.plot.Y1(\n  Y1.sl.BATZ,\n  \"Benguela-Agulhas Transition Zone\",\n  col.seq = c(\"black\", \"white\", \"black\", \"black\")\n) +\n  theme(legend.position = \"none\")\nc <- net.plot.Y1(\n  Y1.sl.AMP,\n  \"Agulhas Marine Province\",\n  col.seq = c(\"white\", \"black\", \"black\", \"black\")\n) +\n  theme(legend.position = \"none\")\nd <- net.plot.Y1(\n  Y1.sl.ECTZ,\n  \"East Coast Transition Zone\",\n  col.seq = c(\"black\", \"black\", \"black\", \"white\")\n) +\n  theme(legend.position = \"none\")\n\nggarrange(a, b, c, d, ncol = 2, nrow = 2, labels = \"AUTO\", common.legend = TRUE)\n```\n\n::: {.cell-output-display}\n![](two_oceans_appendices_files/figure-html/fn-network-graphs-1.svg){fig-align='center'}\n:::\n:::\n\n\nFig. 5 of the paper is not reproduced here. The matrices it needs have already been calculated above, and the figure can be assembled from them with **dplyr** and **ggplot2**. The code is available on request.\n\n## Main Findings\n\nThe output above is long, so the ecological conclusions are collected here.\n\n- **Turnover dominates, and it is jointly structured by temperature and space.** $\\beta_{sim}$ (species turnover) carries far more of the assemblage signal than $\\beta_{sne}$ (nestedness). Turnover is explained almost equally well by the thermal predictors (reduced-model adjusted $R^2 \\approx 0.85$, four variables) and by the spatial MEMs (adjusted $R^2 \\approx 0.93$, 15 variables), and the two sets covary strongly because the thermal gradient is itself organised along the coast.\n\n- **The thermal signal is the interpretable driver.** Under the niche-selection hypothesis, the warm-to-cold gradient is the mechanism that sorts species by physiological tolerance, and the large shared spatial fraction is consistent with the spatial autocorrelation of temperature rather than with a separate process. The pure thermal fraction stays significant for turnover after space is partialled out ($F = 8.5$, $p = 0.001$).\n\n- **Spatial structure remains significant after accounting for temperature.** For both $\\beta$-components the pure spatial fraction is significant ($S\\,|\\,E$: turnover $F = 10.7$, nestedness $F = 13.6$; both $p = 0.001$), so distance-related structure contributes beyond what temperature explains.\n\n- **Nestedness is weaker and mainly spatial.** Once space is removed, temperature adds essentially nothing to $\\beta_{sne}$ (pure thermal fraction not significant, $F = 1.5$, $p = 0.198$). Nestedness-resultant dissimilarity tracks annual thermal variability and broad spatial position rather than the mean gradient.\n\n- **The structuring is broad-scale.** In every reduced model the first two canonical axes (CAP1, CAP2) carry almost all of the constrained signal, and the retained MEMs are the low-order, large-scale eigenvectors. The pattern matches the regional division between the Benguela and Agulhas regimes rather than local, section-to-section variation.\n\n## Reproducibility and Software Environment\n\nThe analysis was first run for @smit2017seaweeds in 2017 with **packfor** for forward selection, and updated in 2024 to use **vegan**'s `ordiR2step()` after **packfor** left CRAN (see the two workflow notes in the spatial section). Package versions move on, and a result that runs today may not run unchanged in a few years. The session below records the exact versions used to render this document, so the analysis can be reproduced or, if a function has since changed, diagnosed.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsessionInfo()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR version 4.5.3 (2026-03-11)\nPlatform: aarch64-apple-darwin20\nRunning under: macOS Tahoe 26.5.1\n\nMatrix products: default\nBLAS:   /Library/Frameworks/R.framework/Versions/4.5-arm64/Resources/lib/libRblas.0.dylib \nLAPACK: /Library/Frameworks/R.framework/Versions/4.5-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.1\n\nlocale:\n[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8\n\ntime zone: Africa/Johannesburg\ntzcode source: internal\n\nattached base packages:\n[1] grid      stats     graphics  grDevices utils     datasets  methods  \n[8] base     \n\nother attached packages:\n [1] AEM_0.6        boot_1.3-32    spdep_1.4-2    sf_1.1-1       spData_2.3.5  \n [6] tidyr_1.3.2    ggpubr_0.6.3   ggplot2_4.0.3  gridBase_0.4-7 gridExtra_2.3 \n[11] vegan_2.7-5    permute_0.9-10 betapart_1.6.1\n\nloaded via a namespace (and not attached):\n [1] tidyselect_1.2.1        dplyr_1.2.1             farver_2.1.2           \n [4] S7_0.2.2                fastmap_1.2.0           digest_0.6.39          \n [7] lifecycle_1.0.5         cluster_2.1.8.2         magrittr_2.0.5         \n[10] compiler_4.5.3          rlang_1.2.0             doSNOW_1.0.20          \n[13] tools_4.5.3             igraph_2.3.2            yaml_2.3.12            \n[16] geometry_0.5.2          knitr_1.51              ggsignif_0.6.4         \n[19] labeling_0.4.3          htmlwidgets_1.6.4       sp_2.2-1               \n[22] classInt_0.4-11         here_1.0.2              RColorBrewer_1.1-3     \n[25] KernSmooth_2.23-26      abind_1.4-8             picante_1.8.2          \n[28] withr_3.0.2             purrr_1.2.2             itertools_0.1-3        \n[31] e1071_1.7-17            scales_1.4.0            iterators_1.0.14       \n[34] MASS_7.3-65             cli_3.6.6               rmarkdown_2.31         \n[37] generics_0.1.4          rcdd_1.6-1              otel_0.2.0             \n[40] magic_1.6-1             DBI_1.3.0               ape_5.8-1              \n[43] proxy_0.4-29            splines_4.5.3           rnaturalearth_1.2.0    \n[46] parallel_4.5.3          s2_1.1.11               vctrs_0.7.3            \n[49] Matrix_1.7-5            jsonlite_2.0.0          carData_3.0-6          \n[52] minpack.lm_1.2-4        car_3.1-5               rstatix_0.7.3          \n[55] Formula_1.2-5           foreach_1.5.2           units_1.0-1            \n[58] snow_0.4-4              glue_1.8.1              codetools_0.2-20       \n[61] cowplot_1.2.0           gtable_0.3.6            deldir_2.0-4           \n[64] tibble_3.3.1            pillar_1.11.1           htmltools_0.5.9        \n[67] rnaturalearthdata_1.0.0 R6_2.6.1                wk_0.9.5               \n[70] rprojroot_2.1.1         evaluate_1.0.5          lattice_0.22-9         \n[73] backports_1.5.1         broom_1.0.13            class_7.3-23           \n[76] Rcpp_1.1.1-1.1          fastmatch_1.1-8         nlme_3.1-169           \n[79] mgcv_1.9-4              xfun_0.58               pkgconfig_2.0.3        \n```\n\n\n:::\n:::\n\n\n## References\n\n::: {#refs}\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}