{
  "hash": "31947207d818be7cb417312949edd2df",
  "result": {
    "engine": "knitr",
    "markdown": "---\ndate: last-modified\ndate-format: \"YYYY/MM/DD\"\ntitle: \"8. ANOVA\"\nsubtitle: \"Comparing the Means of More than Two Groups\"\nreference-location: margin\n---\n\n\n::: {.cell}\n\n:::\n\n\n![A meme about fancy statistics.](../../images/fancy_stats.jpg){fig-align=\"center\" width=\"250\"}\n\n> *\"He uses statistics as a drunken man uses lamp posts --- for support rather than for illumination.\"*\n>\n> --- Marissa Mayer\n\n\n::: {.cell}\n\n:::\n\n\n::: {.callout-note appearance=\"simple\"}\n## In This Chapter\n\n-   one-way ANOVA\n-   Tukey HSD\n-   factorial ANOVA\n-   Welch's one-way ANOVA\n-   Kruskal-Wallis rank-sum test\n:::\n\n::: {.callout-note appearance=\"simple\"}\n## Cheatsheet\nFind here a [Cheatsheet](../../docs/Methods_cheatsheet_v1.pdf) on statistical methods.\n:::\n\n::: {.callout-important appearance=\"simple\"}\n## Tasks to Complete in This Chapter\n\n-   Task G\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchicks <- as_tibble(ChickWeight)\nchicks_day21 <- filter(chicks, Time == 21)\n```\n:::\n\n\n# Introduction\n\nANOVA extends the comparison-of-means idea from [Chapter 7](07-t_tests.qmd) to more than two groups. The question changes from \"do these two means differ?\" to \"do these group means all come from the same population mean?\" The response variable is still continuous. The predictor is still categorical. But now we have more than two groups.\n\nAlthough ANOVA is also a linear model with categorical predictors, this chapter keeps the discussion at the grouped-data level. The later regression chapters, especially [Chapter 11](11-simple-linear-regression.qmd) and [Chapter 13](13-multiple-regression-and-model-specification.qmd), make the linear-model connection explicit and introduce residual-based diagnostics in that context.\n\n# Why Not Do Multiple *t*-Tests?\n\nThe first impulse with several groups is often to compare every pair with a separate *t*-test. That is the wrong decision. Each additional test creates another opportunity for a false positive, so the overall Type I error rate rises as the number of pairwise comparisons increases.\n\nIn the `chicks` data we have four diets. Pairwise testing would require six null hypotheses:\n\n$$H_{0}: \\mu_1 = \\mu_2$$\n$$H_{0}: \\mu_1 = \\mu_3$$\n$$H_{0}: \\mu_1 = \\mu_4$$\n$$H_{0}: \\mu_2 = \\mu_3$$\n$$H_{0}: \\mu_2 = \\mu_4$$\n$$H_{0}: \\mu_3 = \\mu_4$$\n\nWith each repeated test, the probability of rejecting at least one true null hypothesis increases.\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {#tbl-kbl-results-long-digits .cell tbl-cap='Probability of at least one Type I error when all pairwise *t*-tests are run among *K* groups.'}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"zpzphebvda\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#zpzphebvda table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#zpzphebvda thead, #zpzphebvda tbody, #zpzphebvda tfoot, #zpzphebvda tr, #zpzphebvda td, #zpzphebvda th {\n  border-style: none;\n}\n\n#zpzphebvda p {\n  margin: 0;\n  padding: 0;\n}\n\n#zpzphebvda .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#zpzphebvda .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#zpzphebvda .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#zpzphebvda .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#zpzphebvda .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#zpzphebvda .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#zpzphebvda .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#zpzphebvda .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#zpzphebvda .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#zpzphebvda .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#zpzphebvda .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#zpzphebvda .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#zpzphebvda .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#zpzphebvda .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#zpzphebvda .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#zpzphebvda .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#zpzphebvda .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#zpzphebvda .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#zpzphebvda .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zpzphebvda .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#zpzphebvda .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#zpzphebvda .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#zpzphebvda .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zpzphebvda .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#zpzphebvda .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#zpzphebvda .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#zpzphebvda .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zpzphebvda .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#zpzphebvda .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#zpzphebvda .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#zpzphebvda .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#zpzphebvda .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#zpzphebvda .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zpzphebvda .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#zpzphebvda .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zpzphebvda .gt_left {\n  text-align: left;\n}\n\n#zpzphebvda .gt_center {\n  text-align: center;\n}\n\n#zpzphebvda .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#zpzphebvda .gt_font_normal {\n  font-weight: normal;\n}\n\n#zpzphebvda .gt_font_bold {\n  font-weight: bold;\n}\n\n#zpzphebvda .gt_font_italic {\n  font-style: italic;\n}\n\n#zpzphebvda .gt_super {\n  font-size: 65%;\n}\n\n#zpzphebvda .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#zpzphebvda .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#zpzphebvda .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#zpzphebvda .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#zpzphebvda .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#zpzphebvda .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#zpzphebvda .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#zpzphebvda .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#zpzphebvda div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"K\">K</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"a0.2\">0.2</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"a0.1\">0.1</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"a0.05\">0.05</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"a0.02\">0.02</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"a0.01\">0.01</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"a0.001\">0.001</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"K\" class=\"gt_row gt_right\">2</td>\n<td headers=\"0.2\" class=\"gt_row gt_right\">0.20</td>\n<td headers=\"0.1\" class=\"gt_row gt_right\">0.10</td>\n<td headers=\"0.05\" class=\"gt_row gt_right\">0.05</td>\n<td headers=\"0.02\" class=\"gt_row gt_right\">0.02</td>\n<td headers=\"0.01\" class=\"gt_row gt_right\">0.01</td>\n<td headers=\"0.001\" class=\"gt_row gt_right\">0.00</td></tr>\n    <tr><td headers=\"K\" class=\"gt_row gt_right\">3</td>\n<td headers=\"0.2\" class=\"gt_row gt_right\">0.49</td>\n<td headers=\"0.1\" class=\"gt_row gt_right\">0.27</td>\n<td headers=\"0.05\" class=\"gt_row gt_right\">0.14</td>\n<td headers=\"0.02\" class=\"gt_row gt_right\">0.06</td>\n<td headers=\"0.01\" class=\"gt_row gt_right\">0.03</td>\n<td headers=\"0.001\" class=\"gt_row gt_right\">0.00</td></tr>\n    <tr><td headers=\"K\" class=\"gt_row gt_right\">4</td>\n<td headers=\"0.2\" class=\"gt_row gt_right\">0.74</td>\n<td headers=\"0.1\" class=\"gt_row gt_right\">0.47</td>\n<td headers=\"0.05\" class=\"gt_row gt_right\">0.26</td>\n<td headers=\"0.02\" class=\"gt_row gt_right\">0.11</td>\n<td headers=\"0.01\" class=\"gt_row gt_right\">0.06</td>\n<td headers=\"0.001\" class=\"gt_row gt_right\">0.01</td></tr>\n    <tr><td headers=\"K\" class=\"gt_row gt_right\">5</td>\n<td headers=\"0.2\" class=\"gt_row gt_right\">0.89</td>\n<td headers=\"0.1\" class=\"gt_row gt_right\">0.65</td>\n<td headers=\"0.05\" class=\"gt_row gt_right\">0.40</td>\n<td headers=\"0.02\" class=\"gt_row gt_right\">0.18</td>\n<td headers=\"0.01\" class=\"gt_row gt_right\">0.10</td>\n<td headers=\"0.001\" class=\"gt_row gt_right\">0.01</td></tr>\n    <tr><td headers=\"K\" class=\"gt_row gt_right\">10</td>\n<td headers=\"0.2\" class=\"gt_row gt_right\">1.00</td>\n<td headers=\"0.1\" class=\"gt_row gt_right\">0.99</td>\n<td headers=\"0.05\" class=\"gt_row gt_right\">0.90</td>\n<td headers=\"0.02\" class=\"gt_row gt_right\">0.60</td>\n<td headers=\"0.01\" class=\"gt_row gt_right\">0.36</td>\n<td headers=\"0.001\" class=\"gt_row gt_right\">0.04</td></tr>\n    <tr><td headers=\"K\" class=\"gt_row gt_right\">20</td>\n<td headers=\"0.2\" class=\"gt_row gt_right\">1.00</td>\n<td headers=\"0.1\" class=\"gt_row gt_right\">1.00</td>\n<td headers=\"0.05\" class=\"gt_row gt_right\">1.00</td>\n<td headers=\"0.02\" class=\"gt_row gt_right\">0.98</td>\n<td headers=\"0.01\" class=\"gt_row gt_right\">0.85</td>\n<td headers=\"0.001\" class=\"gt_row gt_right\">0.17</td></tr>\n    <tr><td headers=\"K\" class=\"gt_row gt_right\">100</td>\n<td headers=\"0.2\" class=\"gt_row gt_right\">1.00</td>\n<td headers=\"0.1\" class=\"gt_row gt_right\">1.00</td>\n<td headers=\"0.05\" class=\"gt_row gt_right\">1.00</td>\n<td headers=\"0.02\" class=\"gt_row gt_right\">1.00</td>\n<td headers=\"0.01\" class=\"gt_row gt_right\">1.00</td>\n<td headers=\"0.001\" class=\"gt_row gt_right\">0.99</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\nANOVA solves that problem by asking one global question first:\n\n$$H_{0}: \\mu_1 = \\mu_2 = \\mu_3 = \\dots = \\mu_k$$\n$$H_{a}: \\text{not all group means are equal}$$\n\nIf the global null hypothesis is rejected, we then ask which groups differ. That second step belongs to a post hoc procedure such as Tukey's HSD.\n\n:::: {.callout-important}\n## Task G.1: Do It Now!\nWhy is one global ANOVA preferable to six separate *t*-tests in the four-diet chick example?\n::::\n\n::: {.callout-note appearance=\"simple\"}\n## Bonferroni Correction\n\nShould you insist on doing multiple *t*-tests, Bonferroni correction divides the significance threshold by the number of tests. It reduces the false-positive rate, but it can become very conservative. The better solution, when the scientific question concerns several group means at once, is to fit the appropriate multi-group model, such as an ANOVA, rather than correct a stack of pairwise *t*-tests after the fact.\n:::\n\n# How ANOVA Partitions Variation\n\nANOVA answers the global question by partitioning the total variation in the response into two components:\n\n-   variation among the group means;\n-   variation within the groups.\n\nIf the group means differ more than we would expect from within-group variation alone, the ANOVA result becomes large enough to reject $H_0$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngrand_mean <- mean(chicks_day21$weight)\n\nggplot(chicks_day21, aes(Diet, weight)) +\n  geom_jitter(width = 0.08, alpha = 0.5, size = 1.5, colour = \"grey40\") +\n  stat_summary(fun = mean, geom = \"point\", size = 2.8, colour = \"red4\") +\n  geom_hline(yintercept = grand_mean, colour = \"dodgerblue3\", linetype = 2, linewidth = 0.7) +\n  labs(x = \"Diet\", y = \"Chick mass (g)\")\n```\n\n::: {.cell-output-display}\n![Visual intuition for ANOVA. The dashed blue line is the grand mean. The red points are the diet means. Distance from the red points to the blue line contributes to between-group variation. Distance from observations to their group mean contributes to within-group variation.](08-anova_files/figure-html/fig-anova-decomposition-1.svg){#fig-anova-decomposition}\n:::\n:::\n\n\n::: {.callout-note collapse=\"true\" appearance=\"simple\"}\n## Mathematical Detail\n\nSuppose there are $k$ groups, $Y_{ij}$ is the $j$-th observation in group $i$, $\\bar{Y}_i$ is the mean of group $i$, and $\\bar{Y}$ is the grand mean.\n\n$$SS_{\\text{total}} = SS_{\\text{among}} + SS_{\\text{within}}$$ {#eq-anova-ss}\n\nThe total sum of squares is:\n\n$$SS_{\\text{total}} = \\sum_{i=1}^{k}\\sum_{j=1}^{n_i}(Y_{ij} - \\bar{Y})^2$$ {#eq-anova-sstotal}\n\nThe among-groups sum of squares is:\n\n$$SS_{\\text{among}} = \\sum_{i=1}^{k} n_i(\\bar{Y}_i - \\bar{Y})^2$$ {#eq-anova-ssamong}\n\nThe within-groups sum of squares is:\n\n$$SS_{\\text{within}} = \\sum_{i=1}^{k}\\sum_{j=1}^{n_i}(Y_{ij} - \\bar{Y}_i)^2$$ {#eq-anova-sswithin}\n\nANOVA converts these to mean squares:\n\n$$MS_{\\text{among}} = \\frac{SS_{\\text{among}}}{k - 1}, \\qquad MS_{\\text{within}} = \\frac{SS_{\\text{within}}}{N - k}$$ {#eq-anova-ms}\n\nand compares them with the *F*-ratio:\n\n$$F = \\frac{MS_{\\text{among}}}{MS_{\\text{within}}}$$ {#eq-anova-f}\n\nLarge *F* values indicate that the group means differ more than we would expect from within-group variation alone.\n:::\n\n# Data Structure and Decision Rule\n\nUse a one-way ANOVA when:\n\n-   the response variable is continuous;\n-   the predictor is categorical with three or more independent levels;\n-   the observations are independent;\n-   the within-group distributions are reasonably well behaved.\n\nUse this decision rule:\n\n-   if the group spreads are similar, use classical one-way ANOVA with `aov()`;\n-   if the group spreads differ clearly, use Welch's one-way ANOVA with `oneway.test()`;\n-   if the data are strongly non-normal and a rank-based comparison is more defensible, use Kruskal-Wallis with `kruskal.test()`.\n\nBoxplots with jitter are the first EDA tool to use here. Look for:\n\n-   separation in group centres;\n-   large differences in spread;\n-   outliers that dominate one group;\n-   shapes that suggest strong skewness.\n\nLater regression chapters revisit these same issues through residuals. In this chapter the checks remain at the grouped raw-data level.\n\n::: {.callout-note appearance=\"simple\"}\n## About Homogeneity Tests\n\nYou've heard this before: Levene's test and Bartlett's test are supporting tools, not the main decision pathway. Visual comparison of spread comes first. If the group spreads differ substantially, switch to Welch's ANOVA rather than treating a non-significant homogeneity test as permission to ignore the problem.\n:::\n\n# R Functions\n\nThe main functions used in this chapter are:\n\n-   `aov()` for classical ANOVA;\n-   `summary()` for the ANOVA table;\n-   `TukeyHSD()` for post hoc pairwise comparisons;\n-   `oneway.test()` for Welch's one-way ANOVA;\n-   `kruskal.test()` for the Kruskal-Wallis rank-sum test.\n\n# Example 1: Chick Masses Under Four Diets\n\nAt Day 21, do chicks fed four diets differ in mean body mass?\n\nThe hypotheses are:\n\n$$H_{0}: \\mu_1 = \\mu_2 = \\mu_3 = \\mu_4$$\n$$H_{a}: \\text{not all group means are equal}$$\n\n## The One-Way Design\n\nThis is a one-way design because there is one grouping variable, `Diet`, with four levels. The response variable is chick mass.\n\n## Do an Exploratory Data Analysis (EDA)\n\nBegin with a boxplot and jittered points so that the distribution within each diet is visible.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(chicks_day21, aes(x = Diet, y = weight)) +\n  geom_boxplot(\n    width = 0.6,\n    fill = \"grey85\",\n    colour = \"black\",\n    outlier.shape = NA\n  ) +\n  geom_jitter(width = 0.08, alpha = 0.5, size = 1.5, colour = \"grey40\") +\n  stat_summary(\n    fun = mean,\n    geom = \"point\",\n    size = 2.5,\n    colour = \"black\"\n  ) +\n  stat_summary(\n    fun.data = mean_sdl,\n    fun.args = list(mult = 1),\n    geom = \"errorbar\",\n    width = 0.12,\n    linewidth = 0.5,\n    colour = \"black\"\n  ) +\n  labs(x = \"Diet\", y = \"Chick mass (g)\")\n```\n\n::: {.cell-output-display}\n![Boxplot and jittered observations for chick mass at Day 21 under four diets. Black points show the diet means and the vertical bars show one standard deviation above and below each mean.](08-anova_files/figure-html/fig-boxwhisker2-1.svg){#fig-boxwhisker2}\n:::\n:::\n\n\nThe plot suggests that Diet 3 has the largest mean mass and Diet 1 the smallest. The spreads are not identical, but they are similar enough that a classical one-way ANOVA is plausible.\n\nWe can support that visual judgement with grouped summaries and a homogeneity test.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchicks_day21 |>\n  group_by(Diet) |>\n  dplyr::summarise(\n    n = dplyr::n(),\n    mean = mean(weight),\n    sd = sd(weight),\n    shapiro_p = shapiro.test(weight)$p.value,\n    .groups = \"drop\"\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 5\n  Diet      n  mean    sd shapiro_p\n  <fct> <int> <dbl> <dbl>     <dbl>\n1 1        16  178.  58.7     0.591\n2 2        10  215.  78.1     0.949\n3 3        10  270.  71.6     0.895\n4 4         9  239.  43.3     0.186\n```\n\n\n:::\n\n```{.r .cell-code}\ncar::leveneTest(weight ~ Diet, data = chicks_day21)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLevene's Test for Homogeneity of Variance (center = median)\n      Df F value Pr(>F)\ngroup  3  1.1597 0.3367\n      41               \n```\n\n\n:::\n:::\n\n\nThe Shapiro-Wilk tests show no strong evidence against normality within any diet at Day 21, and Levene's test shows no strong evidence that the spreads differ. So, there is no strong reason to not apply an ANOVA.\n\n## Apply the Test\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchicks_aov1 <- aov(weight ~ Diet, data = chicks_day21)\nsummary(chicks_aov1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Df Sum Sq Mean Sq F value  Pr(>F)   \nDiet         3  57164   19055   4.655 0.00686 **\nResiduals   41 167839    4094                   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nThe ANOVA table answers the global question only. A significant result means that at least one diet mean differs from at least one other diet mean.\n\n:::: {.callout-important}\n## Task G.2: Do It Now!\na. What does the ANOVA result say about chick masses at Day 21?\nb. Which part of the result is global, and which part still needs a follow-up test?\n::::\n\n## Identify Which Groups Differ\n\nOnce there is enough evidence to no longer accept the global null hypothesis, use Tukey's HSD to identify the pairwise differences while controlling the family-wise error rate.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nTukeyHSD(chicks_aov1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Tukey multiple comparisons of means\n    95% family-wise confidence level\n\nFit: aov(formula = weight ~ Diet, data = chicks_day21)\n\n$Diet\n         diff        lwr       upr     p adj\n2-1  36.95000  -32.11064 106.01064 0.4868095\n3-1  92.55000   23.48936 161.61064 0.0046959\n4-1  60.80556  -10.57710 132.18821 0.1192661\n3-2  55.60000  -21.01591 132.21591 0.2263918\n4-2  23.85556  -54.85981 102.57092 0.8486781\n4-3 -31.74444 -110.45981  46.97092 0.7036249\n```\n\n\n:::\n:::\n\n\nEach row in the Tukey output is one pairwise comparison. The `diff` column is the estimated mean difference between the two diets. The `lwr` and `upr` columns give the confidence interval for that difference. If the confidence interval does not cross zero, the two diets differ at the chosen family-wise confidence level. If the interval includes zero, the data do not support a clear difference for that pair. The `p adj` column gives the multiplicity-adjusted *p*-value for the same comparison.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(TukeyHSD(chicks_aov1))\n```\n\n::: {.cell-output-display}\n![Tukey HSD comparisons among the four chick diets at Day 21.](08-anova_files/figure-html/fig-tukeydiff-1.svg){#fig-tukeydiff}\n:::\n:::\n\n\n## Interpret the Results\n\nThe global ANOVA is significant, so we reject $H_0$ and conclude that diet explains some of the variation in chick mass at Day 21. The clearest pairwise difference is between Diet 1 and Diet 3. Diet 3 chicks are about 92.6 g heavier on average than Diet 1 chicks.\n\nThe observed diet means are 177.8 g, 214.7 g, 270.3 g, and 238.6 g. Those differences are not all the same size, and the Tukey step shows that only some of them are large enough relative to within-diet variation to be declared significant.\n\nThe overall effect size is also worth reporting. For this ANOVA, about 25% of the variation in Day 21 chick mass is associated with diet ($\\eta^2 \\approx 0.25$).\n\n## Reporting\n\n::: {.callout-note appearance=\"simple\"}\n## Write-Up\n\n**Methods**\n\nChick mass at Day 21 was compared among four diet treatments with a one-way ANOVA. The grouped distributions were inspected with boxplots and summary statistics, and group spread was checked before fitting the model. Tukey's HSD procedure was then used for post hoc pairwise comparisons.\n\n**Results**\n\nAt Day 21, mean chick mass differed among diets (one-way ANOVA: $F_{3,41} = 4.66$, $p < 0.01$). Chicks fed Diet 1 had a mean mass of 177.8 g (SD = 58.7), compared with 214.7 g (SD = 78.1) for Diet 2, 270.3 g (SD = 71.6) for Diet 3, and 238.6 g (SD = 43.3) for Diet 4. Tukey's HSD showed that the clearest pairwise difference was between Diet 1 and Diet 3 ($p < 0.01$), with Diet 3 chicks heavier by 92.6 g on average. Diet accounted for about 25% of the variation in chick mass at Day 21 ($\\eta^2 \\approx 0.25$).\n\n**Discussion**\n\nThe post hoc structure shows selective diet differences rather than universal separation among all four diet means. The global ANOVA detects structure among the means; Tukey's HSD identifies where that structure lies.\n:::\n\n:::: {.callout-important}\n## Task G.3: Do It Now!\na. Why can the ANOVA be significant even though not every Tukey comparison is significant?\nb. Produce a `ggplot2` version of the Tukey result.\n::::\n\n# Factorial ANOVA\n\nSo far, there has been one grouping variable only. We now extend the same idea to more than one factor.\n\nIn the `ChickWeight` data, diet is not the only categorical structure. Time also changes chick mass. That gives two distinct questions:\n\n-   what is the effect of diet?\n-   does the effect of diet change through time?\n\n## A Detour We Should Avoid\n\nOne tempting approach is to run a separate one-way ANOVA at each time point. That repeats the same multiple-testing problem that motivated ANOVA in the first place.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntimes <- c(0, 2, 10, 21)\np_values <- numeric(length(times))\n\nfor (i in seq_along(times)) {\n  time_data <- filter(chicks, Time == times[i])\n  fit <- aov(weight ~ Diet, data = time_data)\n  p_values[i] <- summary(fit)[[1]][[\"Pr(>F)\"]][1]\n}\n\ntime_scan <- data.frame(\n  Time = times,\n  p_value = p_values\n)\n\ntime_scan\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Time      p_value\n1    0 0.3459145928\n2    2 0.0055475424\n3   10 0.0009891053\n4   21 0.0068579588\n```\n\n\n:::\n:::\n\n\nThe results are interpretable, but our method was less than ideal (and not to mention, also repetitive). Each time point gets its own ANOVA, and the family-wise error rate rises again. Separate ANOVAs across time repeat the same multiple-testing problem as separate *t*-tests across diets.\n\n:::: {.callout-important}\n## Task G.4: Do It Now!\nWhat does the `time_scan` table suggest about when diet differences become visible, and why is that table still not the clean final analysis?\n::::\n\n## Two Factors in One Model\n\nA two-way ANOVA brings diet and time into the same model. Below, `Time` is converted to a factor because the question is about distinct sampling times.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchicks_two_way <- filter(chicks, Time %in% c(0, 21)) |>\n  mutate(Time = factor(Time))\n\nsummary(aov(weight ~ Diet + Time, data = chicks_two_way))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Df Sum Sq Mean Sq F value  Pr(>F)    \nDiet         3  39595   13198   5.987 0.00091 ***\nTime         1 734353  734353 333.120 < 2e-16 ***\nResiduals   90 198402    2204                    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nThis additive model asks whether diet and time each have an effect on chick mass, assuming that the diet effect is the same at both time points.\n\n## Interaction in Factorial ANOVA\n\nIf the effect of diet changes with time, the additive model is too simple. We then include an interaction term:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(aov(weight ~ Diet * Time, data = chicks_two_way))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Df Sum Sq Mean Sq F value   Pr(>F)    \nDiet         3  39595   13198   6.839 0.000343 ***\nTime         1 734353  734353 380.521  < 2e-16 ***\nDiet:Time    3  30504   10168   5.269 0.002187 ** \nResiduals   87 167898    1930                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nThe interaction asks whether diet-related differences are the same at Time 0 and Time 21. Stated differently, does the effect of diet change depending on when we sample the chicks? In this subset, yes, it depends. The interaction term is significant, so the effect of diet depends on time.\n\nThis chapter introduces interaction in ANOVA form only. [Chapter 14](14-interaction-effects.qmd) develops the interpretation of interactions in much more detail.\n\n:::: {.callout-important}\n## Task G.5: Do It Now!\na. What does the interaction term mean biologically in this chick example?\nb. Why do we lose information if we fit only separate one-way ANOVAs across time?\n::::\n\n# If Assumptions Fail {#sec-alt}\n\nThe one-way alternatives are:\n\n-   use classical ANOVA when the group spreads are similar and the grouped distributions are reasonably well behaved;\n-   use Welch's ANOVA when the main problem is unequal spread across groups;\n-   use Kruskal-Wallis when a rank-based one-way comparison is more defensible;\n-   switch to a different model when the real issue is dependence, repeated measurement, or a non-Gaussian response structure.\n\n## Welch's One-Way ANOVA\n\nWelch's ANOVA keeps the same one-way comparison-of-means question but does not assume equal variances.\n\n\n::: {.cell}\n\n```{.r .cell-code}\noneway.test(weight ~ Diet, data = chicks_day21)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne-way analysis of means (not assuming equal variances)\n\ndata:  weight and Diet\nF = 4.6618, num df = 3.000, denom df = 20.594, p-value = 0.01219\n```\n\n\n:::\n:::\n\n\nThe interpretation is the same as for classical one-way ANOVA: does at least one group mean differ? The difference is that Welch's test does not pool the within-group variances into one common estimate.\n\n## Kruskal-Wallis Rank-Sum Test\n\nIf the response is too badly behaved for a mean-based one-way ANOVA, Kruskal-Wallis is the standard one-way rank-based alternative.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkruskal.test(weight ~ Diet, data = chicks_day21)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tKruskal-Wallis rank sum test\n\ndata:  weight by Diet\nKruskal-Wallis chi-squared = 10.585, df = 3, p-value = 0.0142\n```\n\n\n:::\n:::\n\n\nAs with one-way ANOVA, a significant Kruskal-Wallis result is global. It tells us that the groups do not all occupy the same part of the rank distribution, but it does not identify which groups differ.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npairwise.wilcox.test(\n  x = chicks_day21$weight,\n  g = chicks_day21$Diet,\n  p.adjust.method = \"holm\"\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPairwise comparisons using Wilcoxon rank sum test with continuity correction \n\ndata:  chicks_day21$weight and chicks_day21$Diet \n\n  1     2     3    \n2 0.616 -     -    \n3 0.026 0.573 -    \n4 0.126 0.616 0.616\n\nP value adjustment method: holm \n```\n\n\n:::\n:::\n\n\nKruskal-Wallis is a one-way method. There is no direct two-way Kruskal-Wallis counterpart that plays the same introductory role for factorial designs. Once the design includes multiple factors, the analysis needs a different modelling strategy rather than a simple rank-based extension of the one-way test.\n\n\n\n# What This Chapter Does Not Cover\n\n-   **ANCOVA** is a linear model with a factor and a continuous covariate. It belongs in [Chapter 13](13-multiple-regression-and-model-specification.qmd), where factors and covariates are treated within the same model.\n-   **Repeated-measures, blocked, or within-individual designs** are dependence problems. Those belong in [Chapter 18](18-dependence-and-mixed-models.qmd).\n-   **Multifactor rank-based procedures** are not a clean introductory counterpart to factorial ANOVA. Once the design reaches that level, it is usually better to rethink the modelling approach directly.\n\n# Conclusion\n\nANOVA is the multi-group extension of the mean-comparison questions introduced with *t*-tests. The sequence is straightforward: recognise when repeated pairwise testing is inappropriate, ask one global question, inspect the grouped data, fit the model, and then use a post hoc procedure only if the global null hypothesis has been rejected.\n\nThe one-way case gives the foundation. Factorial ANOVA adds more than one categorical predictor. Later chapters connect this grouped-data view of ANOVA to the broader linear-model family.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}