{
  "hash": "e767ee4008c3e17829823aea018656f8",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"BCB744 Intro R Example 2\"\nformat: html\nparams: \n  hide_answers: true\n---\n\n\n::: {.cell}\n\n:::\n\n\nBelow is an example of a test or exam question similar to those you may encounter in the BCB744 Intro R module.\n\nThis is a practice exercise. While I will not assess your script, I will provide a rubric to guide your self-evaluation. You are expected to complete the task within the allocated time, submit your script to iKamva by the deadline. This allows me to track participation and I have reason to believe that engagement with these practice tasks correlates with improved performance in the final exam --- a hypothesis supported by prior observations.\n\nFor your own benefit, I strongly encourage you to work independently. Doing so will ensure that you develop the problem-solving skills necessary for success in the final assessment.\n\n[**Due date:** Thursday, 13 March 2025, 17:00.]{.my-highlight}\n\n\n# Question 1\n\n**The `datasets::UKDriverDeaths` and `datasets::Seatbelts` datasets**\n\nThese datasets are meant to be used together --- `UKDriverDeaths` has the same data as is provided in the variable `drivers` in `seatbelts`, but it also provides information about the temporal structure of the `Seatbelts` dataset. You will have to devise a way to use this temporal information in your analysis.\n\n* Produce a dataframe that combines the temporal information provided in `UKDriverDeaths` with the other information in `Seatbelts`.\n* Produce a faceted graph (using `facet_wrap()`, placing `drivers`, `front`, `rear`, `VanKilled` in facets) showing a timeline of monthly means of deaths (means taken across years) whilst distinguishing between the two levels of `law`.\n* What do you conclude from your analysis?\n\n::: {.content-hidden}\n\n**Answer**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\ndeaths <- datasets::UKDriverDeaths\nseatbelts <- datasets::Seatbelts\n\n# checking the data (not necessary)\nplot(deaths)\nplot(seatbelts)\n\n# make the combined dataframe\ndf <- data.frame(date = seq.Date(as.Date(\"1969-01-01\"), as.Date(\"1984-12-01\"), by = \"month\"),\n                 as.matrix(seatbelts))\n\n# make long dataframe\ndf |>\n  select(-DriversKilled, -kms, -PetrolPrice) |>\n  pivot_longer(cols = c(drivers, front, rear, VanKilled),\n               names_to = \"type\",\n               values_to = \"killed\") |>\n  mutate(year = year(date)) |>\n  group_by(year, type, law) |>\n  summarise(mean_killed = round(mean(killed), 2), .groups = \"drop\") |>\n  ggplot(aes(x = year, y = mean_killed)) +\n    geom_line(colour = \"grey70\") +\n    geom_point(aes(colour = as.factor(law)), size = 0.3) +\n    facet_wrap(~type, ncol = 2, scales = \"free\") +\n    guides(colour = guide_legend(\"Law\")) +\n    theme_minimal() +\n    labs(x = \"Year\", y = \"Mean deaths (count)\",\n         title = \"UK Car Driver and Passenger Deaths\",\n         subtitle = \"Jan 1969 to Dec 1984\")\n```\n\n::: {.cell-output-display}\n![Monthly seatbelt deaths by law and type (faceted time series).](BCB744_Intro_R_Example_2_files/figure-html/fig-library-tidyverse-1.svg){#fig-library-tidyverse-1 width=75%}\n:::\n\n::: {.cell-output-display}\n![Monthly seatbelt deaths by law and type (faceted time series).](BCB744_Intro_R_Example_2_files/figure-html/fig-library-tidyverse-2.svg){#fig-library-tidyverse-2 width=75%}\n:::\n\n::: {.cell-output-display}\n![Monthly seatbelt deaths by law and type (faceted time series).](BCB744_Intro_R_Example_2_files/figure-html/fig-library-tidyverse-3.svg){#fig-library-tidyverse-3 width=75%}\n:::\n:::\n\n\nThe data indicate that mandatory the seatbelt law, introduced on January 31, 1983, appears to have reduced the number of deaths resulting from car crashes for drivers, front passengers of passenger cars and for the drivers of vans. However, there was no apparent reduction in deaths for rear passengers, likely because the law requiring them to wear seatbelts did not come into effect until 1991.\n\nIt should be noted, however, that the interpretation of these results is not entirely clear. From 1969 to December 1982, there was a consistent reduction in deaths, which may have been due to other advancements in car safety features, road safety legislation. Additionally and only two data points are available following the introduction of mandatory seatbelt laws in 1983, and more data are needed to determine whether this reduction was statistically significant. Nevertheless, it is worth noting that the reduction did prove to be statistically significant.\n\n:::\n\n# Question 2\n\nPlease use the **nycflights13** package for this exercise.\n\n## 2.a\nWhat are the 10 most common destinations for flights from NYC airports\nin 2013, and what is the total distance travelled to each of these\nairports? Make a 2-panel figure and display these data graphically.\n\n::: {.content-hidden}\n\n**Answer**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggpubr)\nlibrary(nycflights13)\n\ntab1 <- flights %>%\n  group_by(dest) %>%  \n  summarise(n = n(),\n            total_distance = sum(distance)) %>% \n  arrange(desc(n)) %>%\n  slice(1:10)\n\nplt1 <- ggplot(tab1) +\n  geom_col(aes(x = dest, y = n), fill = \"grey90\", alpha = 0.7,\n           colour = \"indianred\") +\n  theme_minimal() +\n  labs(x = \"Airport code\",\n       y = \"Number of\\ndestimations\")\nplt2 <- ggplot(tab1) +\n  geom_col(aes(x = dest, y = total_distance * 0.621371), # convert to km\n           fill = \"grey90\", alpha = 0.7, colour = \"indianred\") +\n  theme_minimal() +\n  labs(x = \"Airport code\",\n       y = \"Total\\ndistance (km)\")\nggarrange(plt1, plt2, ncol = 1, labels = \"AUTO\")\n```\n\n::: {.cell-output-display}\n![The figure for Question 2.](BCB744_Intro_R_Example_2_files/figure-html/fig-library-ggpubr-1.svg){#fig-library-ggpubr width=75%}\n:::\n:::\n\n\n:::\n\n## 2.b\nWhich airlines have the most flights departing from NYC airports in\n2013? Make a table that lists these in descending order of frequency\nshows the number of flights for each airline. In your table, list the\nnames of the airlines as well. *Hint:* you can use the `airlines`\ndataset to look up the airline name based on `carrier` code.\n\n::: {.content-hidden}\n\n**Answer**\n\n\n::: {.cell}\n\n```{.r .cell-code}\npopular_destinations <- flights %>%\n  count(carrier) %>%\n  arrange(desc(n)) %>%\n  inner_join(airlines, by = \"carrier\") %>% \n  as_tibble()\nhead(popular_destinations, n = 16)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR> # A tibble: 16 × 3\nR>    carrier     n name                       \nR>    <chr>   <int> <chr>                      \nR>  1 UA      58665 United Air Lines Inc.      \nR>  2 B6      54635 JetBlue Airways            \nR>  3 EV      54173 ExpressJet Airlines Inc.   \nR>  4 DL      48110 Delta Air Lines Inc.       \nR>  5 AA      32729 American Airlines Inc.     \nR>  6 MQ      26397 Envoy Air                  \nR>  7 US      20536 US Airways Inc.            \nR>  8 9E      18460 Endeavor Air Inc.          \nR>  9 WN      12275 Southwest Airlines Co.     \nR> 10 VX       5162 Virgin America             \nR> 11 FL       3260 AirTran Airways Corporation\nR> 12 AS        714 Alaska Airlines Inc.       \nR> 13 F9        685 Frontier Airlines Inc.     \nR> 14 YV        601 Mesa Airlines Inc.         \nR> 15 HA        342 Hawaiian Airlines Inc.     \nR> 16 OO         32 SkyWest Airlines Inc.\n```\n\n\n:::\n:::\n\n\nThe carrier with the highest number of flights departing from NYC airports in 2013 is United Airlines, followed by JetBlue Airways, ExpressJet Airlines.\n\n:::\n\n## 2.c\n\nConsider only flights that have non-missing arrival delay information.\nYour answer should include the name of the carrier in addition to the\ncarrier code and the values asked.\n\ni.  Which carrier had the highest mean arrival delay?\n\nii.  Which carrier had the lowest mean arrival delay?\n\nMake sure that your answer includes the name of the carrier and the\ncalculated mean (±SD) delay times, and use a sensible number of decimal\ndigits.\n\n::: {.content-hidden}\n\n**Answer**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nflights %>%\n  filter(!is.na(arr_delay)) %>%\n  group_by(carrier) %>%\n  summarise(mean_arr_delay = round(mean(arr_delay), 1),\n            sd_arr_delay = round(sd(arr_delay), 1)) %>%\n  arrange(desc(mean_arr_delay)) %>%\n  inner_join(airlines, by = \"carrier\") %>%\n  slice(c(1, n())) %>% \n  as_tibble()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR> # A tibble: 2 × 4\nR>   carrier mean_arr_delay sd_arr_delay name                  \nR>   <chr>            <dbl>        <dbl> <chr>                 \nR> 1 F9                21.9         61.6 Frontier Airlines Inc.\nR> 2 AS                -9.9         36.5 Alaska Airlines Inc.\n```\n\n\n:::\n:::\n\n\nThe longest arrival delay was on Frontier Airlines that, on average, arrived 21.9 ± 61.5 (mean ± SD) minutes late. On the contrary, Alaska Airlines typically arrived earlier than anticipated by 9.9 ± 36.5 (mean ± SD) minutes.\n\n:::\n\n## 2.d\n\nWhat were the mean values for the weather variables at the origin\nairport on the top 10 days with the highest departure delays? Contrast\nthis with a similar view on the 10 days with the lowest departure\ndelays. Your table(s) should include the names of origin airports, the\ndates with the highest (lowest) departure delays, and the mean (±SD)\nweather variables on these days.\n\nCan you make any inferences about the effect of weather conditions on\nflight delays? Are there any problems with this analysis, and how might\nyou improve this analysis for a clearer view of the effect of weather\nconditions on the ability of flights to depart on time?\n\n::: {.content-hidden}\n\n**Answer**\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntop_delay <- bind_rows(\n    flights %>% slice_max(order_by = dep_delay, n = 10),\n    flights %>% slice_min(order_by = dep_delay, n = 10),\n) %>% \n  select(carrier, flight, tailnum, dep_delay, month, day, origin) %>%\n  inner_join(weather, by = c(\"origin\", \"month\", \"day\")) %>% \n  pivot_longer(cols = temp:visib,\n               names_to = \"weather_var\",\n               values_to = \"value\") %>% \n  na.omit() %>% \n  group_by(carrier, flight, tailnum, dep_delay, weather_var) %>% \n  summarise(mean_weather_var = round(mean(value, na.rm = TRUE), ),\n            sd_weather_var = round(sd(value, na.rm = TRUE), 1)) %>% \n  unite(\"mean_sd\", mean_weather_var:sd_weather_var, sep = \" ± \") %>% \n  arrange(desc(dep_delay)) %>% \n  pivot_wider(names_from = weather_var, values_from = mean_sd) %>% \n  as_tibble()\ntop_delay\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR> # A tibble: 22 × 13\nR>    carrier flight tailnum dep_delay dewp     humid   precip pressure temp  visib\nR>    <chr>    <int> <chr>       <dbl> <chr>    <chr>   <chr>  <chr>    <chr> <chr>\nR>  1 HA          51 N384HA       1301 35 ± 2.7 74 ± 1… 0 ± 0  1026 ± … 43 ±… 10 ±…\nR>  2 MQ        3535 N504MQ       1137 53 ± 4.5 57 ± 1… 0 ± 0  1014 ± … 71 ±… 10 ±…\nR>  3 MQ        3695 N517MQ       1126 24 ± 2.8 48 ± 1… 0 ± 0  1031 ± … 44 ±… 10 ±…\nR>  4 AA         177 N338AA       1014 57 ± 2.1 73 ± 1… 0 ± 0  1018 ± 1 66 ±… 10 ±…\nR>  5 MQ        3075 N665MQ       1005 73 ± 1.2 83 ± 1… 0 ± 0  1013 ± … 79 ±… 9 ± 1\nR>  6 DL        2391 N959DL        960 47 ± 2.8 68 ± 1… 0 ± 0  1013 ± … 58 ±… 10 ±…\nR>  7 DL        2119 N927DA        911 17 ± 5.2 50 ± 14 0 ± 0  1020 ± 4 35 ±… 10 ±…\nR>  8 DL        2007 N3762Y        899 70 ± 1.1 83 ± 9  0 ± 0  1008 ± … 76 ±… 9 ± …\nR>  9 DL        2047 N6716C        898 72 ± 1.4 84 ± 3… 0 ± 0  1012 ± … 77 ±… 9 ± …\nR> 10 AA         172 N5DMAA        896 51 ± 3.9 93 ± 6… 0 ± 0  1016 ± … 54 ±… 3 ± …\nR> # ℹ 12 more rows\nR> # ℹ 3 more variables: wind_dir <chr>, wind_speed <chr>, wind_gust <chr>\n```\n\n\n:::\n:::\n\n\nNothing obvious I can see about the effect of weather variables in affecting the departure delay. We would need to do some multivariate stats to assess.\n\n:::\n\n## 2.e\n\nPartition each day into four equal time intervals, *e.g.* 00:01-06:00,\n06:01-12:00, 12:01-18:00, and 18:01-00:00.\n\ni.  At each time interval, what is the proportion of flights delayed at\n    departure? Illustrate your finding in a figure.\n\n::: {.content-hidden}\n\n**Answer**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create time of day variable\nflights_tod <- flights %>%\n  mutate(time_of_day = case_when(\n    sched_dep_time >= 001  & sched_dep_time <= 600  ~ \"00:01-06:00\",\n    sched_dep_time >= 601  & sched_dep_time <= 1200 ~ \"06:01-12:00\",\n    sched_dep_time >= 1201 & sched_dep_time <= 1800 ~ \"12:01-18:00\",\n    sched_dep_time >= 1801                          ~ \"18:01-00:00\"\n  )) %>% \n  mutate(day_of_week = wday(time_hour))\n\n# Find proportion of delayed flights for each time of day\ndelay_time <- flights_tod %>%\n  filter(!is.na(dep_delay)) %>%\n  mutate(dep_delayed = ifelse(dep_delay > 0, \"delayed\", \"ontime\")) %>%\n  count(time_of_day, dep_delayed) %>%\n  group_by(time_of_day) %>%\n  mutate(prop_delayed = n / sum(n)) %>%\n  filter(dep_delayed == \"delayed\") %>%\n  arrange(prop_delayed) %>% \n  as_tibble()\nhead(delay_time)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR> # A tibble: 4 × 4\nR>   time_of_day dep_delayed     n prop_delayed\nR>   <chr>       <chr>       <int>        <dbl>\nR> 1 00:01-06:00 delayed      1819        0.207\nR> 2 06:01-12:00 delayed     32466        0.260\nR> 3 12:01-18:00 delayed     58325        0.463\nR> 4 18:01-00:00 delayed     35822        0.520\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(delay_time, aes(x = time_of_day, y = prop_delayed)) +\n  geom_col(fill = \"grey90\", alpha = 0.7, colour = \"indianred\") +\n  theme_minimal() +\n  labs(x = \"Time of day\",\n       y = \"Proportion of\\nflights delayed\")\n```\n\n::: {.cell-output-display}\n![The figure for Question 6a.](BCB744_Intro_R_Example_2_files/figure-html/fig-ggplot-delay-time-aes-x-1.svg){#fig-ggplot-delay-time-aes-x width=75%}\n:::\n:::\n\n\nAbout 21% of flights are delayed between midnight and 6:00, 26% are delayed between 6:00-12:00, 46% delays between 12:00-18:00, and 52% delays between 18:00pm, midnight. As the day progresses and the better the chance is of there being a delay.\n\n:::\n\nii.  Based on your analysis, does the chance of being delayed change\n    throughout the day?\n\nSee answer to Question 2.e.i.\n\niii.  For each weekday (1-7) aggregated over 2013, which of the time\n    intervals has the most flights? Create a figure to show your\n    finding.\n\n::: {.content-hidden}\n\n**Answer**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nflights_tod %>% \n  group_by(time_of_day, day_of_week) %>% \n  summarise(n_flights = n()) %>% \n  ggplot(aes(x = day_of_week, y = n_flights)) +\n    geom_col(fill = \"grey90\", alpha = 0.7, colour = \"indianred\") +\n    theme_minimal() +\n    labs(x = \"Time of day\",\n         y = \"Number of\\nflights\") +\n    facet_wrap(~time_of_day)\n```\n\n::: {.cell-output-display}\n![The figure for Question 6c.](BCB744_Intro_R_Example_2_files/figure-html/fig-flights-tod-1.svg){#fig-flights-tod width=75%}\n:::\n:::\n\n\nMidnight to 6-am has the fewest flights, regardless of what day of the week we are looking at --- although Sundays (day 1), Saturday (day 7) have slightly fewer flights. Similarly and Sun?Sat have slightly fewer flights between 6-am to 6-pm, although the total number of flights are much higher (closer to 20000 flights per day). Evenings from 6-pm to midnight the flights decrease in numbers, and Saturdays have fewer flights during this time than other days.\n\n:::\n\n## 2.f\n\nFind the 10 planes that spend the longest time (cumulatively) in the air.\n\ni.  For each model, what are the cumulative, mean flight times? In this table and also mention their type, manufacturer, model, number of engines, and speed.\n\n::: {.content-hidden}\n\n**Answer**\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncum_flights <- flights %>%\n  group_by(tailnum) %>% \n  summarise(cum_air_time = sum(air_time),\n            mean_air_time = round(mean(air_time, na.rm = TRUE), 1)) %>% \n  slice_max(order_by = cum_air_time, n = 10) %>% \n  inner_join(planes, by = \"tailnum\") %>%\n  select(tailnum, cum_air_time, mean_air_time, type, manufacturer, model, engines, speed) %>% \n  as_tibble()\nhead(cum_flights)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR> # A tibble: 6 × 8\nR>   tailnum cum_air_time mean_air_time type       manufacturer model engines speed\nR>   <chr>          <dbl>         <dbl> <chr>      <chr>        <chr>   <int> <int>\nR> 1 N502UA         97320          340. Fixed win… BOEING       757-…       2    NA\nR> 2 N512UA         95943          341. Fixed win… BOEING       757-…       2    NA\nR> 3 N505UA         95591          339  Fixed win… BOEING       757-…       2    NA\nR> 4 N557UA         87371          337. Fixed win… BOEING       757-…       2    NA\nR> 5 N518UA         80772          341. Fixed win… BOEING       757-…       2    NA\nR> 6 N508UA         79998          336. Fixed win… BOEING       757-…       2    NA\n```\n\n\n:::\n:::\n\n\n:::\n\nii.  Create a table that lists, for each air-plane identified in (i.), each flight (and associated destination) that it undertook during 2013. \n\n::: {.content-hidden}\n\n**Answer**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nflight_dest <- flights %>% \n  filter(tailnum %in% cum_flights$tailnum) %>% \n  select(tailnum, origin, dest, time_hour) %>% \n  as_tibble()\nhead(flight_dest)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR> # A tibble: 6 × 4\nR>   tailnum origin dest  time_hour          \nR>   <chr>   <chr>  <chr> <dttm>             \nR> 1 N518UA  JFK    LAX   2013-01-01 11:00:00\nR> 2 N502UA  JFK    SFO   2013-01-01 14:00:00\nR> 3 N512UA  JFK    LAX   2013-01-01 15:00:00\nR> 4 N557UA  JFK    SFO   2013-01-01 17:00:00\nR> 5 N508UA  JFK    SFO   2013-01-01 18:00:00\nR> 6 N591JB  JFK    PSE   2013-01-01 23:00:00\n```\n\n\n:::\n:::\n\n\n:::\n\niii.  Summarise all the in formation in (ii.) on a map of the USA. Use\n    lines to connect departure and destination locations (each\n    labelled). Different facets in the figure must be used for each of\n    the 10 planes. You can use the `alpha` value in **ggplot2** such\n    that the colour intensity of overlapping flight lines is\n    proportional to the number of flights taken along the path. For\n    bonus marks, ensure that the curvature of Earth is indicated in the\n    flight lines. *Hint:* such lines would display as curves, not straight\n    lines.\n\n::: {.content-hidden}\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# to be done in due module...\n```\n:::\n\n\n:::\n\n## 2.g\n\nLimit this analysis to only the coldest three winter and warmest three\nsummer months (show evidence for how this is decided). For each of these\ntwo seasons, create a visualisation to explore if there is a\nrelationship between the mean daily departure delay and the mean daily\ntemperature. Be as economical with your code as possible.\n\nDiscuss your answer.\n\n::: {.content-hidden}\n\n**Answer**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nseas <- weather %>% \n  group_by(month) %>% \n  summarise(mean_temp = round(mean(temp, na.rm = TRUE), 1)) %>% \n  as_tibble()\nseas\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR> # A tibble: 12 × 2\nR>    month mean_temp\nR>    <int>     <dbl>\nR>  1     1      35.6\nR>  2     2      34.3\nR>  3     3      39.9\nR>  4     4      51.7\nR>  5     5      61.8\nR>  6     6      72.2\nR>  7     7      80.1\nR>  8     8      74.5\nR>  9     9      67.4\nR> 10    10      60.1\nR> 11    11      45  \nR> 12    12      38.4\n```\n\n\n:::\n\n```{.r .cell-code}\nggplot(seas, aes(x = month, y = (mean_temp - 32)*5/9)) +\n  geom_col(fill = \"grey90\", alpha = 0.7, colour = \"indianred\") +\n  scale_x_continuous(breaks = seq(2, 12, by = 2)) +\n  theme_minimal() +\n  labs(x = \"Month\",\n       y = \"Mean temp. (°C)\")\n```\n\n::: {.cell-output-display}\n![Mean monthly temperature used to define coldest and warmest months.](BCB744_Intro_R_Example_2_files/figure-html/fig-ec-1.svg){#fig-ec width=75%}\n:::\n:::\n\n\nThe coldest months are December, January, and February. The warmest time of year is during June, July, August.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nflights %>% \n  filter(month %in% c(12, 1, 2, 6, 7, 8)) %>% \n  inner_join(weather, by = c(\"origin\", \"month\", \"day\")) %>% \n  group_by(month) %>% \n  summarise(mean_dep_delay = mean(dep_delay, na.rm = TRUE),\n            mean_temp = round(mean(temp, na.rm = TRUE), 1)) %>% \n  mutate(seas = c(\"winter\", \"winter\", \"summer\", \"summer\", \"summer\", \"winter\")) %>% \n  ggplot(aes(x = (mean_temp - 32)*5/9, y = mean_dep_delay)) +\n    geom_point(aes(col = seas)) +\n  theme_minimal() +\n  labs(x = \"Mean temp. (°C)\", y = \"Mean delay (min)\")\n```\n\n::: {.cell-output-display}\n![Mean departure delay vs. temperature for winter and summer months.](BCB744_Intro_R_Example_2_files/figure-html/fig-flights-1.svg){#fig-flights width=75%}\n:::\n:::\n\n\nIt seems that, in general, shorter delays are experienced during winter months. To fully assess the effect of weather variables on delays, a more detailed statistical analysis will be required.\n\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}