{
  "hash": "12dfb0b42fdb97274db7bdc25dc6c28a",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"11. Simple Linear Regression\"\nsubtitle: \"The Entry Point to Model-Based Biostatistics\"\nauthor: \"A. J. Smit\"\ndate: last-modified\ndate-format: \"YYYY/MM/DD\"\nreference-location: margin\n---\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n::: {.callout-note appearance=\"simple\"}\n## In This Chapter\n\n-   what a simple linear regression model is;\n-   when regression is more appropriate than correlation;\n-   the assumptions behind a straight-line model;\n-   how to fit a model with `lm()`;\n-   how to diagnose normality, homoscedasticity, linearity, and outliers;\n-   how to interpret slopes, fitted values, confidence intervals, and prediction intervals;\n-   how explanatory and predictive uses of the same regression differ;\n-   how to report a regression in the style of a Results section.\n:::\n\n::: {.callout-note appearance=\"simple\"}\n## Cheatsheet\n\nFind here a [Cheatsheet](../../docs/Methods_cheatsheet_v1.pdf) on statistical methods.\n:::\n\n::: {.callout-important appearance=\"simple\"}\n## Tasks to Complete in This Chapter\n\n-   Task H\n:::\n\n# Introduction\n\nLinear models are among the most useful statistical tools in biology because they allow us to describe and quantify how one variable changes with another. In a regression, we write down a model for a **response** variable, $Y$, as a function of a **predictor** variable, $X$, and then estimate the parameters of that model from the data.\n\nOne of the simplest such models is the **simple linear model**, which has one continuous predictor and one continuous response. The aim may be explanatory, where the predictor is believed to influence the response, or predictive, where we want a formula that allows us to estimate likely values of the response from known values of the predictor. In either case, regression differs from [correlation](09-correlation-and-association.qmd) because it imposes a response-predictor structure on the data.\n\nThis chapter is foundational because the reasoning developed here extends directly to [polynomial regression](12-polynomial-regression.qmd), [multiple regression](13-multiple-regression-and-model-specification.qmd), [interaction terms](14-interaction-effects.qmd), [generalised linear models](19-generalised-linear-models.qmd), and several of the more flexible modelling approaches discussed later. If the response-predictor structure is sound and a straight-line model is biologically plausible, simple linear regression is often the correct point of departure.\n\n# Key Concepts\n\nThese ideas organise the chapter.\n\n-   **Simple linear regression** models one continuous response as a function of one continuous predictor.\n-   **The response-predictor distinction** is essential. Regression is not simply correlation with a fitted line added.\n-   **The slope** is usually the main inferential quantity because it describes the expected change in the response for a one-unit change in the predictor.\n-   **The intercept** is often less biologically interesting, but it is still part of the fitted model.\n-   **Residuals** are central to assumption checking because they reveal structure that the model has failed to capture.\n-   **Confidence intervals** and **prediction intervals** answer different questions and should not be confused.\n\n# Nature of the Data and Assumptions\n\nThe experimenter must ensure the following key requirements for a simple linear regression:\n\n1. **A defensible response-predictor structure:** There should be a theoretical or philosophical basis for treating one variable as the predictor and the other as the response. This may be explicitly causal, but it can also be predictive if that distinction is still biologically sensible.\n2. **Independence of observations:** Each measured value of the response must be independent of the others. If repeated measurements, clustered sampling, or temporal dependence are present, a different modelling framework may be required.\n3. **Continuous predictor:** The predictor variable should be continuous.\n4. **Continuous response:** The response variable should also be continuous.\n\nAfter the model has been fitted, the following assumptions must be checked:\n\n1. **Normality:** The residuals should be approximately normally distributed.\n2. **Homoscedasticity:** The residual variance should be roughly constant across the fitted values.\n3. **Linearity:** The mean relationship between the predictor and the response should be approximately linear.\n4. **Measurement error in the predictor:** Standard linear regression assumes that the predictor is measured without serious error. In practice this is only approximately true, and we return to this issue in [Chapter 15](15-collinearity-confounding-measurement-error.qmd).\n\nAs in the earlier inferential chapters, the workflow is important. We first inspect the data, then fit the model, then examine the residuals, and *only then* interpret the coefficients with confidence.\n\n# The Model\n\nSimple linear regression is the first modelling framework in the sequence in which we write an explicit equation for the mean response and then estimate its parameters from data. The model itself and the least-squares fitting rule are set out more carefully in the `Core Equations` section below.\n\nThe line is fitted by minimising the sum of squared residuals. This is why ordinary linear regression is often called an **ordinary least squares** method.\n\nThe animation below shows the fitted line rotating through the data as the error sum of squares is minimised.\n\n```{=html}\n<video controls width=\"82%\" style=\"display:block; margin: 0 auto;\">\n  <source src=\"../../mov/lm_rotate.mp4\" type=\"video/mp4\">\n  Your browser does not support the video tag.\n</video>\n```\n\n::: {.callout-note appearance=\"simple\"}\n## The Residuals, $\\epsilon_i$\n\nIn most regression models we assume that the residuals are independent and identically distributed. When the residuals are approximately normal this can be written as $\\epsilon_i \\sim N(0, \\sigma^2)$. The requirement of mean zero implies that, on average, the model does not systematically over- or under-predict. Constant variance implies that the spread of residuals is roughly similar across the predictor range. Independence implies that residuals do not carry systematic structure from one observation to the next.\n\nViolation of these assumptions can lead to biased or inefficient parameter estimates, poor uncertainty estimates, and misleading inference.\n:::\n\n# R Function\n\nThe main function used in this chapter is `lm()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm(response ~ predictor, data = df)\n```\n:::\n\n\nYou can read the formula `response ~ predictor` as \"the response is modelled as a function of the predictor.\"\n\n# The Core Equations\n\nSimple linear regression has two equations that students should keep conceptually separate. The first describes the model for the mean response. The second describes how the fitted line is chosen from the data.\n\nThe model itself is:\n\n$$Y_i = \\alpha + \\beta X_i + \\epsilon_i$$ {#eq-slr}\n\nIn @eq-slr, $Y_i$ is the response for observation $i$, $X_i$ is the predictor, $\\alpha$ is the intercept, $\\beta$ is the slope, and $\\epsilon_i$ is the residual error. This is the equation that says what a straight-line mean structure looks like.\n\nThe least-squares criterion used by `lm()` is then to choose $\\alpha$ and $\\beta$ so that the residual sum of squares is as small as possible:\n\n$$\\text{RSS} = \\sum_{i=1}^{n}(Y_i - \\hat{Y}_i)^2$$ {#eq-rss}\n\nEquation @eq-rss is not a second regression model. It is the fitting rule. It tells us how the software decides which of all possible straight lines is the best-fitting one.\n\nThe fitted model can then be explored with functions such as:\n\n-   `summary()` for the coefficients and overall fit;\n-   `confint()` for confidence intervals around the coefficients;\n-   `augment()` from **broom** for fitted values and residuals;\n-   `predict()` for confidence and prediction intervals;\n-   `plot()` for standard diagnostic plots;\n-   `bptest()` from **lmtest** for a formal test of heteroscedasticity.\n\n# Outliers and Their Impact on Simple Linear Regression\n\nOutliers can have disproportionate effects on a simple linear regression because the fitted line is estimated by minimising squared residuals, as in @eq-rss. Extreme observations may therefore influence the slope, the intercept, the standard errors, the confidence intervals, and the diagnostic patterns.\n\nThis does not mean that unusual observations must automatically be removed. Some are recording errors and should be corrected or excluded. Others are rare but real biological events and may carry important information. The correct response is therefore to identify potentially influential points, inspect them carefully, and decide whether they reveal error, unusual but valid biology, or a more fundamental model problem.\n\n# Example 1: Sparrow wing length and age\n\nWe begin with a very small sparrow dataset because it makes the general logic transparent. We then move to a fuller worked example using the Adelie penguin data from the `palmerpenguins` package, which is much closer to the style and level of complexity encountered in real biological analyses.\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {#tbl-gt-sparrows .cell tbl-cap='Sparrow wing-length data used in the introductory simple linear regression example.'}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"mrpqafgjjr\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#mrpqafgjjr table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#mrpqafgjjr thead, #mrpqafgjjr tbody, #mrpqafgjjr tfoot, #mrpqafgjjr tr, #mrpqafgjjr td, #mrpqafgjjr th {\n  border-style: none;\n}\n\n#mrpqafgjjr p {\n  margin: 0;\n  padding: 0;\n}\n\n#mrpqafgjjr .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#mrpqafgjjr .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#mrpqafgjjr .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#mrpqafgjjr .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#mrpqafgjjr .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#mrpqafgjjr .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mrpqafgjjr .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#mrpqafgjjr .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#mrpqafgjjr .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#mrpqafgjjr .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#mrpqafgjjr .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#mrpqafgjjr .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#mrpqafgjjr .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#mrpqafgjjr .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#mrpqafgjjr .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#mrpqafgjjr .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#mrpqafgjjr .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#mrpqafgjjr .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#mrpqafgjjr .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mrpqafgjjr .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#mrpqafgjjr .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#mrpqafgjjr .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#mrpqafgjjr .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mrpqafgjjr .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#mrpqafgjjr .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#mrpqafgjjr .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mrpqafgjjr .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mrpqafgjjr .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#mrpqafgjjr .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mrpqafgjjr .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#mrpqafgjjr .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mrpqafgjjr .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#mrpqafgjjr .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mrpqafgjjr .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#mrpqafgjjr .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mrpqafgjjr .gt_left {\n  text-align: left;\n}\n\n#mrpqafgjjr .gt_center {\n  text-align: center;\n}\n\n#mrpqafgjjr .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#mrpqafgjjr .gt_font_normal {\n  font-weight: normal;\n}\n\n#mrpqafgjjr .gt_font_bold {\n  font-weight: bold;\n}\n\n#mrpqafgjjr .gt_font_italic {\n  font-style: italic;\n}\n\n#mrpqafgjjr .gt_super {\n  font-size: 65%;\n}\n\n#mrpqafgjjr .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#mrpqafgjjr .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#mrpqafgjjr .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#mrpqafgjjr .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#mrpqafgjjr .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#mrpqafgjjr .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#mrpqafgjjr .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#mrpqafgjjr .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#mrpqafgjjr div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"age\">Age (days)</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"wing\">Wing length<br>(cm)</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"age\" class=\"gt_row gt_right\">3</td>\n<td headers=\"wing\" class=\"gt_row gt_right\">1.4</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right\">4</td>\n<td headers=\"wing\" class=\"gt_row gt_right\">1.5</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right\">5</td>\n<td headers=\"wing\" class=\"gt_row gt_right\">2.2</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right\">6</td>\n<td headers=\"wing\" class=\"gt_row gt_right\">2.4</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right\">8</td>\n<td headers=\"wing\" class=\"gt_row gt_right\">3.1</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right\">9</td>\n<td headers=\"wing\" class=\"gt_row gt_right\">3.2</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right\">10</td>\n<td headers=\"wing\" class=\"gt_row gt_right\">3.2</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right\">11</td>\n<td headers=\"wing\" class=\"gt_row gt_right\">3.9</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right\">12</td>\n<td headers=\"wing\" class=\"gt_row gt_right\">4.1</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right\">14</td>\n<td headers=\"wing\" class=\"gt_row gt_right\">4.7</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right\">15</td>\n<td headers=\"wing\" class=\"gt_row gt_right\">4.5</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right\">16</td>\n<td headers=\"wing\" class=\"gt_row gt_right\">5.2</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right\">17</td>\n<td headers=\"wing\" class=\"gt_row gt_right\">5.0</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n## Do an Exploratory Data Analysis (EDA)\n\nWe start with the sparrow data to see the basic form of a simple linear model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(sparrows)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      age          wing      \n Min.   : 3   Min.   :1.400  \n 1st Qu.: 6   1st Qu.:2.400  \n Median :10   Median :3.200  \n Mean   :10   Mean   :3.415  \n 3rd Qu.:14   3rd Qu.:4.500  \n Max.   :17   Max.   :5.200  \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Wing length of sparrows at different ages.](11-simple-linear-regression_files/figure-html/fig-sparrow-1.svg){#fig-sparrow}\n:::\n:::\n\n\nThe scatter plot suggests a clear positive linear relationship: older sparrows tend to have longer wings, and the relationship appears close to linear over the range of the data. This small example is useful because it makes the fitted line and the slope easy to understand before we move to a noisier biological dataset.\n\n## State the Model Question and Hypothesis\n\nThe biological question in the sparrow example is whether wing length changes systematically with age.\n\nThe inferential focus in a simple linear regression is usually the slope in @eq-slr:\n\n$$H_{0}: \\beta = 0$$\n$$H_{a}: \\beta \\ne 0$$\n\nIf the slope is zero (a more-or-less horizontal line), there is no linear relationship between the predictor and the expected value of the response. If the slope differs from zero, then the predictor helps explain variation in the response.\n\n## Fit the Model\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsparrow_mod <- lm(wing ~ age, data = sparrows)\nsummary(sparrow_mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = wing ~ age, data = sparrows)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.30699 -0.21538  0.06553  0.16324  0.22507 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  0.71309    0.14790   4.821 0.000535 ***\nage          0.27023    0.01349  20.027 5.27e-10 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.2184 on 11 degrees of freedom\nMultiple R-squared:  0.9733,\tAdjusted R-squared:  0.9709 \nF-statistic: 401.1 on 1 and 11 DF,  p-value: 5.267e-10\n```\n\n\n:::\n:::\n\n\nThe output provides the intercept, the slope, their standard errors, a test of whether the coefficients differ from zero, the residual standard error, and the model $R^2$.\n\n## Test the Assumptions\n\nAssumptions in regression are checked after fitting the model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsparrow_aug <- augment(sparrow_mod)\nsparrow_aug |>\n  select(age, wing, .fitted, .resid) |>\n  head()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 4\n    age  wing .fitted  .resid\n  <dbl> <dbl>   <dbl>   <dbl>\n1     3   1.4    1.52 -0.124 \n2     4   1.5    1.79 -0.294 \n3     5   2.2    2.06  0.136 \n4     6   2.4    2.33  0.0655\n5     8   3.1    2.87  0.225 \n6     9   3.2    3.15  0.0548\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](11-simple-linear-regression_files/figure-html/fig-sparrow-diagnostics-1.svg){#fig-sparrow-diagnostics}\n:::\n:::\n\n\nThe diagnostic plots suggest that the model is broadly adequate for these data. The residuals do not show severe curvature, the spread is reasonably even, and the Q-Q plot does not suggest a dramatic departure from normality. Because the dataset is small, these plots should be interpreted cautiously, but there is no obvious reason to abandon the linear model.\n\n## Interpret the Results\n\nThe fitted slope is positive, which means that wing length increases with age. In this example, the slope estimate is about 0.27 cm per day, so the model implies that the expected wing length increases by roughly 0.27 cm for each additional day of age across the range of these observations.\n\nThe intercept is the expected wing length when age is zero. Here that value is not biologically the main point of interest. It is simply the point where the fitted line crosses the vertical axis.\n\nThe model explains a large proportion of the variation in the observed wing lengths ($R^2 \\approx 0.97$), and the test of the slope provides very strong evidence that the linear relationship is not zero ($p < 0.001$).\n\n## Reporting\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Bill length as a function of body mass for Adelie penguins. The straight line is the fitted simple linear regression and the blue shading is the 95% confidence interval.](11-simple-linear-regression_files/figure-html/fig-penguin-results-1.svg){#fig-penguin-results}\n:::\n:::\n\n\n::: {.callout-note appearance=\"simple\"}\n## Write-Up\n\n**Methods**\n\nThe relationship between sparrow wing length and age was assessed with a simple linear regression, with wing length as the response variable and age as the continuous predictor. Model adequacy was evaluated from standard residual diagnostics.\n\n**Results**\n\nSparrow wing length increased strongly with age in the fitted simple linear regression ($\\beta = 0.270$, 95% CI: 0.241 to 0.300; $R^2 = 0.97$; $p < 0.001$). Across the observed age range, older birds therefore had consistently longer wings, with the expected wing length increasing by about 0.27 cm for each additional day of age.\n\n**Discussion**\n\nThis example is useful because it makes the biological interpretation of the slope very clear: age is associated with a strong increase in wing length over the observed range, and the fitted line captures most of the variation in these simple demonstration data.\n:::\n\n# Example 2: Adelie penguin bill length and body mass\n\nThe sparrow example makes the general workflow clear, but it is useful to repeat the same approach in a more interesting dataset. The following example uses the `penguins` dataset from the `palmerpenguins` package to model bill length as a function of body mass in Adelie penguins.\n\nAlthough we could also calculate a correlation, we will use a simple linear regression because we want a predictive model that estimates bill length from body mass. This is a defensible use of simple linear regression even though we are not claiming that body mass directly causes bill length.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nAdelie <- penguins[penguins$species == \"Adelie\", ]\nAdelie <- Adelie[-4, ]\n```\n:::\n\n\n\n::: {#tbl-penguins .cell tbl-cap='Size measurements for adult foraging Adelie penguins near Palmer Station, Antarctica.'}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"xtlayiskng\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#xtlayiskng table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#xtlayiskng thead, #xtlayiskng tbody, #xtlayiskng tfoot, #xtlayiskng tr, #xtlayiskng td, #xtlayiskng th {\n  border-style: none;\n}\n\n#xtlayiskng p {\n  margin: 0;\n  padding: 0;\n}\n\n#xtlayiskng .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#xtlayiskng .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#xtlayiskng .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#xtlayiskng .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#xtlayiskng .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#xtlayiskng .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xtlayiskng .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#xtlayiskng .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#xtlayiskng .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#xtlayiskng .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#xtlayiskng .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#xtlayiskng .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#xtlayiskng .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#xtlayiskng .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#xtlayiskng .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#xtlayiskng .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#xtlayiskng .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#xtlayiskng .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#xtlayiskng .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xtlayiskng .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#xtlayiskng .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#xtlayiskng .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#xtlayiskng .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xtlayiskng .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#xtlayiskng .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#xtlayiskng .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xtlayiskng .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xtlayiskng .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#xtlayiskng .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xtlayiskng .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#xtlayiskng .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xtlayiskng .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#xtlayiskng .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xtlayiskng .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#xtlayiskng .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xtlayiskng .gt_left {\n  text-align: left;\n}\n\n#xtlayiskng .gt_center {\n  text-align: center;\n}\n\n#xtlayiskng .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#xtlayiskng .gt_font_normal {\n  font-weight: normal;\n}\n\n#xtlayiskng .gt_font_bold {\n  font-weight: bold;\n}\n\n#xtlayiskng .gt_font_italic {\n  font-style: italic;\n}\n\n#xtlayiskng .gt_super {\n  font-size: 65%;\n}\n\n#xtlayiskng .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#xtlayiskng .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#xtlayiskng .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#xtlayiskng .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#xtlayiskng .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#xtlayiskng .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#xtlayiskng .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#xtlayiskng .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#xtlayiskng div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"bill_length_mm\">Bill length (mm)</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"body_mass_g\">Body mass (g)</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"bill_length_mm\" class=\"gt_row gt_right\">39.1</td>\n<td headers=\"body_mass_g\" class=\"gt_row gt_right\">3750</td></tr>\n    <tr><td headers=\"bill_length_mm\" class=\"gt_row gt_right\">39.5</td>\n<td headers=\"body_mass_g\" class=\"gt_row gt_right\">3800</td></tr>\n    <tr><td headers=\"bill_length_mm\" class=\"gt_row gt_right\">40.3</td>\n<td headers=\"body_mass_g\" class=\"gt_row gt_right\">3250</td></tr>\n    <tr><td headers=\"bill_length_mm\" class=\"gt_row gt_right\">36.7</td>\n<td headers=\"body_mass_g\" class=\"gt_row gt_right\">3450</td></tr>\n    <tr><td headers=\"bill_length_mm\" class=\"gt_row gt_right\">39.3</td>\n<td headers=\"body_mass_g\" class=\"gt_row gt_right\">3650</td></tr>\n    <tr><td headers=\"bill_length_mm\" class=\"gt_row gt_right\">38.9</td>\n<td headers=\"body_mass_g\" class=\"gt_row gt_right\">3625</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n## Do an Exploratory Data Analysis (EDA)\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(Adelie)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 151   8\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(Adelie)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      species          island   bill_length_mm  bill_depth_mm  \n Adelie   :151   Biscoe   :44   Min.   :32.10   Min.   :15.50  \n Chinstrap:  0   Dream    :56   1st Qu.:36.75   1st Qu.:17.50  \n Gentoo   :  0   Torgersen:51   Median :38.80   Median :18.40  \n                                Mean   :38.79   Mean   :18.35  \n                                3rd Qu.:40.75   3rd Qu.:19.00  \n                                Max.   :46.00   Max.   :21.50  \n flipper_length_mm  body_mass_g       sex          year     \n Min.   :172       Min.   :2850   female:73   Min.   :2007  \n 1st Qu.:186       1st Qu.:3350   male  :73   1st Qu.:2007  \n Median :190       Median :3700   NA's  : 5   Median :2008  \n Mean   :190       Mean   :3701               Mean   :2008  \n 3rd Qu.:195       3rd Qu.:4000               3rd Qu.:2009  \n Max.   :210       Max.   :4775               Max.   :2009  \n```\n\n\n:::\n:::\n\n\nWe see that the dataset contains many more observations than the sparrow example. We focus here on `body_mass_g` and `bill_length_mm`. Both are continuous, and restricting the analysis to Adelie penguins gives us a relatively coherent biological subset for the example.\n\n## Create a Plot\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(Adelie,\n       aes(x = body_mass_g, y = bill_length_mm)) +\n  geom_point(shape = 1, colour = \"pink\") +\n  geom_smooth(method = \"lm\", se = FALSE, colour = \"steelblue4\") +\n  labs(x = \"Body mass (g)\", y = \"Bill length (mm)\") +\n  theme_grey()\n```\n\n::: {.cell-output-display}\n![Scatter plot of the Palmer Station Adelie penguin data with a best fit line.](11-simple-linear-regression_files/figure-html/fig-penguin-slr-1.svg){#fig-penguin-slr}\n:::\n:::\n\n\nAlthough there is considerable scatter in the data, there is also a clear positive relationship between body mass and bill length. This relationship appears linear enough to justify a simple linear model as a first approximation.\n\n## State the Hypothesis\n\n$$H_{0}: \\beta = 0$$\n$$H_{a}: \\beta \\ne 0$$\n\nThat is, the null hypothesis is that body mass has no linear association with bill length, while the alternative is that the slope differs from zero.\n\nIf the slope is zero, then the predictor does not explain systematic change in the expected response.\n\n## Fit the Model\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod1 <- lm(bill_length_mm ~ body_mass_g,\n           data = Adelie)\nsummary(mod1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = bill_length_mm ~ body_mass_g, data = Adelie)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-6.4208 -1.3690  0.1874  1.4825  5.6168 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 2.699e+01  1.483e+00  18.201  < 2e-16 ***\nbody_mass_g 3.188e-03  3.977e-04   8.015 2.95e-13 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2.234 on 149 degrees of freedom\nMultiple R-squared:  0.3013,\tAdjusted R-squared:  0.2966 \nF-statistic: 64.24 on 1 and 149 DF,  p-value: 2.955e-13\n```\n\n\n:::\n:::\n\n\n## Test the Assumptions\n\nTo facilitate assumption checking we use `augment()` from **broom** to add fitted values, residuals, leverage, and related diagnostics to the data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod1_data <- augment(mod1)\n```\n:::\n\n\n### Normality\n\nThe Shapiro-Wilk test can be used as one formal check of the residual distribution.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshapiro.test(residuals(mod1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  residuals(mod1)\nW = 0.99613, p-value = 0.9637\n```\n\n\n:::\n:::\n\n\nHere the formal test does not suggest a serious departure from normality, but the graphical diagnostics are usually more informative than the test alone.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Diagnostic plots for the simple linear regression of Adelie penguin bill length on body mass. A) Normal Q-Q plot. B) Histogram of residuals. C) Residuals versus fitted values. D) Scale-location plot.](11-simple-linear-regression_files/figure-html/fig-assump-plots-1.svg){#fig-assump-plots}\n:::\n:::\n\n\nThe Q-Q plot and histogram suggest that the residuals are approximately normally distributed. There is no obvious extreme departure that would make the model immediately unusable.\n\n### Homoscedasticity\n\nThe Breusch-Pagan test is one formal check of constant variance.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbptest(mod1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tstudentized Breusch-Pagan test\n\ndata:  mod1\nBP = 1.6677, df = 1, p-value = 0.1966\n```\n\n\n:::\n:::\n\n\nThe test does not suggest strong heteroscedasticity, and the residuals-versus-fitted and scale-location plots also indicate that the spread of residuals is reasonably even across the fitted range.\n\n### Check for Outliers\n\nOutliers and influential observations can be explored in several complementary ways. Here we look at DFFITS, Cook's distance, residuals versus leverage, and Cook's distance versus leverage.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncooksd_thresh <- 4 / nrow(mod1_data)\ndffits_threshold <- 2 * sqrt(2 / nrow(Adelie))\n\nmod1_data <- mod1_data %>%\n  mutate(index = row_number(),\n         leverage = hatvalues(mod1),\n         dffits = dffits(mod1),\n         colour = ifelse(.cooksd > cooksd_thresh, \"black\", \"pink\"))\n```\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Diagnostic plots for visual inspection of outliers in the Adelie penguin regression. A) DFFITS. B) Cook's distance. C) Residuals versus leverage. D) Cook's distance versus leverage. Observations beyond the Cook's distance threshold are shown in black and labelled by row number.](11-simple-linear-regression_files/figure-html/fig-penguin-outliers1-1.svg){#fig-penguin-outliers1}\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Scatter plot of Adelie penguin bill length against body mass, with observations exceeding the Cook's distance threshold highlighted.](11-simple-linear-regression_files/figure-html/fig-penguin-outliers2-1.svg){#fig-penguin-outliers2}\n:::\n:::\n\n\nThese plots do not suggest a catastrophic influence problem, but they do remind us that some observations contribute more to the fitted line than others. If an identified point were an obvious data-entry error, it could be corrected or excluded. If it were a real biological extreme, it would usually be better to keep it and discuss its influence.\n\n## Interpret the Results\n\nNow that the assumptions appear broadly acceptable, we can interpret the fitted model. The slope of the regression line is positive, so bill length increases with body mass. The coefficient is about $3.2 \\times 10^{-3}$ mm/g, meaning that the expected bill length increases by about 0.0032 mm for every additional gram of body mass.\n\nThe multiple $R^2$ is about 0.30, so the model explains roughly 30% of the observed variation in bill length. This is a useful reminder that a biologically informative regression does not need to explain nearly all the variation in the response to be worthwhile.\n\nThe test of the slope provides strong evidence that the relationship is not zero ($p < 0.001$). An ANOVA on the fitted model leads to the same practical conclusion: the straight-line model explains a meaningful amount of variation in bill length.\n\n## Reporting\n\n::: {.callout-note appearance=\"simple\"}\n## Write-Up\n\n**Methods**\n\nThe data analysed in this example were drawn from the Palmer Penguins dataset, which contains measurements on penguins sampled in the Palmer Archipelago, Antarctica. For this worked example, only Adelie penguins were retained. Bill length was treated as the response variable and body mass as the continuous predictor.\n\nA simple linear regression model was fitted using `lm()` in R, with bill length modelled as a function of body mass. Model adequacy was assessed by inspecting residual plots, by applying the Shapiro-Wilk test to the residuals, and by using the Breusch-Pagan test to assess homoscedasticity. Influential observations were explored using Cook's distance, DFFITS, and leverage-based diagnostics.\n\n**Results**\n\nBill length increased with body mass in the fitted simple linear regression ($\\beta = 0.00319$, SE = 0.00040, $t = 8.02$, $p < 0.001$) (@fig-penguin-results). The model explained about 30% of the variation in bill length ($R^2 = 0.30$), indicating that body mass was an informative but incomplete predictor of bill length. The overall model was also strongly supported by the ANOVA ($F = 64.25$, $p < 0.001$, d.f. = 1, 149).\n\n**Discussion**\n\nIn summary, the worked example supports a positive relationship between body mass and bill length in Adelie penguins. The model is clearly informative, but substantial unexplained variation remains, which suggests that additional biological predictors would be needed for a fuller account of bill-length variation.\n:::\n\n# Confidence and Prediction Intervals\n\nThe fitted line gives the expected mean response for a given value of the predictor, but two different kinds of interval are commonly needed.\n\n-   A **confidence interval** describes uncertainty in the estimated mean response.\n-   A **prediction interval** describes uncertainty for an individual future observation.\n\nThe prediction interval is always wider because it must include the scatter of individual observations around the fitted mean.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnew_x <- tibble(age = c(7, 13))\npredict(sparrow_mod, newdata = new_x, interval = \"confidence\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       fit      lwr      upr\n1 2.604698 2.444344 2.765051\n2 4.226072 4.065719 4.386425\n```\n\n\n:::\n\n```{.r .cell-code}\npredict(sparrow_mod, newdata = new_x, interval = \"prediction\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       fit      lwr      upr\n1 2.604698 2.097951 3.111444\n2 4.226072 3.719325 4.732818\n```\n\n\n:::\n:::\n\n\nWe can also visualise the same distinction in the penguin example.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npred_conf <- as.data.frame(predict(mod1,\n                                   newdata = Adelie,\n                                   interval = \"confidence\"))\n\npred_pred <- as.data.frame(predict(mod1,\n                                   newdata = Adelie,\n                                   interval = \"prediction\"))\n\nresults <- cbind(Adelie, pred_conf, pred_pred[, 2:3])\nnames(results)[c(9:13)] <- c(\"fit\", \"lwr_conf\", \"upr_conf\",\n                             \"lwr_pred\", \"upr_pred\")\n\nggplot(data = results, aes(x = body_mass_g, y = fit)) +\n  geom_line(linewidth = 0.4, colour = \"red\") +\n  geom_ribbon(aes(ymin = lwr_pred, ymax = upr_pred),\n              alpha = 0.2, fill = \"red\") +\n  geom_ribbon(aes(ymin = lwr_conf, ymax = upr_conf),\n              alpha = 0.2, fill = \"blue\") +\n  geom_point(aes(y = bill_length_mm), shape = 1) +\n  labs(x = \"Body mass (g)\", y = \"Bill length (mm)\") +\n  theme_grey()\n```\n\n::: {.cell-output-display}\n![Adelie penguin bill length model with confidence interval (blue) and prediction interval (pink) around the fitted values.](11-simple-linear-regression_files/figure-html/fig-penguin-intervals-1.svg){#fig-penguin-intervals}\n:::\n:::\n\n\nConfidence intervals are useful when the primary interest lies in the mean expected response at a given predictor value. Prediction intervals are more relevant when the goal is to anticipate the range in which an individual future observation may fall.\n\n# Prediction Versus Explanation\n\nBy this point in the chapter it should be clear that the same fitted straight-line model can be used for at least two different scientific purposes.\n\n-   In an **explanatory** analysis, the main interest is usually the slope itself and what it says about the biological relationship between the predictor and the response.\n-   In a **predictive** analysis, the emphasis shifts toward fitted values, prediction intervals, and how accurately the model can anticipate new observations.\n\nThe sparrow example is mostly explanatory. We care primarily that wing length increases with age and that the slope is clearly positive. The Adelie penguin example is closer to a predictive framing because we have treated body mass as a variable from which bill length might be estimated for new individuals.\n\nThe distinction is important because it changes what should be emphasised in a Results section. Explanatory work usually emphasises the slope, its uncertainty, and the biological interpretation of the effect. Predictive work still needs the model coefficients, but it should pay much more attention to fitted values, prediction intervals, and the amount of unexplained variation.\n\nThis is also why a model with a highly significant slope is not automatically a good predictive model. A relationship can be biologically real and still leave substantial scatter around the fitted line, as in the penguin data. Conversely, a model that predicts well is not automatically evidence for a causal mechanism. In [Chapter 23](23-prediction-and-explanation.qmd), we return to this distinction.\n\n# What to Do When Assumptions Fail\n\nIf the assumptions of the linear model are not adequate, the first step is not to abandon the analysis mechanically but to ask what the diagnostic pattern is telling you.\n\n-   If the residuals suggest **non-linearity**, consider whether the relationship should be transformed or whether a more flexible model is needed.\n-   If the residual variance changes strongly with fitted values, revisit [Chapter 6](06-assumptions-and-transformations.qmd) and consider transformation or a different modelling approach.\n-   If outliers have strong leverage or influence, inspect them carefully before deciding what to do.\n-   If the real question is still only one of association, and not response modelling, return to [Chapter 9](09-correlation-and-association.qmd).\n\n# Common Mistakes\n\nCommon mistakes in simple linear regression include:\n\n-   using regression when the relationship is only associative and poorly justified as a response-predictor model;\n-   ignoring non-independence among observations;\n-   fitting a straight line to a clearly curved relationship;\n-   treating statistical significance as biological importance;\n-   reporting $R^2$ without discussing effect size, uncertainty, or assumptions.\n\n# Summary\n\n-   Simple linear regression models one continuous response as a function of one continuous predictor.\n-   The slope is usually the main inferential quantity because it describes how the expected response changes with the predictor.\n-   Regression differs from correlation because it imposes a response-predictor structure.\n-   Residual diagnostics are essential because they tell us whether the model is adequate.\n-   Outlier diagnostics help us decide whether unusual observations are errors, influential extremes, or signs of model misspecification.\n-   Confidence intervals and prediction intervals answer different questions.\n\nThis chapter establishes the workflow for modelling. The next chapter extends the same logic to several predictors at once, where model specification becomes a more demanding scientific task.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}