{
  "hash": "35a145ba6e96105a51890a6e26211702",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"BCB744 Task E\"\nformat:\n  html:\n    fig-format: png\n    fig_retina: 2\n    fig-dpi: 400\nexecute:\n  dev: ragg_png\n  fig-format: png\nparams:\n  hide_answers: true\n---\n\n::: {.callout-note appearance=\"simple\"}\n## Self-Assessment Task E.1\n\na. Explain the output of `dimnames()` when applied to the `penguins` dataset. **(/2)**\nb. Explain the output of `str()` when applied to the `penguins` dataset. **(/3)**\n\n::: {.content-hidden}\n\n**Answer**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(palmerpenguins)\ndata(penguins)\n\n# a.\ndimnames(penguins)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[[1]]\n  [1] \"1\"   \"2\"   \"3\"   \"4\"   \"5\"   \"6\"   \"7\"   \"8\"   \"9\"   \"10\"  \"11\"  \"12\" \n [13] \"13\"  \"14\"  \"15\"  \"16\"  \"17\"  \"18\"  \"19\"  \"20\"  \"21\"  \"22\"  \"23\"  \"24\" \n [25] \"25\"  \"26\"  \"27\"  \"28\"  \"29\"  \"30\"  \"31\"  \"32\"  \"33\"  \"34\"  \"35\"  \"36\" \n [37] \"37\"  \"38\"  \"39\"  \"40\"  \"41\"  \"42\"  \"43\"  \"44\"  \"45\"  \"46\"  \"47\"  \"48\" \n [49] \"49\"  \"50\"  \"51\"  \"52\"  \"53\"  \"54\"  \"55\"  \"56\"  \"57\"  \"58\"  \"59\"  \"60\" \n [61] \"61\"  \"62\"  \"63\"  \"64\"  \"65\"  \"66\"  \"67\"  \"68\"  \"69\"  \"70\"  \"71\"  \"72\" \n [73] \"73\"  \"74\"  \"75\"  \"76\"  \"77\"  \"78\"  \"79\"  \"80\"  \"81\"  \"82\"  \"83\"  \"84\" \n [85] \"85\"  \"86\"  \"87\"  \"88\"  \"89\"  \"90\"  \"91\"  \"92\"  \"93\"  \"94\"  \"95\"  \"96\" \n [97] \"97\"  \"98\"  \"99\"  \"100\" \"101\" \"102\" \"103\" \"104\" \"105\" \"106\" \"107\" \"108\"\n[109] \"109\" \"110\" \"111\" \"112\" \"113\" \"114\" \"115\" \"116\" \"117\" \"118\" \"119\" \"120\"\n[121] \"121\" \"122\" \"123\" \"124\" \"125\" \"126\" \"127\" \"128\" \"129\" \"130\" \"131\" \"132\"\n[133] \"133\" \"134\" \"135\" \"136\" \"137\" \"138\" \"139\" \"140\" \"141\" \"142\" \"143\" \"144\"\n[145] \"145\" \"146\" \"147\" \"148\" \"149\" \"150\" \"151\" \"152\" \"153\" \"154\" \"155\" \"156\"\n[157] \"157\" \"158\" \"159\" \"160\" \"161\" \"162\" \"163\" \"164\" \"165\" \"166\" \"167\" \"168\"\n[169] \"169\" \"170\" \"171\" \"172\" \"173\" \"174\" \"175\" \"176\" \"177\" \"178\" \"179\" \"180\"\n[181] \"181\" \"182\" \"183\" \"184\" \"185\" \"186\" \"187\" \"188\" \"189\" \"190\" \"191\" \"192\"\n[193] \"193\" \"194\" \"195\" \"196\" \"197\" \"198\" \"199\" \"200\" \"201\" \"202\" \"203\" \"204\"\n[205] \"205\" \"206\" \"207\" \"208\" \"209\" \"210\" \"211\" \"212\" \"213\" \"214\" \"215\" \"216\"\n[217] \"217\" \"218\" \"219\" \"220\" \"221\" \"222\" \"223\" \"224\" \"225\" \"226\" \"227\" \"228\"\n[229] \"229\" \"230\" \"231\" \"232\" \"233\" \"234\" \"235\" \"236\" \"237\" \"238\" \"239\" \"240\"\n[241] \"241\" \"242\" \"243\" \"244\" \"245\" \"246\" \"247\" \"248\" \"249\" \"250\" \"251\" \"252\"\n[253] \"253\" \"254\" \"255\" \"256\" \"257\" \"258\" \"259\" \"260\" \"261\" \"262\" \"263\" \"264\"\n[265] \"265\" \"266\" \"267\" \"268\" \"269\" \"270\" \"271\" \"272\" \"273\" \"274\" \"275\" \"276\"\n[277] \"277\" \"278\" \"279\" \"280\" \"281\" \"282\" \"283\" \"284\" \"285\" \"286\" \"287\" \"288\"\n[289] \"289\" \"290\" \"291\" \"292\" \"293\" \"294\" \"295\" \"296\" \"297\" \"298\" \"299\" \"300\"\n[301] \"301\" \"302\" \"303\" \"304\" \"305\" \"306\" \"307\" \"308\" \"309\" \"310\" \"311\" \"312\"\n[313] \"313\" \"314\" \"315\" \"316\" \"317\" \"318\" \"319\" \"320\" \"321\" \"322\" \"323\" \"324\"\n[325] \"325\" \"326\" \"327\" \"328\" \"329\" \"330\" \"331\" \"332\" \"333\" \"334\" \"335\" \"336\"\n[337] \"337\" \"338\" \"339\" \"340\" \"341\" \"342\" \"343\" \"344\"\n\n[[2]]\n[1] \"species\"           \"island\"            \"bill_length_mm\"   \n[4] \"bill_depth_mm\"     \"flipper_length_mm\" \"body_mass_g\"      \n[7] \"sex\"               \"year\"             \n```\n\n\n:::\n\n```{.r .cell-code}\n# b.\nstr(penguins)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [344 × 8] (S3: tbl_df/tbl/data.frame)\n $ species          : Factor w/ 3 levels \"Adelie\",\"Chinstrap\",..: 1 1 1 1 1 1 1 1 1 1 ...\n $ island           : Factor w/ 3 levels \"Biscoe\",\"Dream\",..: 3 3 3 3 3 3 3 3 3 3 ...\n $ bill_length_mm   : num [1:344] 39.1 39.5 40.3 NA 36.7 39.3 38.9 39.2 34.1 42 ...\n $ bill_depth_mm    : num [1:344] 18.7 17.4 18 NA 19.3 20.6 17.8 19.6 18.1 20.2 ...\n $ flipper_length_mm: int [1:344] 181 186 195 NA 193 190 181 195 193 190 ...\n $ body_mass_g      : int [1:344] 3750 3800 3250 NA 3450 3650 3625 4675 3475 4250 ...\n $ sex              : Factor w/ 2 levels \"female\",\"male\": 2 1 1 NA 1 2 1 2 NA NA ...\n $ year             : int [1:344] 2007 2007 2007 2007 2007 2007 2007 2007 2007 2007 ...\n```\n\n\n:::\n:::\n\n\n\n- ✓ `dimnames()` returns the names of the rows and columns of the dataset. \n- ✓ The rows are numbered 1 to 344, and the columns are named `species`, `island`, `bill_length_mm`, `bill_depth_mm`, `flipper_length_mm`, `body_mass_g`, `sex`, `year`.\n- ✓ `str()` provides a concise summary of the dataset's structure. It shows the number of observations (344) and variables (8), the variable names, and their data types.\n- ✓ The dataset contains 344 observations of 8 variables.\n- ✓ The variables are a mix of character, factor, and numeric data types.\n\n:::\n:::\n\n::: {.callout-note appearance=\"simple\"}\n## Self-Assessment Task E.2\n\nHow would you manually calculate the mean value for the `normal_data` we generated in the lecture? **(/3)**\n\n::: {.content-hidden}\n\n**Answer**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(666)\nn <- 5000\nmean <- 0\nsd <- 1\nnormal_data <- rnorm(n, mean, sd)\nround(sum(normal_data) / length(normal_data), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.009\n```\n\n\n:::\n:::\n\n\n- ✓✓✓ The mean value of the `normal_data` is calculated by summing all the data points and dividing by the number of data points. Assign three marks if they correctly calculate the mean of the `normal_data` without using the function `mean()`.\n\n:::\n:::\n\n::: {.callout-note appearance=\"simple\"}\n## Self-Assessment Task E.3\n\nFind the `faithful` dataset and describe both variables in terms of their measures of central tendency. Include graphs in support of your answers (use `ggplot()`), and conclude with a brief statement about the data distribution. **(/10)**\n\n::: {.content-hidden}\n\n**Answer**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load the faithful dataset\ndata(faithful)\nlibrary(ggpubr)\n\nplt1 <- ggplot(faithful, aes(x = eruptions)) +\n  geom_histogram(fill = \"lightblue\", colour = \"black\") +\n  labs(title = \"Eruptions\", x = \"Duration (minutes)\", y = \"Frequency\") +\n  theme_minimal()\n\nplt2 <- ggplot(faithful, aes(x = waiting)) +\n  geom_histogram(fill = \"lightgreen\", colour = \"black\") +\n  labs(title = \"Waiting\", x = \"Time (minutes)\", y = \"Frequency\") +\n  theme_minimal()\n\n# Arrange the plots side by side\nggarrange(plt1, plt2, ncol = 2)\n```\n\n::: {.cell-output-display}\n![Histograms of Old Faithful eruptions and waiting times.](task_e_blocks_files/figure-html/unnamed-chunk-3-1.png)\n:::\n\n```{.r .cell-code}\n# Central tendency measures\nlibrary(e1071)\nkurtosis(faithful$eruptions)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -1.511605\n```\n\n\n:::\n\n```{.r .cell-code}\nkurtosis(faithful$waiting)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -1.156263\n```\n\n\n:::\n\n```{.r .cell-code}\nskewness(faithful$eruptions)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.4135498\n```\n\n\n:::\n\n```{.r .cell-code}\nskewness(faithful$waiting)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.414025\n```\n\n\n:::\n:::\n\n\nThe faithful dataset contains data on the Old Faithful geyser in Yellowstone National Park. It measures the eruption duration (in minutes) and the waiting time between eruptions (also in minutes). We use both graphical and statistical measures to understand the central tendency and overall distribution of each variable.\n\n*1. Eruption Duration*\n\nUsing **ggplot2**, the histogram of eruption durations reveals a bimodal distribution --- one cluster of short eruptions around 2 minutes, another around 4.3 minutes. This visible separation implies that computing a single mean or median would obscure meaningful structural information in the data.\n\nStatistical measures of central tendency support the visual impression:\n\n- Skewness = -0.4135\n- Kurtosis = -1.5116\n\nThe negative skewness suggests a slight asymmetry with a longer left tail, though the bimodal structure renders this value difficult to interpret in isolation. The negative kurtosis implies a flatter distribution compared to a normal curve --- again, a consequence of the data’s underlying bimodality.\n\n*2. Waiting Time*\n\nThe histogram for waiting times similarly displays two overlapping modes, with denser regions around 55, 80 minutes.\n\nThe numerical descriptors are:\n\n- Skewness = -0.4140\n- Kurtosis = -1.1563\n\nAs with eruption durations, the slightly negative skew, platykurtic (low kurtosis) profile again reflect a flattened and spread-out distribution --- not tightly peaked, and not symmetric.\n\n*3. Conclusion About the Data's Distribution*\n\nDue to the bimodal nature of the measured variables, neither conforms to expectations of central tendency characterisation. Yes, we can compute mean, median values but their interpretive value is diminished in the presence of this obvious bimodality. This indicates a structural feature of the physical process operating there (*i.e.* not merely a statistical artefact), suggestive of two regimes of geyser activity (short/long eruptions, brief/long waits).\n\nThe skewness and kurtosis figures reinforce the visual presentation of the data structure: the distributions are asymmetrical and flatter than a normal curve and make parametric assumptions (*e.g.*, normality in linear models) poorly-suited (unless stratified, transformed in some way or another). The histograms and moment-based statistics highlight the need to interrogate shape and structure --- not merely central values --- and would suggest that a more detailed approach is taken to studying the processes operating there.\n\n- ✓ 8/10 for the correct graphical representation and interpretation of the data distribution, and for the calculation of skewness, kurtosis.\n- ✓ 2/10 for some sensible explanation of what this means.\n\n:::\n:::\n\n::: {.callout-note appearance=\"simple\"}\n## Self-Assessment Task E.4\n\nManually calculate the variance and SD for the `normal_data` we generated in the lecture. Make sure your answer is the same as those reported there. **(/5)**\n\n::: {.content-hidden}\n\n**Answer**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Using the equations for sample variance and sd\n# (not the built-in functions), do:\n\n# Variance\n(norm_var <- round(sum((normal_data - mean(normal_data))^2) /\n                     (length(normal_data) - 1), 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.002\n```\n\n\n:::\n\n```{.r .cell-code}\n# Standard deviation\n(norm_sd <- round(sqrt(norm_var), 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.001\n```\n\n\n:::\n:::\n\n\n:::\n:::\n\n::: {.callout-note appearance=\"simple\"}\n## Self-Assessment Task E.5\n\nWrite a few lines of code to demonstrate that the $(0-0.25]$, $(0.25-0.5]$, $(0.5-0.75]$,$(0.75-1]$ quantiles of the `normal_data` we generated in the lecture indeed conform to the formal definition for what quantiles are. I.e., show manually how you can determine that 25% of the observations indeed fall below -0.66 for the `normal_data`. Explain the rationale to your approach. **(/10)**\n\n::: {.content-hidden}\n\n**Answer**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Generate random data from a normal distribution\nset.seed(666)\nn <- 5000 # Number of data points\nmean <- 0\nsd <- 1\nnormal_data <- rnorm(n, mean, sd)\n\n# Calculate the quantiles\nq_25 <- quantile(normal_data, p = 0.25)\nq_50 <- quantile(normal_data, p = 0.50)\nq_75 <- quantile(normal_data, p = 0.75)\nq_100 <- quantile(normal_data, p = 1.00)\n\n# Verify each quantile interval\n(count_0_to_25 <- sum(normal_data <= q_25))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1250\n```\n\n\n:::\n\n```{.r .cell-code}\n(count_25_to_50 <- sum(normal_data > q_25 & normal_data <= q_50))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1250\n```\n\n\n:::\n\n```{.r .cell-code}\n(count_50_to_75 <- sum(normal_data > q_50 & normal_data <= q_75))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1250\n```\n\n\n:::\n\n```{.r .cell-code}\n(count_75_to_100 <- sum(normal_data > q_75 & normal_data <= q_100))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1250\n```\n\n\n:::\n\n```{.r .cell-code}\n# Calculate percentages\n(perc_0_to_25 <- count_0_to_25 / n * 100)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 25\n```\n\n\n:::\n\n```{.r .cell-code}\n(perc_25_to_50 <- count_25_to_50 / n * 100)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 25\n```\n\n\n:::\n\n```{.r .cell-code}\n(perc_50_to_75 <- count_50_to_75 / n * 100)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 25\n```\n\n\n:::\n\n```{.r .cell-code}\n(perc_75_to_100 <- count_75_to_100 / n * 100)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 25\n```\n\n\n:::\n\n```{.r .cell-code}\n# Make a figure to visualise\nlibrary(ggplot2)\nggplot(data.frame(x = normal_data), aes(x = x)) +\n  geom_histogram(binwidth = 0.5, fill = \"lightblue\", colour = \"black\") +\n  geom_vline(xintercept = c(q_25, q_50, q_75), colour = c(\"red\", \"blue\", \"green\"), linetype = \"dashed\") +\n  labs(title = \"Histogram of normal_data with quantiles\", x = \"Value\", y = \"Frequency\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![Quantile verification for simulated normal data.](task_e_blocks_files/figure-html/unnamed-chunk-5-1.png)\n:::\n:::\n\nTo demonstrate that the $(0-0.25]$, $(0.25-0.5]$, $(0.5-0.75]$,$(0.75-1]$ quantiles of our generated `normal_data` conform to the formal definition of quantiles, we must verify that approximately 25% of observations fall within each quantile interval. The formal definition states that the $p$-th quantile is a value $q_p$ such that the proportion of observations less than or equal to $q_p$ is approximately $p$.\n\n*Approach*\n\nIn practice, there are three key steps:\n\n1. Compute the quantiles using the `quantile()` function.\n\n2. Count observations in each quantile interval by using logical expressions to filter the data:\n    - For the first interval $(0-0.25]$: count values $\\leq q_{0.25}$\n    - For the second interval $(0.25-0.5]$: count values $> q_{0.25}$$\\leq q_{0.50}$\n    - For the third interval $(0.5-0.75]$: count values $> q_{0.50}$$\\leq q_{0.75}$\n    - For the fourth interval $(0.75-1]$: count values $> q_{0.75}$\n\n3. Convert counts to percentages by dividing by the total number of observations and multiplying by 100.\n\n- ✓ (x 10) They must correctly calculate the quantiles and verify that approximately 25% (*i.e.* obtain the percentage value in the calcs) of the observations fall within each quantile interval. They should also provide a clear explanation of their approach. No need to have a figure, but some bonus marks may be given if one is provided.\n\n:::\n:::\n\n::: {.callout-note appearance=\"simple\"}\n## Self-Assessment Task E.6\n\nWhy is it important to consider the grouping structures that might be present within our datasets? **(/2)**\n\n::: {.content-hidden}\n\n**Answer**\n\nSimpson's Paradox: Relationships seen in grouped data can reverse/disappear when examining subgroups separately.\n\nHeterogeneity: Different groups within data often exhibit distinct statistical properties. A a single mean (and/or SD) across all observations masks this variability and can provide a distorted view of the real phenomena.\n\nStatistical Independence: Many statistical tests assume independence of observations. If data contain hierarchical or nested structures (*e.g.*, individuals within ecosystems, repeated measurements from the same subjects), this assumption is violated, might invalidate statistical inferences.\n\nGroup-Specific Insights: Analysing data by relevant groupings (*e.g.* a population of a flowering plant in different climatic regions or time periods) may show relevant patterns and differences that would otherwise remain hidden in aggregate statistics.\n\nSo, if we do not account for group structures, summary statistics may reflect artificial central tendencies, dispersions that do not realistically represent any meaningful subpopulation within the data. This limits the validity and usefulness of the analysis.\n\n- ✓ (x 2) ... give some marks if some if what is above is mentioned.\n\n:::\n:::\n\n::: {.callout-note appearance=\"simple\"}\n## Self-Assessment Task E.7\n\nExplain the output of `summary()` when applied to the `penguins` dataset. **(/3)**\n\n::: {.content-hidden}\n\n**Answer**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(penguins)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      species          island    bill_length_mm  bill_depth_mm  \n Adelie   :152   Biscoe   :168   Min.   :32.10   Min.   :13.10  \n Chinstrap: 68   Dream    :124   1st Qu.:39.23   1st Qu.:15.60  \n Gentoo   :124   Torgersen: 52   Median :44.45   Median :17.30  \n                                 Mean   :43.92   Mean   :17.15  \n                                 3rd Qu.:48.50   3rd Qu.:18.70  \n                                 Max.   :59.60   Max.   :21.50  \n                                 NA's   :2       NA's   :2      \n flipper_length_mm  body_mass_g       sex           year     \n Min.   :172.0     Min.   :2700   female:165   Min.   :2007  \n 1st Qu.:190.0     1st Qu.:3550   male  :168   1st Qu.:2007  \n Median :197.0     Median :4050   NA's  : 11   Median :2008  \n Mean   :200.9     Mean   :4202                Mean   :2008  \n 3rd Qu.:213.0     3rd Qu.:4750                3rd Qu.:2009  \n Max.   :231.0     Max.   :6300                Max.   :2009  \n NA's   :2         NA's   :2                                 \n```\n\n\n:::\n:::\n\n\n- The `summary()` function provides a concise summary (obviously) of the dataset's numerical variables. It includes the minimum, 1st quartile, median, mean, 3rd quartile, and maximum values for each variable (*i.e.* central tendency, some view of the dispersion). For categorical variables and it shows the frequency of each level. We caqn gain some basic insight into the distribution of the data and identify potential outliers or missing values.\n- ✓ (x 3)  Assign a few marks if they correctly describe the output of `summary()` with specific reference to the `penguins` dataset. For example:\n    - We can see that the penguin's bill depth (in mm) is close to normally distributed given that the mean value of 17.15 mm is very close to the median of 17.30 mm, with the minimum, maximum values at 13.10 mm and 21.50 mm and respectively. There are two missing values here. The bill length, however, is slightly skewed to the right with a mean of 43.92 mm, a median of 44.45 mm...\n\n:::\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}