---
title: "BCB744 Task E.8"
format:
  html:
    fig-format: png
    fig_retina: 2
    fig-dpi: 400
execute:
  dev: ragg_png
  fig-format: png
params:
  hide_answers: true
---

::: {.callout-note appearance="simple"}
## Self-Assessment Task E.8

a. Using a tidy workflow, assemble a summary table of the **palmerpenguins** dataset that has a similar appearance as that produced by `psych::describe(penguins)`. **(/5)**

    - For bonus marks (which will not count anything) of up to 10% added to Task E, apply a beautiful, creative styling to the table using the  [**kable**](https://cran.r-project.org/web/packages/kableExtra/vignettes/awesome_table_in_html.html) package. Try and make it as publication ready as possible. Refer to a few journal articles to see how to professionally typeset tables.

b. Still using the **palmerpenguins** dataset, perform an exploratory data analysis to investigate the relationship between penguin species, their morphological traits (bill length and bill depth, flipper length, and body mass). Employ the tidyverse approaches learned earlier in the module to explore the data, account for the grouping structures present within the dataset. **(/10)**

c. Provide visualisations (use Figure 4 as inspiration) and summary statistics to support your findings and elaborate on any observed patterns or trends. **(/10)**

d. Ensure your presentation is professional and adhere to the standards required by scientific publications. State the major aims of your analysis and the patterns you seek. Using the combined findings from the EDA and the figures produced here, discuss the findings in a formal Results section. **(/5)**

`r if (params$hide_answers) "::: {.content-hidden}"`

**Answer**

```{r}
#| tbl-cap: "A descriptive summary of the palmerpenguins dataset."
library(kableExtra)
library(tidyverse)
library(palmerpenguins)

# a.
penguins %>%
  select_if(is.numeric) %>%
  psych::describe() %>%
  kable("html") %>%
  kable_styling("striped", full_width = F)

# b.
penguins %>%
  select(species, bill_length_mm, bill_depth_mm, flipper_length_mm, body_mass_g) %>%
  pivot_longer(-species) %>%
  ggplot(aes(x = species, y = value, fill = species)) +
  geom_boxplot() +
  facet_wrap(~name, scales = "free_y") +
  theme_minimal()
```

`r if (params$hide_answers) ":::"`
:::
