documentclass: scrartcl
fontsize: 10pt
geometry:
  - top=26mm
  - bottom=28mm
  - inner=24mm
  - outer=24mm
linestretch: 1.05
colorlinks: true
number-sections: true
toc: true
toc-depth: 3
bibliography: references.bib
csl: styles/marine-biology.csl
fig-dpi: 300
fig-format: pdf
pdf-engine: lualatex
include-in-header:
  - pdf/templates/preamble.tex
template-partials:
  - pdf/templates/before-body.tex
  - pdf/templates/after-body.tex
metadata:
  pdf_series_title: "BCB744 Biostatistics"
  pdf_author: "A. J. Smit"
execute:
  freeze: false
  cache: false
