{
  "hash": "c6235628e183989de7aecd8fa1019c12",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"22. Nonlinear Regression\"\nsubtitle: \"When Straight Lines Are Not Enough\"\ndate: last-modified\ndate-format: \"YYYY/MM/DD\"\nreference-location: margin\n---\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n::: {.callout-note appearance=\"simple\"}\n## In This Chapter\n\n-   Why some biological relationships are mechanistically nonlinear\n-   How nonlinear regression differs from polynomial and additive models\n-   The logic of named nonlinear functions\n-   A worked Michaelis-Menten example\n-   How nonlinear mixed-effects models extend mechanistic curves to repeated-measures data\n-   What to check when fitting nonlinear models\n:::\n\n# Introduction\n\nSome relationships are curved because the biology is curved. Growth saturates, enzyme kinetics asymptote, seasonal cycles oscillate, and responses may level off, bend, or change slope across the range of the predictor. In such cases, a straight-line model is often too rigid.\n\nIn this chapter, I focus specifically on mechanistic nonlinear regression: models where the response is described by a named nonlinear function whose parameters have scientific meaning. Examples include saturating uptake curves, logistic growth, seasonal sine curves, and other biologically motivated responses.\n\nPolynomial regression and GAMs are covered in their own chapters because they answer a different modelling need. Here the emphasis is narrower and stronger: what to do when the biology suggests the form of the curve itself.\n\n# Key Concepts\n\n-   **Nonlinearity** often reflects real biological structure rather than unwanted curvature.\n-   **Flexible regression** can model patterns that a straight line misses.\n-   **Mechanistic nonlinear models are appropriate when the curve has a biologically motivated form.**\n-   **Greater flexibility increases the risk of overfitting** if used carelessly.\n-   **Model choice should follow biological form**, not only convenience or visual preference.\n\n# When This Method Is Appropriate\n\nYou should move beyond a simple linear model when:\n\n-   the fitted residuals show clear curvature;\n-   the biology suggests an asymptote, threshold, saturation, or oscillation;\n-   the response changes differently across the predictor range;\n-   the question concerns parts of the response distribution other than the mean.\n\nThe diagnostic chapters earlier in the sequence already suggested this possibility. This chapter is about what to do next.\n\n# Nature of the Data and Assumptions\n\nMechanistic nonlinear regression is still regression, so the familiar concerns about independence, residual spread, and overall model adequacy do not disappear. In many introductory applications, the response variable is continuous and the residuals are assumed to be approximately normally distributed with constant variance.\n\nThe key distinction is that the mean structure is explicitly nonlinear and tied to a named function. These models are usually fitted by nonlinear least squares with `nls()`, or by mixed-effects extensions when grouped or repeated-measures data are present.\n\nThe practical point is that you choose a non-linear model because the straight-line model is inadequate and because the curved alternative matches the biological process or the inferential question more closely. And it looks pretty and complicated.\n\n# The Core Equation\n\nThe general form of a nonlinear regression is:\n\n$$Y_i = f(X_i, \\theta) + \\epsilon_i$$ {#eq-nonlinear}\n\nIn @eq-nonlinear, $f(\\cdot)$ is a biologically chosen nonlinear function and $\\theta$ represents the parameter set that defines its shape. This chapter then uses a Michaelis-Menten curve as the main worked example of that general idea.\n\n# R Functions\n\nSome of the most useful R functions are:\n\n-   `nls()` for nonlinear least-squares models;\n-   `nlme::nlme()` when nonlinear relationships occur in grouped or repeated-measures data.\n\nExamples:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm(response ~ poly(x, degree = 2), data = df)\nnls(y ~ Vmax * x / (Km + x), data = df,\n    start = list(Vmax = 1, Km = 1))\nnlme::nlme(y ~ Vmax * x / (Km + x), data = df, ...)\n```\n:::\n\n\nOne practical difference from ordinary regression is that `nls()` usually needs sensible starting values. Unlike `lm()`, it uses an iterative search for the best-fitting parameter values, and poor starting values can prevent convergence.\n\n# Example 1: Why Use a Mechanistic Nonlinear Model?\n\nThe first decision is whether the biology gives you a reason to prefer a specific nonlinear function rather than a descriptive curve.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Examples of curved models fitted to simulated data. A polynomial can capture modest curvature, a GAM can adapt flexibly to the data, and a mechanistic nonlinear model can represent a known saturating biological response.](22-nonlinear-regression_files/figure-html/fig-main-families-1.svg){#fig-main-families}\n:::\n:::\n\n\n@fig-main-families shows three broad situations:\n\n-   A polynomial model can describe modest curvature, but it is mainly descriptive.\n-   A GAM is very useful when the relationship is clearly curved but its exact form is unknown or not informative.\n-   A mechanistic nonlinear model is most attractive when the biology suggests a specific function, because its parameters can often be interpreted directly.\n\nThat last point is important. If we know the process should saturate, as in nutrient uptake kinetics, a mechanistic model tells us more than a flexible smoother. It gives us interpretable parameters such as an asymptote or a half-saturation constant.\n\n# Example 2: Algal Nutrient Uptake Kinetics\n\nWe can measure algal nutrient uptake rates using a multiple flask experiment. We prepare a series of flasks, each containing a different initial concentration of the substrate nutrient, and then estimate nutrient uptake rate over a fixed time interval. The result is a set of uptake rates, $V$ ($\\mu\\mathrm{mol}\\ \\mathrm{N}\\ \\mathrm{g}^{-1}\\ \\mathrm{h}^{-1}$), paired with substrate concentrations, $[S]$ ($\\mu\\mathrm{mol}\\ \\mathrm{L}^{-1}$).\n\nIf you need a reminder of the biological and experimental context behind these data, refer back to the BDC223 nutrient-uptake material in [Lecture 8a: Nutrient Uptake](../../BDC223/L08a-nutrient_uptake.qmd), [Lecture 8b: Uptake Kinetics -- Michaelis-Menten](../../BDC223/L08b-nutrients_michaelis_menten.qmd), and [Lab 4: Uptake Kinetics -- Michaelis-Menten](../../BDC223/Lab4_nitrogen_uptake.qmd). Those pages explain the experimental principles of the multiple-flask design in much more detail than is needed here.\n\nApplied to algae, the Michaelis-Menten model assumes an irreversible uptake process that saturates at high substrate concentrations. It effectively quantifies key characteristics of the nutrient uptake system, including the maximum uptake rate and the alga's affinity for the nutrient:\n\n$$V_i = \\frac{V_{max} \\cdot [S_i]}{K_m + [S_i]} + \\epsilon_i$$ {#eq-mm}\n\nIn @eq-mm:\n\n-   $V_i$ is the uptake rate at the $i$-th observation ($\\mu\\mathrm{mol}\\ \\mathrm{N}\\ \\mathrm{g}^{-1}\\ \\mathrm{h}^{-1}$);\n-   $V_{max}$ is the maximum nutrient uptake rate achieved ($\\mu\\mathrm{mol}\\ \\mathrm{N}\\ \\mathrm{g}^{-1}\\ \\mathrm{h}^{-1}$);\n-   $[S_i]$ is the substrate concentration at the $i$-th observation ($\\mu\\mathrm{mol}\\ \\mathrm{L}^{-1}$);\n-   $K_m$ is the substrate concentration at which uptake reaches half of $V_{max}$ ($\\mu\\mathrm{mol}\\ \\mathrm{L}^{-1}$); and\n-   $\\epsilon_i$ is the residual error.\n\nThe two parameters are biologically meaningful. $V_{max}$ represents the maximum capacity of the alga to utilise the nutrient and is measured in $\\mu\\mathrm{mol}\\ \\mathrm{N}\\ \\mathrm{g}^{-1}\\ \\mathrm{h}^{-1}$. $K_m$ describes the affinity of the uptake system for that nutrient and is measured in $\\mu\\mathrm{mol}\\ \\mathrm{L}^{-1}$. Lower values of $K_m$ indicate higher affinity.\n\n## Do an Exploratory Data Analysis (EDA)\n\nTo demonstrate fitting a nonlinear model to $V$ versus $[S]$ data from a multiple flask experiment, I simulate data across a range of substrate concentrations. The dataset consists of five replicate flasks for each of 13 substrate concentrations.\n\n\n::: {.cell tbl-cap='Preview of the simulated multiple-flask dataset (first and last four rows).'}\n\n```{.r .cell-code}\nconc_vec <- c(0, 0.1, 0.5, 2, 5, 7.5, 10, 12.5, 15, 17.5, 20, 25, 30)\nn_rep <- 5\nKm_vec <- c(10)\nVmax_vec <- c(50)\nKm_vec_sd <- c(1.2)\nVmax_vec_sd <- c(0.7)\n\nmf_data <- generate_data(\n  n_trt = 1,\n  n_rep = n_rep,\n  conc_vec = conc_vec,\n  Km_vec = Km_vec,\n  Vmax_vec = Vmax_vec,\n  Km_vec_sd = Km_vec_sd,\n  Vmax_vec_sd = Vmax_vec_sd\n) |>\n  select(rep, S, V)\n\nmf_data |>\n  slice(c(1:4, (n() - 3):n())) |>\n  gt::gt() |>\n  gt::fmt_number(columns = c(S, V), decimals = 2)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"oyprksffsj\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#oyprksffsj table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#oyprksffsj thead, #oyprksffsj tbody, #oyprksffsj tfoot, #oyprksffsj tr, #oyprksffsj td, #oyprksffsj th {\n  border-style: none;\n}\n\n#oyprksffsj p {\n  margin: 0;\n  padding: 0;\n}\n\n#oyprksffsj .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#oyprksffsj .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#oyprksffsj .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#oyprksffsj .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#oyprksffsj .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#oyprksffsj .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#oyprksffsj .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#oyprksffsj .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#oyprksffsj .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#oyprksffsj .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#oyprksffsj .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#oyprksffsj .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#oyprksffsj .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#oyprksffsj .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#oyprksffsj .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#oyprksffsj .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#oyprksffsj .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#oyprksffsj .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#oyprksffsj .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#oyprksffsj .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#oyprksffsj .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#oyprksffsj .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#oyprksffsj .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#oyprksffsj .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#oyprksffsj .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#oyprksffsj .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#oyprksffsj .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#oyprksffsj .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#oyprksffsj .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#oyprksffsj .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#oyprksffsj .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#oyprksffsj .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#oyprksffsj .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#oyprksffsj .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#oyprksffsj .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#oyprksffsj .gt_left {\n  text-align: left;\n}\n\n#oyprksffsj .gt_center {\n  text-align: center;\n}\n\n#oyprksffsj .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#oyprksffsj .gt_font_normal {\n  font-weight: normal;\n}\n\n#oyprksffsj .gt_font_bold {\n  font-weight: bold;\n}\n\n#oyprksffsj .gt_font_italic {\n  font-style: italic;\n}\n\n#oyprksffsj .gt_super {\n  font-size: 65%;\n}\n\n#oyprksffsj .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#oyprksffsj .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#oyprksffsj .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#oyprksffsj .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#oyprksffsj .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#oyprksffsj .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#oyprksffsj .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#oyprksffsj .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#oyprksffsj div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"rep\">rep</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"S\">S</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"V\">V</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"rep\" class=\"gt_row gt_center\">1</td>\n<td headers=\"S\" class=\"gt_row gt_right\">0.00</td>\n<td headers=\"V\" class=\"gt_row gt_right\">0.00</td></tr>\n    <tr><td headers=\"rep\" class=\"gt_row gt_center\">2</td>\n<td headers=\"S\" class=\"gt_row gt_right\">0.00</td>\n<td headers=\"V\" class=\"gt_row gt_right\">0.00</td></tr>\n    <tr><td headers=\"rep\" class=\"gt_row gt_center\">3</td>\n<td headers=\"S\" class=\"gt_row gt_right\">0.00</td>\n<td headers=\"V\" class=\"gt_row gt_right\">0.00</td></tr>\n    <tr><td headers=\"rep\" class=\"gt_row gt_center\">4</td>\n<td headers=\"S\" class=\"gt_row gt_right\">0.00</td>\n<td headers=\"V\" class=\"gt_row gt_right\">0.00</td></tr>\n    <tr><td headers=\"rep\" class=\"gt_row gt_center\">2</td>\n<td headers=\"S\" class=\"gt_row gt_right\">30.00</td>\n<td headers=\"V\" class=\"gt_row gt_right\">35.12</td></tr>\n    <tr><td headers=\"rep\" class=\"gt_row gt_center\">3</td>\n<td headers=\"S\" class=\"gt_row gt_right\">30.00</td>\n<td headers=\"V\" class=\"gt_row gt_right\">39.07</td></tr>\n    <tr><td headers=\"rep\" class=\"gt_row gt_center\">4</td>\n<td headers=\"S\" class=\"gt_row gt_right\">30.00</td>\n<td headers=\"V\" class=\"gt_row gt_right\">37.78</td></tr>\n    <tr><td headers=\"rep\" class=\"gt_row gt_center\">5</td>\n<td headers=\"S\" class=\"gt_row gt_right\">30.00</td>\n<td headers=\"V\" class=\"gt_row gt_right\">36.73</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Plot of uptake rate, V, as a function of substrate concentration, [S], for a multiple flask experiment. The relationship is clearly curved and tends towards saturation.](22-nonlinear-regression_files/figure-html/fig-mf-eda-1.svg){#fig-mf-eda}\n:::\n:::\n\n\nThe plot in @fig-mf-eda already suggests that a straight line is not the right model. Uptake increases quickly away from low substrate concentrations and then begins to level off when the concentrations become higher. That is exactly the sort of pattern for which a Michaelis-Menten model was designed.\n\nYou will also often see greater spread in uptake rate at higher substrate concentrations. That happens because the high-concentration part of the curve approaches the enzyme-limited region. Once transport and assimilation systems are near saturation, small biological differences among flasks in tissue condition, enzyme capacity, light history, or temperature response can translate into visibly different realised uptake rates. At low concentrations, by contrast, uptake is constrained more strongly by substrate availability itself, so the responses are often pulled into a narrower range.\n\n## State the Model Question\n\nAt this point, two related questions arise.\n\nThe first is descriptive and mechanistic: can we estimate the uptake parameters $V_{max}$ ($\\mu\\mathrm{mol}\\ \\mathrm{N}\\ \\mathrm{g}^{-1}\\ \\mathrm{h}^{-1}$) and $K_m$ ($\\mu\\mathrm{mol}\\ \\mathrm{L}^{-1}$) from these data?\n\nThe second is comparative: does a Michaelis-Menten model fit these data better than a simple linear model?\n\nThose are not the same question. The first is about parameter estimation within a nonlinear biological model. The second is about choosing between two competing mean structures.\n\n## Fit the Model\n\nThe Michaelis-Menten model is fit with `nls()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnls_mod <- nls(\n  V ~ mm_fun(S, Vmax, Km),\n  data = mf_data,\n  start = c(Vmax = 30, Km = 5)\n)\n\nsummary(nls_mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nFormula: V ~ mm_fun(S, Vmax, Km)\n\nParameters:\n     Estimate Std. Error t value Pr(>|t|)    \nVmax  51.4417     1.1770   43.70   <2e-16 ***\nKm    10.5507     0.5975   17.66   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.312 on 63 degrees of freedom\n\nNumber of iterations to convergence: 3 \nAchieved convergence tolerance: 8.864e-06\n```\n\n\n:::\n:::\n\n\nThe starting values do not have to be exact, but they should be sensible. Here we know from the plot that the asymptote is probably somewhere around $40$ to $50\\ \\mu\\mathrm{mol}\\ \\mathrm{N}\\ \\mathrm{g}^{-1}\\ \\mathrm{h}^{-1}$, and that the half-saturation constant is likely to be in the single digits of $\\mu\\mathrm{mol}\\ \\mathrm{L}^{-1}$.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Michaelis-Menten model fitted to the uptake data. The dashed lines indicate the estimated Km and Vmax values.](22-nonlinear-regression_files/figure-html/fig-mf-fit-1.svg){#fig-mf-fit}\n:::\n:::\n\n\n## Check Diagnostics\n\nBecause this is a least-squares nonlinear model, residual diagnostics are interpreted much as they are for ordinary regression.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmf_data <- mf_data |>\n  mutate(\n    fitted = fitted(nls_mod),\n    resid = resid(nls_mod)\n  )\n\nshapiro.test(mf_data$resid)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  mf_data$resid\nW = 0.97225, p-value = 0.1517\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Basic diagnostics for the Michaelis-Menten fit. The residuals show no serious trend with the fitted values, and the distribution is approximately symmetric.](22-nonlinear-regression_files/figure-html/fig-mf-diagnostics-1.svg){#fig-mf-diagnostics}\n:::\n:::\n\n\nThe diagnostics in @fig-mf-diagnostics do not suggest any serious problem. The residual spread is fairly even, and the histogram is approximately symmetric. As always, you should not rely on a single formal test, but the residual behaviour is consistent with a usable fit.\n\n## Interpret the Results\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm_mod <- lm(V ~ S, data = mf_data)\nmodel_comp <- anova(lm_mod, nls_mod)\nf_stat <- model_comp$F[2]\n\nAIC(lm_mod, nls_mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        df      AIC\nlm_mod   3 395.8491\nnls_mod  3 223.6862\n```\n\n\n:::\n\n```{.r .cell-code}\nBIC(lm_mod, nls_mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        df      BIC\nlm_mod   3 402.3723\nnls_mod  3 230.2094\n```\n\n\n:::\n\n```{.r .cell-code}\nmodel_comp\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: V\n          Df  Sum Sq Mean Sq F value    Pr(>F)    \nS          1 10274.8 10274.8  422.59 < 2.2e-16 ***\nResiduals 63  1531.8    24.3                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nThe fitted nonlinear model gives estimated values for $V_{max}$ and $K_m$, and these are the biologically meaningful outputs of the analysis. The estimated $V_{max}$ is the asymptotic uptake rate in $\\mu\\mathrm{mol}\\ \\mathrm{N}\\ \\mathrm{g}^{-1}\\ \\mathrm{h}^{-1}$, while $K_m$ indicates the substrate concentration in $\\mu\\mathrm{mol}\\ \\mathrm{L}^{-1}$ at which the uptake rate reaches half of that asymptote.\n\nThe model comparison also matters. If the linear and Michaelis-Menten models are both fitted to the same data, the nonlinear model has markedly lower information criteria and a much smaller residual error. That supports the biological interpretation already suggested by the plot; that is, uptake increases with substrate concentration, but it does so in a saturating rather than indefinitely linear way.\n\n## Reporting\n\n::: {.callout-note appearance=\"simple\"}\n## Write-Up\n\n**Methods**\n\nNutrient uptake rate was modelled as a function of substrate concentration with a Michaelis-Menten nonlinear regression fitted by nonlinear least squares. The nonlinear model was compared with a simple linear regression using information criteria and nested model comparison to assess whether the saturating form provided a better description of the data.\n\n**Results**\n\nNutrient uptake increased rapidly with substrate concentration at low concentrations and then approached an asymptote, consistent with Michaelis-Menten kinetics (@fig-mf-fit). The fitted nonlinear model estimated a maximum uptake rate of 51.44 $\\mu\\mathrm{mol}\\ \\mathrm{N}\\ \\mathrm{g}^{-1}\\ \\mathrm{h}^{-1}$ and a half-saturation constant of 10.55 $\\mu\\mathrm{mol}\\ \\mathrm{L}^{-1}$. Relative to a simple linear regression, the Michaelis-Menten model provided the better description of the data, with lower AIC and BIC values and a significant improvement in fit (F = NA, `p < 0.05`).\n\n**Discussion**\n\nThe main biological point is that uptake is saturating rather than indefinitely linear over the observed concentration range. That matters because the fitted parameters now speak directly to uptake capacity and nutrient affinity.\n:::\n\n## What If We Add Treatments?\n\nExperiments are seldom as simple as the one above. Consider an experiment designed to assess whether an experimental treatment, such as light intensity or seawater temperature, affects nutrient uptake kinetics. It is biologically plausible to expect that each treatment will result in unique $V_{max}$ values ($\\mu\\mathrm{mol}\\ \\mathrm{N}\\ \\mathrm{g}^{-1}\\ \\mathrm{h}^{-1}$) and $K_m$ values ($\\mu\\mathrm{mol}\\ \\mathrm{L}^{-1}$).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmf_data2 <- generate_data(\n  n_trt = 3,\n  n_rep = 5,\n  conc_vec = conc_vec,\n  Km_vec = c(10, 8, 6),\n  Vmax_vec = c(50, 40, 22),\n  Km_vec_sd = c(1.2, 1.1, 1.0),\n  Vmax_vec_sd = c(0.7, 1.0, 0.8)\n)\n```\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Simulated nutrient uptake curves for three treatments. The pattern suggests treatment-specific nonlinear responses rather than a single shared curve.](22-nonlinear-regression_files/figure-html/fig-mf-treatment-1.svg){#fig-mf-treatment}\n:::\n:::\n\n\nThe treatment-specific curvature in @fig-mf-treatment makes the modelling problem more challenging and exciting. A separate `nls()` fit can be used for each treatment, or a nonlinear mixed-effects model can be used when dependence or grouping must be handled explicitly. That is the nonlinear counterpart of the fixed-effects and mixed-effects logic introduced in [Chapter 19](19-dependence-and-mixed-models.qmd). If the response is also non-normal, you are moving towards the broader territory covered in [Chapter 20](20-generalised-linear-models.qmd).\n\nThe important point is that nonlinear modelling “draws a curve” *and* it chooses a mean structure that matches the process and then extending that structure carefully when treatments, dependence, or more complicated designs are present.\n\n## Repeated-Measures Extension\n\nThe next extension appears when the same experimental unit is measured repeatedly across the concentration gradient. For example, you might measure uptake repeatedly on the same thallus, plant, or mesocosm under several substrate concentrations. At that point, the observations within each unit are no longer independent, so a separate `nls()` fit per unit or a pooled `nls()` fit is no longer enough.\n\nThe nonlinear mixed-effects version of the model keeps the Michaelis-Menten mean structure but lets one or more parameters vary among experimental units. A common starting point is to allow each unit to have its own `Vmax` ($\\mu\\mathrm{mol}\\ \\mathrm{N}\\ \\mathrm{g}^{-1}\\ \\mathrm{h}^{-1}$) around a population-level mean:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnlme::nlme(\n  V ~ mm_fun(S, Vmax, Km),\n  data = uptake_long,\n  fixed = Vmax + Km ~ treatment,\n  random = Vmax ~ 1 | individual,\n  start = c(...)\n)\n```\n:::\n\n\nIn that formulation, the fixed effects describe how treatment shifts the average kinetic parameters, while the random effect acknowledges that repeated observations from the same individual share the same underlying uptake curve. A full worked example needs a dataset with true repeated measurements on the same biological units and enough observations per unit to estimate the random-effects structure sensibly.\n\n# Example 3: Repeated-Measures Michaelis-Menten Kinetics\n\nThe previous examples treated each flask as an independent unit observed once at each starting concentration. A perturbation experiment is different. The same flask is sampled repeatedly through time as nutrient concentration declines, so the observations from that flask are correlated. This is exactly the kind of dependence problem introduced in [Chapter 19](19-dependence-and-mixed-models.qmd), except that the mean structure is now nonlinear rather than linear.\n\nFor the BDC223 treatment of this experimental design, including depletion curves and the distinction between perturbation and multiple-flask methods, see [Lecture 8a: Nutrient Uptake](../../BDC223/L08a-nutrient_uptake.qmd), [Lecture 8b: Uptake Kinetics -- Michaelis-Menten](../../BDC223/L08b-nutrients_michaelis_menten.qmd), and [Lab 4: Uptake Kinetics -- Michaelis-Menten](../../BDC223/Lab4_nitrogen_uptake.qmd). Here we pick up at the point where those experiments become a modelling problem.\n\n## Example Dataset\n\nThese data come from a perturbation experiment on the red seaweed *Gracilaria* sp. Flasks were enriched to approximately 55--60 $\\mu M$ nitrate and sampled repeatedly over roughly 2.5 hours. Uptake rates were measured under three levels of water movement (`low`, `med`, `high`), with three replicate flasks per treatment.\n\n\n::: {.cell tbl-cap='Preview of the perturbation dataset (first eight rows).'}\n\n```{.r .cell-code}\nmm_data <- read.csv(file.path(\"..\", \"..\", \"data\", \"BCB744\", \"flow_rates.txt\"), sep = \"\") |>\n  mutate(\n    flask = factor(flask),\n    trt = factor(trt, levels = c(\"low\", \"med\", \"high\"))\n  )\n\nhead(mm_data, 8) |>\n  gt::gt() |>\n  gt::fmt_number(columns = c(V, S), decimals = 2)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"nrmpannemu\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#nrmpannemu table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#nrmpannemu thead, #nrmpannemu tbody, #nrmpannemu tfoot, #nrmpannemu tr, #nrmpannemu td, #nrmpannemu th {\n  border-style: none;\n}\n\n#nrmpannemu p {\n  margin: 0;\n  padding: 0;\n}\n\n#nrmpannemu .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#nrmpannemu .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#nrmpannemu .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#nrmpannemu .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#nrmpannemu .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#nrmpannemu .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#nrmpannemu .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#nrmpannemu .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#nrmpannemu .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#nrmpannemu .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#nrmpannemu .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#nrmpannemu .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#nrmpannemu .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#nrmpannemu .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#nrmpannemu .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#nrmpannemu .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#nrmpannemu .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#nrmpannemu .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#nrmpannemu .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nrmpannemu .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#nrmpannemu .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#nrmpannemu .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#nrmpannemu .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nrmpannemu .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#nrmpannemu .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#nrmpannemu .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#nrmpannemu .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nrmpannemu .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#nrmpannemu .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#nrmpannemu .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#nrmpannemu .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#nrmpannemu .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#nrmpannemu .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nrmpannemu .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#nrmpannemu .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nrmpannemu .gt_left {\n  text-align: left;\n}\n\n#nrmpannemu .gt_center {\n  text-align: center;\n}\n\n#nrmpannemu .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#nrmpannemu .gt_font_normal {\n  font-weight: normal;\n}\n\n#nrmpannemu .gt_font_bold {\n  font-weight: bold;\n}\n\n#nrmpannemu .gt_font_italic {\n  font-style: italic;\n}\n\n#nrmpannemu .gt_super {\n  font-size: 65%;\n}\n\n#nrmpannemu .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#nrmpannemu .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#nrmpannemu .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#nrmpannemu .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#nrmpannemu .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#nrmpannemu .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#nrmpannemu .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#nrmpannemu .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#nrmpannemu div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"flask\">flask</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"trt\">trt</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"V\">V</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"S\">S</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"flask\" class=\"gt_row gt_center\">a1</td>\n<td headers=\"trt\" class=\"gt_row gt_center\">low</td>\n<td headers=\"V\" class=\"gt_row gt_right\">10.80</td>\n<td headers=\"S\" class=\"gt_row gt_right\">60.20</td></tr>\n    <tr><td headers=\"flask\" class=\"gt_row gt_center\">a2</td>\n<td headers=\"trt\" class=\"gt_row gt_center\">low</td>\n<td headers=\"V\" class=\"gt_row gt_right\">10.00</td>\n<td headers=\"S\" class=\"gt_row gt_right\">61.10</td></tr>\n    <tr><td headers=\"flask\" class=\"gt_row gt_center\">a3</td>\n<td headers=\"trt\" class=\"gt_row gt_center\">low</td>\n<td headers=\"V\" class=\"gt_row gt_right\">14.10</td>\n<td headers=\"S\" class=\"gt_row gt_right\">60.80</td></tr>\n    <tr><td headers=\"flask\" class=\"gt_row gt_center\">a1</td>\n<td headers=\"trt\" class=\"gt_row gt_center\">low</td>\n<td headers=\"V\" class=\"gt_row gt_right\">7.30</td>\n<td headers=\"S\" class=\"gt_row gt_right\">59.40</td></tr>\n    <tr><td headers=\"flask\" class=\"gt_row gt_center\">a2</td>\n<td headers=\"trt\" class=\"gt_row gt_center\">low</td>\n<td headers=\"V\" class=\"gt_row gt_right\">15.40</td>\n<td headers=\"S\" class=\"gt_row gt_right\">59.40</td></tr>\n    <tr><td headers=\"flask\" class=\"gt_row gt_center\">a3</td>\n<td headers=\"trt\" class=\"gt_row gt_center\">low</td>\n<td headers=\"V\" class=\"gt_row gt_right\">9.50</td>\n<td headers=\"S\" class=\"gt_row gt_right\">59.40</td></tr>\n    <tr><td headers=\"flask\" class=\"gt_row gt_center\">a1</td>\n<td headers=\"trt\" class=\"gt_row gt_center\">low</td>\n<td headers=\"V\" class=\"gt_row gt_right\">12.50</td>\n<td headers=\"S\" class=\"gt_row gt_right\">56.70</td></tr>\n    <tr><td headers=\"flask\" class=\"gt_row gt_center\">a2</td>\n<td headers=\"trt\" class=\"gt_row gt_center\">low</td>\n<td headers=\"V\" class=\"gt_row gt_right\">10.50</td>\n<td headers=\"S\" class=\"gt_row gt_right\">56.20</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n## Do an Exploratory Data Analysis (EDA)\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Repeated-measures uptake data from the perturbation experiment. Each dashed line traces one flask through time as substrate concentration declines.](22-nonlinear-regression_files/figure-html/fig-mm-eda-1.svg){#fig-mm-eda}\n:::\n:::\n\n\nThe relationship in @fig-mm-eda is again saturating, so a Michaelis-Menten mean structure is still sensible. The important difference is that each dashed trajectory comes from the same flask measured repeatedly. That means the residuals are likely to be correlated within flask, and the flasks are nested within treatment.\n\n## State the Model Question\n\nThe biological question is whether the Michaelis-Menten parameters differ among water-movement treatments once the repeated-measures structure of the perturbation experiment is taken into account. Here that means asking whether treatment shifts $V_{max}$ ($\\mu\\mathrm{mol}\\ \\mathrm{N}\\ \\mathrm{g}^{-1}\\ \\mathrm{h}^{-1}$) and/or $K_m$ ($\\mu\\mathrm{mol}\\ \\mathrm{L}^{-1}$).\n\n$$H_{0}: V_{max} \\text{ and } K_m \\text{ are the same across treatments after accounting for flask-level dependence}$$\n$$H_{a}: \\text{At least one of } V_{max} \\text{ or } K_m \\text{ differs among treatments after accounting for flask-level dependence}$$\n\n## Fit the Model\n\nWe compare two nonlinear mixed-effects models. The first is a **global** model in which all treatments share the same Michaelis-Menten parameters. The second allows `Vmax` and `Km` to vary by treatment while retaining the same repeated-measures structure.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnum_levels <- nlevels(mm_data$trt)\n\nstart_global <- c(\n  Vmax = max(mm_data$V),\n  Km = median(mm_data$S)\n)\n\nstart_trt <- list(\n  fixed = c(\n    Vmax = rep(max(mm_data$V), num_levels),\n    Km = rep(median(mm_data$S), num_levels)\n  )\n)\n\nmm_global <- nlme(\n  V ~ mm_fun(S, Vmax, Km),\n  data = mm_data,\n  fixed = Vmax + Km ~ 1,\n  random = Vmax ~ 1 | trt/flask,\n  groups = ~ trt/flask,\n  correlation = corAR1(form = ~ 1 | trt/flask),\n  start = start_global,\n  method = \"ML\"\n)\n\nmm_trt <- nlme(\n  V ~ mm_fun(S, Vmax, Km),\n  data = mm_data,\n  fixed = list(Vmax ~ trt, Km ~ trt),\n  random = Vmax ~ 1 | trt/flask,\n  groups = ~ trt/flask,\n  correlation = corAR1(form = ~ 1 | trt/flask),\n  start = start_trt,\n  method = \"ML\"\n)\n\nmm_comp <- anova(mm_global, mm_trt)\n\nmm_comp\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          Model df      AIC      BIC    logLik   Test  L.Ratio p-value\nmm_global     1  6 656.0306 673.3274 -322.0153                        \nmm_trt        2 10 648.1068 676.9348 -314.0534 1 vs 2 15.92387  0.0031\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(mm_trt)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNonlinear mixed-effects model fit by maximum likelihood\n  Model: V ~ mm_fun(S, Vmax, Km) \n  Data: mm_data \n       AIC      BIC    logLik\n  648.1068 676.9348 -314.0534\n\nRandom effects:\n Formula: Vmax ~ 1 | trt\n        Vmax.(Intercept)\nStdDev:     0.0001334691\n\n Formula: Vmax ~ 1 | flask %in% trt\n        Vmax.(Intercept) Residual\nStdDev:     2.572032e-05 2.641716\n\nCorrelation Structure: AR(1)\n Formula: ~1 | trt/flask \n Parameter estimate(s):\n      Phi \n0.1539479 \nFixed effects:  list(Vmax ~ trt, Km ~ trt) \n                      Value Std.Error  DF   t-value p-value\nVmax.(Intercept)  13.727753  2.011411 118  6.824938  0.0000\nVmax.trtmed       -1.917486  2.239487 118 -0.856217  0.3936\nVmax.trthigh       1.623586  2.258494 118  0.718880  0.4736\nKm.(Intercept)    16.847854  7.413292 118  2.272655  0.0249\nKm.trtmed        -11.917482  7.783803 118 -1.531062  0.1284\nKm.trthigh       -11.480851  7.623149 118 -1.506051  0.1347\n Correlation: \n               Vm.(I) Vmx.trtm Vmx.trth Km.(I) Km.trtm\nVmax.trtmed    -0.898                                 \nVmax.trthigh   -0.891  0.800                          \nKm.(Intercept)  0.923 -0.829   -0.822                 \nKm.trtmed      -0.879  0.892    0.783   -0.952        \nKm.trthigh     -0.898  0.806    0.877   -0.972  0.926 \n\nStandardized Within-Group Residuals:\n       Min         Q1        Med         Q3        Max \n-2.0770735 -0.7687045 -0.2436554  0.4550069  3.3221378 \n\nNumber of Observations: 132\nNumber of Groups: \n           trt flask %in% trt \n             3              9 \n```\n\n\n:::\n:::\n\n\nThree parts of the specification are important:\n\n-   `fixed = ... ~ trt` allows the Michaelis-Menten parameters to differ among treatments.\n-   `random = Vmax ~ 1 | trt/flask` allows replicate flasks within treatments to vary in baseline uptake capacity.\n-   `correlation = corAR1(...)` acknowledges that repeated measurements within the same flask are serially correlated.\n\nThis is the nonlinear counterpart of the grouped-dependence ideas from Chapter 19. The model still estimates a mechanistic curve, but it now does so in a way that respects repeated measurement on the same experimental unit while keeping the kinetic parameters in their usual units of $\\mu\\mathrm{mol}\\ \\mathrm{N}\\ \\mathrm{g}^{-1}\\ \\mathrm{h}^{-1}$ ($V_{max}$) and $\\mu\\mathrm{mol}\\ \\mathrm{L}^{-1}$ ($K_m$).\n\n## Check Diagnostics\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmm_data <- mm_data |>\n  mutate(\n    fitted_nlme = fitted(mm_trt),\n    resid_nlme = resid(mm_trt, type = \"pearson\")\n  )\n\nshapiro.test(mm_data$resid_nlme)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  mm_data$resid_nlme\nW = 0.97547, p-value = 0.01719\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Basic diagnostics for the nonlinear mixed-effects model. The residual pattern is acceptable for a teaching example, with no strong trend against the fitted values.](22-nonlinear-regression_files/figure-html/fig-mm-diagnostics-1.svg){#fig-mm-diagnostics}\n:::\n:::\n\n\nThe diagnostics in @fig-mm-diagnostics show whether the fitted nonlinear mean structure and the residual assumptions are at least broadly compatible with the data.\n\n## Interpret the Results\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncoef_mm <- fixed.effects(mm_trt)\n\nVmax_by_trt <- c(\n  low = coef_mm[\"Vmax.(Intercept)\"],\n  med = coef_mm[\"Vmax.(Intercept)\"] + coef_mm[\"Vmax.trtmed\"],\n  high = coef_mm[\"Vmax.(Intercept)\"] + coef_mm[\"Vmax.trthigh\"]\n)\n\nKm_by_trt <- c(\n  low = coef_mm[\"Km.(Intercept)\"],\n  med = coef_mm[\"Km.(Intercept)\"] + coef_mm[\"Km.trtmed\"],\n  high = coef_mm[\"Km.(Intercept)\"] + coef_mm[\"Km.trthigh\"]\n)\n\nparam_tbl <- tibble(\n  trt = factor(c(\"low\", \"med\", \"high\"), levels = c(\"low\", \"med\", \"high\")),\n  Vmax = round(unname(Vmax_by_trt), 2),\n  Km = round(unname(Km_by_trt), 2)\n)\n\nparam_tbl\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  trt    Vmax    Km\n  <fct> <dbl> <dbl>\n1 low    13.7 16.8 \n2 med    11.8  4.93\n3 high   15.4  5.37\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Treatment-specific nonlinear mixed-effects fits for the perturbation experiment.](22-nonlinear-regression_files/figure-html/fig-mm-fit-1.svg){#fig-mm-fit}\n:::\n:::\n\n\nThe likelihood-ratio test comparing the shared-parameter model with the treatment-specific model shows that allowing `Vmax` and `Km` to vary by treatment improves fit strongly (`p = 0.0031`). That is the main inferential result. The treatment-specific parameter estimates suggest that the low-flow treatment has the highest fitted `Km` in $\\mu\\mathrm{mol}\\ \\mathrm{L}^{-1}$, while the medium and high treatments reach similar uptake behaviour at lower substrate concentrations. The fitted `Vmax` values, measured in $\\mu\\mathrm{mol}\\ \\mathrm{N}\\ \\mathrm{g}^{-1}\\ \\mathrm{h}^{-1}$, differ less strongly than the `Km` estimates in this example.\n\nIn nonlinear mixed-effects work, the global model comparison is often more informative than reading each coefficient one-by-one as though they were ordinary linear-model terms. The treatment effect here is a shift in the shape of the kinetic curve under a repeated-measures design.\n\n## Reporting\n\n::: {.callout-note appearance=\"simple\"}\n## Write-Up\n\n**Methods**\n\nNitrate-uptake kinetics were analysed with a Michaelis-Menten nonlinear mixed-effects model fitted to repeated observations from perturbation flasks. Treatment was included as a fixed effect on the Michaelis-Menten parameters (`Vmax` and `Km`), replicate flasks were treated as random effects nested within treatment, and a first-order autoregressive correlation structure was used to account for serial dependence among repeated measurements within each flask. A global model with shared kinetic parameters across treatments was compared with a treatment-specific model using a likelihood-ratio test.\n\n**Results**\n\nAllowing Michaelis-Menten parameters to vary among treatments improved model fit relative to the shared-parameter model (likelihood-ratio test: L.Ratio = 15.92, `p = 0.0031`). The fitted treatment-specific curves differed mainly in the half-saturation constant, with the low-flow treatment showing the highest fitted $K_m$ and the medium- and high-flow treatments reaching high uptake rates at lower substrate concentrations (@fig-mm-fit). Estimated parameter values were low flow: $V_{max} =$ 13.73 $\\mu\\mathrm{mol}\\ \\mathrm{N}\\ \\mathrm{g}^{-1}\\ \\mathrm{h}^{-1}$ and $K_m =$ 16.85 $\\mu\\mathrm{mol}\\ \\mathrm{L}^{-1}$; medium flow: $V_{max} =$ 11.81 $\\mu\\mathrm{mol}\\ \\mathrm{N}\\ \\mathrm{g}^{-1}\\ \\mathrm{h}^{-1}$ and $K_m =$ 4.93 $\\mu\\mathrm{mol}\\ \\mathrm{L}^{-1}$; high flow: $V_{max} =$ 15.35 $\\mu\\mathrm{mol}\\ \\mathrm{N}\\ \\mathrm{g}^{-1}\\ \\mathrm{h}^{-1}$ and $K_m =$ 5.37 $\\mu\\mathrm{mol}\\ \\mathrm{L}^{-1}$.\n\n**Discussion**\n\nThe biological point is that repeated-measures uptake data can support treatment differences in kinetic behaviour, but only if the dependence structure is modelled explicitly. Ignoring the repeated sampling of the same flasks would treat correlated measurements as independent and would make the inferential result less trustworthy.\n:::\n\n# Choosing Among Flexible Models\n\nThere are a few practical considerations to keep in mind when choosing a mechanistic nonlinear model. Sometimes different curved models can provide similar fits to the same data, but they have very different implications for interpretation. The reason to prefer a mechanistic nonlinear model is precisely that its parameters mean something biologically. If that interpretability is weak or artificial, a descriptive alternative such as a polynomial regression or GAM may be more honest.\n\n# Practical Caution\n\nFlexibility is valuable, but it comes with a cost.\n\n-   More flexible models are often harder to interpret.\n-   They can overfit small datasets.\n-   They may fit noise rather than structure if the biological logic is weak.\n-   Nonlinear least-squares models can fail to converge if the functional form or starting values are poor.\n\nThis is why flexible regression should be a response to a clear diagnostic or biological need, not just a default preference for curved lines.\n\n# Summary\n\n-   Not all biological relationships are well described by straight lines.\n-   Mechanistic nonlinear models serve a distinct purpose within the broader family of curved-response models.\n-   Model choice should follow the biology and the inferential goal.\n-   Mechanistic nonlinear models are especially valuable when their parameters have clear biological meaning.\n-   Greater flexibility can improve fit, but it also increases interpretive demands and the risk of overfitting.\n\nIn the next chapter, I extend the regression sequence in a different direction by asking what happens when the scientific target is another part of the response distribution rather than the mean alone.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}