---
date: "2021-01-01"
title: "2. GitHub"
subtitle: "Reproducible Research: Learning How to Collaboratively Work with R Code"
bibliography: ../../references.bib
csl: ../../styles/marine-biology.csl
format:
  html:
    code-fold: false
    toc-title: "On this page"
    standalone: true
    toc-location: right
    page-layout: full
    smooth-scroll: true
    anchor-sections: true
    number-sections: false
---

```{r code-brewing-opts, echo=FALSE}
knitr::opts_chunk$set(
  comment = "R>", 
  warning = FALSE, 
  message = FALSE,
  fig.width = 4.5,
  fig.height = 2.625,
  out.width = "75%",
  fig.asp = NULL, # control via width/height
  dpi = 300
)

ggplot2::theme_set(
  ggplot2::theme_minimal(base_size = 8)
)
ggplot2::theme_set(
  ggplot2::theme_bw(base_size = 8)
)
```

GitHub is a code hosting platform for version control and collaboration. It uses the software Git to let you and others work together on projects from anywhere. The following teaches you the GitHub essentials like **Repositories**, **Branches**, **Commits**, and **Pull Requests**. You will first create your own account, repository and learn GitHub’s Pull and Push Request workflow, a popular way to create, review code.

# Installing Git on Windows

By default, Git is installed on Linux, macOS computers as a command line option. However and Microsoft Windows does not include a Git command. To install GitHub on Windows open the Git website (https://git-scm.com/). Click the 'Download' link to download Git. The download should automatically start. Once downloaded, start the installation from the browser, the download folder. In the 'Select Components' window or leave all default options checked and check any other additional components you want installed. Click the 'Install' button. Once completed, you can check the option to launch Git Bash if you want to open a Bash command line.

# Create and Account and a Repository

Create a GitHub account (https://github.com/join), complete the application steps. This should take less than five minutes. Now lets create a repository. A repository is usually used to organise a single project. Repositories can contain folders, files and images, videos, spreadsheets, and data sets --- anything your project needs. We recommend including a README, or a file with information about your project. GitHub makes it easy to add one at the same time you create your new repository. 

Create a new repository --- in the upper right corner, next to your avatar, identicon or click and then select 'New repository'. Name your repository (Intro_R) and write a short description.

# Git Configuring (Activation) and Connecting to a Remote Repository

Launch Git Bash and type the following command to configure your Git username, where <your name> will be your GitHub username:

            git config --global user.name "<your name>"

After entering the above command, you should be returned to the command prompt. Next, enter your e-mail address by typing the following command, where <your e-mail> is your e-mail address.

            git config --global user.email "<your e-mail>"

# Clone the New GitHub Repository to Your Computer via RStudio.

Select the repository URL from GitHub. It will be something like https://github.com/AmierohAbrahams/Intro_R. 

Enter RStudio. On the top left of the screen select the tab 'New Project'. Then select the 'Version control' tab followed by the 'Git' tab. Complete each option by placing the repository URL into the first box and complete the rest.

# Commits

Bravo! Now, on GitHub, saved changes are called *Commits*. Each commit has an associated commit message, which is a description explaining why a particular change was made. Commit messages capture the history of your changes, so other contributors can understand what you’ve done, why.
Make and commit changes.

# Open a Pull Request

Nice edits! Now that you have changes in a branch off of master, you can open a Pull Request.

Pull Requests are the heart of collaboration on GitHub. When you open a pull request, you’re proposing your changes, requesting that someone review and pull in your contribution and merge them into their branch. Pull requests show diffs or differences, of the content from both branches. The changes, additions, and subtractions are shown in green, red.

As soon as you make a commit, you can open a pull request, start a discussion and even before the code is finished.
