# Default author
author:
  - name: 'AJ Smit'
    url: https://ajsmit.netlify.app
    affiliation: University of the Western Cape
    affiliation-url: https://uwc.ac.za
    orcid: 0000-0002-3799-6126

project:
  type: website

bibliography: references.bib
citation: true
csl: marine-biology.csl
license: "CC BY"
number-sections: true
title-block-banner: false
toc: true
toc-title: On this page
toc-location: right

format:
  html:
    page-layout: full
    grid:
      sidebar-width: 250px
      body-width: 950px
      margin-width: 450px
      gutter-width: 1.5rem
    theme:
      - journal
      - custom.scss
    css: styles.css
    anchor-sections: true
    citations-hover: true
    code-block-bg: true
    # monobackgroundcolor: "#DC3545"
    code-block-border-left: "black"
    code-copy: true
    code-fold: false
    code-overflow: scroll
    code-line-numbers: false
    code-link: true
    code-tools: true
    comments:
      hypothesis: true
    fig-align: center
    fig-cap-location: bottom
    fig-dpi: 240
    fig-format: svg
    fig-height: 4
    # df-print: kable
    fig-width: 6
    footnotes-hover: true
    highlight-style: pygments
    linkcolor: "#00565E"
    number-depth: 4
    number-sections: true
    self-contained: false
    standalone: true
    smooth-scroll: true
    tbl-cap-location: top
    toc: true
    toc-location: right
    toc-title: "On this page"
  # pdf:
  #   # documentclass: scrartcl
  #   cite-method: biblatex
  #   colorlinks: true
  #   fontsize: 10pt
  #   include-in-header:
  #     template.tex
  #   lof: false
  #   lot: false

execute:
  cache: false
  freeze: auto
  echo: true
  message: false
  warning: false

website:
  search:
    location: sidebar
  page-navigation: true
  title: "The Tangled Bank"
  site-url: http://tangledbank.netlify.app
  favicon: "images/favicon.ico"
  # image: "images/hex_logo.png"
  google-analytics: G-SCYH68M489
  cookie-consent: true
  repo-url: https://github.com/ajsmit/tangled_bank
  repo-actions: [edit, issue]

  page-footer:
    left: "© 2023, AJ Smit"
    right: "This page is built with [Quarto](https://quarto.org/)."
    background: light

  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - about.qmd
      - text: "Vignettes"
        menu:
        - text: "Detect lab event streaks based on specified thresholds"
          href: vignettes/Lab_streaks.qmd
        - text: "Dates From netCDF Files: Two Approaches"
          href: vignettes/netCDF_dates.qmd
        - text: "Downloading and Prep: ERDDAP"
          href: vignettes/prep_NOAA_OISST.qmd
        - text: "Retrieving Chlorophyll-a Data from ERDDAP Servers"
          href: vignettes/chl_ERDDAP.qmd
        - text: "Basic Detection and Visualisation of Events"
          href: vignettes/MHW_basic_detection.qmd
        - text: "Downloading and Prep: Python + CDO"
          href: vignettes/alt_method.qmd
        - text: "Detecting Events in Gridded Data"
          href: vignettes/gridded_data.qmd
        - text: "Regridding gridded data"
          href: vignettes/regridding.qmd
        - text: "Displaying MHWs and MCSs as Horizon Plots"
          href: vignettes/MHW_MCS_horizonplots.qmd
        - text: "heatwaveR Issues"
          href: vignettes/heatwaveR_issues.qmd
        - text: "Plotting the Whale Sightings and Chlorophyll-*a* Concentrations"
          href: vignettes/chl_sightings.qmd
        - text: "Spatial Localisation, Subsetting, and Aggregation of the Chlorophyll-*a* Data"
          href: vignettes/chl_localisation.qmd
        - text: "Wavelet Analysis of Diatom Time Series"
          href: vignettes/elem_ts_methods.qmd
      - text: "High-Performace Computing"
        menu:
        - text: "Using Lengau"
          href: vignettes/README_Lengau.qmd
        - text: "PBSPro user and job management"
          href: vignettes/PBSPro_users.qmd
        - text: "Using tmux"
          href: vignettes/README_tmux.qmd
    right:
    - icon: twitter
      href: https://twitter.com/ajsmit
    - icon: github
      menu:
        - text: Source Code
          url:  https://github.com/ajsmit/tangled_bank
        - text: Report a Bug
          url:  https://bugs.com

  sidebar:
    align: center
    background: "#01565E"
    back-to-top-navigation: true
    border: true
    logo: "images/hex_logo.png"
    pinned: true
    style: "floating"
    search: true
    collapse-level: 1
    contents:
      - text: "☘︎"
      - text: "UNDERGRADUATE"
      - text: "---"
      - section: "BDC223"
        contents:
          - href: pages/BDC223_FAQ.qmd
      - section: "BDC334"
        contents:
          - href: BDC334/BDC334_index.qmd
          - href: BDC334/01-introduction.qmd
            text: "Lab 1: Ecological Data"
          - href: BDC334/02a-r_rstudio.qmd
            text: "Lab 2a: R and RStudio"
          - href: BDC334/02b-env_dist.qmd
            text: "Lab 2b: Environmental Distance"
          - href: BDC334/03-biodiversity1.qmd
            text: "Lab 3: Quantifying Biodiversity"
          - href: BDC334/04-biodiversity2.qmd
            text: "Lab 4: Describing Biodiversity Patterns"
          - href: pages/Transboundary_systems.qmd
      - text: "☘"
      - text: "HONOURS CORE"
      - text: "---"
      - section: "BCB744 (Intro R)"
        contents:
          - href: BCB744/BCB744_index.qmd
          - href: BCB744/intro_r/01-RStudio.qmd
          - href: BCB744/intro_r/02-working-with-data.qmd
          - href: BCB744/intro_r/03-workflow.qmd
          - href: BCB744/intro_r/04-graphics.qmd
          - href: BCB744/intro_r/05-faceting.qmd
          - href: BCB744/intro_r/06-brewing.qmd
          - href: BCB744/intro_r/07-mapping.qmd
          - href: BCB744/intro_r/08-mapping_style.qmd
          - href: BCB744/intro_r/09-mapping_rnaturalearth.qmd
          - href: BCB744/intro_r/10-mapping_quakes.qmd
          - href: BCB744/intro_r/11-tidy.qmd
          - href: BCB744/intro_r/12-tidier.qmd
          - href: BCB744/intro_r/13-tidiest.qmd
          - href: BCB744/intro_r/14-recap.qmd
          - href: BCB744/intro_r/15-functions.qmd
          - href: BCB744/intro_r/16-base_r.qmd
          - href: BCB744/intro_r/17-dates.qmd
      - section: "BCB744 (Biostatistics)"
        contents:
          - href: BCB744/basic_stats/01-data-in-R.qmd
          - href: BCB744/basic_stats/02-summarise-and-describe.qmd
          - href: BCB744/basic_stats/03-visualise.qmd
          - href: BCB744/basic_stats/04-distributions.qmd
          - href: BCB744/basic_stats/05-inference.qmd
          - href: BCB744/basic_stats/05a-decision_guide.qmd
          - href: BCB744/basic_stats/06-assumptions.qmd
          - href: BCB744/basic_stats/07-t_tests.qmd
          - href: BCB744/basic_stats/08-anova.qmd
          - href: BCB744/basic_stats/09-regressions.qmd
          - href: BCB744/basic_stats/10-correlations.qmd
          - href: BCB744/basic_stats/11-glance.qmd
          - href: BCB744/basic_stats/12-confidence.qmd
      - text: "☘"
      - text: "HONOURS ELECTIVES"
      - text: "---"
      - section: "BCB743"
        contents:
          - href: BCB743/BCB743_index.qmd
          - href: BCB743/00-review.qmd
          - href: BCB743/05-correlations.qmd
          - href: BCB743/06-deep_dive.qmd
          - href: BCB743/07-ordination.qmd
          - href: BCB743/08-PCA.qmd
          - href: BCB743/08-PCA_examples.qmd
          - href: BCB743/08-PCA_SDG.qmd
          - href: BCB743/09-CA.qmd
          - href: BCB743/10-PCoA.qmd
          - href: BCB743/11-nMDS.qmd
          - href: BCB743/11-nMDS_diatoms.qmd
          - href: BCB743/12-constrained_ordination.qmd
          - href: BCB743/13-cluster_analysis.qmd
      - text: "☘︎"
      - text: "SUPPORT"
      - text: "---"
      - section: "Web Resources"
        contents:
          - href: resources/general_resources_web.qmd
          - href: resources/ecology_resources_web.qmd
          - href: resources/spatial_resources_web.qmd
      - text: "☘︎

comments:
  utterances:
    repo: ajsmit/tangled_bank
