project:
  type: website

vars:
  github-url: "https://github.com/ajsmit/tangled_bank"

# Default author
author:
  - name: ' Smit, A. J.'
    url: https://tangledbank.netlify.app
    affiliation: University of the Western Cape
    affiliation-url: https://uwc.ac.za
    orcid: 0000-0002-3799-6126

copyright:
  holder: "Smit, A. J."
  year: 2025

# Metadata stuff
# pagetitle: "{{< meta title >}} | Smit, A. J."

bibliography: references.bib
citation: true
csl: marine-biology.csl
funding: "The author received no specific funding for this work."
license: "CC BY-NC-SA"
title-block-banner: false
title-block-style: default

lightbox: auto

execute:
  cache: false
  freeze: auto
  echo: true
  message: false
  warning: false

format:
  html:
    anchor-sections: true
    grid:
      sidebar-width: 300px
      body-width: 1000px
      margin-width: 300px
      gutter-width: 1.5rem
    citations-hover: true
    code-block-bg: true
    code-copy: true
    code-fold: false
    code-overflow: scroll
    code-line-numbers: true
    code-link: true
    code-tools: true
    comments:
      hypothesis: true
    # df-print: kable
    crossrefs-hover: true
    css: LesCodex2.css
    embed-resources: false
    fig-align: center
    fig-height: 7.5
    fig-width: 12
    fig-format: svg
    fig_retina: 2
    fig-cap-location: bottom
    fig-dpi: 400
    fontsize: 1.1em
    footnotes-hover: true
    highlight-style: github
    html-math-method: mathjax
    link-external-icon: true
    link-external-newwindow: true
    number-depth: 3
    number-sections: false
    page-layout: article
    reference-location: margin
    self-contained: false
    standalone: true
    smooth-scroll: true
    tbl-cap-location: margin
    tbl-colwidths: false
    theme: [minty, styles.scss]
    toc: true
    toc-depth: 3
    toc-location: right
    toc-title: "On this page"

website:
  title: "The Tangled Bank"
  description: "UWC's Biodiversity & Conservation Biology Department Pages For BDC334, BCB743, and BCB744."
  favicon: "images/favicon.ico"
  site-url: http://tangledbank.netlify.app
  repo-url: https://github.com/ajsmit/tangled_bank
  google-analytics: G-SCYH68M489
  bread-crumbs: true
  cookie-consent:
    type: express
    style: headline
    palette: light
  search:
    location: sidebar
  open-graph: true
  page-navigation: true
  repo-actions: [edit, issue]
  reader-mode: true
  # image: "images/hex_logo.png"
  page-footer:
    left: "© 2025, AJ Smit"
    background: dark

  navbar:
    background: primary
    search: true
    collapse-below: lg
    left:
      - text: "Home"
        file: index.qmd
      - text: "Vignettes"
        menu:
        - text: "Dates From netCDF Files: Two Approaches"
          href: vignettes/netCDF_dates.qmd
        - text: "Downloading and Prep: ERDDAP"
          href: vignettes/prep_NOAA_OISST.qmd
        - text: "Retrieving Chlorophyll-a Data from ERDDAP Servers"
          href: vignettes/chl_ERDDAP.qmd
        - text: "Downloading and Prep: Python + CDO"
          href: vignettes/alt_method.qmd
        - text: "Detecting Events in Gridded Data"
          href: vignettes/gridded_data.qmd
        - text: "Regridding gridded data"
          href: vignettes/regridding.qmd
        - text: "Displaying MHWs and MCSs as Horizon Plots"
          href: vignettes/MHW_MCS_horizonplots.qmd
        - text: "heatwaveR Issues"
          href: vignettes/heatwaveR_issues.qmd
        - text: "Plotting the Whale Sightings and Chlorophyll-*a* Concentrations"
          href: vignettes/chl_sightings.qmd
        - text: "Spatial Localisation, Subsetting, and Aggregation of the Chlorophyll-*a* Data"
          href: vignettes/chl_localisation.qmd
        - text: "Wavelet Analysis of Diatom Time Series"
          href: vignettes/elem_ts_methods.qmd
        - text: "Extracting gridded data within a buffer"
          href: vignettes/buffer_data_extract.qmd
      - text: "High-Performace Computing"
        menu:
        - text: "Using Lengau"
          href: vignettes/README_Lengau.qmd
        - text: "PBSPro user and job management"
          href: vignettes/PBSPro_users.qmd
        - text: "Using tmux"
          href: vignettes/README_tmux.qmd
      - blog.qmd
    right:
    - about.qmd
    - text: "Blogroll"
      menu:
      - text: "R-bloggers"
        href: https://www.r-bloggers.com
    - icon: rss
      href: blog.xml
    - icon: github
      menu:
        - text: Source Code
          url:  https://github.com/ajsmit/tangled_bank
        - text: Report a Bug
          url:  https://bugs.com

  sidebar:
    alignment: left
    background: light
    back-to-top-navigation: true
    border: false
    logo: "images/hex_logo.png"
    pinned: true
    search: true
    style: floating
    title: "The Tangled Bank"
    type: light
    collapse-level: 1
    contents:
      - href: index.qmd
        text: "Home"
      - text: "☘☘☘"
      - text: "UNDERGRADUATE"
      - text: "---"
      - section: "BDC223: Plant Ecophysiology"
        contents:
          - href: BDC223/BDC223_index.qmd
            text: "**About**"
          - href: BDC223/L00-introduction.qmd
          - href: BDC223/L01-worldmapper.qmd
          - href: BDC223/L02-SA_V.qmd
          - href: BDC223/L03-plant_stress.qmd
          - href: BDC223/L04-carbon_cycle.qmd
          - href: BDC223/L05-light.qmd
          - href: BDC223/L06a-pigments_photosynthesis.qmd
          - href: BDC223/L06b-jassby_platt.qmd
          - href: BDC223/L07-chromatic_adaptation.qmd
          - href: BDC223/L08a-nutrient_uptake.qmd
          - href: BDC223/L08b-nutrients_michaelis_menten.qmd
          - href: BDC223/Lab1_SA_V.qmd
          - href: BDC223/Lab2_misc_calcs.qmd
          - href: BDC223/Lab3_PI_curves.qmd
          - href: BDC223/Lab4_nitrogen_uptake.qmd
          - href: BDC223/BDC223_FAQ.qmd
      - section: "BDC334: Biogeography & Global Ecology"
        contents:
          - href: BDC334/BDC334_syllabus.qmd
            text: "**About**"
          - href: BDC334/BDC334-Lecture-Transcripts.qmd
            text: "[BCB334 Lecture Transcript]{.my-highlight}"
          - href: BDC334/Lec-01-introduction.qmd
          - href: BDC334/Lec-02-ecosystems.qmd
          - href: BDC334/Lec-03-gradients.qmd
          - href: BDC334/Lec-04-biodiversity.qmd
          - text: "Lecture 5. Multivariate Data"
          - href: BDC334/Lec-06-unified-ecology.qmd
          - text: "Lecture 7: Threats to Biodiversity"
          - text: "Lecture 8: Nature's Contribution to People"
          - href: BDC334/Lab-01-introduction.qmd
          - href: BDC334/Lab-02a-r_rstudio.qmd
          - href: BDC334/Lab-02b-env_dist.qmd
          - href: BDC334/Lab-03-biodiversity.qmd
          - href: BDC334/Lab-04-biodiversity.qmd
          - href: pages/Transboundary_systems.qmd
      - text: "☘☘☘"
      - text: "HONOURS CORE"
      - text: "---"
      - section: "BCB744: Introduction to R, & Biostatistics"
        contents:
          - href: BCB744/BCB744_index.qmd
            text: "**About**"
          - text: "---"
          - href: BCB744/intro_r/01-RStudio.qmd
          - href: BCB744/intro_r/02-working-with-data.qmd
          - href: BCB744/intro_r/03-data-in-R.qmd
          - href: BCB744/intro_r/04-workflow.qmd
          - href: BCB744/intro_r/05-graphics.qmd
          - href: BCB744/intro_r/06-faceting.qmd
          - href: BCB744/intro_r/07-brewing.qmd
          - href: BCB744/intro_r/08-mapping.qmd
          - href: BCB744/intro_r/09-mapping_style.qmd
          - href: BCB744/intro_r/10-mapping_rnaturalearth.qmd
          - href: BCB744/intro_r/11-mapping_quakes.qmd
          - href: BCB744/intro_r/12-tidy.qmd
          - href: BCB744/intro_r/13-tidier.qmd
          - href: BCB744/intro_r/14-tidiest.qmd
          - href: BCB744/intro_r/15-recap.qmd
          - href: assessments/BCB744_Intro_R_Self-Assessment.qmd
            text: "[Intro R Self-Assessment]{.my-highlight}"
          - href: assessments/examples/BCB744_Intro_R_Example_1.qmd
          - href: assessments/examples/BCB744_Intro_R_Example_2.qmd
          - href: self-assessment_v1.html
            text: "Self-Assessment Form"
          - href: assessments/BCB744_Intro_R_Presentations.qmd
            text: "[Presentations]{.my-highlight}"
          - href: assessments/BCB744_Intro_R_Test_2025.qmd
            text: "[Intro R Test]{.my-highlight}"
          - text: "---"
          - href: BCB744/basic_stats/01-scientific-philosophy.qmd
          - href: BCB744/basic_stats/02-summarise-and-describe.qmd
          - href: BCB744/basic_stats/03-visualise.qmd
          - href: BCB744/basic_stats/04-distributions.qmd
          - href: BCB744/basic_stats/05-inference.qmd
          - href: BCB744/basic_stats/06-assumptions.qmd
          - href: BCB744/basic_stats/07-t_tests.qmd
          - href: BCB744/basic_stats/08-anova.qmd
          - href: BCB744/basic_stats/09-regressions.qmd
          - href: BCB744/basic_stats/10-correlations.qmd
          - href: BCB744/basic_stats/11-decision_guide.qmd
          - href: BCB744/basic_stats/12-glance.qmd
          - href: BCB744/basic_stats/13-confidence.qmd
          - href: BCB744/basic_stats/14-transformations.qmd
          - href: assessments/BCB744_Biostatistics_Self-Assessment.qmd
            text: "[Biostatistics Self-Assessment]{.my-highlight}"
          - href: assessments/examples/BCB744_BioStats_Example_1.qmd
      - text: "☘☘☘"
      - text: "HONOURS ELECTIVES"
      - text: "---"
      - section: "BCB743: Quantitative Ecology"
        contents:
          - href: BCB743/BCB743_index.qmd
            text: "**About**"
          - href: BCB743/review.qmd
            text: "1-4: Review Concepts fo Biodiversity"
          - href: BCB743/correlations.qmd
            text: "5: Correlations & Associations"
          - href: BCB743/ordination.qmd
            text: "7: Intro to Ordination"
          - href: BCB743/PCA.qmd
            text: "8a: Principal Components Analysis"
          - href: BCB743/PCA_examples.qmd
            text: "8b: PCA: Additional Examples"
          - href: BCB743/PCA_SDG_example.qmd
            text: "8c: PCA: WHO SDG Example"
          - href: BCB743/CA.qmd
            text: "9a: Correspondence Analysis"
          - href: BCB743/DCA.qmd
            text: "9b: Detrended Correspondence Analysis"
          - href: BCB743/PCoA.qmd
            text: "10: Principal Coordinates Analysis"
          - href: BCB743/nMDS.qmd
            text: "11a: Non-metric Multidimensional Scaling"
          - href: BCB743/nMDS_diatoms.qmd
            text: "11b: nMDS: PERMANOVA (Diatoms) Example"
          - href: BCB743/unconstrained-summary.qmd
            text: "12: Unconstrained Ordination Summary"
          - href: BCB743/constrained_ordination.qmd
            text: "13a: Distance-Based Redundancy Analysis"
          - href: BCB743/two_oceans_appendices.qmd
            text: "13b: db-RDA: Seaweeds Example"
          - href: BCB743/cluster_analysis.qmd
            text: "14: Cluster Analysis"
          - href: BCB743/model_building.qmd
            text: "15: Model Building"
          - href: BCB743/deep_dive.qmd
            text: "16a: Deep Dive Into Gradients"
          - href: BCB743/multiple_regression.qmd
            text: "16b: Multiple Regression"
      - text: "☘☘☘︎"
      - href: AI4AI/AI4AI.qmd
      - text: "---"
      - text: "☘☘☘︎"
      - text: "SUPPORT"
      - text: "---"
      - section: "Web Resources"
        contents:
          - href: resources/general_resources_web.qmd
          - href: resources/ecology_resources_web.qmd
          - href: resources/spatial_resources_web.qmd
      - text: "☘☘☘︎"

# comments:
#   giscus:
#     repo: ajsmit/tangled_bank
