project:
  type: website

# Default author
author:
  - name: 'Albertus J. Smit'
    url: https://tangledbank.netlify.app
    affiliation: University of the Western Cape
    affiliation-url: https://uwc.ac.za
    orcid: 0000-0002-3799-6126

# Metadata stuff
pagetitle: "{{< meta title >}} | Albertus J. Smit"
author-meta: "Albertus J. Smit"

bibliography: references.bib
citation: true
freeze: true
funding: "The author received no specific funding for this work."
license: "CC BY-NC-SA"
title-block-banner: false
title-block-style: default

copyright:
  holder: Smit, AJ
  year: 2024

csl: marine-biology.csl

execute:
  cache: false
  freeze: auto
  echo: true
  message: false
  warning: false

format:
  html:
    anchor-sections: true
    page-layout: article
    fig_retina: 2
    grid:
      sidebar-width: 300px
      body-width: 1000px
      margin-width: 300px
      gutter-width: 1.5rem
    theme: [minty, theme.scss]
    fontcolor: "#000000"
    mainfont: Merriweather
    monofont: "Roboto Mono"
    citations-hover: true
    code-block-bg: true
    code-copy: true
    code-fold: false
    code-overflow: scroll
    code-line-numbers: true
    code-link: true
    code-tools: true
    comments:
      hypothesis: true
    # df-print: kable
    fig-align: center
    fig-cap-location: margin
    fig-dpi: 300
    fig-format: svg
    fig-height: 4
    fig-width: 6
    fontsize: 1.1em
    footnotes-hover: true
    highlight-style: tango
    link-external-icon: true
    number-depth: 2
    number-sections: false
    reference-location: margin
    self-contained: false
    standalone: true
    smooth-scroll: true
    tbl-cap-location: top
    toc: true
    toc-location: right
    toc-title: "On this page"

website:
  title: "The Tangled Bank"
  description: "UWC's Biodiversity & Conservation Biology Department Pages Serving BDC334, BCB743, and BCB744."
  favicon: "images/favicon.ico"
  site-url: http://tangledbank.netlify.app
  repo-url: https://github.com/ajsmit/tangled_bank
  google-analytics: G-SCYH68M489
  bread-crumbs: true
  cookie-consent:
    type: express
    style: headline
    palette: dark
  search:
    location: sidebar
  open-graph: true
  page-navigation: true
  repo-actions: [edit, issue]
  reader-mode: true
  # image: "images/hex_logo.png"
  page-footer:
    left: "© 2024, AJ Smit"
    right: |
      <span class="faux-block">Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)</span></br>
      <span class="faux-block">[View the source at {{< fa brands github >}} GitHub]({{< var github-url >}})</span>
    background: dark

  navbar:
    background: primary
    search: true
    collapse-below: lg
    left:
      - text: "Home"
        file: index.qmd
      - text: "BDC334"
        menu:
        - href: BDC334/BDC334_index.qmd
        - href: BDC334/L01a-introduction.qmd
          text: "Lecture 1a: Setting the Scene"
        - href: BDC334/L01b-macroecology.qmd
          text: "Lecture 1b: Macroecology"
        - href: BDC334/L02a-gradients.qmd
          text: "Lecture 2a: Ecological Gradients"
        - href: BDC334/L02b-biodiversity.qmd
          text: "Lecture 2b: Metrics of Environmental and Species Diversity"
        - href: BDC334/01-introduction.qmd
          text: "Lab 1: Ecological Data"
        - href: BDC334/02a-r_rstudio.qmd
          text: "Lab 2a: R & RStudio"
        - href: BDC334/02b-env_dist.qmd
          text: "Lab 2b: Environmental Distance"
        - href: BDC334/03-biodiversity1.qmd
          text: "Lab 3: Quantifying Biodiversity"
        - href: BDC334/04-biodiversity2.qmd
          text: "Lab 4: Describing Biodiversity Patterns"
        - href: pages/Transboundary_systems.qmd
      - text: "Vignettes"
        menu:
        - text: "Dates From netCDF Files: Two Approaches"
          href: vignettes/netCDF_dates.qmd
        - text: "Downloading and Prep: ERDDAP"
          href: vignettes/prep_NOAA_OISST.qmd
        - text: "Retrieving Chlorophyll-a Data from ERDDAP Servers"
          href: vignettes/chl_ERDDAP.qmd
        - text: "Downloading and Prep: Python + CDO"
          href: vignettes/alt_method.qmd
        - text: "Detecting Events in Gridded Data"
          href: vignettes/gridded_data.qmd
        - text: "Regridding gridded data"
          href: vignettes/regridding.qmd
        - text: "Displaying MHWs and MCSs as Horizon Plots"
          href: vignettes/MHW_MCS_horizonplots.qmd
        - text: "heatwaveR Issues"
          href: vignettes/heatwaveR_issues.qmd
        - text: "Plotting the Whale Sightings and Chlorophyll-*a* Concentrations"
          href: vignettes/chl_sightings.qmd
        - text: "Spatial Localisation, Subsetting, and Aggregation of the Chlorophyll-*a* Data"
          href: vignettes/chl_localisation.qmd
        - text: "Wavelet Analysis of Diatom Time Series"
          href: vignettes/elem_ts_methods.qmd
        - text: "Extracting gridded data within a buffer"
          href: vignettes/buffer_data_extract.qmd
      - text: "High-Performace Computing"
        menu:
        - text: "Using Lengau"
          href: vignettes/README_Lengau.qmd
        - text: "PBSPro user and job management"
          href: vignettes/PBSPro_users.qmd
        - text: "Using tmux"
          href: vignettes/README_tmux.qmd
      - blog.qmd
    right:
    - about.qmd
    - text: "Blogroll"
      menu:
      - text: "R-bloggers"
        href: https://www.r-bloggers.com
    - icon: rss
      href: blog.xml
    - icon: github
      menu:
        - text: Source Code
          url:  https://github.com/ajsmit/tangled_bank
        - text: Report a Bug
          url:  https://bugs.com

  sidebar:
    alignment: left
    background: light
    back-to-top-navigation: true
    border: false
    logo: "images/hex_logo.png"
    pinned: true
    search: true
    style: floating
    title: "The Tangled Bank"
    type: light
    collapse-level: 1
    contents:
      - href: index.qmd
        text: "Home"
      - text: "☘☘☘︎"
      - text: "BCB UNDERGRADUATE"
      - text: "---"
      - section: "BDC223 Ecophysiology"
        contents:
          - href: pages/BDC223_FAQ.qmd
      - section: "BDC334 Biogeography & Global Ecology"
        contents:
          - href: BDC334/BDC334_index.qmd
          - href: BDC334/L01a-introduction.qmd
            text: "Lecture 1a: Setting the Scene"
          - href: BDC334/L01b-macroecology.qmd
            text: "Lecture 1b: Macroecology"
          - href: BDC334/L02a-gradients.qmd
            text: "Lecture 2a: Ecological Gradients"
          - href: BDC334/L02b-biodiversity.qmd
            text: "Lecture 2b: Metrics of Environmental and Species Diversity"
          - href: BDC334/01-introduction.qmd
            text: "Lab 1: Ecological Data"
          - href: BDC334/02a-r_rstudio.qmd
            text: "Lab 2a: R & RStudio"
          - href: BDC334/02b-env_dist.qmd
            text: "Lab 2b: Environmental Distance"
          - href: BDC334/03-biodiversity1.qmd
            text: "Lab 3: Quantifying Biodiversity"
          - href: BDC334/04-biodiversity2.qmd
            text: "Lab 4: Describing Biodiversity Patterns"
          - href: pages/Transboundary_systems.qmd
      - text: "☘☘☘"
      - text: "BCB HONOURS CORE"
      - text: "---"
      - section: "BCB744 Intro R"
        contents:
          - href: BCB744/BCB744_index.qmd
          - href: BCB744/intro_r/01-RStudio.qmd
          - href: BCB744/intro_r/02-working-with-data.qmd
          - href: BCB744/intro_r/03-workflow.qmd
          - href: BCB744/intro_r/04-graphics.qmd
          - href: BCB744/intro_r/05-faceting.qmd
          - href: BCB744/intro_r/06-brewing.qmd
          - href: BCB744/intro_r/07-mapping.qmd
          - href: BCB744/intro_r/08-mapping_style.qmd
          - href: BCB744/intro_r/09-mapping_rnaturalearth.qmd
          - href: BCB744/intro_r/10-mapping_quakes.qmd
          - href: BCB744/intro_r/11-tidy.qmd
          - href: BCB744/intro_r/12-tidier.qmd
          - href: BCB744/intro_r/13-tidiest.qmd
          - href: BCB744/intro_r/14-recap.qmd
          - href: BCB744/intro_r/15-functions.qmd
          - href: BCB744/intro_r/16-base_r.qmd
          - href: BCB744/intro_r/17-dates.qmd
      - section: "BCB744 Biostatistics"
        contents:
          - href: BCB744/basic_stats/BCB744_scientific_philosophy.qmd
          - href: BCB744/basic_stats/01-data-in-R.qmd
          - href: BCB744/basic_stats/02-summarise-and-describe.qmd
          - href: BCB744/basic_stats/03-visualise.qmd
          - href: BCB744/basic_stats/04-distributions.qmd
          - href: BCB744/basic_stats/05-inference.qmd
          - href: BCB744/basic_stats/06-assumptions.qmd
          - href: BCB744/basic_stats/07-t_tests.qmd
          - href: BCB744/basic_stats/08-anova.qmd
          - href: BCB744/basic_stats/09-regressions.qmd
          - href: BCB744/basic_stats/10-correlations.qmd
          - href: BCB744/basic_stats/11-decision_guide.qmd
          - href: BCB744/basic_stats/12-glance.qmd
          - href: BCB744/basic_stats/13-confidence.qmd
          - href: BCB744/basic_stats/14-transformations.qmd
      - text: "☘☘☘"
      - text: "BCB HONOURS ELECTIVES"
      - text: "---"
      - section: "BCB743 Quantitative Ecology"
        contents:
          - href: BCB743/BCB743_index.qmd
            text: "Overview & Introduction"
          - href: BCB743/review.qmd
            text: "1-4: Review Concepts fo Biodiversity"
          - href: BCB743/correlations.qmd
            text: "5: Correlations & Associations"
          - href: BCB743/ordination.qmd
            text: "7: Intro to Ordination"
          - href: BCB743/PCA.qmd
            text: "8a: Principal Components Analysis"
          - href: BCB743/PCA_examples.qmd
            text: "8b: PCA: Additional Examples"
          - href: BCB743/PCA_SDG_example.qmd
            text: "8c: PCA: WHO SDG Example"
          - href: BCB743/CA.qmd
            text: "9a: Correspondence Analysis"
          - href: BCB743/DCA.qmd
            text: "9b: Detrended Correspondence Analysis"
          - href: BCB743/PCoA.qmd
            text: "10: Principal Coordinates Analysis"
          - href: BCB743/nMDS.qmd
            text: "11a: Non-metric Multidimensional Scaling"
          - href: BCB743/nMDS_diatoms.qmd
            text: "11b: nMDS: PERMANOVA (Diatoms) Example"
          - href: BCB743/unconstrained-summary.qmd
            text: "12: Unconstrained Ordination Summary"
          - href: BCB743/model_building.qmd
            text: "13: Model Building"
          - href: BCB743/multiple_regression.qmd
            text: "14a: Multiple Regression"
          - href: BCB743/deep_dive.qmd
            text: "14b: Gradients Example"
          - href: BCB743/constrained_ordination.qmd
            text: "15a: Distance-Based Redundancy Analysis"
          - href: BCB743/two_oceans_appendices.qmd
            text: "15b: db-RDA: Seaweeds Example"
          - href: BCB743/cluster_analysis.qmd
            text: "16: Cluster Analysis"
      - text: "☘☘☘︎"
      - text: "SUPPORT"
      - text: "---"
      - section: "Web Resources"
        contents:
          - href: resources/general_resources_web.qmd
          - href: resources/ecology_resources_web.qmd
          - href: resources/spatial_resources_web.qmd
      - text: "☘☘☘︎"

# comments:
#   giscus:
#     repo: ajsmit/tangled_bank
