project:
  type: website
  page-footer:
  background: light

execute:
  cache: false
  freeze: auto

website:
  page-navigation: true
  title: "The Tangled Bank"
  site-url: http://tangledbank.netlify.app
  favicon: favicon.ico

  google-analytics: G-SCYH68M489
  cookie-consent: true

  repo-url: https://github.com/ajsmit/tangled_bank
  repo-actions: [edit, issue]

  page-footer:
    left: "© 2022, Prof. AJ Smit"
    right: "This page is built with [Quarto](https://quarto.org/)."
    background: light

  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - about.qmd
    right:
    - icon: twitter
      href: https://twitter.com/ajsmit
    - icon: github
      menu:
        - text: Source Code
          url:  https://github.com/ajsmit/tangled_bank
        - text: Report a Bug
          url:  https://bugs.com

  sidebar:
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "**BDC334**"
        contents:
          - href: BDC334/BDC334_index.qmd
          - href: BDC334/01-introduction.qmd
          - href: BDC334/02a-r_rstudio.qmd
          - href: BDC334/02b-env_dist.qmd
          - href: BDC334/03-04-biodiversity.qmd
      - text: "---"
      - section: "**BCB743**"
        contents:
          - href: BCB743/BCB743_index.qmd
          - href: BCB743/00-review.qmd
          - href: BCB743/05-correlations.qmd
          - href: BCB743/06-deep_dive.qmd
          - href: BCB743/07-ordination.qmd
          - href: BCB743/08-PCA.qmd
          - href: BCB743/08-PCA_examples.qmd
          - href: BCB743/08-PCA_SDG.qmd
          - href: BCB743/09-CA.qmd
          - href: BCB743/10-PCoA.qmd
          - href: BCB743/11-nMDS.qmd
          - href: BCB743/11-nMDS_diatoms.qmd
          - href: BCB743/12-constrained_ordination.qmd
          - href: BCB743/13-cluster_analysis.qmd
      - text: "---"
      - section: "**WEB RESOURCES**"
        contents:
          - href: resources.qmd

format:
  html:
    theme:
      light: united
      dark: [cosmo, theme-dark.scss]
    css: styles.css
    anchor-sections: true
    citations-hover: false
    code-block-bg: true
    code-block-border-left: "#31BAE9"
    code-copy: true
    code-fold: true
    code-overflow: scroll
    code-line-numbers: false
    code-link: true
    code-tools: true
    comments:
      hypothesis: true
    fig-align: center
    fig-cap-location: bottom
    fig-dpi: 240
    fig-format: svg
    fig-height: 4
    df-print: kable
    fig-width: 6
    footnotes-hover: true
    include-after-body: js.html
    number-depth: 4
    number-sections: true
    self-contained: false
    smooth-scroll: true
    tbl-cap-location: top
    toc: true

comments:
  utterances:
    repo:  ajsmit/tangled_bank
