project:
  type: website

execute:
  cache: false
  freeze: auto

website:
  title: "The Tangled Bank"
  page-navigation: true
  page-footer: "Copyright 2022, Prof. AJ Smit"
  navbar:
    background: primary
    collapse-below: lg
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - sidebar:bdc334
      - sidebar:bcb743
      - text: "About"
        file: about.qmd
    right:
      - icon: twitter
        href: https://twitter.com/ajsmit
        aria-label: AJ Smit's Twitter
      - icon: github
        href: https://github.com/ajsmit
        aria-label: AJ Smit's GitHub

  sidebar:
    - id: bdc334
      title: "BDC334"
      style: "floating"
      background: dark
      collapse-level: 3
      contents:
        - BDC334/BDC334_index.qmd
        - BDC334/01-introduction.qmd
        - BDC334/02-r_rstudio.qmd
        - BDC334/03-env_dist.qmd
        - BDC334/04-biodiversity.qmd
    - id: bcb743
      title: "BCB743"
      contents:
        - BCB743/BCB743_index.qmd
        - BCB743/03-deep_dive.qmd
        - BCB743/05-spp_dissimilarity.qmd
        - BCB743/06-correlations.qmd
        - BCB743/07-ordination.qmd
        - BCB743/08-PCA.qmd
        - BCB743/08-PCA_examples.qmd
        - BCB743/08-PCA_SDG.qmd
        - BCB743/09-CA.qmd
        - BCB743/10-PCoA.qmd
        - BCB743/11-nMDS.qmd
        - BCB743/11-nMDS_diatoms.qmd
        - BCB743/12-constrained_ordination.qmd
        - BCB743/13-cluster_analysis.qmd

  tools:
    - icon: twitter
      href: https://twitter.com
    - icon: github
      menu:
        - text: Source Code
          url:  https://code.com
        - text: Report a Bug
          url:  https://bugs.com

format:
  html:
    anchor-sections: true
    fig-cap-location: bottom
    citations-hover: false
    code-block-bg: true
    code-block-border-left: "#31BAE9"
    code-copy: true
    code-fold: true
    code-overflow: scroll
    code-line-numbers: false
    code-link: true
    code-tools: true
    comments:
      hypothesis: true
    df-print: kable
    fig-align: center
    fig-format: svg
    fig-dpi: 240
    fig-width: 4
    fig-height: 2.75
    footnotes-hover: true
    include-after-body: js.html
    number-depth: 4
    number-sections: true
    self-contained: false
    smooth-scroll: true
    tbl-cap-location: top
    theme:
      light: flatly
      dark: darkly
    toc: true
    toc-location: right
