---
title: "About"
---

## Disentangling the Tangled Bank {.unnumbered}

Charles Darwin's **Tangled Bank** describes the complexity and interconnectedness of ecosystems and how different species compete and coexist within them. "The Tangled Bank" is a metaphor that refers to the idea that the relationships between species in an ecosystem are intricate and overlapping, like a bank of plants and associated species in a natural environment that is densely woven together.

Darwin used this metaphor to explain how changes in one species can have ripple effects throughout an ecosystem. He argued that the survival, persistence, thriving, and evolution of a species are intimately connected to the conditions and interactions within its environment. In particular, he stressed the importance of *natural selection* as the driving force behind the evolution of species, where those that are best adapted to their environment (*fitness*) are more likely to survive and pass on their traits to the next generation.

Today, data about the world and the diversity of life in it are ubiquitous. This vast amount of complex data can be overwhelming. It may be challenging to see the interrelations between different data sources. Those of us who work with environmental, ecological, and biological data must understand these interconnections, the variety of analytical methods, and models about the data and the world.

I extend the 'Tangled Bank' metaphor to how insights from diverse data sources can interact with one another and equip us to develop deep knowledge about our world. The ever-growing array of analytical methods, which in themselves may be intricately related, drives the 'data[^2] --> information[^3] --> knowledge[^4] --> wisdom[^5]' (DIKW) pipeline, and helps us to untangle the Tangled Bank.


## Why Disentangle the Bank? {.unnumbered}
In a changing and increasingly fragile world, the Tangled Bank is risking becoming a Trampled Bank and by doing so losing its structural and functional integrity. Fortunately, the breadth of data about our world and the depths of information gained is becoming increasing complex. The DIKW pipeline will guide assessments of ecosystems and the state of the world. Through the transformation of data into wisdom, we can:

* arrive at more sustainable policies and practices that consider the long-term implications of our actions on the environment;
* improve public awareness about the importance of preserving natural resources and ecosystems for future generations;
* roll out early warning systems and adaptive management strategies to address environmental challenges such as climate change, habitat loss, and pollution; and
* create innovation in green technologies and promote environmentally responsible behavior among individuals and organisations.

[^2]: `Data` refer to raw, unprocessed numerical representations (facts) about the world. Because of applying the process of scientific enquiry, we can make a case for data being the closest approximation and reflection of reality. In the context of natural systems, this could include measurements of temperature, precipitation, air quality, populations, communities, or any other quantifiable aspect of the environment. It is typically presented in a structured or unstructured format and lacks context or meaning.

[^3]: `Information` refers to data that have been processed, organised, and structured to provide context and meaning. It can be thought of as the result of adding structure and interpretation to raw data. In this stage, data are put into context, such as trends in climate change, loss of biodiversity, or increasing pollution levels. This helps us understand the state of the natural systems and identify potential problems.

[^4]: `Knowledge` is the next level of abstraction and refers to a deeper understanding or insight that is gained from information. It is the result of synthesising information to draw conclusions or make predictions. Through the process of knowledge generation we gain a deeper understanding of the underlying patterns, relationships, and principles. This stage involves continuing to use scientific methods, our and other's expertise, and past experiences to make sense of the information. For instance, understanding the factors driving climate change or the consequences of deforestation on ecosystems. In other words, knowledge is what we gain when we apply meaning and context to information, and we use it to make informed decisions or take actions.

[^5]: `Wisdom` is the final stage in the DIKW pipeline, and the highest level of abstraction possible. Here we apply knowledge to make informed, ethical, and sustainable decisions about how we interact with the natural systems that make up our planet, Earth. This stage involves critical thinking, foresight, and an understanding of the complex interdependencies within the environment. Wisdom allows us to make choices that balance our needs with the long-term health and resilience of the planet.
