---
title: "The Tangled Bank"
date: "2022-08-08"
description: The Biodiversity and Conservation Biology R Pages serving BDC334, BCB743, and BCB744
---

> "***It is interesting to contemplate a tangled bank**, clothed with many plants of many kinds, with birds singing on the bushes, with various insects flitting about, and with worms crawling through the damp earth, and to reflect that these elaborately constructed forms, so different from each other, and dependent upon each other in so complex a manner, have all been produced by laws acting around us. These laws, taken in the largest sense, being Growth with reproduction; Inheritance which is almost implied by reproduction; Variability from the indirect and direct action of the conditions of life, and from use and disuse; a Ratio of Increase so high as to lead to a Struggle for Life, and as a consequence to Natural Selection, entailing Divergence of Character and the Extinction of less improved forms. Thus, from the war of nature, from famine and death, the most exalted object which we are capable of conceiving, namely, the production of the higher animals, directly follows. There is grandeur in this view of life, with its several powers, having been originally breathed by the Creator[^1] into a few forms or into one; and that, whilst this planet has gone circling on according to the fixed law of gravity, from so simple a beginning endless forms most beautiful and most wonderful have been, and are being evolved.*"
>
> --- Charles Darwin, Origin of Species, 1859

## Untangling the Tangled Bank

Charles Darwin's **The Tangled Bank** describes the complexity and interconnectedness of ecosystems and how different species compete and coexist within them. "The Tangled Bank" is a metaphor that refers to the idea that the relationships between species in an ecosystem are intricate and overlapping, like a bank of plants and associated species in a natural environment that is densely woven together.

Darwin used this metaphor to explain how changes in one species can have ripple effects throughout an ecosystem, affecting other species and altering the entire ecosystem. He argued that the survival and evolution of a species are intimately connected to the conditions and interactions within its environment. In particular, he stressed the importance of natural selection as the driving force behind the evolution of species, where those that are best adapted to their environment are more likely to survive and pass on their traits to the next generation.

Today, data about the world and the diversity of life in it are ubiquitous. This vast amount and complexity of data can be overwhelming, and it is often challenging to see the connections between different data sources and how they affect one another. Like a natural ecosystem that richly interacts on all fronts, scientists dealing with environmental, ecological, and biological data must understand the interconnectedness of the different data sources, analytical methods, and models. The 'Tangled Bank' metaphor extends to explaining how insights from diverse data sources can interact with one another and equip us to arrive at deep knowledge about our world. The ever-growing array of analytical methods, which in themselves may be intricately related, drives the 'data[^2] --> information[^3] --> knowledge[^4] --> wisdom[^5]' (DIKW) pipeline, and helps us to untangle the Tangled Bank.

In a changing and increasingly fragile world, Darwin's Tangled Bank is untangling and losing its structural and functional integrity. However, the complexity of data about our world and the depths of information gained is becoming increasing complex. The DIKW pipeline is crucial for guiding our interactions with the natural systems. By transforming data into wisdom, we can:

* Develop more sustainable policies and practices that consider the long-term implications of our actions on the environment.
* Raise public awareness about the importance of preserving natural resources and ecosystems for future generations.
* Implement early warning systems and adaptive management strategies to address environmental challenges such as climate change, habitat loss, and pollution.
* Foster innovation in green technologies and promote environmentally responsible behavior among individuals and organisations.

Ultimately, the DIKW pipeline helps us to make wiser decisions that protect and preserve the natural systems, ensuring a healthy and sustainable world for present and future generations.


[^1]: Talking about the compatibility of science and religion, Darwin said "*I cannot pretend to throw the least light on such abstruse problems. The mystery of the beginning of all things is insoluble by us; and I for one must be content to remain an Agnostic*." The source of this insight in Darwin's religious views is, Darwin, Charles (1958), Barlow, Nora (ed.), The Autobiography of Charles Darwin 1809–1882. With the original omissions restored. Edited and with appendix and notes by his granddaughter Nora Barlow

[^2]: `Data` refer to raw, unprocessed numerical representations (facts) about the world. Because of applying the process of scientific enquiry, we can make a case for data being the closest approximation and reflection of reality. In the context of natural systems, this could include measurements of temperature, precipitation, air quality, populations, communities, or any other quantifiable aspect of the environment. It is typically presented in a structured or unstructured format and lacks context or meaning.

[^3]: `Information` refers to data that have been processed, organised, and structured to provide context and meaning. It can be thought of as the result of adding structure and interpretation to raw data. In this stage, data are put into context, such as trends in climate change, loss of biodiversity, or increasing pollution levels. This helps us understand the state of the natural systems and identify potential problems.

[^4]: `Knowledge` is the next level of abstraction and refers to a deeper understanding or insight that is gained from information. It is the result of synthesising information to draw conclusions or make predictions. Through the process of knowledge generation we gain a deeper understanding of the underlying patterns, relationships, and principles. This stage involves continuing to use scientific methods, our and other's expertise, and past experiences to make sense of the information. For instance, understanding the factors driving climate change or the consequences of deforestation on ecosystems. In other words, knowledge is what we gain when we apply meaning and context to information, and we use it to make informed decisions or take actions.

[^5]: `Wisdom` is the final stage in the DIKW pipeline, and the highest level of abstraction possible. Here we apply knowledge to make informed, ethical, and sustainable decisions about how we interact with the natural systems that make up our planet, Earth. This stage involves critical thinking, foresight, and an understanding of the complex interdependencies within the environment. Wisdom allows us to make choices that balance our needs with the long-term health and resilience of the planet.

## On these pages

This website offers material in support of several modules taught at the [Biological and Conservation Biology Department](https://www.uwc.ac.za/study/all-areas-of-study/departments/department-of-biodiversity-and-conservation-biology/overview), [University of the Western Cape](http://www.uwc.ac.za/). The courses are taught by [AJ Smit](https://www.uwc.ac.za/study/all-areas-of-study/departments/department-of-biodiversity-and-conservation-biology/people) and are rich in [R](https://cran.r-project.org/) content. They include:

-   Plant Ecophysiology (BDC223)---to be developed
-   [Biogeography and Global Ecology (BDC334)](BDC334/BDC334_index.qmd)
-   [Introduction to R](BCB744/BCB744_index.qmd) and Biostatistics (BCB744)---in development
-   [Quantitative Ecology (BCB743)](BCB743/BCB743_index.qmd)

In addition to the taught material, there are vignettes with some R tricks I have learned over the years, including examples of how to analyse oceanographic and Earth datasets.
