---
title: "Species dissimilarities"
subtitle: "Assignment 2"  
author: 
  - "AJ Smit"
date: '2020/06/28 (updated: `r Sys.Date()`)'
output:
  xaringan::moon_reader:
    css:
      - default
      - "default-fonts.css"
      - ki
      - "uwc_logo.css"
    yolo: false
    self_contained: TRUE  
    lib_dir: libs
    nature:
      highlightStyle: idea
      highlightLines: true
      highlightLanguage: r
      countIncrementalSlides: false
      ratio: 16:9
---

```{r setup, include = FALSE, echo = FALSE} 
library(tidyverse)
library(ggpubr)
knitr::opts_chunk$set(echo = TRUE,
                      comment = "R>",
                      message = FALSE,
                      warning = FALSE,
                      include = TRUE,
                      fig.retina = 3,
                      fig.width = 6,
                      fig.height = 3.6,
                      fig.align = "center")
```

Submit a R script wherein you provide answers to Questions 1--9 by no later than 8:00 tomorrow. Label the script as follows: **`BCB743_<Name>_<Surname>_Assignment_2.R`**, e.g. **`BCB743_AJ_Smit_Assignment_2.R`**.

Refer to the [Species Dissimilarity lecture material](https://ajsmit.netlify.app/workshops/quantecol/chapters/05-spp_dissimilarity/) for the question context.

---

### Assignment 2 Questions

> **Question 1:** Look at the dataset and explain its structure in words.
>
> **Question 2:** Would we use Bray-Curtis or Jaccard dissimilarities?
>
> **Question 3:** Apply the calculation.
>
> **Question 4:** Explain the meaning of the results in broad terms.

---

> **Question 5:** Examine it more closely: what general pattern comes out?
>
> **Question 6:** Plot this pattern (hint, it is best seen in the 1st column of the dissimilarity matrix).
>
> **Question 7:** What explanation can you offer for this pattern?
>
> **Question 8:** Using the `decostand()` function, create presence/absence data, and apply the appropriate `vegdist()` function to obtain a suitable dissimilarity matrix.
>
> **Question 9:** Create another plot and explain the pattern.
