---
title: "PCA"
subtitle: "Assignment 4"  
author: 
  - "AJ Smit"
date: '2020/06/28 (updated: `r Sys.Date()`)'
output:
  xaringan::moon_reader:
    css:
      - default
      - "default-fonts.css"
      - ki
      - "uwc_logo.css"
    yolo: false
    self_contained: TRUE  
    lib_dir: libs
    nature:
      highlightStyle: idea
      highlightLines: true
      highlightLanguage: r
      countIncrementalSlides: false
      ratio: 16:9
---

```{r setup, include = FALSE, echo = FALSE} 
library(tidyverse)
library(ggpubr)
knitr::opts_chunk$set(echo = TRUE,
                      comment = "R>",
                      message = FALSE,
                      warning = FALSE,
                      include = TRUE,
                      fig.retina = 3,
                      fig.width = 6,
                      fig.height = 3.6,
                      fig.align = "center")
```

Submit a R script wherein you provide answers to Questions 1--8 by no later than 8:00 tomorrow. Label the script as follows: **`BCB743_<Name>_<Surname>_Assignment_4.R`**, e.g. **`BCB743_AJ_Smit_Assignment_4.R`**.

Refer to the [Principal Component Analysis lecture material](https://ajsmit.netlify.app/workshops/quantecol/chapters/06-pca/) to see the questions in context.

---

### Assignment 4 Questions

> **Question 1:** With reference to the sampling design (i.e. position of sample sites along the length of the river), provide mechanistics/ecological reasons for the strongly correlated environmental variables shown above in the pairwise correlation diagram. You might have to create additional spatial maps of scaled variables (as immediately above) to support your answer.
>
> **Question 2:** Provide a summary of the main findings of the Doubs River fish community structure study, focusing in this instance mainly on the environmental drivers.
>
> **Question 3:** Why can a PCA, or *any* ordination for that matter, not explain all of the variation in a dataset? In other words, why is it best to only use the first few Principal Components for insight into the drivers of variability? What is 'explained' by the remaining PC axes?

---

> **Question 4:** Replicate the analysis shown above on the **environmental data** included with these datasets: 1. [bird communities along elevation gradient in Yushan Mountain, Taiwan](https://www.davidzeleny.net/anadat-r/doku.php/en:data:ybirds); 2. [alpine plant communities in Aravo, France](https://www.davidzeleny.net/anadat-r/doku.php/en:data:aravo).
>
> **Question 5:** Discuss the patterns observed: 1. explain the ordination diagram with particular reference to the major patterns shown; 2. provide a mechanistic explanation for the existence of the patterns seen with respect to elevation/altitude; and 3. if there are significant positive or negative correlations between the environmental variables, provide mechanistic reasons for how they came about.
