---
title: "Biodiversity"
subtitle: "Assignment 1"  
author: 
  - "AJ Smit"
date: '2020/06/28 (updated: `r Sys.Date()`)'
output:
  xaringan::moon_reader:
    css:
      - default
      - "default-fonts.css"
      - ki
      - "uwc_logo.css"
    yolo: false
    self_contained: TRUE  
    lib_dir: libs
    nature:
      highlightStyle: idea
      highlightLines: true
      highlightLanguage: r
      countIncrementalSlides: false
      ratio: 16:9
---

```{r setup, include = FALSE, echo = FALSE} 
library(tidyverse)
library(ggpubr)
knitr::opts_chunk$set(echo = TRUE,
                      comment = "R>",
                      message = FALSE,
                      warning = FALSE,
                      include = TRUE,
                      fig.retina = 3,
                      fig.width = 6,
                      fig.height = 3.6,
                      fig.align = "center")
```

Submit a R script wherein you provide answers to Questions 1--9 by no later than 8:00 tomorrow. Label the script as follows: **`BCB743_<Name>_<Surname>_Assignment_1.R`**, e.g. **`BCB743_AJ_Smit_Assignment_1.R`**.

Refer to the [Biodiversity lecture material](https://ajsmit.netlify.app/workshops/quantecol/chapters/02-biodiversity/) for the question context.

---

### Assignment 1 Questions

> **Question 1:** Why is the matrix square, and what determines the number of rows/columns?
>
> **Question 2:** What is the meaning of the diagonal?
>
> **Question 3:** What is the meaning of the non-diagonal elements?
>
> **Question 4:** Take the data in row 1 and create a line graph that shows these values as a function of section number.
>
> **Question 5:** Provide a mechanistic (ecological) explanation for why this figure takes the shape that it does.

---

> **Question 6:** Why is there a difference between the two?
>
> **Question 7:** Which is correct?
>
> **Question 8:** Plot species turnover as a function of Section number, and provide a mechanistic exaplanation for the pattern observed.
>
> **Question 9:** Based on an assessment of literature on the topic, provide a discussion of nestedness-resultant β-diversity. Use either a marine or terrestrial example to explain this mode of structuring biodiversity.
