---
title: "Correlations & associations"
subtitle: "Assignment 3"  
author: 
  - "AJ Smit"
date: '2020/06/28 (updated: `r Sys.Date()`)'
output:
  xaringan::moon_reader:
    css:
      - default
      - "default-fonts.css"
      - ki
      - "uwc_logo.css"
    yolo: false
    self_contained: TRUE  
    lib_dir: libs
    nature:
      highlightStyle: idea
      highlightLines: true
      highlightLanguage: r
      countIncrementalSlides: false
      ratio: 16:9
---

```{r setup, include = FALSE, echo = FALSE} 
library(tidyverse)
library(ggpubr)
knitr::opts_chunk$set(echo = TRUE,
                      comment = "R>",
                      message = FALSE,
                      warning = FALSE,
                      include = TRUE,
                      fig.retina = 3,
                      fig.width = 6,
                      fig.height = 3.6,
                      fig.align = "center")
```

Submit a R script wherein you provide answers to Questions 1--8 by no later than 8:00 tomorrow. Label the script as follows: **`BCB743_<Name>_<Surname>_Assignment_3.R`**, e.g. **`BCB743_AJ_Smit_Assignment_3.R`**.

Refer to the [Correlations & Associations lecture material](https://ajsmit.netlify.app/workshops/quantecol/chapters/06-correlations/) to see the questions in context.

---

### Assignment 3 Questions

> **Question 1:** Create a plot of pairwise correlations.
>
> **Question 2:** Name to two top positive and two top negative *statistically-significant* correlations.
>
> **Question 3:** For each, discuss the mechanism behind the relationships. Why do these relationships exist?
>
> **Question 4:** Why do we need to transpose the data?

---

> **Question 5:** What are the properties of a transposed species table?
>
> **Question 6:** What are the properties of an association matrix? How do these properties differ from that of a i) species dissmilarity matrix and from a ii) correlation matrix?
>
> **Question 7:** What is the difference between `spp_assoc1` and `spp_assoc2`? Is the information contained in each markedly different from the other?
>
> **Question 8:** Explain the kind of insight we are able to glean from a species association matrix.
