---
title: 'BCB744 (BioStats): Summative Task 2'
date: '2023/04/11 (updated: `r Sys.Date()`)'
author:
- affiliation: University of the Western Cape
  name: AJ Smit
---

```{r global_options, include = FALSE}
knitr::opts_chunk$set(fig.path = 'compliled_figures/', include = TRUE, 
                      echo = TRUE, warning = FALSE, message = FALSE, 
                      tidy = FALSE, width.cutoff = 80, cache = FALSE, 
                      results = "hide", size = "small")
```

\section*{Instructions}

\begin{enumerate}
\item Produce full R scripts, including the meta-information at the top (name, date, purpose, etc.). Include comments explaining the purpose of the various tests/sections as necessary.
\item At the onset, \emph{assume} that all assumptions are met (they might not be!). For each question, i) state the name of the parametric statistical test selected and write a sentence or two to justify your choice, and ii) write down the appropriate $H_{0}$.
\item Test the assumptions. For each statistical test (as per 1.), state the appropriate assumptions to be tested, mention how you will test the assumptions (incl. writing out the $H_{0}$ if necessary, or explaining the principle behind a graphical method), and explain the findings. Given the outcome of the test of assumptions, is your choice of test selected in (1.) still correct? If some/all the assumption tests are violated, how will you proceed? 
\item Proceed with the analysis, and explain the findings in the light of the hypothesis tests stated at the beginning. ANOVAs, correlations, and regressions will require graphical support; this is not necessary for \emph{t}-tests.
\item Pay attention to formatting. 10\% will be allocated to the appearance of the script, including considerations of aspects of the tidiness of the file, the use of appropriate headings, and adherence to code conventions (e.g. spacing etc.).
\end{enumerate}

\section{The wheat yield data}

Please see the file '**fertiliser_crop_data.csv**' for this dataset. The data represent an experiment designed to test whether or not fertiliser type and the density of planting have an effect on the yield of wheat. The dataset contains the following variables:

\begin{itemize}
\item Final yield (kg per acre)
\item Type of fertiliser (fertiliser type A, B, or C)
\item Planting density (1 = low density, 2 = high density)
\item Block in the field (north, east, south, west)
\end{itemize}

\begin{description}
\item[Question 1] Do fertiliser type and planting density affect the yield of wheat? If so, which is the best density to plant wheat at, and which fertiliser produces the best yield?
\item[Question 2] Does it matter if the wheat is planted in portions of the experimental fields that face north, east, south, or west?
\end{description}

\section{The shells data}

See the '**shells.csv**' file. This dataset contains measurements of shell widths and lengths of the left and right valves of two species of mussels, \emph{Aulacomya} sp. and \emph{Choromytilus} sp. Length and width measurements are presented in mm.

\begin{description}
\item[Question 3] Which species of mussel is the i) widest and ii) longest?
\item[Question 4] Within each species of mussel, are the four different measurements correlated with each other?
\item[Question 5] Considering \emph{Aulacomya} sp. only, use a linear regression to predict the length of the left valve when the width of the left valve is 15 and 17 mm. 
\end{description}

\section{The health data}

These data are in '**health.csv**'. Inside the file are several columns, but the ones that are relevant to this question are:

\begin{itemize}
\item 'Sex', which is the gender of the individuals assessed
\item 'Substance', indicating the kind of drug abused by the individuals in question
\item 'Mental\_score', which is the outcome of a test designed to test the cognitive ability of individuals
\end{itemize}

\begin{description}
\item[Question 6] Do males and females suffer the same cognitive impairments if they abuse cocaine, alcohol, or heroin?
\item[Question 7] Which drug is worst in terms of affecting the user's mental health?
\end{description}

\section{The air quality data}

Package **datasets**, dataset `airquality`. These are daily air quality measurements in New York, May to September 1973. See the help file for details.

\begin{description}
\item[Question 8] Which two of the four response variables are best correlated with each other?
\item[Question 9] Provide a detailed correlation analysis for those two variables.
\end{description}

\section{The crickets data}

The file '**crickets.csv**' contains data for some crickets whose chirp rate was measured at several temperatures. The temperature was measured in °F, but please make sure you do all the calculations using °C instead.

\begin{description}
\item[Question 10] Does the chirp rate of the crickets depend on the temperature?
\item[Question 11] Provide an equation that quantifies this relationship.
\end{description}

\section{The SST data}

The file '**SST.csv**' contains sea surface temperatures for Port Nolloth and Muizenberg in °C. The data are from 1 January 2010 to 31 December 2011.

\begin{description}
\item[Question 12] Do the temperatures differ between the two places?
\item[Question 13] For each of the two sites, which month has the i) lowest and ii) highest temperature?
\item[Question 14] For each of the two sites, is the winter temperature colder than the summer temperature?
\item[Question 15] Same as Question 14, but use 95\% confidence intervals to approach this problem (and provide the supporting graphs).
\end{description}

Hint: The **lubridate** package (and others) offers convenient ways to work with time series (i.e. in this case coding a variable for month).

\hfill \break
That's all, Folks!


