---
title: "CA"
subtitle: "Assignment 6"  
author: 
  - "AJ Smit"
date: '2020/06/28 (updated: `r Sys.Date()`)'
output:
  xaringan::moon_reader:
    css:
      - default
      - "default-fonts.css"
      - ki
      - "uwc_logo.css"
    yolo: false
    self_contained: TRUE  
    lib_dir: libs
    nature:
      highlightStyle: idea
      highlightLines: true
      highlightLanguage: r
      countIncrementalSlides: false
      ratio: 16:9
---

```{r setup, include = FALSE, echo = FALSE} 
library(tidyverse)
library(ggpubr)
knitr::opts_chunk$set(echo = TRUE,
                      comment = "R>",
                      message = FALSE,
                      warning = FALSE,
                      include = TRUE,
                      fig.retina = 3,
                      fig.width = 6,
                      fig.height = 3.6,
                      fig.align = "center")
```

Submit a R script wherein you provide answers to Questions 1--3 by no later than 8:00 tomorrow. Label the script as follows: **`BCB743_<Name>_<Surname>_Assignment_6.R`**, e.g. **`BCB743_AJ_Smit_Assignment_6.R`**.

Refer to the [Correspondence Analysis lecture material](https://ajsmit.netlify.app/quantecol/chapters/09-ca/) to see the questions in context.

---

### Assignment 6 Questions

> **Question 1.** How would you explain the patterns seen in the four panels of the above figure?
>
> **Question 2.** Apply approaches taken from the analysis shown immediately above to these datasets: 1. [bird communities along elevation gradient in Yushan Mountain, Taiwan](https://www.davidzeleny.net/anadat-r/doku.php/en:data:ybirds); 2. [alpine plant communities in Aravo, France](https://www.davidzeleny.net/anadat-r/doku.php/en:data:aravo).
>
> **Question 3.** Discuss the patterns observed, and explain the ordination diagrams with particular reference to how the species are influenced by the major environmental drivers.
>
> **Question 4 (Bonus)** For bonus marks that could earn you 120/100, please see if you can recreate the bottom right figure for the species 'Cogo' using **ggplot2**. This will require digging deep into the ordination and ordisurf objects, creating dataframes for each layer of data, and assembling the graph manually.
