{
  "hash": "e757269d2f8280d753b0795c1583944a",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"9. Correlation and Association\"\nsubtitle: \"Quantifying Relationships Without Imposing a Response Model\"\ndate: last-modified\ndate-format: \"YYYY/MM/DD\"\nreference-location: margin\nnumber-sections: true\n---\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n::: {.callout-note appearance=\"simple\"}\n## In This Chapter\n\n-   Correlation as a measure of association\n-   Pearson, Spearman, and Kendall correlation\n-   Correlation versus regression\n-   Interpreting strength, sign, and uncertainty\n:::\n\n# Introduction\n\nIn the previous chapters we focused on comparing means across groups. Sometimes, however, our question is not whether groups differ, but whether two continuous variables tend to vary together. For example, do heavier kelps also have longer stipes? Do warmer waters also contain less dissolved oxygen? Do larger animals tend to have larger home ranges?\n\nThese are questions about **association**. The most familiar tool for this purpose is **correlation**, which quantifies the strength and direction of the relationship between two variables. Unlike regression, correlation does not formally assign one variable the role of response and the other the role of predictor. That distinction matters, because correlation is descriptive while regression is explicitly model-based.\n\nThis chapter therefore acts as a bridge. It closes the sequence of core inferential tools by showing how association can be quantified, but it also prepares the way for the regression chapters that follow.\n\n# Key Concepts\n\nThese ideas define the logic of the chapter before we move into the worked example.\n\n-   **Correlation** quantifies the strength and direction of association between variables.\n-   **Association is not causation** because correlation alone does not show that one variable causes changes in the other.\n-   **Correlation is not regression** because correlation does not specify a formal response and predictor.\n-   **Pearson, Spearman, and Kendall** answer related but not identical questions.\n-   **Strength, sign, and uncertainty** all matter when interpreting a correlation coefficient.\n\n# Nature of the Data and Assumptions\n\nThe appropriateness of a correlation analysis depends on the nature of the variables and on the question being asked.\n\n-   **Two measured variables** Correlation is used when we have two variables measured on the same sampling units.\n-   **Paired observations** Each value of one variable must correspond to the same observation in the other variable.\n-   **Independence of sampling units** The sampling units themselves should be independent of one another.\n-   **Appropriate form of relationship** Pearson correlation is most appropriate when the relationship is approximately linear and the variables are continuous. Spearman and Kendall correlation are more appropriate when the relationship is monotonic or when rank-based inference is preferred.\n-   **Outliers matter** Correlation coefficients can be strongly influenced by a small number of extreme values, so visual inspection is essential.\n\nBefore calculating a correlation coefficient, it is therefore necessary to make a scatterplot and inspect the overall pattern in the data.\n\n# R Functions\n\nThe main function used in this chapter is `cor.test()`. It can be applied with different methods:\n\n-   `method = \"pearson\"` for Pearson's product-moment correlation;\n-   `method = \"spearman\"` for Spearman's rank correlation;\n-   `method = \"kendall\"` for Kendall's rank correlation.\n\nThe base function `cor()` calculates the coefficient itself, but `cor.test()` is more useful for inference because it also returns a test statistic, confidence interval where appropriate, and a *p*-value.\n\n# A Worked Example\n\nWe will use the `ecklonia` data introduced in the previous chapter. Here we ask whether stipe length and stipe mass tend to vary together among individual kelps.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\necklonia <- read_csv(file.path(\"..\", \"..\", \"data\", \"BCB744\", \"ecklonia.csv\"))\n```\n:::\n\n\n## Do an exploratory data analysis (EDA)\n\nAs always, we begin by looking at the data numerically and graphically.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\necklonia %>%\n  summarise(\n    n = n(),\n    mean_stipe_length = mean(stipe_length),\n    sd_stipe_length = sd(stipe_length),\n    mean_stipe_mass = mean(stipe_mass),\n    sd_stipe_mass = sd(stipe_mass)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR> # A tibble: 1 × 5\nR>       n mean_stipe_length sd_stipe_length mean_stipe_mass sd_stipe_mass\nR>   <int>             <dbl>           <dbl>           <dbl>         <dbl>\nR> 1    26              531.            132.            5.56          1.60\n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(data = ecklonia, aes(x = stipe_length, y = stipe_mass, colour = site)) +\n  geom_point(size = 2.2, alpha = 0.8) +\n  geom_smooth(method = \"lm\", se = FALSE, linewidth = 0.8, colour = \"black\") +\n  labs(x = \"Stipe length (mm)\", y = \"Stipe mass (kg)\") +\n  theme_pubclean()\n```\n\n::: {.cell-output-display}\n![Association between stipe length and stipe mass in _Ecklonia maxima_.](09-correlation-and-association_files/figure-html/fig-ecklonia-correlation-1.svg){#fig-ecklonia-correlation fig-align='center' width=88%}\n:::\n:::\n\n\nThe scatterplot suggests a positive association: longer stipes tend to have larger mass. The pattern is not perfectly tight, but it is clearly not random either. This makes a correlation analysis sensible.\n\n## State the question and hypotheses\n\nThe central question is whether the association between stipe length and stipe mass differs from zero.\n\nFor Pearson correlation, the hypotheses are:\n\n$$H_{0}: \\rho = 0$$\n$$H_{a}: \\rho \\ne 0$$\n\nwhere $\\rho$ is the population correlation coefficient.\n\n## Apply Pearson correlation\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncor.test(ecklonia$stipe_length, ecklonia$stipe_mass, method = \"pearson\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR> \nR> \tPearson's product-moment correlation\nR> \nR> data:  ecklonia$stipe_length and ecklonia$stipe_mass\nR> t = 3.4592, df = 24, p-value = 0.002038\nR> alternative hypothesis: true correlation is not equal to 0\nR> 95 percent confidence interval:\nR>  0.2439676 0.7880821\nR> sample estimates:\nR>       cor \nR> 0.5768102\n```\n\n\n:::\n:::\n\n\n## Interpret the results\n\nThe Pearson correlation coefficient is positive ($r = 0.577$), which indicates that longer stipes tend to be associated with heavier stipes. The *p*-value is small ($p < 0.01$), so the data provide strong evidence against the null hypothesis of no linear association. The confidence interval for the correlation excludes zero, which supports the same conclusion.\n\nThis result does not mean that stipe length causes stipe mass or vice versa. It means only that the two variables co-vary positively in these data.\n\n## Reporting\n\nWhen reporting a correlation analysis, state:\n\n-   the variables being compared;\n-   the type of correlation used;\n-   the value of the correlation coefficient;\n-   the sample size;\n-   the test statistic and *p*-value;\n-   a short biological interpretation.\n\nFor example, you might report:\n\n> Stipe length and stipe mass in *Ecklonia maxima* were positively correlated (Pearson correlation: $r = 0.577$, $n = 26$, $p < 0.01$). The 95% confidence interval for the correlation coefficient ranged from 0.244 to 0.788, indicating a moderate positive association in which kelps with longer stipes also tended to have greater stipe mass.\n\n# Rank-Based Correlation\n\nPearson correlation is appropriate when the relationship is approximately linear and the variables are continuous. If the relationship is monotonic but not well described by a straight line, or if the data are rank-like or strongly influenced by outliers, a rank-based correlation may be preferable.\n\n## Spearman correlation\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncor.test(ecklonia$stipe_length, ecklonia$stipe_mass,\n         method = \"spearman\", exact = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR> \nR> \tSpearman's rank correlation rho\nR> \nR> data:  ecklonia$stipe_length and ecklonia$stipe_mass\nR> S = 1081.7, p-value = 0.0005598\nR> alternative hypothesis: true rho is not equal to 0\nR> sample estimates:\nR>       rho \nR> 0.6301745\n```\n\n\n:::\n:::\n\n\nSpearman's $\\rho$ asks whether the ranks of the two variables tend to increase together. In this example it also indicates a positive association ($\\rho = 0.630$, $p < 0.001$), which is broadly consistent with the Pearson result.\n\n## Kendall correlation\n\nKendall's $\\tau$ is another rank-based measure of association. It is often useful in smaller datasets or when tied ranks are common. The main practical point is that Spearman and Kendall provide alternatives when Pearson's assumptions are not plausible.\n\n# Correlation Versus Regression\n\nIt is important not to confuse correlation with regression.\n\n-   **Correlation** asks whether two variables vary together.\n-   **Regression** asks whether a response variable changes systematically as a function of one or more predictors.\n\nThis distinction is not just technical. If your question is \"do these variables co-vary?\", correlation is appropriate. If your question is \"how does the response change with the predictor?\", then you are already in the territory of regression. That is why this chapter naturally leads into the next one.\n\n# If Assumptions Fail\n\nIf the relationship is not linear, the variables are ordinal, or the data contain influential outliers, Pearson correlation may not be appropriate. In such cases:\n\n-   use Spearman or Kendall correlation for rank-based association;\n-   inspect the scatterplot carefully before interpreting any coefficient;\n-   move to a regression model if the real question is one of response and predictor rather than simple association.\n\n# Summary\n\nCorrelation is a measure of association, not a model of response. The important workflow is therefore:\n\n1. Plot the data.\n2. Decide whether the question is really about association.\n3. Choose Pearson, Spearman, or Kendall according to the data and relationship.\n4. Interpret the coefficient, uncertainty, and *p*-value together.\n5. Do not confuse association with causation, or correlation with regression.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}