{
  "hash": "1366ea2a60d3458f8324625b457fc616",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"8c: PCA of WHO SDGs\"\nsubtitle: \"Task C\"\nformat:\n  html:\n    code-fold: true\n    code-summary: \"Show the answers\"\n---\n\n\n::: {.cell}\n\n:::\n\n\n## Practice Task\n\nWork through these exercises after reading the [PCA of WHO SDGs](../PCA_SDG_example.qmd) chapter, reusing the WHO SDG data loaded there. Four exercises are hands-on calculations and two are short conceptual questions. A worked answer is given under each exercise; try it yourself before opening it.\n\n1. Reproduce the PCA of the WHO SDG data from the chapter: load and scale the data, run the ordination (`vegan::rda()` or `prcomp()`), and produce the biplot.\n\n::: {.callout-note collapse=\"true\"}\n## Show the answer\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nlibrary(tidyverse)\nlibrary(vegan)\n\nsdg <- read.csv(here::here(\"data\", \"BCB743\", \"WHO\", \"SDG_complete.csv\"))\nsdg_ind <- sdg |> select(starts_with(\"SDG\")) # the indicator columns\nrownames(sdg_ind) <- make.unique(as.character(sdg$Location))\nsdg_ind <- sdg_ind[complete.cases(sdg_ind), ] # keep countries with full records\n\npca_sdg <- rda(sdg_ind, scale = TRUE) # correlation PCA (indicators standardised)\n\nplot(pca_sdg, scaling = 2, type = \"n\", main = \"WHO SDG PCA (scaling 2)\")\npoints(pca_sdg, display = \"sites\", pch = 19, col = \"grey70\", cex = 0.5)\ntext(pca_sdg, display = \"species\", col = \"firebrick\", cex = 0.55)\n```\n\n::: {.cell-output-display}\n![](Task_C_files/figure-html/task-c-q1-1.svg)\n:::\n:::\n\n\nAfter dropping countries with missing indicators, the PCA runs on a standardised country-by-indicator matrix. The biplot shows the indicator arrows fanning out along PC1, with the countries (grey points) spread along the same axis. The first axis is a broad **attainment** gradient: indicators of good health outcomes point one way and indicators of burden or risk point the other, so a country's position along PC1 summarises where it sits on that composite scale.\n:::\n\n2. Produce a screeplot with the broken-stick criterion, report the variance explained by PC1 and PC2, and state how many components are worth interpreting.\n\n::: {.callout-note collapse=\"true\"}\n## Show the answer\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nvar_sdg <- round(100 * eigenvals(pca_sdg) / sum(eigenvals(pca_sdg)), 1)\nvar_sdg[1:6] # % variance, first 6 axes\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n PC1  PC2  PC3  PC4  PC5  PC6 \n44.5  8.5  5.6  4.8  4.5  3.7 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"false\"}\nscreeplot(\n  pca_sdg,\n  bstick = TRUE,\n  type = \"lines\",\n  main = \"SDG PCA: eigenvalues vs broken-stick\"\n)\n```\n\n::: {.cell-output-display}\n![](Task_C_files/figure-html/task-c-q2-1.svg)\n:::\n:::\n\n\nPC1 captures 44.5% of the variance and PC2 8.5% (together 53%), so the data are strongly one-dimensional. The broken-stick comparison confirms that the first one or two axes exceed the random expectation, so interpretation should focus on PC1, with PC2 read only as a weak secondary addition. The many trailing axes carry indicator-specific variation and noise.\n:::\n\n3. Examine the variable loadings and identify which SDG indicators load most strongly on PC1 and on PC2. What does each axis represent?\n\n::: {.callout-note collapse=\"true\"}\n## Show the answer\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nloadings <- scores(pca_sdg, display = \"species\", choices = 1:2) |>\n  as.data.frame()\nloadings |> arrange(PC1) |> slice(c(1:5, (n() - 4):n())) # most negative & most positive on PC1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               PC1         PC2\nSDG3.2_3 -1.406351 -0.08061411\nSDG3.2_1 -1.403091 -0.08442038\nSDG3.2_2 -1.384485 -0.12092644\nSDG3.7   -1.366977 -0.06717432\nSDG3.9_3 -1.317152 -0.09198457\nSDG3.c_4  1.237298 -0.19228848\nSDG3.c_1  1.240555  0.00330015\nSDG3.c_3  1.283114 -0.08710845\nSDG3.1_2  1.353637  0.19590231\nSDG3.8_2  1.354642 -0.07720902\n```\n\n\n:::\n:::\n\n\nThe indicators with the largest absolute PC1 loadings define the axis (the single strongest is SDG3.2_3): at one end sit indicators of poor health outcomes and high disease or mortality burden, and at the other end indicators of strong health-system performance and good outcomes. PC1 is therefore an overall health-and-development attainment gradient. PC2 is defined by a smaller set of indicators that distinguish countries with otherwise similar overall attainment, often separating a particular dimension (such as a specific disease burden or a financing measure) from the general pattern; it is a secondary contrast rather than a second major gradient.\n:::\n\n4. Locate South Africa and three or four comparator countries of your choice on the biplot, and describe where they sit relative to the axes.\n\n::: {.callout-note collapse=\"true\"}\n## Show the answer\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nfocus <- c(\"South Africa\", \"Nigeria\", \"Germany\", \"Brazil\", \"Norway\")\nsite_sc <- scores(pca_sdg, display = \"sites\", choices = 1:2, scaling = 2) |>\n  as.data.frame() |>\n  rownames_to_column(\"country\")\nsite_sc |> filter(country %in% focus)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       country        PC1        PC2\n1       Brazil  0.3338315 -0.2950017\n2      Germany  0.8569510  0.3329607\n3      Nigeria -1.5157883 -0.5176548\n4       Norway  0.8851571 -0.6758352\n5 South Africa -0.3362570  1.6863449\n```\n\n\n:::\n:::\n\n\nThe comparator countries spread along PC1 in the order one would expect from their health systems: South Africa sits at PC1 = -0.34, between Norway (0.89) and Nigeria (-1.52) at the two ends of the attainment axis, with Brazil nearby. South Africa's score should be read against these neighbours rather than against any single raw indicator: countries close together on the biplot share a similar *multivariate* SDG profile, which is exactly the summary PCA is designed to give.\n:::\n\n5. Explain why the SDG indicators must be standardised (scaled) before PCA, and what would happen to the ordination if they were left on their original scales.\n\n::: {.callout-note collapse=\"true\"}\n## Show the answer\n\nPCA decomposes variance, and variance depends on the measurement scale. The SDG indicators are recorded in incompatible units, namely percentages, rates per 100 000, monetary measures, and counts, so their raw variances differ by orders of magnitude. Without standardisation (here `scale = TRUE`, equivalent to a PCA on the correlation matrix), the indicators with the largest numerical spread would dominate the first axis for purely arithmetic reasons, and the ordination would describe which variable happens to be measured on the biggest scale rather than which countries are alike. Scaling each indicator to unit variance puts them on an equal footing so that the axes reflect shared structure across indicators.\n:::\n\n6. Interpret PC1 as an SDG-attainment gradient: what does a country's score on PC1 tell you, and what are the limitations of collapsing SDG attainment onto a single axis?\n\n::: {.callout-note collapse=\"true\"}\n## Show the answer\n\nA country's PC1 score is a composite index: it places the country on the dominant axis of co-variation among the health indicators, so a high score means the country tends to score well across the bundle of correlated indicators that define the axis. That single number is a useful, defensible summary because the indicators are strongly correlated. Its limitations are real, though: collapsing many goals onto one axis hides **trade-offs** (a country may do well on some goals and poorly on others), it is sensitive to the **missing-data** decisions made before the PCA, it ignores **within-country inequality**, and the very choice to reduce attainment to one number embeds a value judgement about how the goals should be weighted. PC1 is a starting description, not a verdict.\n:::\n\n## Assessment Criteria\n\nThis Task is not formally assessed. It is built around four hands-on analyses (Exercises 1--4) and two short conceptual questions (Exercises 5--6); work through all six and bring your annotated Quarto document to class for discussion.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}