{
  "hash": "70435105d5ca9e9d68f8383a177cf199",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"21. Nonlinear Regression\"\nsubtitle: \"When Straight Lines Are Not Enough\"\nauthor: \"A. J. Smit\"\ndate: last-modified\ndate-format: \"YYYY/MM/DD\"\nreference-location: margin\n---\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n::: {.callout-note appearance=\"simple\"}\n## In This Chapter\n\n-   Why some biological relationships are mechanistically nonlinear\n-   How nonlinear regression differs from polynomial and additive models\n-   The logic of named nonlinear functions\n-   A worked Michaelis-Menten example\n-   What to check when fitting nonlinear models\n:::\n\n# Introduction\n\nSome relationships are curved because the biology is curved. Growth saturates, enzyme kinetics asymptote, seasonal cycles oscillate, and responses may level off, bend, or change slope across the range of the predictor. In such cases, a straight-line model is often too rigid.\n\nThis chapter focuses specifically on mechanistic nonlinear regression: models where the response is described by a named nonlinear function whose parameters have scientific meaning. Examples include saturating uptake curves, logistic growth, seasonal sine curves, and other biologically motivated responses.\n\nPolynomial regression and GAMs are covered in their own chapters because they answer a different modelling need. Here the emphasis is narrower and stronger: what to do when the biology suggests the form of the curve itself.\n\n# Key Concepts\n\n-   **Nonlinearity** often reflects real biological structure rather than unwanted curvature.\n-   **Flexible regression** can model patterns that a straight line misses.\n-   **Mechanistic nonlinear models are appropriate when the curve has a biologically motivated form.**\n-   **Greater flexibility increases the risk of overfitting** if used carelessly.\n-   **Model choice should follow biological form**, not only convenience or visual preference.\n\n# When This Method Is Appropriate\n\nYou should move beyond a simple linear model when:\n\n-   the fitted residuals show clear curvature;\n-   the biology suggests an asymptote, threshold, saturation, or oscillation;\n-   the response changes differently across the predictor range;\n-   the question concerns parts of the response distribution other than the mean.\n\nThe diagnostic chapters earlier in the sequence already suggested this possibility. This chapter is about what to do next.\n\n# Nature of the Data and Assumptions\n\nMechanistic nonlinear regression is still regression, so the familiar concerns about independence, residual spread, and overall model adequacy do not disappear. In many introductory applications, the response variable is continuous and the residuals are assumed to be approximately normally distributed with constant variance.\n\nThe key distinction is that the mean structure is explicitly nonlinear and tied to a named function. These models are usually fitted by nonlinear least squares with `nls()`, or by mixed-effects extensions when grouped or repeated-measures data are present.\n\nThe practical point is that you do not choose a curved model just because it draws a pleasing bendy line through the points. You choose it because the straight-line model is inadequate and because the curved alternative matches the biological process or the inferential question more closely.\n\n# The Core Equation\n\nThe general form of a nonlinear regression is:\n\n$$Y_i = f(X_i, \\theta) + \\epsilon_i$$ {#eq-nonlinear}\n\nIn @eq-nonlinear, $f(\\cdot)$ is a biologically chosen nonlinear function and $\\theta$ represents the parameter set that defines its shape. This chapter then uses a Michaelis-Menten curve as the main worked example of that general idea.\n\n# R Functions\n\nSome of the most useful R functions are:\n\n-   `nls()` for nonlinear least-squares models;\n-   `nlme::nlme()` when nonlinear relationships occur in grouped or repeated-measures data.\n\nExamples:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm(response ~ poly(x, degree = 2), data = df)\nnls(y ~ Vmax * x / (Km + x), data = df,\n    start = list(Vmax = 1, Km = 1))\nnlme::nlme(y ~ Vmax * x / (Km + x), data = df, ...)\n```\n:::\n\n\nOne practical difference from ordinary regression is that `nls()` usually needs sensible starting values. Unlike `lm()`, it uses an iterative search for the best-fitting parameter values, and poor starting values can prevent convergence.\n\n# Example 1: Why Use a Mechanistic Nonlinear Model?\n\nThe first decision is whether the biology gives you a reason to prefer a specific nonlinear function rather than a descriptive curve.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Examples of curved models fitted to simulated data. A polynomial can capture modest curvature, a GAM can adapt flexibly to the data, and a mechanistic nonlinear model can represent a known saturating biological response.](21-nonlinear-regression_files/figure-html/fig-main-families-1.svg){#fig-main-families}\n:::\n:::\n\n\n@fig-main-families shows three broad situations:\n\n-   A polynomial model can describe modest curvature, but it is mainly descriptive.\n-   A GAM is very useful when the relationship is clearly curved but its exact form is unknown or not informative.\n-   A mechanistic nonlinear model is most attractive when the biology suggests a specific function, because its parameters can often be interpreted directly.\n\nThat last point is important. If we know the process should saturate, as in nutrient uptake kinetics, a mechanistic model tells us more than a flexible smoother. It gives us interpretable parameters such as an asymptote or a half-saturation constant.\n\n# Example 2: Algal Nutrient Uptake Kinetics\n\nWe can measure algal nutrient uptake rates using a multiple flask experiment. We prepare a series of flasks, each containing a different initial concentration of the substrate nutrient, and then estimate nutrient uptake rate over a fixed time interval. The result is a set of uptake rates, $V$, paired with substrate concentrations, $[S]$.\n\nApplied to algae, the Michaelis-Menten model assumes an irreversible uptake process that saturates at high substrate concentrations. It effectively quantifies key characteristics of the nutrient uptake system, including the maximum uptake rate and the alga's affinity for the nutrient:\n\n$$V_i = \\frac{V_{max} \\cdot [S_i]}{K_m + [S_i]} + \\epsilon_i$$ {#eq-mm}\n\nIn @eq-mm:\n\n-   $V_i$ is the uptake rate at the $i$-th observation;\n-   $V_{max}$ is the maximum nutrient uptake rate achieved;\n-   $[S_i]$ is the substrate concentration at the $i$-th observation;\n-   $K_m$ is the substrate concentration at which uptake reaches half of $V_{max}$; and\n-   $\\epsilon_i$ is the residual error.\n\nThe two parameters are biologically meaningful. $V_{max}$ represents the maximum capacity of the alga to utilise the nutrient, while $K_m$ describes the affinity of the uptake system for that nutrient. Lower values of $K_m$ indicate higher affinity.\n\n## Do an Exploratory Data Analysis (EDA)\n\nTo demonstrate fitting a nonlinear model to $V$ versus $[S]$ data from a multiple flask experiment, I simulate data across a range of substrate concentrations. The dataset consists of five replicate flasks for each of 13 substrate concentrations.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconc_vec <- c(0, 0.1, 0.5, 2, 5, 7.5, 10, 12.5, 15, 17.5, 20, 25, 30)\nn_rep <- 5\nKm_vec <- c(10)\nVmax_vec <- c(50)\nKm_vec_sd <- c(1.2)\nVmax_vec_sd <- c(0.7)\n\nmf_data <- generate_data(\n  n_trt = 1,\n  n_rep = n_rep,\n  conc_vec = conc_vec,\n  Km_vec = Km_vec,\n  Vmax_vec = Vmax_vec,\n  Km_vec_sd = Km_vec_sd,\n  Vmax_vec_sd = Vmax_vec_sd\n) |>\n  select(rep, S, V)\n\nmf_data\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 65 × 3\n   rep       S     V\n   <fct> <dbl> <dbl>\n 1 1       0   0    \n 2 2       0   0    \n 3 3       0   0    \n 4 4       0   0    \n 5 5       0   0    \n 6 1       0.1 0.511\n 7 2       0.1 0.588\n 8 3       0.1 0.480\n 9 4       0.1 0.496\n10 5       0.1 0.453\n# ℹ 55 more rows\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Plot of uptake rate, V, as a function of substrate concentration, [S], for a multiple flask experiment. The relationship is clearly curved and tends towards saturation.](21-nonlinear-regression_files/figure-html/fig-mf-eda-1.svg){#fig-mf-eda}\n:::\n:::\n\n\nThe plot in @fig-mf-eda already suggests that a straight line is not the right model. Uptake increases quickly at low substrate concentrations and then begins to level off. That is exactly the sort of pattern for which a Michaelis-Menten model was designed.\n\n## State the Model Question\n\nAt this point, two related questions arise.\n\nThe first is descriptive and mechanistic: can we estimate the uptake parameters $V_{max}$ and $K_m$ from these data?\n\nThe second is comparative: does a Michaelis-Menten model fit these data better than a simple linear model?\n\nThose are not the same question. The first is about parameter estimation within a nonlinear biological model. The second is about choosing between two competing mean structures.\n\n## Fit the Model\n\nThe Michaelis-Menten model is fit with `nls()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnls_mod <- nls(\n  V ~ mm_fun(S, Vmax, Km),\n  data = mf_data,\n  start = c(Vmax = 30, Km = 5)\n)\n\nsummary(nls_mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nFormula: V ~ mm_fun(S, Vmax, Km)\n\nParameters:\n     Estimate Std. Error t value Pr(>|t|)    \nVmax  51.4417     1.1770   43.70   <2e-16 ***\nKm    10.5507     0.5975   17.66   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.312 on 63 degrees of freedom\n\nNumber of iterations to convergence: 3 \nAchieved convergence tolerance: 8.864e-06\n```\n\n\n:::\n:::\n\n\nThe starting values do not have to be exact, but they should be sensible. Here we know from the plot that the asymptote is probably somewhere around 40 to 50, and that the half-saturation constant is likely to be in the single digits.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Michaelis-Menten model fitted to the uptake data. The dashed lines indicate the estimated Km and Vmax values.](21-nonlinear-regression_files/figure-html/fig-mf-fit-1.svg){#fig-mf-fit}\n:::\n:::\n\n\n## Check Diagnostics\n\nBecause this is a least-squares nonlinear model, residual diagnostics are interpreted much as they are for ordinary regression.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmf_data <- mf_data |>\n  mutate(\n    fitted = fitted(nls_mod),\n    resid = resid(nls_mod)\n  )\n\nshapiro.test(mf_data$resid)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  mf_data$resid\nW = 0.97225, p-value = 0.1517\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Basic diagnostics for the Michaelis-Menten fit. The residuals show no serious trend with the fitted values, and the distribution is approximately symmetric.](21-nonlinear-regression_files/figure-html/fig-mf-diagnostics-1.svg){#fig-mf-diagnostics}\n:::\n:::\n\n\nThese diagnostics do not suggest any serious problem. The residual spread is fairly even, and the histogram is approximately symmetric. As always, you should not rely on a single formal test, but the residual behaviour is consistent with a usable fit.\n\n## Interpret the Results\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm_mod <- lm(V ~ S, data = mf_data)\nmodel_comp <- anova(lm_mod, nls_mod)\nf_stat <- model_comp$F[2]\n\nAIC(lm_mod, nls_mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        df      AIC\nlm_mod   3 395.8491\nnls_mod  3 223.6862\n```\n\n\n:::\n\n```{.r .cell-code}\nBIC(lm_mod, nls_mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        df      BIC\nlm_mod   3 402.3723\nnls_mod  3 230.2094\n```\n\n\n:::\n\n```{.r .cell-code}\nmodel_comp\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: V\n          Df  Sum Sq Mean Sq F value    Pr(>F)    \nS          1 10274.8 10274.8  422.59 < 2.2e-16 ***\nResiduals 63  1531.8    24.3                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nThe fitted nonlinear model gives estimated values for $V_{max}$ and $K_m$, and these are the biologically meaningful outputs of the analysis. The estimated $V_{max}$ is the asymptotic uptake rate, while $K_m$ indicates the substrate concentration at which the uptake rate reaches half of that asymptote.\n\nThe model comparison also matters. If the linear and Michaelis-Menten models are both fitted to the same data, the nonlinear model has markedly lower information criteria and a much smaller residual error. That supports the biological interpretation already suggested by the plot; that is, uptake increases with substrate concentration, but it does so in a saturating rather than indefinitely linear way.\n\n## Reporting\n\n::: {.callout-note appearance=\"simple\"}\n## Write-Up\n\n**Methods**\n\nNutrient uptake rate was modelled as a function of substrate concentration with a Michaelis-Menten nonlinear regression fitted by nonlinear least squares. The nonlinear model was compared with a simple linear regression using information criteria and nested model comparison to assess whether the saturating form provided a better description of the data.\n\n**Results**\n\nNutrient uptake increased rapidly with substrate concentration at low concentrations and then approached an asymptote, consistent with Michaelis-Menten kinetics (@fig-mf-fit). The fitted nonlinear model estimated a maximum uptake rate of 51.44 and a half-saturation constant of 10.55. Relative to a simple linear regression, the Michaelis-Menten model provided the better description of the data, with lower AIC and BIC values and a significant improvement in fit (F = NA, `p < 0.05`).\n\n**Discussion**\n\nThe main biological point is that uptake is saturating rather than indefinitely linear over the observed concentration range. That matters because the fitted parameters now speak directly to uptake capacity and nutrient affinity.\n:::\n\n## What If We Add Treatments?\n\nExperiments are seldom as simple as the one above. Consider an experiment designed to assess whether an experimental treatment, such as light intensity or seawater temperature, affects nutrient uptake kinetics. It is biologically plausible to expect that each treatment will result in unique $V_{max}$ and $K_m$ values.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmf_data2 <- generate_data(\n  n_trt = 3,\n  n_rep = 5,\n  conc_vec = conc_vec,\n  Km_vec = c(10, 8, 6),\n  Vmax_vec = c(50, 40, 22),\n  Km_vec_sd = c(1.2, 1.1, 1.0),\n  Vmax_vec_sd = c(0.7, 1.0, 0.8)\n)\n```\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Simulated nutrient uptake curves for three treatments. The pattern suggests treatment-specific nonlinear responses rather than a single shared curve.](21-nonlinear-regression_files/figure-html/fig-mf-treatment-1.svg){#fig-mf-treatment}\n:::\n:::\n\n\nAt that point, the modelling problem becomes a bit more challenging and exciting. A separate `nls()` fit can be used for each treatment, or a nonlinear mixed-effects model can be used when dependence or grouping must be handled explicitly. That is the nonlinear counterpart of the fixed-effects and mixed-effects logic introduced in [Chapter 18](18-dependence-and-mixed-models.qmd). If the response is also non-normal, you are moving towards the broader territory covered in [Chapter 19](19-generalised-linear-models.qmd).\n\nThe important point is that nonlinear modelling “draws a curve” *and* it chooses a mean structure that matches the process and then extending that structure carefully when treatments, dependence, or more complicated designs are present.\n\n# Choosing Among Flexible Models\n\nThere are a few practical considerations to keep in mind when choosing a mechanistic nonlinear model. Sometimes different curved models can provide similar fits to the same data, but they have very different implications for interpretation. The reason to prefer a mechanistic nonlinear model is precisely that its parameters mean something biologically. If that interpretability is weak or artificial, a descriptive alternative such as a polynomial regression or GAM may be more honest.\n\n# Practical Caution\n\nFlexibility is valuable, but it comes with a cost.\n\n-   More flexible models are often harder to interpret.\n-   They can overfit small datasets.\n-   They may fit noise rather than structure if the biological logic is weak.\n-   Nonlinear least-squares models can fail to converge if the functional form or starting values are poor.\n\nThis is why flexible regression should be a response to a clear diagnostic or biological need, not just a default preference for curved lines.\n\n# Summary\n\n-   Not all biological relationships are well described by straight lines.\n-   Mechanistic nonlinear models serve a distinct purpose within the broader family of curved-response models.\n-   Model choice should follow the biology and the inferential goal.\n-   Mechanistic nonlinear models are especially valuable when their parameters have clear biological meaning.\n-   Greater flexibility can improve fit, but it also increases interpretive demands and the risk of overfitting.\n\nThe next chapter extends the regression sequence in a different direction again by asking what happens when the scientific target is not the conditional mean, but another part of the response distribution.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}