{
  "hash": "89c2f0846e012e8f1b849080008312ca",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lecture 6: Pigments & Photosynthesis\"\nsubtitle: \"Theory\"\nformat:\n  html:\n    anchor-sections: true\n    number-sections: true\n    page-layout: article\n  typst:\n    fontsize: 11pt\n    hyphenate: true\n    lang: en\n    mainfont: \"Minion Pro\"\n    section-numbering: 1.1.1.1\n    toc: true\n---\n\n::: callout-tip\n## This Theory Accompanies the Following Lab\n\n- [Lab 3: PI Curves — Jassby and Platt](Lab3_PI_curves.qmd)\n:::\n\n![](images/BDC223_L06a_slide01.jpeg)\n\n## Introduction: Pigments and Photosynthesis\n\n![](images/BDC223_L06a_slide02.jpeg)\n\nGood morning everyone, welcome back to BDC223. Today we are going to follow on from our lectures on light, and we are going to be talking about pigments and photosynthesis. Much of today's discussion, and also the next couple of lectures about pigments as well as chromatic adaptation, is based on two papers I need you to read. The papers are both on iKamva; you can find them there. Please read them while working through these lectures — it is quite important that you understand their content. Everything I am going to talk about today will be explained in a lot greater detail in those two papers.\n\n## Overview of Pigments in Photosynthetic Organisms\n\n![](images/BDC223_L06a_slide03.jpeg)\n\nSo, in order to exploit the light available in the environment, plants and algae — indeed, all photo-oxygenic organisms — rely on a range of pigments that extract energy from light and convert it into chemical potential energy in the process of photosynthesis.\n\nThe predominant pigment in all photo-oxygenic production on Earth, and in all plants, algae, and cyanobacteria, is a molecule called chlorophyll-*a*. The chlorophyll-*a* pigment takes light energy and converts it into chemical energy. It is the only pigment that plays such a central role in photosynthesis. There are many other pigments called accessory pigments; they do not directly drive photosynthesis but support light harvesting.\n\n## Absorption Properties of chlorophyll-*a* and Accessory Pigments\n\nChlorophyll-*a* absorbs light mainly in the blue and red regions. In the previous lecture you saw that visible light falls between roughly $390$ nm to around $760$ nm. That is the range of photosynthetically active radiation. However, within that range, not all light is equally effective at driving photosynthesis. This is because chlorophyll-*a* can maximally absorb light at $440$ nm (blue light) and $675$ nm (red light).\n\nRegardless of where these primary producers are — on land, in water, or elsewhere — they are sensitive to blue and red light. If they do not have sufficient light at precisely those wavelengths, their rate of photosynthesis will be impaired.\n\n![](images/BDC223_L06a_slide04.jpeg)\n\nHere are some graphs (Slide reference) that show the absorption for chlorophyll-*a* and chlorophyll-*b*. chlorophyll-*a*, shown as the red line, has two main peaks: one around $425$ nm (blue) and one in the red region around $660$ to $675$ nm. Chlorophyll-*b* has similar peaks but they are shifted: the blue peak sits nearer to $460$ nm, closer to green, and the red peak falls slightly toward the orange region.\n\n![](images/BDC223_L06a_slide05.jpeg)\n\nChlorophyll-*b* (in fact, none of the accessory pigments) does not drive photosynthesis directly, but it can harvest light and pass that energy to chlorophyll-*a*, thus broadening the range of light absorbed and utilised for photosynthesis. You will notice that, in the middle of these spectra, there is a gap — a region where light is available yet not absorbed by chlorophyll-*a* or *b*. This is often referred to as the \"green gap\" and is the reason why plants appear green: green light is not absorbed by the major photosynthetic pigments in most leaves, so it is reflected back into the environment and to our eyes.\n\n::: callout-note\n## How Do Accessory Pigments Pass on Energy to the Reaction Centers?\n\nAccessory pigments transfer the energy they capture from light to chlorophyll-*a* through a mechanism known as resonance energy transfer (more precisely, Förster resonance energy transfer, or FRET, in biophysical terms). This is a non-radiative process, meaning that the energy is not emitted as light and then reabsorbed, but is instead conveyed directly through electromagnetic interactions between the excited accessory pigment and the chlorophyll-*a* molecule. When a photon excites an accessory pigment, its electrons are elevated to a higher energy state; as this energy relaxes, it is transferred to a neighbouring chlorophyll-*a* molecule if the two pigments are sufficiently close (usually within 2–6 nanometres) and their electronic energy levels are appropriately aligned. At distances below ~1–2 nanometers, excitonic coupling can take place, wherein the excited states of neighbouring pigments become quantum-mechanically delocalised across multiple molecules rather than localising on discrete donors and acceptors.\n\nThe thylakoid membrane in chloroplasts is not a disordered soup of pigments but a carefully arranged molecular architecture known as the light-harvesting complex (LHC). Within these complexes, accessory pigments (such as chlorophyll-*b* and various carotenoids) are embedded in protein scaffolds alongside chlorophyll-*a* in spatial configurations that maximise energy transfer efficiency. The proteins hold pigments at precise orientations and distances that facilitate resonance coupling between excited states. The energy \"hops\" from pigment to pigment down an energetic gradient, ultimately funnelling to the reaction centre chlorophyll-*a*, where the photochemical conversion (electron transfer) occurs. This funnel-like arrangement of pigments and the efficiency of resonance transfer together allow plants and algae to capture a broad spectrum of solar radiation and direct it toward the relatively narrow photochemical core without significant loss.\n:::\n\n## The Green Gap and Accessory Pigments\n\n![](images/BDC223_L06a_slide06.jpeg)\n\nPlants have evolved various pigments to fill that green gap. Among the most notable of these are carotenoids, which include beta-carotene, and the phycobilins, such as phycoerythrin and phycocyanin. Carotenoids are also the pigments responsible for the orange colour in carrots, as indicated by the orange line on many absorption spectra.\n\nThe carotenoids and phycobilins absorb light in the green gap and pass that energy on to chlorophyll-*a*, enabling photosynthesis that would otherwise not occur at those wavelengths. These are called accessory pigments because they complement the absorption range of chlorophyll-*a* and make photosynthesis more effective in sub-optimal light conditions.\n\nAt first glance, the diversity of accessory pigments appears as vast as the diversity of light climates in the ocean, on land, and in freshwater. However, later experiments — especially those by Engelman, Haxo, and Blinks (to be discussed in your papers)—demonstrate that the diversity of accessory pigments does not necessarily correspond to the diversity of environmental light conditions.\n\n## Classification and Function of Pigments\n\n![](images/BDC223_L06a_slide07.jpeg)\n\nThere are three main pigment classes:\n\n1.  **Chlorophylls** – The major photosynthetic pigments. chlorophyll-*a* is primary, with chlorophylls-b and -c acting as accessory pigments that transfer absorbed energy to chlorophyll-*a*.\n2.  **Carotenoids** – Includes beta-carotene and xantho-phylls, which also serve as accessory pigments.\n3.  **Phycobilins** – Reddish or purplish pigments, including phycocyanin and phycoerythrin, mainly found in certain algae and cyanobacteria.\n\nAcross all photoautotrophs, there are more than forty pigments involved. They bind differently to the proteins making up the photosynthetic machinery, expanding the plant's ability to absorb different wavelengths, especially in the green gap, and maintain high photosynthetic efficiency in a range of environments.\n\n![](images/BDC223_L06a_slide08.jpeg)\n\nEspecially in algae, the types of pigments present can indicate taxonomic relationships and phylogenetic heritage. By extracting pigments from a seawater sample, for example, one can deduce the classes of algae present. Similar underpinnings occur in terrestrial plants, with certain pigments associated with specific plant types.\n\n## What Is Photosynthesis?\n\nPhotosynthesis is the conversion of light energy — radiant energy — into chemical potential energy. It drives carbon fixation: uptake of $\\mathrm{CO}_2$ from the environment, splitting water, and releasing oxygen as a byproduct. The reactions occur in the photosystems I and II.\n\nAs a function of light intensity, photosynthesis responds with an increased rate — to a point. This relationship is described by the photosynthesis-irradiance (PI) curve.\n\n## The Photosynthesis-Irradiance (PI) Curve\n\n![](images/BDC223_L06a_slide09.jpeg)\n\nThe PI curve (Slide reference):\n\n-   **Y-Axis**: Rate of photosynthesis, measured by carbon incorporation (e.g., mg C m$^{-2}$ s$^{-1}$, mg C m$^{-2}$ hr$^{-1}$, or mg C m$^{-2}$ day$^{-1}$).\n-   **X-Axis**: Irradiance (light intensity).\n\n![](images/BDC223_L06a_slide10.jpeg)\n\nInitially, the PI curve is linear: as irradiance increases, photosynthesis increases at a rate defined by the slope $\\alpha$ (alpha). Alpha reflects the plant's sensitivity to changes in irradiance. A steep alpha (steep slope) means more sensitivity to small changes in light; a shallow slope indicates less sensitivity and a need for greater changes in light intensity to affect photosynthesis rate.\n\nAt a certain point, the rate reaches saturation, denoted as $I_k$. This occurs where the extrapolated horizontal maximum rate ($P_{max}$) intersects with the linear part of the curve. Beyond this, increasing light does not increase photosynthetic rate since all the photosynthetic machinery is working at full capacity — much like pressing a car accelerator to the floor when the engine cannot go faster.\n\nShould irradiance keep increasing, photosynthesis can decline — a phenomenon called photoinhibition. Here, excessive light can cause actual damage, or trigger protective mechanisms within the photosynthetic apparatus to prevent damage, analogous to running a car engine past its operating limits.\n\nRespiration occurs at all times, consuming oxygen, while photosynthesis (in the presence of light) produces it. At low light, the rate of oxygen production by photosynthesis is less than the rate of consumption by respiration, resulting in net negative oxygen production. The light compensation point is the irradiance where net oxygen production is zero.\n\n**Net photosynthesis**: Above the compensation point — positive net oxygen evolution.\\\n**Gross photosynthesis**: Total oxygen produced, regardless of respiration.\n\nUnderstanding these parameters — the light compensation point, $\\alpha$, $P_{max}$, $I_k$, etc.—is crucial. We will revisit this concept in practical sessions where you will fit models to real data.\n\n### The hyperbolic tangent model\n\nThe hyperbolic tangent model was proposed by Jassby and Platt (1976). It has become one of the most widely used models for describing the relationship between photosynthetic rate and irradiance (light intensity) in aquatic photosynthetic organisms, including algae ranging from kelp to phytoplankton. The model captures the core dynamics of photosynthesis, in which the rate of photosynthesis initially increases with light intensity but eventually saturates as the photosynthetic machinery reaches its maximum efficiency. This is a simple model, but it effective because the biologically meaningful parameters can be directly interpreted to assess plant or algal productivity in various light environments.\n\nThe hyperbolic tangent model is expressed as:\n\n$$ P(I) = P_{\\text{max}} \\times \\tanh\\left(\\frac{\\alpha I}{P_{\\text{max}}}\\right) $$\n\nWhere:\n\n- $P(I)$ represents the photosynthetic rate at a given irradiance $I$ (light intensity),\n- $P_{\\text{max}}$ is the maximum photosynthetic rate (also referred to as the light-saturated rate),\n- $\\alpha$ is the initial slope of the curve, which reflects the photosynthetic efficiency at low light levels,\n- $I$ is the irradiance (light intensity),\n\nOne is also able to determine the saturating irradiance, $I_{\\text{k}}$, which is the light intensity at which photosynthesis reaches $P_{\\text{max}}$. Simply read this value off the graph where $P(I) = P_{\\text{max}}$ (see the lecture slides '6.BDC223_Pigments_Photosynthesis_2024.key.pdf'.\n\nThe hyperbolic tangent function $\\tanh$ is used to smoothly describe the transition between the linear increase in photosynthesis at low light intensities and the eventual plateau at higher intensities, where photosynthesis becomes light-saturated. The light compensation point, the point at which photosynthesis equals respiration (i.e., net photosynthesis is zero), can also be derived from this model.\n\nThe model describes the essential processes of photosynthesis with just two parameters: $P_{\\text{max}}$ and $\\alpha$. Both parameters are biologically meaningful and tell us how efficiently an organism can convert light into chemical energy under different light conditions. For example, higher values of $P_{\\text{max}}$ indicate a greater potential for photosynthesis under optimal light conditions, while the value of $\\alpha$ indicates how quickly photosynthesis responds to low light.\n\nApplications of the hyperbolic tangent model are numerous. It is commonly used to estimate the photosynthetic performance of marine and freshwater algae, seagrasses, and macroalgae under varying environmental conditions. In kelp forests, for instance, we may use this model to assess how different species adapt to light intensities at various depths or how photosynthetic performance shifts in response to seasonal changes in light availability. Looking at phytoplankton, the model helps estimate productivity across different layers of the water column, where light intensity decreases with depth.\n\nBelow are a few lines of data taken from a hypothetical P-I experiment. The data are for five replicate experiments with the same light intensities (independent variable), representing conditions typically encountered by kelp at latitudes between -36° and -23°S.\n\n\n::: {#tbl-library-minpack-lm-for .cell messages='false'}\n::: {.cell-output-display}\n\n\n|   | Replicate| Light (μmol photons m⁻² s⁻¹)| Photosynthesis (mg C m⁻² h⁻¹)|\n|:--|---------:|----------------------------:|-----------------------------:|\n|3  |         1|                          100|                          4.59|\n|17 |         2|                          200|                          8.83|\n|53 |         5|                          200|                          8.05|\n|44 |         4|                          350|                         12.27|\n|35 |         3|                          500|                         12.57|\n|54 |         5|                          250|                          9.38|\n|34 |         3|                          450|                         11.90|\n|11 |         1|                          500|                         13.53|\n|27 |         3|                          100|                          4.20|\n\n\n:::\n:::\n\n\n\n::: {.cell messages='false'}\n\n:::\n\n\n\n::: {.cell messages='false'}\n\n:::\n\n\n\n::: {.cell messages='false'}\n::: {.cell-output-display}\n![Nonlinear regression Jassby and Platt (1976) model fitted to simulated P-I data for a hypothetical kelp.](L06-pigments_photosynthesis_files/figure-typst/fig-jassby-platt-1.svg){#fig-jassby-platt}\n:::\n:::\n\n\nAfter fitting the model to the data, we can determine the values for $P_{\\text{max}}$ and $\\alpha$ for each replicate and determine the average value across the five fits. The combined plot (@fig-jassby-platt) displays the observed data points for all replicates and the fitted curve from the first replicate.\n\nThe average model fit values of the estimated parameters across all replicates are as follows:\n\n- **$P_{\\text{max}}$:** 13.05 mg C m⁻² h⁻¹\n- **$\\alpha$:** 0.05 μmol photons m⁻² s⁻¹\n\n### Considering the light compensation point\n\nThe **light compensation point** ($I_c$) is the irradiance level at which the rate of photosynthesis equals the rate of respiration, resulting in a net photosynthetic rate of zero. Below this point, the organism consumes more energy (via respiration) than it produces through photosynthesis, leading to a net loss of energy. Estimating $I_c$ is important for determining the minimum light intensity required for the survival of photosynthetic organisms, after compensation for the effect of cellular respiration.\n\nIn the context of the **Jassby and Platt hyperbolic tangent model**, $I_c$ can be estimated by solving for the irradiance $I$ when the net photosynthetic rate $P(I)$ equals zero:\n\n$$\n0 = P_{\\text{max}} \\times \\tanh\\left(\\frac{\\alpha I_{\\text{LCP}}}{P_{\\text{max}}}\\right)\n$$\n\nSince $\\tanh(0) = 0$, the net photosynthetic rate is zero when $I = 0$. However, due to respiration, the net photosynthesis can be negative at zero light intensity. To account for respiration, we can modify the model to include **dark respiration rate** ($R$):\n\n$$\nP(I) = P_{\\text{max}} \\times \\tanh\\left(\\frac{\\alpha I}{P_{\\text{max}}}\\right) - R\n$$\n\nNow, $I_c$ is the irradiance at which $P(I) = 0$:\n\n$$\n0 = P_{\\text{max}} \\times \\tanh\\left(\\frac{\\alpha I_{\\text{LCP}}}{P_{\\text{max}}}\\right) - R\n$$\n\nWe can solve this equation numerically to find $I_{\\text{LCP}}$.\n\n\n::: {#tbl-set-seed .cell messages='false'}\n::: {.cell-output-display}\n\n\n|   | Replicate| Light (μmol photons m⁻² s⁻¹)| Photosynthesis (mg C m⁻² h⁻¹)|\n|:--|---------:|----------------------------:|-----------------------------:|\n|3  |         1|                          100|                          3.65|\n|37 |         4|                            0|                         -2.17|\n|5  |         1|                          200|                          6.98|\n|57 |         5|                          400|                          9.43|\n|54 |         5|                          250|                          7.41|\n|60 |         5|                          550|                         10.98|\n|33 |         3|                          400|                          9.66|\n|6  |         1|                          250|                          7.89|\n|49 |         5|                            0|                         -1.86|\n\n\n:::\n:::\n\n\n\n::: {.cell messages='false'}\n\n:::\n\n\n\n::: {.cell messages='false'}\n\n:::\n\n\n\n::: {.cell messages='false'}\n::: {.cell-output-display}\n![Nonlinear regression Jassby and Platt (1976) model fitted to simulated P-I data for a hypothetical kelp. This model includes the effect of the light compensation point.](L06-pigments_photosynthesis_files/figure-typst/fig-jassby-platt2-1.svg){#fig-jassby-platt2}\n:::\n:::\n\n\nThe model fit to the data is in @fig-jassby-platt2. The average model fit values of the estimated parameters across all replicates are as follows:\n\n- **$P_{\\text{max}}$:** 13.15 mg C m⁻² h⁻¹\n- **$\\alpha$:** 0.05 μmol photons m⁻² s⁻¹\n- **$I_c$:** 41.28 μmol photons m⁻² s⁻¹\n\n### Platt et al. (1980) model with photoinhibition\n\nLet us now look at the **Platt et al. (1980)** model, which incorporates photoinhibition into the photosynthesis-irradiance (P-I) relationship. This model extends the understanding of photosynthesis by accounting for the decrease in photosynthetic efficiency at high light intensities due to photoinhibition — a phenomenon where excessive light damages the photosynthetic apparatus, leading to reduced photosynthetic rates.\n\nThe model is expressed mathematically as:\n\n$$\nP(I) = P_{\\text{max}} \\left(1 - \\exp\\left(-\\frac{\\alpha I}{P_{\\text{max}}}\\right)\\right) \\exp\\left(-\\frac{\\beta I}{P_{\\text{max}}}\\right)\n$$\n\nWhere:\n\n- $P_{\\text{max}}$ is the maximum photosynthetic rate in the absence of photoinhibition.\n- $\\beta$ is the photoinhibition parameter (rate of decrease in photosynthesis at high light).\n- $\\exp$ denotes the exponential function.\n\nThis model combines the positive effect of light on photosynthesis at low irradiance with the negative effect of photoinhibition at high irradiance, providing a comprehensive description of the photosynthetic response across a wide range of light intensities.\n\n\n::: {#tbl-set-seed-2 .cell messages='false'}\n::: {.cell-output-display}\n\n\n|   | Replicate| Light (μmol photons m⁻² s⁻¹)| Photosynthesis (mg C m⁻² h⁻¹)|\n|:--|---------:|----------------------------:|-----------------------------:|\n|45 |         3|                         1000|                         10.05|\n|76 |         5|                          700|                          9.13|\n|34 |         2|                         1600|                         10.16|\n|52 |         4|                            0|                         -2.00|\n|1  |         1|                            0|                         -0.86|\n|77 |         5|                          800|                          9.58|\n|10 |         1|                          900|                         11.26|\n|13 |         1|                         1200|                         11.43|\n|39 |         3|                          400|                          7.98|\n\n\n:::\n:::\n\n\n\n\n::: {.cell messages='false'}\n\n:::\n\n\n\n::: {.cell messages='false'}\n\n:::\n\n\n\n::: {.cell messages='false'}\n::: {.cell-output-display}\n![Nonlinear regression Platt et al. (1980) model fitted to simulated P-I data for a hypothetical kelp. This model includes the effect of photoinhibition.](L06-pigments_photosynthesis_files/figure-typst/fn-jassby-1.svg)\n:::\n:::\n\n\n## Effects of Environmental Stress\n\n![](images/BDC223_L06a_slide11.jpeg)\n\n$P_{max}$ represents the maximum photosynthetic capacity, which is influenced by many stresses, including thermal stress, nutrient stress, and light stress. Any of these can reduce a plant's capacity to sustain $P_{max}$, and a reduction in this parameter is often the first sign of environmental stress. Measuring these rates gives insights into how and when plants become stressed.\n\n![](images/BDC223_L06a_slide12.jpeg)\n\nHere are some indicative values (Slide reference):\n\n-   Intertidal environments: light saturation might occur at $400$–$600\\;\\mu\\mathrm{mol}\\,\\mathrm{m}^{-2}\\,\\mathrm{s}^{-1}$\n-   Sublittoral species (deeper): saturated at $150$–$250\\;\\mu\\mathrm{mol}\\,\\mathrm{m}^{-2}\\,\\mathrm{s}^{-1}$\n-   As depth increases, saturation occurs at progressively lower irradiances.\n-   Some deep-water plants can become photoinhibited at what would seem to us like relatively dim light.\n\nThese values—$I_C$, $I_K$, $P_{max}$, $\\alpha$—vary among species, being determined both by environmental adaptation and genetic heritage, and thus serve as good indicators of a plant's typical habitat and stress response.\n\nWhat we saw above is a standard textbook interpretation and formulation of a PI-curve. However, there are several mathematical models that can be used to describe the PI-curve. We will look at two of the most commonly used models: the hyperbolic tangent model by Jassby and Platt (1976) and the Platt et al. (1980) model, which includes photoinhibition.\n\n## Absorption Spectrum Vs Action Spectrum\n\n![](images/BDC223_L06a_slide13.jpeg)\n\nBefore moving on, it is critical to distinguish the absorption spectrum from the action spectrum.\n\n-   **Absorption spectrum**: Measures the amount of light absorbed by all pigments at every wavelength — essentially, how much light is not reflected or transmitted.\n-   **Action spectrum**: For each wavelength, measures the biological effect — oxygen evolution rate — that results from absorption.\n\n![](images/BDC223_L06a_slide14.jpeg)\n\nTypically, the action and absorption spectra match well, but not perfectly. For instance, between about $450$ and $500$ nm, there is a mismatch. This occurs because, beyond the optimal absorption peak of chlorophyll-*a*, carotenoids start absorbing light. While they can capture light within this region, they are less efficient at passing the energy to chlorophyll-*a*, resulting in a lower action than absorption value.\n\nThis demonstrates that the ability of accessory pigments to pass energy to chlorophyll-*a* is not perfectly efficient; some energy is lost in the process. Nonetheless, the presence of carotenoids extends the range in which photosynthesis can be driven by chlorophyll-*a*.\n\nIn summary, accessory pigments are essential in harvesting a broader range of light and making photosynthesis effective under varied light environments, even if energy transfer from accessory to primary pigments is not perfectly efficient.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}