{
  "hash": "9fad665d9f2fd671a358b6305d2b13c0",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"13. Multiple Regression and Model Specification\"\nsubtitle: \"From Biological Hypotheses to Statistical Models\"\nauthor: \"A. J. Smit\"\ndate: last-modified\ndate-format: \"YYYY/MM/DD\"\nreference-location: margin\n---\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n::: {.callout-note appearance=\"simple\"}\n## In This Chapter\n\n-   why simple regression is often not enough;\n-   how a multiple regression extends the simple linear model;\n-   why model specification is part of the scientific argument;\n-   how to think about omitted variables, proxies, and categorical predictors;\n-   how dummy-variable coding works in practice for real bioregions;\n-   how to fit and interpret a worked multiple regression example;\n-   how interactions and contrasts fit into the broader multiple-regression workflow.\n:::\n\n::: {.callout-important appearance=\"simple\"}\n## Tasks to Complete in This Chapter\n\n-   None\n:::\n\n# Introduction\n\nIn [Chapter 11](11-simple-linear-regression.qmd) we saw how to model the relationship between two variables using simple linear regression. However, in ecosystems the relationship between the response variable and the explanatory variables is more complex and in many cases cannot be adequately captured by a single driver. In such cases, multiple linear regression is used to model the relationship between the response variable and multiple explanatory variables.\n\nBiological systems are rarely driven by one variable alone. A response such as growth, abundance, diversity, or disease prevalence usually reflects the combined influence of several environmental, physiological, or experimental factors. Multiple regression is therefore the natural extension of simple regression to a more realistic ecological setting.\n\nBut adding more predictors creates a much more demanding scientific problem: **which predictors belong in the model, and why?** This chapter therefore combines two topics that should not be separated:\n\n1. multiple regression as a modelling framework; and\n2. model specification as the translation of biological ideas into statistical structure.\n\n# Key Concepts\n\nThe chapter turns on the following ideas.\n\n-   **Multiple regression** models a response using several predictors at once.\n-   **Holding other predictors constant** is what gives partial coefficients their meaning.\n-   **Model specification** translates biological reasoning into a statistical formula.\n-   **Omitted variables, poor functional form, and unjustified interactions** can distort inference.\n-   **Predictor choice** should be theory-driven rather than data-convenience driven.\n-   **Categorical predictors** are part of the same linear-model family and can be handled naturally in multiple regression.\n\n# Nature of the Data and Assumptions\n\nThe same broad assumptions that apply in simple linear regression apply here too, but now in a multivariable setting.\n\n-   **Response variable** The response should usually be continuous.\n-   **Predictors** Predictor variables are often continuous, but they may also be categorical.\n-   **Independence** The observations must be independent.\n-   **Approximate linearity** The response should relate approximately linearly to each predictor on the scale used in the model.\n-   **Residual assumptions** Residuals should be approximately normal with roughly constant variance.\n-   **Limited multicollinearity** Predictors should not be so strongly overlapping that their coefficients become unstable or uninterpretable.\n\nThe additional difficulty in multiple regression is that the model must be judged as a fitted statistical object *and* also as a biological specification. Even if the residual assumptions are acceptable, the model can still be weak because the variables are badly chosen or badly motivated. We return to the interpretive problems created by multicollinearity, confounding, and measurement error in [Chapter 15](15-collinearity-confounding-measurement-error.qmd).\n\n# The Core Equation\n\nThe general multiple-regression model can be written as:\n\n$$Y_i = \\alpha + \\beta_1 X_{1i} + \\beta_2 X_{2i} + \\cdots + \\beta_p X_{pi} + \\epsilon_i$$ {#eq-mlr}\n\nIn @eq-mlr, each $\\beta_j$ is a partial slope. That means each coefficient is interpreted while holding the other predictors in the model constant. This is the main mathematical difference from simple linear regression and the reason multiple-regression coefficients require more careful biological interpretation.\n\n# Outliers\n\nAs in simple regression, outliers can have strong effects on coefficient estimation, standard errors, and interpretation. In multiple regression, however, unusual observations may be unusual in multivariate space even when they do not look extreme on any single predictor alone. So, diagnostic plots and leverage measures become especially important once we fit the model.\n\n# R Function\n\nThe `lm()` function in R is used to fit a multiple linear regression model. The syntax is similar to that of the `lm()` function used for simple linear regression, but now with several predictor variables.\n\nThe function takes the basic form:\n\n```r\nlm(formula, data)\n```\n\nFor a model with only continuous predictors:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlm(response ~ predictor1 + predictor2 + predictor3,\n   data = dataset)\n```\n:::\n\n\nInteraction effects are implemented by including the product of two variables in the formula:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlm(response ~ predictor1 * predictor2, data = dataset)\n```\n:::\n\n\nWhen we have both continuous and categorical predictors, the formula is simply extended:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlm(response ~ continuous_predictor1 + continuous_predictor2 +\n     factor(categorical_predictor),\n   data = dataset)\n```\n:::\n\n\nR automatically handles the dummy-variable coding of factors. This is one reason multiple regression and ANOVA are so closely connected.\n\n# Why Model Specification Matters\n\nIn simple regression, the modelling decision is often obvious: one response, one predictor. In multiple regression, the structure of the model becomes part of the argument. The important questions are:\n\n-   Which variables represent the hypothesised process?\n-   Which variables are potential confounders that must be controlled?\n-   Which variables are only proxies for a harder-to-measure mechanism?\n-   Should the relationship be linear, transformed, or nonlinear?\n-   Does the effect of one predictor depend on another?\n\nModel specification therefore comes before model fitting. If the biological logic is weak, the fitted model is likely to be weak as well. The practical consequences of confounders, proxies, and measurement error are developed in much more detail in [Chapter 15](15-collinearity-confounding-measurement-error.qmd).\n\n# Example 1: A Climate Model for the East Coast Transition Zone\n\nThe main worked example in this chapter uses the seaweed data produced in the analysis by @smit2017seaweeds. The same dataset is used repeatedly in `BCB_Stats`, and it is well suited to this chapter because it contains:\n\n-   a continuous response variable, the mean Sørensen dissimilarity `Y`;\n-   several continuous climatological predictors;\n-   and a categorical predictor, the bioregional classification `bio`.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsw <- read.csv(\"../../data/BCB743/seaweed/spp_df2.csv\")\nrbind(head(sw, 3), tail(sw, 3))[,-1]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR>        dist  bio    augMean   febRange      febSD     augSD    annMean\nR> 1     0.000  BMP 0.00000000 0.00000000 0.00000000 0.0000000 0.00000000\nR> 2    51.138  BMP 0.05741369 0.09884404 0.16295271 0.3132800 0.01501846\nR> 3   104.443  BMP 0.15043904 0.34887754 0.09934163 0.4188239 0.02602247\nR> 968 102.649 ECTZ 0.41496099 0.11330069 0.24304493 0.7538546 0.52278161\nR> 969  49.912 ECTZ 0.17194242 0.05756093 0.18196664 0.3604341 0.24445006\nR> 970   0.000 ECTZ 0.00000000 0.00000000 0.00000000 0.0000000 0.00000000\nR>               Y        Y1          Y2\nR> 1   0.000000000 0.0000000 0.000000000\nR> 2   0.003610108 0.0000000 0.003610108\nR> 3   0.003610108 0.0000000 0.003610108\nR> 968 0.198728140 0.1948882 0.003839961\nR> 969 0.069337442 0.0443038 0.025033645\nR> 970 0.000000000 0.0000000 0.000000000\n```\n\n\n:::\n:::\n\n\nWe begin by focusing on the East Coast Transition Zone (`ECTZ`) and asking which combination of climate variables best explains variation in `Y`.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsw_ectz <- sw |>\n  filter(bio == \"ECTZ\")\n\nsw_sub1 <- sw_ectz[, c(\"Y\", \"augMean\", \"febRange\", \"febSD\", \"augSD\", \"annMean\")]\n```\n:::\n\n\n## Do an Exploratory Data Analysis (EDA)\n\nWe first inspect the scale and range of the variables in the subset we intend to model.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(sw_sub1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR>        Y              augMean          febRange          febSD       \nR>  Min.   :0.00000   Min.   :0.0000   Min.   :0.0000   Min.   :0.0000  \nR>  1st Qu.:0.09615   1st Qu.:0.1817   1st Qu.:0.1866   1st Qu.:0.1820  \nR>  Median :0.22779   Median :0.4686   Median :0.7531   Median :0.6256  \nR>  Mean   :0.24393   Mean   :0.5313   Mean   :0.8329   Mean   :0.7209  \nR>  3rd Qu.:0.35690   3rd Qu.:0.7927   3rd Qu.:1.3896   3rd Qu.:1.2072  \nR>  Max.   :0.63754   Max.   :1.7508   Max.   :2.2704   Max.   :2.1249  \nR>      augSD           annMean      \nR>  Min.   :0.0000   Min.   :0.0000  \nR>  1st Qu.:0.4178   1st Qu.:0.1874  \nR>  Median :1.0454   Median :0.5228  \nR>  Mean   :1.3207   Mean   :0.5722  \nR>  3rd Qu.:2.0924   3rd Qu.:0.8085  \nR>  Max.   :4.5267   Max.   :1.8941\n```\n\n\n:::\n:::\n\n\nBefore fitting a multiple regression, it is also useful to look at each predictor individually against the response because it provides intuition about the data structure before we begin combining effects.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npredictors <- c(\"augMean\", \"febRange\", \"febSD\", \"augSD\", \"annMean\")\n\nmodels <- map(predictors, ~ lm(as.formula(paste(\"Y ~\", .x)),\n                               data = sw_ectz))\n\nplts1 <- map(predictors, function(predictor) {\n  ggplot(sw_ectz, aes(x = .data[[predictor]], y = Y)) +\n    geom_point(shape = 1, colour = \"dodgerblue4\") +\n    geom_smooth(method = \"lm\", col = \"magenta\", fill = \"pink\") +\n    labs(title = paste(\"Y vs\", predictor),\n         x = predictor,\n         y = \"Y\") +\n    theme_grey()\n})\n\nggpubr::ggarrange(plotlist = plts1, ncol = 2,\n                  nrow = 3, labels = \"AUTO\")\n```\n\n::: {.cell-output-display}\n![Individual simple linear regressions fitted to the variables `augMean`, `febRange`, `febSD`, `augSD`, and `annMean` as predictors of the seaweed species composition as measured by the Sørensen dissimilarity, `Y`.](13-multiple-regression-and-model-specification_files/figure-html/fig-seaweed-slr-1.svg){#fig-seaweed-slr fig-align='center' width=3000}\n:::\n:::\n\n\nThe individual plots show that each predictor appears to relate positively and approximately linearly to the response when considered alone. But those one-predictor views do not tell us how the predictors behave once they are considered together, and they do not tell us whether some predictors overlap so strongly that their coefficients become unstable.\n\n## State the Hypotheses\n\nThe null hypothesis for the overall model is that there is no significant relationship between the response `Y` and any of the entered climatological variables, implying that the coefficients for all predictors are equal to zero:\n\n$$H_{0}: \\beta_1 = \\beta_2 = \\beta_3 = \\beta_4 = \\beta_5 = 0$$\n\nThe alternative is that at least one coefficient differs from zero:\n\n$$H_{a}: \\exists \\, \\beta_i \\ne 0 \\text{ for at least one } i$$\n\nAt the main-effects level, each predictor has its own hypothesis:\n\n$$H_{0}: \\beta_i = 0$$\n$$H_{a}: \\beta_i \\ne 0$$\n\nHowever, as soon as several predictors are included in the model, each coefficient becomes a **partial** effect. Its interpretation depends on the presence of the others.\n\n## Fit the Initial Model\n\nWe first fit a full model containing the five climate predictors, and a null model containing only the intercept.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfull_mod1 <- lm(Y ~ augMean + febRange + febSD + augSD + annMean,\n                data = sw_sub1)\nnull_mod1 <- lm(Y ~ 1, data = sw_sub1)\n\nsummary(full_mod1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR> \nR> Call:\nR> lm(formula = Y ~ augMean + febRange + febSD + augSD + annMean, \nR>     data = sw_sub1)\nR> \nR> Residuals:\nR>       Min        1Q    Median        3Q       Max \nR> -0.131229 -0.042352 -0.003415  0.038601  0.144128 \nR> \nR> Coefficients:\nR>              Estimate Std. Error t value Pr(>|t|)    \nR> (Intercept)  0.044886   0.006306   7.118 9.04e-12 ***\nR> augMean     -0.079925   0.042630  -1.875 0.061841 .  \nR> febRange     0.112913   0.015949   7.080 1.14e-11 ***\nR> febSD       -0.057174   0.016554  -3.454 0.000637 ***\nR> augSD        0.003024   0.004886   0.619 0.536421    \nR> annMean      0.322776   0.041615   7.756 1.59e-13 ***\nR> ---\nR> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\nR> \nR> Residual standard error: 0.05713 on 283 degrees of freedom\nR> Multiple R-squared:  0.8804,\tAdjusted R-squared:  0.8782 \nR> F-statistic: 416.5 on 5 and 283 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nThe full model fits strongly, but the coefficient table already hints at a practical problem: some variables that looked useful on their own are no longer clearly interpretable once the others are included. This is a common sign of multicollinearity.\n\n## Check for Multicollinearity\n\nSome of the predictors may be highly correlated with each other, and this can make the model less precise and harder to interpret because the coefficients' standard errors become inflated. A formal way to detect multicollinearity is to calculate the variance inflation factor (VIF) for each predictor.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nvif(full_mod1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR>   augMean  febRange     febSD     augSD   annMean \nR> 27.947767 10.806635  8.765732  2.497739 31.061900\n```\n\n\n:::\n:::\n\n\nThe VIF values show that some predictors overlap too strongly for comfortable interpretation. We therefore simplify the candidate set before asking which predictors belong in the final model.\n\nThis is a useful practical response to collinearity, but it is not the whole conceptual story. [Chapter 15](15-collinearity-confounding-measurement-error.qmd) explains why overlapping predictors create interpretive instability, how that differs from confounding, and why measurement error can produce similar practical difficulties.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nthreshold <- 10\nvif_mod <- full_mod1\nsw_vif <- sw_sub1\n\nwhile (TRUE) {\n  vif_values <- vif(vif_mod)\n  max_vif <- max(vif_values)\n\n  if (max_vif > threshold) {\n    high_vif_var <- names(which.max(vif_values))\n    sw_vif <- sw_vif[, !(names(sw_vif) %in% high_vif_var)]\n    vif_mod <- lm(Y ~ ., data = sw_vif)\n  } else {\n    break\n  }\n}\n\nsummary(vif_mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR> \nR> Call:\nR> lm(formula = Y ~ ., data = sw_vif)\nR> \nR> Residuals:\nR>       Min        1Q    Median        3Q       Max \nR> -0.153994 -0.049229 -0.006086  0.045947  0.148579 \nR> \nR> Coefficients:\nR>             Estimate Std. Error t value Pr(>|t|)    \nR> (Intercept) 0.028365   0.007020   4.040 6.87e-05 ***\nR> augMean     0.283335   0.011131  25.455  < 2e-16 ***\nR> febSD       0.049639   0.008370   5.930 8.73e-09 ***\nR> augSD       0.022150   0.004503   4.919 1.47e-06 ***\nR> ---\nR> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\nR> \nR> Residual standard error: 0.06609 on 285 degrees of freedom\nR> Multiple R-squared:  0.8387,\tAdjusted R-squared:  0.837 \nR> F-statistic: 494.1 on 3 and 285 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\nvif(vif_mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR>  augMean    febSD    augSD \nR> 1.423601 1.674397 1.585055\n```\n\n\n:::\n:::\n\n\nThis process leaves a much more interpretable candidate model. The retained predictors are `augMean`, `febSD`, and `augSD`, and the VIF values are now comfortably low.\n\nRegularisation techniques such as ridge regression, lasso regression, or elastic net can also be used to deal with multicollinearity. These are discussed later in [Chapter 24](24-regularisation.qmd).\n\n## Fit the Selected Model\n\nIt may be that not all variables retained after the VIF screen are needed to explain the response. We can therefore use forward selection to identify the most parsimonious model within this reduced candidate set.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmod1 <- stepAIC(\n  lm(Y ~ 1, data = sw_vif),\n  scope = list(lower = lm(Y ~ 1, data = sw_vif), upper = vif_mod),\n  direction = \"forward\",\n  trace = FALSE\n)\n\nformula(mod1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR> Y ~ augMean + febSD + augSD\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(mod1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR> \nR> Call:\nR> lm(formula = Y ~ augMean + febSD + augSD, data = sw_vif)\nR> \nR> Residuals:\nR>       Min        1Q    Median        3Q       Max \nR> -0.153994 -0.049229 -0.006086  0.045947  0.148579 \nR> \nR> Coefficients:\nR>             Estimate Std. Error t value Pr(>|t|)    \nR> (Intercept) 0.028365   0.007020   4.040 6.87e-05 ***\nR> augMean     0.283335   0.011131  25.455  < 2e-16 ***\nR> febSD       0.049639   0.008370   5.930 8.73e-09 ***\nR> augSD       0.022150   0.004503   4.919 1.47e-06 ***\nR> ---\nR> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\nR> \nR> Residual standard error: 0.06609 on 285 degrees of freedom\nR> Multiple R-squared:  0.8387,\tAdjusted R-squared:  0.837 \nR> F-statistic: 494.1 on 3 and 285 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\nanova(mod1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR> Analysis of Variance Table\nR> \nR> Response: Y\nR>            Df Sum Sq Mean Sq  F value    Pr(>F)    \nR> augMean     1 6.0084  6.0084 1375.660 < 2.2e-16 ***\nR> febSD       1 0.3604  0.3604   82.507 < 2.2e-16 ***\nR> augSD       1 0.1057  0.1057   24.196 1.473e-06 ***\nR> Residuals 285 1.2448  0.0044                       \nR> ---\nR> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nThe selected model is:\n\n$$\nY = \\alpha + \\beta_1 \\text{augMean} + \\beta_2 \\text{febSD} + \\beta_3 \\text{augSD} + \\epsilon\n$$\n\nThis is a useful teaching result because it shows that model building is not simply about keeping every plausible variable. It is about arriving at a model that is statistically stable and biologically interpretable.\n\n## Test the Assumptions / Check Diagnostics\n\nBefore interpreting the model in earnest, we must check whether its assumptions are adequate. Added-variable plots are useful because they show the relationship between the response and each predictor while accounting for the effect of the other predictors.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\navPlots(mod1, col = \"dodgerblue4\", col.lines = \"magenta\")\n```\n\n::: {.cell-output-display}\n![Partial regression plots for `mod1` with the selected variables `augMean`, `febSD`, and `augSD`.](13-multiple-regression-and-model-specification_files/figure-html/fig-mod1-partial-1.svg){#fig-mod1-partial fig-align='center' width=2400}\n:::\n:::\n\n\nThe added-variable plot for `augMean` shows a particularly strong and tight partial relationship with the response. The `febSD` and `augSD` plots show weaker effects with more scatter, but both still contribute.\n\nWe can also look at standard diagnostic plots for the model as a whole.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nautoplot(mod1, shape = 21, colour = \"dodgerblue4\",\n         smooth.colour = \"magenta\") +\n  theme_grey()\n```\n\n::: {.cell-output-display}\n![Diagnostic plots to assess the fit of the final multiple linear regression model, `mod1`.](13-multiple-regression-and-model-specification_files/figure-html/fig-mod1-diagnostics-1.svg){#fig-mod1-diagnostics fig-align='center' width=2400}\n:::\n:::\n\n\nThe model appears broadly acceptable. There may be mild curvature or slight heteroscedasticity, but there is no glaring red flag severe enough to invalidate interpretation. As always, adequacy is a matter of judgement, not perfection.\n\nComponent-plus-residual plots provide another useful perspective because they show whether the relationship between the response and each predictor appears reasonably linear in the fitted model.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncrPlots(mod1, col = \"dodgerblue4\", col.lines = \"magenta\")\n```\n\n::: {.cell-output-display}\n![Component plus residual diagnostic plots to assess the fit of the final multiple linear regression model, `mod1`.](13-multiple-regression-and-model-specification_files/figure-html/fig-mod1-crplots-1.svg){#fig-mod1-crplots fig-align='center' width=2400}\n:::\n:::\n\n\n## Interpret the Results\n\nThe fitted model shows that `augMean`, `febSD`, and `augSD` are all positively related to Sørensen dissimilarity in the East Coast Transition Zone once they are considered together. The strongest partial effect is associated with `augMean`, while `febSD` and `augSD` make smaller but still clearly positive contributions.\n\nEach slope in a multiple regression must be read conditionally: it gives the expected change in the response for a one-unit increase in that predictor **while the other predictors are held constant**. That conditional interpretation is the strength of the model, but it is also where the dangers lie. If predictors overlap strongly, or if one predictor stands in for an omitted biological cause, the apparent partial effect can become difficult to interpret. [Chapter 15](15-collinearity-confounding-measurement-error.qmd) returns to that problem directly.\n\nThe model fit is strong: the adjusted $R^2$ is about 0.84, so the selected predictors explain a large proportion of the observed variation in `Y`. The overall model test provides very strong evidence that the model explains more variation than an intercept-only model ($p < 0.001$).\n\nThe ANOVA table is useful here because it shows how much variance each predictor adds sequentially to the model. But remember that this sequential interpretation depends on the order in which predictors are entered.\n\n## Reporting\n\n::: {.callout-note appearance=\"simple\"}\n## Write-Up\n\n**Methods**\n\nMultiple linear regression was used to model mean Sørensen dissimilarity in the East Coast Transition Zone as a function of candidate climate predictors. Collinearity among predictors was assessed before final interpretation, and overlapping predictors were removed to obtain a more stable final model.\n\n**Results**\n\nIn the East Coast Transition Zone, mean Sørensen dissimilarity was well explained by a multiple linear regression containing August mean temperature, February temperature variability, and August temperature variability (adjusted $R^2 = 0.84$; overall model $p < 0.001$). All three retained predictors had positive partial effects, with August mean temperature showing the strongest contribution ($\\beta = 0.283$), followed by February temperature variability ($\\beta = 0.050$) and August temperature variability ($\\beta = 0.022$). Predictors with problematic overlap were removed before final interpretation, so the reported coefficients represent comparatively stable partial relationships.\n\n**Discussion**\n\nThe main discussion point is that the model identifies a small set of comparatively stable climatic predictors, rather than treating every candidate variable as independently meaningful. This is why model specification and collinearity screening matter in multiple regression.\n:::\n\n# Example 2: Categorical Predictors and Interaction of Distance and Bioregion\n\nMultiple regression can include both continuous and categorical predictors. In R, this is done by entering the categorical variable as a factor. This matters because many ecological questions involve a mixture of environmental gradients and group structure.\n\nFor example:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlm(response ~ dist + factor(bio), data = df)\n```\n:::\n\n\nOnce categorical predictors are included, multiple regression and ANOVA become part of the same linear-model family. This is why the earlier ANOVA chapter and the present modelling chapters connect so naturally.\n\n## Dummy variable coding\n\nWhen a categorical variable is included in a regression model, R does not fit a separate coefficient for every level plus an intercept. That would be redundant. Instead, it uses **dummy variables** (also called **indicator variables**) to represent the levels of the factor.\n\nSuppose a categorical predictor `C` has three levels: `C1`, `C2`, and `C3`. If `C1` is used as the reference level (by default, `lm()` chooses the first alpha-numeric factor), then only two dummy variables are needed:\n\n-   `D1 = 1` when the observation belongs to `C2`, and `0` otherwise;\n-   `D2 = 1` when the observation belongs to `C3`, and `0` otherwise.\n\nThe reference level `C1` is represented by `D1 = 0` and `D2 = 0`. In that case the model can be written as:\n\n$$\nY_i = \\alpha + \\beta_1 X_i + \\gamma_1 D_{i1} + \\gamma_2 D_{i2} + \\epsilon_i\n$$\n\nHere:\n\n-   $\\alpha$ is the intercept for the reference category;\n-   $\\beta_1$ is the slope of the continuous predictor `X` for the reference category;\n-   $\\gamma_1$ is the difference in intercept between `C2` and the reference category `C1`;\n-   $\\gamma_2$ is the difference in intercept between `C3` and the reference category `C1`.\n\nThis is the coding that `lm()` uses by default for factors. The first level of the factor is taken as the reference level unless you change it explicitly with `relevel()`. The practical implication is that when you see coefficients such as `bioBMP` or `bioECTZ`, they do not represent absolute means for those groups. They represent differences from the reference bioregion, holding the continuous predictors constant.\n\nIf an interaction between a continuous predictor and a factor is added, the same reasoning extends to the slopes. The main slope belongs to the reference level, and the interaction terms show how the slope changes in the other levels relative to that reference. You need to understand this to interpret the `dist * bio` example below.\n\n## What the coding looks like in practice\n\nThe abstract notation above is necessary, but it becomes much easier once we look at the actual coding used for the seaweed bioregions. We first create one row for each bioregion and then inspect the model matrix that `lm()` would construct internally.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbio_demo <- tibble(\n  bio = factor(c(\"AMP\", \"B-ATZ\", \"BMP\", \"ECTZ\"),\n               levels = levels(factor(sw$bio)))\n)\n\nbio_model_matrix <- model.matrix(~ bio, data = bio_demo) |>\n  as.data.frame() |>\n  mutate(bio = bio_demo$bio) |>\n  relocate(bio)\n\nbio_model_matrix\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR>     bio (Intercept) bioB-ATZ bioBMP bioECTZ\nR> 1   AMP           1        0      0       0\nR> 2 B-ATZ           1        1      0       0\nR> 3   BMP           1        0      1       0\nR> 4  ECTZ           1        0      0       1\n```\n\n\n:::\n:::\n\n\n\n::: {#tbl-bio-demo .cell layout-align=\"center\" tbl-cap='How the seaweed bioregions are represented by default dummy coding when `AMP` is the reference level.'}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"groajsmhhg\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#groajsmhhg table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#groajsmhhg thead, #groajsmhhg tbody, #groajsmhhg tfoot, #groajsmhhg tr, #groajsmhhg td, #groajsmhhg th {\n  border-style: none;\n}\n\n#groajsmhhg p {\n  margin: 0;\n  padding: 0;\n}\n\n#groajsmhhg .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#groajsmhhg .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#groajsmhhg .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#groajsmhhg .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#groajsmhhg .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#groajsmhhg .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#groajsmhhg .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#groajsmhhg .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#groajsmhhg .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#groajsmhhg .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#groajsmhhg .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#groajsmhhg .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#groajsmhhg .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#groajsmhhg .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#groajsmhhg .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#groajsmhhg .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#groajsmhhg .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#groajsmhhg .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#groajsmhhg .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#groajsmhhg .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#groajsmhhg .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#groajsmhhg .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#groajsmhhg .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#groajsmhhg .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#groajsmhhg .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#groajsmhhg .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#groajsmhhg .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#groajsmhhg .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#groajsmhhg .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#groajsmhhg .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#groajsmhhg .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#groajsmhhg .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#groajsmhhg .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#groajsmhhg .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#groajsmhhg .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#groajsmhhg .gt_left {\n  text-align: left;\n}\n\n#groajsmhhg .gt_center {\n  text-align: center;\n}\n\n#groajsmhhg .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#groajsmhhg .gt_font_normal {\n  font-weight: normal;\n}\n\n#groajsmhhg .gt_font_bold {\n  font-weight: bold;\n}\n\n#groajsmhhg .gt_font_italic {\n  font-style: italic;\n}\n\n#groajsmhhg .gt_super {\n  font-size: 65%;\n}\n\n#groajsmhhg .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#groajsmhhg .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#groajsmhhg .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#groajsmhhg .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#groajsmhhg .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#groajsmhhg .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#groajsmhhg .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#groajsmhhg .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#groajsmhhg div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"bio\">bio</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"a(Intercept)\">(Intercept)</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"bioB-ATZ\">bioB-ATZ</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"bioBMP\">bioBMP</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"bioECTZ\">bioECTZ</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"bio\" class=\"gt_row gt_center\">AMP</td>\n<td headers=\"(Intercept)\" class=\"gt_row gt_right\">1</td>\n<td headers=\"bioB-ATZ\" class=\"gt_row gt_right\">0</td>\n<td headers=\"bioBMP\" class=\"gt_row gt_right\">0</td>\n<td headers=\"bioECTZ\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"bio\" class=\"gt_row gt_center\">B-ATZ</td>\n<td headers=\"(Intercept)\" class=\"gt_row gt_right\">1</td>\n<td headers=\"bioB-ATZ\" class=\"gt_row gt_right\">1</td>\n<td headers=\"bioBMP\" class=\"gt_row gt_right\">0</td>\n<td headers=\"bioECTZ\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"bio\" class=\"gt_row gt_center\">BMP</td>\n<td headers=\"(Intercept)\" class=\"gt_row gt_right\">1</td>\n<td headers=\"bioB-ATZ\" class=\"gt_row gt_right\">0</td>\n<td headers=\"bioBMP\" class=\"gt_row gt_right\">1</td>\n<td headers=\"bioECTZ\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"bio\" class=\"gt_row gt_center\">ECTZ</td>\n<td headers=\"(Intercept)\" class=\"gt_row gt_right\">1</td>\n<td headers=\"bioB-ATZ\" class=\"gt_row gt_right\">0</td>\n<td headers=\"bioBMP\" class=\"gt_row gt_right\">0</td>\n<td headers=\"bioECTZ\" class=\"gt_row gt_right\">1</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbio_model_matrix |>\n  pivot_longer(cols = -bio, names_to = \"term\", values_to = \"value\") |>\n  ggplot(aes(x = term, y = bio, fill = factor(value))) +\n  geom_tile(colour = \"white\") +\n  scale_fill_manual(values = c(\"0\" = \"grey85\", \"1\" = \"steelblue4\")) +\n  labs(x = NULL, y = \"Bioregion\", fill = \"Value\") +\n  theme_grey()\n```\n\n::: {.cell-output-display}\n![Dummy-variable coding for the seaweed bioregions. `AMP` is the reference level, so its dummy columns are all zero.](13-multiple-regression-and-model-specification_files/figure-html/fig-bio-dummy-coding-1.svg){#fig-bio-dummy-coding fig-align='center' width=1200}\n:::\n:::\n\n\nThis picture makes the bookkeeping explicit. `AMP` is the reference level, so all the dummy columns are zero there. `B-ATZ`, `BMP`, and `ECTZ` each receive a `1` in their own indicator column, which is why their fitted coefficients must be read as differences from `AMP`, not as stand-alone group means.\n\nThe same logic carries directly into the interaction model. Once `dist * bio` is fitted, the coefficient for `dist` is the slope for `AMP`, and each `dist:bio...` term tells you how much the slope changes in the corresponding bioregion relative to `AMP`.\n\n## State the Biological Question\n\nThe seaweed dataset includes two additional variables that we have not yet considered closely:\n\n-   `dist`, the geographic distance between seaweed samples along the coast of South Africa; and\n-   `bio`, the bioregional classification of the samples.\n\nThese variables lend themselves to a few interesting questions:\n\n1. Is the Sørensen dissimilarity of the seaweed flora  related to geographic distance?\n2. Does the average Sørensen dissimilarity vary among bioregions?\n3. Is the effect of geographic distance on Sørensen dissimilarity different for each bioregion?\n\nThe third question requires that we consider possible interaction between the drivers, geographic distance and bioregion. So Example 2 extends the Chapter 13 workflow by combining continuous and categorical predictors in the same multiple-regression model.\n\n## State the model and hypotheses\n\nThe full model can be written as:\n\n$$\nY = \\alpha + \\beta_1 \\text{dist} + \\beta_2 \\text{bio} + \\beta_3 (\\text{dist} \\times \\text{bio}) + \\epsilon\n$$\n\nBecause `bio` has four levels, the fitted model is actually expanded internally into several dummy variables and their interactions. With `AMP` as the reference bioregion, the model is equivalent to:\n\n$$\n\\begin{aligned}\nY = \\alpha &+ \\beta_1 \\text{dist}\n+ \\beta_2 \\text{bio}_{\\text{B-ATZ}}\n+ \\beta_3 \\text{bio}_{\\text{BMP}}\n+ \\beta_4 \\text{bio}_{\\text{ECTZ}} \\\\\n&+ \\beta_5 (\\text{dist} \\times \\text{bio}_{\\text{B-ATZ}})\n+ \\beta_6 (\\text{dist} \\times \\text{bio}_{\\text{BMP}})\n+ \\beta_7 (\\text{dist} \\times \\text{bio}_{\\text{ECTZ}})\n+ \\epsilon\n\\end{aligned}\n$$\n\nIn words:\n\n-   the intercept and `dist` slope describe the reference bioregion;\n-   the `bio` coefficients describe how the intercept differs in the other bioregions relative to the reference;\n-   the interaction terms describe how the slope of `dist` differs in the other bioregions relative to the reference.\n\nThe overall null is that neither the main effects nor the interaction contributes to explaining the response. The interaction-specific null is that the effect of distance does not differ among bioregions.\n\n## Visualise the main effects\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\np1 <- ggplot(sw, aes(x = dist, y = Y)) +\n  geom_point(shape = 1, aes(colour = bio)) +\n  geom_smooth(method = \"lm\", se = TRUE,\n              colour = \"black\", fill = \"grey60\",\n              linewidth = 0.4) +\n  scale_colour_brewer(palette = \"Set1\") +\n  labs(x = \"Distance (km)\",\n       y = \"Sørensen Dissimilarity\") +\n  theme_grey()\n\np2 <- ggplot(sw, aes(x = bio, y = Y)) +\n  geom_boxplot(aes(colour = bio)) +\n  labs(x = \"Bioregional Classification\",\n       y = \"Sørensen Dissimilarity\") +\n  theme_grey() +\n  theme(legend.position = \"none\")\n\nggarrange(p1, p2, ncol = 2, labels = \"AUTO\")\n```\n\n::: {.cell-output-display}\n![Plot of main effects of A) distance along the coast and B) bioregional classification on the Sørensen dissimilarity index.](13-multiple-regression-and-model-specification_files/figure-html/fig-mod2-main-effects-1.svg){#fig-mod2-main-effects fig-align='center' width=2400}\n:::\n:::\n\n\nThe plot of `Y` against distance already suggests that one slope for all bioregions may be too simple. Colouring by bioregion reveals hidden structure. The boxplots also suggest that the average values of `Y` differ among bioregions.\n\n## Fit and assess nested models\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmod2a <- lm(Y ~ dist, data = sw)\nmod2 <- lm(Y ~ dist * bio, data = sw)\n\nanova(mod2a, mod2, test = \"F\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR> Analysis of Variance Table\nR> \nR> Model 1: Y ~ dist\nR> Model 2: Y ~ dist * bio\nR>   Res.Df    RSS Df Sum of Sq      F    Pr(>F)    \nR> 1    968 7.7388                                  \nR> 2    962 2.2507  6    5.4881 390.95 < 2.2e-16 ***\nR> ---\nR> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(mod2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR> \nR> Call:\nR> lm(formula = Y ~ dist * bio, data = sw)\nR> \nR> Residuals:\nR>       Min        1Q    Median        3Q       Max \nR> -0.112117 -0.030176 -0.004195  0.023698  0.233520 \nR> \nR> Coefficients:\nR>                 Estimate Std. Error t value Pr(>|t|)    \nR> (Intercept)    5.341e-03  4.177e-03   1.279   0.2013    \nR> dist           3.530e-04  1.140e-05  30.958  < 2e-16 ***\nR> bioB-ATZ      -6.140e-03  1.659e-02  -0.370   0.7114    \nR> bioBMP         3.820e-02  6.659e-03   5.737 1.29e-08 ***\nR> bioECTZ        1.629e-02  6.447e-03   2.527   0.0117 *  \nR> dist:bioB-ATZ  7.976e-04  1.875e-04   4.255 2.30e-05 ***\nR> dist:bioBMP   -1.285e-04  2.065e-05  -6.222 7.31e-10 ***\nR> dist:bioECTZ   4.213e-04  1.801e-05  23.392  < 2e-16 ***\nR> ---\nR> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\nR> \nR> Residual standard error: 0.04837 on 962 degrees of freedom\nR> Multiple R-squared:  0.8607,\tAdjusted R-squared:  0.8597 \nR> F-statistic: 849.2 on 7 and 962 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\nanova(mod2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR> Analysis of Variance Table\nR> \nR> Response: Y\nR>            Df Sum Sq Mean Sq F value    Pr(>F)    \nR> dist        1 8.4199  8.4199 3598.79 < 2.2e-16 ***\nR> bio         3 3.6232  1.2077  516.21 < 2.2e-16 ***\nR> dist:bio    3 1.8648  0.6216  265.69 < 2.2e-16 ***\nR> Residuals 962 2.2507  0.0023                      \nR> ---\nR> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nThe nested comparison shows that adding the bioregion effect and its interaction with distance improves the model strongly. The residual sum of squares decreases sharply, and the test indicates that the richer model provides a substantially better fit ($p < 0.001$).\n\nThis chapter does not explain the full interaction table, because that is the focus of [Chapter 14](14-interaction-effects.qmd). But the present example is important because it shows that interactions are not an exotic extra. They arise naturally once multiple regression allows both continuous and categorical predictors.\n\n## Interpret the interaction model\n\nThe coefficient table must be read with care because `bio` is represented through dummy-variable coding. The reference bioregion is absorbed into the intercept, and the remaining bioregion coefficients are interpreted relative to that reference. The interaction terms then tell us how the slope of `dist` differs among the other bioregions relative to the reference.\n\nSo, if `AMP` is the reference level, then:\n\n-   the coefficient for `dist` is the slope for `AMP`;\n-   the coefficient for `bioBMP` is the difference in intercept between `BMP` and `AMP` when `dist = 0`;\n-   the coefficient for `dist:bioBMP` is the amount by which the `BMP` slope differs from the `AMP` slope.\n\nThe same logic applies to the other bioregions. This is why the main effect of a factor and the interaction terms should never be interpreted in isolation. They are part of one combined coding system.\n\nThe broad interpretation is straightforward even if the bookkeeping is not:\n\n-   the effect of distance on `Y` is strong;\n-   the mean level of `Y` differs among bioregions;\n-   and, importantly, the slope of distance is not the same in all bioregions.\n\nThat last point is the biologically important one. Different bioregions show different rates at which Sørensen dissimilarity increases with distance.\n\n## Reporting\n\n::: {.callout-note appearance=\"simple\"}\n## Write-Up\n\n**Methods**\n\nNested linear models were used to test whether the relationship between Sørensen dissimilarity and geographic distance differed among bioregions. The interaction between distance and bioregion was assessed by comparing a single-slope model with a richer model containing both the bioregional main effect and the `dist × bio` interaction.\n\n**Results**\n\nSørensen dissimilarity increased strongly with geographic distance, but the rate of increase differed among bioregions in the fitted interaction model. Adding bioregional main effects and the `dist × bio` interaction improved model fit substantially relative to a single-slope distance model ($F = 390.95$, $p < 0.001$), and the interaction model explained a large proportion of the variation in dissimilarity ($R^2 = 0.86$; adjusted $R^2 = 0.86$). The baseline distance effect was strongly positive ($\\beta = 3.53 \\times 10^{-4}$, $p < 0.001$), but this slope was steeper in some bioregions and shallower in others, confirming that the relationship between geographic separation and compositional turnover is not spatially uniform along the South African coast.\n\n**Discussion**\n\nThe biologically important point is that compositional turnover is structured jointly by distance and bioregional context. The interaction is therefore biologically meaningful rather than a technical complication in the model formula.\n:::\n\n# Example 3: The Final Model\n\nWe can now expand the selected climate model to include `bio` as a predictor alongside `augMean`, `febSD`, and `augSD`. This creates a richer model in which the continuous climate effects may differ among bioregions.\n\n## Fit the richer model\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsw_sub2 <- sw |>\n  dplyr::select(Y, augMean, febSD, augSD, bio)\n\nfull_mod3 <- lm(Y ~ (augMean + febSD + augSD) * bio, data = sw_sub2)\nfull_mod3a <- lm(Y ~ augMean + febSD + augSD, data = sw_sub2)\nnull_mod3 <- lm(Y ~ 1, data = sw_sub2)\n\nanova(full_mod3, full_mod3a)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR> Analysis of Variance Table\nR> \nR> Model 1: Y ~ (augMean + febSD + augSD) * bio\nR> Model 2: Y ~ augMean + febSD + augSD\nR>   Res.Df    RSS  Df Sum of Sq      F    Pr(>F)    \nR> 1    954 3.5603                                   \nR> 2    966 5.6890 -12   -2.1288 47.535 < 2.2e-16 ***\nR> ---\nR> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\nAIC(full_mod3, full_mod3a)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR>            df       AIC\nR> full_mod3  17 -2652.498\nR> full_mod3a  5 -2221.852\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(full_mod3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR> \nR> Call:\nR> lm(formula = Y ~ (augMean + febSD + augSD) * bio, data = sw_sub2)\nR> \nR> Residuals:\nR>      Min       1Q   Median       3Q      Max \nR> -0.15399 -0.03841 -0.01475  0.03464  0.24051 \nR> \nR> Coefficients:\nR>                    Estimate Std. Error t value Pr(>|t|)    \nR> (Intercept)       0.0299094  0.0062756   4.766 2.17e-06 ***\nR> augMean           0.3441099  0.0158575  21.700  < 2e-16 ***\nR> febSD            -0.0006481  0.0027954  -0.232 0.816706    \nR> augSD            -0.0059012  0.0034011  -1.735 0.083044 .  \nR> bioB-ATZ         -0.0459611  0.0242519  -1.895 0.058374 .  \nR> bioBMP            0.0160756  0.0100749   1.596 0.110906    \nR> bioECTZ          -0.0015444  0.0090275  -0.171 0.864197    \nR> augMean:bioB-ATZ -0.0461775  0.0874044  -0.528 0.597400    \nR> augMean:bioBMP   -0.2406297  0.0211404 -11.382  < 2e-16 ***\nR> augMean:bioECTZ  -0.0607745  0.0189030  -3.215 0.001348 ** \nR> febSD:bioB-ATZ    0.0409425  0.0818927   0.500 0.617223    \nR> febSD:bioBMP      0.0056433  0.0150126   0.376 0.707070    \nR> febSD:bioECTZ     0.0502867  0.0082266   6.113 1.43e-09 ***\nR> augSD:bioB-ATZ    0.0655983  0.0371033   1.768 0.077382 .  \nR> augSD:bioBMP      0.0410220  0.0114706   3.576 0.000366 ***\nR> augSD:bioECTZ     0.0280513  0.0053752   5.219 2.21e-07 ***\nR> ---\nR> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\nR> \nR> Residual standard error: 0.06109 on 954 degrees of freedom\nR> Multiple R-squared:  0.7797,\tAdjusted R-squared:  0.7762 \nR> F-statistic: 225.1 on 15 and 954 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\nanova(full_mod3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR> Analysis of Variance Table\nR> \nR> Response: Y\nR>              Df Sum Sq Mean Sq  F value    Pr(>F)    \nR> augMean       1 9.9900  9.9900 2676.902 < 2.2e-16 ***\nR> febSD         1 0.0530  0.0530   14.208 0.0001737 ***\nR> augSD         1 0.4266  0.4266  114.308 < 2.2e-16 ***\nR> bio           3 0.8551  0.2850   76.374 < 2.2e-16 ***\nR> augMean:bio   3 0.7910  0.2637   70.647 < 2.2e-16 ***\nR> febSD:bio     3 0.3475  0.1158   31.034 < 2.2e-16 ***\nR> augSD:bio     3 0.1353  0.0451   12.085 9.097e-08 ***\nR> Residuals   954 3.5603  0.0037                       \nR> ---\nR> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nThe final interaction model is clearly better than the reduced additive model. The AIC is lower, and the nested comparison indicates that allowing the slopes to differ among bioregions improves fit strongly.\n\nThe model is now much more interesting and insightful than the one we began with. That does not necessarily make it better in every sense, but it may be better if the biological question really concerns whether the climate relationships differ among bioregions.\n\n## Interpret the more interesting model\n\nThe summary of `full_mod3` shows that:\n\n-   `augMean` remains a strong predictor of `Y`;\n-   several interaction terms are important, which means the climate-response relationships differ among bioregions;\n-   the overall model explains a substantial proportion of the variation in the response.\n\nSo, the outcome is that the relationship between the seaweed dissimilarity index and the selected climate variables is not spatially uniform, but that the influence of those variables changes among the bioregions. That is a much more insightful ecological statement than anything we could obtain from a single-predictor regression.\n\n## Reporting\n\n::: {.callout-note appearance=\"simple\"}\n## Write-Up\n\n**Methods**\n\nA more insightful interaction model was fitted to evaluate whether the relationships between Sørensen dissimilarity and the selected climate predictors differed among bioregions. The interaction-rich model was compared with the corresponding additive model using information criteria and nested model comparison.\n\n**Results**\n\nThe full interaction multiple regression explained a large proportion of the variation in mean Sørensen dissimilarity ($R^2 = 0.78$; adjusted $R^2 = 0.78$) and fit the data substantially better than the corresponding additive model (lower AIC; nested model comparison $F = 47.54$, $p < 0.001$). August mean temperature remained the dominant positive predictor in the reference bioregion ($\\beta = 0.344$, $p < 0.001$), but several significant interaction terms showed that the effects of August mean temperature, February temperature variability, and August temperature variability differed among bioregions. In particular, the slopes associated with `augMean` were weaker in `BMP` and `ECTZ` than in the reference bioregion, while positive interactions involving `febSD` and `augSD` indicated that the effect of short-term temperature variability was stronger in some bioregions than in others.\n\n**Discussion**\n\nThis final model with interactions supports the broader ecological interpretation that the climatic drivers of compositional turnover are not spatially uniform along the South African coast. In a manuscript, that would be the main discussion point rather than a long catalogue of coefficient values.\n:::\n\n# Alternative Categorical Variable Coding Schemes (Contrasts)\n\nThroughout the chapter, the categorical variables have been handled with the default dummy-variable coding. But alternative coding schemes are possible, and they change the way the coefficients are interpreted.\n\nThe following synthetic example shows a few different possibilities.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(123)\nn <- 100\nx <- rnorm(n)\ncat_var <- factor(sample(c(\"A\", \"B\", \"C\", \"D\"), n, replace = TRUE))\ny <- 2 * x + ifelse(cat_var == \"A\", 3,\n                    ifelse(cat_var == \"B\", 1,\n                           ifelse(cat_var == \"C\", -1, -3))) + rnorm(n)\n\ndata_contr <- data.frame(y, x, cat_var)\nhead(data_contr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR>            y           x cat_var\nR> 1  0.6667876 -0.56047565       B\nR> 2  1.3086873 -0.23017749       B\nR> 3  0.4496192  1.55870831       D\nR> 4  2.1326402  0.07050839       A\nR> 5 -2.8608771  0.12928774       D\nR> 6  0.1497346  1.71506499       D\n```\n\n\n:::\n:::\n\n\nWith default treatment coding, one level becomes the reference category:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncontrasts(data_contr$cat_var)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR>   B C D\nR> A 0 0 0\nR> B 1 0 0\nR> C 0 1 0\nR> D 0 0 1\n```\n\n\n:::\n:::\n\n\nThis means that the coefficient for each non-reference level is interpreted as the difference between that level and the reference level, holding the other predictors constant.\n\nYou can change the reference level:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndata_contr$cat_var <- relevel(data_contr$cat_var, ref = \"C\")\ncontrasts(data_contr$cat_var)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR>   A B D\nR> C 0 0 0\nR> A 1 0 0\nR> B 0 1 0\nR> D 0 0 1\n```\n\n\n:::\n:::\n\n\nOr use effect coding:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncontrasts(data_contr$cat_var) <- contr.sum(4)\ncontrasts(data_contr$cat_var)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR>   [,1] [,2] [,3]\nR> C    1    0    0\nR> A    0    1    0\nR> B    0    0    1\nR> D   -1   -1   -1\n```\n\n\n:::\n:::\n\n\nThe practical lesson is not that students must memorise every contrast scheme. It is that the interpretation of categorical coefficients depends on how the coding is done.\n\n# Summary\n\n-   Multiple regression extends simple regression to several predictors.\n-   Model specification is not a side issue; it is part of the scientific argument.\n-   The meaning of each coefficient depends on the other predictors included in the model.\n-   Multicollinearity can make a model statistically unstable and biologically difficult to interpret.\n-   Categorical predictors and interaction terms belong naturally within the multiple-regression framework.\n-   A useful multiple regression is one that is both statistically adequate and scientifically defensible.\n\nThis chapter now lays out the full modelling landscape: additive models, interactions, richer bioregional structures, and categorical coding. The next chapter returns to the interaction problem directly and develops it in more focused detail.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}