{
  "hash": "6d5efce57f5eb62f744d4b449bc09153",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"18: Generalised Linear Models (GLM)\"\nsubtitle: \"Task L\"\nformat:\n  html:\n    code-fold: true\n    code-summary: \"Show the answers\"\n---\n\n\n::: {.cell}\n\n:::\n\n\n## Practice Task\n\nWork through these exercises after reading the [Generalised Linear Models](../glm.qmd) chapter. They use two **vegan** datasets that suit GLMs naturally: the oribatid mite counts (`data(mite); data(mite.env)`) for Poisson-family models, and the Sibbo island bird incidences (`data(sipoo); data(sipoo.map)`) for a binomial model. Four exercises are hands-on and two are conceptual. A worked answer is given under each exercise; try it yourself before opening it.\n\n1. Choose a reasonably common species in `mite` and fit a **Poisson GLM** of its count on the `mite.env` predictors `SubsDens`, `WatrCont` and `Topo`. Report the coefficients on both the link and the response scale (exponentiate), and interpret the sign of each.\n\n::: {.callout-note collapse=\"true\"}\n## Show the answer\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nlibrary(tidyverse)\nlibrary(vegan)\nlibrary(MASS)\n\ndata(mite); data(mite.env)\nfocal <- names(which.max(colSums(mite)))      # the most abundant species\ndat <- mite.env\ndat$y <- mite[[focal]]\n\nm_pois <- glm(y ~ SubsDens + WatrCont + Topo, data = dat, family = poisson)\nsummary(m_pois)$coefficients\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 Estimate   Std. Error    z value     Pr(>|z|)\n(Intercept) -0.1412208705 0.1034926679 -1.3645495 1.723947e-01\nSubsDens    -0.0005566142 0.0020313081 -0.2740176 7.840711e-01\nWatrCont     0.0074239678 0.0001673936 44.3503581 0.000000e+00\nTopoHummock  0.3635814547 0.0579682728  6.2720767 3.562639e-10\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"false\"}\nexp(coef(m_pois))                              # multiplicative effect on the response (count) scale\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)    SubsDens    WatrCont TopoHummock \n  0.8682975   0.9994435   1.0074516   1.4384720 \n```\n\n\n:::\n:::\n\n\nThe fitted species is LCIL (the most abundant mite). On the **link** (log) scale the coefficients are additive; exponentiating moves them to the **response** (count) scale, where each becomes a multiplicative factor on the expected count. A positive log-coefficient (exponentiated value above 1) means the expected count rises with that predictor, a negative one (below 1) means it falls. For this mite the water-content term carries the strongest effect, consistent with moisture being the dominant gradient in this community.\n:::\n\n2. Check the model for **overdispersion** (compare the residual deviance to its degrees of freedom, or use `performance::check_overdispersion()`). If it is overdispersed, refit it as a **quasi-Poisson** and a **negative binomial** model (`MASS::glm.nb()`), and compare the standard errors and inferences with the Poisson fit.\n\n::: {.callout-note collapse=\"true\"}\n## Show the answer\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\ndisp <- sum(residuals(m_pois, \"pearson\")^2) / m_pois$df.residual\ndisp                                           # >> 1 indicates overdispersion\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 45.67041\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"false\"}\nm_qp <- glm(y ~ SubsDens + WatrCont + Topo, data = dat, family = quasipoisson)\nm_nb <- glm.nb(y ~ SubsDens + WatrCont + Topo, data = dat)\n\n# compare standard errors of the same coefficients across the three fits\nse <- function(m) summary(m)$coefficients[, \"Std. Error\"]\nround(cbind(poisson = se(m_pois), quasipoisson = se(m_qp), negbin = se(m_nb)), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            poisson quasipoisson negbin\n(Intercept)   0.103        0.699  0.772\nSubsDens      0.002        0.014  0.015\nWatrCont      0.000        0.001  0.001\nTopoHummock   0.058        0.392  0.380\n```\n\n\n:::\n:::\n\n\nThe dispersion statistic is **45.7** (far above 1), so the counts are strongly **overdispersed**: their variance greatly exceeds the Poisson assumption that variance equals the mean. The Poisson standard errors are therefore much too small, which makes predictors look more significant than they are. The quasi-Poisson and negative-binomial refits inflate the standard errors to reflect the extra variance (the negative binomial does so by estimating a dispersion parameter, here $\\theta$ = **0.55**), so several borderline \"significant\" Poisson terms become non-significant. The point estimates barely change; what changes, and what matters, is the honesty of the uncertainty.\n:::\n\n3. Using `sipoo`, compute each island's species **richness** and fit a Poisson (or negative binomial) GLM of richness on `log(area)` taken from `sipoo.map`. The slope on `log(area)` is the exponent $z$ of the species-area relationship $S = cA^{z}$; report it and comment on its magnitude relative to the typical range of $z \\approx 0.2$--$0.35$.\n\n::: {.callout-note collapse=\"true\"}\n## Show the answer\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\ndata(sipoo); data(sipoo.map)\nrich <- rowSums(sipoo)                                      # bird species per island\narea <- sipoo.map[rownames(sipoo), \"area\"]\n\nsar <- glm(rich ~ log(area), family = poisson)\ncoef(sar)[\"log(area)\"]                                     # the species-area exponent z\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nlog(area) \n0.4626734 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"false\"}\nggplot(tibble(area, rich), aes(area, rich)) +\n  geom_point() +\n  stat_smooth(method = \"glm\", method.args = list(family = poisson),\n              formula = y ~ log(x), se = TRUE) +\n  scale_x_log10() +\n  labs(x = \"Island area (log scale)\", y = \"Bird species richness\")\n```\n\n::: {.cell-output-display}\n![](Task_L_files/figure-html/task-l-q3-1.svg)\n:::\n:::\n\n\nWith a Poisson log link and `log(area)` as the predictor, the model is $\\log S = \\log c + z\\,\\log A$, so the slope is exactly the species-area exponent $z$ in $S = cA^{z}$. The estimated $z$ for the Sibbo islands is **0.46**, at or slightly above the upper end of the classic $0.2$--$0.35$ range, which is plausible for a true-island archipelago (isolated islands tend to have steeper species-area slopes than nested mainland samples). Richness rises with area, but with diminishing returns on the arithmetic scale, exactly the curvature the log link captures.\n:::\n\n4. Convert one moderately common `sipoo` bird species to presence/absence and fit a **logistic GLM** of its occurrence on `log(area)`. Report the odds ratio for a doubling of island area and the area at which the predicted probability of occurrence is 0.5.\n\n::: {.callout-note collapse=\"true\"}\n## Show the answer\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nprev <- colSums(sipoo)\nfb <- names(which.min(abs(prev - nrow(sipoo) / 2)))       # species closest to 50% prevalence\ndfb <- data.frame(pa = sipoo[[fb]], area = area)\n\nm_log <- glm(pa ~ log(area), data = dfb, family = binomial)\nb <- coef(m_log)\nc(species = fb,\n  OR_per_doubling = round(2^b[\"log(area)\"], 2),           # odds multiply by this per doubling of area\n  area_p50 = round(exp(-b[1] / b[\"log(area)\"]), 1))       # area where P(occurrence) = 0.5\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                  species OR_per_doubling.log(area)      area_p50.(Intercept) \n               \"Sylvcurr\"                    \"2.73\"                     \"9.2\" \n```\n\n\n:::\n:::\n\n\nThe fitted species is Sylvcurr. The logit model is $\\text{logit}(p) = \\beta_0 + \\beta_1\\log(\\text{area})$, so doubling the area multiplies the **odds** of occurrence by $2^{\\beta_1}$ = **2.73** (comfortably above 1, so larger islands are more likely to hold the species), and presence becomes more likely than absence ($p = 0.5$) above an island area of about **9.2** units. This is island biogeography in a single GLM: occurrence probability rises smoothly with island area along an S-shaped (logistic) curve.\n:::\n\n5. Explain why a Poisson or negative-binomial GLM is more appropriate than ordinary least-squares regression for count data, and what overdispersion means both statistically and ecologically.\n\n::: {.callout-note collapse=\"true\"}\n## Show the answer\n\nCounts are non-negative integers whose variance grows with their mean, and they are often concentrated near zero. Ordinary least squares assumes the opposite, namely a continuous response with constant-variance, normally distributed errors, so it can predict impossible negative counts, it gives wrong standard errors when the variance is tied to the mean, and its residuals are heteroscedastic by construction. A Poisson GLM models the log of the mean count with a distribution defined only on the non-negative integers and with the mean-variance link built in. **Overdispersion** is when the data vary even more than Poisson allows (variance > mean). Statistically it means the Poisson standard errors are too small and significance is overstated; ecologically it usually reflects unmodelled heterogeneity, namely clumping, patchiness, or omitted environmental drivers, so that individuals are not distributed independently. The negative binomial adds a parameter to absorb that extra variance and restore honest inference.\n:::\n\n6. Explain the role of the **link function** in a GLM (log for counts, logit for binary data). Take one fitted coefficient from Exercises 1--4 and interpret it on both the link scale and the back-transformed response scale.\n\n::: {.callout-note collapse=\"true\"}\n## Show the answer\n\nThe **link function** connects the linear predictor (a sum of $\\beta x$ terms that can take any real value) to the mean of a response that is constrained, so that the model can be linear and additive on the link scale while respecting the bounds of the data on the response scale. The **log** link keeps counts positive (the mean is $e^{\\eta}$, always > 0) and makes predictor effects multiplicative; the **logit** link keeps probabilities in $[0, 1]$ and makes effects multiplicative on the odds. Taking the water-content coefficient from the Poisson mite model in Exercise 1: on the **link** scale it is the change in log-expected-count per unit of water content (additive); back-transformed with `exp()` it is the **factor** by which the expected count is multiplied per unit increase in water content. The same coefficient, read on two scales, answers two questions: \"is the effect positive?\" (link scale) and \"by how much does the count change?\" (response scale).\n:::\n\n## Assessment Criteria\n\nThis Task is not formally assessed. It is built around four hands-on analyses (Exercises 1--4) and two short conceptual questions (Exercises 5--6); work through all six and bring your annotated Quarto document to class for discussion.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}