{
  "hash": "3d6732054691a0d0b56d76d533b3a777",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"8a: Principal Component Analysis (PCA)\"\nsubtitle: \"Task B\"\nformat:\n  html:\n    code-fold: true\n    code-summary: \"Show the answers\"\n---\n\n\n::: {.cell}\n\n:::\n\n\n## Practice Task\n\nWork through these exercises after reading the [Principal Component Analysis](../PCA.qmd) chapter, using the Doubs River environmental data. Four exercises are hands-on calculations and two are short conceptual questions. A worked answer is given under each exercise; try it yourself before opening it.\n\n1. Run a PCA on the Doubs **environmental** data (scaled); produce a biplot (scaling 2) and a screeplot, and report the variance explained by PC1 and PC2.\n\n::: {.callout-note collapse=\"true\"}\n## Show the answer\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nlibrary(tidyverse)\nlibrary(vegan)\n\nload(here::here(\n  \"data\",\n  \"BCB743\",\n  \"NEwR-2ed_code_data\",\n  \"NEwR2-Data\",\n  \"Doubs.RData\"\n))\n\npca_env <- rda(env, scale = TRUE) # correlation PCA (variables standardised)\n\nvar_expl <- round(100 * eigenvals(pca_env) / sum(eigenvals(pca_env)), 1)\nvar_expl[1:2] # variance explained by PC1 and PC2 (%)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n PC1  PC2 \n54.3 19.7 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"false\"}\nbiplot(pca_env, scaling = 2, main = \"Doubs environment, PCA scaling 2\")\n```\n\n::: {.cell-output-display}\n![](Task_B_files/figure-html/task-b-q1-1.svg)\n:::\n\n```{.r .cell-code  code-fold=\"false\"}\nscreeplot(pca_env, type = \"lines\", main = \"Doubs PCA screeplot\")\n```\n\n::: {.cell-output-display}\n![](Task_B_files/figure-html/task-b-q1-2.svg)\n:::\n:::\n\n\nA correlation PCA (`scale = TRUE`) is appropriate because the 11 variables are measured in different units. **PC1 explains 54.3% of the variance and PC2 19.7%, so the first two axes together capture 74%** --- a large fraction for an 11-variable table, and the screeplot shows the steep drop in eigenvalues after the first one or two axes. In the biplot the nutrient and load vectors (`pho`, `amm`, `nit`, `bod`) point one way and `ele`/`oxy` point the other, with the sites spread along PC1 from upstream to downstream: PC1 is the longitudinal river gradient re-expressed as a single composite axis.\n:::\n\n2. Replicate the PCA on the environmental data of two external datasets --- the [bird communities along the elevation gradient in Yushan Mountain, Taiwan](https://www.davidzeleny.net/anadat-r/doku.php/en:data:ybirds) and the [alpine plant communities in Aravo, France](https://www.davidzeleny.net/anadat-r/doku.php/en:data:aravo) --- each with a biplot, a screeplot, and the variance on the first two axes.\n\n::: {.callout-note collapse=\"true\"}\n## Show the answer\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# --- Yushan bird environmental data ---\nybirds_env <- read.table(\n  here::here(\"data\", \"BCB743\", \"ybirds_env.txt\"),\n  header = TRUE,\n  row.names = 1\n)\nybirds_env_num <- ybirds_env |> select(where(is.numeric)) # keep numeric predictors\n\npca_yb <- rda(ybirds_env_num, scale = TRUE)\nvar_yb <- round(100 * eigenvals(pca_yb) / sum(eigenvals(pca_yb)), 1)\nvar_yb[1:2] # variance explained by PC1 and PC2 (%), Yushan\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n PC1  PC2 \n52.7 18.5 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"false\"}\nbiplot(pca_yb, scaling = 2, main = \"Yushan environment, PCA scaling 2\")\n```\n\n::: {.cell-output-display}\n![](Task_B_files/figure-html/task-b-q2-1.svg)\n:::\n\n```{.r .cell-code  code-fold=\"false\"}\nscreeplot(pca_yb, bstick = TRUE, type = \"lines\", main = \"Yushan screeplot\")\n```\n\n::: {.cell-output-display}\n![](Task_B_files/figure-html/task-b-q2-2.svg)\n:::\n\n```{.r .cell-code  code-fold=\"false\"}\n# --- Aravo alpine plant environmental data (from the ade4 package) ---\ndata(aravo, package = \"ade4\")\naravo_env_num <- aravo$env |> select(where(is.numeric)) # Aspect, Slope, PhysD, Snow\n\npca_ar <- rda(aravo_env_num, scale = TRUE)\nvar_ar <- round(100 * eigenvals(pca_ar) / sum(eigenvals(pca_ar)), 1)\nvar_ar[1:2] # variance explained by PC1 and PC2 (%), Aravo\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n PC1  PC2 \n41.1 24.8 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"false\"}\nbiplot(pca_ar, scaling = 2, main = \"Aravo environment, PCA scaling 2\")\n```\n\n::: {.cell-output-display}\n![](Task_B_files/figure-html/task-b-q2-3.svg)\n:::\n\n```{.r .cell-code  code-fold=\"false\"}\nscreeplot(pca_ar, bstick = TRUE, type = \"lines\", main = \"Aravo screeplot\")\n```\n\n::: {.cell-output-display}\n![](Task_B_files/figure-html/task-b-q2-4.svg)\n:::\n:::\n\n\nThe Yushan environmental table is dominated by one axis, the **elevation** gradient: **PC1 explains 52.7% and PC2 18.5%**, with elevation (`ELE`), slope, and vegetation-structure variables loading on PC1 and the 50 stations ordering from low to high elevation.\n\nThe Aravo alpine data tell the same story on a smaller environmental table: **PC1 explains 41.1% and PC2 24.8%**, separating sites mainly by snowmelt timing (`Snow`) and physical disturbance (`PhysD`), the principal gradients structuring alpine plant communities. In both cases a single dominant physical gradient organises most of the multivariate structure, so the first two axes summarise the table efficiently.\n:::\n\n3. Add the **broken-stick** criterion to the Doubs PCA (for example `vegan::screeplot(..., bstick = TRUE)` or `BiodiversityR::PCAsignificance()`). How many axes should be retained?\n\n::: {.callout-note collapse=\"true\"}\n## Show the answer\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nscreeplot(\n  pca_env,\n  bstick = TRUE,\n  type = \"lines\",\n  main = \"Doubs PCA: eigenvalues vs broken-stick\"\n)\n```\n\n::: {.cell-output-display}\n![](Task_B_files/figure-html/task-b-q3-1.svg)\n:::\n:::\n\n\nThe broken-stick model is the variance an axis would capture if total variance were divided at random. An axis is worth interpreting only while its observed eigenvalue (the line/bars) exceeds the broken-stick expectation. For the Doubs environment that holds for the first one to two axes and no more, which matches the visual impression that essentially one dominant gradient, plus a weak second axis, carries the interpretable structure. Retaining further axes would be fitting noise.\n:::\n\n4. Overlay additional structure on the Doubs PCA: colour the sites by their upstream-downstream position, or fit a variable with `envfit()`, and interpret what the first axis represents.\n\n::: {.callout-note collapse=\"true\"}\n## Show the answer\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nsite_scores <- scores(pca_env, display = \"sites\", scaling = 2) |>\n  as.data.frame() |>\n  mutate(dfs = env$dfs) # distance from source = river position\n\nggplot(site_scores, aes(PC1, PC2, colour = dfs)) +\n  geom_point(size = 2) +\n  scale_colour_viridis_c(name = \"Distance\\nfrom source\") +\n  labs(title = \"Doubs sites in PCA space, coloured by river position\")\n```\n\n::: {.cell-output-display}\n![](Task_B_files/figure-html/task-b-q4-1.svg)\n:::\n\n```{.r .cell-code  code-fold=\"false\"}\n# fit the environmental variables and overlay the significant ones on the ordination\nef <- envfit(pca_env, env, permutations = 999)\nordiplot(\n  pca_env,\n  display = \"sites\",\n  type = \"text\",\n  scaling = 2,\n  main = \"Doubs PCA with envfit vectors\"\n)\nplot(ef, p.max = 0.05, col = \"blue\") # add significant variables as arrows\n```\n\n::: {.cell-output-display}\n![](Task_B_files/figure-html/task-b-q4-2.svg)\n:::\n\n```{.r .cell-code  code-fold=\"false\"}\nef\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n***VECTORS\n\n         PC1      PC2     r2 Pr(>r)    \ndfs  0.89739  0.44123 0.9029  0.001 ***\nele -0.86169 -0.50744 0.9040  0.001 ***\nslo -0.76272 -0.64673 0.3525  0.036 *  \ndis  0.82328  0.56763 0.8347  0.001 ***\npH  -0.13619  0.99068 0.1345  0.141    \nhar  0.83877  0.54449 0.7109  0.001 ***\npho  0.86941 -0.49410 0.9124  0.001 ***\nnit  0.99620 -0.08704 0.8209  0.001 ***\namm  0.82222 -0.56917 0.9234  0.001 ***\noxy -0.89008  0.45581 0.7384  0.001 ***\nbod  0.80593 -0.59201 0.8980  0.001 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\nPermutation: free\nNumber of permutations: 999\n```\n\n\n:::\n:::\n\n\nColouring the sites by distance from source shows a smooth progression along PC1 from headwater (dark) to lowland (light) sites. Fitting the environmental variables with `envfit()` and overlaying them on the ordination makes the same point with arrows: the significant vectors (distance from source, elevation, oxygen, and the nutrient and load variables) all align with PC1, and `dfs` in particular has a very high $r^2$ and a significant permutation $p$-value. This confirms quantitatively what the biplot suggested: the first principal component *is* the upstream-downstream position of the site, and every variable that loads on it does so because it changes with that position.\n:::\n\n5. With reference to the sampling design along the river, give the mechanistic, ecological reasons for the strongly correlated environmental variables revealed by the PCA.\n\n::: {.callout-note collapse=\"true\"}\n## Show the answer\n\nThe sites are arranged in sequence from the source to the mouth, so position along the river is itself the dominant explanatory structure, and the variables are correlated because each tracks that position:\n\n- **Elevation and distance from source** fall and rise together because the channel descends as it lengthens.\n- **Discharge** grows downstream as tributaries accumulate, so it rises with distance from source.\n- **Nutrients and organic load** (`pho`, `nit`, `amm`, `bod`) accumulate in the lower reaches as the catchment integrates inputs, so they form a mutually correlated block.\n- **Dissolved oxygen** falls where organic load is high, opposing the nutrient block.\n\nNone of these requires a direct pairwise mechanism. They are joint expressions of the longitudinal gradient, which is exactly why PCA can compress them into one or two axes.\n:::\n\n6. Why can a PCA (or any ordination) not explain all of the variation in a dataset, and why do we interpret only the first few components? What is represented by the later axes?\n\n::: {.callout-note collapse=\"true\"}\n## Show the answer\n\nA PCA re-expresses *p* variables as *p* orthogonal components that together hold 100% of the variance, so in that arithmetic sense it does capture everything. The point is that the variance is not evenly spread. The first components concentrate the shared, structured variation (here the river gradient), while later components hold progressively weaker signals: local site idiosyncrasies, the unique part of single variables, measurement error, and noise. We interpret only the first few because they carry the coordinated, ecologically meaningful structure; the trailing axes are dominated by variation that is either unstructured or specific to one variable, so reading them invites over-interpretation of noise. The broken-stick and screeplot diagnostics in Exercise 3 are precisely the tools for drawing that line.\n:::\n\n## Assessment Criteria\n\nThis Task is not formally assessed. It is built around four hands-on analyses (Exercises 1--4) and two short conceptual questions (Exercises 5--6); work through all six and bring your annotated Quarto document to class for discussion.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}