{
  "hash": "6fb023cacadd2f91cc0384dafa7dbaa8",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"BCB744 Biostatistics — Practical Assessment (Version 2)\"\nsubtitle: \"Chapters 1–14 | Total: 170 marks\"\ndate: \"2026-07-25\"\nlang: en-GB\nengine: knitr\nparams:\n  hide_answers: false\nexecute:\n  cache: false\n  warning: false\n  message: false\nformat:\n  html:\n    embed-resources: true\n    code-tools: false\n    number-sections: false\n    toc: true\n    toc-depth: 2\n---\n\n\n\n::: {.callout-important appearance=\"simple\"}\n## Instructions\n\n- Answer **all eight questions**. The paper totals **170 marks** and you have **30 hr** to complete it.\n- Submit a thoroughly annotated HTML report rendered from Quarto. Show the R code used and interpret the evidence in complete sentences.\n- This is a practical assessment. Marks are awarded for exploratory data analysis, statistical reasoning, correct analysis, diagnostics, interpretation, and communication. No question asks for a stand-alone theory essay.\n- Before each inferential analysis, state the biological question and the null and alternative hypotheses. Identify the observational or experimental unit.\n- Use plots and numerical summaries to examine the data before choosing or fitting a test. Check assumptions at the level appropriate to the analysis.\n- Report estimates or effect sizes, uncertainty where available, test statistics, degrees of freedom, and **exact *p*-values**.\n- Unless a question explicitly requests otherwise, use a two-sided significance level of $\\alpha = 0.05$.\n- Long, unedited console dumps are not acceptable and will be penalised. Present only output that contributes to the analysis.\n\n- [**Required YAML Structure:**]{.my-highlight} Your Quarto document must begin with the following YAML header (fill in your own details where indicated):\n\n  ````yaml\n  ---\n  title: \"BCB744 Biostatistics Assessment\"\n  author: \"Your Name\"\n  date: \"2026\"\n  format:\n    html:\n      embed-resources: true\n      toc: false\n      number-sections: false\n  ---\n  ````\n\n  Your document should follow this hierarchical structure:\n\n  ````markdown\n  # Question 1\n\n  ## Preamble\n  ## Introduction\n  ## Methods\n  ## Results\n  ## Discussion\n\n  # Question 2\n\n  ## Preamble\n  ## Introduction\n  ## Methods\n  ## Results\n  ## Discussion\n\n  [... continue for the remaining questions ...]\n\n  # References\n  ````\n:::\n\n# Question 1 — Mammalian Body and Brain Mass (/20)\n\nThe `mammals` dataset in **MASS** contains body mass (kg) and brain mass (g) for 62 terrestrial mammal species. Each row represents one species.\n\na. Inspect the structure, missingness, and numerical range of both variables. Produce an informative two-panel EDA figure showing the distribution of raw body mass and raw brain mass. Summarise what the figure and appropriate measures of centre and spread reveal. **(/5)**\n\nb. Apply a base-10 logarithm to both variables. Reproduce the two distribution plots on the transformed scale and explain, using evidence from your plots and summaries, whether the transformation improves their suitability for model-based analysis. **(/5)**\n\nc. Treat the 62 observed species as a finite population. Set the seed to `744`, then draw 2,000 random samples **without replacement** at each of two sample sizes, $n=10$ and $n=40$. For every sample, calculate the mean log~10~ brain mass. Plot the two sampling distributions and report their empirical means, standard errors, and central 95% ranges. Explain what the comparison demonstrates about sample size and sampling uncertainty. **(/6)**\n\nd. Make a scatter plot of log~10~ brain mass against log~10~ body mass. Describe the form, direction, strength, and any unusual observations. State one limitation of treating the 62 species as independent replicates. Do not yet fit a regression model. **(/4)**\n\n\n\n::: {.callout-tip appearance=\"simple\"}\n## Worked answer — Question 1\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmammals_df <- MASS::mammals |>\n  tibble::rownames_to_column(\"species\")\n\nstr(mammals_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n'data.frame':\t62 obs. of  3 variables:\n $ species: chr  \"Arctic fox\" \"Owl monkey\" \"Mountain beaver\" \"Cow\" ...\n $ body   : num  3.38 0.48 1.35 465 36.33 ...\n $ brain  : num  44.5 15.5 8.1 423 119.5 ...\n```\n\n\n:::\n\n```{.r .cell-code}\ncolSums(is.na(mammals_df))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nspecies    body   brain \n      0       0       0 \n```\n\n\n:::\n\n```{.r .cell-code}\nmammals_df |>\n  summarise(\n    across(\n      c(body, brain),\n      list(\n        min = min,\n        q1 = ~ quantile(.x, 0.25),\n        median = median,\n        mean = mean,\n        q3 = ~ quantile(.x, 0.75),\n        max = max,\n        sd = sd,\n        iqr = IQR\n      )\n    )\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  body_min body_q1 body_median body_mean body_q3 body_max body_sd body_iqr\n1    0.005     0.6      3.3425    198.79 48.2025     6654 899.158  47.6025\n  brain_min brain_q1 brain_median brain_mean brain_q3 brain_max brain_sd\n1      0.14     4.25        17.25   283.1342      166      5712 930.2789\n  brain_iqr\n1    161.75\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmammals_df |>\n  pivot_longer(c(body, brain), names_to = \"measurement\", values_to = \"value\") |>\n  mutate(\n    measurement = recode(\n      measurement,\n      body = \"Body mass (kg)\",\n      brain = \"Brain mass (g)\"\n    )\n  ) |>\n  ggplot(aes(value)) +\n  geom_histogram(bins = 18, colour = \"white\", fill = \"#2C7FB8\") +\n  geom_vline(\n    data = mammals_df |>\n      pivot_longer(\n        c(body, brain),\n        names_to = \"measurement\",\n        values_to = \"value\"\n      ) |>\n      mutate(\n        measurement = recode(\n          measurement,\n          body = \"Body mass (kg)\",\n          brain = \"Brain mass (g)\"\n        )\n      ) |>\n      summarise(median = median(value), .by = measurement),\n    aes(xintercept = median),\n    linetype = 2\n  ) +\n  facet_wrap(~measurement, scales = \"free\") +\n  labs(x = NULL, y = \"Number of species\")\n```\n\n::: {.cell-output-display}\n![Raw distributions of body mass and brain mass among 62 mammal species. The dashed lines show the medians.](BCB744_Biostatistics_Practical_Assessment_2026_V2_files/figure-html/q1-raw-distributions-1.svg)\n:::\n:::\n\n\nThere are 62 species and no missing values. Both variables are extremely right-skewed. For body mass, the mean is far larger than the median because a few very large mammals dominate the upper tail. Brain mass shows the same pattern. The medians and IQRs therefore describe a typical species more faithfully than the means and standard deviations on the raw scale.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmammals_log <- mammals_df |>\n  mutate(\n    log_body = log10(body),\n    log_brain = log10(brain)\n  )\n\nmammals_log |>\n  summarise(\n    across(\n      c(log_body, log_brain),\n      list(mean = mean, median = median, sd = sd, iqr = IQR)\n    )\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  log_body_mean log_body_median log_body_sd log_body_iqr log_brain_mean\n1     0.5808858       0.5240363    1.356357     1.904032       1.363771\n  log_brain_median log_brain_sd log_brain_iqr\n1         1.236743     1.062507      1.593602\n```\n\n\n:::\n\n```{.r .cell-code}\nmammals_log |>\n  pivot_longer(\n    c(log_body, log_brain),\n    names_to = \"measurement\",\n    values_to = \"log_value\"\n  ) |>\n  mutate(\n    measurement = recode(\n      measurement,\n      log_body = \"log10 body mass\",\n      log_brain = \"log10 brain mass\"\n    )\n  ) |>\n  ggplot(aes(log_value)) +\n  geom_histogram(bins = 14, colour = \"white\", fill = \"#41AB5D\") +\n  facet_wrap(~measurement, scales = \"free\") +\n  labs(x = \"Transformed value\", y = \"Number of species\")\n```\n\n::: {.cell-output-display}\n![](BCB744_Biostatistics_Practical_Assessment_2026_V2_files/figure-html/q1-log-distributions-1.svg)\n:::\n:::\n\n\nThe log transformation compresses the extreme upper tails and makes both distributions much more nearly symmetric. It also brings each mean closer to its median. This does not itself prove that a regression will be valid, but it makes a roughly linear relationship and stable residual variance more plausible. Those properties must be checked after fitting the model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(744)\n\nsampling_means <- bind_rows(\n  tibble(\n    sample_size = 10,\n    sample_mean = replicate(\n      2000,\n      mean(sample(mammals_log$log_brain, size = 10, replace = FALSE))\n    )\n  ),\n  tibble(\n    sample_size = 40,\n    sample_mean = replicate(\n      2000,\n      mean(sample(mammals_log$log_brain, size = 40, replace = FALSE))\n    )\n  )\n) |>\n  mutate(sample_size = factor(sample_size, levels = c(10, 40)))\n\nsampling_summary <- sampling_means |>\n  summarise(\n    empirical_mean = mean(sample_mean),\n    empirical_se = sd(sample_mean),\n    lower_2.5 = quantile(sample_mean, 0.025),\n    upper_97.5 = quantile(sample_mean, 0.975),\n    .by = sample_size\n  )\n\nsampling_summary\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  sample_size empirical_mean empirical_se lower_2.5 upper_97.5\n  <fct>                <dbl>        <dbl>     <dbl>      <dbl>\n1 10                    1.37       0.303      0.780       1.97\n2 40                    1.37       0.0982     1.18        1.56\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(mammals_log$log_brain)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.363771\n```\n\n\n:::\n\n```{.r .cell-code}\nggplot(sampling_means, aes(sample_mean)) +\n  geom_histogram(bins = 35, colour = \"white\", fill = \"#756BB1\") +\n  geom_vline(\n    xintercept = mean(mammals_log$log_brain),\n    linewidth = 0.8\n  ) +\n  facet_wrap(\n    ~sample_size,\n    labeller = labeller(sample_size = \\(x) paste0(\"n = \", x))\n  ) +\n  labs(\n    x = expression(\"Sample mean \" * log[10] * \" brain mass\"),\n    y = \"Number of simulated samples\"\n  )\n```\n\n::: {.cell-output-display}\n![](BCB744_Biostatistics_Practical_Assessment_2026_V2_files/figure-html/q1-sampling-distributions-1.svg)\n:::\n:::\n\n\nBoth sampling distributions are centred close to the finite-population mean. The distribution for $n=40$ has a smaller empirical standard error and a narrower central 95% range than the distribution for $n=10$. Larger samples therefore give more precise estimates of the population mean because sample-to-sample variation is reduced. Sampling without replacement also introduces a finite-population correction, which is substantial when 40 of the 62 species are selected. This simulation describes repeated samples from these 62 species; it does not by itself justify generalisation to every mammal species.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nq1_provisional <- lm(log_brain ~ log_body, data = mammals_log)\n\nmammals_log |>\n  mutate(abs_residual = abs(residuals(q1_provisional))) |>\n  ggplot(aes(log_body, log_brain)) +\n  geom_point(colour = \"#2B8CBE\", alpha = 0.8) +\n  geom_smooth(method = \"lm\", se = TRUE, colour = \"#CB181D\") +\n  geom_text(\n    data = \\(x) slice_max(x, abs_residual, n = 4),\n    aes(label = species),\n    nudge_y = 0.12,\n    check_overlap = TRUE,\n    size = 3\n  ) +\n  labs(\n    x = expression(log[10] * \" body mass (kg)\"),\n    y = expression(log[10] * \" brain mass (g)\")\n  )\n```\n\n::: {.cell-output-display}\n![Relationship between log-transformed body and brain mass among mammal species. Labels identify the four observations with the largest absolute residuals from a provisional straight line.](BCB744_Biostatistics_Practical_Assessment_2026_V2_files/figure-html/q1-scatter-1.svg)\n:::\n:::\n\n\nThe transformed variables show a strong, positive, approximately linear association, although several species depart noticeably from the overall pattern. Species are not necessarily independent because shared evolutionary history can make closely related species more similar than expected under independent sampling. A phylogenetically informed analysis would be needed for strong comparative biological inference.\n:::\n\n\n\n# Question 2 — A Thermal-Acclimation Experiment (/16)\n\nThe following code creates a new dataset from an experiment on 24 individually tagged intertidal snails. Oxygen consumption was measured for each snail before and after a 14-day warm-acclimation treatment. Rates are in µmol O~2~ h^-1^.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsnails <- tibble(\n  snail_id = sprintf(\"S%02d\", 1:24),\n  before = c(\n    5.8,\n    6.1,\n    4.9,\n    5.4,\n    6.7,\n    5.2,\n    5.9,\n    6.4,\n    5.1,\n    5.6,\n    6.3,\n    5.0,\n    5.7,\n    6.2,\n    4.8,\n    5.5,\n    6.0,\n    5.3,\n    6.5,\n    5.4,\n    5.9,\n    6.1,\n    5.2,\n    5.8\n  ),\n  after = c(\n    6.4,\n    6.8,\n    5.1,\n    6.0,\n    7.5,\n    5.7,\n    6.6,\n    7.0,\n    5.6,\n    6.1,\n    7.1,\n    5.4,\n    6.3,\n    6.9,\n    5.2,\n    6.2,\n    6.7,\n    5.9,\n    7.2,\n    5.8,\n    6.5,\n    6.8,\n    5.8,\n    6.4\n  )\n)\n```\n:::\n\n\na. Reshape the data into a tidy long form and produce a graphic that preserves the pairing between measurements. Add a concise numerical summary of the before, after, and within-snail change values. **(/5)**\n\nb. State the experimental unit and the hypotheses. Check the distribution of the **within-snail differences**, explain why this is the relevant diagnostic, and conduct an appropriate inferential test. **(/6)**\n\nc. Report the estimated mean change, its 95% confidence interval, the test statistic, degrees of freedom, and *p*-value. Interpret both the statistical and biological result. **(/5)**\n\n\n\n::: {.callout-tip appearance=\"simple\"}\n## Worked answer — Question 2\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsnails_long <- snails |>\n  pivot_longer(c(before, after), names_to = \"occasion\", values_to = \"oxygen\") |>\n  mutate(occasion = factor(occasion, levels = c(\"before\", \"after\")))\n\nsnails_change <- snails |>\n  mutate(change = after - before)\n\nsnails_change |>\n  summarise(\n    before_mean = mean(before),\n    before_sd = sd(before),\n    after_mean = mean(after),\n    after_sd = sd(after),\n    mean_change = mean(change),\n    sd_change = sd(change),\n    median_change = median(change),\n    iqr_change = IQR(change)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 8\n  before_mean before_sd after_mean after_sd mean_change sd_change median_change\n        <dbl>     <dbl>      <dbl>    <dbl>       <dbl>     <dbl>         <dbl>\n1         5.7     0.529       6.29    0.648       0.592     0.141           0.6\n# ℹ 1 more variable: iqr_change <dbl>\n```\n\n\n:::\n\n```{.r .cell-code}\nggplot(snails_long, aes(occasion, oxygen, group = snail_id)) +\n  geom_line(colour = \"grey65\", alpha = 0.8) +\n  geom_point(aes(colour = occasion), size = 2.2, show.legend = FALSE) +\n  stat_summary(\n    aes(group = 1),\n    fun = mean,\n    geom = \"line\",\n    colour = \"black\",\n    linewidth = 1.1\n  ) +\n  stat_summary(\n    aes(group = 1),\n    fun = mean,\n    geom = \"point\",\n    colour = \"black\",\n    size = 3\n  ) +\n  labs(\n    x = NULL,\n    y = expression(\"Oxygen consumption (\" * mu * \"mol O\"[2] * \" \" * h^-1 * \")\")\n  )\n```\n\n::: {.cell-output-display}\n![](BCB744_Biostatistics_Practical_Assessment_2026_V2_files/figure-html/q2-eda-1.svg)\n:::\n:::\n\n\nThe snail is the experimental unit because the treatment comparison is made within each tagged individual. Let $d_i = \\text{after}_i-\\text{before}_i$. The hypotheses are $H_0:\\mu_d=0$ and $H_A:\\mu_d\\ne0$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(snails_change, aes(sample = change)) +\n  stat_qq() +\n  stat_qq_line() +\n  labs(x = \"Theoretical quantiles\", y = \"Observed change quantiles\")\n```\n\n::: {.cell-output-display}\n![](BCB744_Biostatistics_Practical_Assessment_2026_V2_files/figure-html/q2-assumptions-1.svg)\n:::\n\n```{.r .cell-code}\nshapiro.test(snails_change$change)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  snails_change$change\nW = 0.9031, p-value = 0.02506\n```\n\n\n:::\n:::\n\n\nThe paired *t*-test assumes that the within-pair differences are approximately normally distributed. It does not require the separate before and after samples to be normally distributed. The Q-Q plot and Shapiro-Wilk result show no important contradiction of this assumption.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nq2_test <- t.test(snails$after, snails$before, paired = TRUE)\nq2_test\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPaired t-test\n\ndata:  snails$after and snails$before\nt = 20.533, df = 23, p-value = 2.723e-16\nalternative hypothesis: true mean difference is not equal to 0\n95 percent confidence interval:\n 0.5320579 0.6512754\nsample estimates:\nmean difference \n      0.5916667 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.5916667\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.5320579 0.6512754\nattr(,\"conf.level\")\n[1] 0.95\n```\n\n\n:::\n:::\n\n\nThe fitted estimate is the mean **after minus before** change. Its confidence interval excludes zero, and the paired test provides strong evidence against $H_0$. Warm acclimation increased oxygen consumption in this sample by about the reported mean change in µmol O~2~ h^-1^. The result estimates an average response over 14 days; it does not establish whether the response persists longer or generalises beyond the sampled population.\n:::\n\n\n\n# Question 3 — Bee Repellency of Orchard Sprays (/20)\n\nThe built-in `OrchardSprays` dataset records the decrease in the volume of a sugar solution after honeybees were exposed to eight orchard-spray treatments. The decrease is used as an index of bee repellency. There are eight observations per treatment. For this assessment, treat each orchard position as an independent experimental unit and treatment as the sole explanatory factor; do not model `rowpos` or `colpos`.\n\na. Inspect the data and produce a figure that displays all observations as well as a suitable distributional summary for each treatment. Calculate a suite of suitable summary statistics and report them neatly in a table using the **gt** package. **(/6)**\n\nb. State the experimental unit and hypotheses for an overall treatment comparison. Select an appropriate inferential approach and justify it using the study design, the distribution of model errors, the variability among treatments, and the influence of unusual observations. Show the diagnostic evidence supporting your decision. **(/7)**\n\nc. Conduct the analysis selected in (b). If the overall result justifies further investigation, compare treatment pairs using a procedure that controls the family-wise error rate. Report the overall result and the adjusted pairwise evidence, then explain which treatments differ and in which direction without claiming more than the analysis supports. **(/7)**\n\n\n\n::: {.callout-tip appearance=\"simple\"}\n## Worked answer — Question 3\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsprays <- as_tibble(OrchardSprays) |>\n  mutate(treatment = factor(treatment))\n\nspray_summary <- sprays |>\n  summarise(\n    n = n(),\n    mean = mean(decrease),\n    median = median(decrease),\n    sd = sd(decrease),\n    iqr = IQR(decrease),\n    .by = treatment\n  ) |>\n  arrange(treatment)\n\nspray_summary |>\n  gt::gt(rowname_col = \"treatment\") |>\n  gt::tab_header(\n    title = \"Bee repellency by orchard-spray treatment\",\n    subtitle = \"Decrease in sugar-solution volume\"\n  ) |>\n  gt::cols_label(\n    n = \"n\",\n    mean = \"Mean\",\n    median = \"Median\",\n    sd = \"SD\",\n    iqr = \"IQR\"\n  ) |>\n  gt::fmt_number(\n    columns = c(mean, median, sd, iqr),\n    decimals = 2\n  )\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"iufniyuxis\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#iufniyuxis table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#iufniyuxis thead, #iufniyuxis tbody, #iufniyuxis tfoot, #iufniyuxis tr, #iufniyuxis td, #iufniyuxis th {\n  border-style: none;\n}\n\n#iufniyuxis p {\n  margin: 0;\n  padding: 0;\n}\n\n#iufniyuxis .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#iufniyuxis .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#iufniyuxis .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#iufniyuxis .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#iufniyuxis .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#iufniyuxis .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#iufniyuxis .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#iufniyuxis .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#iufniyuxis .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#iufniyuxis .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#iufniyuxis .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#iufniyuxis .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#iufniyuxis .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#iufniyuxis .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#iufniyuxis .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#iufniyuxis .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#iufniyuxis .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#iufniyuxis .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#iufniyuxis .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#iufniyuxis .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#iufniyuxis .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#iufniyuxis .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#iufniyuxis .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#iufniyuxis .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#iufniyuxis .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#iufniyuxis .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#iufniyuxis .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#iufniyuxis .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#iufniyuxis .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#iufniyuxis .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#iufniyuxis .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#iufniyuxis .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#iufniyuxis .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#iufniyuxis .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#iufniyuxis .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#iufniyuxis .gt_left {\n  text-align: left;\n}\n\n#iufniyuxis .gt_center {\n  text-align: center;\n}\n\n#iufniyuxis .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#iufniyuxis .gt_font_normal {\n  font-weight: normal;\n}\n\n#iufniyuxis .gt_font_bold {\n  font-weight: bold;\n}\n\n#iufniyuxis .gt_font_italic {\n  font-style: italic;\n}\n\n#iufniyuxis .gt_super {\n  font-size: 65%;\n}\n\n#iufniyuxis .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#iufniyuxis .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#iufniyuxis .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#iufniyuxis .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#iufniyuxis .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#iufniyuxis .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#iufniyuxis .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#iufniyuxis .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#iufniyuxis div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"6\" class=\"gt_heading gt_title gt_font_normal\" style>Bee repellency by orchard-spray treatment</td>\n    </tr>\n    <tr class=\"gt_heading\">\n      <td colspan=\"6\" class=\"gt_heading gt_subtitle gt_font_normal gt_bottom_border\" style>Decrease in sugar-solution volume</td>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"a::stub\"></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"n\">n</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"mean\">Mean</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"median\">Median</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"sd\">SD</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"iqr\">IQR</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><th id=\"stub_1_1\" scope=\"row\" class=\"gt_row gt_center gt_stub\">A</th>\n<td headers=\"stub_1_1 n\" class=\"gt_row gt_right\">8</td>\n<td headers=\"stub_1_1 mean\" class=\"gt_row gt_right\">4.62</td>\n<td headers=\"stub_1_1 median\" class=\"gt_row gt_right\">4.00</td>\n<td headers=\"stub_1_1 sd\" class=\"gt_row gt_right\">3.20</td>\n<td headers=\"stub_1_1 iqr\" class=\"gt_row gt_right\">2.25</td></tr>\n    <tr><th id=\"stub_1_2\" scope=\"row\" class=\"gt_row gt_center gt_stub\">B</th>\n<td headers=\"stub_1_2 n\" class=\"gt_row gt_right\">8</td>\n<td headers=\"stub_1_2 mean\" class=\"gt_row gt_right\">7.62</td>\n<td headers=\"stub_1_2 median\" class=\"gt_row gt_right\">7.50</td>\n<td headers=\"stub_1_2 sd\" class=\"gt_row gt_right\">3.29</td>\n<td headers=\"stub_1_2 iqr\" class=\"gt_row gt_right\">3.00</td></tr>\n    <tr><th id=\"stub_1_3\" scope=\"row\" class=\"gt_row gt_center gt_stub\">C</th>\n<td headers=\"stub_1_3 n\" class=\"gt_row gt_right\">8</td>\n<td headers=\"stub_1_3 mean\" class=\"gt_row gt_right\">25.25</td>\n<td headers=\"stub_1_3 median\" class=\"gt_row gt_right\">16.50</td>\n<td headers=\"stub_1_3 sd\" class=\"gt_row gt_right\">24.43</td>\n<td headers=\"stub_1_3 iqr\" class=\"gt_row gt_right\">7.00</td></tr>\n    <tr><th id=\"stub_1_4\" scope=\"row\" class=\"gt_row gt_center gt_stub\">D</th>\n<td headers=\"stub_1_4 n\" class=\"gt_row gt_right\">8</td>\n<td headers=\"stub_1_4 mean\" class=\"gt_row gt_right\">35.00</td>\n<td headers=\"stub_1_4 median\" class=\"gt_row gt_right\">32.00</td>\n<td headers=\"stub_1_4 sd\" class=\"gt_row gt_right\">13.44</td>\n<td headers=\"stub_1_4 iqr\" class=\"gt_row gt_right\">16.25</td></tr>\n    <tr><th id=\"stub_1_5\" scope=\"row\" class=\"gt_row gt_center gt_stub\">E</th>\n<td headers=\"stub_1_5 n\" class=\"gt_row gt_right\">8</td>\n<td headers=\"stub_1_5 mean\" class=\"gt_row gt_right\">63.12</td>\n<td headers=\"stub_1_5 median\" class=\"gt_row gt_right\">53.00</td>\n<td headers=\"stub_1_5 sd\" class=\"gt_row gt_right\">26.91</td>\n<td headers=\"stub_1_5 iqr\" class=\"gt_row gt_right\">23.50</td></tr>\n    <tr><th id=\"stub_1_6\" scope=\"row\" class=\"gt_row gt_center gt_stub\">F</th>\n<td headers=\"stub_1_6 n\" class=\"gt_row gt_right\">8</td>\n<td headers=\"stub_1_6 mean\" class=\"gt_row gt_right\">69.00</td>\n<td headers=\"stub_1_6 median\" class=\"gt_row gt_right\">70.00</td>\n<td headers=\"stub_1_6 sd\" class=\"gt_row gt_right\">29.19</td>\n<td headers=\"stub_1_6 iqr\" class=\"gt_row gt_right\">34.00</td></tr>\n    <tr><th id=\"stub_1_7\" scope=\"row\" class=\"gt_row gt_center gt_stub\">G</th>\n<td headers=\"stub_1_7 n\" class=\"gt_row gt_right\">8</td>\n<td headers=\"stub_1_7 mean\" class=\"gt_row gt_right\">68.50</td>\n<td headers=\"stub_1_7 median\" class=\"gt_row gt_right\">72.00</td>\n<td headers=\"stub_1_7 sd\" class=\"gt_row gt_right\">20.14</td>\n<td headers=\"stub_1_7 iqr\" class=\"gt_row gt_right\">9.50</td></tr>\n    <tr><th id=\"stub_1_8\" scope=\"row\" class=\"gt_row gt_center gt_stub\">H</th>\n<td headers=\"stub_1_8 n\" class=\"gt_row gt_right\">8</td>\n<td headers=\"stub_1_8 mean\" class=\"gt_row gt_right\">90.25</td>\n<td headers=\"stub_1_8 median\" class=\"gt_row gt_right\">81.00</td>\n<td headers=\"stub_1_8 sd\" class=\"gt_row gt_right\">24.22</td>\n<td headers=\"stub_1_8 iqr\" class=\"gt_row gt_right\">21.25</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n\n```{.r .cell-code}\nggplot(sprays, aes(treatment, decrease, colour = treatment)) +\n  geom_boxplot(outlier.shape = NA, alpha = 0.18, show.legend = FALSE) +\n  geom_jitter(width = 0.08, height = 0, size = 2.2, show.legend = FALSE) +\n  labs(x = \"Spray treatment\", y = \"Decrease in sugar-solution volume\")\n```\n\n::: {.cell-output-display}\n![](BCB744_Biostatistics_Practical_Assessment_2026_V2_files/figure-html/q3-eda-1.svg)\n:::\n:::\n\n\nThe experimental unit is the individual spray observation represented by a row, assuming that the eight values within each treatment arose from independent replicates. The hypotheses are $H_0:\\mu_A=\\mu_B=\\cdots=\\mu_H$ and $H_A:$ at least one treatment mean differs.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nq3_lm <- lm(decrease ~ treatment, data = sprays)\n\npar(mfrow = c(2, 2))\nplot(q3_lm)\n```\n\n::: {.cell-output-display}\n![](BCB744_Biostatistics_Practical_Assessment_2026_V2_files/figure-html/q3-model-diagnostics-1.svg)\n:::\n\n```{.r .cell-code}\npar(mfrow = c(1, 1))\n\nshapiro.test(residuals(q3_lm))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  residuals(q3_lm)\nW = 0.92159, p-value = 0.0005796\n```\n\n\n:::\n\n```{.r .cell-code}\nbartlett.test(decrease ~ treatment, data = sprays)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tBartlett test of homogeneity of variances\n\ndata:  decrease by treatment\nBartlett's K-squared = 42.031, df = 7, p-value = 5.128e-07\n```\n\n\n:::\n\n```{.r .cell-code}\nsort(cooks.distance(q3_lm), decreasing = TRUE)[1:5]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         9         27         29         58         30 \n0.16736129 0.12550127 0.11642103 0.09818933 0.09601947 \n```\n\n\n:::\n\n```{.r .cell-code}\n4 / nrow(sprays)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.0625\n```\n\n\n:::\n:::\n\n\nThe residual plots should be read together rather than turning each diagnostic into an automatic pass/fail rule. Here the distributions differ in spread and include unusual observations. Bartlett’s test is sensitive to non-normality, but its result and the residual-versus-fitted plot both warn against assuming equal variance. I therefore use Welch’s one-way ANOVA, which relaxes the equal-variance assumption while retaining a comparison of group means.\n\n\n::: {.cell}\n\n```{.r .cell-code}\noneway.test(decrease ~ treatment, data = sprays, var.equal = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne-way analysis of means (not assuming equal variances)\n\ndata:  decrease and treatment\nF = 33.515, num df = 7.000, denom df = 22.843, p-value = 1.476e-10\n```\n\n\n:::\n:::\n\n\nThe Welch test rejects equality of all treatment means. A Games-Howell procedure would be a natural unequal-variance post-hoc method, but it requires an additional package. A transparent base-R alternative is pairwise Welch *t*-tests with Holm correction:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npairwise.t.test(\n  x = sprays$decrease,\n  g = sprays$treatment,\n  p.adjust.method = \"holm\",\n  pool.sd = FALSE\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPairwise comparisons using t tests with non-pooled SD \n\ndata:  sprays$decrease and sprays$treatment \n\n  A       B       C       D       E       F       G      \nB 0.57461 -       -       -       -       -       -      \nC 0.48607 0.57461 -       -       -       -       -      \nD 0.00623 0.01027 1.00000 -       -       -       -      \nE 0.00875 0.01027 0.13889 0.26397 -       -       -      \nF 0.00850 0.01027 0.08408 0.16494 1.00000 -       -      \nG 0.00091 0.00120 0.02928 0.02998 1.00000 1.00000 -      \nH 0.00050 0.00061 0.00249 0.00354 0.48607 0.68070 0.57461\n\nP value adjustment method: holm \n```\n\n\n:::\n:::\n\n\nOnly pairs with Holm-adjusted *p* < 0.05 should be described as supported differences. Treatments D, E, F, G, and H each had a larger mean decrease than A and B. Treatment G also exceeded C and D, while H exceeded C and D. No other pair had an adjusted *p*-value below 0.05. The omnibus result does not mean every treatment differs from every other treatment, and non-significant pairs should not be declared equivalent.\n:::\n\n\n\n# Question 4 — Allometric Scaling of Mammalian Brains (/22)\n\nReturn to the log-transformed mammal data from Question 1. Treat this as a model-building question rather than a repeat of the EDA.\n\na. Quantify the association between log~10~ body mass and log~10~ brain mass. Select and justify an appropriate inferential measure from the form and distribution of the data, state the hypotheses, and report its estimate, 95% confidence interval, test statistic, degrees of freedom, and *p*-value. **(/4)**\n\nb. Fit a suitable model to predict log~10~ brain mass from log~10~ body mass. Present the fitted equation, interpret both coefficients and the slope in allometric terms, and report the slope estimate with its 95% confidence interval, test statistic, degrees of freedom, *p*-value, and model $R^2$. **(/6)**\n\nc. Assess whether the fitted model satisfies its distributional and structural assumptions. Quantify case influence, identify the most influential species, and explain whether the evidence warrants deleting any observation. **(/4)**\n\nd. Obtain the mean-response 95% confidence interval and individual-species 95% prediction interval for a mammal weighing 10 kg. Interpret the difference between the two intervals on the original brain-mass scale. **(/4)**\n\ne. Write one concise, publication-style results paragraph integrating the principal numerical findings from (a)–(d). Distinguish the fitted mean response from prediction for a new species and avoid causal language. **(/4)**\n\n\n\n::: {.callout-tip appearance=\"simple\"}\n## Worked answer — Question 4\n\n$H_0:\\rho=0$ and $H_A:\\rho\\ne0$, where $\\rho$ is the population Pearson correlation between the two transformed measurements.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nq4_cor <- cor.test(\n  mammals_log$log_body,\n  mammals_log$log_brain,\n  method = \"pearson\"\n)\nq4_cor\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's product-moment correlation\n\ndata:  mammals_log$log_body and mammals_log$log_brain\nt = 26.409, df = 60, p-value < 2.2e-16\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.9335522 0.9755352\nsample estimates:\n      cor \n0.9595748 \n```\n\n\n:::\n:::\n\n\nThe scatter plot from Question 1 supports a linear measure of association on the log scales. The estimated correlation is positive and strong, with its confidence interval well above zero.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nq4_lm <- lm(log_brain ~ log_body, data = mammals_log)\nsummary(q4_lm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = log_brain ~ log_body, data = mammals_log)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.74503 -0.21380 -0.02676  0.18934  0.84613 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  0.92713    0.04171   22.23   <2e-16 ***\nlog_body     0.75169    0.02846   26.41   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.3015 on 60 degrees of freedom\nMultiple R-squared:  0.9208,\tAdjusted R-squared:  0.9195 \nF-statistic: 697.4 on 1 and 60 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\nconfint(q4_lm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                2.5 %    97.5 %\n(Intercept) 0.8436923 1.0105616\nlog_body    0.6947503 0.8086215\n```\n\n\n:::\n:::\n\n\nThe fitted equation is\n\n$$\n\\widehat{\\log_{10}(\\text{brain})}\n= \\hat{\\beta}_0 + \\hat{\\beta}_1\\log_{10}(\\text{body}).\n$$\n\nThe slope is an allometric exponent: a ten-fold increase in body mass is associated with an expected increase of $\\hat{\\beta}_1$ log~10~ units in brain mass, or a multiplication of expected brain mass by $10^{\\hat{\\beta}_1}$. The slope test evaluates $H_0:\\beta_1=0$ against $H_A:\\beta_1\\ne0$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(2, 2))\nplot(q4_lm)\n```\n\n::: {.cell-output-display}\n![](BCB744_Biostatistics_Practical_Assessment_2026_V2_files/figure-html/q4-diagnostics-1.svg)\n:::\n\n```{.r .cell-code}\npar(mfrow = c(1, 1))\n\nq4_influence <- mammals_log |>\n  mutate(cooks_d = cooks.distance(q4_lm)) |>\n  arrange(desc(cooks_d))\n\nq4_influence |>\n  dplyr::select(species, body, brain, cooks_d) |>\n  slice_head(n = 6)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          species    body   brain    cooks_d\n1           Human  62.000 1320.00 0.12202210\n2      Musk shrew   0.048    0.33 0.05105702\n3   Water opossum   3.500    3.90 0.05090140\n4   Rhesus monkey   6.800  179.00 0.04651557\n5 Ground squirrel   0.101    4.00 0.04079438\n6             Pig 192.000  180.00 0.03787819\n```\n\n\n:::\n\n```{.r .cell-code}\n4 / nrow(mammals_log)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.06451613\n```\n\n\n:::\n\n```{.r .cell-code}\nshapiro.test(residuals(q4_lm))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  residuals(q4_lm)\nW = 0.98268, p-value = 0.5293\n```\n\n\n:::\n:::\n\n\nThe residual-versus-fitted and scale-location plots assess functional form and variance; the Q-Q plot assesses residual normality; and Cook’s distance measures how strongly each row affects the fitted model. A value above the common $4/n$ screening threshold deserves investigation, but it is not an automatic deletion rule. A biologically valid extreme species should remain unless there is evidence of measurement or transcription error. A sensitivity fit with and without an influential point may be reported.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nq4_new <- data.frame(log_body = log10(10))\n\nq4_conf <- predict(q4_lm, newdata = q4_new, interval = \"confidence\")\nq4_pred <- predict(q4_lm, newdata = q4_new, interval = \"prediction\")\n\n10^q4_conf\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       fit      lwr      upr\n1 47.73236 39.68098 57.41738\n```\n\n\n:::\n\n```{.r .cell-code}\n10^q4_pred\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       fit      lwr      upr\n1 47.73236 11.75855 193.7636\n```\n\n\n:::\n:::\n\n\nExponentiating converts the fitted values and interval limits back to grams. The confidence interval estimates uncertainty in the **mean** brain mass for the modelled population of 10 kg mammals. The prediction interval is wider because it also includes residual among-species variation and is intended for a single new 10 kg species.\n\nA suitable publication-style result is:\n\n> Across the 62 mammal species, log~10~ brain mass was strongly and positively associated with log~10~ body mass (Pearson's $r$ = 0.96, 95% CI [0.934, 0.976], $t_{60}$ = 26.41, $p$ < 0.001). The fitted relationship was $\\widehat{\\log_{10}(\\text{brain mass})} = 0.927 + 0.752 $\\log_{10}(\\text{body mass})$, with body mass explaining 92.1% of the variation in log~10~ brain mass. The allometric slope was 0.752 (95% CI [0.695, 0.809]). For a 10 kg mammal, the estimated mean brain mass was 47.7 g (95% CI [39.7, 57.4]), whereas the 95% interval for a single new 10 kg species was [11.8, 193.8] g. The wider latter interval reflects residual among-species variation, and the observational analysis supports association rather than causation.\n:::\n\n\n\n# Question 5 — Curvature in an Enzyme Assay (/18)\n\nThe built-in `DNase` dataset contains optical-density measurements from an assay of deoxyribonuclease. Use only observations from `Run == 1`. Treat `conc` as the predictor and `density` as the response.\n\na. Inspect and plot the relationship. Fit two candidate models for the expected response: the first assumes a constant change in optical density per unit increase in concentration; the second adds the square of concentration as an additional predictor, entered in the original concentration units. Overlay both fitted relationships on the observations and write their equations. **(/6)**\n\nb. Formally determine whether the additional term improves fit sufficiently to retain the more complex candidate. State the hypotheses in terms of that added coefficient and report the comparison statistic, degrees of freedom, and *p*-value. **(/5)**\n\nc. Diagnose the selected model's assumptions and case influence. Interpret the fitted relationship only within the observed concentration range, and use fitted values to quantify the expected optical density at the minimum, median, and maximum observed concentrations. Explain what these estimates reveal about how the response changes across the concentration gradient. **(/7)**\n\n\n\n::: {.callout-tip appearance=\"simple\"}\n## Worked answer — Question 5\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndnase_1 <- as_tibble(DNase) |>\n  filter(Run == 1)\n\nstr(dnase_1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [16 × 3] (S3: tbl_df/tbl/data.frame)\n $ Run    : Ord.factor w/ 11 levels \"10\"<\"11\"<\"9\"<..: 4 4 4 4 4 4 4 4 4 4 ...\n $ conc   : num [1:16] 0.0488 0.0488 0.1953 0.1953 0.3906 ...\n $ density: num [1:16] 0.017 0.018 0.121 0.124 0.206 0.215 0.377 0.374 0.614 0.609 ...\n```\n\n\n:::\n\n```{.r .cell-code}\nrange(dnase_1$conc)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]  0.04882812 12.50000000\n```\n\n\n:::\n\n```{.r .cell-code}\nq5_linear <- lm(density ~ conc, data = dnase_1)\nq5_quadratic <- lm(density ~ conc + I(conc^2), data = dnase_1)\n\nq5_grid <- tibble(\n  conc = seq(min(dnase_1$conc), max(dnase_1$conc), length.out = 200)\n) |>\n  mutate(\n    linear = predict(q5_linear, newdata = pick(everything())),\n    quadratic = predict(q5_quadratic, newdata = pick(everything()))\n  ) |>\n  pivot_longer(c(linear, quadratic), names_to = \"model\", values_to = \"density\")\n\nggplot(dnase_1, aes(conc, density)) +\n  geom_point(size = 2.5) +\n  geom_line(\n    data = q5_grid,\n    aes(colour = model),\n    linewidth = 1\n  ) +\n  labs(\n    x = \"DNase concentration\",\n    y = \"Optical density\",\n    colour = \"Model\"\n  )\n```\n\n::: {.cell-output-display}\n![](BCB744_Biostatistics_Practical_Assessment_2026_V2_files/figure-html/q5-data-models-1.svg)\n:::\n:::\n\n\nThe two fitted candidate equations are\n\n$$\n\\widehat{\\text{density}} =\n0.2597 +\n0.1344(\\text{conc})\n$$\n\nand\n\n$$\n\\widehat{\\text{density}} =\n0.0942 +\n0.308(\\text{conc})\n-\n0.0144(\\text{conc}^2).\n$$\n\nThe nested hypotheses are $H_0:\\beta_2=0$ (the straight line is adequate) and $H_A:\\beta_2\\ne0$ (the quadratic term improves fit).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(q5_linear, q5_quadratic)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nModel 1: density ~ conc\nModel 2: density ~ conc + I(conc^2)\n  Res.Df     RSS Df Sum of Sq      F    Pr(>F)    \n1     14 0.67824                                  \n2     13 0.07680  1   0.60144 101.81 1.622e-07 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(q5_quadratic)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = density ~ conc + I(conc^2), data = dnase_1)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-0.124207 -0.047433  0.006407  0.055317  0.102491 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  0.094221   0.029249   3.221  0.00669 ** \nconc         0.308026   0.017854  17.252 2.43e-10 ***\nI(conc^2)   -0.014366   0.001424 -10.090 1.62e-07 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.07686 on 13 degrees of freedom\nMultiple R-squared:  0.9858,\tAdjusted R-squared:  0.9836 \nF-statistic: 451.5 on 2 and 13 DF,  p-value: 9.728e-13\n```\n\n\n:::\n:::\n\n\nThe nested-model *F*-test provides evidence that the quadratic term improves fit if its *p*-value is below 0.05. The comparison must be made between models fitted to exactly the same observations.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(2, 2))\nplot(q5_quadratic)\n```\n\n::: {.cell-output-display}\n![](BCB744_Biostatistics_Practical_Assessment_2026_V2_files/figure-html/q5-diagnostics-1.svg)\n:::\n\n```{.r .cell-code}\npar(mfrow = c(1, 1))\n\nq5_prediction_points <- tibble(\n  conc = c(\n    min(dnase_1$conc),\n    median(dnase_1$conc),\n    max(dnase_1$conc)\n  ),\n  position = c(\"Minimum\", \"Median\", \"Maximum\")\n) |>\n  mutate(\n    fitted_density = predict(q5_quadratic, newdata = pick(conc))\n  ) |>\n  dplyr::select(position, conc, fitted_density)\n\nq5_prediction_points\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  position    conc fitted_density\n  <chr>      <dbl>          <dbl>\n1 Minimum   0.0488          0.109\n2 Median    1.17            0.435\n3 Maximum  12.5             1.70 \n```\n\n\n:::\n:::\n\n\nThe selected model describes a curved increase in optical density over the measured concentration range. The fitted values at the minimum, median, and maximum concentrations quantify the response on the scale of the assay. Their successive changes show that optical density increases rapidly over part of the gradient but that the increase is not constant across the full range. These predictions are interpolations supported by the observed concentrations; the fitted equation should not be used to infer behaviour beyond that range. The diagnostic plots determine whether the additional term has adequately removed systematic curvature without introducing serious variance, normality, or influence problems.\n:::\n\n\n\n# Question 6 — Sex, Body Mass, and Heart Mass in Cats (/24)\n\nThe `cats` dataset in **MASS** contains sex (`Sex`), body mass (`Bwt`, kg), and heart mass (`Hwt`, g) for 144 adult cats.\n\na. Inspect the data and use a scatter plot, group-specific fitted lines, and concise summaries to explore how heart mass varies with body mass and sex. **(/5)**\n\nb. Fit a model that estimates the partial association of body mass and sex with heart mass, initially assuming that the body-mass association has the same slope in both sexes. Write the fitted equation, state term-specific hypotheses, identify the reference sex, interpret every coefficient with units, and report coefficient uncertainty and overall model fit. **(/8)**\n\nc. Compare three candidate models: (i) body mass as the sole predictor; (ii) body mass and sex with a common body-mass slope; and (iii) body mass and sex with the body-mass slope allowed to differ between sexes. Use appropriate formal comparisons to determine what additional structure the data support. Explain why insufficient evidence for different slopes is not proof that the population slopes are identical. **(/5)**\n\nd. For the selected model, assess distributional and structural assumptions, quantify whether the predictors contain redundant information, and identify influential observations. Conclude with a concise results paragraph containing the principal estimates and inferential evidence while distinguishing association from causation. **(/6)**\n\n\n\n::: {.callout-tip appearance=\"simple\"}\n## Worked answer — Question 6\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncats_df <- as_tibble(MASS::cats) |>\n  mutate(Sex = relevel(factor(Sex), ref = \"F\"))\n\ncats_df |>\n  summarise(\n    n = n(),\n    mean_bwt = mean(Bwt),\n    sd_bwt = sd(Bwt),\n    mean_hwt = mean(Hwt),\n    sd_hwt = sd(Hwt),\n    .by = Sex\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 6\n  Sex       n mean_bwt sd_bwt mean_hwt sd_hwt\n  <fct> <int>    <dbl>  <dbl>    <dbl>  <dbl>\n1 F        47     2.36  0.274     9.20   1.36\n2 M        97     2.9   0.467    11.3    2.54\n```\n\n\n:::\n\n```{.r .cell-code}\nggplot(cats_df, aes(Bwt, Hwt, colour = Sex)) +\n  geom_point(alpha = 0.75) +\n  geom_smooth(method = \"lm\", se = TRUE) +\n  labs(\n    x = \"Body mass (kg)\",\n    y = \"Heart mass (g)\",\n    colour = \"Sex\"\n  )\n```\n\n::: {.cell-output-display}\n![](BCB744_Biostatistics_Practical_Assessment_2026_V2_files/figure-html/q6-eda-1.svg)\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nq6_body <- lm(Hwt ~ Bwt, data = cats_df)\nq6_additive <- lm(Hwt ~ Bwt + Sex, data = cats_df)\nq6_interaction <- lm(Hwt ~ Bwt * Sex, data = cats_df)\n\nsummary(q6_additive)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Hwt ~ Bwt + Sex, data = cats_df)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3.5833 -0.9700 -0.0948  1.0432  5.1016 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  -0.4149     0.7273  -0.571    0.569    \nBwt           4.0758     0.2948  13.826   <2e-16 ***\nSexM         -0.0821     0.3040  -0.270    0.788    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.457 on 141 degrees of freedom\nMultiple R-squared:  0.6468,\tAdjusted R-squared:  0.6418 \nF-statistic: 129.1 on 2 and 141 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\nconfint(q6_additive)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 2.5 %   97.5 %\n(Intercept) -1.8528230 1.022918\nBwt          3.4929923 4.658546\nSexM        -0.6831776 0.518984\n```\n\n\n:::\n:::\n\n\nBecause female (`F`) is explicitly the reference category:\n\n- The intercept estimates female heart mass at `Bwt = 0` kg. It is required algebraically but is outside the data and has no direct biological meaning.\n- The `Bwt` coefficient is the expected change in heart mass, in grams, per 1 kg increase in body mass, holding sex constant.\n- The `SexM` coefficient is the adjusted mean difference in heart mass between males and females of the same body mass.\n\nThe term-specific null hypotheses are $H_0:\\beta_1=0$ and $H_0:\\beta_2=0$, each against a two-sided non-zero alternative. Coefficient confidence intervals convey the precision of the estimates, while adjusted $R^2$ summarises the proportion of variability explained with a penalty for model size.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nq6_compare_sex <- anova(q6_body, q6_additive)\nq6_compare_interaction <- anova(q6_additive, q6_interaction)\n\nq6_compare_sex\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nModel 1: Hwt ~ Bwt\nModel 2: Hwt ~ Bwt + Sex\n  Res.Df    RSS Df Sum of Sq      F Pr(>F)\n1    142 299.53                           \n2    141 299.38  1    0.1548 0.0729 0.7875\n```\n\n\n:::\n\n```{.r .cell-code}\nq6_compare_interaction\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nModel 1: Hwt ~ Bwt + Sex\nModel 2: Hwt ~ Bwt * Sex\n  Res.Df    RSS Df Sum of Sq      F  Pr(>F)  \n1    141 299.38                              \n2    140 291.05  1    8.3317 4.0077 0.04722 *\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(q6_interaction)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Hwt ~ Bwt * Sex, data = cats_df)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3.7728 -1.0118 -0.1196  0.9272  4.8646 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   2.9813     1.8428   1.618 0.107960    \nBwt           2.6364     0.7759   3.398 0.000885 ***\nSexM         -4.1654     2.0618  -2.020 0.045258 *  \nBwt:SexM      1.6763     0.8373   2.002 0.047225 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.442 on 140 degrees of freedom\nMultiple R-squared:  0.6566,\tAdjusted R-squared:  0.6493 \nF-statistic: 89.24 on 3 and 140 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\nconfint(q6_interaction)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 2.5 %      97.5 %\n(Intercept) -0.6620801  6.62470490\nBwt          1.1024137  4.17041438\nSexM        -8.2416012 -0.08919944\nBwt:SexM     0.0208271  3.33170228\n```\n\n\n:::\n:::\n\n\nThe first comparison provides insufficient evidence that adding a constant sex difference improves the body-mass-only model. The second comparison does support allowing the body-mass slope to differ by sex. The interaction model is therefore retained. In that model, the `Bwt` coefficient is the female slope, `SexM` is the estimated male–female difference at 0 kg and is not biologically interpretable in isolation, and `Bwt:SexM` is the amount by which the male slope differs from the female slope. The male slope is the sum of the `Bwt` and `Bwt:SexM` coefficients. A non-significant interaction would indicate insufficient evidence of different slopes, not prove exact equality; in these data, however, the interaction comparison is significant at $\\alpha=0.05$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(2, 2))\nplot(q6_interaction)\n```\n\n::: {.cell-output-display}\n![](BCB744_Biostatistics_Practical_Assessment_2026_V2_files/figure-html/q6-diagnostics-1.svg)\n:::\n\n```{.r .cell-code}\npar(mfrow = c(1, 1))\n\n# Compute a variance-inflation factor for every non-intercept model column.\nq6_x <- model.matrix(q6_interaction)[, -1, drop = FALSE]\nq6_vif <- vapply(\n  seq_len(ncol(q6_x)),\n  \\(j) {\n    response <- q6_x[, j]\n    others <- q6_x[, -j, drop = FALSE]\n    1 / (1 - summary(lm(response ~ others))$r.squared)\n  },\n  numeric(1)\n)\nnames(q6_vif) <- colnames(q6_x)\nq6_vif\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      Bwt      SexM  Bwt:SexM \n 9.753216 64.736123 96.871572 \n```\n\n\n:::\n\n```{.r .cell-code}\ncats_df |>\n  mutate(\n    cooks_d = cooks.distance(q6_interaction),\n    leverage = hatvalues(q6_interaction),\n    studentised_residual = rstudent(q6_interaction)\n  ) |>\n  arrange(desc(cooks_d)) |>\n  slice_head(n = 6)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 6\n  Sex     Bwt   Hwt cooks_d leverage studentised_residual\n  <fct> <dbl> <dbl>   <dbl>    <dbl>                <dbl>\n1 M       3.9  20.5  0.186    0.0580                 3.62\n2 F       3    13    0.101    0.140                  1.59\n3 M       3.7  11    0.0759   0.0408                -2.73\n4 M       3.5  17.2  0.0378   0.0275                 2.35\n5 M       3.6  11.8  0.0280   0.0337                -1.81\n6 M       2.1  10.1  0.0265   0.0408                 1.59\n```\n\n\n:::\n\n```{.r .cell-code}\n4 / nrow(cats_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.02777778\n```\n\n\n:::\n:::\n\n\nThe residual plots assess linearity, constant variance, normality, and influence. Variance-inflation factors quantify redundancy among the three model columns. Because an uncentred continuous predictor appears in an interaction, some non-essential inflation is expected; centring body mass would reduce this without changing fitted values or the interaction test. Cook’s distance flags observations for checking and sensitivity analysis, not automatic deletion.\n\nA suitable results paragraph is:\n\n> Heart mass increased with body mass in both sexes, but the fitted association differed between females and males. Adding a constant sex difference to the body-mass-only model did not improve fit ($F_{1,141}$ = 0.07, $p$ = 0.788), whereas allowing the slopes to differ did ($F_{1,140}$ = 4.01, $p$ = 0.0472). In the retained model, the estimated female slope was 2.64 g heart mass per kg body mass and the male slope was 4.31 g kg^-1^. The fitted slope difference was 1.68 g kg^-1^ (95% CI [0.02, 3.33]). The model explained 65.7% of the observed variation in heart mass. These observational data support sex-specific associations between body and heart mass, not a causal effect.\n:::\n\n\n\n# Question 7 — Theophylline Concentration Profiles (/25)\n\nThe built-in `Theoph` dataset contains serum theophylline concentrations (`conc`, mg L^-1^) measured repeatedly over approximately 25 hours after oral administration to 12 subjects. It also records subject body mass (`Wt`, kg), dose (`Dose`, mg kg^-1^), and elapsed time (`Time`, h). The object has a specialised grouped-data class rather than being an ordinary tibble.\n\na. Convert `Theoph` to a plain tibble, convert `Subject` to an unordered factor, and arrange observations by subject and time. Audit the resulting data by reporting its dimensions, missing values, observations per subject, and whether `Wt` and `Dose` remain constant within each subject. Explain why these checks are necessary before calculating subject-level quantities. **(/5)**\n\nb. Create a new dataset containing exactly one row per subject and the following variables:\n\n- body mass and dose;\n- number of concentration measurements;\n- observed peak concentration;\n- time at which the observed peak occurred; and\n- area under the concentration-time curve from the first to last observation, calculated by joining successive observations with straight lines and summing the resulting trapezoid areas.\n\nPresent this dataset as a clearly labelled and appropriately rounded `gt` table. **(/7)**\n\nc. Produce one figure that shows all subject-specific concentration profiles as lines and points. Superimpose a population summary obtained by dividing elapsed time into the intervals 0–0.5, >0.5–1, >1–2, >2–4, >4–8, >8–12, and >12–25 hours, then calculating the median and interquartile range of concentration within each interval. The figure must distinguish individual trajectories from the population summary and have a self-contained caption. **(/6)**\n\nd. Determine whether body mass is associated with the subject-level area under the curve calculated in (b). Produce a labelled EDA figure, select and justify a suitable inferential measure, state the hypotheses, check the relevant assumptions, and report the estimate, 95% confidence interval, test statistic, degrees of freedom, and *p*-value. Interpret the evidence without treating a non-significant result as proof of no association. **(/7)**\n\n\n\n::: {.callout-tip appearance=\"simple\"}\n## Worked answer — Question 7\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntheoph <- as_tibble(datasets::Theoph) |>\n  mutate(Subject = factor(Subject, ordered = FALSE)) |>\n  arrange(Subject, Time)\n\ndim(theoph)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 132   5\n```\n\n\n:::\n\n```{.r .cell-code}\ncolSums(is.na(theoph))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSubject      Wt    Dose    Time    conc \n      0       0       0       0       0 \n```\n\n\n:::\n\n```{.r .cell-code}\nq7_audit <- theoph |>\n  summarise(\n    observations = n(),\n    distinct_weights = n_distinct(Wt),\n    distinct_doses = n_distinct(Dose),\n    .by = Subject\n  )\n\nq7_audit\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 12 × 4\n   Subject observations distinct_weights distinct_doses\n   <fct>          <int>            <int>          <int>\n 1 6                 11                1              1\n 2 7                 11                1              1\n 3 8                 11                1              1\n 4 11                11                1              1\n 5 3                 11                1              1\n 6 2                 11                1              1\n 7 4                 11                1              1\n 8 9                 11                1              1\n 9 12                11                1              1\n10 10                11                1              1\n11 1                 11                1              1\n12 5                 11                1              1\n```\n\n\n:::\n:::\n\n\nThe data contain 132 observations from 12 subjects, with 11 observations per subject and no missing values. Each subject has one recorded body mass and one dose. Confirming ordering and within-subject constancy is essential because peak timing and trapezoid areas depend on the temporal sequence, while subject-level attributes must not be accidentally averaged across inconsistent values.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntheoph_subject <- theoph |>\n  summarise(\n    Wt = first(Wt),\n    Dose = first(Dose),\n    n_measurements = n(),\n    peak_conc = max(conc),\n    time_to_peak = Time[which.max(conc)],\n    auc = sum(\n      diff(Time) * (head(conc, -1) + tail(conc, -1)) / 2\n    ),\n    .by = Subject\n  )\n\ntheoph_subject |>\n  gt::gt(rowname_col = \"Subject\") |>\n  gt::tab_header(\n    title = \"Subject-level theophylline summaries\",\n    subtitle = \"Observed concentrations over the sampled 24-hour period\"\n  ) |>\n  gt::cols_label(\n    Wt = \"Body mass (kg)\",\n    Dose = \"Dose (mg kg⁻¹)\",\n    n_measurements = \"Measurements\",\n    peak_conc = \"Peak concentration (mg L⁻¹)\",\n    time_to_peak = \"Time to peak (h)\",\n    auc = \"AUC (mg h L⁻¹)\"\n  ) |>\n  gt::fmt_number(\n    columns = c(Wt, Dose, peak_conc, time_to_peak, auc),\n    decimals = 2\n  )\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"hsvhtlsxxr\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#hsvhtlsxxr table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#hsvhtlsxxr thead, #hsvhtlsxxr tbody, #hsvhtlsxxr tfoot, #hsvhtlsxxr tr, #hsvhtlsxxr td, #hsvhtlsxxr th {\n  border-style: none;\n}\n\n#hsvhtlsxxr p {\n  margin: 0;\n  padding: 0;\n}\n\n#hsvhtlsxxr .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#hsvhtlsxxr .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#hsvhtlsxxr .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#hsvhtlsxxr .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#hsvhtlsxxr .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#hsvhtlsxxr .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hsvhtlsxxr .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#hsvhtlsxxr .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#hsvhtlsxxr .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#hsvhtlsxxr .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#hsvhtlsxxr .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#hsvhtlsxxr .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#hsvhtlsxxr .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#hsvhtlsxxr .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#hsvhtlsxxr .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#hsvhtlsxxr .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#hsvhtlsxxr .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#hsvhtlsxxr .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#hsvhtlsxxr .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hsvhtlsxxr .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#hsvhtlsxxr .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#hsvhtlsxxr .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#hsvhtlsxxr .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hsvhtlsxxr .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#hsvhtlsxxr .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#hsvhtlsxxr .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hsvhtlsxxr .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hsvhtlsxxr .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#hsvhtlsxxr .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hsvhtlsxxr .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#hsvhtlsxxr .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hsvhtlsxxr .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#hsvhtlsxxr .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hsvhtlsxxr .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#hsvhtlsxxr .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hsvhtlsxxr .gt_left {\n  text-align: left;\n}\n\n#hsvhtlsxxr .gt_center {\n  text-align: center;\n}\n\n#hsvhtlsxxr .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#hsvhtlsxxr .gt_font_normal {\n  font-weight: normal;\n}\n\n#hsvhtlsxxr .gt_font_bold {\n  font-weight: bold;\n}\n\n#hsvhtlsxxr .gt_font_italic {\n  font-style: italic;\n}\n\n#hsvhtlsxxr .gt_super {\n  font-size: 65%;\n}\n\n#hsvhtlsxxr .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#hsvhtlsxxr .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#hsvhtlsxxr .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#hsvhtlsxxr .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#hsvhtlsxxr .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#hsvhtlsxxr .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#hsvhtlsxxr .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#hsvhtlsxxr .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#hsvhtlsxxr div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"7\" class=\"gt_heading gt_title gt_font_normal\" style>Subject-level theophylline summaries</td>\n    </tr>\n    <tr class=\"gt_heading\">\n      <td colspan=\"7\" class=\"gt_heading gt_subtitle gt_font_normal gt_bottom_border\" style>Observed concentrations over the sampled 24-hour period</td>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"a::stub\"></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Wt\">Body mass (kg)</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Dose\">Dose (mg kg⁻¹)</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"n_measurements\">Measurements</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"peak_conc\">Peak concentration (mg L⁻¹)</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"time_to_peak\">Time to peak (h)</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"auc\">AUC (mg h L⁻¹)</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><th id=\"stub_1_1\" scope=\"row\" class=\"gt_row gt_right gt_stub\">6</th>\n<td headers=\"stub_1_1 Wt\" class=\"gt_row gt_right\">80.00</td>\n<td headers=\"stub_1_1 Dose\" class=\"gt_row gt_right\">4.00</td>\n<td headers=\"stub_1_1 n_measurements\" class=\"gt_row gt_right\">11</td>\n<td headers=\"stub_1_1 peak_conc\" class=\"gt_row gt_right\">6.44</td>\n<td headers=\"stub_1_1 time_to_peak\" class=\"gt_row gt_right\">1.15</td>\n<td headers=\"stub_1_1 auc\" class=\"gt_row gt_right\">73.78</td></tr>\n    <tr><th id=\"stub_1_2\" scope=\"row\" class=\"gt_row gt_right gt_stub\">7</th>\n<td headers=\"stub_1_2 Wt\" class=\"gt_row gt_right\">64.60</td>\n<td headers=\"stub_1_2 Dose\" class=\"gt_row gt_right\">4.95</td>\n<td headers=\"stub_1_2 n_measurements\" class=\"gt_row gt_right\">11</td>\n<td headers=\"stub_1_2 peak_conc\" class=\"gt_row gt_right\">7.09</td>\n<td headers=\"stub_1_2 time_to_peak\" class=\"gt_row gt_right\">3.48</td>\n<td headers=\"stub_1_2 auc\" class=\"gt_row gt_right\">90.75</td></tr>\n    <tr><th id=\"stub_1_3\" scope=\"row\" class=\"gt_row gt_right gt_stub\">8</th>\n<td headers=\"stub_1_3 Wt\" class=\"gt_row gt_right\">70.50</td>\n<td headers=\"stub_1_3 Dose\" class=\"gt_row gt_right\">4.53</td>\n<td headers=\"stub_1_3 n_measurements\" class=\"gt_row gt_right\">11</td>\n<td headers=\"stub_1_3 peak_conc\" class=\"gt_row gt_right\">7.56</td>\n<td headers=\"stub_1_3 time_to_peak\" class=\"gt_row gt_right\">2.02</td>\n<td headers=\"stub_1_3 auc\" class=\"gt_row gt_right\">88.56</td></tr>\n    <tr><th id=\"stub_1_4\" scope=\"row\" class=\"gt_row gt_right gt_stub\">11</th>\n<td headers=\"stub_1_4 Wt\" class=\"gt_row gt_right\">65.00</td>\n<td headers=\"stub_1_4 Dose\" class=\"gt_row gt_right\">4.92</td>\n<td headers=\"stub_1_4 n_measurements\" class=\"gt_row gt_right\">11</td>\n<td headers=\"stub_1_4 peak_conc\" class=\"gt_row gt_right\">8.00</td>\n<td headers=\"stub_1_4 time_to_peak\" class=\"gt_row gt_right\">0.98</td>\n<td headers=\"stub_1_4 auc\" class=\"gt_row gt_right\">80.09</td></tr>\n    <tr><th id=\"stub_1_5\" scope=\"row\" class=\"gt_row gt_right gt_stub\">3</th>\n<td headers=\"stub_1_5 Wt\" class=\"gt_row gt_right\">70.50</td>\n<td headers=\"stub_1_5 Dose\" class=\"gt_row gt_right\">4.53</td>\n<td headers=\"stub_1_5 n_measurements\" class=\"gt_row gt_right\">11</td>\n<td headers=\"stub_1_5 peak_conc\" class=\"gt_row gt_right\">8.20</td>\n<td headers=\"stub_1_5 time_to_peak\" class=\"gt_row gt_right\">1.02</td>\n<td headers=\"stub_1_5 auc\" class=\"gt_row gt_right\">99.29</td></tr>\n    <tr><th id=\"stub_1_6\" scope=\"row\" class=\"gt_row gt_right gt_stub\">2</th>\n<td headers=\"stub_1_6 Wt\" class=\"gt_row gt_right\">72.40</td>\n<td headers=\"stub_1_6 Dose\" class=\"gt_row gt_right\">4.40</td>\n<td headers=\"stub_1_6 n_measurements\" class=\"gt_row gt_right\">11</td>\n<td headers=\"stub_1_6 peak_conc\" class=\"gt_row gt_right\">8.33</td>\n<td headers=\"stub_1_6 time_to_peak\" class=\"gt_row gt_right\">1.92</td>\n<td headers=\"stub_1_6 auc\" class=\"gt_row gt_right\">91.53</td></tr>\n    <tr><th id=\"stub_1_7\" scope=\"row\" class=\"gt_row gt_right gt_stub\">4</th>\n<td headers=\"stub_1_7 Wt\" class=\"gt_row gt_right\">72.70</td>\n<td headers=\"stub_1_7 Dose\" class=\"gt_row gt_right\">4.40</td>\n<td headers=\"stub_1_7 n_measurements\" class=\"gt_row gt_right\">11</td>\n<td headers=\"stub_1_7 peak_conc\" class=\"gt_row gt_right\">8.60</td>\n<td headers=\"stub_1_7 time_to_peak\" class=\"gt_row gt_right\">1.07</td>\n<td headers=\"stub_1_7 auc\" class=\"gt_row gt_right\">106.80</td></tr>\n    <tr><th id=\"stub_1_8\" scope=\"row\" class=\"gt_row gt_right gt_stub\">9</th>\n<td headers=\"stub_1_8 Wt\" class=\"gt_row gt_right\">86.40</td>\n<td headers=\"stub_1_8 Dose\" class=\"gt_row gt_right\">3.10</td>\n<td headers=\"stub_1_8 n_measurements\" class=\"gt_row gt_right\">11</td>\n<td headers=\"stub_1_8 peak_conc\" class=\"gt_row gt_right\">9.03</td>\n<td headers=\"stub_1_8 time_to_peak\" class=\"gt_row gt_right\">0.63</td>\n<td headers=\"stub_1_8 auc\" class=\"gt_row gt_right\">86.33</td></tr>\n    <tr><th id=\"stub_1_9\" scope=\"row\" class=\"gt_row gt_right gt_stub\">12</th>\n<td headers=\"stub_1_9 Wt\" class=\"gt_row gt_right\">60.50</td>\n<td headers=\"stub_1_9 Dose\" class=\"gt_row gt_right\">5.30</td>\n<td headers=\"stub_1_9 n_measurements\" class=\"gt_row gt_right\">11</td>\n<td headers=\"stub_1_9 peak_conc\" class=\"gt_row gt_right\">9.75</td>\n<td headers=\"stub_1_9 time_to_peak\" class=\"gt_row gt_right\">3.52</td>\n<td headers=\"stub_1_9 auc\" class=\"gt_row gt_right\">119.98</td></tr>\n    <tr><th id=\"stub_1_10\" scope=\"row\" class=\"gt_row gt_right gt_stub\">10</th>\n<td headers=\"stub_1_10 Wt\" class=\"gt_row gt_right\">58.20</td>\n<td headers=\"stub_1_10 Dose\" class=\"gt_row gt_right\">5.50</td>\n<td headers=\"stub_1_10 n_measurements\" class=\"gt_row gt_right\">11</td>\n<td headers=\"stub_1_10 peak_conc\" class=\"gt_row gt_right\">10.21</td>\n<td headers=\"stub_1_10 time_to_peak\" class=\"gt_row gt_right\">3.55</td>\n<td headers=\"stub_1_10 auc\" class=\"gt_row gt_right\">138.37</td></tr>\n    <tr><th id=\"stub_1_11\" scope=\"row\" class=\"gt_row gt_right gt_stub\">1</th>\n<td headers=\"stub_1_11 Wt\" class=\"gt_row gt_right\">79.60</td>\n<td headers=\"stub_1_11 Dose\" class=\"gt_row gt_right\">4.02</td>\n<td headers=\"stub_1_11 n_measurements\" class=\"gt_row gt_right\">11</td>\n<td headers=\"stub_1_11 peak_conc\" class=\"gt_row gt_right\">10.50</td>\n<td headers=\"stub_1_11 time_to_peak\" class=\"gt_row gt_right\">1.12</td>\n<td headers=\"stub_1_11 auc\" class=\"gt_row gt_right\">148.92</td></tr>\n    <tr><th id=\"stub_1_12\" scope=\"row\" class=\"gt_row gt_right gt_stub\">5</th>\n<td headers=\"stub_1_12 Wt\" class=\"gt_row gt_right\">54.60</td>\n<td headers=\"stub_1_12 Dose\" class=\"gt_row gt_right\">5.86</td>\n<td headers=\"stub_1_12 n_measurements\" class=\"gt_row gt_right\">11</td>\n<td headers=\"stub_1_12 peak_conc\" class=\"gt_row gt_right\">11.40</td>\n<td headers=\"stub_1_12 time_to_peak\" class=\"gt_row gt_right\">1.00</td>\n<td headers=\"stub_1_12 auc\" class=\"gt_row gt_right\">121.29</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\nFor successive observations $(t_i,c_i)$ and $(t_{i+1},c_{i+1})$, the trapezoid contribution is\n\n$$\n(t_{i+1}-t_i)\\frac{c_i+c_{i+1}}{2}.\n$$\n\nSumming these contributions produces one observed area under the concentration-time curve for each subject.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nq7_breaks <- c(0, 0.5, 1, 2, 4, 8, 12, 25)\n\ntheoph_binned <- theoph |>\n  mutate(\n    time_interval = cut(\n      Time,\n      breaks = q7_breaks,\n      include.lowest = TRUE,\n      right = TRUE\n    )\n  )\n\ntheoph_population <- theoph_binned |>\n  filter(!is.na(time_interval)) |>\n  summarise(\n    plot_time = median(Time),\n    median_conc = median(conc),\n    q1_conc = quantile(conc, 0.25),\n    q3_conc = quantile(conc, 0.75),\n    .by = time_interval\n  ) |>\n  arrange(plot_time)\n\nggplot(theoph, aes(Time, conc, group = Subject, colour = Subject)) +\n  geom_line(alpha = 0.55, linewidth = 0.6) +\n  geom_point(alpha = 0.7, size = 1.5) +\n  geom_ribbon(\n    data = theoph_population,\n    aes(\n      x = plot_time,\n      ymin = q1_conc,\n      ymax = q3_conc,\n      group = 1\n    ),\n    inherit.aes = FALSE,\n    fill = \"grey55\",\n    alpha = 0.25\n  ) +\n  geom_line(\n    data = theoph_population,\n    aes(x = plot_time, y = median_conc, group = 1),\n    inherit.aes = FALSE,\n    colour = \"black\",\n    linewidth = 1.2\n  ) +\n  geom_point(\n    data = theoph_population,\n    aes(x = plot_time, y = median_conc),\n    inherit.aes = FALSE,\n    colour = \"black\",\n    size = 2.4\n  ) +\n  guides(colour = guide_legend(ncol = 2)) +\n  labs(\n    x = \"Time since administration (h)\",\n    y = expression(\"Serum theophylline concentration (mg L\"^-1 * \")\"),\n    colour = \"Subject\"\n  )\n```\n\n::: {.cell-output-display}\n![Serum theophylline concentration over time for 12 subjects. Thin coloured lines and points show individual profiles. The black line shows median concentration within seven elapsed-time intervals, and the grey band spans the corresponding interquartile range.](BCB744_Biostatistics_Practical_Assessment_2026_V2_files/figure-html/q7-profile-figure-1.svg)\n:::\n:::\n\n\nThe individual trajectories show rapid uptake followed by a slower decline, with appreciable subject-to-subject differences in peak height, peak timing, and persistence. The binned median and IQR summarise the common temporal pattern without hiding individual profiles.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(theoph_subject, aes(Wt, auc, label = Subject)) +\n  geom_point(size = 2.5, colour = \"#2C7FB8\") +\n  geom_smooth(method = \"lm\", se = TRUE, colour = \"#CB181D\") +\n  geom_text(nudge_y = 3, check_overlap = TRUE, size = 3) +\n  labs(\n    x = \"Body mass (kg)\",\n    y = expression(\"Observed AUC (mg h L\"^-1 * \")\")\n  )\n```\n\n::: {.cell-output-display}\n![Association between body mass and the observed area under the serum theophylline concentration-time curve. Labels identify subjects.](BCB744_Biostatistics_Practical_Assessment_2026_V2_files/figure-html/q7-association-1.svg)\n:::\n\n```{.r .cell-code}\nshapiro.test(theoph_subject$Wt)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  theoph_subject$Wt\nW = 0.9742, p-value = 0.9495\n```\n\n\n:::\n\n```{.r .cell-code}\nshapiro.test(theoph_subject$auc)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  theoph_subject$auc\nW = 0.92514, p-value = 0.3314\n```\n\n\n:::\n\n```{.r .cell-code}\nq7_cor <- cor.test(\n  theoph_subject$Wt,\n  theoph_subject$auc,\n  method = \"pearson\"\n)\nq7_cor\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's product-moment correlation\n\ndata:  theoph_subject$Wt and theoph_subject$auc\nt = -1.1225, df = 10, p-value = 0.2879\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n -0.7621143  0.2962494\nsample estimates:\n      cor \n-0.334528 \n```\n\n\n:::\n:::\n\n\nThe subject is the independent observational unit. The hypotheses are $H_0:\\rho=0$ and $H_A:\\rho\\ne0$. The scatter plot is reasonably compatible with a straight-line association, neither variable shows strong evidence against normality, and no single point obviously determines the pattern, so Pearson's correlation is defensible. The estimated association is moderate and negative, but its confidence interval spans both substantial negative and modest positive values ($r$ = -0.335, 95% CI [-0.762, 0.296], $t_{10}$ = -1.12, $p$ = 0.288). The data therefore do not provide strong evidence of an association, but the small sample and wide interval mean that an association cannot be ruled out.\n:::\n\n\n\n# Question 8 — Exercise and Resting Pulse (/25)\n\nThe `survey` dataset in **MASS** contains questionnaire responses from 237 university students. Relevant variables are sex (`Sex`), exercise frequency (`Exer`), resting pulse rate (`Pulse`, beats min^-1^), and age (`Age`, years). This question compares students who reported exercising frequently with those who reported no exercise; students in the intermediate `\"Some\"` category are outside the target comparison.\n\na. Starting from `MASS::survey`, retain only `Sex`, `Exer`, `Pulse`, and `Age`. Keep the `\"Freq\"` and `\"None\"` exercise categories, remove incomplete rows, and:\n\n- recode exercise as an ordered factor labelled `\"None\"` and `\"Frequently\"`;\n- create age bands `\"16–18\"`, `\"19–21\"`, and `\"22+\"`; and\n- report, in a compact audit, the original number of rows, the number excluded as `\"Some\"`, the number removed for incomplete required values, and the final number analysed.\n\nShow enough checks to demonstrate that the resulting variables and category order are correct. **(/6)**\n\nb. Calculate sample size, mean, median, standard deviation, and IQR of pulse rate for each exercise-by-sex combination. Present the result as a polished `gt` table with units and sensible rounding. **(/5)**\n\nc. Construct one figure comparing the pulse-rate distributions between exercise groups. It must show the distribution shape, a compact quartile summary, individual observations coloured by age band, separate panels for sex, and the mean with a 95% confidence interval. Use position adjustments that keep all layers readable and provide a self-contained caption. **(/7)**\n\nd. Ignoring sex for this specified unadjusted comparison, determine whether mean pulse rate differs between the two exercise groups. State the observational unit and hypotheses, use graphical and formal evidence to assess the relevant assumptions, select and conduct an appropriate analysis, and report the estimated difference with its 95% confidence interval, test statistic, degrees of freedom, and *p*-value. Discuss one reason why this observational comparison should not be interpreted causally. **(/7)**\n\n\n\n::: {.callout-tip appearance=\"simple\"}\n## Worked answer — Question 8\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsurvey_raw <- as_tibble(MASS::survey)\n\nq8_original_n <- nrow(survey_raw)\nq8_some_n <- sum(survey_raw$Exer == \"Some\", na.rm = TRUE)\n\nsurvey_target <- survey_raw |>\n  dplyr::select(Sex, Exer, Pulse, Age) |>\n  filter(Exer %in% c(\"Freq\", \"None\"))\n\nq8_incomplete_n <- sum(!complete.cases(survey_target))\n\nsurvey_clean <- survey_target |>\n  drop_na() |>\n  mutate(\n    exercise = factor(\n      Exer,\n      levels = c(\"None\", \"Freq\"),\n      labels = c(\"None\", \"Frequently\"),\n      ordered = TRUE\n    ),\n    age_band = cut(\n      Age,\n      breaks = c(-Inf, 19, 22, Inf),\n      right = FALSE,\n      labels = c(\"16–18\", \"19–21\", \"22+\")\n    )\n  ) |>\n  dplyr::select(-Exer)\n\ntibble(\n  stage = c(\n    \"Original rows\",\n    \"Excluded: Some exercise\",\n    \"Removed: incomplete required values\",\n    \"Final analysed rows\"\n  ),\n  n = c(\n    q8_original_n,\n    q8_some_n,\n    q8_incomplete_n,\n    nrow(survey_clean)\n  )\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 2\n  stage                                   n\n  <chr>                               <int>\n1 Original rows                         237\n2 Excluded: Some exercise                98\n3 Removed: incomplete required values    28\n4 Final analysed rows                   111\n```\n\n\n:::\n\n```{.r .cell-code}\nstr(survey_clean)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [111 × 5] (S3: tbl_df/tbl/data.frame)\n $ Sex     : Factor w/ 2 levels \"Female\",\"Male\": 2 2 2 1 1 2 1 2 2 2 ...\n $ Pulse   : int [1:111] 104 87 83 74 80 68 89 78 72 72 ...\n $ Age     : num [1:111] 17.6 16.9 18.8 35.8 28.5 ...\n $ exercise: Ord.factor w/ 2 levels \"None\"<\"Frequently\": 1 1 2 2 2 2 2 2 2 2 ...\n $ age_band: Factor w/ 3 levels \"16–18\",\"19–21\",..: 1 1 1 3 3 1 2 1 1 1 ...\n```\n\n\n:::\n\n```{.r .cell-code}\ncount(survey_clean, exercise, Sex, age_band)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 12 × 4\n   exercise   Sex    age_band     n\n   <ord>      <fct>  <fct>    <int>\n 1 None       Female 16–18        3\n 2 None       Female 19–21        2\n 3 None       Female 22+          2\n 4 None       Male   16–18        7\n 5 None       Male   19–21        2\n 6 None       Male   22+          1\n 7 Frequently Female 16–18       25\n 8 Frequently Female 19–21        9\n 9 Frequently Female 22+          7\n10 Frequently Male   16–18       29\n11 Frequently Male   19–21       15\n12 Frequently Male   22+          9\n```\n\n\n:::\n:::\n\n\nThe final dataset contains one row per student and explicitly orders the exercise comparison from no exercise to frequent exercise. The audit distinguishes exclusions made by the research question from removals caused by missing required data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsurvey_summary <- survey_clean |>\n  summarise(\n    n = n(),\n    mean = mean(Pulse),\n    median = median(Pulse),\n    sd = sd(Pulse),\n    iqr = IQR(Pulse),\n    .by = c(exercise, Sex)\n  ) |>\n  arrange(exercise, Sex)\n\nsurvey_summary |>\n  gt::gt(groupname_col = \"exercise\", rowname_col = \"Sex\") |>\n  gt::tab_header(\n    title = \"Resting pulse rate by exercise frequency and sex\",\n    subtitle = \"Pulse rate in beats min⁻¹\"\n  ) |>\n  gt::cols_label(\n    n = \"n\",\n    mean = \"Mean\",\n    median = \"Median\",\n    sd = \"SD\",\n    iqr = \"IQR\"\n  ) |>\n  gt::fmt_number(\n    columns = c(mean, median, sd, iqr),\n    decimals = 1\n  )\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"lwabautiqf\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#lwabautiqf table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#lwabautiqf thead, #lwabautiqf tbody, #lwabautiqf tfoot, #lwabautiqf tr, #lwabautiqf td, #lwabautiqf th {\n  border-style: none;\n}\n\n#lwabautiqf p {\n  margin: 0;\n  padding: 0;\n}\n\n#lwabautiqf .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#lwabautiqf .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#lwabautiqf .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#lwabautiqf .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#lwabautiqf .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#lwabautiqf .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#lwabautiqf .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#lwabautiqf .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#lwabautiqf .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#lwabautiqf .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#lwabautiqf .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#lwabautiqf .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#lwabautiqf .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#lwabautiqf .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#lwabautiqf .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#lwabautiqf .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#lwabautiqf .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#lwabautiqf .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#lwabautiqf .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lwabautiqf .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#lwabautiqf .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#lwabautiqf .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#lwabautiqf .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lwabautiqf .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#lwabautiqf .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#lwabautiqf .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#lwabautiqf .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lwabautiqf .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#lwabautiqf .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#lwabautiqf .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#lwabautiqf .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#lwabautiqf .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#lwabautiqf .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lwabautiqf .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#lwabautiqf .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lwabautiqf .gt_left {\n  text-align: left;\n}\n\n#lwabautiqf .gt_center {\n  text-align: center;\n}\n\n#lwabautiqf .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#lwabautiqf .gt_font_normal {\n  font-weight: normal;\n}\n\n#lwabautiqf .gt_font_bold {\n  font-weight: bold;\n}\n\n#lwabautiqf .gt_font_italic {\n  font-style: italic;\n}\n\n#lwabautiqf .gt_super {\n  font-size: 65%;\n}\n\n#lwabautiqf .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#lwabautiqf .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#lwabautiqf .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#lwabautiqf .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#lwabautiqf .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#lwabautiqf .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#lwabautiqf .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#lwabautiqf .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#lwabautiqf div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"6\" class=\"gt_heading gt_title gt_font_normal\" style>Resting pulse rate by exercise frequency and sex</td>\n    </tr>\n    <tr class=\"gt_heading\">\n      <td colspan=\"6\" class=\"gt_heading gt_subtitle gt_font_normal gt_bottom_border\" style>Pulse rate in beats min⁻¹</td>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"a::stub\"></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"n\">n</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"mean\">Mean</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"median\">Median</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"sd\">SD</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"iqr\">IQR</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr class=\"gt_group_heading_row\">\n      <th colspan=\"6\" class=\"gt_group_heading\" scope=\"colgroup\" id=\"None\">None</th>\n    </tr>\n    <tr class=\"gt_row_group_first\"><th id=\"stub_1_1\" scope=\"row\" class=\"gt_row gt_center gt_stub\">Female</th>\n<td headers=\"None stub_1_1 n\" class=\"gt_row gt_right\">7</td>\n<td headers=\"None stub_1_1 mean\" class=\"gt_row gt_right\">71.4</td>\n<td headers=\"None stub_1_1 median\" class=\"gt_row gt_right\">70.0</td>\n<td headers=\"None stub_1_1 sd\" class=\"gt_row gt_right\">11.4</td>\n<td headers=\"None stub_1_1 iqr\" class=\"gt_row gt_right\">9.0</td></tr>\n    <tr><th id=\"stub_1_2\" scope=\"row\" class=\"gt_row gt_center gt_stub\">Male</th>\n<td headers=\"None stub_1_2 n\" class=\"gt_row gt_right\">10</td>\n<td headers=\"None stub_1_2 mean\" class=\"gt_row gt_right\">80.5</td>\n<td headers=\"None stub_1_2 median\" class=\"gt_row gt_right\">80.0</td>\n<td headers=\"None stub_1_2 sd\" class=\"gt_row gt_right\">15.2</td>\n<td headers=\"None stub_1_2 iqr\" class=\"gt_row gt_right\">25.8</td></tr>\n    <tr class=\"gt_group_heading_row\">\n      <th colspan=\"6\" class=\"gt_group_heading\" scope=\"colgroup\" id=\"Frequently\">Frequently</th>\n    </tr>\n    <tr class=\"gt_row_group_first\"><th id=\"stub_1_3\" scope=\"row\" class=\"gt_row gt_center gt_stub\">Female</th>\n<td headers=\"Frequently stub_1_3 n\" class=\"gt_row gt_right\">41</td>\n<td headers=\"Frequently stub_1_3 mean\" class=\"gt_row gt_right\">73.6</td>\n<td headers=\"Frequently stub_1_3 median\" class=\"gt_row gt_right\">72.0</td>\n<td headers=\"Frequently stub_1_3 sd\" class=\"gt_row gt_right\">12.5</td>\n<td headers=\"Frequently stub_1_3 iqr\" class=\"gt_row gt_right\">12.0</td></tr>\n    <tr><th id=\"stub_1_4\" scope=\"row\" class=\"gt_row gt_center gt_stub\">Male</th>\n<td headers=\"Frequently stub_1_4 n\" class=\"gt_row gt_right\">53</td>\n<td headers=\"Frequently stub_1_4 mean\" class=\"gt_row gt_right\">70.7</td>\n<td headers=\"Frequently stub_1_4 median\" class=\"gt_row gt_right\">70.0</td>\n<td headers=\"Frequently stub_1_4 sd\" class=\"gt_row gt_right\">9.6</td>\n<td headers=\"Frequently stub_1_4 iqr\" class=\"gt_row gt_right\">12.0</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(\n  survey_clean,\n  aes(exercise, Pulse, fill = exercise)\n) +\n  geom_violin(\n    trim = FALSE,\n    alpha = 0.22,\n    colour = \"grey35\",\n    show.legend = FALSE\n  ) +\n  geom_boxplot(\n    width = 0.16,\n    outlier.shape = NA,\n    alpha = 0.45,\n    show.legend = FALSE\n  ) +\n  geom_jitter(\n    aes(colour = age_band),\n    width = 0.10,\n    height = 0,\n    alpha = 0.75,\n    size = 1.8\n  ) +\n  stat_summary(\n    fun.data = mean_cl_normal,\n    geom = \"pointrange\",\n    colour = \"black\",\n    linewidth = 0.7\n  ) +\n  facet_wrap(~Sex) +\n  labs(\n    x = \"Exercise frequency\",\n    y = expression(\"Resting pulse rate (beats min\"^-1 * \")\"),\n    colour = \"Age band\"\n  )\n```\n\n::: {.cell-output-display}\n![Resting pulse-rate distributions among students reporting no exercise or frequent exercise, shown separately by sex. Violins show distribution shape, internal boxes show medians and quartiles, coloured points are individual students classified by age band, and black points and intervals show means and 95% confidence intervals.](BCB744_Biostatistics_Practical_Assessment_2026_V2_files/figure-html/q8-figure-1.svg)\n:::\n:::\n\n\nThe figure preserves the raw observations and distribution shapes while also showing quartiles and uncertainty around each mean. The unequal group sizes remain visible rather than being concealed by bars.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(survey_clean, aes(sample = Pulse)) +\n  stat_qq() +\n  stat_qq_line() +\n  facet_wrap(~exercise) +\n  labs(x = \"Theoretical quantiles\", y = \"Observed pulse-rate quantiles\")\n```\n\n::: {.cell-output-display}\n![](BCB744_Biostatistics_Practical_Assessment_2026_V2_files/figure-html/q8-inference-1.svg)\n:::\n\n```{.r .cell-code}\nsurvey_clean |>\n  summarise(\n    shapiro_w = unname(shapiro.test(Pulse)$statistic),\n    p_value = shapiro.test(Pulse)$p.value,\n    variance = var(Pulse),\n    .by = exercise\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 4\n  exercise   shapiro_w p_value variance\n  <ord>          <dbl>   <dbl>    <dbl>\n1 None           0.971   0.831     200.\n2 Frequently     0.978   0.107     121.\n```\n\n\n:::\n\n```{.r .cell-code}\nq8_test <- t.test(Pulse ~ exercise, data = survey_clean, var.equal = FALSE)\nq8_test\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  Pulse by exercise\nt = 1.3306, df = 19.642, p-value = 0.1986\nalternative hypothesis: true difference in means between group None and group Frequently is not equal to 0\n95 percent confidence interval:\n -2.737842 12.352361\nsample estimates:\n      mean in group None mean in group Frequently \n                76.76471                 71.95745 \n```\n\n\n:::\n:::\n\n\nThe student is the observational unit. With the factor ordered as `\"None\"` then `\"Frequently\"`, the estimated contrast is mean pulse in the no-exercise group minus mean pulse in the frequent-exercise group. The hypotheses are $H_0:\\mu_{\\text{None}}-\\mu_{\\text{Frequently}}=0$ and $H_A:\\mu_{\\text{None}}-\\mu_{\\text{Frequently}}\\ne0$. The Q-Q plots and within-group tests do not show strong departures from normality. Welch's two-sample procedure is a cautious choice because it does not require equal population variances and accommodates the unequal sample sizes.\n\nThe estimated difference is 4.81 beats min^-1^, with a 95% confidence interval from -2.74 to 12.35 beats min^-1^ ($t_{19.64}$ = 1.33, $p$ = 0.199). The interval includes zero, so the data do not provide strong evidence of a mean difference. This does not demonstrate equal population means. Exercise was self-reported rather than experimentally assigned, and the groups may differ in sex, age, health, medication, fitness, or other factors; the result therefore cannot be interpreted as a causal effect of exercise.\n:::\n\n\n\n\n\n# Coverage and marking map\n\n| Question | Main assessed work | Chapters | Marks |\n|---|---|---:|---:|\n| 1 | Data structure, descriptive statistics, visualisation, distributions, transformation, sampling uncertainty, EDA | 1–6 | 20 |\n| 2 | Hypotheses, assumptions, paired *t*-test, estimation and interpretation | 5–7, 10 | 16 |\n| 3 | Group EDA, one-way ANOVA alternatives, residual diagnostics, multiplicity-controlled comparisons | 5–6, 8, 10–11 | 20 |\n| 4 | Correlation, simple regression, diagnostics, confidence and prediction intervals | 9, 11–12 | 22 |\n| 5 | Linear versus polynomial regression, nested comparison, diagnostics and bounded interpretation | 11, 13 | 18 |\n| 6 | Multiple regression, categorical predictors, nested models, diagnostics, collinearity and influence | 11, 14 | 24 |\n| 7 | Longitudinal-data wrangling, subject-level integration, layered visualisation, association | 2–5, 9–10 | 25 |\n| 8 | Filtering, recoding, grouped summaries, layered faceted visualisation, two-group inference | 2–3, 5–7, 10 | 25 |\n| **Total** |  | **1–14** | **170** |\n\n\n",
    "supporting": [
      "BCB744_Biostatistics_Practical_Assessment_2026_V2_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}