---
date: "2024-06-25"
title: "Multiple Linear Regression (MLR)"
---

::: callout-tip
## **Material required for this chapter**

| Type           | Name                                     | Link                                                                              |
|----------------|------------------------------------------|-----------------------------------------------------------------------------------|
| **Theory**     | The Biostatistics Book                   | [Chapter 5](../docs/The-Biostatistics-Book-Ch-3-5.pdf)                                                                         |
| **Slides**     | None                                     |                                                                                   |
| **Data**       | The seaweed data                         | [💾 `Seaweed data ZIP`](../data/seaweed/seaweed.zip)                                  |
:::

::: {.callout-important appearance="simple"}
## Tasks to complete in this Chapter

* [Task G 1--5](assessments/Task_G.qmd)

When embarking in Task G, please refer to some musings in the chapter about [Model Building](model_building.qmd).
:::

## About the Data

Load some data produced in the analysis by @smit2017seaweeds. Please refer to the chapter [Deep Dive into Gradients](deep_dive.qmd) for the data description. Also refer to chapter [Seaweeds in Two Oceans: Beta-Diversity (Appendices)](Seaweed_in_Two_Oceans_v2/two_oceans_appendices.qmd).

This dataset is suitable for a multiple linear regression because it has continuous response variables ($\beta_\text{sør}$, $\beta_\text{sim}$, and $\beta_\text{sne}$, the Sørenesen dissimilarity, the turnover component of $\beta$-diversity, and the nestedness-resultant component of $\beta$-diversity, respectively), continuous predictor variables (the mean climatological temperature for August, the mean climatological temperature for the year, the temperature range for February and August, and the SD of February and August), and a categorial variable (the bioregional classification of the samples).

```{r}
seaweed <- read.csv("../data/seaweed/spp_df2.csv")
rbind(head(seaweed, 3), tail(seaweed, 3))[,-1]
```

Not much here. Please refer to the chapter referenced above.
