#!/usr/bin/env python3
"""Generate and optionally render the BCB744 biostatistics PDF book project."""

from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys
from pathlib import Path


BOOK_DIR = Path(__file__).resolve().parent
CHAPTER_DIR = BOOK_DIR.parent
REPO_ROOT = BOOK_DIR.parents[2]
STAGING_DIR = BOOK_DIR / "_staging"
OUTPUT_CONFIG = STAGING_DIR / "_quarto.yml"
OUTPUT_INDEX = STAGING_DIR / "index.qmd"

CHAPTER_PATTERN = re.compile(r"^(?P<num>\d{2})-.*\.qmd$")
TITLE_PREFIX_PATTERN = re.compile(r"^\s*\d+\.\s*")
FENCE_PATTERN = re.compile(r"^(```|~~~)(\{.*\})?\s*$")

PARTS: tuple[tuple[str, range], ...] = (
    ("Part I: Statistical Foundations", range(1, 7)),
    ("Part II: Core Inferential Methods", range(7, 11)),
    ("Part III: Regression and Model Building", range(11, 18)),
    ("Part IV: Advanced Modelling Extensions", range(18, 26)),
    ("Part V: Reproducible Analytical Workflow", range(26, 27)),
)


def discover_chapters() -> list[tuple[int, Path]]:
    chapters: list[tuple[int, Path]] = []
    for path in CHAPTER_DIR.glob("*.qmd"):
        match = CHAPTER_PATTERN.match(path.name)
        if match:
            chapters.append((int(match.group("num")), path))
    chapters.sort(key=lambda item: item[0])
    return chapters


def build_config(chapters: list[tuple[int, Path]]) -> str:
    chapter_lookup = {num: path for num, path in chapters}

    lines = [
        "# Generated by build_biostats_book.py. Do not edit by hand.",
        "project:",
        "  type: book",
        "  output-dir: ../_book",
        "book:",
        '  title: "BCB744 Biostatistics"',
        '  subtitle: "Collected PDF Edition"',
        '  author: "A. J. Smit"',
        '  date: "last-modified"',
        '  output-file: "BCB744_Biostatistics_Book"',
        "  chapters:",
        "    - index.qmd",
    ]

    for part_title, number_range in PARTS:
        lines.extend(
            [
                f'    - part: "{part_title}"',
                "      chapters:",
            ]
        )
        for chapter_num in number_range:
            path = chapter_lookup.get(chapter_num)
            if path is not None:
                lines.append(f"        - BCB744/basic_stats/{path.name}")

    lines.extend(
        [
            "bibliography: references.bib",
            "csl: styles/marine-biology.csl",
            "filters:",
            "  - imagify",
            "crossref:",
            "  chapters: true",
            "execute:",
            "  cache: false",
            "  freeze: false",
            "format:",
            "  html:",
            "    fig-numbering: false",
            "    anchor-sections: true",
            "    number-sections: false",
            "    page-layout: article",
            "    toc: true",
            "  pdf:",
            "    documentclass: book",
            "    include-in-header: BCB744/basic_stats/book/biostats_book_preamble.tex",
            "    citation-location: bottom",
            "    code-blocks:",
            "      break-lines: true",
            "      break-by-word: true",
            '    fontsize: "11pt"',
            "    fig-dpi: 300",
            "    fig-format: pdf",
            "    fig-width: 4.2",
            "    fig-align: center",
            "    fig-numbering: true",
            "    filters:",
            "      - BCB744/basic_stats/book/figure-size-filter.lua",
            "    highlight-style: tango",
            "    indent: false",
            "    keep-tex: false",
            "    latex-tinytex: false",
            "    number-sections: true",
            "    number-depth: 3",
            "    par-skip: 6pt",
            "    pdf-engine: lualatex",
            "    prefer-html: true",
            "    toc: false",
            '    citecolor: "blue"',
            '    linkcolor: "blue"',
            '    filecolor: "blue"',
            '    urlcolor: "blue"',
            '    toccolor: "blue"',
            "",
        ]
    )

    return "\n".join(lines)


def write_config(text: str) -> None:
    OUTPUT_CONFIG.write_text(text, encoding="utf-8")


def ensure_symlink(target: Path, link_path: Path) -> None:
    if link_path.exists() or link_path.is_symlink():
        if link_path.is_dir() and not link_path.is_symlink():
            shutil.rmtree(link_path)
        else:
            link_path.unlink()

    link_path.parent.mkdir(parents=True, exist_ok=True)
    link_path.symlink_to(target)


def copy_qmd_with_pdf_override(source: Path, destination: Path) -> None:
    text = source.read_text(encoding="utf-8")
    lines = text.splitlines()

    if lines and lines[0].strip() == "---":
        try:
            closing_index = lines[1:].index("---") + 1
        except ValueError:
            closing_index = -1

        if closing_index != -1:
            front_matter = [
                normalize_front_matter_line(line)
                for line in lines[1:closing_index]
                if not line.strip().startswith("prefer-html:")
                and not line.strip().startswith("always_allow_html:")
            ]
            body = rewrite_book_body(lines[closing_index + 1 :])
            front_matter.extend(
                [
                    "prefer-html: true",
                    "always_allow_html: true",
                ]
            )
            text = "\n".join(["---", *front_matter, "---", *body]) + "\n"
        else:
            shifted_body = "\n".join(rewrite_book_body(lines))
            text = f"---\nprefer-html: true\nalways_allow_html: true\n---\n\n{shifted_body}\n"
    else:
        shifted_body = "\n".join(rewrite_book_body(lines))
        text = f"---\nprefer-html: true\nalways_allow_html: true\n---\n\n{shifted_body}\n"

    destination.write_text(text, encoding="utf-8")


def rewrite_book_body(lines: list[str]) -> list[str]:
    return rewrite_book_chunk_options(shift_body_headings(lines))


def normalize_front_matter_line(line: str) -> str:
    stripped = line.strip()
    if stripped.startswith("title:"):
        return strip_title_number(line)
    return line


def strip_title_number(line: str) -> str:
    match = re.match(r'^(\s*title:\s*)(["\']?)(.*?)(["\']?)\s*$', line)
    if not match:
        return line

    prefix, open_quote, title_text, close_quote = match.groups()
    normalized_title = TITLE_PREFIX_PATTERN.sub("", title_text).strip()
    quote = open_quote or close_quote
    if quote:
        return f"{prefix}{quote}{normalized_title}{quote}"
    return f"{prefix}{normalized_title}"


def shift_body_headings(lines: list[str]) -> list[str]:
    shifted: list[str] = []
    in_fence = False
    fence_marker = ""

    for line in lines:
        stripped = line.lstrip()

        fence_match = FENCE_PATTERN.match(stripped)
        if fence_match:
            marker = fence_match.group(1)
            if not in_fence:
                in_fence = True
                fence_marker = marker
            elif marker == fence_marker:
                in_fence = False
                fence_marker = ""
            shifted.append(line)
            continue

        if not in_fence:
            match = re.match(r"^(#{1,5})(\s+.*)$", line)
            if match:
                hashes, rest = match.groups()
                shifted.append(f"#{hashes}{rest}")
                continue

        shifted.append(line)

    return shifted


def rewrite_book_chunk_options(lines: list[str]) -> list[str]:
    rewritten: list[str] = []
    in_chunk = False
    chunk_lines: list[str] = []

    for line in lines:
        if not in_chunk and re.match(r"^```+\{[a-zA-Z]", line):
            in_chunk = True
            chunk_lines = [line]
            continue

        if in_chunk:
            chunk_lines.append(line)
            if re.match(r"^```+$", line.strip()):
                rewritten.extend(_rewrite_chunk(chunk_lines))
                in_chunk = False
                chunk_lines = []
            continue

        rewritten.append(line)

    if chunk_lines:
        rewritten.extend(_rewrite_chunk(chunk_lines))

    return rewritten


def _rewrite_chunk(chunk_lines: list[str]) -> list[str]:
    option_end = 1
    option_lines: list[str] = []
    while option_end < len(chunk_lines):
        line = chunk_lines[option_end]
        if line.startswith("#|"):
            option_lines.append(line)
            option_end += 1
            continue
        break

    if not option_lines:
        return chunk_lines

    out_width_seen = False
    fig_width_seen = False
    rewritten_options: list[str] = []
    for line in option_lines:
        stripped = line.strip()
        if stripped.startswith("#| out-width:"):
            rewritten_options.append('#| out-width: "90%"')
            out_width_seen = True
            continue
        if stripped.startswith("#| fig-width:"):
            fig_width_seen = True
            match = re.search(r"(-?\d+(?:\.\d+)?)", stripped)
            if match and float(match.group(1)) > 4.2:
                rewritten_options.append("#| fig-width: 4.2")
            else:
                rewritten_options.append(line)
            continue
        rewritten_options.append(line)

    if not fig_width_seen:
        rewritten_options.append("#| fig-width: 4.2")
    if not out_width_seen:
        rewritten_options.append('#| out-width: "90%"')

    return [chunk_lines[0], *rewritten_options, *chunk_lines[option_end:]]


def prepare_staging(chapters: list[tuple[int, Path]]) -> None:
    if STAGING_DIR.exists():
        shutil.rmtree(STAGING_DIR)
    STAGING_DIR.mkdir(parents=True)

    shutil.copy2(BOOK_DIR / "index.qmd", OUTPUT_INDEX)

    for name in ("_extensions", "BDC334", "data", "docs", "images", "styles"):
        ensure_symlink(REPO_ROOT / name, STAGING_DIR / name)

    ensure_symlink(REPO_ROOT / "references.bib", STAGING_DIR / "references.bib")

    staged_bcb744 = STAGING_DIR / "BCB744"
    staged_basic_stats = staged_bcb744 / "basic_stats"
    staged_bcb744.mkdir(parents=True, exist_ok=True)
    staged_basic_stats.mkdir(parents=True, exist_ok=True)

    ensure_symlink(REPO_ROOT / "BCB744" / "BCB744_index.qmd", staged_bcb744 / "BCB744_index.qmd")
    staged_book = staged_basic_stats / "book"
    staged_book.mkdir(parents=True, exist_ok=True)
    ensure_symlink(BOOK_DIR / "biostats_book_preamble.tex", staged_book / "biostats_book_preamble.tex")
    ensure_symlink(BOOK_DIR / "figure-size-filter.lua", staged_book / "figure-size-filter.lua")
    ensure_symlink(REPO_ROOT / "BCB744" / "tasks", staged_bcb744 / "tasks")
    ensure_symlink(REPO_ROOT / "BCB744" / "assessments", staged_bcb744 / "assessments")

    extra_basic_stats = (
        "index.qmd",
        "kaggle_life_expectancy.qmd",
    )
    for filename in extra_basic_stats:
        copy_qmd_with_pdf_override(CHAPTER_DIR / filename, staged_basic_stats / filename)

    for _, chapter_path in chapters:
        copy_qmd_with_pdf_override(chapter_path, staged_basic_stats / chapter_path.name)


def render_book(fmt: str) -> int:
    cmd = ["quarto", "render", str(STAGING_DIR), "--to", fmt]
    completed = subprocess.run(cmd, cwd=BOOK_DIR)
    return completed.returncode


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate the BCB744 biostatistics book config and optionally render it."
    )
    parser.add_argument(
        "--render",
        choices=("pdf", "html", "all"),
        help="Render the book after regenerating the Quarto config.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    chapters = discover_chapters()
    if not chapters:
        print("No numbered biostatistics chapters were found.", file=sys.stderr)
        return 1

    prepare_staging(chapters)
    write_config(build_config(chapters))
    print(f"Wrote {OUTPUT_CONFIG.relative_to(REPO_ROOT)} with {len(chapters)} chapters.")

    if args.render is None:
        return 0

    if args.render == "all":
        for fmt in ("html", "pdf"):
            rc = render_book(fmt)
            if rc != 0:
                return rc
        return 0

    return render_book(args.render)


if __name__ == "__main__":
    raise SystemExit(main())
