{
  "hash": "92a96c1cde00cfcd0ab3d25ad0e8b995",
  "result": {
    "engine": "knitr",
    "markdown": "---\ndate: \"2026-08-19\"\ndate-modified: \"last-modified\"\ntitle: \"Lab 4. Species Distribution Patterns\"\nformat:\n  html:\n    anchor-sections: true\n    date-format: long\n    date-modified: last-modified\n    date-modified-title: \"Last updated\"\n    number-sections: true\n    page-layout: article\nparams:\n  hide_answers: false\n---\n\n\n::: callout-note\n## BCB743\n\n**This material must be reviewed by BCB743 students in Week 1 of Quantitative Ecology.**\n:::\n\n::: callout-tip\n## This Lab Accompanies the Following Lecture\n\n- [Lecture 6: Unified Ecology](Lec-06-unified-ecology.qmd)\n:::\n\n::: callout-tip\n## Data for This Lab\n- The Barro Colorado Island Tree Counts data [@condit2002beta] -- load **vegan** and load the data with `data(BCI)`\n- The Oribatid mite data [@borcard1992partialling; @borcard1994environmental] -- load **vegan** and load the data with `data(mite)`\n- The seaweed species data [@smit2017seaweeds] -- [`SeaweedSpp.csv`](../data/BCB743/seaweed/SeaweedSpp.csv)\n- The Doubs River species data [@verneaux1973cours; @borcard2011numerical] -- [`DoubsSpe.csv`](../data/BCB743/DoubsSpe.csv)\n:::\n\n::: callout-tip\n## Reading Required for This Lab\n\n- [Matthews and Whittaker (2015)](../docs/Matthews_and_Whittaker_2015.pdf)\n- [Shade et al. (2018)](../docs/Shade_et_al_2018.pdf)\n:::\n\n\nIn this Lab, we will calculate the various species distribution patterns included in the paper by [Shade et al. (2018)](../docs/Shade_et_al_2018.pdf).\n\n\n## Lab goals and relation to Lecture 6 {#sec-lab04-goals}\n\nThis lab translates the analytical framework from [Lecture 6](Lec-06-unified-ecology.qmd) into executable analyses.\n\n- Analytical framing and workflow rationale: see [Why \"Unified Ecology\"](Lec-06-unified-ecology.qmd#sec-lec06-why) and [Integrated Workflow](Lec-06-unified-ecology.qmd#sec-lec06-workflow).\n- Pattern-family framework and assumptions: see [Core Pattern Families](Lec-06-unified-ecology.qmd#sec-lec06-patterns), [Hypothesis-Testing Frame](Lec-06-unified-ecology.qmd#sec-lec06-testing), and [Common Failure Modes](Lec-06-unified-ecology.qmd#sec-lec06-fail).\n\nThe practical flow in this lab is: **setup → pattern demonstrations → interpretation → exercises**.\n\n## The Data {#sec-lab04-setup}\n\nWe will calculate each for the [Barro Colorado Island Tree Counts data](https://repository.si.edu/handle/10088/20925) that come with **vegan**. See `?vegan::BCI` for a description of the data contained with the package, as well as a selection of publications relevant to the data and analyses. The primary publication of interest is @condit2002beta.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(vegan)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# library(vegan) # already loaded\n# library(tidyverse) # already loaded\ndata(BCI) # data contained within vegan\n\n# make a head-tail function\nht <- function(d) rbind(head(d, 7), tail(d, 7))\n\n# Lets look at a portion of the data:\nht(BCI)[1:7, 1:7]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Abarema.macradenia Vachellia.melanoceras Acalypha.diversifolia\n1                  0                     0                     0\n2                  0                     0                     0\n3                  0                     0                     0\n4                  0                     0                     0\n5                  0                     0                     0\n6                  0                     0                     0\n7                  0                     0                     0\n  Acalypha.macrostachya Adelia.triloba Aegiphila.panamensis\n1                     0              0                    0\n2                     0              0                    0\n3                     0              0                    0\n4                     0              3                    0\n5                     0              1                    1\n6                     0              0                    0\n7                     0              0                    1\n  Alchornea.costaricensis\n1                       2\n2                       1\n3                       2\n4                      18\n5                       3\n6                       2\n7                       0\n```\n\n\n:::\n:::\n\n\n## Practical A. Species-Abundance Distribution {#sec-lab04-sad}\n\nTheory link: see [Core Pattern Families](Lec-06-unified-ecology.qmd#sec-lec06-patterns) in [Lecture 6](Lec-06-unified-ecology.qmd).\n\n\nThe species abundance distribution (SAD) expresses one of ecology’s most persistent regularities, *viz.*, in almost any community, a few species dominate in abundance, while the majority are comparatively rare. This skewed pattern is often summarised as “few common, many rare” and has been recognised since the earliest quantitative analyses of community structure. It has become a central object of ecological theory. Graphically, SADs plot species abundance against either species identity or rank to provide a means of comparing empirical assemblages with theoretical expectations of community organisation.\n\nThe first formulation of this pattern was developed by @fisher1943relation, who observed that species frequencies often conform to what he termed a **logarithmic series distribution**. In this representation, *the expected number of species with a given number of individuals declines rapidly as abundance increases*, showing communities where most species occur at low frequencies and only a small fraction reach very high densities. The curve of Fisher’s log-series distribution thus shows the expected number of species $f$ with $n$ observed individuals, and the interpretation of this curve is structurally similar across all SAD models—only the underlying mathematics and rationale differ. Fisher’s model remains widely used as a theoretical benchmark and as a statistical model. In **R**, the **vegan** package implements this procedure through the `fisherfit()` function, which estimates the log-series parameter and compares it to observed community data (@fig-fishers-log).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# take one random sample of a row (site):\n# for this website's purpose, this function ensure the same random\n# sample is drawn each time the web page is recreated\nset.seed(13)\nk <- sample(nrow(BCI), 1)\nfish <- fisherfit(BCI[k, ])\nfish\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nFisher log series model\nNo. of species: 95 \nFisher alpha:   39.87659 \n```\n\n\n:::\n\n```{.r .cell-code}\nplot(fish)\n```\n\n::: {.cell-output-display}\n![Fisher's log series distribution calculated for the Barro Colorado Island Tree Counts data.](Lab-04-biodiversity_files/figure-html/fig-fishers-log-1.svg){#fig-fishers-log}\n:::\n:::\n\n\nBuilding on this foundation, @preston1948commonness introduced an alternative formulation: the **log-normal distribution** of species abundances. Instead of ranking species, he grouped them into “octaves”, *i.e.*, abundance classes that double in size (1, 2, 4, 8, 16, 32, …), and showed that, *in sufficiently well-sampled communities*, the frequency of species within these classes approximates a bell-shaped Gaussian curve when plotted on a logarithmic scale. Preston also emphasised the effect of incomplete sampling: rare species falling below a “veil line” remain undetected, giving the distribution its characteristic truncated form. This method captures the idea that rarity and commonness are not absolute properties but functions of sampling intensity. In **vegan**, Preston’s method is implemented with mathematical modifications to handle ties more effectively via the `prestondistr()` function (@fig-preston).\n\n\n::: {.cell}\n\n```{.r .cell-code}\npres <- prestondistr(BCI[k, ])\npres\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nPreston lognormal model\nMethod: maximized likelihood to log2 abundances \nNo. of species: 95 \n\n      mode      width         S0 \n 0.9234918  1.6267630 26.4300640 \n\nFrequencies by Octave\n                0        1        2        3        4        5         6\nObserved 19.00000 27.00000 21.50000 17.00000 7.000000 2.500000 1.0000000\nFitted   22.49669 26.40085 21.23279 11.70269 4.420327 1.144228 0.2029835\n```\n\n\n:::\n\n```{.r .cell-code}\nplot(pres)\n```\n\n::: {.cell-output-display}\n![Preston's log-normal distribution demonstrated for the BCI data.](Lab-04-biodiversity_files/figure-html/fig-preston-1.svg){#fig-preston}\n:::\n:::\n\n\nA further step was taken by @whittaker1965dominance, who reformulated SADs as **rank-abundance distributions** (RADs), also known as dominance–diversity curves or Whittaker plots. Here, species are ordered from most to least abundant along the $x$-axis, and their relative abundances (often log-transformed) are plotted on the $y$-axis. The slope and curvature of the resulting profile reveal both evenness and the extent of dominance: steep curves indicate communities dominated by a few species, whereas long, shallow tails point to greater species equity. Unlike Fisher’s or Preston’s frequency-based models, Whittaker’s approach highlights the shape of the assemblage as a whole and facilitates comparison across communities with different richness levels. In **vegan**, this is achieved via the `radfit()` function, which overlays multiple fitted models—broken-stick, preemption, log-normal, Zipf, and Zipf–Mandelbrot—onto the observed ranked data (@fig-rad).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrad <- radfit(BCI[k, ])\nrad\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nRAD models, family poisson \nNo. of species 95, total abundance 392\n\n           par1      par2     par3    Deviance AIC      BIC     \nNull                                   56.3132 324.6477 324.6477\nPreemption  0.042685                   55.8621 326.1966 328.7504\nLognormal   0.84069   1.0912           16.1740 288.5085 293.6162\nZipf        0.12791  -0.80986          21.0817 293.4161 298.5239\nMandelbrot  0.66461  -1.2374   4.1886   6.6132 280.9476 288.6093\n```\n\n\n:::\n\n```{.r .cell-code}\nplot(rad)\n```\n\n::: {.cell-output-display}\n![Whittaker's rank abundance distribution curves demonstrated for the BCI data.](Lab-04-biodiversity_files/figure-html/fig-rad-1.svg){#fig-rad}\n:::\n:::\n\n\nWe can also fit the rank abundance distribution curves to several sites at once (previously we have done so on only one site) (@fig-rad2):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm <- sample(nrow(BCI), 6)\nrad2 <- radfit(BCI[m, ])\nrad2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nDeviance for RAD models:\n\n                  3       37       10       13        6       22\nNull        86.1127  93.5952  77.2737  52.6207  72.1627 114.1747\nPreemption  58.9295 104.0978  62.7210  57.7372  54.7709 110.5156\nLognormal   29.2719  19.0653  20.4770  15.8218  19.5788  26.2510\nZipf        50.1262  11.3048  39.7066  22.8006  32.4630  15.5222\nMandelbrot   5.7342   8.9107   9.8353  12.1701   5.5973   9.6047\n```\n\n\n:::\n\n```{.r .cell-code}\nplot(rad2)\n```\n\n::: {.cell-output-display}\n![Rank abundance distribution curves fitted to several sites.](Lab-04-biodiversity_files/figure-html/fig-rad2-1.svg){#fig-rad2}\n:::\n:::\n\n\nAbove, we see that the model selected for capturing the shape of the SAD is the Mandelbrot, and it is plotted individually for each of the randomly selected sites. Model selection works through Akaike’s or Schwartz’s Bayesian information criteria (AIC or BIC; AIC is the default---select the model with the lowest AIC).\n\n[**BiodiversityR**](https://github.com/cran/BiodiversityR) (and [here](http://apps.worldagroforestry.org/downloads/Publications/PDFS/b13695.pdf) and [here](https://rpubs.com/Roeland-KINDT)) also offers options for rank abundance distribution curves; see `rankabundance()` (@fig-rac):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(BiodiversityR)\nrankabund <- rankabundance(BCI)\nrankabunplot(rankabund, cex = 0.8, pch = 0.8, col = \"indianred4\")\n```\n\n::: {.cell-output-display}\n![Rank-abundance curves for the BCI data.](Lab-04-biodiversity_files/figure-html/fig-rac-1.svg){#fig-rac}\n:::\n:::\n\n\nRefer to the help files for the respective functions to see their differences.\n\n### Calculating a SAD from a site × species table\n\nHere’s how to manually derive an SAD from a typical community dataset. Let's assume you have a site × species table, where rows are sampling sites and columns are species, with the cells containing counts (abundances).\n\n1. **Get Total Species Abundances**: Your first step is to get the total abundance for each species across all your sites. You do this by **summing each column**. This collapses your site × species matrix into a single list of numbers, which we call an \"**abundance vector**;\" here each number is the total count for one species.\n\n2. **Create a Frequency Table**: Now, you'll process this abundance vector. Count *how many* species have an abundance of 1, how many have an abundance of 2, and so on, for all abundance values present in your data. The result is a frequency table.\n\nFor example, if your abundance vector is `(1, 1, 5, 2, 8, 1, 2, 5)`, your frequency table would be:\n\n  * Abundance Class 1: 3 species\n  * Abundance Class 2: 2 species\n  * Abundance Class 5: 2 species\n  * Abundance Class 8: 1 species\n\n3. **Plot the SAD**: This frequency table is your SAD. To visualise it as a frequency distribution (like for Fisher's or Preston's models), you plot the **Abundance Class on the *x*-axis** and the **Number of Species (frequency) on the *y*-axis**. You will typically see that classic hollow curve.\n\n4. **Plot the RAD (Whittaker Plot)**: To create a Rank Abundance Distribution from the same data, you take your original abundance vector `(1, 1, 5, 2, 8, 1, 2, 5)`, sort it in descending order `(8, 5, 5, 2, 2, 1, 1, 1)`, and then plot it. The ***x*-axis is the rank** `(1, 2, 3, 4, 5, 6, 7, 8)`, and the ***y*-axis is the corresponding abundance value** `(8, 5, 5, 2, 2, 1, 1, 1)`.\n\n## Practical B. Occupancy-Abundance Relationship {#sec-lab04-oar}\n\nTheory link: see [Core Pattern Families](Lec-06-unified-ecology.qmd#sec-lec06-patterns) and [From Measures to Models](Lec-06-unified-ecology.qmd#sec-lec06-measures-models) in [Lecture 6](Lec-06-unified-ecology.qmd).\n\n\n**Occupancy** refers to the number (or proportion) of sites in which a species is recorded as present. When linked with measures of abundance, it provides a way to examine the spatial distribution of species across a landscape. **Occupancy–abundance relationships** (OARs) reveal that species that are locally abundant at a given site tend also to be widespread across many sites in the region; conversely, species of low local abundance are more often restricted in their wider distribution. This empirical pattern has been so consistently observed that it has been described as verging on an ecological “law;” it tells us about the underlying processes of niche breadth, dispersal capacity, and environmental tolerance. OARs are therefore often used to infer degrees of niche specialisation, with generalists expected to show both high occupancy and high abundance, and specialists clustering toward low values of both measures (@fig-occupancy).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggpubr)\n\n# A function for counts:\n# count number of non-zero elements per column\ncount_fun <- function(x) {\n    length(x[x > 0])\n}\n\nBCI_OA <- data.frame(\n    occ = apply(BCI, MARGIN = 2, count_fun),\n    ab  = apply(BCI, MARGIN = 2, function(x) mean(x[x > 0]))\n)\n\nggplot(BCI_OA, aes(x = ab, y = occ / max(occ))) +\n    geom_point(colour = \"indianred3\") +\n    scale_x_log10() +\n    # scale_y_log10() +\n    labs(\n        title = \"Barro Colorado Island Tree Counts\",\n        x = \"Log (abundance)\", y = \"Occupancy\"\n    ) +\n    theme_linedraw()\n```\n\n::: {.cell-output-display}\n![Occupancy-abundance relationships seen in the BCI data.](Lab-04-biodiversity_files/figure-html/fig-occupancy-1.svg){#fig-occupancy}\n:::\n:::\n\n\n### Calculate the OAR from a site × species table\n\nCalculating and plotting this relationship is easy. Let's start with your site × species table with cells containing abundance counts.\n\n1. **Calculate Occupancy for Each Species**: Occupancy is simply *the number or proportion of sites where a species is present*. To calculate this, you look down each species' column and count how many of the cells have a value greater than zero. You'll end up with a vector of numbers (integers; counts), one number for each species, representing its occupancy. For example, if a species is found at 5 out of 20 surveyed sites, its occupancy count is 5 (or its proportional occupancy is $5/20=0.25$).\n\n2. **Calculate Mean Local Abundance for Each Species**: This step is important. You need the **average abundance** of a species *only in the sites where it actually occurs*. Including sites where it's absent (with an abundance of zero) would artificially deflate the average and obscure the true relationship. Then, for each species, **sum all the abundance values in its column** (the total abundance) and divide this by the occupancy count you calculated in Step 1. This gives you the **mean local abundance** for that species.\n\n3. **Plot the Relationship**: You now have two corresponding vectors of values for all your species: one for occupancy and one for mean local abundance. To visualise the OAR, you create a scatter plot:\n\n  * *x*-axis: Occupancy (the number or proportion of sites occupied).\n  * *y*-axis: Mean Local Abundance. Because abundance values often span several orders of magnitude, this axis is almost always log-transformed (*e.g.*, using $log_{10}$ or $log_{e}$) to better bring out the pattern and meet the assumptions of statistical tests.\n\n## Practical C. Species-Area (Accumulation) {#sec-lab04-accum}\n\nTheory link: see [Alpha–Beta–Gamma linkage](Lec-06-unified-ecology.qmd#sec-lec06-abg) and [Integrated Workflow](Lec-06-unified-ecology.qmd#sec-lec06-workflow) in [Lecture 6](Lec-06-unified-ecology.qmd).\n\n\nSpecies accumulation curves—often presented as sample-based species–area relationships (SAR)—address the question: given what has already been sampled, how many species are yet unseen, and how does observed richness grow as sampling effort expands? Within a single ecosystem type, one ordinarily expects richness to rise with the number of distinct sampling units (plots, quadrats, trawls), then bend toward a plateau as further additions yield few or no new species. The curve is thus a record of discovery under a specified sampling design. In this curve, the $x$-axis represents cumulative sampling effort (number of sites, or cumulative area if sites are areally commensurate), while the $y$-axis records the expected number of species discovered at that effort. As [Roeland Kindt](http://apps.worldagroforestry.org/downloads/Publications/PDFS/b13695.pdf) explains (see p. 41 in the cited note), the curve is generated by “adding” sites and tallying the average richness at each step—an averaging that already hints at a statistical question: in what order are sites added, and how is that order handled?\n\nThe `specaccum()` function has many different ways of adding the new sites to the curve, but the default 'exact' seems to be a sensible choice. **BiodiversityR** has the `accumresult()` function that does nearly the same. Let's demonstrate using **vegan**'s function (@fig-accum, @fig-accum2, and @fig-accum3):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsp1 <- specaccum(BCI)\nsp2 <- specaccum(BCI, \"random\")\n\n# par(mfrow = c(2,2), mar = c(4,2,2,1))\n# par(mfrow = c(1,2))\nplot(sp1,\n    ci.type = \"polygon\", col = \"indianred4\", lwd = 2, ci.lty = 0,\n    ci.col = \"steelblue2\", main = \"Default: exact\",\n    ylab = \"No. of species\"\n)\n```\n\n::: {.cell-output-display}\n![Species-area accumulation curves seen in the BCI data.](Lab-04-biodiversity_files/figure-html/fig-accum-1.svg){#fig-accum}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmods <- fitspecaccum(sp2, \"arrh\")\nplot(mods, col = \"indianred\", ylab = \"No. of species\")\nboxplot(sp2, col = \"yellow\", border = \"steelblue2\", lty = 1, cex = 0.3, add = TRUE)\nsapply(mods$models, AIC)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  [1] 311.4642 303.7835 346.3668 320.0786 338.7978 320.2538 325.6968 346.2671\n  [9] 320.3900 343.8570 318.2509 369.8303 335.9936 350.8711 327.9831 348.1287\n [17] 328.2393 347.8133 324.3837 314.8555 333.1390 340.5678 332.6836 360.5208\n [25] 335.3660 325.3150 347.4324 336.7498 336.6374 276.1878 349.9283 295.0268\n [33] 308.4656 315.8304 303.0776 329.8425 356.2393 368.4302 318.0514 359.5975\n [41] 327.4228 335.7604 259.8340 318.0063 335.7753 285.8790 323.5174 300.3546\n [49] 327.1448 355.2747 288.2583 366.5995 287.4120 327.5877 362.6487 323.5904\n [57] 339.5650 321.2264 336.6331 353.1295 317.9578 311.6528 336.3613 337.8327\n [65] 328.4787 311.6842 345.8035 367.5620 319.0269 305.6546 338.7805 321.8859\n [73] 330.6029 326.7097 345.8923 338.4755 352.8710 355.8038 307.7327 329.2355\n [81] 341.6628 340.1687 333.4771 348.3144 321.4417 317.4331 339.2211 313.1990\n [89] 305.3069 342.4581 318.0308 299.7067 294.7851 324.3237 333.5849 349.2749\n [97] 369.8287 323.0041 332.6820 329.3875\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Fit Arrhenius models to all random accumulations](Lab-04-biodiversity_files/figure-html/fig-accum2-1.svg){#fig-accum2}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\naccum <- accumresult(BCI, method = \"exact\", permutations = 100)\naccumplot(accum)\n```\n\n::: {.cell-output-display}\n![A species accumulation curve.](Lab-04-biodiversity_files/figure-html/fig-accum3-1.svg){#fig-accum3}\n:::\n:::\n\n\nSpecies accumulation curves can also be calculated with the `alpha.accum()` function of the **BAT** package (@fig-accum4). In addition, the **BAT** package can also apply various diversity and species distribution assessments to **phylogenetic** and **functional** diversity. See the examples provided by @cardoso2015bat.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(BAT)\nBCI.acc <- alpha.accum(BCI, prog = FALSE)\n\npar(mfrow = c(1, 2))\nplot(BCI.acc[, 2], BCI.acc[, 17],\n    col = \"indianred\",\n    xlab = \"Individuals\", ylab = \"Chao1P\"\n)\nplot(BCI.acc[, 2], slope(BCI.acc)[, 17],\n    col = \"indianred\",\n    xlab = \"Individuals\", ylab = \"Slope\"\n)\n```\n\n::: {.cell-output-display}\n![A species accumulation curve made with the `alpha.accum()` function of **BAT**.](Lab-04-biodiversity_files/figure-html/fig-accum4-1.svg){#fig-accum4}\n:::\n:::\n\n\n### Calculating a species accumulation curve from scratch\n\nCalculating a proper SAC from a site × species table involves more than just adding up samples in their original order. The order in which you \"collect\" your samples can drastically change the shape of the curve. To solve this, the process relies on repeated randomisation to create a smooth, average curve.\n\n1. **Randomise the Order of Samples**\n\nThe first and most important step is to randomise the order of your samples (the rows in your site × species table). This ensures the resulting curve isn't biased by happening to have a particularly species-rich or species-poor site at the beginning of the sequence.\n\n2. **Accumulate Species in Sequence**\n\nOnce the sample order is shuffled, you build the curve step-by-step:\n\n* For the 1st sample: The cumulative species count is simply the number of species in that first sample.\n* For the 2nd sample: You pool the species from the first and second samples and count the total number of unique species found across both.\n* For the 3rd sample: You pool the species from the first three samples and count the total number of unique species found across all three.\n* You continue this process until all samples in your shuffled list have been added. This single pass creates one possible accumulation curve.\n\n3. **Repeat and Average**\n\nA curve from a single random order is not representative. Therefore, you must repeat steps 1 and 2 many times (typically 100 to 1,000 times), creating a new random permutation of your samples each time. This gives you a large collection of possible accumulation curves.\n\n4. **Plot the Final Curve**\n\nThe final species accumulation curve is the average of all the randomised curves you generated.\n\n* *x*-axis: Number of Samples Accumulated (*e.g.*, 1, 2, 3, ... up to your total number of sites).\n* *y*-axis: The average cumulative number of species found at that level of sampling effort.\n\nIt's also standard practice to plot the standard deviation or confidence intervals around this mean curve. This creates a shaded region or error bars, showing the amount of variation from the different randomisations. A narrow confidence interval indicates a more robust and reliable curve.\n\n## Practical D. Rarefaction Curves {#sec-lab04-rare}\n\nTheory link: see [From Measures to Models](Lec-06-unified-ecology.qmd#sec-lec06-measures-models) and [Common Failure Modes](Lec-06-unified-ecology.qmd#sec-lec06-fail) in [Lecture 6](Lec-06-unified-ecology.qmd).\n\n\nLike **species accumulation curves**, **rarefaction curves** also address the question of unseen species, but they do so in a different way. Rarefaction -- literally “scaling down” [@heck1975explicit] -- is a statistical technique that estimates species richness (often denoted S, or sometimes diversity indices such as Shannon diversity, $H’$, or Simpson’s diversity, $\\lambda$) from community data, typically organised as a site × species table. The main goal is to ask: given a smaller sample of individuals or sites than were actually collected, how many species would we expect to detect? Rarefaction thus provides a way of standardising richness estimates across samples of unequal size and of judging whether sampling effort has been sufficient to capture the community’s complement of species.\n\nAt first sight, rarefaction curves resemble species accumulation curves, since both plot species richness against increasing effort. The difference lies in how “effort” is defined and how the curves are generated. **Species accumulation curves** build up by successively adding new sites or samples (rows of the community matrix) and tallying the union of species observed. By contrast, **rarefaction curves** are constructed by randomly sub-sampling the existing pool of $N$ individuals or samples. Repeated resampling at size $n$ (where $1 \\leq n \\leq N$) yields an expected number of species at that level of effort, and the curve plots this expectation as a function of $n$.\n\nTwo standard rarefaction approaches exist. In **individual-based rarefaction**, the $x$-axis represents the number of individuals sampled across all species, with richness S as the response. The principle is intuitive: when only a few individuals are drawn, they are likely to belong to a small set of species, but as more individuals are added, the chance of encountering new species increases—at a decelerating rate as common species are already represented. In **sample-based rarefaction**, the $x$-axis represents the number of samples (sites, quadrats, trawls), and species richness is again tallied as a function of sample number. In both cases, the resulting curves rise steeply at first, then level off toward a plateau, reflecting the declining probability of detecting the rarest species as sampling effort grows.\n\nThis resampling distinction is what sets rarefaction apart from **species accumulation curves** and **species abundance distributions (SADs)**. While SADs describe how species are distributed in terms of abundance and accumulation curves describe how observed richness grows as sampling units are added, rarefaction explicitly **re-samples the observed data at smaller effort levels** to estimate expected richness. In **R**, the function `rarecurve()` in **vegan** draws rarefaction curves for each row (site) in a community table, producing a family of curves showing how species richness scales with the number of individuals sampled. These are drawn using base graphics [@fig-rarefy], but can be easily reproduced with **ggplot2** for more flexible visualisation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Example provided in ?vegan::rarefy\n# observed number of species per row (site)\nS <- specnumber(BCI)\n\n# calculate total no. individuals sampled per row, and find the minimum\n(raremax <- min(rowSums(BCI)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 340\n```\n\n\n:::\n\n```{.r .cell-code}\nSrare <- rarefy(BCI, raremax, se = FALSE)\npar(mfrow = c(1, 2))\nplot(S, Srare,\n    col = \"indianred3\",\n    xlab = \"Sample size\\n(observed no. of individuals)\", ylab = \"No. species found\"\n)\nrarecurve(BCI,\n    step = 20, sample = raremax, col = \"indianred3\", cex = 0.6,\n    xlab = \"Sample size\\n(observed no. of individuals)\", ylab = \"No. species found\"\n)\n```\n\n::: {.cell-output-display}\n![Rarefaction curves for the BCI data.](Lab-04-biodiversity_files/figure-html/fig-rarefy-1.svg){#fig-rarefy}\n:::\n:::\n\n\nWe can also use the [**iNEXT**](https://github.com/JohnsonHsieh/iNEXT) package for rarefaction curves. From the package's [Introduction Vignette](https://cran.r-project.org/web/packages/iNEXT/vignettes/Introduction.html):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(iNEXT)\n\n# transpose the BCI data:\nBCI_t <- list(BCI = t(BCI))\n\nBCI_out <- iNEXT(BCI_t, q = c(0, 1, 2), datatype = \"incidence_raw\")\nggiNEXT(BCI_out, type = 1, color.var = \"Order.q\")\n## Note: iNEXT is run here with incidence settings for an abundance-origin dataset.\n## The function coerces data internally; interpret results as incidence-based outputs,\n## not abundance-based estimates from this input form.\n```\n\n::: {.cell-output-display}\n![Demonstration of iNEXT capabilities.](Lab-04-biodiversity_files/figure-html/fig-inext-1.svg){#fig-inext}\n:::\n:::\n\n\niNEXT focuses on three measures of Hill numbers of order q: species richness (q = 0), Shannon diversity (q = 1, the exponential of Shannon entropy) and Simpson diversity (q = 2, the inverse of Simpson concentration). For each diversity measure, iNEXT uses the observed sample of abundance or incidence data (called the “reference sample”) to compute diversity estimates and the associated 95% confidence intervals for the following two types of rarefaction and extrapolation (R/E):\n \n1. Sample‐size‐based R/E sampling curves: iNEXT computes diversity estimates for rarefied and extrapolated samples up to an appropriate size. This type of sampling curve plots the diversity estimates with respect to sample size.\n\n2. Coverage‐based R/E sampling curves: iNEXT computes diversity estimates for rarefied and extrapolated samples with sample completeness (as measured by sample coverage) up to an appropriate coverage. This type of sampling curve plots the diversity estimates with respect to sample coverage.\n\niNEXT also plots the above two types of sampling curves and a sample completeness curve. The sample completeness curve provides a bridge between these two types of curves.\n\nFor information about Hill numbers see David Zelený's [Analysis of community data in R](https://www.davidzeleny.net/anadat-r/doku.php/en:diversity_analysis) and Jari Oksanen's coverage of [diversity measures in **vegan**](https://cran.r-project.org/web/packages/vegan/vignettes/diversity-vegan.pdf).\n\nThere are four datasets distributed with iNEXT and numerous examples are provided in the [Introduction Vignette](https://cran.r-project.org/web/packages/iNEXT/vignettes/Introduction.html). iNEXT has an 'odd' data format that might seem foreign to **vegan** users. To use iNEXT with dataset suitable for analysis in vegan, we first need to convert BCI data to a species × site matrix (@fig-inext):\n\n### \"Recipe\" for Individual-Based rarefaction\n\nThis method estimates the expected number of species for a given number of individuals sampled. The R function `rarecurve()` in the **vegan** package automates this process for each site, but here is the recipe for generating one such curve for a single site (one row from your table):\n\n1. **Create the Individual Pool**: From your chosen site's row, create an explicit \"pool\" of all individuals. For example, if the site has 3 individuals of Species A, 0 of Species B, and 5 of Species C, your pool is a list containing `(A, A, A, C, C, C, C, C)`. The total number of individuals in this pool is $N$.\n\n2. **Set the Subsample Size ($n$)**: Choose a subsample size $n$, where $n$ is an integer from 1 to $N$. You will repeat the following steps for many different values of n to build the curve's *x*-axis.\n\n3. **Randomly Subsample Individuals**: From your pool of N individuals, randomly draw $n$ individuals without replacement.\n\n4. **Count Unique Species**: Count the number of unique species in your random subsample. For instance, if you drew `(A, C, C)`, your species count for this draw is 2.\n\n5. **Repeat and Average**: A single draw isn't enough. Repeat steps 3 and 4 many times (*e.g.*, 100 or 1,000 times) for the same subsample size $n$. Then, calculate the average species count across all those repetitions. This gives you the expected species richness, $E(S_n)$, for that specific sample size.\n\n6. **Plot the Curve**: Repeat the entire process (steps 3-5) for a range of subsample sizes from $n=1$ up to $N$. Plot the subsample size ($n$) on the *x*-axis and the expected species richness ($E(S_n)$) on the *y*-axis. The result is a smooth curve that shows how many species you can expect to find for any given number of individuals sampled from that site.\n\n### \"Recipe\" for Sample-Based rarefaction\n\nThis method, which is very similar to a species accumulation curve, estimates the expected number of species for a given number of samples (*e.g.*, sites, quadrats). Here’s the recipe, which uses your entire site × species table:\n\n1. **Define the Sample Pool**: Your pool is the complete set of samples (all the rows in your site × species table). Let's say you have $K$ total samples.\n\n2. **Set the Subsample Size ($k$)**: Choose a number of samples $k$ to draw, where $k$ is an integer from 1 to $K$. This will be the value on your *x*-axis.\n\n3. **Randomly Subsample Samples**: From your pool of $K$ samples, randomly select $k$ of them without replacement.\n\n4. **Count Unique Species**: Combine the species lists from the $k$ chosen samples and count the total number of unique species found across all of them.\n\n5. **Repeat and Average**: Just as before, repeat steps 3 and 4 many times for the same subsample size $k$. Calculate the average species count from all these repetitions to get the expected species richness for that level of sampling effort.\n\n6. **Plot the Curve**: Repeat the process for all subsample sizes from $k=1$ up to $K$. Plot the number of samples ($k$) on the *x*-axis and the corresponding expected species richness on the *y*-axis to create the sample-based rarefaction curve.\n\n## Practical E. Distance-Decay Curves and Elevation (and Other) Gradients {#sec-lab04-dd}\n\nTheory link: see [Distance-decay and ordination framework](Lec-06-unified-ecology.qmd#sec-lec06-ordination) and [Hypothesis-Testing Frame](Lec-06-unified-ecology.qmd#sec-lec06-testing) in [Lecture 6](Lec-06-unified-ecology.qmd).\n\n\nThe principles of distance-decay relationships are closely linked to $\\beta$-diversity turnover concepts introduced in Lecture 4 (especially turnover components). Distance decay is the primary explanation for the spatial pattern of $\\beta$-diversity along the South African coast in @smit2017seaweeds. A deeper dive into distance-decay calculation can be seen in [Deep Dive into Gradients](../BCB743/deep_dive.qmd).\n\nIn one sense, an elevation gradient can be seen as specific case of distance decay. The Doubs River dataset offers a nice example of data collected along an elevation gradient (which also happens to be a gradient along a river). Elevation gradients have many similarities with depth gradients (*e.g.*, down the ocean depths) and latitudinal gradients. \n\n::: callout-note\n## Interpretation Checklist {#sec-lab04-interpret}\nA) When we look at gradients such as elevation (and some others), please think about what the species are *actually* responding to. Are they responding to elevation directly?\n\nB) A recipe for the analysis of distance decay relationships can be found in our earlier lectures on the topic. However, there are many ways to approach these kinds of problems, and, for the sake of doing well in tests and exams, I suggest you deeply think about them.\n:::\n\n::: callout-important\n## Exercises {#sec-lab04-exercises}\n(To be reviewed by BCB743 student but not for marks)\n\n**Total: 14 marks for BDC334 students. Only the calculations, figures and specified labels are marked; the explanations and ecological interpretations are not marked.**\n\n1. **(/ 12; 3 per figure)** Produce the following figures for the species data indicated in [square brackets]:\n    a. species-abundance distribution [mite];\n    b. occupancy-abundance curves [mite];\n    c. species-area curves [seaweed]---note, do not use the **BAT** package's `alpha.accum()` function as your computer might fall over;\n    d. rarefaction curves [mite].\n\n    Answer each under its own heading. For each, also explain briefly what the purpose of the analysis is (i.e. what ecological insights might be provided), and describe the findings of your own analysis as well as any ecological implications that you might be able to detect.\n\n2. **(/ 2)** Find the most dominant species in the Doubs River dataset, using the sum of each species' abundance scores across all sites.\n\n3. Discuss how elevation, depth, or latitudinal gradients are similar in many aspects to distance decay relationships.\n:::\n\n\n\n::: {.callout-tip appearance=\"simple\"}\n## Model answers: Tasks 1--3\n\n### 1.a Species-abundance distribution of mites\n\n**Marking: 3 marks, allocated to the following objectively verifiable components.**\n\n- ✓ **1 mark:** correctly derive the abundance vector and species frequencies for the stated sampling unit.\n- ✓ **1 mark:** plot the corresponding species-abundance distribution with all values represented correctly.\n- ✓ **1 mark:** use readable axes identifying abundance and the number of species (or rank and abundance for a rank-abundance curve).\n\nThe model below pools all 70 sites. A correctly calculated distribution for an explicitly identified single site, or a rank-abundance representation with appropriate axes, is also acceptable. The ecological explanation is not marked.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(mite)\nmite_totals <- colSums(mite)\nmite_summary <- data.frame(\n    sites = nrow(mite),\n    species = sum(mite_totals > 0),\n    individuals = sum(mite)\n)\nknitr::kable(mite_summary)\n```\n\n::: {.cell-output-display}\n\n\n| sites| species| individuals|\n|-----:|-------:|-----------:|\n|    70|      35|        9800|\n\n\n:::\n\n```{.r .cell-code}\nsad_frequency <- as.data.frame(table(mite_totals[mite_totals > 0]))\nnames(sad_frequency) <- c(\"abundance\", \"species_frequency\")\nsad_frequency$abundance <- as.numeric(as.character(sad_frequency$abundance))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(sad_frequency, aes(abundance, species_frequency)) +\n    geom_point(colour = \"indianred3\") +\n    scale_x_log10() +\n    labs(\n        x = \"Total abundance across 70 sites (log10 scale)\",\n        y = \"Number of species\"\n    ) +\n    theme_linedraw()\n```\n\n::: {.cell-output-display}\n![Species-abundance distribution of mites pooled across 70 sites. Each point gives the number of species with a particular total abundance.](Lab-04-biodiversity_files/figure-html/fig-lab4-answer-mite-sad-1.svg){#fig-lab4-answer-mite-sad}\n:::\n:::\n\n\nThe pooled assemblage contains **9,800 individuals and 35 species**. The most abundant species is **LCIL**, with **2,468 individuals**; ONOV and SUCT have 1,209 and 1,187 respectively. The distribution describes the balance of rarity and dominance within the specified assemblage. It does not identify the processes that caused that balance. Pooling sites can also hide differences among local assemblages.\n\n### 1.b Occupancy-abundance relationship of mites\n\n**Marking: 3 marks.**\n\n- ✓ **1 mark:** calculate occupancy from non-zero records and mean abundance using occupied sites only.\n- ✓ **1 mark:** correctly plot all 35 species using the calculated values.\n- ✓ **1 mark:** label both axes, including whether occupancy is a count or a proportion, and indicate the abundance scale.\n\nEither axis orientation is acceptable. For proportional occupancy, divide by **70 sites**, not by the largest observed occupancy unless that value is also 70.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmite_occupancy <- colSums(mite > 0)\nmite_oa <- data.frame(\n    species = colnames(mite),\n    occupancy_count = mite_occupancy,\n    occupancy = mite_occupancy / nrow(mite),\n    mean_local_abundance = mite_totals / mite_occupancy\n)\nknitr::kable(mite_oa[mite_oa$species == \"LCIL\", ],\n    digits = 3,\n    row.names = FALSE\n)\n```\n\n::: {.cell-output-display}\n\n\n|species | occupancy_count| occupancy| mean_local_abundance|\n|:-------|---------------:|---------:|--------------------:|\n|LCIL    |              55|     0.786|               44.873|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(mite_oa, aes(mean_local_abundance, occupancy)) +\n    geom_point(colour = \"indianred3\") +\n    scale_x_log10() +\n    scale_y_continuous(limits = c(0, 1)) +\n    labs(\n        x = \"Mean abundance in occupied sites (log10 scale)\",\n        y = \"Proportion of 70 sites occupied\"\n    ) +\n    theme_linedraw()\n```\n\n::: {.cell-output-display}\n![Occupancy and mean abundance in occupied sites for all 35 mite species.](Lab-04-biodiversity_files/figure-html/fig-lab4-answer-mite-oar-1.svg){#fig-lab4-answer-mite-oar}\n:::\n:::\n\n\nLCIL occurs in **55 of 70 sites** (occupancy **0.786**) and has mean local abundance **44.873**. Across species, occupancy tends to increase with mean local abundance. This describes spatial commonness and local abundance; it does not, on its own, establish niche breadth or distinguish habitat filtering from dispersal and detection effects. These interpretations are not marked.\n\n### 1.c Species accumulation of seaweeds\n\n**Marking: 3 marks.**\n\n- ✓ **1 mark:** correctly accumulate recorded species across coastal sections, with the identifier excluded from the species matrix.\n- ✓ **1 mark:** plot the calculated accumulation curve, ending at **846 species across 58 sections**.\n- ✓ **1 mark:** use readable axes identifying the number of sections sampled and cumulative species richness.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nseaweed_lab4 <- read.csv(\n    here::here(\"data\", \"BCB743\", \"seaweed\", \"SeaweedSpp.csv\"),\n    row.names = 1\n)\n# Remove the unrecorded species from the calculation.\nseaweed_recorded <- seaweed_lab4[, colSums(seaweed_lab4 > 0) > 0]\nseaweed_accum <- specaccum(seaweed_recorded, method = \"exact\")\nknitr::kable(data.frame(\n    sections = seaweed_accum$sites[c(1, 10, 30, 58)],\n    expected_richness = seaweed_accum$richness[c(1, 10, 30, 58)]\n), digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n| sections| expected_richness|\n|--------:|-----------------:|\n|        1|           259.241|\n|       10|           645.454|\n|       30|           771.343|\n|       58|           846.000|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(seaweed_accum,\n    ci.type = \"polygon\", col = \"indianred4\",\n    ci.col = \"steelblue2\", lwd = 2,\n    xlab = \"Number of coastal sections sampled\",\n    ylab = \"Expected cumulative species richness\"\n)\n```\n\n::: {.cell-output-display}\n![Exact sample-based species accumulation across the 58 seaweed coastal sections.](Lab-04-biodiversity_files/figure-html/fig-lab4-answer-seaweed-accum-1.svg){#fig-lab4-answer-seaweed-accum}\n:::\n:::\n\n\nExpected richness is **259.241** at one section, **645.454** at ten sections, **771.343** at thirty sections and **846** at all 58 sections. The file has 847 species columns, but `ANTNEM` contains no recorded presences. A randomised accumulation curve is also acceptable; intermediate estimates vary with the permutations, but the endpoint does not.\n\nThe curve describes the discovery of species as sections are added. Its horizontal axis is sampling effort, not measured habitat area: without comparable section areas it should not be labelled as area in square kilometres. The decreasing rate of addition does not demonstrate that every species on the coast has been detected. The purpose, interpretation and ecological implications are not marked.\n\n### 1.d Individual-based rarefaction of mites\n\n**Marking: 3 marks.**\n\n- ✓ **1 mark:** use the mite abundance counts to calculate individual-based rarefaction for the sites.\n- ✓ **1 mark:** correctly plot the site curves over sample sizes no greater than each site's observed number of individuals.\n- ✓ **1 mark:** label the axes as individuals sampled and expected species richness.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmite_raremax <- min(rowSums(mite))\nmite_rarefied <- rarefy(mite, sample = mite_raremax)\nknitr::kable(data.frame(\n    minimum_individuals = mite_raremax,\n    minimum_rarefied_richness = min(mite_rarefied),\n    maximum_rarefied_richness = max(mite_rarefied)\n), digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n| minimum_individuals| minimum_rarefied_richness| maximum_rarefied_richness|\n|-------------------:|-------------------------:|-------------------------:|\n|                   8|                     1.542|                     6.137|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrarecurve(mite,\n    step = 10, sample = mite_raremax,\n    col = \"indianred3\", label = FALSE,\n    xlab = \"Number of individuals sampled\",\n    ylab = \"Expected species richness\"\n)\n```\n\n::: {.cell-output-display}\n![Individual-based rarefaction curves for the 70 mite sites. The vertical line indicates the common sample size of eight individuals.](Lab-04-biodiversity_files/figure-html/fig-lab4-answer-mite-rarefaction-1.svg){#fig-lab4-answer-mite-rarefaction}\n:::\n:::\n\n\nObserved sample sizes range from **8 to 781 individuals**. At the common sample size of eight individuals, expected richness ranges from **1.542 to 6.137 species**. Rarefaction permits comparisons at equal numbers of individuals, but eight individuals provide little information about rarer species. It standardises the observed samples rather than guaranteeing equal completeness or identifying ecological mechanisms. The explanations and interpretations are not marked.\n\n### 2. The dominant species in the Doubs River data\n\n**Marking: 2 marks.**\n\n- ✓ **1 mark:** identify **Babl** (stone loach, *Barbatula barbatula*) as the species with the largest pooled abundance score.\n- ✓ **1 mark:** report its summed score of **73**, calculated across all 30 sites with the site identifier excluded.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndoubs_species_lab4 <- read.csv(\n    here::here(\"data\", \"BCB743\", \"DoubsSpe.csv\"),\n    row.names = 1\n)\ndoubs_totals_lab4 <- sort(colSums(doubs_species_lab4), decreasing = TRUE)\nknitr::kable(data.frame(\n    species = names(doubs_totals_lab4)[1:5],\n    pooled_abundance_score = unname(doubs_totals_lab4[1:5])\n), row.names = FALSE)\n```\n\n::: {.cell-output-display}\n\n\n|species | pooled_abundance_score|\n|:-------|----------------------:|\n|Babl    |                     73|\n|Phph    |                     68|\n|Ruru    |                     63|\n|Satr    |                     57|\n|Alal    |                     57|\n\n\n:::\n:::\n\n\nThe next highest pooled scores are **Phph = 68**, **Ruru = 63**, and **Satr = Alal = 57**. Here, dominance means the largest sum of the supplied abundance scores. It need not identify the dominant species at each site, the largest biomass, or the species with the largest ecological effect. The value 73 is a pooled score, not necessarily a count of 73 fish.\n\n### 3. Gradients and distance decay\n\n**No marks are assigned to this discussion.**\n\nDistance decay describes increasing compositional dissimilarity, or decreasing similarity, as separation increases. Elevation, depth and latitude can coincide with changes in temperature, light, pressure, oxygen, moisture or habitat. Species with different tolerances may replace one another along these environmental gradients, producing compositional changes that resemble geographic distance decay. In the Doubs River, downstream separation also covaries with river conditions, so geographic and environmental explanations can be difficult to separate.\n\nOrganisms respond to the associated conditions rather than necessarily to the coordinate itself. Geographic separation may additionally reduce dispersal, while barriers and history can contribute to the pattern. A gradient need not produce a smooth or monotonic response, and a distance-decay curve alone cannot establish which mechanism operates. Comparing compositional dissimilarity with both environmental and geographic distances, and considering spatial dependence, would help evaluate these alternatives.\n:::\n\n\n\n:::{.callout-important}\n## Submission Instructions\n\nThe Lab 4 assignment is due at **08:00 on Monday, 28 September 2026** and\nwill not be pre-assessed. It must nevertheless be uploaded to iKamva by the\nstated deadline and completed as a self-assessed submission. Upload the\ncompleted self-assessment to iKamva by 23:59 on the same day. See the\n[Lab submission and self-assessment policy](BDC334_syllabus.qmd#sec-lab-self-assessment)\nfor the checking and penalty rules.\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}