{
  "hash": "05ca3fbe9818154466f4132cf69813e9",
  "result": {
    "engine": "knitr",
    "markdown": "---\ndate: \"2021-01-01\"\ntitle: \"7. *t*-Tests\"\nsubtitle: \"One-Sample, Two-Sample, and Paired Mean Comparisons\"\nreference-location: margin\n---\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n::: {.callout-note appearance=\"simple\"}\n## In This Chapter\n\n-   One-sample *t*-tests\n-   Two-sample s *t*-tests\n-   Paired *t*-tests\n-   Comparison of proportions\n:::\n\n::: {.callout-note appearance=\"simple\"}\n## Required Reading\n- My book chapter on [one sample hypotheses](../../docs/AJ Smit - Biostatistics--The-Book - One-sample Hypotheses.pdf) (DRAFT).\n:::\n\n::: {.callout-important appearance=\"simple\"}\n## Tasks to Complete in This Chapter\n\n-   Task F\n:::\n\n# Introduction\n\nAs biologists, we often want to use sample data to make an inference about a larger population. Sometimes we want to know whether the mean of a single sample differs from an expected value. At other times we want to compare the means of two groups, or the mean change within the same individuals measured twice. The family of tests most commonly used for these questions are *t*-tests.\n\nA *t*-test is therefore not only a test for comparing two groups. More generally, it is a statistical hypothesis test used to assess whether a sample mean, or the difference between two means, is likely to be zero under a null hypothesis. The exact form of the test depends on the structure of the data:\n\n-   in a **one-sample *t*-test** we compare one sample mean, $\\bar{x}$, against a known or hypothesised value, $\\mu_{0}$;\n-   in a **two-sample *t*-test** we compare the means of two independent groups, $\\bar{A}$ and $\\bar{B}$;\n-   in a **paired *t*-test** we compare the mean difference, $\\bar{d}$, between matched measurements.\n\nThese questions arise frequently in ecology and biology. We might ask whether the mean chlorophyll concentration in a lagoon differs from a regulatory threshold, whether the mean size of plants differs between a control and a treatment, or whether the same individuals are heavier after a feeding trial than before it started.\n\nIn all cases, we work with sample data but wish to say something about the population from which the sample was drawn. This means that the logic of the chapter must begin with the inferential question, the hypotheses, and the nature of the data before we rush to the function in R.\n\n# Key Concepts\n\nThese ideas define the logic of the chapter before we move into the worked tests.\n\n- ***t*-test:** A statistical hypothesis test used to determine whether a sample mean, or a difference between means, is consistent with a null hypothesis.\n- **One-sample vs. two-sample vs. paired:** The choice of *t*-test depends on the data structure: one sample against a fixed value, two independent groups against one another, or two related measurements on the same sampling units.\n- **One-sided vs. two-sided tests:** A two-sided test asks whether a value differs in either direction, while a one-sided test asks whether the difference is specifically greater than or less than zero.\n- **Student versus Welch:** Student's *t*-test assumes equal variances between groups; Welch's *t*-test relaxes this assumption and is the default in R.\n- **Assumptions matter:** The appropriateness of a *t*-test depends on the nature of the data, especially the scale of measurement, independence, approximate normality, and in the two-sample case the equality or inequality of variances.\n- **Non-parametric alternatives:** When the assumptions for a *t*-test are not met, rank-based alternatives such as `wilcox.test()` may be more appropriate.\n- **`t.test()` is the main R function:** The same function handles one-sample, two-sample, and paired designs through arguments such as `mu`, `paired`, `var.equal`, and `alternative`.\n\n# Nature of the Data and Assumptions\n\nThe appropriateness of a *t*-test hinges on the nature of the response data and on the study design.\n\n-   **Continuous response variable** The response variable should be measured on a continuous scale, such as length, mass, concentration, or temperature.\n\n-   **Correct data structure** The design determines which *t*-test is appropriate:\n\n    -   **One-sample *t*-test** when one sample is compared to a hypothesised mean, $\\mu_{0}$;\n    -   **Independent two-sample *t*-test** when two groups are made up of different individuals or sampling units;\n    -   **Paired *t*-test** when measurements are matched, such as before-and-after measurements on the same individuals or matched pairs.\n\n-   **Independence** The observations used in the test must be independent in the way assumed by the design. In a two-sample test, observations in one group should not determine those in the other group. In a paired design, the pairs are deliberate, but the pairs themselves should still be independent of one another.\n\n-   **Approximate normality** The data, or more precisely the relevant differences or sampling distribution, should be approximately normally distributed for Student's or Welch's *t*-tests. If this assumption is not met, especially in small samples, you should consider a non-parametric alternative such as the Wilcoxon signed-rank test or the Mann-Whitney test via `wilcox.test()`. This assumption is relaxed in larger samples because of the [Central Limit Theorem](04-distributions-sampling-uncertainty.qmd).\n\n-   **Homoscedasticity for Student's two-sample test** In a classical Student's two-sample *t*-test, the variances of the two groups should be approximately equal. If this assumption is not met, you should use Welch's *t*-test instead. In R, Welch's test is the default, and a Student's test is obtained by setting `var.equal = TRUE`.\n\n-   **Random sampling or random assignment** The data should come from a defensible sampling design so that the observations are representative of the population or experimental process of interest.\n\nBefore carrying out a *t*-test, you should examine the data visually and statistically. Histograms, boxplots, Q-Q plots, and tests such as `shapiro.test()` or Levene's test help you decide whether the parametric route is appropriate. When assumptions fail badly, please refer back to [Chapter 6](06-assumptions-and-transformations.qmd) for remedies and alternatives.\n\n# R Functions\n\nThe main function used throughout this chapter is `t.test()`. It can be used for:\n\n-   one-sample *t*-tests by specifying `mu = ...`,\n-   independent two-sample *t*-tests using either `x, y` or a formula such as `response ~ group`,\n-   paired *t*-tests by specifying `paired = TRUE`.\n\nThe most important arguments are:\n\n-   `mu` for the hypothesised mean in a one-sample test,\n-   `alternative` to choose `\"two.sided\"`, `\"less\"`, or `\"greater\"`,\n-   `paired` to indicate matched observations,\n-   `var.equal` to request Student's two-sample *t*-test rather than Welch's.\n\nWhen the assumptions for a *t*-test are not met, the main alternative used in this chapter is `wilcox.test()`. For one-sample and paired settings it serves as a rank-based alternative to the *t*-test, and for two independent groups it provides the Mann-Whitney or Wilcoxon rank-sum approach, depending on the argument structure.\n\n# A Simple Experimental Logic\n\n::: callout-important\n## Do This Now!\n**Task F.1.** Work with two friends and devise a real 'experiment' (or designed sampling to determine some real-world phenomenon, more likely) in which you demonstrate the following two principles:\n\na. the effect of sample size on the estimate of the mean and variance (use SD),\nb. the effect of repeated sampling on the value of the mean and variance. In both cases, apply the correct *t*-test (later in this Chapter) to test whether sample size and repeat sampling has a statistically significant effect. What conclusion do you reach?\n\nReport back comprehensively with Task F.\n:::\n\nThe simplest experiment that makes any scientific sense is one where data are collected to represent two groups --- maybe a treatment compared to a control. For example, \"does adding manure to some plants have a measurable effect on their growth compared to the situation where nothing was added that might affect the plants' growth?\" To answer this very basic question one often uses a ***t*-test**. \n\nThe most commonly used *t*-test is **Student's *t*-test**[^1], a statistical hypothesis test used to determine whether two samples of data are significantly different from each other. It was introduced by William Gosset, who wrote under the pseudonym 'Student,' in 1908. This is a parametric test, and as already indicated, it assumes the data are normally distributed, that the variances of the two samples being compared are equal.\n\n[^1]: Whereas the Student's *t*-test applies to data whose variances are equal among the two groups, the **Welch's *t*-test** is used when the variances are unequal. The Welch's *t*-test is a more robust test, is preferred when the sample sizes are unequal or the variances are unequal. The Welch's *t*-test is the default setting in the`t.test()` function in R (through the argument `var.equal = FALSE`, which is the default).\n\nNow it becomes interesting. There are several flavours of *t*-tests, depending on the nature of our samples, the type of question being asked but all of them involve comparing two samples. Specifically, *the comparison involves the sample means*, and as such, they test whether or not the central tendencies of two samples differ. Here are the variations:\n\n-   **One-sample *t*-tests:** only one sample set of data that we wish to compare against a known population mean:\n\n    -   one-sided one-sample *t*-tests\n    -   two-sided one-sample *t*-tests\n\n-   **Two-sample (or independent sample) *t*-tests:** the means of two groups are compared against each other:\n\n    -   one-sided two-sample *t*-tests\n    -   two-sided two-sample *t*-tests\n\n-   **Paired sample *t*-tests:** two samples that are 'matched' or as the name indicates, *paired*, *i.e.* they are not independent of one another:\n\n    -   one-sided\n    -   two-sided\n\nLet us go into detail into each of these variations of *t*-tests.\n\n# One-sample *t*-tests\n\nSometimes we have only one sample, but we still want to make an inference about a population. In that case the question is not whether two groups differ from one another, but whether the mean of our sample differs from some hypothesised value, $\\mu_{0}$. That hypothesised value may come from a regulatory threshold, a historical mean, a theoretical expectation, or a biologically meaningful reference point.\n\nThe one-sample *t*-test asks whether the difference between the sample mean, $\\bar{x}$, and the hypothesised mean, $\\mu_{0}$, is large relative to the variation in the sample. As in the one-sample hypothesis chapter in `BCB_Stats`, the logic should always proceed in the same order: first decide whether the one-sample design is appropriate, then state the hypotheses, then look carefully at the data, and only then run `t.test()`.\n\n## When to use a one-sample *t*-test\n\nUse a one-sample *t*-test when:\n\n-   you have one sample of observations;\n-   the response variable is continuous;\n-   the observations are independent;\n-   you want to compare the sample mean against a known or hypothesised value, $\\mu_{0}$;\n-   the data are approximately normally distributed, or the sample size is large enough that the test is reasonably robust.\n\nIf you already know the direction of the expected effect before seeing the data, you may use a one-sided test. If you simply want to know whether the mean differs from $\\mu_{0}$ in either direction, use a two-sided test.\n\n## Two-sided one-sample *t*-test\n\n::: {.callout-note}\n## Hypothesis for two-sided one-sample *t*-test\n\n$$H_{0}: \\bar{x} = \\mu_{0}$$\n$$H_{a}: \\bar{x} \\ne \\mu_{0}$$\n\nThis is the same as:\n\n$$H_{0}: \\bar{x} - \\mu_{0} = 0$$\n$$H_{a}: \\bar{x} - \\mu_{0} \\ne 0$$\n\nHere $\\bar{x}$ is the sample mean and $\\mu_{0}$ is the hypothesised population mean against which the sample is being compared.\n\nBecause this is a two-sided test, the alternative hypothesis does not specify direction. We are asking whether $\\bar{x}$ differs from $\\mu_{0}$, not whether it is specifically less than or greater than $\\mu_{0}$.\n:::\n\nIn R, a one-sample *t*-test is done with `t.test(x, mu = ...)`. The default is a two-sided test, so unless you specify otherwise, `t.test()` evaluates whether the sample mean differs from $\\mu_{0}$ in either direction.\n\n::: {.column-margin}\n**The one-sample *t*-test:**\n\n$$t = \\frac{\\overline{x} - \\mu}{s / \\sqrt{n}}$$ {#eq-onesample}\n\nwhere $t$ is the calculated $t$-value, $\\overline{x}$ is the sample mean, $\\mu$ is the hypothesised population mean, $s$ is the sample standard deviation,$n$ the sample size.\n:::\n\n## A worked one-sample example\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# create a single sample of random normal data\nset.seed(666)\nr_one <- data.frame(dat = rnorm(n = 20, mean = 20, sd = 5),\n                    sample = \"A\")\n```\n:::\n\n\nWe will work with one sample of random normal data and compare its mean against two possible reference values. The purpose of the example is to run the test and to see how the result depends on the hypothesised mean, $\\mu_{0}$.\n\n### Do an exploratory data analysis (EDA)\n\nBefore fitting the test, we should inspect the data numerically and graphically.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(r_one$dat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR>    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \nR>   8.916  15.358  20.230  20.007  24.021  30.750\n```\n\n\n:::\n\n```{.r .cell-code}\nsd(r_one$dat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR> [1] 6.611199\n```\n\n\n:::\n\n```{.r .cell-code}\nshapiro.test(r_one$dat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR> \nR> \tShapiro-Wilk normality test\nR> \nR> data:  r_one$dat\nR> W = 0.94911, p-value = 0.3538\n```\n\n\n:::\n:::\n\n\nThe sample is small, so it is useful to check both the summary statistics and the approximate normality of the observations. We should also look at a plot.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(data = r_one, aes(y = dat, x = sample)) +\n  geom_boxplot(fill = \"indianred\", notch = TRUE,\n               alpha = 0.3, colour = \"black\") +\n  # population  mean (mu) = 20\n  geom_hline(yintercept = 20, colour = \"dodgerblue2\", \n             size = 0.9) +\n  # population  mean (mu) = 30\n  geom_hline(yintercept = 30, colour = \"indianred2\", \n             size = 0.9) +\n  labs(y = \"Value\", x = NULL) +\n  coord_flip() +\n  theme_pubclean()\n```\n\n::: {.cell-output-display}\n![Boxplot of random normal data with. A hypothetical (reference) population mean of 20 is shown as a blue line, with the red line showing another reference mean of 30.](07-t_tests_files/figure-html/fig-boxplot1-1.svg){#fig-boxplot1 fig-align='center' width=78%}\n:::\n:::\n\n\nThe boxplot shows the sample distribution relative to two possible hypothesised means. Visually, the sample appears to be centred much closer to 20 than to 30. That immediately suggests that a test against 20 may not be significant, whereas a test against 30 may be.\n\n### State the hypotheses\n\nSuppose we first ask whether this sample could reasonably have come from a population with mean 20. The hypotheses are:\n\n$$H_{0}: \\mu = 20$$\n$$H_{a}: \\mu \\ne 20$$\n\nWe can then ask the same question for a hypothesised population mean of 30:\n\n$$H_{0}: \\mu = 30$$\n$$H_{a}: \\mu \\ne 30$$\n\n### Apply the test\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# compare random data against a population mean of 20\nt.test(r_one$dat, mu = 20)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR> \nR> \tOne Sample t-test\nR> \nR> data:  r_one$dat\nR> t = 0.0048653, df = 19, p-value = 0.9962\nR> alternative hypothesis: true mean is not equal to 20\nR> 95 percent confidence interval:\nR>  16.91306 23.10133\nR> sample estimates:\nR> mean of x \nR>  20.00719\n```\n\n\n:::\n\n```{.r .cell-code}\n# compare random data against a population mean of 30\nt.test(r_one$dat, mu = 30)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR> \nR> \tOne Sample t-test\nR> \nR> data:  r_one$dat\nR> t = -6.7596, df = 19, p-value = 1.858e-06\nR> alternative hypothesis: true mean is not equal to 30\nR> 95 percent confidence interval:\nR>  16.91306 23.10133\nR> sample estimates:\nR> mean of x \nR>  20.00719\n```\n\n\n:::\n:::\n\n\n### Interpret the results\n\nThe test against $\\mu_{0} = 20$ asks whether the observed sample mean is far enough from 20, relative to the sample variation, to reject the null hypothesis. The test against $\\mu_{0} = 30$ asks the same question, but now the hypothesised mean is much farther from the centre of the observed data.\n\nThis is the key inferential logic of the one-sample *t*-test: the same data can support different conclusions depending on the null value being tested. The output should therefore always be interpreted in relation to the biological or experimental meaning of $\\mu_{0}$.\n\n### Reporting\n\nWhen reporting a one-sample *t*-test, state:\n\n-   the sample mean and its units;\n-   the hypothesised mean, $\\mu_{0}$;\n-   the *t* statistic and degrees of freedom;\n-   the *p*-value;\n-   a short biological interpretation of the result.\n\nFor example, you might report:\n\n> The mean of the sample ($\\bar{x} = 20.01, SD = 6.61, n = 20)$ did not differ from the hypothesised value of $\\mu_0 = 20$ (one-sample *t*-test: $t_{19} = 0.005, p > 0.05$). The 95% confidence interval for the mean ($16.91$ to $23.10$) included the reference value, indicating that the observed data are consistent with a population mean of 20.\n>\n> In contrast, the sample mean differed from a hypothesised value of $\\mu_0 = 30$ ($t_{19} = -6.76$, $p < 0.001$). The same confidence interval ($16.91$ to $23.10$) did not include 30, indicating that the observed values are not compatible with a population mean of 30.\n> \n> Together, these results show that inference depends on the hypothesised reference value: the data support a mean near 20 but provide strong evidence against a mean of 30.\n\n\n\n## One-sided one-sample *t*-tests\n\n::: {.callout-note}\n## Hypothesis for one-sided one-sample *t*-test\n\nFor example, when we are concerned that our sample mean, $\\bar{x}$, should be less than the *a priori* established value, $\\mu_{0}$:\n\n$$H_{0}: \\bar{x} \\ge \\mu_{0}$$\n$$H_{a}: \\bar{x} \\lt \\mu_{0}$$\n\nOnly one of the two options is shown.\n:::\n\nOne-sided tests are used when the direction of the alternative hypothesis is specified before the data are analysed. For example, we may wish to know whether the sample mean is specifically less than $\\mu_{0}$, or specifically greater than $\\mu_{0}$. This must be justified by the scientific question.\n\nIn R, one-sided one-sample tests are requested with the `alternative` argument:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# check against the trailing tail\nt.test(r_one$dat, mu = 30, alternative = \"less\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR> \nR> \tOne Sample t-test\nR> \nR> data:  r_one$dat\nR> t = -6.7596, df = 19, p-value = 9.292e-07\nR> alternative hypothesis: true mean is less than 30\nR> 95 percent confidence interval:\nR>      -Inf 22.56339\nR> sample estimates:\nR> mean of x \nR>  20.00719\n```\n\n\n:::\n\n```{.r .cell-code}\n# check against the leading tail\nt.test(r_one$dat, mu = 30, alternative = \"greater\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR> \nR> \tOne Sample t-test\nR> \nR> data:  r_one$dat\nR> t = -6.7596, df = 19, p-value = 1\nR> alternative hypothesis: true mean is greater than 30\nR> 95 percent confidence interval:\nR>  17.451    Inf\nR> sample estimates:\nR> mean of x \nR>  20.00719\n```\n\n\n:::\n:::\n\n\nAre these the results we would have expected? Why does the second test not return a significant result? The answer lies in the direction of the alternative hypothesis: the first test asks whether the mean is less than 30, which is compatible with the data, whereas the second asks whether the mean is greater than 30, which is not.\n\n## If assumptions fail\n\nIf the observations are strongly non-normal, especially in small samples, or if the data contain severe outliers that undermine the mean-based logic of the test, a one-sample *t*-test may not be appropriate. In such cases, a rank-based alternative such as `wilcox.test()` may be more defensible. The broader reasoning behind the checking of assumptions and deciding on alternatives is discussed in [Chapter 6](06-assumptions-and-transformations.qmd).\n\n::: callout-important\n## Do This Now!\nCreate a visualisation to graphically demonstrate the outcome of this *t*-test.\n:::\n\n# Two-sample *t*-tests\n\nVery often, however, the inferential question is not whether one sample differs from a fixed value, but whether the means of two groups differ from one another. This happens when we compare a control against a treatment, one habitat against another, or one species against another. The response variable is still continuous, but now the grouping variable has two levels.\n\nIn this case we use a **two-sample *t*-test**, also called an **independent-samples *t*-test**, because the observations in the two groups are assumed to be independent. As with the one-sample test, the logic must still proceed in the same order: decide whether the design is appropriate, state the hypotheses, examine the data, choose the correct version of the test, and then interpret the result in biological terms.\n\n## When to use a two-sample *t*-test\n\nUse a two-sample *t*-test when:\n\n-   you have a continuous response variable;\n-   you have two groups to compare;\n-   the observations in one group are independent of those in the other group;\n-   the data in each group are approximately normal, or the sample sizes are large enough for the test to be robust;\n-   you are interested in whether the difference between the group means is zero.\n\nAt this point we must also decide which two-sample *t*-test is appropriate. If the two groups have approximately equal variances, we may use **Student's *t*-test**. If the variances differ, we use **Welch's *t*-test**, which is more robust and is the default in R.\n\n## Two-sided two-sample *t*-test\n\n::: {.callout-note}\n## Hypothesis for two-sided two-sample *t*-test\n\n$$H_{0}: \\bar{A} = \\bar{B}$$\n$$H_{a}: \\bar{A} \\ne \\bar{B}$$\n\nwhere $\\bar{A}$ is the population mean of the first sample and $\\bar{B}$ the population mean of the second sample. In this example we have a two-sided two-sample *t*-test, which is the default in R's `t.test()` function.\n\nThis is the same as saying:\n\n$$H_{0}: \\bar{A} - \\bar{B} = 0$$\n$$H_{a}: \\bar{A} - \\bar{B} \\ne 0$$\n\nAgain, $H_{0}$ does not distinguish between whether the difference is greater than or less than 0. We are simply asking whether the two means differ.\n:::\n\nThis is the most common *t*-test in experimental biology. We use it when our two samples come from different individuals or sampling units, and when there is no natural pairing between the observations.\n\n## Student's versus Welch's *t*-test\n\nThere are two main varieties of the two-sample *t*-test. In the case of samples whose variances do not differ appreciably, we may perform a **Student's *t*-test**. @eq-tstat shows how the *t*-statistic is calculated for Student's *t*-test. If the variances differ between the two groups, we instead perform **Welch's *t*-test** as written in @eq-welch. Welch's *t*-test is more robust and is therefore the default in R's `t.test()` function.\n\n::: {.column-margin}\n**Student's *t*-test:**\n$$t=\\frac{\\bar{A}-\\bar{B}}{\\sqrt{\\frac{S^{2}}{n}+\\frac{S^{2}}{m}}}$$ {#eq-tstat}\n\n$\\bar{A}$$\\bar{B}$ are the means for groups $A$$B$, respectively; $n$$m$ are the sample sizes of the two sets of samples, respectively;$S^{2}$ is the pooled variance, which is calculated as per @eq-pooledvar:\n\n$$S^{2}=\\frac{(n-1)S_{A}^{2}+(m-1)S_{B}^{2} }{n+m-2}$$ {#eq-pooledvar}\n\nThe degrees of freedom, *d.f.*, in the equation for the shared variance is $n_{A}+m_{B}-2$.\n:::\n\n::: {.column-margin}\n**Welch's *t*-test:**\n$$t=\\frac{\\bar{A}-\\bar{B}}{\\sqrt{\\frac{S^{2}_{A}}{n}+\\frac{S^{2}_{B}}{m}}}$$ {#eq-welch}\n\nHere, $S_{A}$$S_{B}$ are the variances of groups $A$$B$, respectively (see Section X). The *d.f.* to use with Welch's *t*-test is obtained using the Welch--Satterthwaite equation (@eq-satterthwaite):\n\n$$d.f. = \\frac{\\left( \\frac{S^{2}_{A}}{n}+\\frac{S^{2}_{B}}{m} \\right)^{2}}{\\left( \\frac{S^{4}_{A}}{n-1} + \\frac{S^{4}_{B}}{m-1} \\right)}$$ {#eq-satterthwaite}\n:::\n\nIn the olden days, we had to calculate the *t*-statistic and degrees of freedom by hand and then read probabilities from a printed table. R now does this for us automatically, but the formulas still matter because they explain why Student's and Welch's tests differ.\n\n## A worked two-sample example\n\nLet us generate some new random normal data and ask whether the values in two independent groups differ from one another.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# random normal data\nset.seed(666)\nr_two <- data.frame(dat = c(rnorm(n = 20, mean = 4, sd = 1),\n                            rnorm(n = 20, mean = 5, sd = 1)),\n                    sample = c(rep(\"A\", 20), rep(\"B\", 20)))\n```\n:::\n\n\n### Do an exploratory data analysis (EDA)\n\nAs before, we begin by exploring the data before fitting a model.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nr_two |>\n  group_by(sample) |>\n  summarise(\n    n = n(),\n    mean = mean(dat),\n    sd = sd(dat),\n    .groups = \"drop\"\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR> # A tibble: 2 × 4\nR>   sample     n  mean    sd\nR>   <chr>  <int> <dbl> <dbl>\nR> 1 A         20  4.00  1.32\nR> 2 B         20  4.75  1.08\n```\n\n\n:::\n\n```{.r .cell-code}\nby(r_two$dat, r_two$sample, shapiro.test)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR> r_two$sample: A\nR> \nR> \tShapiro-Wilk normality test\nR> \nR> data:  dd[x, ]\nR> W = 0.94911, p-value = 0.3538\nR> \nR> ------------------------------------------------------------ \nR> r_two$sample: B\nR> \nR> \tShapiro-Wilk normality test\nR> \nR> data:  dd[x, ]\nR> W = 0.94942, p-value = 0.3584\n```\n\n\n:::\n:::\n\n\nThe summaries tell us whether the two groups differ in their sample means and whether their spread appears similar. We should also inspect the groups visually.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(data = r_two, aes(x = sample, y = dat, fill = sample)) +\n  geom_boxplot(alpha = 0.35, colour = \"black\", outlier.shape = NA) +\n  geom_jitter(width = 0.08, alpha = 0.7, size = 1.8) +\n  labs(x = \"Group\", y = \"Value\") +\n  theme_pubclean() +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![Boxplots of two independent samples. Group B has a slightly higher mean than Group A, but the spread is similar.](07-t_tests_files/figure-html/fig-boxplot2-1.svg){#fig-boxplot2 fig-align='center' width=78%}\n:::\n:::\n\n\nThe boxplots suggest that the two groups are roughly similar in spread, but that Group B may have a higher mean than Group A. Because these data were simulated with the same standard deviation, a Student's *t*-test is appropriate here.\n\n### State the hypotheses\n\nFor a two-sided comparison, the hypotheses are:\n\n$$H_{0}: \\mu_{A} = \\mu_{B}$$\n$$H_{a}: \\mu_{A} \\ne \\mu_{B}$$\n\nEquivalently:\n\n$$H_{0}: \\mu_{A} - \\mu_{B} = 0$$\n$$H_{a}: \\mu_{A} - \\mu_{B} \\ne 0$$\n\n### Apply the test\n\nNow we apply the *t*-test. Note how we set the `var.equal` argument to `TRUE` because we know these simulated data have the same standard deviation.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# perform t-test\n# note how we set the `var.equal` argument to TRUE because we know\n# our data has the same SD (they are simulated as such!)\nt.test(dat ~ sample, data = r_two, var.equal = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR> \nR> \tTwo Sample t-test\nR> \nR> data:  dat by sample\nR> t = -1.9544, df = 38, p-value = 0.05805\nR> alternative hypothesis: true difference in means between group A and group B is not equal to 0\nR> 95 percent confidence interval:\nR>  -1.51699175  0.02670136\nR> sample estimates:\nR> mean in group A mean in group B \nR>        4.001438        4.746584\n```\n\n\n:::\n\n```{.r .cell-code}\n# if the variances are not equal, simply set `var.equal` to false\n# and a Welch's t-test will be performed\n```\n:::\n\n\nThe first argument we see in `t.test()` is `dat ~ sample`. Usually in R when we see a `~` (tilde), we are creating what is known as a formula. A formula tells R how it should look for relationships between a response and a grouping or explanatory variable. In our code above, `dat ~ sample` means that the values in the `dat` column are being compared across the levels of the `sample` column. We will see this same formula notation repeatedly later in ANOVAs and linear models.\n\n### Interpret the results\n\nThe two-sample *t*-test asks whether the observed difference between the group means is large relative to the variation within the groups. If the *p*-value is small, we reject the null hypothesis that the mean difference is zero. If the *p*-value is not small, we conclude that the data do not provide strong evidence for a difference in means.\n\nThe confidence interval is also important. It gives an estimated range for the mean difference between the two groups. If this interval excludes zero, the result is consistent with a statistically significant difference.\n\n### Reporting\n\nWhen reporting a two-sample *t*-test, state:\n\n-   the mean and spread for each group;\n-   whether you used Student's or Welch's *t*-test;\n-   the *t* statistic and degrees of freedom;\n-   the *p*-value;\n-   a brief biological interpretation of the mean difference.\n\nFor example, you might report:\n\n> The mean value in Group A was $4.00 \\pm 1.32$ (SD, $n = 20$), while the mean value in Group B was $4.75 \\pm 1.08$ (SD, $n = 20$). A two-sample Student's *t*-test indicated that this difference was not statistically significant at the 0.05 level ($t_{38} = -1.95$, $p > 0.05$). The 95% confidence interval for the mean difference between the groups ranged from $-1.52$ to $0.03$, which included zero. These data therefore suggest that, although Group B tended to have the higher mean, the evidence was not quite strong enough to conclude that the population means differ.\n\n\n\n::: callout-important\n## Do This Now!\nCreate a visualisation to graphically demonstrate the outcome of this *t*-test.\n:::\n\n## One-sided two-sample *t*-test\n\n::: {.callout-note}\n## Hypothesis for one-sided two-sample *t*-test\n\nFor example, when we are concerned that the sample mean of the first population, $\\bar{A}$, should be greater than that of the second, $\\bar{B}$:\n\n$$H_{0}: \\bar{A} \\le \\bar{B}$$\n$$H_{a}: \\bar{A} \\gt \\bar{B}$$\n\nOnly one of the two options is shown.\n:::\n\nJust as with the one-sample *t*-tests above, we may also specify which tail of the distribution we are interested in when we compare the means of two samples. This is a **one-sided two-sample *t*-test**. Here too we may use either Student's or Welch's form, depending on the variances. The direction of the test must be justified before looking at the results.\n\nIn R we do this with the `alternative` argument:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# is the mean of sample B smaller than that of sample A?\ncompare_means(dat ~ sample, data = r_two,\n              method = \"t.test\", var.equal = TRUE,\n              alternative = \"less\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR> # A tibble: 1 × 8\nR>   .y.   group1 group2     p p.adj p.format p.signif method\nR>   <chr> <chr>  <chr>  <dbl> <dbl> <chr>    <chr>    <chr> \nR> 1 dat   A      B      0.971  0.97 0.97     ns       T-test\n```\n\n\n:::\n\n```{.r .cell-code}\n# is the mean of sample B greater than that of sample A?\ncompare_means(dat ~ sample, data = r_two,\n              method = \"t.test\", var.equal = TRUE,\n              alternative = \"greater\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR> # A tibble: 1 × 8\nR>   .y.   group1 group2      p p.adj p.format p.signif method\nR>   <chr> <chr>  <chr>   <dbl> <dbl> <chr>    <chr>    <chr> \nR> 1 dat   A      B      0.0290 0.029 0.029    *        T-test\n```\n\n\n:::\n:::\n\n\nWhat do these results show? Is this surprising? It should not be. The data were generated so that Group B tends to be larger than Group A, so a directional test framed that way is more likely to support the alternative than one framed in the opposite direction.\n\n## If assumptions fail\n\nIf the group variances differ, use Welch's *t*-test rather than Student's *t*-test. If the data are badly non-normal, strongly skewed, or dominated by outliers, a rank-based alternative such as `wilcox.test()` may be preferable. The broader workflow for checking assumptions and choosing alternatives is dealt with in [Chapter 6](06-assumptions-and-transformations.qmd).\n\n# Paired *t*-tests\n\nSometimes the two measurements we want to compare do not come from different individuals or sampling units, but from the same units measured twice, or from units that have been deliberately matched. In such cases the observations are not independent across the two groups, and a standard two-sample *t*-test is no longer appropriate.\n\nThe logic of the paired *t*-test is therefore slightly different. We do not compare two independent means directly. Instead, we calculate the difference within each pair, and then ask whether the mean of those differences is zero. In other words, the paired *t*-test is really a one-sample *t*-test applied to the set of paired differences.\n\n## When to use a paired *t*-test\n\nUse a paired *t*-test when:\n\n-   the response variable is continuous;\n-   each observation in one group is naturally matched to one observation in the other group;\n-   the pairing is meaningful, such as before-and-after measurements on the same individuals, left-versus-right measurements on the same organism, or deliberately matched experimental units;\n-   the paired differences are approximately normally distributed.\n\nThe crucial point is that the analysis focuses on the **differences within pairs**, not on the raw values considered as though they came from independent groups.\n\n::: {.callout-note}\n## Hypothesis for two-sided Paired *t*-test\n\n$$H_{0}: \\bar{d} = 0$$\n$$H_{a}: \\bar{d} \\ne 0$$\n\nwhere $\\bar{d}$ is the mean population difference based on the matched pairs.\n\nAgain, here $H_{0}$ does not consider if differences are greater than or less than 0 --- a difference in either direction is significant. One-sided versions of the hypothesis can be stated as well.\n:::\n\n::: {.column-margin}\n**Paired *t*-test:**\n$$t = \\frac{\\bar{d}}{s_d/\\sqrt{n}}$$\n\nwhere $\\bar{d}$ is the sample mean of the differences between paired observations, $s_d$ is the sample standard deviation of the differences,$n$ is the number of pairs. The resulting $t$-statistic is then compared to the appropriate $t$-distribution with $n-1$ degrees of freedom to determine the $p$-value.\n:::\n\nPaired *t*-tests are therefore used when the dependence between observations is not a problem to be ignored, but the central feature of the design. This test is also sometimes called a dependent-samples *t*-test or a repeated-measures *t*-test.\n\nFor example, we might want to determine whether the right arms of a group of people differ in length from their left arms. For each individual, the right arm measurement is matched to the left arm measurement from the same person. Or, we may wish to determine whether piglets weigh more after a feeding trial than they did at the start of the trial. Each individual piglet then contributes a before-and-after pair of measurements.\n\n## A worked paired example\n\nLet us use a small example in which piglets are weighed before and after a three-week feeding period. The inferential question is whether body mass increases over time within the same individuals.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(666)\npiglets <- data.frame(\n  id = 1:12,\n  before = round(rnorm(12, mean = 8.2, sd = 0.7), 2),\n  after = round(rnorm(12, mean = 9.0, sd = 0.7), 2)\n)\n\npiglets$diff <- piglets$after - piglets$before\npiglets\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR>    id before after  diff\nR> 1   1   8.73  9.61  0.88\nR> 2   2   9.61  7.80 -1.81\nR> 3   3   7.95  9.09  1.14\nR> 4   4   9.62  8.95 -0.67\nR> 5   5   6.65  9.60  2.95\nR> 6   6   8.73  9.24  0.51\nR> 7   7   7.29  8.59  1.30\nR> 8   8   7.64  9.55  1.91\nR> 9   9   6.95  8.52  1.57\nR> 10 10   8.17  8.17  0.00\nR> 11 11   9.71  9.89  0.18\nR> 12 12   6.96  8.78  1.82\n```\n\n\n:::\n:::\n\n\n### Do an exploratory data analysis (EDA)\n\nBefore running the paired *t*-test, we should inspect the paired differences because these are the values that the test uses directly.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(piglets$diff)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR>    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \nR>  -1.810   0.135   1.010   0.815   1.633   2.950\n```\n\n\n:::\n\n```{.r .cell-code}\nsd(piglets$diff)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR> [1] 1.277024\n```\n\n\n:::\n\n```{.r .cell-code}\nshapiro.test(piglets$diff)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR> \nR> \tShapiro-Wilk normality test\nR> \nR> data:  piglets$diff\nR> W = 0.9798, p-value = 0.9828\n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(data = piglets, aes(x = diff)) +\n  geom_histogram(binwidth = 0.5, fill = \"indianred\", colour = \"black\", alpha = 0.5) +\n  geom_vline(xintercept = 0, colour = \"dodgerblue2\", linewidth = 0.9) +\n  labs(x = \"Paired difference in mass (after - before)\", y = \"Frequency\") +\n  theme_pubclean()\n```\n\n::: {.cell-output-display}\n![Distribution of paired differences in piglet body mass after minus before the feeding period.](07-t_tests_files/figure-html/fig-paired-differences-1.svg){#fig-paired-differences fig-align='center' width=78%}\n:::\n:::\n\n\nThe distribution of paired differences is centred above zero, which already suggests that the piglets tended to be heavier after the feeding period. The Shapiro-Wilk test also indicates that the differences are reasonably consistent with normality, so a paired *t*-test is appropriate.\n\n### State the hypotheses\n\nFor a two-sided paired *t*-test, the hypotheses are:\n\n$$H_{0}: \\mu_{d} = 0$$\n$$H_{a}: \\mu_{d} \\ne 0$$\n\nwhere $\\mu_{d}$ is the population mean of the paired differences. If we had a strictly directional biological question, such as whether piglets are heavier after feeding than before, we could also frame this as a one-sided test.\n\n### Apply the test\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nt.test(piglets$after, piglets$before, paired = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR> \nR> \tPaired t-test\nR> \nR> data:  piglets$after and piglets$before\nR> t = 2.2108, df = 11, p-value = 0.04915\nR> alternative hypothesis: true mean difference is not equal to 0\nR> 95 percent confidence interval:\nR>  0.003617508 1.626382492\nR> sample estimates:\nR> mean difference \nR>           0.815\n```\n\n\n:::\n:::\n\n\nWe can also use the formula interface with paired data if the data are arranged appropriately, but in practice the paired vectors are often the clearest way to express the analysis.\n\n### Interpret the results\n\nThe paired *t*-test asks whether the mean of the within-individual differences is zero. In this example the mean paired difference is positive, which indicates that the piglets tended to gain mass over the feeding period. Because the confidence interval for the mean difference lies just above zero and the *p*-value is near 0.05, the evidence suggests a modest but statistically detectable increase in mass.\n\n### Reporting\n\nIn a results section, the reporting logic for a paired *t*-test is similar to the other *t*-tests, but now the emphasis falls on the **mean paired difference** rather than on two separate independent means. A journal-style results paragraph should therefore report:\n\n-   what the two paired measurements were;\n-   the mean difference between them and its units;\n-   the *t* statistic and degrees of freedom;\n-   the *p*-value;\n-   the confidence interval for the mean difference;\n-   a short interpretation in biological terms.\n\nFor example, you might report:\n\n> Piglet body mass increased over the three-week feeding period. A paired *t*-test showed that the mean within-individual change in body mass differed significantly from zero ($t_{11} = 2.21$, $p < 0.05$). The mean paired difference was $0.815$ kg, with a 95% confidence interval from $0.004$ to $1.626$ kg, indicating that the piglets were, on average, heavier after the feeding period than at the start.\n\n## If assumptions fail\n\nIf the paired differences are strongly non-normal, especially in a small sample, the paired *t*-test may not be appropriate. In that case a Wilcoxon signed-rank test via `wilcox.test(..., paired = TRUE)` may be more defensible. As before, the broader workflow for evaluating assumptions is discussed in [Chapter 6](06-assumptions-and-transformations.qmd).\n\n::: callout-important\n## Do This Now!\n**Task F.3.** Divide the class into two groups. In each group, collect your own data that are suitable for analysis with a paired *t*-test. State your hypothesis. Test it. Discuss. Report back comprehensively in Task F.\n:::\n\n# Is There a Difference Between Two Proportions?\n\nAll of the tests we have covered above are designed for continuous response data, such as fish lengths, chlorophyll concentrations, or body mass. Sometimes, however, our response is not continuous but binary: success or failure, bitten or not bitten, germinated or not germinated, alive or dead. In such cases the quantity of interest is a **proportion**, and the logic of the analysis changes accordingly.\n\nIf we want to compare proportions against a known value, or compare the proportions of two samples against one another, we use `prop.test()`. Although this is not a *t*-test, it fits naturally here because the inferential logic is similar: we still state a hypothesis, examine the data, apply the appropriate test, interpret the result, and report it clearly.\n\n## When to use a proportion test\n\nUse `prop.test()` when:\n\n-   the response variable records success/failure outcomes;\n-   the data can be summarised as the number of successes out of a total number of trials;\n-   you want to compare an observed proportion against a hypothesised value, or compare the proportions of two groups;\n-   the observations are independent.\n\nAs with the *t*-tests above, the exact form of the test depends on the question. We may do a **one-sample proportion test** when comparing an observed proportion to a known or expected probability, or a **two-sample proportion test** when comparing the success proportions of two groups.\n\nLet us create a simple dataset to see how this works. Below we create some data showing the result of placing two different subjects, Jack and Jill, in separate sealed rooms for two hours (120 minutes). Once every minute a mosquito is let into the room before being extracted again. The columns `yes` and `no` show whether the mosquito bit the subject during that one minute. Who says science cannot be fun!\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmosquito <- matrix(c(70, 85, 50, 35), ncol = 2)\ncolnames(mosquito) <- c(\"yes\", \"no\")\nrownames(mosquito) <- c(\"Jack\", \"Jill\")\nmosquito\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR>      yes no\nR> Jack  70 50\nR> Jill  85 35\n```\n\n\n:::\n:::\n\n\n## One-sample proportion tests\n\nIf we have only one sample, we must specify the total number of trials as well as the expected population probability of success. In the arguments within `prop.test()`, `x` denotes the number of successes recorded, `n` shows the total number of individual trials performed, and `p` is the expected probability.\n\n### State the hypotheses\n\nFor a two-sided one-sample proportion test, the hypotheses are:\n\n$$H_{0}: p = p_{0}$$\n$$H_{a}: p \\ne p_{0}$$\n\nwhere $p$ is the observed population proportion and $p_{0}$ is the hypothesised proportion.\n\n### Apply the test\n\nIt is easiest to think of this as a series of 100 coin tosses, where the null expectation is that the probability of heads is 0.5.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# When the probability matches the population\nprop.test(x = 45, n = 100, p = 0.5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR> \nR> \t1-sample proportions test with continuity correction\nR> \nR> data:  45 out of 100, null probability 0.5\nR> X-squared = 0.81, df = 1, p-value = 0.3681\nR> alternative hypothesis: true p is not equal to 0.5\nR> 95 percent confidence interval:\nR>  0.3514281 0.5524574\nR> sample estimates:\nR>    p \nR> 0.45\n```\n\n\n:::\n\n```{.r .cell-code}\n# When it does not\nprop.test(x = 33, n = 100, p = 0.5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR> \nR> \t1-sample proportions test with continuity correction\nR> \nR> data:  33 out of 100, null probability 0.5\nR> X-squared = 10.89, df = 1, p-value = 0.0009668\nR> alternative hypothesis: true p is not equal to 0.5\nR> 95 percent confidence interval:\nR>  0.2411558 0.4320901\nR> sample estimates:\nR>    p \nR> 0.33\n```\n\n\n:::\n:::\n\n\n### Interpret the results\n\nThe first test asks whether an observed success proportion of 0.45 differs from the hypothesised value of 0.50. The answer is no: the confidence interval includes 0.50 and the *p*-value is not small. The second test asks whether an observed proportion of 0.33 differs from 0.50. In that case the answer is yes: the *p*-value is very small and the confidence interval does not include 0.50.\n\nThe inferential logic is therefore identical to what we saw with one-sample *t*-tests. The conclusion depends on how far the observed sample proportion lies from the null value, relative to the uncertainty in the estimate.\n\n### Reporting\n\nWhen reporting a one-sample proportion test, state:\n\n-   the number of successes and the total number of trials;\n-   the observed proportion;\n-   the hypothesised proportion;\n-   the test statistic and *p*-value;\n-   the confidence interval for the observed proportion;\n-   a short interpretation in biological terms.\n\nFor example, you might report:\n\n> In 45 successes out of 100 trials, the observed proportion was 0.45. A one-sample proportion test indicated that this did not differ from the hypothesised probability of 0.50 ($\\chi^2 = 0.81$, $p > 0.05$). The 95% confidence interval for the observed proportion ranged from 0.351 to 0.552, which included the null value of 0.50.\n>\n> In contrast, 33 successes out of 100 trials yielded an observed proportion of 0.33, which differed significantly from 0.50 ($\\chi^2 = 10.89$, $p < 0.001$). The 95% confidence interval ranged from 0.241 to 0.432, indicating that the true success probability was likely lower than one half.\n\n## Two-sample proportion tests\n\nIf we have two samples that we would like to compare against one another, we enter them into the function as follows:\n\n### State the hypotheses\n\nFor a two-sided comparison of two proportions, the hypotheses are:\n\n$$H_{0}: p_{1} = p_{2}$$\n$$H_{a}: p_{1} \\ne p_{2}$$\n\nwhere $p_{1}$ and $p_{2}$ are the success probabilities in the two groups.\n\n### Apply the test\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# NB: Note that the `mosquito` data are a matrix, NOT a data.frame\nprop.test(mosquito)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR> \nR> \t2-sample test for equality of proportions with continuity correction\nR> \nR> data:  mosquito\nR> X-squared = 3.5704, df = 1, p-value = 0.05882\nR> alternative hypothesis: two.sided\nR> 95 percent confidence interval:\nR>  -0.253309811  0.003309811\nR> sample estimates:\nR>    prop 1    prop 2 \nR> 0.5833333 0.7083333\n```\n\n\n:::\n:::\n\n\n### Interpret the results\n\nIn the mosquito example, the estimated bite proportion for Jack is 0.583, while that for Jill is 0.708. The two-sample proportion test asks whether this observed difference is large enough, relative to sampling uncertainty, to conclude that the underlying bite probabilities differ.\n\nThe *p*-value here is about 0.059, which is just above the conventional 0.05 threshold. The 95% confidence interval for the difference in proportions includes zero, so we would conclude that these data do not quite provide strong enough evidence for a difference in bite rate between Jack and Jill, even though Jill appears to have been bitten more often.\n\n### Reporting\n\nWhen reporting a two-sample proportion test, state:\n\n-   the number of successes and total trials in each group;\n-   the observed proportions for each group;\n-   the test statistic and *p*-value;\n-   the confidence interval for the difference in proportions;\n-   a short biological interpretation.\n\nFor example, you might report:\n\n> Mosquitoes bit Jack in 70 of 120 trials (proportion = 0.583) and Jill in 85 of 120 trials (proportion = 0.708). A two-sample test for equality of proportions indicated that this difference was not statistically significant at the 0.05 level ($\\chi^2 = 3.57$, $p > 0.05$). The 95% confidence interval for the difference in proportions ranged from $-0.253$ to $0.003$, indicating that although Jill appeared to be bitten more often, the data do not provide quite enough evidence to conclude that the two bite probabilities differ.\n\n::: callout-important\n## Do This Now!\n**Task F.4.** Divide the class into two groups, Group A, Group B. In each group and collect data on 100 coin tosses. The intention is to compare the coin tosses across Groups A and B. State your hypothesis. Test it. Discuss. Report back in Task F.\n:::\n\n## One-sided and two-sided Tests\n\nAs with all the other tests that compare values, proportion tests may be specified as either one- or two-sided. The default setting for `prop.test()`, like the default for `t.test()`, is a two-sided test. See the code below to confirm that the results are identical with and without the added argument:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Default\nprop.test(mosquito)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR> \nR> \t2-sample test for equality of proportions with continuity correction\nR> \nR> data:  mosquito\nR> X-squared = 3.5704, df = 1, p-value = 0.05882\nR> alternative hypothesis: two.sided\nR> 95 percent confidence interval:\nR>  -0.253309811  0.003309811\nR> sample estimates:\nR>    prop 1    prop 2 \nR> 0.5833333 0.7083333\n```\n\n\n:::\n\n```{.r .cell-code}\n# Explicitly state two-sided test\nprop.test(mosquito, alternative = \"two.sided\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR> \nR> \t2-sample test for equality of proportions with continuity correction\nR> \nR> data:  mosquito\nR> X-squared = 3.5704, df = 1, p-value = 0.05882\nR> alternative hypothesis: two.sided\nR> 95 percent confidence interval:\nR>  -0.253309811  0.003309811\nR> sample estimates:\nR>    prop 1    prop 2 \nR> 0.5833333 0.7083333\n```\n\n\n:::\n:::\n\n\nIf we want to specify only one of the tails, we do so in precisely the same way as with the *t*-tests above.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Jack is bit less than Jill\nprop.test(mosquito, alternative = \"less\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR> \nR> \t2-sample test for equality of proportions with continuity correction\nR> \nR> data:  mosquito\nR> X-squared = 3.5704, df = 1, p-value = 0.02941\nR> alternative hypothesis: less\nR> 95 percent confidence interval:\nR>  -1.00000000 -0.01597923\nR> sample estimates:\nR>    prop 1    prop 2 \nR> 0.5833333 0.7083333\n```\n\n\n:::\n\n```{.r .cell-code}\n# Jack is bit more than Jill\nprop.test(mosquito, alternative = \"greater\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR> \nR> \t2-sample test for equality of proportions with continuity correction\nR> \nR> data:  mosquito\nR> X-squared = 3.5704, df = 1, p-value = 0.9706\nR> alternative hypothesis: greater\nR> 95 percent confidence interval:\nR>  -0.2340208  1.0000000\nR> sample estimates:\nR>    prop 1    prop 2 \nR> 0.5833333 0.7083333\n```\n\n\n:::\n:::\n\n\nDo these results differ from the two-sided test? What is different? The answer is that the direction of the alternative matters. If our directional hypothesis is that Jack is bitten less often than Jill, the one-sided *p*-value is 0.029, which supports that alternative. If we ask the opposite question, the *p*-value is 0.971, which clearly does not.\n\n## If assumptions fail\n\nThe main assumptions behind proportion tests are that the observations are independent and that the data arise from counts of successes and failures. If the observations are dependent, or if the counts are very small, other methods may be more appropriate. For now, the key point is that proportion tests extend the same inferential workflow used for *t*-tests to binary-response data.\n\n# A *t*-test Workflow\n\nNow that we have seen how to compare the means of two sample sets of data, let us see what that complete workflow would look like in R. For this example we will use the `ecklonia` data from [Intro R Workshop: Data Manipulation, Analysis, Graphing](https://robwschlegel.github.io/Intro_R_Workshop/).\n\n## Loading Data\n\nBefore we can run any analyses we will need to load our data. We are also going to convert these data from their wide format into a long format because this is more useful for the rest of our workflow.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\necklonia <- read_csv(file.path(\"..\", \"..\", \"data\", \"BCB744\", \"ecklonia.csv\")) %>% \n  gather(key = \"variable\", value = \"value\", -species, -site, -ID)\n```\n:::\n\n\n## Visualising Data\n\nWith our data loaded, let us visualise them in order to ensure that these are indeed the data we are after (@fig-ecklonia1). Visualising the data will also help us to formulate a hypothesis.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(data = ecklonia, aes(x = variable, y = value, fill = site)) +\n  geom_boxplot(colour = \"black\", fill = \"dodgerblue4\", alpha = 0.4) +\n  coord_flip() +\n  theme_grey()\n```\n\n::: {.cell-output-display}\n![Boxplots showing differences in morphometric properties of the kelp _Ecklonia maxima_ at two sites in False Bay.](07-t_tests_files/figure-html/fig-ecklonia1-1.svg){#fig-ecklonia1 fig-align='center' width=88%}\n:::\n:::\n\n\nThe first thing we should notice from the figure above is that our different measurements are on very different scales. This makes comparing all of our data visually rather challenging. Even given this complication, one should readily be able to make out that the measurement values at Batsata Rock appear to be greater than at Boulders Beach. Within the framework of the scientific process, that is what we would call an 'observation', and is the first step towards formulating a hypothesis. The next step is to refine our observation into a hypothesis. By what measurement are the kelps greater at one site than the other?\n\n## Formulating a Hypothesis\n\nLooking at the figure above it appears that for almost all measurements of length, Batsata Rock far exceeds that of Boulders Beach however, the stipe masses between the two sites appear to be more similar. Let us pull out just this variable, create a new boxplot (@fig-ecklonia2).\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# filter the data\necklonia_sub <- ecklonia %>% \n  filter(variable == \"stipe_mass\")\n\n# then create a new figure\nggplot(data = ecklonia_sub, aes(x = variable, y = value, fill = site)) +\n  geom_boxplot(colour = \"black\", alpha = 0.4) +\n  coord_flip() +\n  labs(y = \"Stipe mass (kg)\", x = \"\") +\n  theme(axis.text.y = element_blank(),\n        axis.ticks.y = element_blank()) +\n  theme_grey()\n```\n\n::: {.cell-output-display}\n![Boxplots showing the difference in stipe mass (kg) of the kelp _Ecklonia maxima_ at two sites in False Bay.](07-t_tests_files/figure-html/fig-ecklonia2-1.svg){#fig-ecklonia2 fig-align='center' width=88%}\n:::\n:::\n\n\nNow we have a more interesting comparison at hand. The question I think of when I look at these data is \"Are the stipe masses at Batsata Rock greater than at Boulders Beach?\". The hypothesis necessary to answer this question would look like this:\n\n-   *H*~0~: Stipe mass at Batsata Rock **is not** greater than at Boulders Beach.\n-   *H*~a~: Stipe mass at Batsata Rock **is** greater than at Boulders Beach.\n\nOr more formally:\n\n-   $H_{0}: \\bar{A} \\leq \\bar{B}$\n-   $H_{a}: \\bar{A} > \\bar{B}$.\n\nWhich test must we use for this hypothesis?\n\n## Choosing a Test\n\nBefore we can pick the correct statistical test for our hypothesis, we need to be clear on what it is we are asking. Starting with the data being used is usually a good first step. As we may see in the above figure, we have two sample sets that we are comparing. Therefore, unsurprisingly, we will likely be using a *t*-test. But we are not done yet. How is it that we are comparing these two sample sets? Remember from the examples above that there are multiple different ways to compare two sets of data. For our hypothesis we want to see if the stipe mass at Batsata Rock is **greater than** the stipe mass at Boulders Beach, not just that they are different. Because of this we will need a one-sided *t*-test. But wait, there is more! We have zeroed in on which sort of test would be appropriate for our hypothesis, but before we run it we need to check our assumptions.\n\n## Checking Assumptions\n\nIn case we forgot, here are the assumptions for a *t*-test:\n\n-   the dependent variable must be **continuous**,\n-   the observations in the groups being compared are **independent** of each other,\n-   the data are **normally distributed**,\n-   that the data are **homoscedastic**, and in particular, that there are no outliers.\n\nWe know that the first two assumptions are met because our data are measurements of mass at two different sites. Before we can run our one-sided *t*-test we must meet the last two assumptions. Lucky us, we have a function tat will do that automagically.\n\nPlease refer to [Chapter 6](06-assumptions-and-transformations.qmd) to see what to do if the assumptions fail.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\necklonia_sub %>% \n  group_by(site) %>% \n  summarise(stipe_mass_var = two_assum(value)[1],\n            stipe_mass_norm = two_assum(value)[2])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR> # A tibble: 2 × 3\nR>   site           stipe_mass_var stipe_mass_norm\nR>   <chr>                   <dbl>           <dbl>\nR> 1 Batsata Rock             2.00           0.813\nR> 2 Boulders Beach           2.64           0.527\n```\n\n\n:::\n:::\n\n\nLovely. The variances are equal and the data are normal. On to the next step.\n\n## Running an Analysis\n\nWith our assumptions checked, we may now analyse our data. We will see below how to do this with both of the functions we have learned in this chapter for comparing means of two sample sets.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nt.test(value ~ site, data = ecklonia_sub,\n       var.equal = TRUE, alternative = \"greater\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR> \nR> \tTwo Sample t-test\nR> \nR> data:  value by site\nR> t = 1.8741, df = 24, p-value = 0.03657\nR> alternative hypothesis: true difference in means between group Batsata Rock and group Boulders Beach is greater than 0\nR> 95 percent confidence interval:\nR>  0.09752735        Inf\nR> sample estimates:\nR>   mean in group Batsata Rock mean in group Boulders Beach \nR>                     6.116154                     4.996154\n```\n\n\n:::\n:::\n\n\n## Interpreting the Results\n\nWe may reject the null hypothesis that the stipe mass of kelps at Batsata Rock is not greater than at Boulders Beach if our *t*-test returns a *p*-value $\\leq$ 0.05. We must also pay attention to some of the other results from our *t*-test, specifically the *t*-value (`t`) and the degrees of freedom (`df`) as these are also needed when we are writing up our results. From all of the information above, we may accept the alternative hypothesis. But how do we write that up?\n\n## Drawing Conclusions\n\nThere are many ways to present one's findings. Style, without *too much* flourish, is encouraged as long as certain necessary pieces of information are provided. In a scientific paper, the results section would normally report the sample means, the test used, the test statistic, degrees of freedom, the *p*-value, and the biological interpretation in one compact paragraph.\n\nFor example, one might report:\n\n> Mean stipe mass of *Ecklonia maxima* was higher at Batsata Rock ($6.12 \\pm 1.41$ kg SD, $n = 13$) than at Boulders Beach ($5.00 \\pm 1.63$ kg SD, $n = 13$). A one-sided two-sample Student's *t*-test indicated that stipe mass at Batsata Rock was significantly greater than at Boulders Beach ($t_{24} = 1.87$, $p < 0.05$). The 95% confidence interval for the mean difference was $0.10$ kg to $\\infty$, supporting the conclusion that kelp at Batsata Rock had greater stipe mass.\n\n## Going Further\n\nBut why though? As is often the case in life, and science is no exception, answers to our questions just create even more questions! Why would the mass of kelp stipes at one locations in the same body of water, only a kilometre or so apart be significantly different? It looks like we are going to need to design a new experiment... Masters thesis anyone?\n\n# Conclusion\n\n*t*-tests are one of the first classes of inferential statistics students typically lerarn in a module on biostatistics. They are suitable for situations where you have two groups of data to compare and to establish if the difference between their means is zero. Lesson learned here are generalisable to more complex analysis.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}