---
date: "2024-07-19"
title: "Lecture 1a. About Biogeography & Global Ecology"
---

::: callout-note
## BCB743

**This material must be reviewed by BCB743 students in Week 1 of
Quantitative Ecology.**
:::

## Introduction to Biogeography and Global Ecology

### Main Outcomes

On completion of this module the student should be able to:

- Discuss the past, present and projected future patterns of global biogeography.
- Examine the distribution of past floras, faunas and climate with respect to plate tectonics and compare them
with current distributions.
- Explain the role that the major environmental drivers play in driving these biogeographical patterns.
- Understand the physical basis underpinning the components of global change.
- Recognise the central importance that humans play in bringing about global change.
- Understand the ecological, physiological and behavioural basis for biogeographical change.
- Contrast the fundamental differences between ecological biogeography and historical biogeography.
- Consider the biogeography of key extant plant and animal lineages.
- Apply the appropriate concepts to collect, analyse and interpret multivariate environmental and ecological data.
- Present their position on the above in discussion or in written format.

### Main Content

**Professor Boatwright:**

- Global biogeography: key principles and concepts.
- Continental drift and glaciation.
- Theories of biogeography and biogeographic reconstruction.
- Phylogeography
- Island biogeography theory and its applications for conservation.

**Professor Smit:**

- Latitudinal gradients in diversity.
- Interactions of body and population size on diversity and distribution.
- Earth as a system
- The physical nature of environmental drivers of biogeography.
- Global change: the distinction between natural variability and anthropogenically-driven change.
- Overview of the biological responses to global change.
- Basic data collection and analytical methods in biogeography.

### Exploration of Concepts

Ecosystems form the foundation of life on Earth, encompassing complex interactions between living organisms and their physical environment. This lecture series will explore the fundamental concepts, characteristics, and driving forces that shape and maintain ecosystems across our planet.

We'll begin by defining ecosystems and examining their basic structure, including both biotic and abiotic components. Next, we'll investigate key ecosystem characteristics such as energy flow, nutrient cycling, biodiversity, and community structure. Throughout the course, we'll explore the various drivers influencing ecosystem dynamics, including natural factors like climate and geological processes, as well as anthropogenic influences related to global change.

Our study will cover diverse ecosystem types, ranging from terrestrial to aquatic, and from microscopic to global scales. The practical component of this module will focus on quantifying ecosystem processes across various spatial scales. We'll also discuss the importance of ecosystem services and their critical role in supporting human well-being and planetary health.

By the end of this series, you'll have gained a comprehensive understanding of ecosystem concepts. You'll better appreciate the natural world around us and the factors that shape it. This knowledge will serve as a foundation for more advanced studies in ecology, environmental science, and conservation biology.

For those interested in further study, I teach a course called [Quantitative Ecology](../BCB743/BCB743_index.html) in the BCB Department for Honours students. This advanced course focuses on analysing ecosystem data across different scales.

We will focus on some important topics that integrate many of the above ideas:

**1. Conceptual overview of ecosystems and their characteristics and drivers**

This topic explores the conceptual overview of ecosystems, including their characteristics and drivers. This will equip you to answer questions such as:

- What is an ecosystem?
- What are the main components of ecosystems?
- What is 'macroecology'?
- What are ecosystem's functional and structural properties?
- How do we measure and describe these properties?
- What drives ecosystems? 
- How do we measure these drivers?
- How do we measure the responses of ecosystems to these drivers?
- Does it all matter? How? For whom?

**2. Gradients in diversity**

We will examine how ecosystem function and structure become arranged across Earth's surface. In Labs we will use data to quantify biodiversity structure. At the end, you should be equipped to answer questions such as:

- What are gradients?
- Why do gradients exist?
- What are the main environmental gradients?
- How do these gradients affect biodiversity? Why do biodiversity, ecosystem properties, and ecological function change along these gradients?
- What are the main gradients in diversity, globally and regionally?
- How are gradients (environment and species) being affected by global change?

**3. The role of humans in driving global change**

Humans have drastically altered ecosystem function and structure across space and time. Here, we emphasise the main drivers and their impacts on ecosystems. You will answer questions such as:

- What are the main drivers of global change?
- How do humans affect these drivers?
- What are the main impacts of these drivers on ecosystems?
- How do these impacts affect biodiversity, ecosystem properties, and ecological function?
- What are the main consequences of these impacts for humans?
- What can we do to mitigate these impacts?

**4. Anthropogenic and natural impacts on ecosystem integrity**

Following on from the previous topic, we now focus on the definition of 'anthropogenic' and look at these effects of human activities. Question such as the following will arise: 

- What is ecosystem integrity?
- How do humans affect ecosystem integrity?
- What are the main impacts of humans on ecosystem integrity?
- How do these impacts affect biodiversity, ecosystem properties, and ecological function?
- What are the main consequences of these impacts for humans?
- What can we do to mitigate these impacts?

**5. Exploration of selected marine and terrestrial ecosystems**

Now we explore selected marine and terrestrial ecosystems of South Africa focus).

- What are the main characteristics of these ecosystems?
- What are the main drivers of these ecosystems?
- How do these drivers affect biodiversity, ecosystem properties, and ecological function?
- What are the main consequences of these impacts for humans?
- What can we do to mitigate these impacts?

**6. Develop an understanding of the importance of biodiversity and ecosystem services**

Learn about the importance of biodiversity and ecosystem services. In the process, we unpack some modern frameworks that help us understand the importance of biodiversity and ecosystem services.

- What does biodiversity do?
- Why does biodiversity matter?
- What are sustainability and resilience, and how do they relate to biodiversity and ecosystem services?
- What are ecosystem services?
- What are the main ecosystem services?
- How do biodiversity and ecosystem properties affect these services?
- What are the main consequences of these impacts for humans?

As we work through this module, check your understand by seeing if you can answer the above questions. If you can, you are well on your way to understanding the main content of this module.

# Lecture Transcript: Introduction and Module Organisation

## Traditional vs Modern Ecology

A question arose: when referring to patterns and processes in traditional ecology, is there such a thing as modern ecology? Yes, this module is very much about modern ecology. Traditional ecological approaches would focus on surveys at a local scale, such as conducting a transect survey in a nearby nature reserve, limited by what can be physically accessed.

Today, with computers and satellite remote sensing, we can examine large-scale patterns—across countries, continents, or even globally—often using satellite data. Not only can we synthesise many small-scale surveys collected by different people over time, but we can also employ advanced numerical analyses to make sense of very large data sets—ones so substantial, they can no longer fit within Excel.

Modern ecologists now collaborate across the globe, pool significant data sets, and use advanced methods to reveal broad-scale patterns in biodiversity, species composition, and ecological functioning. Whereas traditional studies looked at the local, modern ecology can rigorously address processes at global, continental, or deep historical time scales.

## Example from South African Vegetation Mapping

For example, in the 1940s, a person with the surname Pocock [attention: likely a confusion with John Phillips or John Acocks; “Pocock” is incorrect here], attempted to classify all of South Africa's vegetation. He travelled by train, classifying the habitats he saw through the window. Even this method was constrained compared to the view we now have through remote sensing satellites.

Now, we can stand “$80\,\mathrm{km}$” above the Earth and map entire landscapes from above, unconstrained by natural or political boundaries.

## Broader Shifts in Approach

Traditional ecological studies focused on what happens in places within easy reach—a single nature reserve, for example. Modern studies look for patterns across nations or hemispheres, and also explore new levels of taxonomic detail, such as genetic variation and subspecies.

'Scale' can refer both to spatial scale—local to global—as well as temporal scale: considering recent changes versus millennia or longer time spans. Modern approaches allow us to examine ecological phenomena and biogeographic patterns at both these broader spatial and longer temporal dimensions.

Collaboration is increasingly important. Where once ecological studies might have one or two authors focused on a single location, it's now common to find large teams of co-authors bringing together expertise and data from multiple sites or even continents in pursuit of broader ecological generalities.

## The Value of Global Approaches

The aim of global ecology is to derive general ecological 'laws' or repeatable principles that apply across the full diversity of ecosystems—from Russian tundra to Amazonian rainforest to the Australian outback. Though these systems may look entirely different, we seek to identify commonalities in their fundamental processes.

Thirty years ago, when I was a student, almost all work was at a very local scale and typically on one's nearest nature reserve. Today, with advances in technology and computational power, questions can be more complex and less parochial. The questions themselves have evolved and broadened: “What can South Africa’s biodiversity teach Patagonian ecologists?” Global-scale studies provide answers of relevance far beyond one region or ecosystem.

## Closing and Summary

If you have further questions—about the module structure, assessments, or the content of the introductory material—please ask, either now or later via the chat or WhatsApp group.

If there are no more questions, I'll post this video online for you to access within the next half an hour or so. Thank you.
