---
date: "2024-07-19"
title: "Lecture 1b. Macroecology"
---

## Ecological Concepts

When we talk about 'ecology', central to our discussion is the concept of biodiversity. The Convention on Biological Diversity defines biodiversity as:

> "The variability among living organisms from all sources including, *inter alia*, terrestrial, marine and other aquatic ecosystems and the ecological complexes of which they are part; this includes diversity within species, between species and of ecosystems."

In this lecture, we will work towards an understanding of macroecology by working through these topics:

- ‘Traditional’ ecology—focus on the ‘local’ scale.
- The distinction between populations and communities.
- A definition for what ecology is.
- The concept of the ‘niche’ (fundamental and realised).
- The concept of ‘species’.
- Describe the properties of communities, viz. mainly structure and function.
- Using measures of diversity to understand structure.
- Arrive at the concept of macroecology.

In this module, we'll rely on thinking emerging from a unifying field of ecology called macroecology. According to @keith2012macroecology, macroecology is:

> "...the study of the mechanisms underlying general patterns of ecology across scales."

## Macroecology: Ecology Across Scales

::: {.my-highlight}
For a deeper dive into macroecology, please see the paper @shade2018macroecology. I provide some additional views on macroecology to supplement the insights you extract from this publication.
:::

Macroecology explores ecological patterns and processes across a wide range of scales (from microbes to blue whales, from the Cape Flats Nature Reserve to the whole of Earth, and from the Pleistocene to 2100). To the best of my knowledge, the term ‘macroecology’ was coined by @brown1989macroecology, who used it to study continental biotas. The term has since then undergone much growth and evolution in recent decades. More recently, it has led to attempts to develop unified theories of ecology [e.g. @keith2012macroecology, @shade2018macroecology], driven by a convergence of technological and methodological advancements, building upon earlier foundations laid by disciplines such as ‘phytosociology.’

Phytosociology (phytocoenology or plant sociology) studies and classifies plant communities. It has greatly influenced modern ecological research. Phytosociologists emphasise systematic vegetation classification and the understanding of plant community structure, which prepared the ground for many concepts in macroecology. For example, the Braun-Blanquet method, a cornerstone method in phytosociology since its development by Josias Braun-Blanquet (1884-1980) [@DENGLER20082767; @dengler2016phytosociology], still forms a standardised approach to vegetation sampling. The method has been adapted and expanded in the study of, amongst other things, benthic (limnetic and marine) communities, as it is well suited to sampling communities comprised mainly of sessile organisms.

Recent progress in macroecology was achieved through advances in several key areas. Molecular phylogenetics provided new insights into evolutionary relationships, while high-resolution datasets of abiotic and biotic variables offered unprecedented detail about environmental conditions and species distributions. Today’s vast (and rapidly growing) computational power allows the processing and analysis of these complex datasets, and novel numerical approaches and a robust statistical framework provide tools to extract insightful patterns from the data. 

Increased knowledge sharing and access to open data have further accelerated the growth of macroecology. Wider collaborative networks of ecologists now provide a more integrated understanding of ecological systems across broad spatial and temporal scales. We can now tackle complex questions that were previously out of reach.

Some of these fundamental questions include inquiries about variations in body size across species and regions, the patterns of biodiversity at global spatial scales and over geological timescales, abundance distributions across size classes of organisms, geographical range dynamics as we experience the various pressures of global change and the role of neutral processes in shaping ecological communities.

While 'traditional' ecology primarily focuses on describing natural patterns, macroecology has shifted towards finding mechanistic explanations for the processes resulting in observed biodiversity patterns. This transition advances our understanding of ecological systems, moving beyond mere description to explanation and prediction. Ecological systems are also increasingly coupled with Earth system models to offer projections of ecological structure and function in the future.

Today’s ecology students must reconcile their biological observations and knowledge with hypotheses about patterns and processes and understand the statistical models used to explain them. New frameworks are being developed to integrate biological theory with sophisticated statistical techniques, and we can conduct more robust and meaningful analyses of large-scale ecological data.

A key insight from this approach is the recognition that local species interactions can explain broad-scale patterns in species distributions. This understanding bridges the gap between small-scale ecological studies and large-scale macroecological patterns and provides a more cohesive view of how ecosystems function across different spatial scales.

This growing recognition that links local processes to global patterns has led some ecologists to try and find unified theories of ecology. These theories aim to be predictive by offering explanations for observed patterns and the ability to forecast future ecological scenarios. Such unified theories represent a holy grail in ecology and potentially provide an integrated framework for understanding and predicting ecological phenomena across scales and systems.

The advancements in macroecology have significantly enhanced our comprehension of biodiversity, ecosystem functioning, and ecological responses to global change. Notably, macroecology has exerted a remarkably wide-ranging and transformative impact at the intersection of scientific research and policy-making. This influence is especially evident in land-use management, climate change mitigation and adaptation strategies, and efforts to address biodiversity loss.

