---
date: "2024-07-22"
title: "Lecture 3: Species Distribution Patterns"
---

::: callout-note
## BCB743

**This material must be reviewed by BCB743 students in Week 1 of
Quantitative Ecology.**
:::

::: callout-tip
## This Lecture is Accompanied by the Following Lab

- [Lab 4. Species Distribution Patterns](04-biodiversity2.qmd)
:::

::: callout-tip
## Reading Required For This Lab

- [Gotelli and Chao (2013)](../docs/Gotelli_and_Chao_2013.pdf)
- [Matthews and Whittaker (2015)](../docs/Matthews_and_Whittaker_2015.pdf)
- [Shade et al. (2018)](../docs/Shade_et_al_2018.pdf)
:::


Univariate diversity measures such as Simpson and Shannon diversity have already been prepared from species tables, and we have also calculated measures of $\beta$-diversity that looked at pairwise comparisons and offered insight into community structure across a landscape and hinted at the processes that might have resulted in these structures. These ways of expressing biodiversity only gets us so far in understanding the structure of communities. A much deeper insight into the processes responsible for community formation can be obtained by looking at how the species patterns are distributed across sites. This is the focus of this lecture.

Let's shine the spotlight to additional views on ecological structures and the ecological processes that structure the communities---sometimes we will see reference to 'community or species formation processes' to offer mechanistic views on how species come to be arranged into communities (the aforementioned turnover and nestedness-resultant $\beta$-diversity are examples of other formation processes). Let's develop views that are based on all the information contained in the species tables, i.e. abundance, the number of sites, and the diversity of the biota. This deeper view is not necessarily captured if we limit our toolkit to the various univariate and pairwise descriptors of biodiversity.

You will already be familiar with the paper by @shade2018macroecology. Several kinds of ecological patterns are mentioned in the paper, and they can be derived from a species table with abundance data (but *not* presence-absence data!). The patterns that can be derived from such a table include (see @fig-shade below), and they are as follows:

* Species-abundance distribution
* Occupancy-abundance curves
* Species-area curves
* Rarefaction curves
* Distance-decay curves
* Elevation gradients

![Species distribution curves by @shade2018macroecology. [Note that this figure starts with a species table where the species are arranged down the rows and the sites along the variables (columns). I, and also the **vegan** package, require that the **species are down the columns (called variables) and the sites (or samples) are along the rows**. This is the convention that will be used throughout this module.]{.my-highlight}](../images/Shade_et_al_2018_Fig_1.png){#fig-shade fig-align="center" width="600"}

## Species Abundance Distribution

Species Abundance Distribution (SAD) describes how individuals are distributed among all the species within our sampled community. It tells us about the patterns of species dominance and rarity---this information relates to a more nuanced understanding of ecological dynamics, community structure, and the mechanisms driving biodiversity.

To create a SAD curve, we create a histogram (or stepped line graph as in @shade2018macroecology) of the number of individuals on the *x*-axis (ranked from least to most abundant) and the number of species represented by a particular abundance on the *y*-axis. The resultant curve is often referred to as a rank-abundance curve or Whittaker plot [see @matthews2015species].

The shape of the resulting curve often is that typical of a log-normal distribution. That is, the line shows that the bulk of the species rank from rare to low abundant, but that progressively, fewer and fewer species become increasingly abundant. This situation seems typical of most communities and might even be likened to what passes as a 'law' or 'theory' in ecology.

However, there are a few other models that describe SADs, such as the geometric series, log-series, log-normal, and broken-stick models. Each model assumes different ecological processes and mechanisms. 

