return {
 ["name:TeX Gyre Termes/B:mode=node;script=latn;language=dflt;#b#589825"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/tex-gyre/texgyretermes-bold.otf", false },
 ["name:TeX Gyre Termes/B:mode=node;script=latn;language=dflt;#b#589826"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/tex-gyre/texgyretermes-bold.otf", false },
 ["name:TeX Gyre Termes/B:mode=node;script=latn;language=dflt;+tlig;#b#589824"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/tex-gyre/texgyretermes-bold.otf", false },
 ["name:TeX Gyre Termes/B:mode=node;script=latn;language=dflt;+tlig;#b#717619"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/tex-gyre/texgyretermes-bold.otf", false },
 ["name:TeX Gyre Termes/BI:mode=node;script=latn;language=dflt;#bi#589825"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/tex-gyre/texgyretermes-bolditalic.otf", false },
 ["name:TeX Gyre Termes/BI:mode=node;script=latn;language=dflt;#bi#589826"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/tex-gyre/texgyretermes-bolditalic.otf", false },
 ["name:TeX Gyre Termes/I:mode=node;script=latn;language=dflt;#i#589825"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/tex-gyre/texgyretermes-italic.otf", false },
 ["name:TeX Gyre Termes/I:mode=node;script=latn;language=dflt;#i#589826"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/tex-gyre/texgyretermes-italic.otf", false },
 ["name:TeX Gyre Termes/I:mode=node;script=latn;language=dflt;+tlig;#i#589824"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/tex-gyre/texgyretermes-italic.otf", false },
 ["name:TeX Gyre Termes:mode=node;#589822"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/tex-gyre/texgyretermes-regular.otf", false },
 ["name:TeX Gyre Termes:mode=node;#589826"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/tex-gyre/texgyretermes-regular.otf", false },
 ["name:TeX Gyre Termes:mode=node;script=latn;language=dflt;#589825"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/tex-gyre/texgyretermes-regular.otf", false },
 ["name:TeX Gyre Termes:mode=node;script=latn;language=dflt;#589826"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/tex-gyre/texgyretermes-regular.otf", false },
 ["name:TeX Gyre Termes:mode=node;script=latn;language=dflt;+tlig;#327680"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/tex-gyre/texgyretermes-regular.otf", false },
 ["name:TeX Gyre Termes:mode=node;script=latn;language=dflt;+tlig;#393216"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/tex-gyre/texgyretermes-regular.otf", false },
 ["name:TeX Gyre Termes:mode=node;script=latn;language=dflt;+tlig;#589824"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/tex-gyre/texgyretermes-regular.otf", false },
 ["name:TeX Gyre Termes:mode=node;script=latn;language=dflt;+tlig;#717619"]={ "/usr/local/texlive/2025/texmf-dist/fonts/opentype/public/tex-gyre/texgyretermes-regular.otf", false },
}