{
  "hash": "7b4577265e009a38e3803330c089c828",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"20. Generalised Linear Models\"\nsubtitle: \"Extending Regression Beyond Normal Responses\"\ndate: last-modified\ndate-format: \"YYYY/MM/DD\"\nreference-location: margin\n---\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n::: {.callout-note appearance=\"simple\"}\n## In This Chapter\n\n-   why ordinary linear models fail for binary, proportional, and count responses;\n-   how families and link functions define a generalised linear model;\n-   how simple proportion tests connect to the binomial GLM framework;\n-   how to fit and interpret a real logistic regression with ecological data;\n-   how to detect overdispersion in count data and what it means for interpretation.\n:::\n\n::: {.callout-important appearance=\"simple\"}\n## Tasks to Complete in This Chapter\n\n-   None\n:::\n\n# Introduction\n\nOrdinary linear regression assumes a normally distributed response with constant variance. Many ecological responses do not meet those conditions at all. Presence-absence data are binary, proportions are constrained between 0 and 1, and counts are non-negative integers whose variance often changes with the mean.\n\n**Generalised linear models (GLMs)** extend regression to handle those cases while retaining the same basic reasoning:\n\n1. define the biological question;\n2. choose predictors;\n3. fit a model;\n4. interpret the fitted effects.\n\nThe difference is that the response distribution and link function must now match the data structure.\n\n# Key Concepts\n\n-   **The family** describes the response distribution, such as binomial for binary data or Poisson for counts.\n-   **The link function** connects the linear predictor to the expected response scale.\n-   **A GLM still has a linear predictor**, but it acts on the link scale rather than directly on the response scale.\n-   **Interpretation depends on scale**: a coefficient may describe a change in log-odds or log-counts rather than a direct additive change in the response.\n-   **Overdispersion** is a warning that the simplest count model may be too optimistic.\n\n# When This Method Is Appropriate\n\nUse a GLM when:\n\n-   the response is binary, such as present/absent or alive/dead;\n-   the response is a proportion derived from successes and failures;\n-   the response is a count;\n-   the variance changes with the mean in a way that an ordinary linear model cannot sensibly represent.\n\nIn this chapter, I pick up the earlier proportion-testing material and place it inside the broader regression sequence.\n\n# Nature of the Data and Assumptions\n\nThe assumptions depend on the GLM family, but some ideas are common and/or familiar:\n\n1. observations should be independent;\n2. the response family should match the data-generating structure;\n3. the link function should make biological and statistical sense;\n4. the linear predictor should be appropriately specified.\n\nUnlike ordinary least squares, GLMs do not assume normal residuals with constant variance. Instead, the variance structure is part of the model family itself.\n\n# The Core Equations\n\nA generalised linear model can be written as:\n\n$$g(\\mu_i) = \\eta_i = \\alpha + \\beta_1 X_{1i} + \\beta_2 X_{2i} + \\cdots + \\beta_p X_{pi}$$ {#eq-glm}\n\nIn @eq-glm, $\\mu_i$ is the expected response for observation $i$, $g(\\cdot)$ is the link function, and $\\eta_i$ is the linear predictor.\n\nFor binomial logistic regression, the most common link is the logit:\n\n$$\\log\\left(\\frac{p_i}{1-p_i}\\right) = \\alpha + \\beta_1 X_{1i} + \\cdots + \\beta_p X_{pi}$$ {#eq-logit}\n\nEquation @eq-logit says that predictors act linearly on the **log-odds** scale.\n\nFor Poisson regression, the most common link is the log link:\n\n$$\\log(\\mu_i) = \\alpha + \\beta_1 X_{1i} + \\cdots + \\beta_p X_{pi}$$ {#eq-poisson}\n\nEquation @eq-poisson means that predictors act linearly on the **log-count** scale.\n\n# R Functions\n\nThe main function is `glm()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglm(response ~ predictors, family = ..., data = df)\n```\n:::\n\n\nTypical uses are:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglm(binary_response ~ predictors, family = binomial, data = df)\nglm(cbind(successes, failures) ~ predictors, family = binomial, data = df)\nglm(count ~ predictors, family = poisson, data = df)\nglm(count ~ predictors, family = quasipoisson, data = df)\n```\n:::\n\n\n# Simple Proportion Tests as a Bridge to GLMs\n\nBefore fitting full binomial models with predictors, it is useful to recognise that the simple proportion tests encountered earlier are part of the same broader reasining framework.\n\nIf we only want to compare an observed proportion against a null expectation, or compare the proportions of two groups without additional predictors, `prop.test()` is still useful.\n\n## One-Sample Proportion Tests\n\nFor a two-sided one-sample proportion test, the hypotheses are:\n\n$$H_{0}: p = p_{0}$$\n$$H_{a}: p \\ne p_{0}$$\n\nHere `x` is the number of successes, `n` is the number of trials, and `p` is the hypothesised probability:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.test(x = 45, n = 100, p = 0.5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t1-sample proportions test with continuity correction\n\ndata:  45 out of 100, null probability 0.5\nX-squared = 0.81, df = 1, p-value = 0.3681\nalternative hypothesis: true p is not equal to 0.5\n95 percent confidence interval:\n 0.3514281 0.5524574\nsample estimates:\n   p \n0.45 \n```\n\n\n:::\n\n```{.r .cell-code}\nprop.test(x = 33, n = 100, p = 0.5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t1-sample proportions test with continuity correction\n\ndata:  33 out of 100, null probability 0.5\nX-squared = 10.89, df = 1, p-value = 0.0009668\nalternative hypothesis: true p is not equal to 0.5\n95 percent confidence interval:\n 0.2411558 0.4320901\nsample estimates:\n   p \n0.33 \n```\n\n\n:::\n:::\n\n\n## Two-Sample Proportion Tests\n\nFor a two-sided comparison of two proportions:\n\n$$H_{0}: p_{1} = p_{2}$$\n$$H_{a}: p_{1} \\ne p_{2}$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmosquito <- matrix(c(70, 85, 50, 35), ncol = 2)\ncolnames(mosquito) <- c(\"yes\", \"no\")\nrownames(mosquito) <- c(\"Jack\", \"Jill\")\nmosquito\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     yes no\nJack  70 50\nJill  85 35\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.test(mosquito)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t2-sample test for equality of proportions with continuity correction\n\ndata:  mosquito\nX-squared = 3.5704, df = 1, p-value = 0.05882\nalternative hypothesis: two.sided\n95 percent confidence interval:\n -0.253309811  0.003309811\nsample estimates:\n   prop 1    prop 2 \n0.5833333 0.7083333 \n```\n\n\n:::\n:::\n\n\nThese tests are useful when the question is simple and there are few or no predictors. Once predictors enter the problem, the binomial GLM becomes the natural extension.\n\n# Example 1: Logistic Regression for Presence-Absence Data\n\n## Example Dataset\n\nWe use the `Sessile_Benthic_Invertebrates.csv` dataset from the rocky intertidal course data. These observations were collected along a shore-position gradient (`Location_m`) and from the left and right sides of the shore platform. Here we derive a binary response indicating whether acorn barnacles were present in a sampled unit.\n\n\n::: {.cell tbl-cap='A subset of the sessile-benthic invertebrate data used for the logistic-regression example.'}\n\n```{.r .cell-code}\nsessile <- read_csv(\n  file.path(\"..\", \"..\", \"data\", \"BCB744\", \"Rocky Intertidal Data\", \"Sessile_Benthic_Invertebrates.csv\"),\n  show_col_types = FALSE\n) |>\n  mutate(\n    Side = factor(Side),\n    acorn_present = as.integer(Acorn.Barnacles > 0)\n  )\n\ngt(head(sessile, 10))\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"hrvfdmmgac\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#hrvfdmmgac table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#hrvfdmmgac thead, #hrvfdmmgac tbody, #hrvfdmmgac tfoot, #hrvfdmmgac tr, #hrvfdmmgac td, #hrvfdmmgac th {\n  border-style: none;\n}\n\n#hrvfdmmgac p {\n  margin: 0;\n  padding: 0;\n}\n\n#hrvfdmmgac .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#hrvfdmmgac .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#hrvfdmmgac .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#hrvfdmmgac .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#hrvfdmmgac .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#hrvfdmmgac .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hrvfdmmgac .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#hrvfdmmgac .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#hrvfdmmgac .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#hrvfdmmgac .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#hrvfdmmgac .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#hrvfdmmgac .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#hrvfdmmgac .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#hrvfdmmgac .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#hrvfdmmgac .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#hrvfdmmgac .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#hrvfdmmgac .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#hrvfdmmgac .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#hrvfdmmgac .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hrvfdmmgac .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#hrvfdmmgac .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#hrvfdmmgac .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#hrvfdmmgac .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hrvfdmmgac .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#hrvfdmmgac .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#hrvfdmmgac .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hrvfdmmgac .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hrvfdmmgac .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#hrvfdmmgac .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hrvfdmmgac .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#hrvfdmmgac .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hrvfdmmgac .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#hrvfdmmgac .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hrvfdmmgac .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#hrvfdmmgac .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hrvfdmmgac .gt_left {\n  text-align: left;\n}\n\n#hrvfdmmgac .gt_center {\n  text-align: center;\n}\n\n#hrvfdmmgac .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#hrvfdmmgac .gt_font_normal {\n  font-weight: normal;\n}\n\n#hrvfdmmgac .gt_font_bold {\n  font-weight: bold;\n}\n\n#hrvfdmmgac .gt_font_italic {\n  font-style: italic;\n}\n\n#hrvfdmmgac .gt_super {\n  font-size: 65%;\n}\n\n#hrvfdmmgac .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#hrvfdmmgac .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#hrvfdmmgac .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#hrvfdmmgac .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#hrvfdmmgac .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#hrvfdmmgac .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#hrvfdmmgac .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#hrvfdmmgac .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#hrvfdmmgac div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Location_m\">Location_m</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Acorn.Barnacles\">Acorn.Barnacles</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Goose.Neck.Barnacles\">Goose.Neck.Barnacles</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Anemones\">Anemones</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Mussels\">Mussels</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Side\">Side</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"acorn_present\">acorn_present</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Location_m\" class=\"gt_row gt_right\">0</td>\n<td headers=\"Acorn.Barnacles\" class=\"gt_row gt_right\">2800</td>\n<td headers=\"Goose.Neck.Barnacles\" class=\"gt_row gt_right\">0</td>\n<td headers=\"Anemones\" class=\"gt_row gt_right\">240</td>\n<td headers=\"Mussels\" class=\"gt_row gt_right\">0</td>\n<td headers=\"Side\" class=\"gt_row gt_center\">Left</td>\n<td headers=\"acorn_present\" class=\"gt_row gt_right\">1</td></tr>\n    <tr><td headers=\"Location_m\" class=\"gt_row gt_right\">0</td>\n<td headers=\"Acorn.Barnacles\" class=\"gt_row gt_right\">2800</td>\n<td headers=\"Goose.Neck.Barnacles\" class=\"gt_row gt_right\">0</td>\n<td headers=\"Anemones\" class=\"gt_row gt_right\">480</td>\n<td headers=\"Mussels\" class=\"gt_row gt_right\">0</td>\n<td headers=\"Side\" class=\"gt_row gt_center\">Right</td>\n<td headers=\"acorn_present\" class=\"gt_row gt_right\">1</td></tr>\n    <tr><td headers=\"Location_m\" class=\"gt_row gt_right\">0</td>\n<td headers=\"Acorn.Barnacles\" class=\"gt_row gt_right\">0</td>\n<td headers=\"Goose.Neck.Barnacles\" class=\"gt_row gt_right\">0</td>\n<td headers=\"Anemones\" class=\"gt_row gt_right\">0</td>\n<td headers=\"Mussels\" class=\"gt_row gt_right\">0</td>\n<td headers=\"Side\" class=\"gt_row gt_center\">Right</td>\n<td headers=\"acorn_present\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"Location_m\" class=\"gt_row gt_right\">0</td>\n<td headers=\"Acorn.Barnacles\" class=\"gt_row gt_right\">0</td>\n<td headers=\"Goose.Neck.Barnacles\" class=\"gt_row gt_right\">0</td>\n<td headers=\"Anemones\" class=\"gt_row gt_right\">0</td>\n<td headers=\"Mussels\" class=\"gt_row gt_right\">0</td>\n<td headers=\"Side\" class=\"gt_row gt_center\">Left</td>\n<td headers=\"acorn_present\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"Location_m\" class=\"gt_row gt_right\">0</td>\n<td headers=\"Acorn.Barnacles\" class=\"gt_row gt_right\">4500</td>\n<td headers=\"Goose.Neck.Barnacles\" class=\"gt_row gt_right\">0</td>\n<td headers=\"Anemones\" class=\"gt_row gt_right\">0</td>\n<td headers=\"Mussels\" class=\"gt_row gt_right\">5</td>\n<td headers=\"Side\" class=\"gt_row gt_center\">Left</td>\n<td headers=\"acorn_present\" class=\"gt_row gt_right\">1</td></tr>\n    <tr><td headers=\"Location_m\" class=\"gt_row gt_right\">0</td>\n<td headers=\"Acorn.Barnacles\" class=\"gt_row gt_right\">13495</td>\n<td headers=\"Goose.Neck.Barnacles\" class=\"gt_row gt_right\">0</td>\n<td headers=\"Anemones\" class=\"gt_row gt_right\">0</td>\n<td headers=\"Mussels\" class=\"gt_row gt_right\">0</td>\n<td headers=\"Side\" class=\"gt_row gt_center\">Right</td>\n<td headers=\"acorn_present\" class=\"gt_row gt_right\">1</td></tr>\n    <tr><td headers=\"Location_m\" class=\"gt_row gt_right\">0</td>\n<td headers=\"Acorn.Barnacles\" class=\"gt_row gt_right\">300</td>\n<td headers=\"Goose.Neck.Barnacles\" class=\"gt_row gt_right\">0</td>\n<td headers=\"Anemones\" class=\"gt_row gt_right\">0</td>\n<td headers=\"Mussels\" class=\"gt_row gt_right\">0</td>\n<td headers=\"Side\" class=\"gt_row gt_center\">Left</td>\n<td headers=\"acorn_present\" class=\"gt_row gt_right\">1</td></tr>\n    <tr><td headers=\"Location_m\" class=\"gt_row gt_right\">0</td>\n<td headers=\"Acorn.Barnacles\" class=\"gt_row gt_right\">342</td>\n<td headers=\"Goose.Neck.Barnacles\" class=\"gt_row gt_right\">0</td>\n<td headers=\"Anemones\" class=\"gt_row gt_right\">0</td>\n<td headers=\"Mussels\" class=\"gt_row gt_right\">0</td>\n<td headers=\"Side\" class=\"gt_row gt_center\">Right</td>\n<td headers=\"acorn_present\" class=\"gt_row gt_right\">1</td></tr>\n    <tr><td headers=\"Location_m\" class=\"gt_row gt_right\">0</td>\n<td headers=\"Acorn.Barnacles\" class=\"gt_row gt_right\">5000</td>\n<td headers=\"Goose.Neck.Barnacles\" class=\"gt_row gt_right\">0</td>\n<td headers=\"Anemones\" class=\"gt_row gt_right\">0</td>\n<td headers=\"Mussels\" class=\"gt_row gt_right\">0</td>\n<td headers=\"Side\" class=\"gt_row gt_center\">Right</td>\n<td headers=\"acorn_present\" class=\"gt_row gt_right\">1</td></tr>\n    <tr><td headers=\"Location_m\" class=\"gt_row gt_right\">0</td>\n<td headers=\"Acorn.Barnacles\" class=\"gt_row gt_right\">1152</td>\n<td headers=\"Goose.Neck.Barnacles\" class=\"gt_row gt_right\">0</td>\n<td headers=\"Anemones\" class=\"gt_row gt_right\">22</td>\n<td headers=\"Mussels\" class=\"gt_row gt_right\">0</td>\n<td headers=\"Side\" class=\"gt_row gt_center\">Left</td>\n<td headers=\"acorn_present\" class=\"gt_row gt_right\">1</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n## Do an Exploratory Data Analysis (EDA)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsessile |>\n  summarise(\n    n = n(),\n    n_present = sum(acorn_present),\n    prop_present = mean(acorn_present),\n    min_loc = min(Location_m),\n    max_loc = max(Location_m)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 5\n      n n_present prop_present min_loc max_loc\n  <int>     <int>        <dbl>   <dbl>   <dbl>\n1   120        NA           NA       0      40\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nggplot(sessile, aes(x = Location_m, y = acorn_present)) +\n  geom_jitter(height = 0.05, width = 0, alpha = 0.35) +\n  labs(\n    x = \"Location on shore gradient (m)\",\n    y = \"Acorn barnacles present\"\n  )\n```\n\n::: {.cell-output-display}\n![Presence and absence of acorn barnacles across the shore-position gradient.](20-generalised-linear-models_files/figure-html/fig-acorn-presence-1.svg){#fig-acorn-presence}\n:::\n:::\n\n\nThe response pattern in @fig-acorn-presence is binary and clearly unsuitable for ordinary linear regression. That immediately points us to a binomial GLM.\n\n## State the Model Question and Hypotheses\n\nThe biological question is whether the probability of acorn-barnacle presence changes along the shore-position gradient.\n\n$$H_{0}: \\beta_{\\text{Location}} = 0$$\n$$H_{a}: \\beta_{\\text{Location}} \\ne 0$$\n\n## Fit the Model\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_logistic <- glm(acorn_present ~ Location_m + Side,\n                    family = binomial,\n                    data = sessile)\n\nsummary(fit_logistic)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = acorn_present ~ Location_m + Side, family = binomial, \n    data = sessile)\n\nCoefficients:\n            Estimate Std. Error z value Pr(>|z|)   \n(Intercept)  0.46201    0.33287   1.388  0.16514   \nLocation_m  -0.05270    0.01790  -2.944  0.00324 **\nSideRight   -0.07575    0.38928  -0.195  0.84572   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 159.95  on 115  degrees of freedom\nResidual deviance: 149.77  on 113  degrees of freedom\n  (4 observations deleted due to missingness)\nAIC: 155.77\n\nNumber of Fisher Scoring iterations: 4\n```\n\n\n:::\n:::\n\n\n## Test Assumptions / Check Diagnostics\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nnew_logistic <- expand.grid(\n  Location_m = seq(min(sessile$Location_m), max(sessile$Location_m), length.out = 200),\n  Side = levels(sessile$Side)\n) |>\n  as_tibble() |>\n  mutate(prob = predict(fit_logistic, newdata = cur_data(), type = \"response\"))\n\nggplot(sessile, aes(x = Location_m, y = acorn_present, colour = Side)) +\n  geom_jitter(height = 0.05, width = 0, alpha = 0.3) +\n  geom_line(data = new_logistic, aes(y = prob), linewidth = 0.9) +\n  labs(\n    x = \"Location on shore gradient (m)\",\n    y = \"Probability of presence\"\n  )\n```\n\n::: {.cell-output-display}\n![Fitted logistic-regression curves for acorn-barnacle presence along the shore-position gradient.](20-generalised-linear-models_files/figure-html/fig-logistic-fit-1.svg){#fig-logistic-fit}\n:::\n:::\n\n\nFor introductory logistic regression, the most important checks are whether the response family is appropriate and whether the fitted probability pattern in @fig-logistic-fit is biologically sensible.\n\n## Interpret the Results\n\nThe fitted location coefficient is negative (`-0.053`, `p < 0.01`), which means the log-odds of acorn-barnacle presence decline as shore position increases. In practical terms, the predicted probability of acorn-barnacle presence declines from about `0.61` near the lower end of the sampled gradient to about `0.16` near the upper end of the gradient.\n\nThe side effect is negligible in this example, so the dominant pattern is a decline in occurrence across shore position rather than a left-right platform difference.\n\n## Reporting\n\n::: {.callout-note appearance=\"simple\"}\n## Write-Up\n\n**Methods**\n\nAcorn-barnacle occurrence was analysed using a binomial generalised linear model with logit link. Presence-absence was modelled as a function of shore position (`Location_m`) and platform side (`Side`) using rocky intertidal observations from the course dataset.\n\n**Results**\n\nThe probability of acorn-barnacle presence declined significantly along the shore-position gradient (logit coefficient for `Location_m` = `-0.053`, $z = -2.94$, `p < 0.01`). The fitted probability of presence on the left side of the platform fell from about `0.61` at the low end of the sampled gradient to about `0.16` at the high end. There was no evidence that left and right sides differed strongly once location was accounted for (`p > 0.05`).\n\n**Discussion**\n\nThe ecological interpretation is that acorn barnacles became less likely to occur higher along the sampled shore gradient. In a manuscript, it is more helpful to phrase this as a change in probability of occurrence than to leave the result on the log-odds scale alone.\n:::\n\n# Example 2: Count Data and Overdispersion\n\n## Example Dataset\n\nWe now use the `Small_Mobile_Invertebrates.csv` rocky intertidal dataset. Here the response is the count of snails in each sampled unit.\n\n\n::: {.cell tbl-cap='A subset of the small mobile invertebrate data used for the count-data GLM example.'}\n\n```{.r .cell-code}\nmobile <- read_csv(\n  file.path(\"..\", \"..\", \"data\", \"BCB744\", \"Rocky Intertidal Data\", \"Small_Mobile_Invertebrates.csv\"),\n  show_col_types = FALSE\n) |>\n  mutate(Side = factor(Side))\n\ngt(head(mobile, 10))\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"jbkvfnrtqg\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#jbkvfnrtqg table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#jbkvfnrtqg thead, #jbkvfnrtqg tbody, #jbkvfnrtqg tfoot, #jbkvfnrtqg tr, #jbkvfnrtqg td, #jbkvfnrtqg th {\n  border-style: none;\n}\n\n#jbkvfnrtqg p {\n  margin: 0;\n  padding: 0;\n}\n\n#jbkvfnrtqg .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#jbkvfnrtqg .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#jbkvfnrtqg .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#jbkvfnrtqg .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#jbkvfnrtqg .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#jbkvfnrtqg .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jbkvfnrtqg .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#jbkvfnrtqg .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#jbkvfnrtqg .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#jbkvfnrtqg .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#jbkvfnrtqg .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#jbkvfnrtqg .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#jbkvfnrtqg .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#jbkvfnrtqg .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#jbkvfnrtqg .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#jbkvfnrtqg .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#jbkvfnrtqg .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#jbkvfnrtqg .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#jbkvfnrtqg .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jbkvfnrtqg .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#jbkvfnrtqg .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#jbkvfnrtqg .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#jbkvfnrtqg .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jbkvfnrtqg .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#jbkvfnrtqg .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#jbkvfnrtqg .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jbkvfnrtqg .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jbkvfnrtqg .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#jbkvfnrtqg .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jbkvfnrtqg .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#jbkvfnrtqg .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jbkvfnrtqg .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#jbkvfnrtqg .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jbkvfnrtqg .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#jbkvfnrtqg .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jbkvfnrtqg .gt_left {\n  text-align: left;\n}\n\n#jbkvfnrtqg .gt_center {\n  text-align: center;\n}\n\n#jbkvfnrtqg .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#jbkvfnrtqg .gt_font_normal {\n  font-weight: normal;\n}\n\n#jbkvfnrtqg .gt_font_bold {\n  font-weight: bold;\n}\n\n#jbkvfnrtqg .gt_font_italic {\n  font-style: italic;\n}\n\n#jbkvfnrtqg .gt_super {\n  font-size: 65%;\n}\n\n#jbkvfnrtqg .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#jbkvfnrtqg .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#jbkvfnrtqg .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#jbkvfnrtqg .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#jbkvfnrtqg .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#jbkvfnrtqg .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#jbkvfnrtqg .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#jbkvfnrtqg .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#jbkvfnrtqg div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Location_m\">Location_m</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Hermit.Crabs\">Hermit.Crabs</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Chitons\">Chitons</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Snails\">Snails</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Limpets\">Limpets</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Side\">Side</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Location_m\" class=\"gt_row gt_right\">0</td>\n<td headers=\"Hermit.Crabs\" class=\"gt_row gt_right\">0</td>\n<td headers=\"Chitons\" class=\"gt_row gt_right\">0</td>\n<td headers=\"Snails\" class=\"gt_row gt_right\">0</td>\n<td headers=\"Limpets\" class=\"gt_row gt_right\">0</td>\n<td headers=\"Side\" class=\"gt_row gt_center\">Left</td></tr>\n    <tr><td headers=\"Location_m\" class=\"gt_row gt_right\">0</td>\n<td headers=\"Hermit.Crabs\" class=\"gt_row gt_right\">0</td>\n<td headers=\"Chitons\" class=\"gt_row gt_right\">0</td>\n<td headers=\"Snails\" class=\"gt_row gt_right\">3</td>\n<td headers=\"Limpets\" class=\"gt_row gt_right\">9</td>\n<td headers=\"Side\" class=\"gt_row gt_center\">Right</td></tr>\n    <tr><td headers=\"Location_m\" class=\"gt_row gt_right\">0</td>\n<td headers=\"Hermit.Crabs\" class=\"gt_row gt_right\">0</td>\n<td headers=\"Chitons\" class=\"gt_row gt_right\">0</td>\n<td headers=\"Snails\" class=\"gt_row gt_right\">0</td>\n<td headers=\"Limpets\" class=\"gt_row gt_right\">0</td>\n<td headers=\"Side\" class=\"gt_row gt_center\">Right</td></tr>\n    <tr><td headers=\"Location_m\" class=\"gt_row gt_right\">0</td>\n<td headers=\"Hermit.Crabs\" class=\"gt_row gt_right\">0</td>\n<td headers=\"Chitons\" class=\"gt_row gt_right\">0</td>\n<td headers=\"Snails\" class=\"gt_row gt_right\">0</td>\n<td headers=\"Limpets\" class=\"gt_row gt_right\">0</td>\n<td headers=\"Side\" class=\"gt_row gt_center\">Left</td></tr>\n    <tr><td headers=\"Location_m\" class=\"gt_row gt_right\">0</td>\n<td headers=\"Hermit.Crabs\" class=\"gt_row gt_right\">0</td>\n<td headers=\"Chitons\" class=\"gt_row gt_right\">0</td>\n<td headers=\"Snails\" class=\"gt_row gt_right\">625</td>\n<td headers=\"Limpets\" class=\"gt_row gt_right\">0</td>\n<td headers=\"Side\" class=\"gt_row gt_center\">Right</td></tr>\n    <tr><td headers=\"Location_m\" class=\"gt_row gt_right\">0</td>\n<td headers=\"Hermit.Crabs\" class=\"gt_row gt_right\">0</td>\n<td headers=\"Chitons\" class=\"gt_row gt_right\">1</td>\n<td headers=\"Snails\" class=\"gt_row gt_right\">0</td>\n<td headers=\"Limpets\" class=\"gt_row gt_right\">1</td>\n<td headers=\"Side\" class=\"gt_row gt_center\">Left</td></tr>\n    <tr><td headers=\"Location_m\" class=\"gt_row gt_right\">0</td>\n<td headers=\"Hermit.Crabs\" class=\"gt_row gt_right\">0</td>\n<td headers=\"Chitons\" class=\"gt_row gt_right\">4</td>\n<td headers=\"Snails\" class=\"gt_row gt_right\">0</td>\n<td headers=\"Limpets\" class=\"gt_row gt_right\">27</td>\n<td headers=\"Side\" class=\"gt_row gt_center\">Left</td></tr>\n    <tr><td headers=\"Location_m\" class=\"gt_row gt_right\">0</td>\n<td headers=\"Hermit.Crabs\" class=\"gt_row gt_right\">0</td>\n<td headers=\"Chitons\" class=\"gt_row gt_right\">0</td>\n<td headers=\"Snails\" class=\"gt_row gt_right\">134</td>\n<td headers=\"Limpets\" class=\"gt_row gt_right\">11</td>\n<td headers=\"Side\" class=\"gt_row gt_center\">Right</td></tr>\n    <tr><td headers=\"Location_m\" class=\"gt_row gt_right\">0</td>\n<td headers=\"Hermit.Crabs\" class=\"gt_row gt_right\">0</td>\n<td headers=\"Chitons\" class=\"gt_row gt_right\">1</td>\n<td headers=\"Snails\" class=\"gt_row gt_right\">3</td>\n<td headers=\"Limpets\" class=\"gt_row gt_right\">31</td>\n<td headers=\"Side\" class=\"gt_row gt_center\">Left</td></tr>\n    <tr><td headers=\"Location_m\" class=\"gt_row gt_right\">0</td>\n<td headers=\"Hermit.Crabs\" class=\"gt_row gt_right\">0</td>\n<td headers=\"Chitons\" class=\"gt_row gt_right\">0</td>\n<td headers=\"Snails\" class=\"gt_row gt_right\">0</td>\n<td headers=\"Limpets\" class=\"gt_row gt_right\">16</td>\n<td headers=\"Side\" class=\"gt_row gt_center\">Left</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n## Do an Exploratory Data Analysis (EDA)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmobile |>\n  summarise(\n    n = n(),\n    mean_snails = mean(Snails),\n    var_snails = var(Snails),\n    max_snails = max(Snails)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 4\n      n mean_snails var_snails max_snails\n  <int>       <dbl>      <dbl>      <dbl>\n1   120          NA         NA         NA\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nggplot(mobile, aes(x = Location_m, y = Snails, colour = Side)) +\n  geom_point(alpha = 0.5) +\n  labs(\n    x = \"Location on shore gradient (m)\",\n    y = \"Snail count\"\n  )\n```\n\n::: {.cell-output-display}\n![Snail counts across the shore-position gradient.](20-generalised-linear-models_files/figure-html/fig-snail-counts-1.svg){#fig-snail-counts}\n:::\n:::\n\n\nThe counts in @fig-snail-counts are non-negative integers and include many zeros together with some very large values. That already suggests we need to be cautious about the simplest Poisson assumptions.\n\n## State the Model Question and Hypotheses\n\nThe question is whether snail abundance changes along the shore gradient and between the two sides of the shore platform.\n\n$$H_{0}: \\beta_{\\text{Location}} = 0$$\n$$H_{a}: \\beta_{\\text{Location}} \\ne 0$$\n\n## Fit the Model\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_pois <- glm(Snails ~ Location_m + Side,\n                family = poisson,\n                data = mobile)\n\nfit_qpois <- glm(Snails ~ Location_m + Side,\n                 family = quasipoisson,\n                 data = mobile)\n\nsummary(fit_pois)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = Snails ~ Location_m + Side, family = poisson, data = mobile)\n\nCoefficients:\n             Estimate Std. Error z value Pr(>|z|)    \n(Intercept)  1.801789   0.141224   12.76   <2e-16 ***\nLocation_m  -0.249638   0.009117  -27.38   <2e-16 ***\nSideRight    2.757775   0.144401   19.10   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for poisson family taken to be 1)\n\n    Null deviance: 6117.7  on 112  degrees of freedom\nResidual deviance: 2921.5  on 110  degrees of freedom\n  (7 observations deleted due to missingness)\nAIC: 3043.1\n\nNumber of Fisher Scoring iterations: 8\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(fit_qpois)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = Snails ~ Location_m + Side, family = quasipoisson, \n    data = mobile)\n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)\n(Intercept)   1.8018     6.2655   0.288    0.774\nLocation_m   -0.2496     0.4045  -0.617    0.538\nSideRight     2.7578     6.4065   0.430    0.668\n\n(Dispersion parameter for quasipoisson family taken to be 1968.325)\n\n    Null deviance: 6117.7  on 112  degrees of freedom\nResidual deviance: 2921.5  on 110  degrees of freedom\n  (7 observations deleted due to missingness)\nAIC: NA\n\nNumber of Fisher Scoring iterations: 8\n```\n\n\n:::\n:::\n\n\n## Test Assumptions / Check Diagnostics\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndispersion <- sum(residuals(fit_pois, type = \"pearson\")^2) / df.residual(fit_pois)\ndispersion\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1968.293\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nnew_count <- expand.grid(\n  Location_m = seq(min(mobile$Location_m), max(mobile$Location_m), length.out = 200),\n  Side = levels(mobile$Side)\n) |>\n  as_tibble() |>\n  mutate(mu = predict(fit_qpois, newdata = cur_data(), type = \"response\"))\n\nggplot(mobile, aes(x = Location_m, y = Snails, colour = Side)) +\n  geom_point(alpha = 0.35) +\n  geom_line(data = new_count, aes(y = mu), linewidth = 0.9) +\n  labs(\n    x = \"Location on shore gradient (m)\",\n    y = \"Snail count\"\n  )\n```\n\n::: {.cell-output-display}\n![Observed snail counts and fitted quasi-Poisson means across the shore-position gradient.](20-generalised-linear-models_files/figure-html/fig-poisson-fit-1.svg){#fig-poisson-fit}\n:::\n:::\n\n\nThe fitted curves in @fig-poisson-fit and the dispersion value of 1968.3 show that the simple Poisson model is much too optimistic. That is exactly the situation in which overdispersion must be acknowledged before interpreting the coefficients.\n\n## Interpret the Results\n\nThe Poisson model suggests that snail counts decline strongly along the shore gradient and differ between sides, but the overdispersion is so extreme that the nominal Poisson standard errors cannot be trusted.\n\nThe quasi-Poisson fit keeps the same mean structure but inflates the uncertainty appropriately. Under that more cautious model, the estimated decline with location and the side effect are no longer supported strongly. The biological conclusion therefore changes once overdispersion is taken seriously.\n\n## Reporting\n\n::: {.callout-note appearance=\"simple\"}\n## Write-Up\n\n**Methods**\n\nSnail counts from rocky intertidal samples were analysed using a count-data GLM with location along the shore gradient and platform side as predictors. A Poisson model was fitted first, and overdispersion was then assessed using the Pearson residual dispersion statistic. Because overdispersion was extreme, a quasi-Poisson model was used for interpretation.\n\n**Results**\n\nThe raw count data were highly variable, with the variance far exceeding the mean. The fitted Poisson model showed strong negative and side effects, but the dispersion statistic was approximately 1968.3, indicating severe overdispersion. Under the quasi-Poisson model, the same mean pattern remained but the standard errors were much larger, and neither predictor provided strong evidence for a clear effect (`p > 0.05`).\n\n**Discussion**\n\nThe important lesson is not only that snail counts vary along the shore. It is that count-data inference can become misleading if overdispersion is ignored. In practice, the first biologically plausible pattern should always be checked against the adequacy of the assumed count distribution.\n:::\n\n# What to Do When Assumptions Fail / Alternatives\n\n-   If a binary model shows dependence among observations, move to a generalised mixed model rather than forcing independence.\n-   If a count model is overdispersed, consider quasi-Poisson, negative binomial, or other more appropriate count models.\n-   If the response is a simple success proportion with no predictors, a proportion test may still be enough.\n-   If the link-scale coefficients are hard to interpret, translate the results back to probabilities or expected counts on the response scale.\n\n# Summary\n\n-   GLMs extend regression to binary, proportional, and count responses.\n-   The family and link function must match the response structure.\n-   Simple proportion tests are part of the same broader modelling logic as binomial GLMs.\n-   In the acorn-barnacle example, the probability of presence declined across the shore gradient.\n-   In the snail-count example, severe overdispersion changed the inferential conclusion and showed why diagnostics matter in GLMs.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}