{
  "hash": "706886852d12e860ec50a41c36de1ae0",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"12. Simple Linear Regression\"\nsubtitle: \"The Entry Point to Model-Based Biostatistics\"\ndate: last-modified\ndate-format: \"YYYY/MM/DD\"\nreference-location: margin\nparams:\n  hide_answers: true\n---\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n::: {.callout-note appearance=\"simple\"}\n## In This Chapter\n\n-   what a simple linear regression model is;\n-   when regression is more appropriate than correlation;\n-   the assumptions behind a straight-line model;\n-   how to fit a model with `lm()`;\n-   how to diagnose normality, homoscedasticity, linearity, and outliers;\n-   how to interpret slopes, fitted values, confidence intervals, and prediction intervals;\n-   how explanatory and predictive uses of the same regression differ;\n-   how to report a regression in the style of a Results section.\n:::\n\n::: {.callout-note appearance=\"simple\"}\n## Cheatsheet\n\nFind here a [Cheatsheet](../../docs/Methods_cheatsheet_v1.pdf) on statistical methods.\n:::\n\n::: {.callout-important appearance=\"simple\"}\n## Tasks to Complete in This Chapter\n\n-   Task H\n:::\n\n# Introduction\n\nLinear models are among the most useful statistical tools in biology because they allow us to describe and quantify how one variable changes with another. In a regression, we write down a model for a **response** variable, $Y$, as a function of a **predictor** variable, $X$, and then estimate the parameters of that model from the data.\n\nThe most basic of these models is the **simple linear model**, which has one continuous predictor and one continuous response. The aim may be *explanatory*, where the predictor is believed to influence the response, or *predictive*, where we want a formula that allows us to estimate likely values of the response from known values of the predictor. In either case, regression differs from [correlation](09-correlation-and-association.qmd) because it imposes a response-predictor structure on the data.\n\nAs established in Chapter 11, every observed response can be written as $Y_i = \\hat{Y}_i + e_i$, where $\\hat{Y}_i$ is the model's prediction and $e_i$ is the residual. Diagnostics inspect the $e_i$.\n\nIn the previous chapter, I defined residuals and showed how fitted models are checked. In this chapter, I apply that diagnostic checks to the full regression model.\n\nBelow, I lay the groundwork for [polynomial regression](13-polynomial-regression.qmd), [multiple regression](14-multiple-regression-and-model-specification.qmd), [interaction terms](15-interaction-effects.qmd), [generalised linear models](20-generalised-linear-models.qmd), and several of the more flexible modelling approaches discussed later. If the response-predictor structure is sound and a straight-line model is biologically plausible, simple linear regression is often the correct point of departure.\n\n# Main Concepts\n\nThese ideas organise the chapter.\n\n-   **Simple linear regression** models one continuous response as a function of one continuous predictor.\n-   **The response-predictor distinction** is essential because it is not simply putting a line onto a correlation scatter plot.\n-   **The slope** is usually the main inferential quantity because it describes the expected change in the response for a one-unit change in the predictor.\n-   **The intercept** is often less biologically interesting, but it is still part of the fitted model.\n-   **Residuals** are central to assumption checking because they reveal structure that the model has failed to capture.\n-   **Confidence intervals** and **prediction intervals** answer different questions and should not be confused.\n\n# Nature of the Data and Assumptions\n\n## Requirements Before Fitting\n\nAs the experimenter, you must ensure the following requirements *before* a simple linear regression is fitted:\n\n1. **A defensible response-predictor structure:** There should be a theoretical or philosophical basis for treating one variable as the predictor and the other as the response. This may be explicitly causal, but it can also be predictive if that distinction is still biologically sensible.\n2. **Independence of observations:** Each measured value of the response must be independent of the others. If repeated measurements, clustered sampling, or temporal dependence are present, a different modelling framework may be required.\n\n   When temporal or spatial order is plausible, plot residuals against the order in which observations were collected. Runs of positive or negative residuals, or systematic cycles, indicate dependence that the model has not captured. For the sparrow and penguin examples you will encounter below, measurements are treated as independent, so this check is not performed here.\n\n3. **Continuous predictor:** The predictor variable should be continuous.\n4. **Continuous response:** The response variable should also be continuous.\n\n## Assumptions to Check After Fitting\n\nAfter the model has been fitted, the following assumptions must be checked:\n\n1. **Normality:** The residuals $e_i$ should be approximately normally distributed.\n2. **Homoscedasticity:** The variance of the residuals $e_i$ should be roughly constant across the fitted values.\n3. **Linearity:** The mean relationship between the predictor and the response should be approximately linear.\n4. **Measurement error in the predictor:** Standard linear regression assumes that the predictor is measured without serious error. In practice this is only approximately true, and we return to this issue in [Chapter 16](16-collinearity-confounding-measurement-error.qmd).\n\nAs in the earlier inferential chapters, you must pay attention to the workflow. We first inspect the data (EDA and graphically), then fit the model, then examine the residuals (graphically first, then assumption tests if desired), and *only then* interpret the coefficients with confidence.\n\n## Assumption–Diagnostic Mapping\n\nThe table below summarises which diagnostic tool targets which assumption and what pattern to watch for.\n\n| Assumption | What it concerns | Main diagnostic | Visual signal to watch for |\n|---|---|---|---|\n| Linearity | mean structure | residual vs fitted plot | slope or curvature in residuals |\n| Constant variance | spread | residual vs fitted / scale-location | funnel or changing vertical spread |\n| Normality | residual distribution | residual Q-Q plot | systematic bends away from reference line |\n| Independence | relationship among residuals | residuals vs order/time/space | runs, cycles, clusters |\n\n# The Model\n\nSimple linear regression is the first statistical method in the work we have done thus far in which we write an explicit equation (the model) for the mean response and then estimate its parameters from data.\n\nThe model is:\n\n$$Y_i = \\alpha + \\beta X_i + \\epsilon_i$$ {#eq-slr-model}\n\nIn @eq-slr-model, $Y_i$ is the response for observation $i$, $X_i$ is the predictor, $\\alpha$ is the intercept, $\\beta$ is the slope, and $\\epsilon_i$ is the error term. Errors $\\epsilon_i$ are unobserved theoretical quantities. Residuals $e_i$ are their observed estimates, computed after fitting, and are the objects used for diagnostic checks.\n\nThe line is fitted by minimising the sum of squared residuals. This is why ordinary linear regression is often called an **ordinary least squares** method.\n\nThe animation below shows the fitted line rotating through the data as the error sum of squares is minimised.\n\n```{=html}\n<video controls width=\"82%\" style=\"display:block; margin: 0 auto;\">\n  <source src=\"../../mov/lm_rotate.mp4\" type=\"video/mp4\">\n  Your browser does not support the video tag.\n</video>\n```\n\n::: {.callout-note appearance=\"simple\"}\n## Errors and Residuals\n\nThe model contains errors $\\epsilon_i$, which are the unobserved theoretical deviations of each true response from the straight-line mean. In most regression models we assume that the errors are independent and identically distributed. When the errors are approximately normal this can be written as $\\epsilon_i \\sim N(0, \\sigma^2)$. The requirement of mean zero implies that, on average, the model does not systematically over- or under-predict. Constant variance implies that the spread of errors is roughly similar across the predictor range. Independence implies that errors do not carry systematic structure from one observation to the next.\n\nThe residuals $e_i = Y_i - \\hat{Y}_i$ are the observed estimates of these unobserved errors. It is the residuals that are available after fitting and that we inspect in diagnostic plots.\n\nViolation of these assumptions can lead to biased or inefficient parameter estimates, poor uncertainty estimates, and misleading inference.\n:::\n\nThe next section formalises how the line is chosen from the data.\n\n# The Fitting Rule\n\nThe least-squares criterion used by `lm()` is to choose $\\alpha$ and $\\beta$ so that the residual sum of squares is as small as possible:\n\n$$\\text{RSS} = \\sum_{i=1}^{n}(Y_i - \\hat{Y}_i)^2$$ {#eq-rss}\n\n@eq-rss is not a regression model. It is the fitting rule that tells us how the software decides which of all possible straight lines is the best-fitting one.\n\n# R Function\n\nThe main function used in this chapter is `lm()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm(response ~ predictor, data = df)\n```\n:::\n\n\nYou can read the formula `response ~ predictor` as \"the response is modelled as a function of the predictor.\"\n\nThe fitted model can then be explored with functions such as:\n\n-   `summary()` for the coefficients and overall fit;\n-   `confint()` for confidence intervals around the coefficients;\n-   `augment()` from **broom** for fitted values and residuals;\n-   `predict()` for confidence and prediction intervals;\n-   `plot()` for standard diagnostic plots;\n-   `bptest()` from **lmtest** for a formal test of heteroscedasticity.\n\n# Outliers and Their Impact on Simple Linear Regression\n\nOutliers can have disproportionate effects on a simple linear regression because the fitted line is estimated by minimising squared residuals, as in @eq-rss. Extreme observations may therefore influence the slope, the intercept, the standard errors, the confidence intervals, and the diagnostic patterns.\n\nThis does not mean that unusual observations must automatically be removed. Some are recording errors and should be corrected or excluded. Others are rare but real biological events and may carry important information. The correct response is therefore to identify potentially influential points, inspect them carefully, and decide whether they reveal error, unusual but valid biology, or a more fundamental model problem.\n\n# Example 1: Sparrow Wing Length and Age\n\n::: {.callout-note appearance=\"simple\"}\n## Diagnostic Workflow for Simple Linear Regression\n\n1. Fit the model with `lm()`.\n2. Plot residuals versus fitted values — check for curvature (linearity) and changing spread (constant variance).\n3. Plot the residual Q-Q plot — check whether the residual distribution is close enough to normal.\n4. If temporal or spatial order is plausible, plot residuals against order — check for runs or cycles (independence).\n5. Inspect Cook's distance and leverage — identify observations with disproportionate influence.\n6. Revise the model if any diagnostic reveals leftover structure.\n:::\n\nI begin with a very small sparrow dataset because it makes the general approach clear. I then go to a fuller worked example using the Adelie penguin data from the `palmerpenguins` package, which is much closer to the style and level of complexity encountered in real biological analyses.\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {#tbl-gt-sparrows .cell tbl-cap='Sparrow wing-length data used in the introductory simple linear regression example.'}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"xntwsueuhk\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#xntwsueuhk table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#xntwsueuhk thead, #xntwsueuhk tbody, #xntwsueuhk tfoot, #xntwsueuhk tr, #xntwsueuhk td, #xntwsueuhk th {\n  border-style: none;\n}\n\n#xntwsueuhk p {\n  margin: 0;\n  padding: 0;\n}\n\n#xntwsueuhk .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#xntwsueuhk .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#xntwsueuhk .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#xntwsueuhk .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#xntwsueuhk .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#xntwsueuhk .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xntwsueuhk .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#xntwsueuhk .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#xntwsueuhk .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#xntwsueuhk .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#xntwsueuhk .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#xntwsueuhk .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#xntwsueuhk .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#xntwsueuhk .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#xntwsueuhk .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#xntwsueuhk .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#xntwsueuhk .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#xntwsueuhk .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#xntwsueuhk .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xntwsueuhk .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#xntwsueuhk .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#xntwsueuhk .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#xntwsueuhk .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xntwsueuhk .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#xntwsueuhk .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#xntwsueuhk .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xntwsueuhk .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xntwsueuhk .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#xntwsueuhk .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xntwsueuhk .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#xntwsueuhk .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xntwsueuhk .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#xntwsueuhk .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xntwsueuhk .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#xntwsueuhk .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xntwsueuhk .gt_left {\n  text-align: left;\n}\n\n#xntwsueuhk .gt_center {\n  text-align: center;\n}\n\n#xntwsueuhk .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#xntwsueuhk .gt_font_normal {\n  font-weight: normal;\n}\n\n#xntwsueuhk .gt_font_bold {\n  font-weight: bold;\n}\n\n#xntwsueuhk .gt_font_italic {\n  font-style: italic;\n}\n\n#xntwsueuhk .gt_super {\n  font-size: 65%;\n}\n\n#xntwsueuhk .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#xntwsueuhk .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#xntwsueuhk .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#xntwsueuhk .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#xntwsueuhk .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#xntwsueuhk .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#xntwsueuhk .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#xntwsueuhk .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#xntwsueuhk div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"age\">Age (days)</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"wing\">Wing length<br>(cm)</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"age\" class=\"gt_row gt_right\">3</td>\n<td headers=\"wing\" class=\"gt_row gt_right\">1.4</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right\">4</td>\n<td headers=\"wing\" class=\"gt_row gt_right\">1.5</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right\">5</td>\n<td headers=\"wing\" class=\"gt_row gt_right\">2.2</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right\">6</td>\n<td headers=\"wing\" class=\"gt_row gt_right\">2.4</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right\">8</td>\n<td headers=\"wing\" class=\"gt_row gt_right\">3.1</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right\">9</td>\n<td headers=\"wing\" class=\"gt_row gt_right\">3.2</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right\">10</td>\n<td headers=\"wing\" class=\"gt_row gt_right\">3.2</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right\">11</td>\n<td headers=\"wing\" class=\"gt_row gt_right\">3.9</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right\">12</td>\n<td headers=\"wing\" class=\"gt_row gt_right\">4.1</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right\">14</td>\n<td headers=\"wing\" class=\"gt_row gt_right\">4.7</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right\">15</td>\n<td headers=\"wing\" class=\"gt_row gt_right\">4.5</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right\">16</td>\n<td headers=\"wing\" class=\"gt_row gt_right\">5.2</td></tr>\n    <tr><td headers=\"age\" class=\"gt_row gt_right\">17</td>\n<td headers=\"wing\" class=\"gt_row gt_right\">5.0</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n## Do an Exploratory Data Analysis (EDA)\n\nThe sparrow data show the basic form of a simple linear model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(sparrows)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      age          wing      \n Min.   : 3   Min.   :1.400  \n 1st Qu.: 6   1st Qu.:2.400  \n Median :10   Median :3.200  \n Mean   :10   Mean   :3.415  \n 3rd Qu.:14   3rd Qu.:4.500  \n Max.   :17   Max.   :5.200  \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Wing length of sparrows at different ages.](12-simple-linear-regression_files/figure-html/fig-sparrow-1.svg){#fig-sparrow}\n:::\n:::\n\n\nIn @fig-sparrow, the scatter plot suggests a clear positive linear relationship: older sparrows tend to have longer wings, and the relationship appears close to linear over the range of the data. This example makes the fitted line and the slope easy to understand before we look at a noisier dataset.\n\n## State the Model Question and Hypothesis\n\nWith the sparrow example, I ask whether wing length changes systematically with age.\n\nThe statistic of interest in a simple linear regression is usually the slope in @eq-slr-model, which quantifies the magnitude and direction of dependence of the response on the predictor:\n\n$$H_{0}: \\beta = 0$$\n$$H_{a}: \\beta \\ne 0$$\n\nIf the slope is zero (a more-or-less horizontal line), there is no linear relationship between the predictor and the expected value of the response. If the slope differs from zero, then the predictor helps explain variation in the response.\n\n## Fit the Model\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsparrow_mod <- lm(wing ~ age, data = sparrows)\nsummary(sparrow_mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = wing ~ age, data = sparrows)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.30699 -0.21538  0.06553  0.16324  0.22507 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  0.71309    0.14790   4.821 0.000535 ***\nage          0.27023    0.01349  20.027 5.27e-10 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.2184 on 11 degrees of freedom\nMultiple R-squared:  0.9733,\tAdjusted R-squared:  0.9709 \nF-statistic: 401.1 on 1 and 11 DF,  p-value: 5.267e-10\n```\n\n\n:::\n:::\n\n\nThe output provides the intercept, the slope, their standard errors, a test of whether the coefficients differ from zero, the residual standard error, and the model $R^2$.\n\n## Test the Assumptions\n\nAssumptions in regression are checked after fitting the model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsparrow_aug <- augment(sparrow_mod)\nsparrow_aug |>\n  select(age, wing, .fitted, .resid) |>\n  head()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 4\n    age  wing .fitted  .resid\n  <dbl> <dbl>   <dbl>   <dbl>\n1     3   1.4    1.52 -0.124 \n2     4   1.5    1.79 -0.294 \n3     5   2.2    2.06  0.136 \n4     6   2.4    2.33  0.0655\n5     8   3.1    2.87  0.225 \n6     9   3.2    3.15  0.0548\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](12-simple-linear-regression_files/figure-html/fig-sparrow-diagnostics-1.svg){#fig-sparrow-diagnostics}\n:::\n:::\n\n\n### Normality\n\nThe Q-Q panel in @fig-sparrow-diagnostics shows the sample quantiles of the residuals plotted against the theoretical quantiles of a normal distribution. For these data the points track close to the reference line, indicating that the residuals do not depart strongly from normality.\n\n### Homoscedasticity\n\nThe residuals-versus-fitted panel in @fig-sparrow-diagnostics does not reveal a systematic funnel or wedge pattern. The spread of residuals appears reasonably even across the range of fitted values, consistent with the constant-variance assumption.\n\n### Influential observations\n\nBecause the dataset contains only 13 observations, formal influence diagnostics have limited statistical power. No single observation stands out dramatically in the scale-location or Cook's-distance panels, but conclusions based on such a small sample should be interpreted cautiously.\n\nIn @fig-sparrow-diagnostics, the diagnostic plots suggest that the model is broadly adequate for these data. The residuals do not show severe curvature, the spread is reasonably even, and the Q-Q plot does not suggest a dramatic departure from normality. Because the dataset is small, these plots should be interpreted cautiously, but there is no obvious reason to abandon the linear model.\n\n## Interpret the Results\n\nInference applies within the observed range of the predictor. Extrapolation beyond the data is possible but requires explicit justification, because the straight-line form may not hold outside the observed range.\n\nI construct the final model fit as a figure, which I will use in my reporting.\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Wing length as a function of age in the sparrow example. The straight line is the fitted simple linear regression and the blue shading is the 95% confidence interval.](12-simple-linear-regression_files/figure-html/fig-sparrow-results-1.svg){#fig-sparrow-results}\n:::\n:::\n\n\nIn @fig-sparrow-results, the fitted slope is positive, which means that wing length increases with age. In this example, the slope estimate is about 0.27 cm per day, so the model implies that the expected wing length increases by roughly 0.27 cm for each additional day of age across the range of these observations.\n\nThe intercept is the expected wing length when age is zero. Here that value is not biologically the main point of interest. It is simply the point where the fitted line crosses the vertical axis.\n\nThe model explains a large proportion of the variation in the observed wing lengths ($R^2 \\approx 0.97$), and the test of the slope provides very strong evidence that the linear relationship is not zero ($p < 0.001$).\n\n## Reporting\n\n::: {.callout-note appearance=\"simple\"}\n## Write-Up\n\n**Methods**\n\nThe relationship between sparrow wing length and age was assessed with a simple linear regression, with wing length as the response variable and age as the continuous predictor. Model adequacy was evaluated from standard residual diagnostics.\n\n**Results**\n\nSparrow wing length increased strongly with age in the fitted simple linear regression ($\\beta = 0.270$, 95% CI: 0.241 to 0.300; $R^2 = 0.97$; $p < 0.001$) (@fig-sparrow-results). Across the observed age range, older birds therefore had consistently longer wings, with the expected wing length increasing by about 0.27 cm for each additional day of age.\n\n**Discussion**\n\nThis example is useful because it makes the biological interpretation of the slope very clear: age is associated with a strong increase in wing length over the observed range, and the fitted line captures most of the variation in these simple demonstration data.\n:::\n\n# Example 2: Adelie Penguin Bill Length and Body Mass\n\nThe following example uses the `penguins` dataset from the `palmerpenguins` package to model bill length as a function of body mass in Adelie penguins.\n\nAlthough I could also calculate a correlation, I will use a simple linear regression because I want a predictive model that estimates bill length from body mass. This is a defensible use of simple linear regression even though I am not claiming that body mass directly causes bill length.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nAdelie <- penguins[penguins$species == \"Adelie\", ]\nAdelie <- Adelie[-4, ]\n```\n:::\n\n\n\n::: {#tbl-penguins .cell tbl-cap='Size measurements for adult foraging Adelie penguins near Palmer Station, Antarctica.'}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"lvyocbqjem\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#lvyocbqjem table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#lvyocbqjem thead, #lvyocbqjem tbody, #lvyocbqjem tfoot, #lvyocbqjem tr, #lvyocbqjem td, #lvyocbqjem th {\n  border-style: none;\n}\n\n#lvyocbqjem p {\n  margin: 0;\n  padding: 0;\n}\n\n#lvyocbqjem .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#lvyocbqjem .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#lvyocbqjem .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#lvyocbqjem .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#lvyocbqjem .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#lvyocbqjem .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#lvyocbqjem .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#lvyocbqjem .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#lvyocbqjem .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#lvyocbqjem .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#lvyocbqjem .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#lvyocbqjem .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#lvyocbqjem .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#lvyocbqjem .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#lvyocbqjem .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#lvyocbqjem .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#lvyocbqjem .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#lvyocbqjem .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#lvyocbqjem .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lvyocbqjem .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#lvyocbqjem .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#lvyocbqjem .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#lvyocbqjem .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lvyocbqjem .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#lvyocbqjem .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#lvyocbqjem .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#lvyocbqjem .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lvyocbqjem .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#lvyocbqjem .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#lvyocbqjem .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#lvyocbqjem .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#lvyocbqjem .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#lvyocbqjem .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lvyocbqjem .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#lvyocbqjem .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lvyocbqjem .gt_left {\n  text-align: left;\n}\n\n#lvyocbqjem .gt_center {\n  text-align: center;\n}\n\n#lvyocbqjem .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#lvyocbqjem .gt_font_normal {\n  font-weight: normal;\n}\n\n#lvyocbqjem .gt_font_bold {\n  font-weight: bold;\n}\n\n#lvyocbqjem .gt_font_italic {\n  font-style: italic;\n}\n\n#lvyocbqjem .gt_super {\n  font-size: 65%;\n}\n\n#lvyocbqjem .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#lvyocbqjem .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#lvyocbqjem .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#lvyocbqjem .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#lvyocbqjem .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#lvyocbqjem .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#lvyocbqjem .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#lvyocbqjem .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#lvyocbqjem div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"bill_length_mm\">Bill length (mm)</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"body_mass_g\">Body mass (g)</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"bill_length_mm\" class=\"gt_row gt_right\">39.1</td>\n<td headers=\"body_mass_g\" class=\"gt_row gt_right\">3750</td></tr>\n    <tr><td headers=\"bill_length_mm\" class=\"gt_row gt_right\">39.5</td>\n<td headers=\"body_mass_g\" class=\"gt_row gt_right\">3800</td></tr>\n    <tr><td headers=\"bill_length_mm\" class=\"gt_row gt_right\">40.3</td>\n<td headers=\"body_mass_g\" class=\"gt_row gt_right\">3250</td></tr>\n    <tr><td headers=\"bill_length_mm\" class=\"gt_row gt_right\">36.7</td>\n<td headers=\"body_mass_g\" class=\"gt_row gt_right\">3450</td></tr>\n    <tr><td headers=\"bill_length_mm\" class=\"gt_row gt_right\">39.3</td>\n<td headers=\"body_mass_g\" class=\"gt_row gt_right\">3650</td></tr>\n    <tr><td headers=\"bill_length_mm\" class=\"gt_row gt_right\">38.9</td>\n<td headers=\"body_mass_g\" class=\"gt_row gt_right\">3625</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n## Do an Exploratory Data Analysis (EDA)\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(Adelie)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 151   8\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(Adelie)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      species          island   bill_length_mm  bill_depth_mm  \n Adelie   :151   Biscoe   :44   Min.   :32.10   Min.   :15.50  \n Chinstrap:  0   Dream    :56   1st Qu.:36.75   1st Qu.:17.50  \n Gentoo   :  0   Torgersen:51   Median :38.80   Median :18.40  \n                                Mean   :38.79   Mean   :18.35  \n                                3rd Qu.:40.75   3rd Qu.:19.00  \n                                Max.   :46.00   Max.   :21.50  \n flipper_length_mm  body_mass_g       sex          year     \n Min.   :172       Min.   :2850   female:73   Min.   :2007  \n 1st Qu.:186       1st Qu.:3350   male  :73   1st Qu.:2007  \n Median :190       Median :3700   NA's  : 5   Median :2008  \n Mean   :190       Mean   :3701               Mean   :2008  \n 3rd Qu.:195       3rd Qu.:4000               3rd Qu.:2009  \n Max.   :210       Max.   :4775               Max.   :2009  \n```\n\n\n:::\n:::\n\n\nWe see that the dataset contains many more observations than the sparrow example. I focus here on `body_mass_g` and `bill_length_mm`. Both are continuous, and restricting the analysis to Adelie penguins gives me a relatively coherent biological subset for the example.\n\n## Create a Plot\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(Adelie,\n       aes(x = body_mass_g, y = bill_length_mm)) +\n  geom_smooth(method = \"lm\", linewidth = 0.4, alpha = 0.4,\n              colour = \"black\", se = TRUE, fill = \"dodgerblue\") +\n  geom_point(shape = 1, colour = \"indianred\") +\n  labs(x = \"Body mass (g)\", y = \"Bill length (mm)\")\n```\n\n::: {.cell-output-display}\n![Scatter plot of the Palmer Station Adelie penguin data with a best fit line.](12-simple-linear-regression_files/figure-html/fig-penguin-slr-1.svg){#fig-penguin-slr}\n:::\n:::\n\n\nIn @fig-penguin-slr, there is also a clear positive relationship between body mass and bill length despite considerable scatter. This relationship appears linear enough to justify a simple linear model as a first approximation. Creating a publication-quality plot complete with the regression line in place preempts the model fitting, but I can use it later for reporting should it turn out that the model fit is defensible.\n\n## State the Hypothesis\n\n$$H_{0}: \\beta = 0$$\n$$H_{a}: \\beta \\ne 0$$\n\nThe null hypothesis is that body mass has no linear association with bill length, while the alternative is that the slope differs from zero.\n\nIf the slope is zero, then the predictor does not explain systematic change in the expected response.\n\n## Fit the Model\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod1 <- lm(bill_length_mm ~ body_mass_g,\n           data = Adelie)\nsummary(mod1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = bill_length_mm ~ body_mass_g, data = Adelie)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-6.4208 -1.3690  0.1874  1.4825  5.6168 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 2.699e+01  1.483e+00  18.201  < 2e-16 ***\nbody_mass_g 3.188e-03  3.977e-04   8.015 2.95e-13 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2.234 on 149 degrees of freedom\nMultiple R-squared:  0.3013,\tAdjusted R-squared:  0.2966 \nF-statistic: 64.24 on 1 and 149 DF,  p-value: 2.955e-13\n```\n\n\n:::\n:::\n\n\n## Test the Assumptions\n\nTo facilitate assumption checking I use `augment()` from **broom** to add fitted values, residuals, leverage, and related diagnostics to the data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod1_data <- augment(mod1)\n```\n:::\n\n\n### Normality\n\nI use the Shapiro-Wilk test as one formal check of the residual distribution.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshapiro.test(residuals(mod1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  residuals(mod1)\nW = 0.99613, p-value = 0.9637\n```\n\n\n:::\n:::\n\n\nThe formal test does not flag a serious departure from normality here, but graphical diagnostics are usually more informative than the test alone, especially in moderate samples where the test has limited power to detect mild departures.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Diagnostic plots for the simple linear regression of Adelie penguin bill length on body mass. A) Normal Q-Q plot. B) Histogram of residuals. C) Residuals versus fitted values. D) Scale-location plot.](12-simple-linear-regression_files/figure-html/fig-assump-plots-1.svg){#fig-assump-plots}\n:::\n:::\n\n\nIn @fig-assump-plots, the Q-Q plot and histogram suggest that the residuals are approximately normally distributed. There is no obvious extreme departure that would make the model immediately unusable.\n\n### Homoscedasticity\n\nThe Breusch-Pagan test is one formal check of constant variance.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbptest(mod1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tstudentized Breusch-Pagan test\n\ndata:  mod1\nBP = 1.6677, df = 1, p-value = 0.1966\n```\n\n\n:::\n:::\n\n\nThe formal test is consistent with the visual impression from the residual plots. Graphical inspection should take precedence: if the scale-location plot shows a clear trend, the spread is not constant regardless of the test p-value. The test does not suggest strong heteroscedasticity, and the residuals-versus-fitted and scale-location panels in @fig-assump-plots also indicate that the spread of residuals is reasonably even across the fitted range.\n\n### Check for Outliers\n\nOutliers and influential observations can be explored in several complementary ways. Here I look at DFFITS, Cook's distance, residuals versus leverage, and Cook's distance versus leverage. Each diagnostic captures a different facet of how an observation affects the fitted model.\n\n**Leverage** measures how far an observation's predictor value sits from the centre of the predictor distribution. A high-leverage point has an unusual $X$ value. Leverage alone is not a problem: if a high-leverage point falls close to the fitted line, it does not distort it. The concern arises when a high-leverage point also has a large residual, because then it pulls the fitted line toward itself without the rest of the data providing a counterweight.\n\n**Cook's distance** measures the total change in all fitted values when one observation is removed from the fit. It therefore captures *overall influence*: a point with a large Cook's distance shifts the entire fitted surface when excluded. The threshold used here is $4/n$, where $n$ is the number of observations. Points exceeding this threshold are flagged for closer inspection, though the threshold is a rough guide rather than a firm rule.\n\n**DFFITS** (Difference in Fits) measures how much the fitted value *at that specific observation* changes when the observation is removed, expressed in units of estimated standard errors. Unlike Cook's distance, which summarises influence on all fitted values, DFFITS focuses on the local fitted value. The threshold here is $2\\sqrt{p/n}$, where $p$ is the number of model parameters. A bar extending beyond the dashed threshold lines indicates an observation whose removal would notably shift the prediction at that point.\n\n**Residuals versus leverage** (panel C) combines the two sources of concern on a single plot. Leverage is on the $x$-axis and standardised residuals are on the $y$-axis. Points to the right have unusual predictor values; points far from zero on the $y$-axis have large residuals. The most problematic observations are those that appear simultaneously in the right (high leverage) and top or bottom (large residual) of the plot. Point size encodes Cook's distance, so large symbols in the upper or lower right are the highest priority to inspect.\n\n**Cook's distance versus leverage** (panel D) makes the relationship between position and influence explicit. Points that sit to the right of the vertical dashed line (twice the mean leverage) and above the horizontal dashed line (the Cook's threshold) combine both unusual predictor position and substantial overall influence. Any point in that upper-right region should be examined in the raw data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncooksd_thresh <- 4 / nrow(mod1_data)\ndffits_threshold <- 2 * sqrt(2 / nrow(Adelie))\n\nmod1_data <- mod1_data %>%\n  mutate(index = row_number(),\n         leverage = hatvalues(mod1),\n         dffits = dffits(mod1),\n         colour = ifelse(.cooksd > cooksd_thresh, \"black\", \"pink\"))\n```\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Diagnostic plots for visual inspection of outliers in the Adelie penguin regression. A) DFFITS. B) Cook's distance. C) Residuals versus leverage. D) Cook's distance versus leverage. Observations beyond the Cook's distance threshold are shown in black and labelled by row number.](12-simple-linear-regression_files/figure-html/fig-penguin-outliers1-1.svg){#fig-penguin-outliers1}\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Scatter plot of Adelie penguin bill length against body mass, with observations exceeding the Cook's distance threshold highlighted.](12-simple-linear-regression_files/figure-html/fig-penguin-outliers2-1.svg){#fig-penguin-outliers2}\n:::\n:::\n\n\nReading @fig-penguin-outliers1 panel by panel:\n\n- **Panel A (DFFITS):** Most bars are well within the dashed threshold lines. No single bar extends far beyond the threshold, so no observation shifts its own fitted value dramatically when removed.\n- **Panel B (Cook's distance):** A handful of bars just exceed or approach the $4/n$ threshold (dashed red line), shown in black and labelled by row number. These are the candidates to inspect further, but no bar is dramatically taller than its neighbours.\n- **Panel C (Residuals vs leverage):** The vertical dashed blue line marks twice the mean leverage. Most points cluster toward the left (low leverage) and within ±2 standardised residuals. A few points sit near or beyond the leverage threshold, but none combine extreme leverage with a large residual. Point sizes (Cook's distance) are small throughout.\n- **Panel D (Cook's distance vs leverage):** Points above the horizontal threshold and to the right of the vertical threshold would be the highest-concern observations. Here no point occupies the upper-right region simultaneously.\n\n@fig-penguin-outliers2 locates the flagged observations in the original scatter plot. Highlighted points are not at the extremes of either variable and are not pulling the line in an obvious direction.\n\nFigures @fig-penguin-outliers1 and @fig-penguin-outliers2 do not suggest a catastrophic influence problem, but they do suggest that some observations contribute more to the fitted line than others. If an identified point was an obvious data-entry error, I could correct or exclude it. If it was a real biological extreme, I'd keep it and discuss its influence.\n\n## Interpret the Results\n\nNow that the assumptions appear broadly acceptable, I can interpret the fitted model. The slope of the regression line is positive, so bill length increases with body mass. The coefficient is about $3.2 \\times 10^{-3}$ mm/g, meaning that the expected bill length increases by about 0.0032 mm for every additional gram of body mass.\n\nNote that the units of the slope depend directly on the units of both variables. Here the slope is expressed in mm per gram, which produces a small numerical value. Rescaling body mass to kilograms (dividing by 1000) would yield a slope of about 3.2 mm/kg, which is easier to describe verbally. The biological meaning is unchanged.\n\nThe multiple $R^2$ is about 0.30, so the model explains roughly 30% of the observed variation in bill length. A biologically informative regression does not *need* to explain nearly all the variation in the response to be worthwhile.\n\nThe test of the slope provides strong evidence that the relationship is not zero ($p < 0.001$). I apply an ANOVA on the fitted model and this leads me to the same practical conclusion, which is that the straight-line model explains a meaningful amount of variation in bill length.\n\nAmong the diagnostics, the residuals-versus-fitted plot is the most informative here. The spread is reasonably even and there is no clear curvature, which supports the straight-line mean structure for this species subset.\n\nHad the Q-Q plot shown strong tail departures or the residual spread changed markedly across the fitted range, the next step would be to consider a response transformation, a different model family, or the inclusion of additional predictors.\n\n## Reporting\n\n::: {.callout-note appearance=\"simple\"}\n## Write-Up\n\n**Methods**\n\nThe data analysed in this example were drawn from the Palmer Penguins dataset, which contains measurements on penguins sampled in the Palmer Archipelago, Antarctica. For this worked example, only Adelie penguins were retained. Bill length was treated as the response variable and body mass as the continuous predictor.\n\nA simple linear regression model was fitted using `lm()` in R, with bill length modelled as a function of body mass. Model adequacy was assessed by inspecting residual plots, by applying the Shapiro-Wilk test to the residuals, and by using the Breusch-Pagan test to assess homoscedasticity. Influential observations were explored using Cook's distance, DFFITS, and leverage-based diagnostics.\n\n**Results**\n\nBill length increased with body mass in the fitted simple linear regression ($\\beta = 0.00319$, SE = 0.00040, $t = 8.02$, $p < 0.001$) (@fig-penguin-slr). The model explained about 30% of the variation in bill length ($R^2 = 0.30$), indicating that body mass was an informative but incomplete predictor of bill length. The overall model was also strongly supported by the ANOVA ($F = 64.25$, $p < 0.001$, d.f. = 1, 149).\n\n**Discussion**\n\nThe worked example supports a positive relationship between body mass and bill length in Adelie penguins, but it also shows the limits of a one-predictor model. Body mass explains part of the variation in bill length, not all of it. A fuller biological account would need additional predictors such as sex, age, or ecological context.\n:::\n\n# Confidence and Prediction Intervals\n\nThe fitted line gives the expected mean response for a given value of the predictor, but two different kinds of interval are commonly needed.\n\n-   A **confidence interval** describes uncertainty in the estimated mean response.\n-   A **prediction interval** describes uncertainty for an individual future observation.\n\nThe prediction interval is always wider because it must include the scatter of individual observations around the fitted mean.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnew_x <- tibble(age = c(7, 13))\npredict(sparrow_mod, newdata = new_x, interval = \"confidence\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       fit      lwr      upr\n1 2.604698 2.444344 2.765051\n2 4.226072 4.065719 4.386425\n```\n\n\n:::\n\n```{.r .cell-code}\npredict(sparrow_mod, newdata = new_x, interval = \"prediction\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       fit      lwr      upr\n1 2.604698 2.097951 3.111444\n2 4.226072 3.719325 4.732818\n```\n\n\n:::\n:::\n\n\nI can also visualise the same distinction in the penguin example.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npred_conf <- as.data.frame(predict(mod1,\n                                   newdata = Adelie,\n                                   interval = \"confidence\"))\n\npred_pred <- as.data.frame(predict(mod1,\n                                   newdata = Adelie,\n                                   interval = \"prediction\"))\n\nresults <- cbind(Adelie, pred_conf, pred_pred[, 2:3])\nnames(results)[c(9:13)] <- c(\"fit\", \"lwr_conf\", \"upr_conf\",\n                             \"lwr_pred\", \"upr_pred\")\n\nggplot(data = results, aes(x = body_mass_g, y = fit)) +\n  geom_line(linewidth = 0.4, colour = \"red\") +\n  geom_ribbon(aes(ymin = lwr_pred, ymax = upr_pred),\n              alpha = 0.2, fill = \"red\") +\n  geom_ribbon(aes(ymin = lwr_conf, ymax = upr_conf),\n              alpha = 0.2, fill = \"blue\") +\n  geom_point(aes(y = bill_length_mm), shape = 1) +\n  labs(x = \"Body mass (g)\", y = \"Bill length (mm)\") +\n  theme_grey()\n```\n\n::: {.cell-output-display}\n![Adelie penguin bill length model with confidence interval (blue) and prediction interval (pink) around the fitted values.](12-simple-linear-regression_files/figure-html/fig-penguin-intervals-1.svg){#fig-penguin-intervals}\n:::\n:::\n\n\nIn @fig-penguin-intervals, the blue confidence band is narrower because it describes uncertainty around the fitted mean response, whereas the pink prediction band is wider because it must also accommodate the scatter of individual penguins around that mean. Confidence intervals are therefore useful when the primary interest lies in the mean expected response at a given predictor value. Prediction intervals are more relevant when the goal is to anticipate the range in which an individual future observation may fall.\n\n# Prediction Versus Explanation\n\nThe same fitted straight-line model can be used for at least two different scientific purposes.\n\n-   In an **explanatory** analysis, the main interest is usually the slope itself and what it says about the biological relationship between the predictor and the response.\n-   In a **predictive** analysis, the emphasis shifts toward fitted values, prediction intervals, and how accurately the model can anticipate new observations.\n\nThe sparrow example is mostly explanatory. We care primarily that wing length increases with age and that the slope is clearly positive. The Adelie penguin example is closer to a predictive framing because we have treated body mass as a variable from which bill length might be estimated for new individuals.\n\nThe distinction is important because it changes what should be emphasised in a Results section. Explanatory work usually emphasises the slope, its uncertainty, and the biological interpretation of the effect. Predictive work still needs the model coefficients, but it should pay much more attention to fitted values, prediction intervals, and the amount of unexplained variation.\n\nThis is also why a model with a highly significant slope is not automatically a good predictive model. A relationship can be biologically real and still leave substantial scatter around the fitted line, as in @fig-penguin-slr. Conversely, a model that predicts well is not automatically evidence for a causal mechanism. In [Chapter 24](24-prediction-and-explanation.qmd), I return to this distinction.\n\n# What to Do When Assumptions Fail\n\nIf the assumptions of the linear model are not adequate, the first step is not to abandon the analysis mechanically but to ask what the diagnostic pattern is telling you.\n\n-   If the residuals suggest **non-linearity**, consider whether the relationship should be transformed or whether a more flexible model is needed.\n-   If the residual variance changes strongly with fitted values, consider transformation or a different modelling approach. [Chapter 6](06-assumptions-and-transformations.qmd) dealt with the raw-data version of this problem; here the same issue appears in the residuals.\n-   If outliers have strong leverage or influence, inspect them carefully before deciding what to do.\n-   If the real question is still only one of association, and not response modelling, return to [Chapter 9](09-correlation-and-association.qmd).\n\n# Common Mistakes\n\nCommon mistakes in simple linear regression include:\n\n-   using regression when the relationship is only associative and poorly justified as a response-predictor model;\n-   ignoring non-independence among observations;\n-   fitting a straight line to a clearly curved relationship;\n-   treating statistical significance as biological importance;\n-   reporting $R^2$ without discussing effect size, uncertainty, or assumptions.\n\n:::: {.callout-warning appearance=\"simple\"}\n## Self-Assessment Task H.3\n\nFind **two datasets** of your own and do a full simple linear regression analysis on each. Briefly describe the data and why they exist. State appropriate hypotheses, do an EDA, make exploratory figures, fit the model, show the fitted line, assess assumptions with diagnostic plots, and write up the results in publication style.\n\n::: {.content-hidden}\n\n**Answer**\n\nA strong answer should include all of the following:\n\n1. **Dataset choice and justification**\n   Explain what each dataset measures, why the response-predictor structure is defensible, and why a straight-line model is biologically sensible as a first approximation.\n2. **Hypotheses**\n   State the null and alternative hypotheses in terms of the slope:\n\n$$H_0: \\beta = 0$$\n$$H_a: \\beta \\ne 0$$\n\n3. **EDA**\n   Provide summary statistics and scatterplots. Comment on outliers, clustering, spread, and whether a straight-line relationship looks plausible.\n4. **Model fitting**\n   Fit the model with `lm(response ~ predictor, data = ...)`, then report the estimated slope, its standard error, confidence interval, the model $R^2$, and the p-value for the slope.\n5. **Diagnostics**\n   Show at least a residuals-versus-fitted plot and a residual Q-Q plot. Explain what they imply about linearity, constant variance, and approximate normality.\n6. **Results section**\n   Write a concise Methods/Results style paragraph that reports the effect size, uncertainty, direction of the relationship, and the biological meaning of the model.\n\nA weak answer merely pastes R output. A strong answer interprets the slope biologically, justifies the model choice, and links the diagnostics to whether the model is trustworthy.\n\n:::\n::::\n\n# Summary\n\n-   Simple linear regression models one continuous response as a function of one continuous predictor.\n-   The slope is usually the main inferential quantity because it describes how the expected response changes with the predictor.\n-   Regression differs from correlation because it imposes a response-predictor structure.\n-   Residual diagnostics are essential because they tell us whether the model is adequate.\n-   Outlier diagnostics help us decide whether unusual observations are errors, influential extremes, or signs of model misspecification.\n-   Confidence intervals and prediction intervals answer different questions.\n\nI established the workflow for modelling, above. In the next chapter, I extend the same workflow to curved relationships, and in [Chapter 14](14-multiple-regression-and-model-specification.qmd) I then move to several predictors at once.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}