{
  "hash": "d74c813db4035831788970996d15842a",
  "result": {
    "engine": "knitr",
    "markdown": "---\ndate: last-modified\ntitle: \"9a: Correspondence Analysis (CA)\"\nauthor: \"A. J. Smit\"\n\n---\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n<!-- # Topic 9: Correspondence Analysis (CA) -->\n\n::: callout-tip\n## **Material Required for This Chapter**\n\n| Type           | Name                                     | Link                                                                              |\n| :--- | :--- | :--- |\n| **Theory**     | Numerical Ecology with R                   | See pages 132-140                                                                 |\n| **Slides**     | CA lecture slides                        | [💾 `BCB743_09_CA.pdf`](../slides/BCB743_09_CA.pdf)                               |\n| **Data**       | The Doubs River data                     | [💾 `Doubs.RData`](../data/BCB743/NEwR-2ed_code_data/NeWR2-Data/Doubs.RData)             |\n:::\n\n::: {.callout-important appearance=\"simple\"}\n## Tasks to Complete in This Chapter\n\n* [Task E 1--4](tasks/Task_E.qmd)\n:::\n\nCorrespondence Analysis (CA) is an eigenvector-based ordination method that handles non-linear species responses more effectively than Principal Component Analysis (PCA). PCA relies on linear relationships and maximises variance explained using a covariance or correlation matrix, but CA employs similar regression techniques based on $\\chi^2$-standardised data and weights. This makes it more appropriate for species count and presence/absence data.\n\n## Why Not Just Use PCA?\n\nThe PCA chapter worked cleanly because the Doubs environmental variables change along the river in a roughly linear way: elevation falls, discharge rises, and a straight arrow captures each trend. Species do not behave like that. A fish species thrives within a limited stretch of the river and is absent elsewhere, so its abundance climbs to a peak somewhere along the gradient and falls away on either side. This is a **unimodal** response, and it is the normal shape for species along environmental gradients (@fig-ca-responses).\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\ng <- seq(0, 100, length.out = 200)\n\nlinear_resp <- bind_rows(\n  tibble(grad = g, abund = pmax(0, 0.9 * g), species = \"Species 1\"),\n  tibble(grad = g, abund = pmax(0, 90 - 0.9 * g), species = \"Species 2\")\n)\n\ngauss <- function(opt, h = 100, w = 14) h * exp(-((g - opt)^2) / (2 * w^2))\noptima <- c(12, 32, 50, 68, 88)\nunimodal_resp <- bind_rows(lapply(seq_along(optima), function(i) {\n  tibble(grad = g, abund = gauss(optima[i]), species = paste(\"Species\", i))\n}))\n\npanel_lin <- ggplot(linear_resp, aes(grad, abund, colour = species)) +\n  geom_line(linewidth = 0.8) +\n  labs(\n    title = \"Linear responses (PCA assumes this)\",\n    x = \"Environmental gradient\",\n    y = \"Abundance\"\n  ) +\n  theme(legend.position = \"none\")\n\npanel_uni <- ggplot(unimodal_resp, aes(grad, abund, colour = species)) +\n  geom_line(linewidth = 0.8) +\n  labs(\n    title = \"Unimodal responses (CA accommodates this)\",\n    x = \"Environmental gradient\",\n    y = \"Abundance\"\n  ) +\n  theme(legend.position = \"none\")\n\nggarrange(panel_lin, panel_uni, ncol = 1, labels = \"AUTO\")\n```\n\n::: {.cell-output-display}\n![Two ways a species' abundance can change along an environmental gradient. **(A)** Linear responses, the shape PCA assumes: abundance rises or falls steadily. **(B)** Unimodal responses, the usual ecological shape: each species peaks at its own preferred position and is absent elsewhere. Different species replace one another along the gradient, so no straight line describes the whole community.](CA_files/figure-html/fig-ca-responses-1.svg){#fig-ca-responses}\n:::\n:::\n\n\nTwo consequences follow, and both answer the question a student naturally asks, namely *why not just run PCA on the species abundances?* First, PCA fits straight lines through humped data, and when species turn over along a long gradient it bends the ends of that gradient back on themselves, producing the horseshoe seen in the [PCA chapter](PCA.qmd#sec-horseshoe-effect). Second, species data are full of zeros: most species are absent from most sites. PCA treats two shared absences as evidence of similarity, so two species that never occur anywhere together can look alike simply because they are jointly absent. These shared absences are the *double zeros*, and they mislead Euclidean methods. CA is built to avoid both traps. The table sets the two methods side by side:\n\n| Feature | PCA | CA |\n| :--- | :--- | :--- |\n| Distance preserved | Euclidean | $\\chi^2$ |\n| Assumed species response | linear | unimodal |\n| Best suited to | environmental variables | species abundance |\n| Sensitivity to double zeros | high | low |\n\nCA maximises the correspondence between species scores and sample scores by preserving $\\chi^2$ distances between sites in a species-by-site matrix instead of Euclidean distances. The $\\chi^2$ distance metric is not influenced by [double zeros](https://www.davidzeleny.net/anadat-r/doku.php/en:similarity), making it suitable for situation when many species might be absent from several sites. The process involves performing a Singular Value Decomposition (SVD), or eigenvalue decomposition (two different approaches in linear algebra applied to the analysis of matrices) on the standardised data matrix, and reporting the eigenvalues and eigenvectors.\n\nIn CA ordination diagrams, species, and sites are presented as points within a reduced-dimensional space. Their relative positions encode the strength and structure of their associations. The distances between these points approximate the $\\chi^2$ distances calculated between the rows (sites) or columns (species) of the original contingency or abundance matrix, and preserve a measure of compositional dissimilarity that is sensitive to the distributional asymmetries characteristic of ecological data. The ordination thus provides a geometric framework for addressing inferential questions of the type: *Which sites have compositional affinities with particular species assemblages?*, or *Which species distributions align with which site characteristics?*\n\nThe species scores are derived as weighted averages of site scores or equivalently as linear combinations of the original species data. As such, they are constructed to maximise the dispersion of species configurations along successive ordination axes. So, they capture dominant gradients, and patterns of variation that may reflect underlying ecological processes. Whereas PCAs provide a linear mapping of species onto environmental gradients, CAs better approximate species’ nonlinear, often unimodal, or skewed, responses to latent environmental factors. Because of this nonlinear structure, species points in CA biplots are not represented as vectors radiating from the origin (as they are in PCA, where linear monotonic gradients predominate). Instead, CA are better suited to visualisations involving curved response surfaces, which indicate the fact that species’ occurrence, or abundance peaks at intermediate positions along gradients rather than increasing or decreasing uniformly across the ordination space.\n\nOne potential downside of CA is that it assumes the total abundance or presence of species across sites to be constant, which may not always hold true. Additionally, some ecologists argue that CA might be overly influenced by rare species, as their contributions to the $\\chi^2$ statistic can be disproportionately large. This issue can be mitigated by applying appropriate transformations or down-weighting rare species in the analysis. CA also produces an artefact of its own, the *arch effect*, which I meet once I have an ordination to look at (see [The Arch Effect](#sec-arch-effect), below).\n\nCA produces one axis fewer than the minimum of the number of sites (*n*) or the number of species (*p*). Like PCA, CA produces orthogonal axes ranked in decreasing order of importance. However, the variation represented is the total inertia, which is the sum of squares of all values in the $\\chi^2$ matrix, rather than the sum of eigenvalues along the diagonal as in PCA. Individual eigenvalues in CA can be greater than 1, indicating that the corresponding axis captures a significant portion of the total variance in the data.\n\nThe scaling of ordination plots in CA is similar to that in PCA. Scaling 1 (site scaling) means that sites close together in the plot have similar species relative frequencies, and any site near a species point will have a relatively large abundance of that species. Scaling 2 (species scaling) means that species points close together will have similar abundance patterns across sites, and any species close to a site point is more likely to have a high abundance at that site.\n\nAs with all ordination techniques, interpreting CA results should be done with caution, and in conjunction with additional ecological knowledge and statistical tests, as the ordination axes may not always have a clear ecological interpretation. Please supplement your reading by referring to [GUSTA ME](https://sites.google.com/site/mb3gustame/indirect-gradient-analysis/ca)) and David Zelený's writing on the topic in [Analysis of community ecology data in R](https://www.davidzeleny.net/anadat-r/doku.php/en:ca_dca).\n\n## Set-up the Analysis Environment\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(vegan)\nlibrary(viridis)\nlibrary(ggrepel) # for tidy biplot labels\nlibrary(ggpubr) # for arranging panels\n\n# Files will be referenced using here::here() for absolute paths\n```\n:::\n\n\n## The Doubs River Data\n\nIn the PCA chapter I analysed the environmental data. This time I work with the species data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nload(here::here(\n  \"data\",\n  \"BCB743\",\n  \"NEwR-2ed_code_data\",\n  \"NEwR2-Data\",\n  \"Doubs.RData\"\n))\nhead(spe, 8)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Cogo Satr Phph Babl Thth Teso Chna Pato Lele Sqce Baba Albi Gogo Eslu Pefl\n1    0    3    0    0    0    0    0    0    0    0    0    0    0    0    0\n2    0    5    4    3    0    0    0    0    0    0    0    0    0    0    0\n3    0    5    5    5    0    0    0    0    0    0    0    0    0    1    0\n4    0    4    5    5    0    0    0    0    0    1    0    0    1    2    2\n5    0    2    3    2    0    0    0    0    5    2    0    0    2    4    4\n6    0    3    4    5    0    0    0    0    1    2    0    0    1    1    1\n7    0    5    4    5    0    0    0    0    1    1    0    0    0    0    0\n8    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0\n  Rham Legi Scer Cyca Titi Abbr Icme Gyce Ruru Blbj Alal Anan\n1    0    0    0    0    0    0    0    0    0    0    0    0\n2    0    0    0    0    0    0    0    0    0    0    0    0\n3    0    0    0    0    0    0    0    0    0    0    0    0\n4    0    0    0    0    1    0    0    0    0    0    0    0\n5    0    0    2    0    3    0    0    0    5    0    0    0\n6    0    0    0    0    2    0    0    0    1    0    0    0\n7    0    0    0    0    0    0    0    0    0    0    0    0\n8    0    0    0    0    0    0    0    0    0    0    0    0\n```\n\n\n:::\n:::\n\n\n## Do the CA\n\nThe **vegan** function `cca()` can be used for CA and Constrained Correspondence Analysis (CCA). When I do not specify constraints, as I do here, I will do a simple CA:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspe_ca <- cca(spe)\n```\n\n::: {.cell-output .cell-output-error}\n\n```\nError in `cca.default()`:\n! all row sums must be >0 in the community data matrix\n```\n\n\n:::\n:::\n\n\nOkay, so there is a problem. The error message says that at least one of the rows sums to 0. Which one?\n\n\n::: {.cell}\n\n```{.r .cell-code}\napply(spe, 1, sum)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 \n 3 12 16 21 34 21 16  0 14 14 11 18 19 28 33 40 44 42 46 56 62 72  4 15 11 43 \n27 28 29 30 \n63 70 87 89 \n```\n\n\n:::\n:::\n\n\nI see that the offending row is row 8, so I can omit it. This function will omit any row that sums to zero (or less):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspe <- spe[rowSums(spe) > 0, ]\nhead(spe, 8)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Cogo Satr Phph Babl Thth Teso Chna Pato Lele Sqce Baba Albi Gogo Eslu Pefl\n1    0    3    0    0    0    0    0    0    0    0    0    0    0    0    0\n2    0    5    4    3    0    0    0    0    0    0    0    0    0    0    0\n3    0    5    5    5    0    0    0    0    0    0    0    0    0    1    0\n4    0    4    5    5    0    0    0    0    0    1    0    0    1    2    2\n5    0    2    3    2    0    0    0    0    5    2    0    0    2    4    4\n6    0    3    4    5    0    0    0    0    1    2    0    0    1    1    1\n7    0    5    4    5    0    0    0    0    1    1    0    0    0    0    0\n9    0    0    1    3    0    0    0    0    0    5    0    0    0    0    0\n  Rham Legi Scer Cyca Titi Abbr Icme Gyce Ruru Blbj Alal Anan\n1    0    0    0    0    0    0    0    0    0    0    0    0\n2    0    0    0    0    0    0    0    0    0    0    0    0\n3    0    0    0    0    0    0    0    0    0    0    0    0\n4    0    0    0    0    1    0    0    0    0    0    0    0\n5    0    0    2    0    3    0    0    0    5    0    0    0\n6    0    0    0    0    2    0    0    0    1    0    0    0\n7    0    0    0    0    0    0    0    0    0    0    0    0\n9    0    0    0    0    1    0    0    0    4    0    0    0\n```\n\n\n:::\n:::\n\n\nNow I am ready for the CA:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspe_ca <- cca(spe)\nspe_ca\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall: cca(X = spe)\n\n              Inertia Rank\nTotal           1.167     \nUnconstrained   1.167   26\n\nInertia is scaled Chi-square\n\nEigenvalues for unconstrained axes:\n   CA1    CA2    CA3    CA4    CA5    CA6    CA7    CA8 \n0.6010 0.1444 0.1073 0.0834 0.0516 0.0418 0.0339 0.0288 \n(Showing 8 of 26 unconstrained eigenvalues)\n```\n\n\n:::\n:::\n\n\nThe more verbose `summary()` output:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(spe_ca)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\ncca(X = spe) \n\nPartitioning of scaled Chi-square:\n              Inertia Proportion\nTotal           1.167          1\nUnconstrained   1.167          1\n\nEigenvalues, and their contribution to the scaled Chi-square \n\nImportance of components:\n                        CA1    CA2     CA3     CA4     CA5     CA6     CA7\nEigenvalue            0.601 0.1444 0.10729 0.08337 0.05158 0.04185 0.03389\nProportion Explained  0.515 0.1237 0.09195 0.07145 0.04420 0.03586 0.02904\nCumulative Proportion 0.515 0.6387 0.73069 0.80214 0.84634 0.88220 0.91124\n                          CA8     CA9     CA10     CA11     CA12     CA13\nEigenvalue            0.02883 0.01684 0.010826 0.010142 0.007886 0.006123\nProportion Explained  0.02470 0.01443 0.009278 0.008691 0.006758 0.005247\nCumulative Proportion 0.93594 0.95038 0.959655 0.968346 0.975104 0.980351\n                          CA14     CA15     CA16     CA17     CA18     CA19\nEigenvalue            0.004867 0.004606 0.003844 0.003067 0.001823 0.001642\nProportion Explained  0.004171 0.003948 0.003294 0.002629 0.001562 0.001407\nCumulative Proportion 0.984522 0.988470 0.991764 0.994393 0.995955 0.997362\n                          CA20      CA21      CA22      CA23      CA24\nEigenvalue            0.001295 0.0008775 0.0004217 0.0002149 0.0001528\nProportion Explained  0.001110 0.0007520 0.0003614 0.0001841 0.0001309\nCumulative Proportion 0.998472 0.9992238 0.9995852 0.9997693 0.9999002\n                           CA25      CA26\nEigenvalue            8.949e-05 2.695e-05\nProportion Explained  7.669e-05 2.310e-05\nCumulative Proportion 1.000e+00 1.000e+00\n```\n\n\n:::\n:::\n\n\nThe output looks similar to that of a PCA. The important things to note are the **inertia** (unconstrained and total inertia are the same), the **Eigenvalues for the unconstrained axes**, the **Species scores,**, and the **Site scores**. Their interpretation is the same as before, but I can reiterate. Let me calculate the total inertia:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nround(sum(spe_ca$CA$eig), 5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.16691\n```\n\n\n:::\n:::\n\n\n::: {.callout-note appearance=\"simple\"}\n## Variance, Inertia, Eigenvalue\n\nThese three terms name the same underlying idea at different stages, and they are easy to confuse:\n\n| Term            | What it measures here |\n| :--- | :--- |\n| Variance (PCA)  | spread among environmental measurements |\n| Inertia (CA)    | spread in species composition among sites |\n| Eigenvalue      | the amount of that spread held by a single axis |\n\nIn CA, **inertia measures the overall heterogeneity of species composition**. A river whose fish community turns over completely from source to mouth has high inertia; one with the same few species at every site has low inertia. The total inertia here (about 1.17) is that whole heterogeneity, and the eigenvalue of CA1 is the share of it the first axis accounts for.\n:::\n\nThe inertia for the first axis (CA1) is:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nround(spe_ca$CA$eig[1], 5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    CA1 \n0.60099 \n```\n\n\n:::\n:::\n\n\nThe inertia of CA1 *and* CA2 is:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nround(sum(spe_ca$CA$eig[1:2]), 5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.74536\n```\n\n\n:::\n:::\n\n\nThe fraction of the variance explained by CA1 and CA2 is:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nround(sum(spe_ca$CA$eig[1:2]) / sum(spe_ca$CA$eig) * 100, 2) # result in %\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 63.87\n```\n\n\n:::\n:::\n\n\nAbove, the value is the same one as in **Cumulative Proportion** in the `summary(spe_ca)` output under the CA2 column.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# make a scree plot using the vegan function:\nscreeplot(spe_ca, bstick = TRUE, type = \"lines\")\n```\n\n::: {.cell-output-display}\n![Scree plot of the Doubs River fish species CA.](CA_files/figure-html/fig-ca-screeplot-1.svg){#fig-ca-screeplot fig-align='center'}\n:::\n:::\n\n\nThe scree plot (@fig-ca-screeplot) shows the eigenvalues of the CA axes which helps me decide how many axes to retain in the analysis. In this case, I will retain the first two axes, as they explain the most variance in the data.\n\nSpecies scores are *actual* species scores now, as they relate to the species data (in the PCA the environmental variables were in the columns, so the species scores there referred to the environment). A species with a large positive or large negative score on an axis is the one most strongly **associated with that end of the axis**, namely the part of the gradient where it peaks. This is not the same as being the most abundant or the most important species overall, and reading a large score as \"dominance\" is a common error. For example, CA1 carries Satr and Cogo at one extreme (scores of about 1.66 and 1.50), the brown trout and bullhead of the cool upper river; lowland species such as Abbr and Blbj sit at the other extreme. A large score therefore tells me where a species sits along the gradient, not how dominant it is.\n\nSite scores are also as seen earlier in PCA. The highest positive or negative loadings indicate sites that are dispersed far apart on the biplot (in ordination space). They will have large differences in fish community composition.\n\nPlease see *Numerical Ecology with R* (pp. 133 to 140). There you will find explanations for how to interpret the ordinations and the ordination diagrams shown below.\n\n## Ordination Diagrams\n\nThe biplots for the above ordination are given in @fig-ca-biplots.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nopar <- par(no.readonly = TRUE)\npar(mfrow = c(1, 2))\nplot(spe_ca, scaling = 1, main = \"CA fish abundances - biplot scaling 1\")\nplot(spe_ca, scaling = 2, main = \"CA fish abundances - biplot scaling 2\")\npar(opar)\n```\n\n::: {.cell-output-display}\n![CA ordination plot of the Doubs River species data showing site scaling (left) and species scaling (right).](CA_files/figure-html/fig-ca-biplots-1.svg){#fig-ca-biplots fig-align='center'}\n:::\n:::\n\n\n**Scaling 1:** This is site scaling, which *emphasises relationships between rows* accurately in low-dimensional ordination space. Distances among objects (samples, or sites) in the biplot are approximations of their $\\chi^{2}$ distances in multidimensional space. Objects found near a point representing a species are likely to contain a high contribution of that species. *Site scaling means that sites close together in the plot have similar species relative frequencies, and any site near a species point will have a relatively large abundance of that species.*\n\n**Scaling 2:** Species scaling. This *emphasises relationships between columns* accurately in low-dimensional ordination space. Distances among objects (samples or sites) in the biplot are not approximations of their $\\chi^{2}$ distances in multidimensional space, but the distances among species are. *Species scaling means that species points close together will have similar abundance patterns across sites, and any species close to a site point is more likely to have a high abundance at that site.*\n\n### How to Read This CA\n\nThe base **vegan** plots are dense, so @fig-ca-interp redraws the same ordination with the sites coloured by their position along the river and the most distinctive species labelled. Reading it is the point of the whole analysis.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nca_pct <- round(100 * spe_ca$CA$eig / sum(spe_ca$CA$eig), 1)\n\nca_sites <- as.data.frame(scores(spe_ca, display = \"sites\", choices = 1:2))\nca_sites$site <- as.integer(rownames(ca_sites))\nca_spp <- as.data.frame(scores(spe_ca, display = \"species\", choices = 1:2))\nca_spp$lab <- rownames(ca_spp)\nca_spp$d <- sqrt(ca_spp$CA1^2 + ca_spp$CA2^2)\nca_lab <- ca_spp[ca_spp$d > quantile(ca_spp$d, 0.45), ] # label the outer species\n\nggplot(ca_sites, aes(CA1, CA2)) +\n  geom_hline(yintercept = 0, colour = \"grey85\") +\n  geom_vline(xintercept = 0, colour = \"grey85\") +\n  annotate(\"point\", x = 0, y = 0, shape = 3, size = 3, colour = \"black\") +\n  annotate(\n    \"text\",\n    x = 0.18,\n    y = 0.16,\n    label = \"centroid\",\n    size = 2.6,\n    hjust = 0\n  ) +\n  geom_point(aes(colour = site), size = 2) +\n  scale_colour_viridis_c(name = \"Site\\n(1 = source)\") +\n  geom_point(\n    data = ca_spp,\n    aes(CA1, CA2),\n    colour = \"seagreen4\",\n    shape = 3,\n    size = 0.8\n  ) +\n  geom_text_repel(\n    data = ca_lab,\n    aes(CA1, CA2, label = lab),\n    colour = \"seagreen4\",\n    size = 2.5,\n    max.overlaps = Inf,\n    segment.colour = \"grey80\"\n  ) +\n  annotate(\n    \"segment\",\n    x = 2.4,\n    y = -1.75,\n    xend = -0.9,\n    yend = -1.75,\n    arrow = arrow(length = unit(2.5, \"mm\")),\n    colour = \"firebrick\"\n  ) +\n  annotate(\n    \"text\",\n    x = 0.75,\n    y = -2.0,\n    label = \"upstream to downstream (CA1)\",\n    colour = \"firebrick\",\n    size = 2.7\n  ) +\n  labs(\n    x = paste0(\"CA1 (\", ca_pct[1], \"%)\"),\n    y = paste0(\"CA2 (\", ca_pct[2], \"%)\")\n  ) +\n  coord_equal()\n```\n\n::: {.cell-output-display}\n![An annotated CA of the Doubs fish data. Points are sites, coloured from the source (dark) to the mouth (yellow). Green crosses are species, labelled where they sit away from the crowded centre. The black cross marks the centroid (the average composition). CA1 orders sites along the river, as the arrow shows.](CA_files/figure-html/fig-ca-interp-1.svg){#fig-ca-interp}\n:::\n:::\n\n\nThe ordination tells a clear ecological story:\n\n- **CA1 carries 51.5% of the inertia**, far more than any other axis, so it is the dominant pattern.\n- **The sites line up along CA1 in river order.** Source sites sit at one end and mouth sites at the other, so CA1 recovers the upstream-to-downstream sequence from species composition alone.\n- **The species split into two faunas.** The cool upper river holds brown trout (`Satr`), grayling (`Thth`), bullhead (`Cogo`), and minnow (`Phph`); the warmer lower river holds bream (`Abbr`), silver bream (`Blbj`), ruffe (`Gyce`), and eel (`Anan`). A site's colour predicts which group it carries.\n- **CA1 is therefore the primary river gradient**, the same upstream-to-downstream gradient that the [PCA of the environmental data](PCA.qmd) recovered, now read through the fish rather than the measurements. The `envfit` arrows added below confirm it: elevation and oxygen point towards the trout end, distance from source and discharge towards the lowland end.\n- **CA2 (12.4%) is a weaker, harder-to-read contrast.** As the arch discussion below shows, much of it is a geometric by-product of the strong first axis rather than a separate ecological gradient.\n\nBelow I provide biplots with site and species scores for four selected species (@fig-ca-ordisurf2). The point size of the site scores scales with species scores: the larger the point, the greater the species score. Here, the species score is seen as a centre of abundance; it represents the species' maximum abundance, which decreases in every direction from the centroid. The plots are augmented with response surfaces created using the `ordisurf()` function. This function fits models to predict the abundance of the species *Salmo trutta fario* (Brown Trout), *Scardinius erythrophthalmus* (Rudd), *Telestes souffia* (Souffia, or Western Vairone), and *Cottus gobio* (Bullhead) using a Generalised Additive Model (GAM) of the Correspondence Analysis (CA) site scores on axes 1, and 2 as the predictor variables. The response surfaces illustrate where the species are most abundant and the direction of their response.\n\nAdditionally, I used the `envfit()` function to project biplot arrows for the continuous environmental variables into the ordination space. Each arrow points in the direction of the maximum increase of the variable. The length of the arrow is proportional to the correlation between the variable and the ordination axes. The significance of the correlation is tested by permutation, with significant vectors shown in red. The environmental variables are the same as those used in the PCA.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npalette(viridis(8))\nopar <- par(no.readonly = TRUE)\npar(mar = c(4, 4, 0.9, 0.5) + .1, mfrow = c(2, 2))\n\ninvisible(ordisurf(\n  spe_ca ~ Satr,\n  data = spe,\n  bubble = 3,\n  family = quasipoisson,\n  knots = 2,\n  col = 6,\n  display = \"sites\",\n  main = \"Salmo trutta fario\"\n))\nabline(h = 0, v = 0, lty = 3)\n\ninvisible(ordisurf(\n  spe_ca ~ Scer,\n  data = spe,\n  bubble = 3,\n  family = quasipoisson,\n  knots = 2,\n  col = 6,\n  display = \"sites\",\n  main = \"Scardinius erythrophthalmus\"\n))\nabline(h = 0, v = 0, lty = 3)\n\ninvisible(ordisurf(\n  spe_ca ~ Teso,\n  data = spe,\n  bubble = 3,\n  family = quasipoisson,\n  knots = 2,\n  col = 6,\n  display = \"sites\",\n  main = \"Telestes souffia\"\n))\nabline(h = 0, v = 0, lty = 3)\n\ninvisible(ordisurf(\n  spe_ca ~ Cogo,\n  data = spe,\n  bubble = 3,\n  family = quasipoisson,\n  knots = 2,\n  col = 6,\n  display = \"sites\",\n  main = \"Cottus gobio\"\n))\nabline(h = 0, v = 0, lty = 3)\n\nenv <- env[-8, ] # because we removed the eighth site in the spp data\n\n# A posteriori projection of environmental variables in a CA\n# The last plot produced (CA scaling 2) must be active\nspe_ca_env <- envfit(spe_ca, env, scaling = 2) # Scaling 2 is default\nplot(spe_ca_env)\n\n# Plot significant variables with a different colour\nplot(spe_ca_env, p.max = 0.05, col = \"red\")\npar(opar)\n```\n\n::: {.cell-output-display}\n![CA ordination plots with species response surfaces of the Doubs River species data emphasising four species of fish: A) Satr, B) Scer, C) Teso, and D) Cogo. D) additionally has the environmental vectors projected on the plot, with the significant vectors shown in red.](CA_files/figure-html/fig-ca-ordisurf2-1.svg){#fig-ca-ordisurf2 fig-align='center'}\n:::\n:::\n\n\nThe species response surfaces in @fig-ca-ordisurf2 show the change of species abundance across the ordination space and the vectors indicate how the species distribution and abundance relate to the predominant environmental gradients. Seen in this way, it quickly becomes evident that the biplot is a simplification of [coenospaces](../BDC334/Lec-03-gradients.qmd).\n\n## The Arch Effect {#sec-arch-effect}\n\nWith an ordination in front of me, the arch effect is easy to see. @fig-ca-arch redraws the site scores and joins the sites in river order, from the source (site 1) to the mouth. The sites do not fall on a straight line along CA1. They bow into an arch, rising on CA2 in the middle of the river and falling again towards each end.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\narch_sites <- as.data.frame(scores(spe_ca, display = \"sites\", choices = 1:2))\narch_sites$site <- as.integer(rownames(arch_sites))\narch_pct <- round(100 * spe_ca$CA$eig / sum(spe_ca$CA$eig), 1)\n\nggplot(arch_sites[order(arch_sites$site), ], aes(CA1, CA2)) +\n  geom_hline(yintercept = 0, colour = \"grey85\") +\n  geom_vline(xintercept = 0, colour = \"grey85\") +\n  geom_path(colour = \"grey70\", linewidth = 0.4) +\n  geom_point(aes(colour = site), size = 2.4) +\n  scale_colour_viridis_c(name = \"Site\\n(1 = source)\") +\n  geom_text(aes(label = site), size = 2, vjust = -0.8) +\n  labs(\n    x = paste0(\"CA1 (\", arch_pct[1], \"%)\"),\n    y = paste0(\"CA2 (\", arch_pct[2], \"%)\")\n  ) +\n  coord_equal()\n```\n\n::: {.cell-output-display}\n![The arch effect. The Doubs sites, joined in order from source to mouth, do not lie on a straight line along CA1 but bend into an arch. CA2 here is largely a geometric by-product of the strong first axis, not a separate ecological gradient.](CA_files/figure-html/fig-ca-arch-1.svg){#fig-ca-arch}\n:::\n:::\n\n\nThe arch is a mathematical artefact, not an ecological pattern. Once CA1 has captured the strong source-to-mouth gradient, the requirement that CA2 be uncorrelated with it forces the mid-river sites, which are average on CA1, to take extreme values on CA2. The second axis therefore curves the gradient back on itself rather than describing a genuine second gradient. This is the CA counterpart of the [horseshoe effect in PCA](PCA.qmd#sec-horseshoe-effect), and it is the milder of the two: the sites keep their correct order along CA1, so the primary gradient is still read correctly, but CA2 should not be interpreted as a second ecological axis.\n\nThe arch can be straightened with a [Detrended Correspondence Analysis (DCA)](DCA.qmd), a variant of CA that removes the trend from the later axes. The next chapter takes that up.\n\n## References\n\n::: {#refs}\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}