{
  "hash": "dd3ca219e58d317bcaef52c46ae1a535",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"14. Multiple Regression and Model Specification\"\nsubtitle: \"From Biological Hypotheses to Statistical Models\"\ndate: last-modified\ndate-format: \"YYYY/MM/DD\"\nreference-location: margin\n---\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n::: {.callout-note appearance=\"simple\"}\n## In This Chapter\n\n-   why simple regression is often insufficient for biological questions with multiple drivers;\n-   how multiple regression models a response using several predictors simultaneously;\n-   why model specification is part of the scientific argument, not just a modelling choice;\n-   how to distinguish model specification from model selection;\n-   how to detect and respond to multicollinearity using the variance inflation factor;\n-   how to read the coefficient table and the ANOVA table, and when each is appropriate;\n-   how dummy-variable coding handles categorical predictors within the linear model;\n-   how ANCOVA relates to multiple regression;\n-   how to fit, diagnose, and report a worked multiple regression example using seaweed biogeographic data.\n:::\n\n::: {.callout-important appearance=\"simple\"}\n## Tasks to Complete in This Chapter\n\n-   None\n:::\n\n# Introduction\n\nI modelled the relationship between two variables in [Chapter 12](12-simple-linear-regression.qmd). Biological systems are rarely that simple. Growth, abundance, species diversity, and dissimilarity in community composition are each driven by several environmental and biological factors acting simultaneously. Multiple linear regression is obvious progression from simple regression to more realistic applications, since it models a continuous response as a linear function of two or more predictors.\n\nAdding predictors creates a more demanding scientific problem alongside the statistical one. Which predictors belong in the model, and why? What does each coefficient mean once others are present? So, I treat multiple regression and model specification together in this chapter, because separating them encourages data-driven assembly of predictors that produces unreliable models. I would rather place emphasis on biology and encourage theory-driven insights as the prime motivation of the model's construction.\n\nThe worked examples use seaweed biogeographic data from @smit2017seaweeds. The dataset reappears in several places in BCB744 and is well suited here because it contains a continuous response, continuous climate predictors, and a categorical regional predictor.\n\n# Key Concepts\n\n-   **Multiple regression** models a response using several predictors simultaneously. Each fitted coefficient is a partial effect; this is, the expected change in the response for a one-unit increase in that predictor when all other predictors are held constant.\n-   **Model specification** is the process of capturing the biological reasoning into a statistical formula. Specifying a model means deciding which variables belong, what functional forms they should take, and whether any interactions are needed.\n-   **Model selection** is the process of choosing among competing specified models. It follows specification; it does not replace it.\n-   **Multicollinearity** arises when predictors are strongly intercorrelated. It inflates coefficient standard errors and makes partial effects difficult to interpret.\n-   **Categorical predictors** enter the linear model through dummy-variable coding. Numerically, this is no different from including a continuous predictor, but the interpretation changes.\n-   **ANCOVA** combines a factor and a continuous covariate in one additive linear model. It is not a separate procedure; it is a special case of multiple regression.\n\n# Model Specification vs Model Selection\n\nWhen model building and fitting are approached as a single activity, the workflow isn't optimal and it might result in a sub-optimal outcome. Keep the two processes apart:\n\n**Model specification** happens before fitting. It means deciding, on biological grounds, which variables could plausibly affect the response, what functional form each relationship might take, and whether any predictors should interact. A good specification reflects the scientific hypothesis, but a poor one produces coefficients that are numerically valid but biologically uninterpretable.\n\n**Model selection** happens only *after* a plausible set of models has been specified. It asks which of the candidate models is best supported by the data, using criteria such as AIC or nested model comparison. Therefore, selection only makes sense within a well-specified candidate set of models. If the specification is weak, for example because predictors are chosen by convenience rather than theory, selection will just identify the least bad option from a set that may not contain the right model at all.\n\nThe practical consequence is that the first question in any multiple regression analysis is not \"which variables reduce AIC?\" but \"which variables represent the hypothesised process, and which are potential confounders?\". Model selection tools such as stepwise algorithms or AIC comparison are used in [Example 1](#example-1-a-climate-model-for-the-east-coast-transition-zone) below, but they are applied within a candidate set that was motivated biologically, not assembled arbitrarily.\n\nThe broader problems of omitted variables, confounding, and measurement error are treated in [Chapter 16](16-collinearity-confounding-measurement-error.qmd).\n\n# Nature of the Data\n\n## Requirements Before Fitting\n\n-   **Response variable:** The response should be continuous and measured without systematic error.\n-   **Predictors:** Predictors may be continuous or categorical. They should represent variables that could plausibly affect the response, not just variables that happen to be available.\n-   **Independence:** Observations must be independent. Spatial autocorrelation, repeated measurements on the same individual, or clustered sampling structures each require approaches beyond the standard multiple regression presented here.\n-   **Approximate linearity:** The response should relate approximately linearly to each continuous predictor on the scale used in the model. Scatterplots of the response against each predictor individually are the first check.\n\n## Assumptions After Fitting\n\nThe residual assumptions in multiple regression are the same as in simple regression, and are also applied to the fitted multiple-predictor model.\n\n-   **Normality:** Residuals should be approximately normally distributed. A Q-Q plot of the residuals is the standard check.\n-   **Constant variance:** Residual variance should not trend with fitted values. A residuals-vs-fitted plot is the standard check.\n-   **No severe multicollinearity:** Predictors should not be so strongly intercorrelated that their partial coefficients become imprecise or uninterpretable. The variance inflation factor quantifies this.\n\nEven when residual assumptions are satisfied, the model can still be scientifically weak if the variables are chosen without biological justification. Statistical adequacy and scientific defensibility are separate criteria and both are indespensible to model building.\n\n# The Core Equation\n\nThe multiple regression model is:\n\n$$Y_i = \\alpha + \\beta_1 X_{1i} + \\beta_2 X_{2i} + \\cdots + \\beta_p X_{pi} + \\epsilon_i$$ {#eq-mlr}\n\nEach $\\beta_j$ in @eq-mlr is a partial slope: the expected change in $Y$ for a one-unit increase in $X_j$ while all other predictors remain constant. This conditional interpretation distinguishes multiple regression from a set of simple regressions run independently, and this is also where misinterpretation most commonly occurs.\n\nA partial coefficient is not a causal effect. It is an adjusted association. If an important driver of the response is omitted from the model and that omitted variable correlates with an included predictor, the included predictor's coefficient will absorb part of the omitted variable's effect. The coefficient then reflects a mixture of the predictor's own relationship with the response and the confounding from the omitted variable. This is the distinction between *collinearity* (which is a property of the included predictors) and *confounding*, which involves a predictor that should have been included but was not. [Chapter 16](16-collinearity-confounding-measurement-error.qmd) delves into both problems in more detail.\n\n# Outliers\n\nUnusual observations can affect coefficient estimates and standard errors in multiple regression as they do in simple regression. The added difficulty is that an observation can be outlying in multivariate predictor space without appearing extreme on any single variable alone. Residuals versus leverage plots and Cook's distance are therefore more informative diagnostics in multiple regression than they would be in a simple regression. Both are produced by the standard diagnostic plotting functions used in the examples below.\n\n# R Function\n\nThe `lm()` function fits a multiple regression model in the same way it fits a simple regression model, extended to include several terms in the formula.\n\nFor a model with only continuous predictors:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm(response ~ predictor1 + predictor2 + predictor3,\n   data = dataset)\n```\n:::\n\n\nInteraction effects between two predictors:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm(response ~ predictor1 * predictor2, data = dataset)\n```\n:::\n\n\nThis expands to `predictor1 + predictor2 + predictor1:predictor2`. The main effects are always included when an interaction is specified this way.\n\nWhen the model contains both continuous and categorical predictors, the formula is extended accordingly:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm(response ~ continuous_predictor1 + continuous_predictor2 +\n     factor(categorical_predictor),\n   data = dataset)\n```\n:::\n\n\nR handles dummy-variable coding of factors automatically. This is one reason multiple regression and ANOVA belong to the same linear-model family.\n\n# Example 1: A Climate Model for the East Coast Transition Zone {#example-1-a-climate-model-for-the-east-coast-transition-zone}\n\nThe seaweed dataset from @smit2017seaweeds contains:\n\n-   `Y` — mean Sørensen dissimilarity between adjacent seaweed assemblages along the South African coast;\n-   several continuous climatological predictors derived from sea-surface temperature records;\n-   `bio` — a categorical bioregional classification.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsw <- read.csv(\"../../data/BCB743/seaweed/spp_df2.csv\")\nrbind(head(sw, 3), tail(sw, 3))[,-1]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       dist  bio    augMean   febRange      febSD     augSD    annMean\n1     0.000  BMP 0.00000000 0.00000000 0.00000000 0.0000000 0.00000000\n2    51.138  BMP 0.05741369 0.09884404 0.16295271 0.3132800 0.01501846\n3   104.443  BMP 0.15043904 0.34887754 0.09934163 0.4188239 0.02602247\n968 102.649 ECTZ 0.41496099 0.11330069 0.24304493 0.7538546 0.52278161\n969  49.912 ECTZ 0.17194242 0.05756093 0.18196664 0.3604341 0.24445006\n970   0.000 ECTZ 0.00000000 0.00000000 0.00000000 0.0000000 0.00000000\n              Y        Y1          Y2\n1   0.000000000 0.0000000 0.000000000\n2   0.003610108 0.0000000 0.003610108\n3   0.003610108 0.0000000 0.003610108\n968 0.198728140 0.1948882 0.003839961\n969 0.069337442 0.0443038 0.025033645\n970 0.000000000 0.0000000 0.000000000\n```\n\n\n:::\n:::\n\n\nI begin with the East Coast Transition Zone (`ECTZ`) and ask which combination of climate variables best explains variation in `Y`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsw_ectz <- sw |>\n  filter(bio == \"ECTZ\")\n\nsw_sub1 <- sw_ectz[, c(\"Y\", \"augMean\", \"febRange\", \"febSD\", \"augSD\", \"annMean\")]\n```\n:::\n\n\n## Exploratory Data Analysis\n\nBefore fitting any model, I summarise the candidate variables and examine each predictor against the response.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(sw_sub1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       Y              augMean          febRange          febSD       \n Min.   :0.00000   Min.   :0.0000   Min.   :0.0000   Min.   :0.0000  \n 1st Qu.:0.09615   1st Qu.:0.1817   1st Qu.:0.1866   1st Qu.:0.1820  \n Median :0.22779   Median :0.4686   Median :0.7531   Median :0.6256  \n Mean   :0.24393   Mean   :0.5313   Mean   :0.8329   Mean   :0.7209  \n 3rd Qu.:0.35690   3rd Qu.:0.7927   3rd Qu.:1.3896   3rd Qu.:1.2072  \n Max.   :0.63754   Max.   :1.7508   Max.   :2.2704   Max.   :2.1249  \n     augSD           annMean      \n Min.   :0.0000   Min.   :0.0000  \n 1st Qu.:0.4178   1st Qu.:0.1874  \n Median :1.0454   Median :0.5228  \n Mean   :1.3207   Mean   :0.5722  \n 3rd Qu.:2.0924   3rd Qu.:0.8085  \n Max.   :4.5267   Max.   :1.8941  \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredictors <- c(\"augMean\", \"febRange\", \"febSD\", \"augSD\", \"annMean\")\n\nmodels <- map(predictors, ~ lm(as.formula(paste(\"Y ~\", .x)),\n                               data = sw_ectz))\n\nplts1 <- map(predictors, function(predictor) {\n  ggplot(sw_ectz, aes(x = .data[[predictor]], y = Y)) +\n    geom_point(shape = 1, colour = \"dodgerblue4\") +\n    geom_smooth(method = \"lm\", col = \"magenta\", fill = \"pink\") +\n    labs(title = paste(\"Y vs\", predictor),\n         x = predictor,\n         y = \"Y\") +\n    theme_grey()\n})\n\nggpubr::ggarrange(plotlist = plts1, ncol = 2,\n                  nrow = 3, labels = \"AUTO\")\n```\n\n::: {.cell-output-display}\n![Simple linear regressions fitted separately for five candidate climate predictors against mean Sørensen dissimilarity (`Y`) in the East Coast Transition Zone.](14-multiple-regression-and-model-specification_files/figure-pdf/fig-seaweed-slr-1.pdf){#fig-seaweed-slr fig-pos='H'}\n:::\n:::\n\n\n@fig-seaweed-slr shows that each predictor relates approximately linearly and positively to `Y` when examined alone. To make the strength of each marginal relationship precise, I extract the slope, its standard error, the coefficient of determination, and the overall model *p*-value from each fitted model and assemble them into @tbl-slr-fits.\n\n\n::: {#tbl-slr-fits .cell tbl-cap='Summary statistics for the five simple linear regressions of mean Sørensen dissimilarity (`Y`) against individual climate predictors in the East Coast Transition Zone. Slope and SE are the partial coefficient and its standard error. *R*² is the coefficient of determination; *p* is the overall model *p*-value from the *F*-test against the intercept-only null.'}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show code\"}\nfmt_pval <- function(p) {\n  case_when(\n    p < 0.001 ~ \"< 0.001\",\n    p < 0.01  ~ paste0(\"= \", formatC(p, digits = 3, format = \"f\")),\n    p < 0.05  ~ paste0(\"= \", formatC(p, digits = 3, format = \"f\")),\n    TRUE      ~ paste0(\"= \", formatC(p, digits = 3, format = \"f\"))\n  )\n}\n\nslr_table <- map2_dfr(predictors, models, function(pred, mod) {\n  tidy_mod   <- tidy(mod)\n  glance_mod <- glance(mod)\n  tibble(\n    Predictor = pred,\n    Slope     = tidy_mod$estimate[2],\n    SE        = tidy_mod$std.error[2],\n    `R²`      = glance_mod$r.squared,\n    `F`       = glance_mod$statistic,\n    `p`       = fmt_pval(glance_mod$p.value)\n  )\n})\n\nslr_table |>\n  gt() |>\n  fmt_number(columns = c(Slope, SE, `R²`), decimals = 3) |>\n  fmt_number(columns = `F`, decimals = 2)\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}lrrrrl}\n\\toprule\nPredictor & Slope & SE & R² & F & p \\\\ \n\\midrule\\addlinespace[2.5pt]\naugMean & 0.346 & 0.011 & 0.778 & 1,007.94 & < 0.001 \\\\ \nfebRange & 0.182 & 0.009 & 0.592 & 416.38 & < 0.001 \\\\ \nfebSD & 0.172 & 0.012 & 0.398 & 190.12 & < 0.001 \\\\ \naugSD & 0.088 & 0.007 & 0.342 & 149.13 & < 0.001 \\\\ \nannMean & 0.332 & 0.009 & 0.837 & 1,468.83 & < 0.001 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n\nAll five predictors are individually significant at $\\alpha = 0.05$, and each accounts for a substantial proportion of the variance in `Y` when fitted alone. These simple regressions are not checked for distributional assumptions; residual normality and homoscedasticity will be assessed properly on the final, correctly specified model. Checking assumptions on exploratory marginal fits would be premature: the residuals from a single-predictor model still contain all the variance that the remaining predictors explain, so any assumption violations diagnosed here may simply reflect omitted predictors rather than genuine model failure. The relevant question at this stage is whether each predictor is plausibly related to the response and approximately linear in that relationship; @fig-seaweed-slr and @tbl-slr-fits together confirm that both conditions are met.\n\nThese one-predictor views do not show how the predictors behave when considered together. In particular, they give no indication of how much the predictors overlap with each other.\n\n## Hypotheses\n\nThe null hypothesis for the overall model is that none of the entered climatological variables explains variation in `Y`:\n\n$$H_{0}: \\beta_1 = \\beta_2 = \\beta_3 = \\beta_4 = \\beta_5 = 0$$\n\nThe alternative is that at least one coefficient differs from zero:\n\n$$H_{a}: \\exists \\, \\beta_i \\ne 0 \\text{ for at least one } i$$\n\nAt the coefficient level, each predictor has its own hypothesis:\n\n$$H_{0}: \\beta_i = 0 \\quad H_{a}: \\beta_i \\ne 0$$\n\nThese individual tests must be read as partial tests: each evaluates the contribution of that predictor given the others in the model.\n\n## Fit the Initial Model\n\nI fit a full model containing all five climate predictors and a null model containing only the intercept.\n\nThe **null model** (`lm(Y ~ 1, data = sw_sub1)`) estimates a single parameter: the grand mean of `Y`. It contains no predictors, so its fitted value is identical for every observation and its residuals are the deviations of each observation from that mean. The null model is the baseline against which any more fully-specified model is compared: a nested test asks whether adding predictors reduces residual variance by more than chance alone.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfull_mod1 <- lm(Y ~ augMean + febRange + febSD + augSD + annMean,\n                data = sw_sub1)\nnull_mod1 <- lm(Y ~ 1, data = sw_sub1)\n\nsummary(full_mod1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Y ~ augMean + febRange + febSD + augSD + annMean, \n    data = sw_sub1)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-0.131229 -0.042352 -0.003415  0.038601  0.144128 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  0.044886   0.006306   7.118 9.04e-12 ***\naugMean     -0.079925   0.042630  -1.875 0.061841 .  \nfebRange     0.112913   0.015949   7.080 1.14e-11 ***\nfebSD       -0.057174   0.016554  -3.454 0.000637 ***\naugSD        0.003024   0.004886   0.619 0.536421    \nannMean      0.322776   0.041615   7.756 1.59e-13 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.05713 on 283 degrees of freedom\nMultiple R-squared:  0.8804,\tAdjusted R-squared:  0.8782 \nF-statistic: 416.5 on 5 and 283 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n::: {.callout-note appearance=\"simple\"}\n`null_mod1` is not passed explicitly to `summary()` or any other function in the code block above. `summary()` on a fitted `lm` object computes the overall $F$-statistic internally, by comparing the fitted model's residual sum of squares with the total sum of squares around the grand mean of `Y`. That total sum of squares is what the null model's residuals would give, and R derives it directly from the response vector without needing the null model object. The explicit `null_mod1` is fitted here to make the conceptual baseline visible as a model object in its own right. It becomes necessary later, in [Fit the Selected Model](#fit-the-selected-model), where I pass it to `stepAIC()` as the lower bound of the forward search. The $F$-statistic reported by `summary(full_mod1)` is the same quantity one would obtain by calling `anova(null_mod1, full_mod1)`: it is numerically equivalent, but `summary()` computes it without requiring the null model to be named.\n:::\n\nThe full model explains a large proportion of the variance in `Y`, but the coefficient table already hints at a problem: two predictors that were individually significant in @tbl-slr-fits are no longer clearly distinguishable from zero once all five are included simultaneously. This pattern is characteristic of multicollinearity.\n\n## Check for Multicollinearity\n\nThe **variance inflation factor** (VIF) for a predictor $X_j$ measures how much the variance of $\\hat\\beta_j$ is inflated relative to what it would be if $X_j$ were uncorrelated with the other predictors. A VIF of 1 indicates no collinearity with the remaining predictors. Values above 5 begin to suggest instability in the coefficient estimate, and values above 10 usually make interpretation unreliable. The formula is:\n\n$$\\text{VIF}_j = \\frac{1}{1 - R^2_j}$$\n\nwhere $R^2_j$ is the coefficient of determination from regressing $X_j$ on all other predictors in the model. When $R^2_j$ is large, $X_j$ can be reconstructed almost entirely from the other predictors, and its partial coefficient becomes imprecise.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvif(full_mod1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  augMean  febRange     febSD     augSD   annMean \n27.947767 10.806635  8.765732  2.497739 31.061900 \n```\n\n\n:::\n:::\n\n\nSeveral predictors have VIF values well above 10, indicating that the full five-predictor model is not interpretable as specified. The solution in this case is to remove the most problematic predictor and refit, iterating until VIF values are acceptable. This is a pragmatic response to collinearity within the data at hand, but it does not resolve the deeper question of why the variables are intercorrelated or what is lost when a variable is removed. [Chapter 16](16-collinearity-confounding-measurement-error.qmd) addresses those questions.\n\nNote also the distinction from confounding: collinearity is a property of the included predictors since they carry overlapping information. Confounding involves a predictor that was omitted entirely but correlates both with an included predictor and with the response, causing the included predictor's coefficient to be biased. Both problems undermine interpretation, but through different mechanisms.\n\n## Reduce Multicollinearity\n\nThe following iterative procedure removes the predictor with the highest VIF at each step until all remaining VIF values fall below a threshold of 10.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nthreshold <- 10\nvif_mod <- full_mod1\nsw_vif <- sw_sub1\n\nwhile (TRUE) {\n  vif_values <- vif(vif_mod)\n  max_vif <- max(vif_values)\n\n  if (max_vif > threshold) {\n    high_vif_var <- names(which.max(vif_values))\n    sw_vif <- sw_vif[, !(names(sw_vif) %in% high_vif_var)]\n    vif_mod <- lm(Y ~ ., data = sw_vif)\n  } else {\n    break\n  }\n}\n\nsummary(vif_mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Y ~ ., data = sw_vif)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-0.153994 -0.049229 -0.006086  0.045947  0.148579 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 0.028365   0.007020   4.040 6.87e-05 ***\naugMean     0.283335   0.011131  25.455  < 2e-16 ***\nfebSD       0.049639   0.008370   5.930 8.73e-09 ***\naugSD       0.022150   0.004503   4.919 1.47e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.06609 on 285 degrees of freedom\nMultiple R-squared:  0.8387,\tAdjusted R-squared:  0.837 \nF-statistic: 494.1 on 3 and 285 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\nvif(vif_mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n augMean    febSD    augSD \n1.423601 1.674397 1.585055 \n```\n\n\n:::\n:::\n\n\nThe retained predictors are `augMean`, `febSD`, and `augSD`, with VIF values now well below the threshold. Regularisation methods such as ridge regression or LASSO can also handle collinearity without discarding predictors, and these are introduced in [Chapter 25](25-regularisation.qmd).\n\n## Fit the Selected Model\n\nNot all three retained predictors may be needed to explain the response. I use forward stepwise AIC to identify the most parsimonious model within the reduced candidate set.\n\nVIF screening and stepwise AIC address different problems and must be applied in that order. VIF screening is a stability check; it asks whether the coefficient estimates are numerically reliable given the intercorrelations among the predictors. If two predictors share most of their information, their partial coefficients become imprecise and their standard errors inflate, regardless of how well either predicts the response.\n\nAIC-based selection cannot fix this: it will choose among poorly identified models and may retain collinear predictors simply because their combined redundancy happens to reduce the AIC criterion slightly. Removing collinear predictors first produces a candidate variable set in which every remaining predictor carries reasonably independent information. Selection then operates on a set of well-identified models and the AIC differences between them are interpretable. Applying `stepAIC` to the original five-predictor set, before VIF screening, would risk retaining a subset of correlated predictors whose coefficients look stable in the selected model only because the worst offenders were excluded by chance during the search.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod1 <- stepAIC(\n  lm(Y ~ 1, data = sw_vif),\n  scope = list(lower = lm(Y ~ 1, data = sw_vif), upper = vif_mod),\n  direction = \"forward\",\n  trace = FALSE\n)\n\nformula(mod1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nY ~ augMean + febSD + augSD\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(mod1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Y ~ augMean + febSD + augSD, data = sw_vif)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-0.153994 -0.049229 -0.006086  0.045947  0.148579 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 0.028365   0.007020   4.040 6.87e-05 ***\naugMean     0.283335   0.011131  25.455  < 2e-16 ***\nfebSD       0.049639   0.008370   5.930 8.73e-09 ***\naugSD       0.022150   0.004503   4.919 1.47e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.06609 on 285 degrees of freedom\nMultiple R-squared:  0.8387,\tAdjusted R-squared:  0.837 \nF-statistic: 494.1 on 3 and 285 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\nanova(mod1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: Y\n           Df Sum Sq Mean Sq  F value    Pr(>F)    \naugMean     1 6.0084  6.0084 1375.660 < 2.2e-16 ***\nfebSD       1 0.3604  0.3604   82.507 < 2.2e-16 ***\naugSD       1 0.1057  0.1057   24.196 1.473e-06 ***\nResiduals 285 1.2448  0.0044                       \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nThe selected model is:\n\n$$\nY = \\alpha + \\beta_1 \\text{augMean} + \\beta_2 \\text{febSD} + \\beta_3 \\text{augSD} + \\epsilon\n$$\n\n## Reading the Coefficient Table and the ANOVA Table\n\n`summary()` and `anova()` each answer a different question, and both appear above.\n\nThe **coefficient table** from `summary()` tests each partial effect *conditional* on all other predictors in the model. The *t*-statistic for `augMean` asks: given that `febSD` and `augSD` are already in the model, does `augMean` still contribute? Each test conditions on the full model as specified.\n\nThe **ANOVA table** from `anova()` is *sequential*. It partitions the total sum of squares in the order the predictors were entered: `augMean` is assessed first, then `febSD` gets credit for what `augMean` left unexplained, and `augSD` gets the remainder. Change the order of predictors in the formula and the sums of squares in the ANOVA table change. For testing whether a predictor contributes after adjusting for all others, the coefficient table is the appropriate place to look. The ANOVA table is more informative when the question is about the total variance attributable to each predictor in a natural sequence, or when comparing nested models (see [Chapter 15](15-interaction-effects.qmd)).\n\n## A Note on Scaling and Centring\n\nThe coefficient for `augMean` gives the expected change in `Y` for a one-unit increase in August mean temperature, in degrees Celsius. When predictors are on very different measurement scales, comparing their coefficients directly is not meaningful, So, a one-unit change in temperature and a one-unit change in temperature variability are not equivalent steps. Standardising predictors to zero mean and unit variance before fitting makes their coefficients comparable in the sense that each then represents the change in `Y` per one standard deviation of the predictor. Centring alone (subtracting the mean without rescaling) does not change the slopes but makes the intercept interpretable as the fitted value of `Y` at average predictor values rather than at predictor values of zero, which are often outside the data range entirely.\n\n## Check Diagnostics\n\nAdded-variable plots show the relationship between the response and each predictor after accounting for all the others in the model. They are the appropriate visual analogue to partial coefficients.\n\n\n::: {.cell}\n\n```{.r .cell-code}\navPlots(mod1, col = \"dodgerblue4\", col.lines = \"magenta\")\n```\n\n::: {.cell-output-display}\n![Added-variable (partial regression) plots for the selected model `mod1`. Each panel shows the relationship between the response and one predictor after removing the effects of the other two predictors.](14-multiple-regression-and-model-specification_files/figure-pdf/fig-mod1-partial-1.pdf){#fig-mod1-partial fig-pos='H'}\n:::\n:::\n\n\nIn @fig-mod1-partial, a tight, steeply sloped partial relationship indicates a strong predictor given the others. `augMean` shows a clear, strong partial relationship. `febSD` and `augSD` show weaker but positive partial associations. If a partial plot showed a nonlinear pattern, that would suggest the predictor needs a transformation or polynomial term. If a partial plot showed no relationship at all, that predictor contributes little once the others are accounted for.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nautoplot(mod1, shape = 21, colour = \"dodgerblue4\",\n         smooth.colour = \"magenta\") +\n  theme_grey()\n```\n\n::: {.cell-output-display}\n![Standard diagnostic plots for `mod1`. Top left: residuals vs fitted values; top right: normal Q-Q; bottom left: scale-location; bottom right: residuals vs leverage.](14-multiple-regression-and-model-specification_files/figure-pdf/fig-mod1-diagnostics-1.pdf){#fig-mod1-diagnostics fig-pos='H'}\n:::\n:::\n\n\nReading @fig-mod1-diagnostics:\n\n-   **Residuals vs fitted:** Points should scatter around zero without a systematic trend. A curve here suggests a missing predictor or a nonlinear term. Fanning, the tendency to display an increasing spread with fitted values, indicates heteroscedasticity and may require a response transformation.\n-   **Normal Q-Q:** Points should fall close to the diagonal. Systematic departure at both tails suggests non-normality; a heavy right tail in particular may require a log transformation of the response.\n-   **Scale-location:** The square root of absolute residuals should be roughly horizontal, and a rising trend confirms heteroscedasticity.\n-   **Residuals vs leverage:** Points with high leverage and large residuals are influential. The dashed contour lines mark Cook's distance of 0.5 and 1.0, and points outside those contours should be examined individually to confirm that they represent genuine observations and not data entry errors or atypical conditions.\n\nMy overall interpretation of @fig-mod1-diagnostics is that the model looks broadly acceptable. There is no severe curvature, no strong fanning, and no obviously influential outliers. Adequacy is a judgement, not a binary pass or fail.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncrPlots(mod1, col = \"dodgerblue4\", col.lines = \"magenta\")\n```\n\n::: {.cell-output-display}\n![Component-plus-residual plots for `mod1`. Each panel shows whether the relationship between the response and that predictor is approximately linear in the fitted model.](14-multiple-regression-and-model-specification_files/figure-pdf/fig-mod1-crplots-1.pdf){#fig-mod1-crplots fig-pos='H'}\n:::\n:::\n\n\nThe component-plus-residual plots in @fig-mod1-crplots are an additional linearity check. A straight pink line against the data cloud confirms that a linear term is adequate for that predictor in the model. Curvature in any panel would suggest adding a polynomial or transformed version of that predictor.\n\n::: {.callout-note appearance=\"simple\"}\nThe added-variable plots in @fig-mod1-partial and the component-plus-residual plots in @fig-mod1-crplots address different questions and plot different quantities against each other, which is why they can look similar without being equivalent.\n\nAn **added-variable plot** for predictor $X_j$ plots two sets of residuals against each other: the residuals from regressing $Y$ on all predictors *except* $X_j$, against the residuals from regressing $X_j$ on all those same other predictors. Both axes have been purged of the other predictors' effects. The slope of the line in that panel is exactly the partial coefficient $\\hat\\beta_j$. What the plot reveals is the partial relationship; that is, the strength and direction of $X_j$'s contribution to $Y$ after everything else in the model has been removed from both variables. If $X_j$ has no partial effect, the cloud in its panel will be horizontal. If $X_j$'s partial effect is nonlinear, the cloud will curve.\n\nA **component-plus-residual plot** (also called a partial-residual plot) for predictor $X_j$ plots $e_i + \\hat\\beta_j X_{ji}$ on the vertical axis — the raw residuals with the fitted linear component of $X_j$ added back in — against $X_{ji}$ itself on the horizontal axis. The idea is to reconstruct what the response would look like as a function of $X_j$ alone, after adjusting for the other predictors. The slope of the fitted line in the panel is again $\\hat\\beta_j$, but now the vertical axis is on the original scale of the predictor rather than on a residualised scale.\n\nThe practical difference is that added-variable plots are better for assessing the *existence* and *strength* of a partial effect and for detecting influential observations, because both axes are free of the other predictors. Component-plus-residual plots are better for diagnosing the *functional form* of each predictor's contribution, because the vertical axis retains the scale of $X_j$ and any smooth curve fitted through the cloud reveals whether a linear term is adequate or whether a nonlinear term is needed. In both plots, the line should be roughly straight; but it is the component-plus-residual plot where departures from linearity are most directly interpretable as evidence that a predictor needs to be transformed.\n:::\n\n## Interpret the Results\n\nThe three retained predictors are August mean temperature (`augMean`), February temperature standard deviation (`febSD`), and August temperature standard deviation (`augSD`). They are all positively associated with mean Sørensen dissimilarity in the East Coast Transition Zone. The strongest partial effect is `augMean`, while `febSD` and `augSD` make smaller but positive contributions.\n\nReading the partial coefficients: a 1 °C increase in August mean temperature is associated with an increase in mean Sørensen dissimilarity of approximately $\\hat\\beta_1$, holding February and August temperature variability constant. That \"holding constant\" qualification is the central point of the conditional interpretation. So, if the predictors were uncorrelated, this would simplify to the marginal effect seen in @fig-seaweed-slr. Because they are moderately correlated even after VIF screening, the partial coefficients differ somewhat from the simple-regression slopes.\n\nThe adjusted $R^2$ is approximately 0.84, indicating that the selected predictors account for a large proportion of the observed variation in `Y`. The ordinary $R^2$ is the proportion of total variance in the response explained by the model:\n\n$$R^2 = 1 - \\frac{\\text{SS}_\\text{res}}{\\text{SS}_\\text{tot}}$$\n\nIt never decreases when a predictor is added, even if that predictor carries no real information, because adding any variable, however useless, can only reduce or hold steady the residual sum of squares $\\text{SS}_\\text{res}$. In a multiple regression with several predictors, this means $R^2$ will overstate explanatory power if the model was arrived at by adding predictors freely. The adjusted $R^2$ corrects for this by penalising for the number of predictors $p$ relative to the sample size $n$:\n\n$$R^2_\\text{adj} = 1 - \\frac{\\text{SS}_\\text{res} / (n - p - 1)}{\\text{SS}_\\text{tot} / (n - 1)}$$\n\nThe denominator of the penalty term, $n - p - 1$, is the residual degrees of freedom. As $p$ increases, $n - p - 1$ shrinks, the ratio $\\text{SS}_\\text{res}/(n - p - 1)$ grows, and $R^2_\\text{adj}$ falls. That is, unless the additional predictor explains enough variance to compensate. The adjusted $R^2$ can therefore decrease when a weak predictor is added, which $R^2$ cannot. For comparing models with different numbers of predictors, the adjusted $R^2$ is the more honest summary of fit.\n\nThe partial coefficients are not causal estimates. The model does not rule out the possibility that some shared, unmeasured environmental driver explains both the temperatures and the dissimilarity. They are adjusted associations within the fitted model.\n\n## Report\n\n::: {.callout-note appearance=\"simple\"}\n## Write-Up\n\n**Methods**\n\nMean Sørensen dissimilarity in the East Coast Transition Zone was modelled as a function of candidate climate predictors using multiple linear regression. Collinearity among predictors was assessed using variance inflation factors; predictors with VIF above 10 were removed iteratively until the remaining predictors were below that threshold. Forward stepwise AIC was used to identify the most parsimonious model within the reduced candidate set. Assumptions were assessed using added-variable plots, standard diagnostic plots, and component-plus-residual plots.\n\n**Results**\n\nMean Sørensen dissimilarity in the East Coast Transition Zone was strongly explained by a multiple linear regression containing August mean temperature, February temperature variability, and August temperature variability (adjusted $R^2 = 0.84$; overall model $F$-test $p < 0.001$). All three retained predictors had positive partial effects. The 95% confidence intervals confirm that the partial effects of `augMean` and `febSD` exclude zero comfortably, while the interval for `augSD` is positive but wider.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconfint(mod1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 2.5 %     97.5 %\n(Intercept) 0.01454656 0.04218330\naugMean     0.26142625 0.30524446\nfebSD       0.03316346 0.06611371\naugSD       0.01328673 0.03101348\n```\n\n\n:::\n:::\n\n\n**Discussion**\n\nThe model identifies a small set of comparatively stable climatic predictors of compositional turnover in the East Coast Transition Zone. The dominant partial effect of August mean temperature is consistent with the pronounced temperature gradient along this coastline, which separates warm-temperate assemblages of the east from cool-water communities to the south. February temperature variability and August temperature variability contribute additional signal, reflecting that compositional differences are also sensitive to thermal range and seasonal extremes.\n:::\n\n# Example 2: Categorical Predictors — Distance and Bioregion\n\nMultiple regression can include both continuous and categorical predictors. In R this is done by entering the categorical variable as a factor. Once a factor is included, multiple regression and ANOVA become part of the same linear-model family, since both are fitted by `lm()` and both produce least-squares estimates within the same framework.\n\n## Dummy Variable Coding\n\nWhen a categorical variable with $k$ levels is included in a regression, R represents it using $k - 1$ dummy variables. One level is taken as the reference, and its contribution is absorbed into the model intercept. Each remaining level receives a coefficient that gives the difference in fitted intercept relative to that reference.\n\nSuppose `bio` has four levels: `AMP`, `B-ATZ`, `BMP`, `ECTZ`. With `AMP` as the reference, the model is:\n\n$$\nY_i = \\alpha + \\beta_1 \\text{dist}_i\n+ \\gamma_1 D_{i,\\text{B-ATZ}}\n+ \\gamma_2 D_{i,\\text{BMP}}\n+ \\gamma_3 D_{i,\\text{ECTZ}}\n+ \\epsilon_i\n$$\n\nwhere each $D$ is 1 for observations belonging to that bioregion and 0 otherwise. The coefficient $\\gamma_1$ is not the mean `Y` for `B-ATZ`; it is the difference between the fitted intercept for `B-ATZ` and the fitted intercept for `AMP`. This is the detail that produces the most confusion when reading R output.\n\n## What the Coding Looks Like in Practice\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nbio_demo <- tibble(\n  bio = factor(c(\"AMP\", \"B-ATZ\", \"BMP\", \"ECTZ\"),\n               levels = levels(factor(sw$bio)))\n)\n\nbio_model_matrix <- model.matrix(~ bio, data = bio_demo) |>\n  as.data.frame() |>\n  mutate(bio = bio_demo$bio) |>\n  relocate(bio)\n```\n:::\n\n\n\n::: {#tbl-bio-demo .cell tbl-cap='Dummy-variable coding for the four seaweed bioregions when `AMP` is the reference level. Each row shows the values of the three indicator variables for that bioregion. `AMP` is coded entirely as zeros, so its contribution is captured by the model intercept.'}\n::: {.cell-output-display}\n\\begin{table}\n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}crrrr}\n\\toprule\nbio & (Intercept) & bioB-ATZ & bioBMP & bioECTZ \\\\ \n\\midrule\\addlinespace[2.5pt]\nAMP & 1 & 0 & 0 & 0 \\\\ \nB-ATZ & 1 & 1 & 0 & 0 \\\\ \nBMP & 1 & 0 & 1 & 0 \\\\ \nECTZ & 1 & 0 & 0 & 1 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nbio_model_matrix |>\n  pivot_longer(cols = -bio, names_to = \"term\", values_to = \"value\") |>\n  ggplot(aes(x = term, y = bio, fill = factor(value))) +\n  geom_tile(colour = \"white\") +\n  scale_fill_manual(values = c(\"0\" = \"grey85\", \"1\" = \"steelblue4\")) +\n  labs(x = NULL, y = \"Bioregion\", fill = \"Value\") +\n  theme_grey()\n```\n\n::: {.cell-output-display}\n![Visualisation of the dummy-variable coding shown in @tbl-bio-demo. `AMP` (reference level) has all zeros; the three other bioregions each have a single 1 in their corresponding indicator column.](14-multiple-regression-and-model-specification_files/figure-pdf/fig-bio-dummy-coding-1.pdf){#fig-bio-dummy-coding fig-pos='H'}\n:::\n:::\n\n\n**Reading the table.** Each row of @tbl-bio-demo is a bioregion; each column after the first is a dummy variable. The first column, `(Intercept)`, contains a 1 for every observation without exception. It is not a variable in the usual sense; it is the column that allows the model to estimate a constant term. Multiplying $\\alpha$ by 1 for every row is how the intercept enters the linear predictor $\\mathbf{X}\\boldsymbol{\\beta}$ in matrix notation. When you see `(Intercept)` in `summary()` output, the coefficient next to it is $\\hat\\alpha$, which is the fitted value of $Y$ when every other column in the model matrix is zero, which in this case means an `AMP` observation at `dist = 0`.\n\nThe three dummy columns come after it. The dummy for a given bioregion is 1 for that bioregion's row and 0 for every other row. `AMP` has a 0 in every dummy column — that is not an error or a gap; it is the definition of the reference level. When all dummies are zero, the model collapses to the intercept column alone, so $\\hat\\alpha$ *is* the fitted baseline for `AMP`.\n\n@fig-bio-dummy-coding shows the same information as a grid. The pattern clearly reveals that no two bioregions share a 1 in the same dummy variable column. Each bioregion is uniquely identified by exactly one blue cell, or, in the case of `AMP`, by the absence of blue cells.\n\n**Translating to `summary()` output.** When `bio` is passed to `lm()` as a factor, R creates exactly the three dummy columns shown in @tbl-bio-demo and fits a coefficient to each. The coefficient table in `summary()` will contain rows named `bioB-ATZ`, `bioBMP`, and `bioECTZ`. It will *not* contain a row for `bioAMP`, because `AMP` is captured entirely by the intercept. Reading those output rows correctly requires remembering the table:\n\n-   For an `AMP` observation: all three dummies are 0. The fitted value from the categorical part of the model is $\\alpha$ — the intercept alone.\n-   For a `BMP` observation: `bioBMP = 1`, the other two dummies are 0. The fitted value from the categorical part is $\\alpha + \\hat\\gamma_2$, where $\\hat\\gamma_2$ is the coefficient of `bioBMP`. The model has shifted the fitted line for `BMP` up (or down) relative to `AMP` by exactly $\\hat\\gamma_2$.\n-   For an `ECTZ` observation: `bioECTZ = 1`, the others are 0. The fitted value is $\\alpha + \\hat\\gamma_3$.\n\nThe slope of `dist` is the same in every bioregion — that is the additive assumption. What differs across bioregions is only the intercept: each non-reference bioregion has its own vertical offset from the `AMP` baseline, and those offsets are exactly the dummy-variable coefficients printed in `summary()`. A positive `bioBMP` coefficient means that BMP sites have higher baseline dissimilarity than AMP sites, after accounting for distance. A negative coefficient would mean the opposite. Neither says anything about the slope of `dist`; that is shared, and its estimate does not change from one bioregion to the next in an additive model.\n\nChanging the reference level with `relevel()` shifts which bioregion is absorbed into the intercept but does not change the fitted values, residuals, or the model's overall explanatory power. It only redistributes how the group differences are expressed in the coefficient table.\n\n## Biological Question and Hypotheses\n\nTwo variables not yet used from the seaweed dataset are:\n\n-   `dist` — geographic distance between adjacent sample sites along the South African coastline;\n-   `bio` — the bioregional classification of each site.\n\nI ask two additive questions here:\n\n1. Is mean Sørensen dissimilarity related to geographic distance?\n2. Does mean Sørensen dissimilarity differ among bioregions after accounting for distance?\n\nA third question — whether the effect of distance differs among bioregions — requires an interaction term and is therefore deferred to [Chapter 15](15-interaction-effects.qmd).\n\nThe additive model for the first two questions is:\n\n$$\nY = \\alpha + \\beta_1 \\text{dist} + \\gamma_1 \\text{bio}_{\\text{B-ATZ}}\n+ \\gamma_2 \\text{bio}_{\\text{BMP}}\n+ \\gamma_3 \\text{bio}_{\\text{ECTZ}}\n+ \\epsilon\n$$\n\nThe null hypothesis is that neither distance nor bioregion contributes to explaining variation in `Y`.\n\n## Visualise the Main Effects\n\n\n::: {.cell}\n\n```{.r .cell-code}\np1 <- ggplot(sw, aes(x = dist, y = Y)) +\n  geom_point(shape = 1, aes(colour = bio)) +\n  geom_smooth(method = \"lm\", se = TRUE,\n              colour = \"black\", fill = \"grey60\",\n              linewidth = 0.4) +\n  scale_colour_brewer(palette = \"Set1\") +\n  labs(x = \"Distance (km)\",\n       y = \"Sørensen Dissimilarity\") +\n  theme_grey()\n\np2 <- ggplot(sw, aes(x = bio, y = Y)) +\n  geom_boxplot(aes(colour = bio)) +\n  labs(x = \"Bioregional Classification\",\n       y = \"Sørensen Dissimilarity\") +\n  theme_grey() +\n  theme(legend.position = \"none\")\n\nggarrange(p1, p2, ncol = 2, labels = \"AUTO\")\n```\n\n::: {.cell-output-display}\n![Main effects of (A) geographic distance along the coast and (B) bioregional classification on mean Sørensen dissimilarity. Points in panel A are coloured by bioregion to show how the distance–dissimilarity relationship maps onto regional structure.](14-multiple-regression-and-model-specification_files/figure-pdf/fig-mod2-main-effects-1.pdf){#fig-mod2-main-effects fig-pos='H'}\n:::\n:::\n\n\n@fig-mod2-main-effects shows that `Y` increases with distance and that the average level of `Y` differs visibly among bioregions. The additive model combines both patterns in a single regression without yet allowing the distance slope to vary by region.\n\n## Fit and Assess Nested Models\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod2a <- lm(Y ~ dist, data = sw)\nmod2 <- lm(Y ~ dist + bio, data = sw)\n\nanova(mod2a, mod2, test = \"F\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nModel 1: Y ~ dist\nModel 2: Y ~ dist + bio\n  Res.Df    RSS Df Sum of Sq      F    Pr(>F)    \n1    968 7.7388                                  \n2    965 4.1156  3    3.6232 283.19 < 2.2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(mod2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Y ~ dist + bio, data = sw)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-0.189964 -0.038724 -0.002277  0.029329  0.256021 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -2.698e-02  4.547e-03  -5.933 4.15e-09 ***\ndist         4.612e-04  1.059e-05  43.533  < 2e-16 ***\nbioB-ATZ     7.340e-02  1.368e-02   5.364 1.02e-07 ***\nbioBMP       1.258e-02  5.258e-03   2.393   0.0169 *  \nbioECTZ      1.385e-01  5.043e-03  27.461  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.06531 on 965 degrees of freedom\nMultiple R-squared:  0.7453,\tAdjusted R-squared:  0.7442 \nF-statistic:   706 on 4 and 965 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\nanova(mod2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: Y\n           Df Sum Sq Mean Sq F value    Pr(>F)    \ndist        1 8.4199  8.4199 1974.25 < 2.2e-16 ***\nbio         3 3.6232  1.2077  283.19 < 2.2e-16 ***\nResiduals 965 4.1156  0.0043                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nThe nested comparison uses the sequential ANOVA framework described in [Example 1](#reading-the-coefficient-table-and-the-anova-table): it asks whether adding `bio` to the distance-only model reduces residual variance by more than chance. The residual sum of squares drops sharply, and the $F$-test is highly significant ($p < 0.001$), so the richer additive model fits substantially better.\n\nThe `summary()` output shows the partial effect of `dist` and the coefficient for each non-reference bioregion. Each `bio` coefficient is the difference in fitted intercept from `AMP` after conditioning on distance.\n\n## Interpret the Additive Model\n\nThe additive model assumes one common slope for `dist` across all bioregions. The fitted distance effect is strongly positive: as sample sites become more geographically separated along the coast, their seaweed assemblages become more dissimilar. The bioregion coefficients show that baseline dissimilarity differs among regions even after that distance effect is removed.\n\nThis additive interpretation is the right level of complexity for the question asked here. The model does not yet address whether the rate at which dissimilarity increases with distance differs among bioregions. If that is the next biological question — and it plausibly is, because distinct oceanographic provinces might produce different turnover rates — then the model must be extended to include an interaction between `dist` and `bio`. That step opens [Chapter 15](15-interaction-effects.qmd).\n\n## Where ANCOVA Fits\n\n**ANCOVA** is often taught as a method distinct from regression and ANOVA. It is not. ANCOVA is a linear model that contains one factor and at least one continuous covariate in an additive structure. The model `mod2` above fits exactly that description: `bio` is the factor and `dist` is the covariate. The coefficient table and ANOVA table produced by `lm()` and `aov()` for an ANCOVA model are algebraically the same.\n\nIn R:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm(Y ~ bio + dist, data = sw)   # regression-style output\naov(Y ~ bio + dist, data = sw)  # ANOVA-style output\n```\n:::\n\n\nBoth fit the same model. The difference is in the emphasis of the output: `lm()` foregrounds the coefficient table and makes the covariate slope explicit; `aov()` foregrounds the ANOVA table and omnibus *F*-tests. For an ANCOVA, `lm()` is usually the clearer teaching choice because it makes the covariate's role visible directly.\n\nThe standard ANCOVA assumption is that the covariate slope is the **same across factor levels** — the same `dist` slope applies in all bioregions. In model terms, that is the additive structure without a `bio:dist` interaction. If there is biological reason to expect that different bioregions show different turnover rates with distance, the interaction model becomes appropriate, and the simple ANCOVA framing no longer applies.\n\n## Report\n\n::: {.callout-note appearance=\"simple\"}\n## Write-Up\n\n**Methods**\n\nNested linear models were used to test whether mean Sørensen dissimilarity was related to geographic distance and whether mean dissimilarity differed among bioregions after accounting for distance. A distance-only model was compared with an additive model containing distance and bioregional classification using a sequential *F*-test.\n\n**Results**\n\nMean Sørensen dissimilarity increased with geographic distance along the South African coast, and an additive model showed that dissimilarity also differed among bioregions independently. Adding bioregion to the distance-only model improved fit substantially ($p < 0.001$; @fig-mod2-main-effects). The fitted distance effect was strongly positive, and the bioregion coefficients indicated that baseline dissimilarity differed among regions relative to the `AMP` reference level.\n\n**Discussion**\n\nCompositional turnover is jointly structured by geographic distance and bioregional context. The additive model attributes both effects to separate, non-interacting sources of variation. The assumption that distance has the same effect in all bioregions remains to be tested; that question is addressed in [Chapter 15](15-interaction-effects.qmd).\n:::\n\n# Example 3: The Full Additive Model\n\nI now combine the selected climate predictors from [Example 1](#example-1-a-climate-model-for-the-east-coast-transition-zone) with `bio` as an additive predictor, using the full dataset rather than the ECTZ subset alone. This produces a model in which climatic effects are estimated jointly with bioregional differences.\n\n## Fit the Model\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsw_sub2 <- sw |>\n  dplyr::select(Y, augMean, febSD, augSD, bio)\n\nfull_mod3 <- lm(Y ~ augMean + febSD + augSD + bio, data = sw_sub2)\nfull_mod3a <- lm(Y ~ augMean + febSD + augSD, data = sw_sub2)\nnull_mod3 <- lm(Y ~ 1, data = sw_sub2)\n\nanova(full_mod3, full_mod3a)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nModel 1: Y ~ augMean + febSD + augSD + bio\nModel 2: Y ~ augMean + febSD + augSD\n  Res.Df   RSS Df Sum of Sq      F    Pr(>F)    \n1    963 4.834                                  \n2    966 5.689 -3  -0.85507 56.781 < 2.2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\nAIC(full_mod3, full_mod3a)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           df       AIC\nfull_mod3   8 -2373.840\nfull_mod3a  5 -2221.852\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(full_mod3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Y ~ augMean + febSD + augSD + bio, data = sw_sub2)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-0.167665 -0.045280 -0.006433  0.039474  0.288426 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  0.027394   0.005267   5.201 2.42e-07 ***\naugMean      0.281357   0.007892  35.653  < 2e-16 ***\nfebSD       -0.002945   0.002864  -1.028    0.304    \naugSD        0.014463   0.002918   4.956 8.49e-07 ***\nbioB-ATZ    -0.012508   0.014915  -0.839    0.402    \nbioBMP      -0.034542   0.006385  -5.410 7.96e-08 ***\nbioECTZ      0.050082   0.006387   7.842 1.18e-14 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.07085 on 963 degrees of freedom\nMultiple R-squared:  0.7008,\tAdjusted R-squared:  0.699 \nF-statistic:   376 on 6 and 963 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\nanova(full_mod3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: Y\n           Df Sum Sq Mean Sq  F value    Pr(>F)    \naugMean     1 9.9900  9.9900 1990.165 < 2.2e-16 ***\nfebSD       1 0.0530  0.0530   10.563  0.001194 ** \naugSD       1 0.4266  0.4266   84.983 < 2.2e-16 ***\nbio         3 0.8551  0.2850   56.781 < 2.2e-16 ***\nResiduals 963 4.8340  0.0050                       \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nThe climate-plus-bioregion model fits substantially better than the climate-only model: AIC is lower and the nested comparison is highly significant. Adding `bio` captures broad regional differences in baseline dissimilarity that the climate predictors alone do not account for. This is ecologically plausible: the South African coast traverses distinct biogeographic provinces shaped by oceanographic features — notably the warm Agulhas current to the south-east and the cold Benguela upwelling to the west — that create regional biotic signatures beyond what the three retained temperature metrics capture.\n\n## Interpret the Model\n\n`augMean` remains the dominant climate predictor. The `bio` coefficients show that after adjusting for the three climate variables, the baseline dissimilarity still differs among regions. The model is additive: the climate slopes are assumed to be the same in all bioregions. The fitted model explains a large proportion of the variation in `Y`, and the residuals show no alarming departures from the linear-model assumptions.\n\nAt this stage the analysis has reached the limit of the additive structure. The next biological question is whether climate relationships themselves differ among bioregions — whether the slope of `augMean` is steeper in the ECTZ than in the BMP, for example. That question requires interactions, which are the subject of [Chapter 15](15-interaction-effects.qmd).\n\n## Report\n\n::: {.callout-note appearance=\"simple\"}\n## Write-Up\n\n**Methods**\n\nA comprehensive additive multiple regression was fitted to evaluate whether mean Sørensen dissimilarity was explained jointly by August mean temperature, February temperature standard deviation, August temperature standard deviation, and bioregional classification. A climate-plus-bioregion model was compared with a climate-only model using AIC and a nested *F*-test.\n\n**Results**\n\nThe climate-plus-bioregion additive model fitted the data substantially better than the corresponding climate-only model (lower AIC; nested model comparison $p < 0.001$). August mean temperature remained the dominant positive predictor. The inclusion of bioregion showed that regional differences in baseline dissimilarity persisted even after the climate variables were accounted for. The overall model explained a large proportion of the variation in mean Sørensen dissimilarity.\n\n**Discussion**\n\nCompositional turnover along the South African coast is shaped both by the selected climate variables and by broader biogeographic structure. The additive model assumes that the climate slopes are uniform across bioregions. Whether that assumption is defensible — or whether the Agulhas and Benguela systems show distinct rates of climate-driven turnover — is a question for the interaction models developed in [Chapter 15](15-interaction-effects.qmd).\n:::\n\n# Alternative Categorical Variable Coding Schemes (Contrasts)\n\nThe examples above use the default treatment coding in R, which takes the first factor level as the reference and expresses all other levels as deviations from it. Two other coding schemes are occasionally useful.\n\n**Effect coding** (sum-to-zero coding) expresses each level's coefficient as a deviation from the grand mean rather than from one reference level. The last level is the one dropped, and its effect is the negative sum of the other coefficients.\n\n**Helmert coding** compares each level to the average of all subsequent levels and can be informative when factor levels have a natural ordering.\n\nThe choice of coding does not affect the fitted values or residuals. It only changes how the coefficients are expressed and therefore how they are interpreted. The practical advice is to use the default treatment coding unless there is a specific scientific reason to express effects differently.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)\nn <- 100\nx <- rnorm(n)\ncat_var <- factor(sample(c(\"A\", \"B\", \"C\", \"D\"), n, replace = TRUE))\ny <- 2 * x + ifelse(cat_var == \"A\", 3,\n                    ifelse(cat_var == \"B\", 1,\n                           ifelse(cat_var == \"C\", -1, -3))) + rnorm(n)\n\ndata_contr <- data.frame(y, x, cat_var)\nhead(data_contr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           y           x cat_var\n1  0.6667876 -0.56047565       B\n2  1.3086873 -0.23017749       B\n3  0.4496192  1.55870831       D\n4  2.1326402  0.07050839       A\n5 -2.8608771  0.12928774       D\n6  0.1497346  1.71506499       D\n```\n\n\n:::\n:::\n\n\nDefault treatment coding:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncontrasts(data_contr$cat_var)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  B C D\nA 0 0 0\nB 1 0 0\nC 0 1 0\nD 0 0 1\n```\n\n\n:::\n:::\n\n\nChange the reference level:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata_contr$cat_var <- relevel(data_contr$cat_var, ref = \"C\")\ncontrasts(data_contr$cat_var)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  A B D\nC 0 0 0\nA 1 0 0\nB 0 1 0\nD 0 0 1\n```\n\n\n:::\n:::\n\n\nEffect coding:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncontrasts(data_contr$cat_var) <- contr.sum(4)\ncontrasts(data_contr$cat_var)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  [,1] [,2] [,3]\nC    1    0    0\nA    0    1    0\nB    0    0    1\nD   -1   -1   -1\n```\n\n\n:::\n:::\n\n\nThe key lesson is not that these coding schemes must be memorised. It is that the interpretation of categorical coefficients in a regression output is inseparable from the coding that produced them.\n\n# Towards Interaction Models\n\nThe three examples in this chapter all use additive structure: the effect of each predictor is assumed to be independent of the others. In the language of the seaweed model, this means the climate slope does not depend on which bioregion an observation comes from, and the bioregion difference does not depend on climate.\n\nThat additivity assumption is an explicit biological claim. For the seaweed data, it may not hold: the rate at which assemblage dissimilarity increases with August mean temperature could plausibly be steeper in a cool upwelling system than in a warm current province, because the thermal gradient has a different ecological meaning in each context. If the slopes differ, the additive model will average across a real biological heterogeneity and produce a fitted `augMean` coefficient that is an average of two different relationships — informative, but potentially misleading.\n\n[Chapter 15](15-interaction-effects.qmd) relaxes the additivity assumption and fits models with explicit interactions. The same seaweed dataset is used there, so the biological context carries directly over. The conceptual step from `Y ~ augMean + bio` to `Y ~ augMean * bio` is small in code and large in interpretation: it shifts from asking \"what is the average climate effect?\" to asking \"does the climate effect differ among bioregions, and if so, how?\"\n\n# Summary\n\nMultiple regression models a continuous response as a linear function of several predictors simultaneously. The central interpretive feature is the partial coefficient: each $\\hat\\beta_j$ gives the expected change in $Y$ for a one-unit increase in $X_j$ while all other predictors are held at their observed values. That conditional interpretation is what distinguishes a coefficient from a multiple regression from the slope in a simple regression.\n\nModel specification — deciding which variables belong and what structure the model should have — is an act of scientific reasoning, not a data-processing step. Multicollinearity, confounding, and measurement error each undermine the reliability of fitted coefficients in different ways; the variance inflation factor detects collinearity but does not resolve confounding, which requires thinking carefully about which variables are absent from the model.\n\nCategorical predictors enter the multiple regression through dummy-variable coding. ANCOVA is the special case in which one predictor is a factor and the remaining predictors are continuous covariates; it is algebraically identical to multiple regression and fitted by the same `lm()` function.\n\nThe three worked examples in this chapter all use additive structure. [Chapter 15](15-interaction-effects.qmd) asks whether the additive assumption is biologically defensible — or whether the effects of climate and region on seaweed compositional turnover are better described by a model that allows those effects to vary jointly.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "\\usepackage{booktabs}\n\\usepackage{caption}\n\\usepackage{longtable}\n\\usepackage{colortbl}\n\\usepackage{array}\n\\usepackage{anyfontsize}\n\\usepackage{multirow}\n"
      ]
    },
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}