---
title: "8a. Principal Component Analysis (PCA)"
subtitle: "Task C"
author: 
  - "AJ Smit"
---

## Task C

1. With reference to the sampling design (i.e. position of sample sites along the length of the Doubs River), provide mechanistic/ecological reasons for the strongly correlated environmental variables shown above in the pairwise correlation diagram. You might have to create additional spatial maps of scaled variables (as immediately above) to support your answer.

2. Provide a summary of the main findings of the Doubs River fish community structure study, focusing in this instance mainly on the environmental drivers.

3. Why can a PCA, or *any* ordination for that matter, not explain all of the variation in a dataset? In other words, why is it best to only use the first few Principal Components for insight into the drivers of variability? What is 'explained' by the remaining PC axes?

4. Replicate the analysis shown above on the **environmental data** included with these datasets:
    i. [bird communities along elevation gradient in Yushan Mountain, Taiwan](https://www.davidzeleny.net/anadat-r/doku.php/en:data:ybirds);
    ii. [alpine plant communities in Aravo, France](https://www.davidzeleny.net/anadat-r/doku.php/en:data:aravo).

5. Discuss the patterns observed:
    i. explain the ordination diagram with particular reference to the major patterns shown;
    ii. provide a mechanistic explanation for the existence of the patterns seen with respect to elevation/altitude; and
    iii. if there are significant positive or negative correlations between the environmental variables, provide mechanistic reasons for how they came about.

::: callout-important
## Submission instructions

Submit a Quarto HTML document wherein you provide answers to Questions 1--5 by the deadline in the syllabus schedule.

Provide a **neat and thoroughly annotated** Quarto/html files which outlines the graphs and all calculations and which displays the resultant distance matrix. Use separate tabs for the different questions.

Please label the Quarto and resulting HTML files as follows:

-   `BCB743_<first_name>_<last_name>_Task_C.qmd`, and

-   `BCB743_<first_name>_<last_name>_Task_C.html`

(the `<` and `>` must be omitted as they are used in the example as field indicators only).

Failing to follow these instructions carefully, precisely, and thoroughly will cause you to lose marks, which could cause a significant drop in your score as formatting counts for 15% of the final mark (out of 100%).

Submit your Labs to me by email.
:::
