---
title: "Task G"
subtitle: "Integrative Assessment"
author: 
  - "AJ Smit"
date: '2024/07/02 (updated: `r Sys.Date()`)'
---

This task uses the data described at the start of the Chapter 5 about [Multiple Regression](../../docs/The-Biostatistics-Book-Ch-3-5.pdf) in The Biostatistics Book. The data can be downloaded [here](../../data/seaweed/seaweed.zip).

Please also refer to the chapter [Deep Dive into Gradients](../deep_dive.qmd) for the data description and the chapter [Seaweeds in Two Oceans: Beta-Diversity (Appendices)](../two_oceans_appendices.qmd) for more information about the analyses in the paper. The publication that captures all the data and analyses is @smit2017seaweeds.

In this task, you will develop a comprehensive data analysis, undertake model building, and provide an interpretation of the findings. In Questions 1--3, your goal is to explore and analyse the species composition and assembly processes of the seaweed flora around the coast of South Africa. Question 4 requires integrating the preceding analyses into a coherent narrative in the form of a scientific paper. Question 5 is a reflection and assessment of theoretical concepts covered in the course, testing critical thinking about variable and model selection.

Begin by thoroughly reading the chapter on [Model Building](../model_building.qmd), then complete Questions 1--3:

## Question 1

**Unconstrained Ordinations:** Use an unconstrained analysis of your choice to explore the species data ($\beta_\text{sim}$ and $\beta_\text{sne}$, represented by columns `Y1` and `Y2` in the dataset) in various meaningful ways. In typical exploratory data analysis (EDA), unconstrained methods can be helpful. Consider including univariate maps that highlight the distribution of species composition along the coast of South Africa or indicate the existence of spatial gradients, using functions like `envfit()` or `ordisurf()`.

Note: The data in `Y1` and `Y2` cannot be used directly, but you'll have to use the data in `SeaweedSpp.csv` to calculate the dissimilarity matrices and then use the `Y1` and `Y2` matrices in your calculations. Matching environmental data in a compatible format are in `SeaweedEnv.RData`. Both these datasets will be in the ZIP file downloadable above.

## Question 2

**MLR Analyses:** Develop multiple linear regression models for the seaweed species composition (`Y1` and `Y2`) using all available predictors. Present the final model(s) that best describe the species assembly processes along the South African coast. The final model may or may not include all the predictors, and you must justify your variable and model selection.

## Question 3

**Constrained Ordination:** Focusing on `Y1` and `Y2`, apply a suitable constrained ordination technique to the data and compare the results with the multiple regression models. Discuss the differences and similarities between the two approaches.

### Notes on Questions 1--3 {.unnumbered}

**[35% towards Task G]**

To complete Questions 1--3, follow the model-building process outlined in the [Model Building](../model_building.qmd) chapter. This includes:

- Guiding the reader through your approach and rationale for the study, commenting on how and why certain methods are used.
- Using Quarto's [Code Annotations](https://quarto.org/docs/authoring/code-annotation.html) to explain key portions of your code, such as specific functions or important arguments.
- Providing a detailed explanation of what the results mean in the context of the specific methodology employed (not in terms of the ecological theory, which is covered in Question 4).
- Describing which variables are used in your analyses and why.
- Conducting data exploration and visualisation (EDA).
- Building models (including hypothesis statements, variable selection using VIF and forward selection, comparisons of nested models, and justifications for variable and model selection).
- Performing model diagnostics (when appropriate).
- Explaining the outputs of `summary()`, `anova()` and any figures (as applicable)---i.e. explain results in context of the stats methods used.
- Discussing the results in the context of the methodology used.
- Not yet discussing the ecological findings, as that is reserved for Question 4.

## Question 4

**Formal Write-up:** Integrate your results (from the unconstrained ordination, MLR, and constrained ordination) with ecological theory in the format of a scientific publication. In other words, adhere to all the expectations of a journal article. Discuss your findings in light of the appropriate ecological hypotheses that might explain the relationships between the predictors and the seaweed species composition. This section should be written as if for a peer-reviewed publication and must include references. The aim is to analyse data about South Africa's seaweed flora and discuss the implications of the results in the context of ecological theory. Draw insights from the analysis of $\beta_\text{sør}$ developed in the Multiple Regression chapter and rely on the theory from the lecture material developed in Task A2.

### Notes on Question 4 {.unnumbered}

**[35% towards Task G]**

Question 4 focuses on model interpretation and discussing the ecological relevance of the results. The paper must have the following sections:

- **Abstract:** A brief summary of the study and the main findings.
- **Introduction:** Introduction (background, rational, justification, etc.), including the aims and hypotheses to be tested.
- **Methods:** Combine and condense the detailed narrative developed for Questions 1--3 into a format suitable for publication. Include a description of the data, methods used, and analyses performed.
- **Results:** Combine the results from Questions 1--3 and present them in a way suitable for a peer-reviewed publication. Include tables and figures as needed. This means that you should present results in the context of the ecological questions being addressed (as appropriate for publications) not in the context of the stats you applied (which was assessed in Questions 1--3).
- **Discussion:** Include a detailed interpretation and discussion of the results. Discuss the implications of the findings in the context of ecological theory, similarities and contrasts with other similar studies, consideration of the limitations of the study, and suggest future research directions.
- **References:** Add references liberally throughout. Try and refrain from citing papers already cited by @smit2017seaweeds.

Mark allocation:

- Introduction, including background, justification, rationale, aims, objectives, hypotheses: 15% of Question 4
- Methods and analyses: 25%
- Results: 15%
- Graphs: 15%
- Discussion: 30%

## Question 5

### Model Building

Choose i) or ii) to answer:

i. **Model Selection:** Discuss the importance of model selection in the context of the analyses you have conducted. What are the key considerations when selecting variables for inclusion in a model? How do you decide which variables to include or exclude? What are the implications of including or excluding variables in a model? **[30% of Question 5]**

ii. **Multicollinearity:** Discuss the concept of multicollinearity and its implications for model building. How do you identify multicollinearity in a dataset, and what are the consequences of multicollinearity for model interpretation and prediction? **[30% of Question 5]**

### Predictors

Answer i) and ii):

i. Ecologists often use predictors such as altitude, depth, latitude, and distance between pairs of sites when they assess environmental gradients. Discuss the advantages and disadvantages of using these predictors in ecological studies. What are the implications of using these predictors for model interpretation and prediction? Substantiate your answer with examples external to any of the analyses performed in BCB743. **[30% of Question 5]**

ii. Why did I exclude longitude from list of example predictors in the previous question? **[5% of Question 5]**

### Deeper Analysis

Choose i) or ii) to answer:

i. **Technological Advances:** Analyse the impact of technological advances (e.g., the use of classical quadrats and transects, aerial photography, integration of ecological data with environmental data, remote sensing, machine learning, etc.) on the field of quantitative ecology over the last four decades. How has the nature of the questions ecologists ask changed? How have these technologies changed the way we collect, analyse, and interpret ecological data? What are the potential benefits and pitfalls of relying heavily on technology in ecological research? **[25% of Question 5]**

ii. **Interdisciplinary Approaches:** Explore the importance of interdisciplinary approaches in quantitative ecology. How can collaboration with other fields (e.g., sociology, economics, geography) enhance our understanding of ecological systems? Discuss the benefits and challenges of working across disciplines. Provide examples of successful interdisciplinary research projects in quantitative ecology. **[25% of Question 5]**

### Your Future in Quantitative Ecology

What personal challenges do you see for yourself as an aspiring quantitative ecologist? How can you prepare yourself to meet these challenges and contribute to the field of quantitative ecology? What skills do you need to develop, and what experiences do you need to gain to be successful in this field? **[10% of Question 5]**

### Notes on Question 5 {.unnumbered}

**[15% towards Task G]**

All answers must be in the form of a narrative essay (1 to 2 pages, depending on the amount of marks).

## Question 6

As an educational reviewer, you are tasked with evaluating the BCB743 course for an article on advanced ecological studies worldwide. Based on concrete examples taken from the course material available to students, your balanced review should assess the positives and negatives around the course's scope, content, and approach within the context of similar international offerings.

Analyse the strengths and weaknesses of BCB743, comparing its depth of theory, practical applications, and learning outcomes to other programs. Consider how well it aligns with current academic trends and emerging technologies in ecological research. Υour target audience comprises students and scholars seeking accredited training in modern quantitative ecological methods. They will use your evaluation to inform their educational choices.

Since the review will also assist the instructor, offer constructive feedback for course improvement and study guidance. Your review should be detailed, balanced, and professional, using specific examples to support your arguments. Compare BCB743 with benchmark programs from renowned institutions to provide concrete reference points.

The ultimate goal is to provide actionable insights that will enhance the quality and effectiveness of BCB743 in preparing students for careers in quantitative ecology.

### Notes on Question 6 {.unnumbered}

**[15% towards Task G]**

**Review Guidelines** These are guidelines only! You are free to structure your review as you see fit, but ensure that you adhere to the overall intent of the review.

- Begin by providing a brief overview of the course's structure, objectives, and target audience, highlighting its unique selling points and distinguishing features.
- Evaluate the course's theoretical depth and practical relevance, comparing it to similar programs offered by other institutions.
- You might decide to focus on the course's curriculum, including the range of topics covered, the depth of coverage, and the balance between theory and practice.
- Consider the course's accessibility and flexibility, including options for remote or online learning, which are increasingly important in modern education.
- You can focus on the course materials (website, lecture notes, assignments, etc.) and their quality, relevance, and alignment with the course objectives and/or the delivery of the content and depth of instruction (your choice).
- You may wish to comment on the level of preparedness of the course's instructors and the quality of the teaching materials, including textbooks, software, and online resources.
- Provide insight into the level of prior knowledge and learning expected from students should they enroll in the course, and the level of support available to help them meet these expectations.
- Evaluate the course's interdisciplinary approach, if any, as ecological studies often intersect with other fields like data science, climate science, and conservation biology.
- Assess the course's emphasis on practical skills development, such as coding, data analysis, and fieldwork, which are crucial for career preparation.
- Comment on the relevance of the course and course examples in the context of South African and global ecological challenges, such as climate change, biodiversity loss, and habitat destruction.
- Provide an opinion on the relevance of the module in the context of South Africa's socio-political landscape.
- Provide insights into the course's integration of real-world case studies or collaboration with conservation partners, which can enhance its practical value.

::: callout-important
## Submission instructions

Submit a Quarto HTML file wherein you provide answers to the questions by the deadline in the syllabus schedule.

Provide a **neat and thoroughly annotated** Quarto/html files which outlines the graphs and all calculations and which displays the resultant distance matrix. Use separate tabs for the different questions.

Please label the Quarto and resulting HTML files as follows:

-   `BCB743_<first_name>_<last_name>_Task_G.qmd`, and

-   `BCB743_<first_name>_<last_name>_Task_G.html`

(the `<` and `>` must be omitted as they are used in the example as field indicators only).

Failing to follow these instructions carefully, precisely, and thoroughly will cause you to lose marks, which could cause a significant drop in your score as formatting counts for 15% of the final mark (out of 100%).

Submit your Labs on iKamva when ready.
:::
