---
title: "8c. PCA of WHO SDGs and 13. Cluster Analysis"
subtitle: "Task D"
author: 
  - "AJ Smit"
---

```{r code-brewing-opts, echo=FALSE}
knitr::opts_chunk$set(
  comment = "R>", 
  warning = FALSE, 
  message = FALSE,
  fig.width = 4.5,
  fig.height = 2.625,
  out.width = "75%",
  fig.asp = NULL, # control via width/height
  dpi = 300
)

ggplot2::theme_set(
  ggplot2::theme_minimal(base_size = 8)
)
ggplot2::theme_set(
  ggplot2::theme_bw(base_size = 8)
)
```

## Task D

**Question 1 refers to PCA SDG.**

1. Explain the code section-by-section in long-form text. Include also the reasoning/rationale behind each section.

**Questions 2--5 refer to [Cluster Analysis](../cluster_analysis.qmd).**

2. What happens if we use `pam()` to create four, five, or even six clusters?

3. In your reasoned opinion, what would be the optimal number of clusters to use?

4. Repeat the analysis using either `kmeans()` or `hclust()`, and feel free to use the **factoextra** helper functions and visualisations. Are the results markedly different? Which clustering approach do you wish to proceed with --- i.e., `pam()`, `hclust()` or `kmeans()`?

5. Describe the patterns that you observe at the end of your ordination and final cluster selection (i.e. based on the optimal number of clusters and whichever cluster technique you deem most appropriate). How does South Africa fare in terms of attaining SDGs? Contrast with some key countries of your choice to make your points. Label the key countries that you refer to in your text by updating the code accordingly. Continue to explain these patterns in terms of the global socio-political/socio-economic landscape. Provide a discourse about possible explanations for the patterns observed globally and regionally.

<!-- ::: callout-important -->
<!-- ## Submission instructions -->

<!-- Submit a Quarto HTML document wherein you provide answers to Questions 1--5 by the deadline in the syllabus schedule. -->

<!-- Provide a **neat and thoroughly annotated** Quarto/html files which outlines the graphs and all calculations and which displays the resultant distance matrix. Use separate tabs for the different questions. -->

<!-- Please label the Quarto and resulting HTML files as follows: -->

<!-- -   `BCB743_<first_name>_<last_name>_Task_D.qmd`, and -->

<!-- -   `BCB743_<first_name>_<last_name>_Task_D.html` -->

<!-- (the `<` and `>` must be omitted as they are used in the example as field indicators only). -->

<!-- Failing to follow these instructions carefully, precisely, and thoroughly will cause you to lose marks, which could cause a significant drop in your score as formatting counts for 15% of the final mark (out of 100%). -->

<!-- Submit your Labs to me by email. -->
<!-- ::: -->

## Assessment Criteria

This Task is not formally assessed.
