{
  "hash": "a3354f578020bd26152482f03510538a",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"BCB744 Final Exam\"\ndate: \"2026-04-26\"\nlang: en-GB\nexecute: \n  cache: false\n  warning: false\n  eval: true\nparams: \n  hide_answers: false\nformat:\n  html:\n    code-tools: false\n    embed-resources: true\n    fig-format: png\n    number-sections: false\n---\n\n\n\n# Exam Guidelines\n\n## Date and Exam Duration\n\nThe Biostatistics Exam will start at 8:00 on 26 April and you have until 14:00 on 27 April, 2026, to complete it. This exam may be conducted anywhere in the world, and it will contribute 40% of the final assessment marks for the BCB744 module.\n\n## Student Guidelines\n\n* **Convert Quarto to HTML:** Submit your assignment as an HTML file, derived from a Quarto document. Ensure your submission is a *thoroughly annotated report*, complete with meta-information (name, date, purpose, etc.) at the beginning. Each section/test should be accompanied by detailed explanations of its purpose.\n\n* [**Required YAML Structure:**]{.my-highlight} Your Quarto document must begin with the following YAML header (fill in your own details where indicated):\n\n  ````yaml\n  ---\n  title: \"BCB744 Biostatistics Exam\"\n  author: \"Your Name\"\n  date: \"2026-04-26\"\n  format:\n    html:\n      embed-resources: true\n      toc: false\n      number-sections: false\n  ---\n  ````\n\n  Your document should follow this hierarchical structure:\n\n  ````markdown\n  # Part A\n\n  ## Question 1\n\n  ### Preamble\n  ### Introduction\n  ### Methods\n  ### Results\n  ### Discussion\n\n  ## Question 2\n\n  ### Preamble\n  ### Introduction\n  ### Methods\n  ### Results\n  ### Discussion\n\n  [... continue for remaining questions ...]\n\n  # Part B\n\n  ## Task 1\n\n  ## Task 2\n  ### 2.1\n  ### 2.2\n  ### 2.3\n\n  [... continue for remaining tasks ...]\n\n  # References\n  ````\n\n* **Testing Assumptions:** For all questions necessitating formal inferential statistics, conduct and document the appropriate preliminary tests to check statistical assumptions. This includes stating the assumptions, detailing the procedures for testing these assumptions, and specifying the null hypotheses ($H_{0}$). If assumptions are tested graphically, elucidate the rationale behind the graphical method. Discuss the outcomes of these assumption tests and provide a rationale for the chosen inferential statistical tests (e.g., *t*-test, ANOVA).\n\n* **State Hypotheses:** When inferential statistics are employed, clearly articulate the null ($H_{0}$) and alternative ($H_{A}$) hypotheses. Later, in the results section, remember to state whether the $H_{0}$ or $H_{A}$ is accepted or rejected.\n\n* **Graphical Support:** Support all descriptive and inferential statistical analyses with appropriate graphical representations of the data.\n\n* **Presentation Format:** Structure each answer as a concise mini-paper, including the sections Introduction, Methods, Results, Discussion, and References. Though each answer is expected to span 2-3 pages, there are no strict page limits. [Does not apply to questions marked with an *]\n\n    * Incorporate a **Preamble** section before the Introduction to detail preliminary analyses, figures, tables, and other relevant background information that doesn't fit into the main narrative of your paper. This section provides insight into the preparatory work and will not be considered part of the main evaluation.\n    \n    * The **Introduction** should set the stage by offering background information, establishing the relevance of the study, and clearly stating the research question or hypothesis. \n    \n    * The **Methods** section must specify the statistical methodologies applied, including how assumptions were tested and any additional data analyses performed. Emphasise the inferential statistics without delving into exploratory data analysis (EDA). \n    \n    * In the **Results** section, focus solely on the findings pertinent to the hypotheses introduced in the Introduction. While assumption tests are part of the statistical analysis, they need not be highlighted in this section as that is what the 'Preamble' section is for. Ensure that figure and/or table captions are informative and self-explanatory.\n    \n    * The **Discussion** section is for interpreting the results, considering their significance, limitations, and implications, and suggesting avenues for future research. You may reference up to five pertinent studies in the Methods and Discussion sections. \n    \n    * End with a consolidated **References** section, listing all sources cited across the questions.\n\n* **Formatting:** Presentation matters. Marks are allocated for the visual quality of the submission. This includes the neatness of the document, proper use of headings, and adherence to coding conventions (e.g., spacing).\n\n## Assessor Guidelines (applies to all questions/tasks)\n\n- Assess good document structure according to logical headings and heading hierarchies.\n- Heavily penalise untidy formatting, excessive output of long, unnecessary data printouts (other than the obvious and required used of `head()`, `tail()`, `glimpse()`, and `summary()`) that serve no purpose [-15%].\n- Answers where the code gives error messages (it fails to run to provide the required output) get 0 for that question.\n- Where students write long-form text feedback/answers within code blocks, where it should have been more appropriately placed within the markdown text between code blocks and presented in full sentences, should be penalised [-10% for each question where this occurs].\n- Text answers written as bullet points and which lacks detailed explanatory power gets penalised [-10%].\n- Untidy presentation and formatting that fails to resemble my model answers (below) penalised [-15%].\n\n## Exam Structure\n\nThe exam is comprised of two parts, **Part A** and **Part B**. They contribute 0.35 and 0.65 to the exam mark, respectively.\n\n## Data Access\n\n[Some datasets are included with R packages, and the remaining data files may be found at the [Google Drive link](https://drive.google.com/drive/folders/1ZAIk6LvmmKxVgGYf1vtnVpQ__Bv17dOB?usp=sharing).]{.my-highlight}\n\n# Part A (0.35)\n\n## Question 1: Effects of Mercury-Contaminated Fish Consumption on Chromosomes\n\n### Dataset Overview\n\nThe dataset `mercuryfish`, available in the R package **coin**, comprises measurements of mercury levels in blood, and proportions of cells exhibiting abnormalities and chromosome aberrations. These data are collected from individuals who consume mercury-contaminated fish and a control group with no such exposure. For detailed attributes and dataset structure, refer to the dataset's documentation within the package.\n\n### Objectives\n\nYour analysis should aim to address the following research questions:\n\na. **Impact of Methyl-Mercury:** Is the consumption of fish containing methyl-mercury associated with an increased proportion of cellular abnormalities?\n\nb. **Mercury Concentration and Cellular Abnormalities:** How does the concentration of mercury in the blood affect the proportion of cells with abnormalities? Moreover, is there a difference in this relationship between the control group and those exposed to mercury?\n\nc. **Relationship Between Variables:** Does a relationship exist between the proportion of abnormal cells (`abnormal`) and the proportion of cells with chromosome aberrations (`ccells`)? This analysis should be conducted separately for the control and exposed groups to identify any disparities.\n\n\n**Answer**\n\na. **Impact of Methyl-Mercury**\n\n\nLoad the mercuryfish dataset\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(coin)\ndata(mercuryfish)\nmercuryfish\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     group mercury abnormal ccells\n1  control     5.3      8.6    2.7\n2  control    15.0      5.0    0.5\n3  control    11.0      8.4    0.0\n4  control     5.8      1.0    0.0\n5  control    17.0     13.0    5.0\n6  control     7.0      5.0    0.0\n7  control     8.5      1.0    0.0\n8  control     9.4      2.3    1.3\n9  control     7.8      2.0    0.0\n10 control    12.0      6.4    1.8\n11 control     8.7      7.0    0.0\n12 control     4.0      1.7    0.0\n13 control     3.0      4.0    1.0\n14 control    12.2      1.8    1.8\n15 control     6.1      2.8    0.0\n16 control    10.2      4.7    3.1\n17 exposed   100.0      6.4    0.7\n18 exposed    70.0      9.2    4.6\n19 exposed   196.0      3.6    0.0\n20 exposed    69.0      3.7    1.7\n21 exposed   370.0     14.2    5.2\n22 exposed   270.0      7.0    0.0\n23 exposed   150.0     13.5    5.0\n24 exposed    60.0     21.5    9.5\n25 exposed   330.0      9.0    2.0\n26 exposed  1100.0     11.0    3.0\n27 exposed    40.0      8.0    1.0\n28 exposed   100.0      9.2    3.5\n29 exposed    70.0      8.0    2.0\n30 exposed   150.0     14.0    5.0\n31 exposed   200.0     11.9    5.5\n32 exposed   304.0     10.0    2.0\n33 exposed   236.0      6.6    3.0\n34 exposed   178.0     13.0    4.0\n35 exposed    41.0      0.0    0.0\n36 exposed   120.0      6.0    2.0\n37 exposed   330.0     13.1    2.2\n38 exposed    62.0      0.0    0.0\n39 exposed    12.8      5.3    2.0\n```\n\n\n:::\n:::\n\n\n  \nCheck the structure of the dataset\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(mercuryfish)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    group mercury abnormal ccells\n1 control     5.3      8.6    2.7\n2 control    15.0      5.0    0.5\n3 control    11.0      8.4    0.0\n4 control     5.8      1.0    0.0\n5 control    17.0     13.0    5.0\n6 control     7.0      5.0    0.0\n```\n\n\n:::\n:::\n\n\nEDA: Boxplot of the proportion of abnormal cells by group\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(mercuryfish, aes(x = group, y = abnormal)) +\n  geom_boxplot(notch = TRUE) +\n  labs(\n    title = \"Proportion of Abnormal Cells by Group\",\n    x = \"Group\",\n    y = \"Proportion of Abnormal Cells\"\n  )\n```\n\n::: {.cell-output-display}\n![](BCB744_Final_Prac_Exam_2026_files/figure-html/unnamed-chunk-3-1.png)\n:::\n:::\n\n\nAbove se see that the exposed group has a higher proportion of abnormal cells (the notches do not overlap between the two groups) Let's test this formally...\n\n\nTest normality of the data within the groups Shapiro-Wilk test H0: The distribution of my data does not differ from a normal distribution Ha: The distribution of my data differs from a normal distribution\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshapiro.test(mercuryfish$abnormal[mercuryfish$group == \"control\"])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  mercuryfish$abnormal[mercuryfish$group == \"control\"]\nW = 0.90267, p-value = 0.0887\n```\n\n\n:::\n\n```{.r .cell-code}\nshapiro.test(mercuryfish$abnormal[mercuryfish$group == \"exposed\"])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  mercuryfish$abnormal[mercuryfish$group == \"exposed\"]\nW = 0.96841, p-value = 0.6509\n```\n\n\n:::\n:::\n\n\nAbove we see that we can accept the assumption of normality for both groups\n\n\nWhat about homogeneity of variances?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmercuryfish |>\n  group_by(group) |>\n  summarise(sample_var = var(abnormal))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  group   sample_var\n  <fct>        <dbl>\n1 control       11.2\n2 exposed       24.3\n```\n\n\n:::\n:::\n\n\nWe see that the variances are more-or-less the same for the two groups\n\n\nWe could do a Levene's test to confirm this Levene's test H0: The variances of the groups are equal Ha: The variances of the groups are not equal\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncar::leveneTest(abnormal ~ group, data = mercuryfish)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLevene's Test for Homogeneity of Variance (center = median)\n      Df F value Pr(>F)\ngroup  1  1.6607 0.2055\n      37               \n```\n\n\n:::\n:::\n\n\nAbove we see that we accept the H0 that states that the variances are equal The data are normally distributed and variances are equal and we can proceed with a Student's t-test\n\n\nConduct a Student's t-test to compare the proportion of abnormal cells between the two groups\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(abnormal ~ group, var.equal = TRUE, data = mercuryfish)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tTwo Sample t-test\n\ndata:  abnormal by group\nt = -2.9664, df = 37, p-value = 0.005253\nalternative hypothesis: true difference in means between group control and group exposed is not equal to 0\n95 percent confidence interval:\n -7.084765 -1.334257\nsample estimates:\nmean in group control mean in group exposed \n             4.668750              8.878261 \n```\n\n\n:::\n:::\n\n\nThe p-value is less than 0.05, indicating a significant difference in the proportion of abnormal cells between the control and exposed groups\n\n\nb. **Mercury Concentration and Cellular Abnormalities**\n\nEDA: Scatterplot of mercury concentration vs. proportion of abnormal cells\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(mercuryfish, aes(x = mercury, y = abnormal, color = group)) +\n  geom_point() +\n  geom_smooth(method = \"lm\", se = TRUE) +\n  labs(\n    title = \"Mercury Concentration vs. Proportion of Abnormal Cells\",\n    x = \"Mercury Concentration\",\n    y = \"Proportion of Abnormal Cells\"\n  )\n```\n\n::: {.cell-output-display}\n![](BCB744_Final_Prac_Exam_2026_files/figure-html/unnamed-chunk-8-1.png)\n:::\n:::\n\n\nTest normality of the data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshapiro.test(mercuryfish$mercury[mercuryfish$group == \"control\"])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  mercuryfish$mercury[mercuryfish$group == \"control\"]\nW = 0.97435, p-value = 0.9032\n```\n\n\n:::\n\n```{.r .cell-code}\nshapiro.test(mercuryfish$mercury[mercuryfish$group == \"exposed\"])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  mercuryfish$mercury[mercuryfish$group == \"exposed\"]\nW = 0.64984, p-value = 3.341e-06\n```\n\n\n:::\n:::\n\n\nWe see that the mercury concentrations are normally distributed for the control group (we do not reject H0) but not for the exposed group (we reject H0); earlier we have seen that the response variable (abnormalities) is normal for both the control and the exposed groups\n\n\nBut since we want to model a linear relationship, now is not quite the right time to do the tests for normality -- we want to do this for the residuals of the model (that is, we fit the model first, and then test the residuals for normality)\n\n\nWe also see from the scatterplot that the data might be approximately linear for the exposed group, but not for the control group where the data are more scattered around very low mercury concentrations near zero\n\n\nWe also see from the very wide confidence intervals that the model is not very good at predicting the proportion of abnormal cells from mercury concentration in the blood in the exposed group; my guess is that there will not be a linear relationship between mercury concentration and the proportion of abnormal cells in the control or exposed groups\n\n\nWe can proceed with a linear regression model to assess the relationship\n\n\nFit a linear regression model to assess the relationship between mercury concentration and the proportion of abnormal cells H0(1): There is no relationship between mercury concentration and the proportion of abnormal cells Ha(1): There is a relationship between mercury concentration and the proportion of abnormal cells H0(2): The relationship between mercury concentration and the proportion of abnormal cells does not differ between the control and exposed groups Ha(2): The relationship between mercury concentration and the proportion of abnormal cells differs between the control and exposed groups\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel.lm <- lm(abnormal ~ mercury + group, data = mercuryfish)\nsummary(model.lm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = abnormal ~ mercury + group, data = mercuryfish)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-8.1709 -2.5884 -0.2124  2.6725 13.3395 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  4.622336   1.081910   4.272 0.000135 ***\nmercury      0.005193   0.004129   1.258 0.216575    \ngroupexposed 3.226585   1.610348   2.004 0.052677 .  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 4.325 on 36 degrees of freedom\nMultiple R-squared:  0.2261,\tAdjusted R-squared:  0.1832 \nF-statistic:  5.26 on 2 and 36 DF,  p-value: 0.009906\n```\n\n\n:::\n:::\n\n\nWe can now check the residuals for normality in the two groups which will confirm that the model is appropriate (or not)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmercuryfish$residuals <- residuals(model.lm)\nshapiro.test(mercuryfish$residuals[mercuryfish$group == \"control\"])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  mercuryfish$residuals[mercuryfish$group == \"control\"]\nW = 0.90326, p-value = 0.09066\n```\n\n\n:::\n\n```{.r .cell-code}\nshapiro.test(mercuryfish$residuals[mercuryfish$group == \"exposed\"])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  mercuryfish$residuals[mercuryfish$group == \"exposed\"]\nW = 0.94985, p-value = 0.2905\n```\n\n\n:::\n:::\n\n\nWe see that the residuals are normally distributed for both groups and hence using a linear model was appropriate\n\n\nThe p-value for the interaction term not less than 0.05, indicating that the relationship between mercury concentration and the proportion of abnormal cells does not differ between the control and exposed groups -- we can reject Ha(1) and Ha(2) If we wanted to (recommended), we could refit the model without the interaction term\n\n\nWe could also do an ANCOVA instead of the linear model to test the interaction term\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel.aov <- aov(abnormal ~ group * mercury, data = mercuryfish)\nsummary(model.aov)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              Df Sum Sq Mean Sq F value  Pr(>F)   \ngroup          1  167.2  167.20   9.246 0.00445 **\nmercury        1   29.6   29.59   1.636 0.20924   \ngroup:mercury  1   40.5   40.47   2.238 0.14361   \nResiduals     35  633.0   18.08                   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nWhat do we conclude? The proportion of abnormal cells differs significantly between the control and exposed groups, with the exposed group exhibiting a higher proportion of abnormal cells. However, the relationship between mercury concentration and the proportion of abnormal cells does not differ between the two groups. There is a good amount of scatter in the amount of cell abnormalities even in just the control group, which suggests that mercury concentration alone may not be a strong predictor of cellular abnormalities. Increasing the amount of mercury in the blood does not necessarily lead to a linear increase but it certainly does account for a few of the highest values seen in the exposed group.\n\n\nc. **Relationship Between Variables**\n\nEDA: Scatterplot of proportion of abnormal cells vs. chromosome cell proportion\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(mercuryfish, aes(x = abnormal, y = ccells, color = group)) +\n  geom_point() +\n  geom_smooth(method = \"lm\", se = TRUE) +\n  labs(\n    title = \"Abnormal Cell Proportion vs. Chromosome Cell Proportion by Group\",\n    x = \"Proportion of Abnormal Cells\",\n    y = \"Proportion of Cells with Chromosome Aberrations\"\n  )\n```\n\n::: {.cell-output-display}\n![](BCB744_Final_Prac_Exam_2026_files/figure-html/unnamed-chunk-13-1.png)\n:::\n:::\n\n\nWe see that there is a clear linear relationship between abnormal cell proportion and Cu cell proportion in both groups, and the confidence intervals are narrow(-ish), indicating that the model could be reasonably good at predicting Cu cell proportion from the proportion of abnormal cells\n\n\nWe know the relationship between continuous covariates is linear and may therefore proceed with a linear regression model; the remaining assumptions will be tested afterwards\n\n\nFit a linear regression model to assess the relationship between the proportion of Cu cells and the proportion of abnormal cells H0(1): There is no relationship between the proportion of Cu cells and the proportion of abnormal cells Ha(1): There is a relationship between the proportion of Cu cells and the proportion of abnormal cells H0(2): The relationship between the proportion of Cu cells and the proportion of abnormal cells does not differ between the control and exposed groups Ha(2): The relationship between the proportion of Cu cells and the proportion of abnormal cells differs between the control and exposed groups\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel.lm2 <- lm(ccells ~ abnormal + group, data = mercuryfish)\nsummary(model.lm2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = ccells ~ abnormal + group, data = mercuryfish)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-2.4760 -0.7479  0.1761  0.5831  2.0133 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  -0.67797    0.36166  -1.875    0.069 .  \nabnormal      0.37547    0.04461   8.417 5.01e-10 ***\ngroupexposed  0.12272    0.42837   0.286    0.776    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.183 on 36 degrees of freedom\nMultiple R-squared:  0.7152,\tAdjusted R-squared:  0.6994 \nF-statistic: 45.21 on 2 and 36 DF,  p-value: 1.516e-10\n```\n\n\n:::\n:::\n\n\nWe can now check the residuals for normality in the two groups which will confirm that the model is appropriate (or not)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmercuryfish$residuals2 <- residuals(model.lm2)\nshapiro.test(mercuryfish$residuals2[mercuryfish$group == \"control\"])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  mercuryfish$residuals2[mercuryfish$group == \"control\"]\nW = 0.95476, p-value = 0.5686\n```\n\n\n:::\n\n```{.r .cell-code}\nshapiro.test(mercuryfish$residuals2[mercuryfish$group == \"exposed\"])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  mercuryfish$residuals2[mercuryfish$group == \"exposed\"]\nW = 0.96346, p-value = 0.5366\n```\n\n\n:::\n:::\n\n\nWe see that the residuals are normally distributed for both groups and hence using a linear model was appropriate\n\n\nThe p-value 'abnormal' term is less than 0.05, indicating that the relationship between the proportion of abnormal cells and the proportion of Cu cells is significant -- we accept Ha(1) The p-value for the interaction term is not less than 0.05, indicating that the relationship between the proportion of abnormal cells and the proportion of Cu cells does not differ between the control and exposed groups -- we do not reject H0(2)\n\n\nWhat do we conclude? The proportion of Cu cells is significantly related to the proportion of abnormal cells, with a higher proportion of abnormal cells corresponding to a higher proportion of Cu cells. This relationship does not differ between the control and exposed groups. The model is appropriate for predicting the proportion of Cu cells from the proportion of abnormal cells, as the residuals are normally distributed for both groups.\n\n\nAlternative approaches for assigning marks: Instead of doing a linear regression with interaction term, which I did not formally teach, equally justified are individual linear regressions for each group and using the confidence intervals to make inferences. This would involve fitting two linear regression models, one for each group, and comparing the confidence intervals of the coefficients to determine if the relationship between the proportion of Cu cells and the proportion of abnormal cells differs between the two groups. This would apply to all the other questions as well.\n\n\nOr, in part (c), we could have done correlations for each group and compared the correlation coefficients to determine if the relationship between the proportion of abnormal cells and the proportion of Cu cells differs between the two groups.\n\n\n\n\n## Question 2: Malignant Glioma Pilot Study\n\n### Dataset Introduction\n\nThe `glioma` dataset, found within the **coin** R package, originates from a pilot study focusing on patients with malignant glioma who underwent pretargeted adjuvant radioimmunotherapy using yttrium-90-biotin. This dataset includes variables such as patient sex, treatment group, age, histology (tissue study), and survival time.\n\n### Objectives\n\nThis analysis aims to investigate the following aspects:\n\na. **Sex and Group Interaction on Survival Time:** Determine whether there is an interaction between patient sex and treatment group that significantly impacts the survival time (`time`).\n\nb. **Age and Histology Interaction on Survival Time:** Assess if age and histology interact in a way that influences the survival time of patients.\n\nc. **Comprehensive Data Exploration:** Conduct an exhaustive graphical examination of the dataset to uncover any additional patterns or relationships that merit statistical investigation. Identify the most compelling and insightful observation, formulate a relevant hypothesis, and perform the appropriate statistical analysis.\n\n\n**Answer**\n\na. **Sex and Group Interaction on Survival Time**\n\nLoad the glioma dataset\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(glioma, package = \"coin\")\n```\n:::\n\n\nCheck the structure of the dataset\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(glioma)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n'data.frame':\t37 obs. of  7 variables:\n $ no.      : int  1 2 3 4 5 6 7 8 9 10 ...\n $ age      : int  41 45 48 54 40 31 53 49 36 52 ...\n $ sex      : Factor w/ 2 levels \"Female\",\"Male\": 1 1 2 2 1 2 2 2 2 2 ...\n $ histology: Factor w/ 2 levels \"GBM\",\"Grade3\": 2 2 2 2 2 2 2 2 2 2 ...\n $ group    : Factor w/ 2 levels \"Control\",\"RIT\": 2 2 2 2 2 2 2 2 2 2 ...\n $ event    : logi  TRUE FALSE FALSE FALSE FALSE TRUE ...\n $ time     : int  53 28 69 58 54 25 51 61 57 57 ...\n```\n\n\n:::\n:::\n\n\nSummary statistics\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(glioma)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      no.              age            sex      histology      group   \n Min.   : 1.000   Min.   :19.00   Female:16   GBM   :20   Control:18  \n 1st Qu.: 5.000   1st Qu.:40.00   Male  :21   Grade3:17   RIT    :19  \n Median :10.000   Median :47.00                                       \n Mean   : 9.757   Mean   :48.49                                       \n 3rd Qu.:14.000   3rd Qu.:57.00                                       \n Max.   :19.000   Max.   :83.00                                       \n   event              time      \n Mode :logical   Min.   : 5.00  \n FALSE:14        1st Qu.:13.00  \n TRUE :23        Median :28.00  \n                 Mean   :30.84  \n                 3rd Qu.:50.00  \n                 Max.   :69.00  \n```\n\n\n:::\n:::\n\n\nEDA: Boxplot of survival\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(glioma, aes(x = group, y = time)) +\n  geom_boxplot(notch = FALSE, aes(colour = sex)) +\n  labs(title = \"Survival Time by Group\", x = \"Group\", y = \"Months\")\n```\n\n::: {.cell-output-display}\n![](BCB744_Final_Prac_Exam_2026_files/figure-html/unnamed-chunk-19-1.png)\n:::\n:::\n\n\nThere does seem to be an effect of group on survival time, with the radioimmunotherapy group having a higher median survival time than the control group A sex-related effect does not seem present\n\n\nLooking at the box and whisker plot, there seems to be an issue with the assumption of normality. Let's test the normality of the data using the Shapiro-Wilk test:\n\n\nShapiro-Wilk test for normality H0: The data are normally distributed Ha: The data are not normally distributed (separate hypotheses for sex and group)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshapiro.test(glioma$time[glioma$group == \"Control\"])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  glioma$time[glioma$group == \"Control\"]\nW = 0.80087, p-value = 0.001563\n```\n\n\n:::\n\n```{.r .cell-code}\nshapiro.test(glioma$time[glioma$group == \"RIT\"])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  glioma$time[glioma$group == \"RIT\"]\nW = 0.92571, p-value = 0.1443\n```\n\n\n:::\n\n```{.r .cell-code}\nshapiro.test(glioma$time[glioma$sex == \"Female\"])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  glioma$time[glioma$sex == \"Female\"]\nW = 0.87292, p-value = 0.03016\n```\n\n\n:::\n\n```{.r .cell-code}\nshapiro.test(glioma$time[glioma$sex == \"Male\"])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  glioma$time[glioma$sex == \"Male\"]\nW = 0.90727, p-value = 0.04852\n```\n\n\n:::\n:::\n\n\nThe p-values are less than 0.05 for the control group and for both sexes, indicating that the data are not normally distributed. We will use non-parametric tests to compare the survival times between the two groups within the factors.\n\n\nWe must also check the homogeneity of variances using Levene's test: H0: The variances are equal Ha: The variances are not equal\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncar::leveneTest(time ~ group, data = glioma)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLevene's Test for Homogeneity of Variance (center = median)\n      Df F value Pr(>F)\ngroup  1  1.5274 0.2247\n      35               \n```\n\n\n:::\n\n```{.r .cell-code}\ncar::leveneTest(time ~ sex, data = glioma)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLevene's Test for Homogeneity of Variance (center = median)\n      Df F value Pr(>F)\ngroup  1  0.0069 0.9344\n      35               \n```\n\n\n:::\n:::\n\n\nVariances are the same everywhere; nevertheless, due to the non-normal data, we will have to use a non-parametric test.\n\n\nWe will check for differences between groups formally using the Kruskal-Wallis test:\n\n\nKruskal-Wallis test H0: The medians of the groups are equal Ha: At least one median is different (to be stated separately for group and sex)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkruskal.test(time ~ group, data = glioma)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tKruskal-Wallis rank sum test\n\ndata:  time by group\nKruskal-Wallis chi-squared = 16.123, df = 1, p-value = 5.936e-05\n```\n\n\n:::\n\n```{.r .cell-code}\nkruskal.test(time ~ sex, data = glioma)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tKruskal-Wallis rank sum test\n\ndata:  time by sex\nKruskal-Wallis chi-squared = 0.54251, df = 1, p-value = 0.4614\n```\n\n\n:::\n:::\n\n\nThe p-value is less than 0.05, indicating that there is a significant difference in survival time between the two groups. We reject the null hypothesis and conclude that the medians of the groups are not equal, but we do not reject the H0 for sex differences.\n\n\nWe cannot do a formal stats test to look for significant interaction terms between sex and group due to the non-normality of the data (i.e. there is not non-parametric equivalent for a two-way ANOVA); However, we can simply look at the box-and-whisker plot: there does not seem to be a significant interaction as the response is the same regardless of sex within each group.\n\n\nb. **Age and Histology Interaction on Survival Time**\n\nEDA: Line/scatterplot of survival by histology and age\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(glioma, aes(x = age, y = time)) +\n  geom_point(aes(colour = histology)) +\n  geom_smooth(method = \"lm\", se = TRUE, aes(colour = histology)) +\n  labs(\n    title = \"Survival Time by Histology and Age\",\n    x = \"Age (Years)\",\n    y = \"Survival time (Months)\"\n  )\n```\n\n::: {.cell-output-display}\n![](BCB744_Final_Prac_Exam_2026_files/figure-html/unnamed-chunk-23-1.png)\n:::\n:::\n\n\nThere does not seem to be a clear effect of age on survival time within each histology group. Notice the wide confidence intervals at the starts and ends of the age range for each histology group: the starts and ends overlap within each group suggesting a statistically insignificant effect of age\n\n\nWe can test formally with a linear model:\n\n\nLinear model H0: There is no interaction between age and histology Ha: There is an interaction between age and histology\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel.lm <- lm(time ~ age * histology, data = glioma)\nsummary(model.lm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = time ~ age * histology, data = glioma)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-37.830 -10.163  -1.397  10.392  37.274 \n\nCoefficients:\n                    Estimate Std. Error t value Pr(>|t|)   \n(Intercept)          38.2531    13.7074   2.791  0.00867 **\nage                  -0.3516     0.2461  -1.429  0.16239   \nhistologyGrade3      -3.2009    20.5856  -0.155  0.87738   \nage:histologyGrade3   0.5739     0.4308   1.332  0.19194   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 15.48 on 33 degrees of freedom\nMultiple R-squared:  0.4464,\tAdjusted R-squared:  0.396 \nF-statistic: 8.869 on 3 and 33 DF,  p-value: 0.0001877\n```\n\n\n:::\n:::\n\n\nBefore we can interpret the linear model fit, we must check that the lm is indeed suited to the data. We can do this by checking the residuals:\n\n\nResiduals vs Fitted plot\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(model.lm, which = 1)\n```\n\n::: {.cell-output-display}\n![](BCB744_Final_Prac_Exam_2026_files/figure-html/unnamed-chunk-25-1.png)\n:::\n:::\n\n\nOr you could check normality of residuals with a QQ plot:\n\n\nNormal Q-Q plot\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqqnorm(model.lm$residuals)\n```\n\n::: {.cell-output-display}\n![](BCB744_Final_Prac_Exam_2026_files/figure-html/unnamed-chunk-26-1.png)\n:::\n:::\n\n\nOr you could check for homogeneity of variances with a residuals vs fitted plot:\n\n\nResiduals vs Fitted plot\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(model.lm, which = 3)\n```\n\n::: {.cell-output-display}\n![](BCB744_Final_Prac_Exam_2026_files/figure-html/unnamed-chunk-27-1.png)\n:::\n:::\n\n\nOr simply assess the normality of the residuals with a Shapiro-Wilk test:\n\n\nShapiro-Wilk test for normality\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglioma$residuals <- model.lm$residuals\n\nshapiro.test(glioma$residuals[glioma$group == \"RIT\"])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  glioma$residuals[glioma$group == \"RIT\"]\nW = 0.93321, p-value = 0.1984\n```\n\n\n:::\n\n```{.r .cell-code}\nshapiro.test(glioma$residuals[glioma$group == \"Control\"])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  glioma$residuals[glioma$group == \"Control\"]\nW = 0.90444, p-value = 0.0687\n```\n\n\n:::\n:::\n\n\nOkay, residuals are normal according to most tests above.\n\n\nThe interaction term is not significant, indicating that there is no interaction between age and histology on survival time.\n\n\nWe will use the Kruskal-Wallis test to compare survival times between the different histology groups:\n\n\nKruskal-Wallis test H0: The medians of the histology groups are equal Ha: At least one median is different\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkruskal.test(time ~ histology, data = glioma)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tKruskal-Wallis rank sum test\n\ndata:  time by histology\nKruskal-Wallis chi-squared = 13.74, df = 1, p-value = 0.0002099\n```\n\n\n:::\n:::\n\n\nThe p-value is less than 0.05, indicating that there is a significant difference in survival time between the histology groups. We reject the null hypothesis and conclude that the medians of the histology groups are not equal.\n\n\nWe cannot do a formal stats test to look for significant interaction terms between age and histology due to the non-normality of the data; However, we can simply look at the box-and-whisker plot: there does not seem to be a significant interaction as the response is the same regardless of age within each histology group.\n\n\nOr we can test with an ANCOVA instead of the linear model above (start first with the assumption of normality and variances within the histology groups -- Levene's test and Shapiro-Wilk's test)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel.aov1 <- aov(time ~ histology * age, data = glioma)\nsummary(model.aov1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              Df Sum Sq Mean Sq F value   Pr(>F)    \nhistology      1   5795    5795  24.169 2.36e-05 ***\nage            1    159     159   0.662    0.422    \nhistology:age  1    425     425   1.775    0.192    \nResiduals     33   7912     240                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nThe outcome is the same as the linear model above: there is no interaction between age and histology on survival time.\n\n\nc. **Comprehensive Data Exploration**\n\n\n\n\n## Question 3: Risk Factors Associated with Low Infant Birth Mass\n\n### Dataset Introduction\n\nPackage **MASS**, dataset `birthwt`: This dataframe has 189 rows and 10 columns. The data were collected at Baystate Medical Center, Springfield, Mass. during 1986.\n\n### Objectives\n\nState three hypotheses and test them. Make sure one of the tests makes use of the 95% confidence interval approach rather than a formal inferential methodology.\n\n\n**Answer**\nLoad the birthwt dataset\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(MASS)\nlibrary(dplyr)\ndata(birthwt)\n```\n:::\n\n\nCheck the structure of the dataset\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(birthwt)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n'data.frame':\t189 obs. of  10 variables:\n $ low  : int  0 0 0 0 0 0 0 0 0 0 ...\n $ age  : int  19 33 20 21 18 21 22 17 29 26 ...\n $ lwt  : int  182 155 105 108 107 124 118 103 123 113 ...\n $ race : int  2 3 1 1 1 3 1 3 1 1 ...\n $ smoke: int  0 0 1 1 1 0 0 0 1 1 ...\n $ ptl  : int  0 0 0 0 0 0 0 0 0 0 ...\n $ ht   : int  0 0 0 0 0 0 0 0 0 0 ...\n $ ui   : int  1 0 0 1 1 0 0 0 0 0 ...\n $ ftv  : int  0 3 1 2 0 0 1 1 1 0 ...\n $ bwt  : int  2523 2551 2557 2594 2600 2622 2637 2637 2663 2665 ...\n```\n\n\n:::\n:::\n\n\n\n\n## Question 4: The Lung Capacity Data*\n\n### Objectives\n\na. Using the Lung Capacity data provided, please calculate the 95% CIs for the `LungCap` variable as a function of:\n\n    i. `Gender`\n    \n    ii. `Smoke`\n    \n    iii. `Caesarean`\n    \nb. Create a graph of the mean ± 95% CIs and determine if there are statistical differences in `LungCap` between the levels of `Gender`, `Smoke`, and `Caesarean`. Do the same using a *t*-test. Are your findings the same using these two approaches?\n\nc. Produce all the associated tests for assumptions -- i.e. the assumptions to be met when deciding whether to use a *t*-test or its non-parametric counterpart.\n\nd. Create a combined tidy dataframe (observe tidy principles) with the estimates for the 95% CI for the `LungCap` data (`LungCap` as a function of `Gender`), estimated using both the traditional and bootstrapping approaches. Create a plot comprising two panels (one for the traditional estimates, one for the bootstrapped estimates) of the mean, median, scatter of raw data points, and the upper and lower 95% CI.\n\ne. Undertake a statistical analysis that factors in the effect of `Age` together with one of the categorical variables on `LungCap`. What new insight does this provide?\n\n## Question 5: Piglet Data\n\n### Objectives\n\nHere are some fictitious data for pigs raised on different diets (make up an equally fictitious justification for the data and develop hypotheses around that):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfeed_1 <- c(60.8, 57.0, 65.0, 58.6, 61.7)\nfeed_2 <- c(68.7, 67.7, 74.0, 66.3, 69.8)\nfeed_3 <- c(102.6, 102.1, 100.2, 96.5, 110.3)\nfeed_4 <- c(87.9, 84.2, 83.1, 85.7, 90.3)\n\nbacon <- data.frame(cbind(feed_1, feed_2, feed_3, feed_4))\n```\n:::\n\n\n## Question 6: Investigating the Impact of Biochar on Crop Growth and Nutritional Value\n\n### Dataset Introduction\n\nIn this analysis, we will explore the effects of biochar application on the growth and elemental composition of four key crops: carrot, lettuce, soybean, and sweetcorn. The dataset for this study is sourced from the US Environmental Protection Agency (EPA) and is available at [EPA's Biochar Dataset](https://catalog.data.gov/dataset/biochar-4-crops). To gain a comprehensive understanding of the dataset and its implications, it is highly recommended to review two pertinent research papers linked on the dataset page. These papers not only provide valuable background information on the studies conducted but also offer critical insights and methodologies for data analysis that may be beneficial for this project.\n\n### Research Goals\n\nThe primary aim of this project is to analyse the impact of biochar on plant yield and identify the three most significant nutrients that influence human health. Your task is to:\n\na. Determine whether biochar treatments vary in effectiveness across the different crops.\nb. Provide evidence-based recommendations on how to tailor biochar application for each specific crop to optimise the production of nutrients beneficial to human health and achieve the best possible yield.\n\nIn the Introduction section, it is important to justify the selection of the three nutrients you will focus on, explaining their importance to human nutrition. Through detailed data analysis, this project seeks to offer actionable insights on biochar application strategies that enhance both the nutritional value and the biomass of the crops by the end of their growth period.\n\n## Question 7: Miscellaneous*\n\n### Objectives\n\na. For each line of the script, below, write an English explanation for what the code does.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(points, aes(x = group, y = count)) +\n  geom_boxplot(aes(colour = group), size = 1, outlier.colour = NA) +\n  geom_point(position = position_jitter(width = 0.2), alpha = 0.3) +\n  facet_grid(group ~ ., scales = \"free\") +\n  labs(x = \"\", y = \"Number of data points\") +\n  theme(\n    legend.position = \"none\",\n    strip.background = element_blank(),\n    strip.text = element_blank()\n  )\n```\n:::\n\n\nb. Using the `rnorm()` function, generate some fictitious data that can be plotted using the code, above. Make sure to assemble these data into a dataframe suitable for plotting, complete with correct column titles.\n\nc. Apply the code *exactly as stated* to the data to demonstrate your understanding of the code and convince the examiner of your understanding of the correct data structure.\n\n---\n\n# Part B (0.65)\n\n## Assessment Criteria\n\nYour responses to Part B will be evaluated based on the following criteria:\n\n1. **Technical Accuracy (50%)**\n   - Correct application of data analyses and statistical methods. Statistical tests should address the hypotheses within what was taught in this module. The assessor recognises that students will not have access to the level of statistical knowledge and experience a research statistician might have. For example, in places, linear mixed models might be more suited to the questions, but students only were taught the basics about ANOVA and simple linear model (relatively simple designs). When non-parametric alternatives are required, I'll assign marks to the any statement that suggests the correct test to use, but not actually marks the execution of those tests.\n   - Use of appropriate R packages, functions, and syntax (code style and liberal commenting)\n   - Appropriate choice and justification of techniques, including due consideration for the assumptions of the methods used\n   - Accurate calculations and results interpretation, down to small details such as how many decimal places to use\n\n2. **Depth of Analysis (20%)**\n   - Comprehensive exploration of the problem\n   - Insightful interpretation of results\n   - Consideration of shortfalls in the analysis (due to data limitations, assumptions, etc.), and suggestions for improvement\n   - Application of out-of-the-box thinking to the problem\n\n3. **Clarity and Communication (20%)**\n   - Logical organisation of ideas, including clear section headings and subheadings\n   - Clear and concise explanations at each stage of the analysis\n   - Effective use of publication quality visualisations where appropriate, including all necessary annotations\n   - Communication of results in a way that is appropriate for a scientific audience (e.g. a journal article)\n\n4. **Critical Thinking Shown in Final Conclusion/Synopsis (10%)**\n   - Discussion of the findings in the context of the problem (add ecological context, etc., as you deem necessary)\n   - Identification of limitations\n   - Discussion of assumptions\n   - Consideration of broader implications\n\n[The marks indicated for each task reflect the relative weight and expected depth of your response. Focus on demonstrating both technical proficiency and conceptual understanding in your answers.]{.my-highlight}\n\n## Background\n\nThese data represent the aerial cover of kelp canopy in South Africa, as measured by Landsat satellites, for the period 1984 to 2024 at a quarterly interval. The intention is to understand the spatio-temporal patterns in kelp canopy cover and to explore how these patterns may be related to coastal sections and biogeographical provinces.\n\nYou are provided with the following files at the Google Drive link emailed to you:\n\n1.\tA table of 58 coastal sections (`58_sections.csv`) that partitions the South African coastline into approximately 50 km intervals. Each section is defined by a single coordinate point (latitude, longitude) representing the boundary of the section.\n2. A table of the biogeographical provinces (`bioregions.csv`) that the 58 coastal sections fall within. There is one row for each of the 58 sections. For this exercise, the biogeographical classification by Professor John Bolton is of interest.\n3.\tA netCDF file (`kelpCanopyFromLandsat_SouthAfrica_v04.nc`). The netCDF file contains satellite-derived measurements of kelp canopy area across the South African coastline from 1984 to 2024, sampled quarterly. Each observation corresponds to a grid cell at a specific time point.\n\n### Task 1: Initial Processing \n\n- **[Task Weight: 10%]**\n- **[Components (1) and (2) marked on a 0–100 scale, then scaled to equal proportions of the Task Weight of 10%]**\n\n1. Read the kelp canopy area, time, location (latitude/longitude), and satellite pass data from the NetCDF file. Once unpacked, it contains over 5 million rows. Your processing workflow will include:\n  - extracting data from the netCDF file where `area` and `passes` are variables defined over 3D space (`longitude`, `latitude`, and `time`); and\n  - using functions such as `tidync::hyper_tibble()` or `ncdf4::ncvar_get()` to read these values.\n  \n\n\n**Answer**\n\n***Note to assessor:*** Students may have used any of a number of NetCDF targeted packages, such as **tidync**, **stars**, or **terra**. Below I use **ncdf4**.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(ncdf4)\nlibrary(geosphere)\nlibrary(mgcv)\n\nnc_path <- here::here(\"data\", \"BCB744\", \"Kelpwatch\", \"\")\nnc_file <- paste0(nc_path, \"kelpCanopyFromLandsat_SouthAfrica_v04.nc\")\nnc <- nc_open(nc_file)\n\narea <- ncvar_get(nc, \"area\")\ntime <- ncvar_get(nc, \"time\")\nyear <- ncvar_get(nc, \"year\")\nquarter <- ncvar_get(nc, \"quarter\")\nlatitude <- ncvar_get(nc, \"latitude\")\nlongitude <- ncvar_get(nc, \"longitude\")\npasses <- ncvar_get(nc, \"passes\")\n\nnc_close(nc)\n```\n:::\n\n\n\nPOSIX timestamps rather than raw seconds:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntime <- as.POSIXct(time, origin = \"1970-01-01\", tz = \"UTC\")\n```\n:::\n\n\n\nCreate index vectors:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntime_idx <- seq_along(time) # 1…ntime\nloc_idx <- seq_along(latitude) # 1…nloc\n```\n:::\n\n\n\n\n2. Restructure the data into a data.table or data.frame:\n  - the data should have six columns: `longitude`, `latitude`, `year`, `quarter`, `area`, and `passes`;\n  - each row should correspond to a unique pixel in space-time (i.e., one location at one time point); and\n  - note that the `time` variable in the netCDF file is in numeric format (e.g., days since origin, where `origin = \"1970-01-01\"`), so you'll have to convert it to POSIX timestamps using appropriate tools (e.g., `as.POSIXct()`).\n\nIf you are unable to read the NetCDF file, you may request access to a processed version of this file (in long CSV format) from me, but you'll be penalised by 10% if you do so.\n\n\n**Answer**\n\n***Note to assessor:*** Find some evidence for the successful execution of the above instructions such as the presence of the required dataframe columns, correct conversion of the time variable, and so on.\n\nCartesian join of (`time_idx` × `loc_idx`), in an order that matches how `as.vector()` will flatten a $nloc × ntime$ matrix. Then, add the flattened area and the six columns and select the required variables and make a long:\n\nCreate Cartesian product of indices\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlong_df <- crossing(\n  time_idx = time_idx,\n  loc_idx = loc_idx\n) |>\n  mutate(\n    area = as.vector(area),\n    time = time[time_idx],\n    year = year[time_idx],\n    quarter = quarter[time_idx],\n    latitude = latitude[loc_idx],\n    longitude = longitude[loc_idx],\n    passes = passes[loc_idx]\n  ) |>\n  dplyr::select(area, time, year, quarter, latitude, longitude, passes)\n\nsummary(long_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      area              time                          year         quarter     \n Min.   :  0.0     Min.   :1984-04-01 00:00:00   Min.   :1984   Min.   :1.000  \n 1st Qu.:  0.0     1st Qu.:1996-01-01 00:00:00   1st Qu.:1996   1st Qu.:1.000  \n Median :  0.0     Median :2005-07-01 00:00:00   Median :2005   Median :2.000  \n Mean   :190.3     Mean   :2005-05-24 09:13:06   Mean   :2005   Mean   :2.477  \n 3rd Qu.:324.0     3rd Qu.:2015-01-01 00:00:00   3rd Qu.:2015   3rd Qu.:3.000  \n Max.   :900.0     Max.   :2024-04-01 00:00:00   Max.   :2024   Max.   :4.000  \n NA's   :1061652                                                               \n    latitude        longitude         passes     \n Min.   :-34.83   Min.   :14.83   Min.   :0.000  \n 1st Qu.:-34.66   1st Qu.:18.12   1st Qu.:1.000  \n Median :-34.35   Median :18.48   Median :1.000  \n Mean   :-33.42   Mean   :18.55   Mean   :1.399  \n 3rd Qu.:-32.98   3rd Qu.:19.40   3rd Qu.:2.000  \n Max.   :-25.44   Max.   :19.97   Max.   :4.000  \n                                                 \n```\n\n\n:::\n:::\n\n\n\n\n### Task 2: Exploratory Data Analysis\n\n- **[Task Weight: 10%]**\n- **[Tasks 2.1, 2.2, and 2.3, each marked on a 0–100 scale, then scaled to equal proportions of the Task Weight of 10%]**\n\n#### 2.1 Weighted Mean Time Series\n\n1. For each `year` and `quarter` combination:\n  - compute the weighted mean of the kelp canopy `area` across all locations, using the number of satellite `passes` as weights;\n  - exclude observations where `passes = 0` or `area` is `NA`; and\n  - plot the resulting time series of weighted mean kelp area, using i) `quarters` on the x-axis, and ii) a continuous `time` index from 1984–2024.\n\n\n**Answer**\n\n***Note to assessor:***  If the student produced the figure exactly as I have it below, this question can get full marks. Else, assess the analysis workflow and assign marks in accordance with the portions of the script that are correctly executed.\n\n\nFilter out missing values and zero passes at the start\n\n\n::: {.cell}\n\n```{.r .cell-code}\nquarter_means <- long_df |>\n  filter(!is.na(area), !is.na(passes)) |>\n  group_by(year, quarter) |>\n  summarise(\n    weighted_area = weighted.mean(area, w = passes, na.rm = TRUE),\n    .groups = \"drop\"\n  ) |>\n  filter(!is.na(weighted_area))\n\nsummary(quarter_means)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      year         quarter      weighted_area  \n Min.   :1984   Min.   :1.000   Min.   :  0.0  \n 1st Qu.:1996   1st Qu.:1.000   1st Qu.:145.8  \n Median :2005   Median :2.000   Median :186.0  \n Mean   :2005   Mean   :2.477   Mean   :185.1  \n 3rd Qu.:2014   3rd Qu.:3.000   3rd Qu.:232.1  \n Max.   :2024   Max.   :4.000   Max.   :321.2  \n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n:::\n\n\nFilter out invalid observations\n\n\n::: {.cell}\n\n```{.r .cell-code}\nquarter_means <- long_df |>\n  filter(!is.na(area), !is.na(passes), passes > 0) |>\n  group_by(year, quarter) |>\n  summarise(\n    weighted_area = weighted.mean(area, w = passes, na.rm = TRUE),\n    .groups = \"drop\"\n  ) |>\n  filter(!is.na(weighted_area)) |>\n  mutate(\n    quarter = as.integer(quarter),\n    time_index = year + (quarter - 1) / 4\n  )\n```\n:::\n\n\nPlot quarterly weighted mean time series\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(quarter_means, aes(x = time_index, y = weighted_area)) +\n  geom_line(color = \"steelblue\", size = 0.8) +\n  geom_point(color = \"black\", size = 0.6) +\n  labs(\n    title = \"Quarterly Weighted Mean Kelp Area (1984–2024)\",\n    x = \"Year (quarterly intervals)\",\n    y = \"Weighted Mean Canopy Area (m²)\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](BCB744_Final_Prac_Exam_2026_files/figure-html/unnamed-chunk-38-1.png){width=60%}\n:::\n:::\n\n\n\n\n2. Compute the weighted mean `area` at each unique (`longitude`, `latitude`) pixel across `time`. Then:\n  - select a random sample of 100 pixels;\n  - for each sampled pixel, extract the full time series of weighted mean area;\n  - plot all 100 time series in a single panel (overlayed), using semi-transparent lines; and\n  - label axes appropriately.\n\n\n**Answer**\n\n***Note to assessor:*** Again, if they produced the figure exactly as below, this question can get full marks. Else, assess the analysis workflow and assign marks in accordance with the portions of the script that are correctly executed.\n\n\n::: {.cell layout-align=\"center}\"}\n\n```{.r .cell-code}\npixel_means <- long_df |>\n  filter(!is.na(area), !is.na(passes), passes > 0) |>\n  group_by(year, quarter, longitude, latitude) |>\n  summarise(\n    weighted_area = weighted.mean(area, w = passes, na.rm = TRUE),\n    .groups = \"drop\"\n  )\n\nsummary(pixel_means)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      year         quarter        longitude        latitude     \n Min.   :1984   Min.   :1.000   Min.   :15.08   Min.   :-34.83  \n 1st Qu.:1997   1st Qu.:2.000   1st Qu.:18.33   1st Qu.:-34.67  \n Median :2006   Median :3.000   Median :18.84   Median :-34.36  \n Mean   :2006   Mean   :2.503   Mean   :18.64   Mean   :-33.62  \n 3rd Qu.:2016   3rd Qu.:3.000   3rd Qu.:19.41   3rd Qu.:-33.95  \n Max.   :2024   Max.   :4.000   Max.   :19.97   Max.   :-26.48  \n weighted_area  \n Min.   :  0.0  \n 1st Qu.:  0.0  \n Median :  0.0  \n Mean   :196.1  \n 3rd Qu.:360.0  \n Max.   :900.0  \n```\n\n\n:::\n:::\n\n\nStep 1: Calculate weighted mean per pixel over time\n\n\n::: {.cell}\n\n```{.r .cell-code}\npixel_means <- long_df |>\n  filter(!is.na(area), !is.na(passes), passes > 0) |>\n  group_by(year, quarter, longitude, latitude) |>\n  summarise(\n    weighted_area = weighted.mean(area, w = passes, na.rm = TRUE),\n    .groups = \"drop\"\n  ) |>\n  mutate(time_index = year + (quarter - 1) / 4)\n```\n:::\n\n\nStep 2: Identify 100 unique (lon, lat) pairs\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(42)\nsample_pixels <- pixel_means |>\n  distinct(longitude, latitude) |>\n  sample_n(100)\n```\n:::\n\n\nStep 3: Filter time series for the sampled pixels\n\n\n::: {.cell}\n\n```{.r .cell-code}\npixel_timeseries_sample <- pixel_means |>\n  inner_join(sample_pixels, by = c(\"longitude\", \"latitude\"))\n```\n:::\n\n\nStep 4: Plot all 100 pixel time series\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(\n  pixel_timeseries_sample,\n  aes(\n    x = time_index,\n    y = weighted_area,\n    group = interaction(longitude, latitude)\n  )\n) +\n  geom_line(alpha = 0.3, color = \"darkorange\") +\n  labs(\n    title = \"Kelp Area Time Series for 100 Random Pixels\",\n    x = \"Year (quarterly intervals)\",\n    y = \"Weighted Mean Canopy Area (m²)\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](BCB744_Final_Prac_Exam_2026_files/figure-html/unnamed-chunk-42-1.png){width=60%}\n:::\n:::\n\n\nThis figure is uninterpretable...\n\n\n\n#### 2.2 Summary Statistics\n\n1. Using the weighted data prepared for each `year` and `quarter` combination (prepared in 2.1.1), compute and report summary statistics for the levels of temporal aggregation:\n\t- by `year`;\n\t- by `quarter`;\n\t- by `year/quarter` combination;\n  - include: weighted mean, median, standard deviation, interquartile range, skewness, and kurtosis; and\n  - comment on the appropriateness of each statistic for these data, and justify your choices in light of the data distribution.\n\n\n**Answer**\n\n***Note to assessor:*** Since this question can be objectively assessed relative to the expectations (specific reporting of correct summary stats per each level of aggregation as I have them below), marks can simply be assigned based on the correct reporting of the summary statistics.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(e1071) # for skewness and kurtosis\n```\n:::\n\n\nYearly aggregation\n\n\n::: {.cell}\n\n```{.r .cell-code}\nyear_stats <- quarter_means |>\n  group_by(year) |>\n  summarise(\n    mean = mean(weighted_area, na.rm = TRUE),\n    median = median(weighted_area, na.rm = TRUE),\n    sd = sd(weighted_area, na.rm = TRUE),\n    iqr = IQR(weighted_area, na.rm = TRUE),\n    skew = skewness(weighted_area, na.rm = TRUE),\n    kurt = kurtosis(weighted_area, na.rm = TRUE)\n  )\nyear_stats\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 41 × 7\n        year  mean median    sd   iqr     skew   kurt\n   <int[1d]> <dbl>  <dbl> <dbl> <dbl>    <dbl>  <dbl>\n 1      1984  54.1   13.6  81.2  73.2   0.375   -2.33\n 2      1985  77.4   77.4 101.   71.4   0       -2.75\n 3      1986 146.   146.   NA     0   NaN      NaN   \n 4      1987  66.3   66.3  NA     0   NaN      NaN   \n 5      1988 133.   133.  188.  133.    0       -2.75\n 6      1989 108.    96.3  79.7  91.8   0.250   -2.04\n 7      1990 171.   173.   41.1  31.5  -0.0806  -1.89\n 8      1991 178.   185.   43.8  50.2  -0.272   -2.03\n 9      1992 213.   240.  124.  152.   -0.329   -2.05\n10      1993 131.   135.   42.8  41.1  -0.191   -1.95\n# ℹ 31 more rows\n```\n\n\n:::\n:::\n\n\nQuarterly aggregation (across all years)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nquarter_stats <- quarter_means |>\n  group_by(quarter) |>\n  summarise(\n    mean = mean(weighted_area, na.rm = TRUE),\n    median = median(weighted_area, na.rm = TRUE),\n    sd = sd(weighted_area, na.rm = TRUE),\n    iqr = IQR(weighted_area, na.rm = TRUE),\n    skew = skewness(weighted_area, na.rm = TRUE),\n    kurt = kurtosis(weighted_area, na.rm = TRUE)\n  )\nquarter_stats\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 7\n  quarter  mean median    sd   iqr   skew    kurt\n    <int> <dbl>  <dbl> <dbl> <dbl>  <dbl>   <dbl>\n1       1  216.   220.  66.6  83.4 -0.898  0.922 \n2       2  185.   204.  74.2 114.  -0.361 -0.598 \n3       3  172.   179.  71.2  85.6 -0.326 -0.0222\n4       4  166.   166.  49.7  46.2  0.177  1.32  \n```\n\n\n:::\n:::\n\n\nYear-quarter combination (already in quarter_means)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nyear_quarter_stats <- quarter_means |>\n  mutate(year_quarter = paste0(year, \" Q\", quarter)) |>\n  summarise(\n    mean = mean(weighted_area, na.rm = TRUE),\n    median = median(weighted_area, na.rm = TRUE),\n    sd = sd(weighted_area, na.rm = TRUE),\n    iqr = IQR(weighted_area, na.rm = TRUE),\n    skew = skewness(weighted_area, na.rm = TRUE),\n    kurt = kurtosis(weighted_area, na.rm = TRUE)\n  )\nyear_quarter_stats\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 6\n   mean median    sd   iqr   skew     kurt\n  <dbl>  <dbl> <dbl> <dbl>  <dbl>    <dbl>\n1  185.   186.  68.3  86.2 -0.323 -0.00284\n```\n\n\n:::\n:::\n\n\n\n\n2. Create visualisations (e.g. boxplots, violin plots, histograms) to support your interpretations.\n\n\n**Answer**\n\n***Note to assessor:*** These or similar figures are required, showing the seasonal effects, the annual effect, a histogram of the frequency of the weighted areas, and something similar to the density distribution (or a frequency histogram) that shows distribution within a quarter. I'd also accept variations of these plots, as long as they speak to the nature of the data being assessed. They need to capture the feature of the summary statistics that I have above.\n\n\nBoxplot by quarter\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(quarter_means, aes(x = factor(quarter), y = weighted_area)) +\n  geom_boxplot(fill = \"lightblue\") +\n  labs(\n    title = \"Kelp Canopy Area by Quarter\",\n    x = \"Quarter\",\n    y = \"Weighted Area\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](BCB744_Final_Prac_Exam_2026_files/figure-html/unnamed-chunk-46-1.png){width=60%}\n:::\n:::\n\n\nBoxplot by year\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(quarter_means, aes(x = factor(year), y = weighted_area)) +\n  geom_boxplot(fill = \"lightgreen\") +\n  labs(title = \"Kelp Canopy Area by Year\", x = \"Year\", y = \"Weighted Area\") +\n  theme_minimal() +\n  theme(axis.text.x = element_text(angle = 90, hjust = 1))\n```\n\n::: {.cell-output-display}\n![](BCB744_Final_Prac_Exam_2026_files/figure-html/unnamed-chunk-47-1.png){width=60%}\n:::\n:::\n\n\nHistogram of all weighted areas\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(quarter_means, aes(x = weighted_area)) +\n  geom_histogram(bins = 30, fill = \"tan\", color = \"black\") +\n  labs(\n    title = \"Histogram of Weighted Kelp Area\",\n    x = \"Weighted Area\",\n    y = \"Frequency\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](BCB744_Final_Prac_Exam_2026_files/figure-html/unnamed-chunk-48-1.png){width=60%}\n:::\n:::\n\n\nDensity plot by quarter\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(quarter_means, aes(x = weighted_area, color = factor(quarter))) +\n  geom_density() +\n  labs(\n    title = \"Density of Weighted Area by Quarter\",\n    x = \"Weighted Area\",\n    color = \"Quarter\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](BCB744_Final_Prac_Exam_2026_files/figure-html/unnamed-chunk-49-1.png){width=60%}\n:::\n:::\n\n\n\n\n3. Based on these, discuss any discernible temporal trends (e.g. decadal increases/decreases) and seasonal patterns (quarterly effects).\n\n\n**Answer**\n\n***Note to assessor:*** Some variation of this:\n\nTemporal variation in kelp canopy area, as observed in the quarterly weighted means from 1984 to 2024, exhibits a broadly increasing trend until the early-2000s, followed by more irregular fluctuations at a higher weighted canopy area than at the start of the time series. The yearly summary statistics confirm this, and show rising means and medians through the late 1990s into the early 2000s, peaking during the 2010s. Although values for some early years (e.g., 1986, 1987) suffer from missing data (e.g., NA for SD and skewness), the central decades present coherent patterns.\n\nThe skewness values tend to hover close to zero, with mild left-skew in later years, suggesting distributions that are not heavily distorted but do include more frequent lower outliers in certain quarters. The kurtosis estimates, consistently below 0 across many years, indicate relatively flat distributions with light tails, again pointing to the presence of moderate, widespread values and a paucity of extreme outliers in the tails.\n\nThe quarterly summaries reveal a seasonal signal: Q1 (January–March) is associated with the highest mean kelp area (216 km²), while Q4 (October–December) shows the lowest (166 km²). This likely reflects seasonal growth dynamics, perhaps linked to photoperiod, wave exposure, or nutrient regimes (factors known to modulate canopy) forming macroalgae. The density plot by quarter reinforces this picture: Q1’s density curve is skewed leftward, indicative of a modal concentration around high values, whereas Q4 shows more compact distributions with lower peaks.\n\nThe boxplots by year reinforce this temporal variation. Inter-annual variation is relatively low during some periods (e.g., 1990s) but expands considerably in the 2010s and 2020s, suggesting a greater degree of spatial heterogeneity or more frequent episodes of extreme coverage. Notably, the increase in spread does not always correspond with a decline in median or mean area, implying that while certain coastal sectors may experience loss, others persist or expand.\n\nThe histogram of weighted area suggests a right-skewed global distribution when pooled over time, driven by many instances of low or zero canopy and fewer but notable high-coverage events.\n\nSo, these patterns suggest:\n\n- A long-term trend toward increased kelp canopy extent over the study period, potentially stabilising or fragmenting in recent years;\n- Clear intra-annual (seasonal) variation, with Q1 consistently supporting greater canopy development than later quarters;\n- Increasing variability over time, which might reflect changing climate regimes, hydrodynamic forcing, or anthropogenic disturbance gradients.\n\nThese findings provide a strong descriptive foundation for the inferential modelling that follows.\n\n\n#### 2.3 Observation Density Map\n\nCreate a map plotting each observed pixel location (defined by `longitude` × `latitude`):\n\n- colour each pixel by the total number of valid observations (i.e., non-NA values of `area`) across all `time` points;\n- overlay the 58 coastal sections as reference points or lines, numbered from west (1) to east (58); and\n- use an appropriate geographic projection and include a legend.\n\n\n**Answer**\n\n***Note to assessor:*** I'm not concerned too much about having a coastline as the data clearly show the coastal profile, but, of course, having the coastline as well is great too (maybe worth a mark or three extra). I'd also be okay if the figure focuses only on sections 1-22 where kelp is present. Again, this is a fairly objective question, so marks can be assigned based on the correct figure (full marks for all the labels, etc., correctly applied as per standards of scientific publications).\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(ggrepel) # for labelling points\nlibrary(viridis) # for color scale\n```\n:::\n\n\nLoad the long_df and coastal sections Assume long_df has already been created from earlier tasks Load the 58 sections file (replace with actual path if needed)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsections_df <- read.csv(here::here(\n  \"data\",\n  \"BCB744\",\n  \"Kelpwatch\",\n  \"58_sections.csv\"\n))\n```\n:::\n\n\n1. Count valid observations per pixel\n\n\n::: {.cell}\n\n```{.r .cell-code}\nobs_counts <- long_df |>\n  filter(!is.na(area)) |>\n  group_by(longitude, latitude) |>\n  summarise(\n    n_obs = n(),\n    .groups = \"drop\"\n  )\n```\n:::\n\n\n2. Prepare coastal sections data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsections <- sections_df |>\n  mutate(section_id = row_number())\n```\n:::\n\n\n3. Plot\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot() +\n  geom_point(\n    data = obs_counts,\n    shape = 4,\n    aes(x = longitude, y = latitude, colour = n_obs)\n  ) +\n  scale_colour_viridis(name = \"Valid\\nObs.\", option = \"plasma\") +\n  geom_point(\n    data = sections,\n    color = \"black\",\n    size = 1.1,\n    shape = 1,\n    aes(x = Longitude, y = Latitude)\n  ) +\n  geom_text_repel(\n    data = sections,\n    size = 2,\n    color = \"black\",\n    max.overlaps = 58,\n    aes(x = Longitude, y = Latitude, label = section_id)\n  ) +\n  coord_fixed(1.3) +\n  labs(\n    title = \"Observation Density Map\",\n    subtitle = \"Total no. valid kelp area obs. per pixel (1984–2024)\",\n    x = \"Longitude\",\n    y = \"Latitude\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](BCB744_Final_Prac_Exam_2026_files/figure-html/unnamed-chunk-53-1.png){width=60%}\n:::\n:::\n\n\n\n\n\n### Task 3: Assigning Kelp Observations to Coastal Sections\n\n- **[Task Weight: 20%]**\n- **[Tasks 4.1 and 4.2 each marked on a 0–100 scale, then scaled in the proportion 0.7 and 0.3 of the Task Weight of 20%]**\n\nUsing the data prepared above, your task now is to spatially classify each kelp canopy observation by assigning it to two types of geographic units.\n\n#### 3.1 Assignment to Coastal Sections\n\nYou are provided with a table of 58 coastal sections, each defined by a single geographic coordinate (`Latitude` and `Longitude`). These points mark successive ~50 km intervals along the South African coastline, numbered from west (1) to east (58).\n\nAssign each kelp canopy observation to the nearest coastal section based on geographic proximity:\n\n- use a geodesic (great-circle) distance metric to compute proximity between kelp sampling points and section coordinates (assume all coordinates are in WGS84);\n- add a new column to your kelp dataset called `section_id`, indicating the row number (1–58) of the nearest section; and\n- you may use any R packages or methods you like, but your code should be efficient and well-commented.\n\n\n\n**Answer**\n\n***Note to assessor:*** Check for objective evidence that a dataframe has been created and that it has the correct columns, i.e., `section_id` or `section`, `longitude`, `latitude`, `year`, `quarter`, and `area` or `weighted_area`. Calculations must show evidence of using the Haversine distance metric.\n\nI use only the relevant sections:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsections_df <- sections_df |>\n  slice(1:22) # no Ecklonia further east of section 22\n```\n:::\n\n\n\nPrepare a script for sectioning the kelp data:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprocessed_file_path <- here::here(\n  \"data\",\n  \"BCB744\",\n  \"Kelpwatch\",\n  \"pixel_means.RData\"\n)\n\nif (file.exists(processed_file_path)) {\n  message(\"Loading pre-processed pixel_means from: \", processed_file_path)\n  load(processed_file_path)\n  message(\"Successfully loaded pixel_means with sections.\")\n} else {\n  message(\"Processing and assigning sections to pixel_means...\")\n}\n```\n:::\n\n\nCheck if the processed file exists and load it\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (file.exists(processed_file_path)) {\n  message(\"Loading pre-processed pixel_means from: \", processed_file_path)\n  load(processed_file_path)\n  message(\"Successfully loaded pixel_means with sections.\")\n} else {\n  message(\"Processing and assigning sections to pixel_means...\")\n\n  # Create section assignments\n  section_coords_matrix <- as.matrix(sections_df[, c(\"Longitude\", \"Latitude\")])\n\n  find_closest_section_idx <- function(kelp_lon, kelp_lat, all_section_coords) {\n    if (is.na(kelp_lon) || is.na(kelp_lat)) {\n      return(NA_integer_)\n    }\n    current_kelp_coord <- c(kelp_lon, kelp_lat)\n    distances <- distHaversine(p1 = current_kelp_coord, p2 = all_section_coords)\n    return(which.min(distances))\n  }\n\n  # Apply the function to each kelp data point\n  assigned_section_indices <- mapply(\n    find_closest_section_idx,\n    kelp_lon = pixel_means$longitude,\n    kelp_lat = pixel_means$latitude,\n    MoreArgs = list(\n      all_section_coords = section_coords_matrix\n    ),\n    SIMPLIFY = TRUE\n  )\n\n  # Add section column to pixel_means\n  # pixel_means2[, section := assigned_section_indices]\n  pixel_means$section <- assigned_section_indices\n\n  # Ensure the data directory exists\n  if (!dir.exists(dirname(processed_file_path))) {\n    dir.create(dirname(processed_file_path), recursive = TRUE)\n  }\n\n  # Save the processed data\n  save(pixel_means, file = processed_file_path)\n  message(\"Processing complete. Data saved to: \", processed_file_path)\n}\n\nhead(pixel_means)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 7\n       year   quarter longitude  latitude weighted_area time_index section\n  <int[1d]> <int[1d]> <dbl[1d]> <dbl[1d]>         <dbl>  <dbl[1d]>   <int>\n1      1984         2      15.1     -26.6             0      1984.       1\n2      1984         2      15.1     -26.6             0      1984.       1\n3      1984         2      15.1     -26.6             0      1984.       1\n4      1984         2      15.1     -26.6             0      1984.       1\n5      1984         2      15.1     -26.6             0      1984.       1\n6      1984         2      15.1     -26.6             0      1984.       1\n```\n\n\n:::\n:::\n\n\n\n\n\n#### 3.2 Assignment to Biogeographical Provinces\n\nYou are also provided with a table that maps each coastal section (1–58) to a biogeographical province, based on a classification by Professor John Bolton.\n\n- Using your previous assignment of each kelp observation to a `section_id`, add a second column called `bioregion_id` that indicates which biogeographical province the observation falls within.\n- Your final kelp dataset should contain the following key columns (alongside the original data):\n  - `longitude`, `latitude`\n  - `year`, `quarter`, `area`, `passes`\n  - `section_id` (integer 1–58)\n  - `bioregion_id` (character or factor)\n- Include your full, annotated R code that performs both spatial assignments into your resultant .html document. Your method should be reproducible, and your code should be easy to follow. Print the `head()` and `tail()` of your final dataset, and include a `summary()` of the data.\n\n\n\n**Answer**\n\n***Note to assessor:*** Check for objective evidence that a dataframe has been created and that it has the correct columns, i.e., `section_id` or `section`, `longitude`, `latitude`, `year`, `quarter`, `area` or `weighted_area`, and also `bioregion` or `bolton` or some unique identifier for the bioregion.\n\nI used a simple merge to assign bioregions to the kelp data, but there are other ways to do it. Again, we want objective evidence that the data have been assigned correctly (e.g. the `head()` and `tail()` of the data, or a `summary()`).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbioreg <- read.csv(here::here(\n  \"data\",\n  \"BCB744\",\n  \"Kelpwatch\",\n  \"bioregions.csv\"\n)) |>\n  mutate(section = row_number()) # Make rownames explicit as 'section'\n```\n:::\n\n\nMerge into pixel_means (assumed already loaded in environment)\n\n\n::: {.cell}\n\n```{.r .cell-code}\npixel_means <- pixel_means |>\n  left_join(bioreg, by = \"section\") |>\n  dplyr::select(-spal.prov, -spal.ecoreg, -lombard)\n```\n:::\n\n\nThe question asks for passes to be present in the data, but I'm okay with omitting it as it is included in the weighted area calculation\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(pixel_means)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 8\n       year   quarter longitude latitude weighted_area time_index section bolton\n  <int[1d]> <int[1d]> <dbl[1d]> <dbl[1d>         <dbl>  <dbl[1d]>   <int> <chr> \n1      1984         2      15.1    -26.6             0      1984.       1 BMP   \n2      1984         2      15.1    -26.6             0      1984.       1 BMP   \n3      1984         2      15.1    -26.6             0      1984.       1 BMP   \n4      1984         2      15.1    -26.6             0      1984.       1 BMP   \n5      1984         2      15.1    -26.6             0      1984.       1 BMP   \n6      1984         2      15.1    -26.6             0      1984.       1 BMP   \n```\n\n\n:::\n\n```{.r .cell-code}\ntail(pixel_means)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 8\n       year   quarter longitude latitude weighted_area time_index section bolton\n  <int[1d]> <int[1d]> <dbl[1d]> <dbl[1d>         <dbl>  <dbl[1d]>   <int> <chr> \n1      2024         2      20.0    -34.8             0      2024.      22 AMP   \n2      2024         2      20.0    -34.8             0      2024.      22 AMP   \n3      2024         2      20.0    -34.8             0      2024.      22 AMP   \n4      2024         2      20.0    -34.8             0      2024.      22 AMP   \n5      2024         2      20.0    -34.8             0      2024.      22 AMP   \n6      2024         2      20.0    -34.8             0      2024.      22 AMP   \n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(pixel_means)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      year         quarter        longitude        latitude     \n Min.   :1984   Min.   :1.000   Min.   :15.08   Min.   :-34.83  \n 1st Qu.:1997   1st Qu.:2.000   1st Qu.:18.33   1st Qu.:-34.67  \n Median :2006   Median :3.000   Median :18.84   Median :-34.36  \n Mean   :2006   Mean   :2.503   Mean   :18.64   Mean   :-33.62  \n 3rd Qu.:2016   3rd Qu.:3.000   3rd Qu.:19.41   3rd Qu.:-33.95  \n Max.   :2024   Max.   :4.000   Max.   :19.97   Max.   :-26.48  \n weighted_area     time_index      section         bolton         \n Min.   :  0.0   Min.   :1984   Min.   : 1.00   Length:5446570    \n 1st Qu.:  0.0   1st Qu.:1998   1st Qu.:15.00   Class :character  \n Median :  0.0   Median :2007   Median :19.00   Mode  :character  \n Mean   :196.1   Mean   :2007   Mean   :15.82                     \n 3rd Qu.:360.0   3rd Qu.:2016   3rd Qu.:20.00                     \n Max.   :900.0   Max.   :2024   Max.   :22.00                     \n```\n\n\n:::\n:::\n\n\n\n\n### Task 4: Inferential Statistics (Part 2)\n\n- **[Task Weight: 30%]**\n- **[Tasks 5.1, 5.2, 5.3, 5.4, and 5.5 each marked on a 0–100 scale, then scaled to equal proportions of the Task Weight of 30%]**\n\nYou are now asked to evaluate a series of research questions concerning the spatial and temporal structure of kelp canopy area. These questions are to be answered using the kelp dataset that has already been processed to include both `section_id` and `bioregion_id`. Use the weighted kelp canopy area (area, weighted by passes) as your response variable throughout -- you should have already prepared this dataset in Task 2.\n\nYou may use ANOVAs and/or linear models. In each case you must clearly state your hypotheses, justify your choice of model, and interpret your findings both statistically and ecologically.\n\n#### 4.1 Spatial Differences Between Coastal Sections\n\nQuestion: Is there a statistically significant difference in mean kelp canopy area between coastal sections?\n\n\n**Answer**\n\n***Note to Assessor (applies to Questions 5.1–5.5):*** It is understood that students are not expected to possess the depth of statistical training characteristic of professional statisticians. While some questions may, in principle, warrant more advanced treatments (e.g. linear mixed-effects models), the scope of instruction in this module was limited to foundational techniques—namely, simple linear models and ANOVA for relatively straightforward designs. **If students applied LMEs or other more complicated models without demonstrating a clear understanding for why they did so, give them zero percent for that answer.** Where assumptions of parametric tests are violated, students should identify suitable non-parametric alternatives. Marks will be awarded for correctly identifying such alternatives, even if these tests are not implemented in code. \n\nHypotheses:\n\n- Null (H₀): There is no difference in mean kelp canopy area across coastal sections.\n- Alternative (H₁): Mean kelp canopy area differs among at least one pair of coastal sections.\n\nJustification: A one-way ANOVA is appropriate for testing whether the means of a continuous response variable (kelp area) differ across the levels of a single categorical factor (coastal section).\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(lmtest)\nlibrary(car)\n```\n:::\n\n\nSet section and bioreg as a factor as this is needed for the tests that will assess the section and bioreg effects\n\n\n::: {.cell}\n\n```{.r .cell-code}\npixel_means <- pixel_means |>\n  mutate(section = as.factor(section), bolton = as.factor(bolton))\n\nmodel_5.1 <- aov(weighted_area ~ section, data = pixel_means)\nsummary(model_5.1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 Df    Sum Sq   Mean Sq F value Pr(>F)    \nsection          18 2.020e+10 1.122e+09   13252 <2e-16 ***\nResiduals   5446551 4.612e+11 8.467e+04                   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nAlso test assumptions... Residuals\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresid_5.1 <- sample(residuals(model_5.1), 5000)\n```\n:::\n\n\nNormality\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshapiro.test(resid_5.1) # Subsample for tractability\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  resid_5.1\nW = 0.80962, p-value < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\nqqnorm(resid_5.1)\nqqline(resid_5.1)\n```\n\n::: {.cell-output-display}\n![](BCB744_Final_Prac_Exam_2026_files/figure-html/unnamed-chunk-59-1.png){width=60%}\n:::\n:::\n\n\nHomogeneity of variances\n\n\n::: {.cell}\n\n```{.r .cell-code}\nleveneTest(weighted_area ~ section, data = pixel_means)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLevene's Test for Homogeneity of Variance (center = median)\n           Df F value    Pr(>F)    \ngroup      18   14154 < 2.2e-16 ***\n      5446551                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nResiduals vs fitted\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(model_5.1, which = 1)\n```\n\n::: {.cell-output-display}\n![](BCB744_Final_Prac_Exam_2026_files/figure-html/unnamed-chunk-61-1.png){width=60%}\n:::\n:::\n\n\n\nOne could do a TukeyHSD test, but the question did not explicitly ask for this. Add two marks if correctly given and executed.\n\n***Results***\nMean kelp canopy area varied significantly across the 19 coastal sections assessed (F${18,5446551}$ = 13,252, *p* < 0.001; one-way ANOVA). Residual diagnostics indicated substantial departures from normality (Shapiro–Wilk *W* = 0.81, *p* < 0.001) and non-constant variance across groups (Levene’s test: F${18,5446551}$ = 14,154, *p* < 0.001), though the extremely large sample size renders the ANOVA robust to these violations. The fitted model accounted for a substantial proportion of the spatial variance in kelp canopy area. Residual plots suggested heteroscedasticity consistent with spatial heterogeneity in canopy distributions.\n\nTo provide a fully defensible hypothesis test (considering both assumptions were violated), do a Kruskal–Wallis rank sum test. This is the standard non-parametric alternative to one-way ANOVA when comparing more than two independent groups (here, coastal sections). It tests whether the distributions of kelp canopy area differ across sections without assuming normality or equal variances.\n\n\n#### 4.2 Spatial Differences Between Biogeographical Provinces\n\nQuestion: Is there a statistically significant difference in mean kelp canopy area between biogeographical provinces?\n\n\n**Answer**\n\nHypotheses:\n\n- Null (H₀): Mean kelp canopy area is not different amongst bioregions.\n- Alternative (H₁): Mean kelp canopy area differs between bioregions.\n\nJustification: Here, bioregion is treated as a categorical predictor, suitable for a one-way ANOVA to test inter-bioregional differences. The weighted kelp area is the continuous response variable. Assumptions of normality and heteroscedasticity hold.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmodel_5.2 <- aov(weighted_area ~ bolton, data = pixel_means)\nsummary(model_5.2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 Df    Sum Sq   Mean Sq F value Pr(>F)    \nbolton            2 6.897e+09 3.448e+09   39585 <2e-16 ***\nResiduals   5446567 4.745e+11 8.711e+04                   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nAlso test assumptions...\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresid_5.2 <- sample(residuals(model_5.2), 5000)\n\nshapiro.test(resid_5.2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  resid_5.2\nW = 0.74748, p-value < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\nqqnorm(resid_5.2)\nqqline(resid_5.2)\n```\n\n::: {.cell-output-display}\n![](BCB744_Final_Prac_Exam_2026_files/figure-html/unnamed-chunk-62-1.png){width=60%}\n:::\n\n```{.r .cell-code}\nleveneTest(weighted_area ~ bolton, data = pixel_means)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLevene's Test for Homogeneity of Variance (center = median)\n           Df F value    Pr(>F)    \ngroup       2   39585 < 2.2e-16 ***\n      5446567                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\nplot(model_5.2, which = 1)\n```\n\n::: {.cell-output-display}\n![](BCB744_Final_Prac_Exam_2026_files/figure-html/unnamed-chunk-62-2.png){width=12cm}\n:::\n:::\n\n\n\n***Results***\nA one-way ANOVA revealed significant differences in mean kelp canopy area between the three biogeographical provinces (BMP, SWP, AMP) (F${2,5446567}$ = 39,585, *p* < 0.001). Residual analysis again revealed non-normal error distribution (Shapiro–Wilk *W* = 0.75, *p* < 0.001) and unequal variances among provinces (Levene’s test: F${2,5446567}$ = 39,585, *p* < 0.001). Despite these assumption violations, the effect was large and consistent with substantial regional differentiation in canopy extent. Residuals from the model were symmetrically distributed but with longer tails in high-variance provinces.\n\nAs before, a Kruskal–Wallis rank sum test is recommended. Again suitable, since the bioregion variable has three independent levels. This test evaluates whether the central tendency of canopy area differs among provinces without assuming parametric conditions.\n\n\n\n#### 4.3 Interaction Between Section and Province\n\nQuestion: Is there an interaction between coastal section and biogeographical province in explaining variation in kelp canopy area?\n\n\n**Answer**\n\nHypotheses:\n\n- H₀₁ (Main effect – Section): There are no differences in mean kelp canopy area across coastal sections.\n- H₀₂ (Main effect – Province): There are no differences in mean kelp canopy area across biogeographical provinces.\n- H₀₃ (Interaction): The effect of coastal section on kelp canopy area is the same across all provinces (i.e., no interaction).\n- H₁ (Alternative): At least one main effect is non-zero, or there is a significant interaction (i.e., the influence of section depends on the province).\n\nA two-way ANOVA with interaction is appropriate here because:\n\n- Both predictors, i.e., `section` (a factor) and province (`bolton`, also a factor), are categorical.\n- The response variable (`weighted_area`) is continuous and assumed to meet the assumptions of normality and homogeneity of variance.\n- The interaction term allows us to assess whether the spatial granularity of section varies in importance across broader-scale bioregions.\n\nThis model allows us to partition variation in canopy area into hierarchical (or cross-cutting) spatial components.\n\n\nTwo-way ANOVA with interaction\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_5.3 <- aov(weighted_area ~ section * bolton, data = pixel_means)\n```\n:::\n\n\nSummary of the model\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(model_5.3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 Df    Sum Sq   Mean Sq F value Pr(>F)    \nsection          18 2.020e+10 1.122e+09   13252 <2e-16 ***\nResiduals   5446551 4.612e+11 8.467e+04                   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nAlso test assumptions...\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresid_5.3 <- sample(residuals(model_5.3), 5000)\n\nshapiro.test(resid_5.3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  resid_5.3\nW = 0.81015, p-value < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\nqqnorm(resid_5.3)\nqqline(resid_5.3)\n```\n\n::: {.cell-output-display}\n![](BCB744_Final_Prac_Exam_2026_files/figure-html/unnamed-chunk-65-1.png){width=60%}\n:::\n\n```{.r .cell-code}\ncar::leveneTest(model_5.3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLevene's Test for Homogeneity of Variance (center = median)\n           Df F value    Pr(>F)    \ngroup      18   14154 < 2.2e-16 ***\n      5446551                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\nplot(model_5.3, which = 1)\n```\n\n::: {.cell-output-display}\n![](BCB744_Final_Prac_Exam_2026_files/figure-html/unnamed-chunk-65-2.png){width=12cm}\n:::\n:::\n\n\n\nIn this case, interaction terms cannot be estimated, because there’s no shared replication across bioregions within sections. The design is not factorial. The solution is to fix mixed models with random and fixed effects.\n\n***Results***\nA two-way ANOVA incorporating both section and biogeographical province, including their interaction, confirmed strong spatial structuring of kelp canopy area (F$_{18,5446551}$ = 13,252, *p* < 0.001 for the section main effect). However, the interaction term was non-estimable due to the confounded structure of the design — each section belonged uniquely to a single province, precluding factorial replication. As such, a fully crossed design could not be evaluated within a fixed-effects ANOVA framework. Model residuals displayed similar deviations from normality and homogeneity as in previous analyses, but were centered and broadly symmetric.\n\nA non-parametric two-way tests for interaction effects do not exist. Because of the nested design, a fully non-parametric two-way ANOVA is not viable. As an alternative approach, perform separate Kruskal–Wallis tests within each province, or apply a permutation-based two-way ANOVA that accommodates unbalanced and non-normal designs.\n\n\n#### 4.4 Linear Trend Over Time by Province\n\nQuestion: Is there a linear trend in kelp canopy area over time, and does the direction or strength of this trend differ between biogeographical provinces?\n\n\n**Answer**\n\nHypotheses:\n\n- H₀₁ (Main effect of time): There is no linear trend in kelp canopy area over time.\n- H₀₂ (Time × Province interaction): The effect (slope) of year is the same across all provinces.\n- H₁ (Alternative): Kelp canopy area shows a linear trend over time, and the rate or direction of change differs by province.\n\nThis is a typical ANCOVA design because:\n\n- The continuous predictor `year` captures temporal trends.\n- The categorical predictor `bolton` accounts for regional differences.\n- The interaction term `year` × `bolton` assesses whether temporal slopes differ among provinces.\n\nANCOVA is ideal for testing whether regression lines have the same slope across groups; here, whether kelp decline/growth rates differ by province.\n\n\nAggregate by year and province\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprovince_annual <- pixel_means |>\n  group_by(year, bolton) |>\n  summarise(mean_area = mean(weighted_area, na.rm = TRUE), .groups = \"drop\")\n```\n:::\n\n\nFit the ANCOVA model\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_5.4 <- lm(mean_area ~ year * bolton, data = province_annual)\n```\n:::\n\n\nShow the fitted model summary:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(model_5.4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = mean_area ~ year * bolton, data = province_annual)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-108.302  -30.177   -3.231   20.679  217.695 \n\nCoefficients:\n                   Estimate Std. Error t value Pr(>|t|)    \n(Intercept)      -9706.8982  1442.5276  -6.729 6.83e-10 ***\nyear                 4.8688     0.7196   6.766 5.70e-10 ***\nboltonB-ATZ       4135.0773  2006.6662   2.061 0.041571 *  \nboltonBMP         7488.3915  2006.6662   3.732 0.000296 ***\nyear:boltonB-ATZ    -1.9800     1.0012  -1.978 0.050340 .  \nyear:boltonBMP      -3.6787     1.0012  -3.674 0.000362 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 52.74 on 116 degrees of freedom\nMultiple R-squared:  0.7016,\tAdjusted R-squared:  0.6888 \nF-statistic: 54.56 on 5 and 116 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\nA Type III ANOVA, as in the car::Anova() function with type = 3, tests the significance of each effect after accounting for all other effects in the model, including interactions. It asks: “What is the unique contribution of this factor, given that all others (including interactions) are already in the model?”\n\n\n::: {.cell}\n\n```{.r .cell-code}\nAnova(model_5.4, type = 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnova Table (Type III tests)\n\nResponse: mean_area\n            Sum Sq  Df F value    Pr(>F)    \n(Intercept) 125927   1 45.2807 6.830e-10 ***\nyear        127296   1 45.7731 5.702e-10 ***\nbolton       38795   2  6.9749  0.001379 ** \nyear:bolton  37570   2  6.7548  0.001679 ** \nResiduals   322599 116                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\nggplot(province_annual, aes(x = year, y = mean_area, color = bolton)) +\n  geom_point(alpha = 0.4) +\n  geom_smooth(method = \"lm\", se = FALSE) +\n  theme_minimal() +\n  labs(\n    title = \"Linear Trends in Kelp Canopy Area by Province\",\n    y = \"Mean Canopy Area per Pixel\",\n    x = \"Year\"\n  )\n```\n\n::: {.cell-output-display}\n![](BCB744_Final_Prac_Exam_2026_files/figure-html/unnamed-chunk-69-1.png){width=60%}\n:::\n:::\n\n\nAlso test assumptions...\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresid_5.4 <- residuals(model_5.4)\n```\n:::\n\n\nNormality\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshapiro.test(resid_5.4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  resid_5.4\nW = 0.93452, p-value = 1.599e-05\n```\n\n\n:::\n\n```{.r .cell-code}\nqqnorm(resid_5.4)\nqqline(resid_5.4)\n```\n\n::: {.cell-output-display}\n![](BCB744_Final_Prac_Exam_2026_files/figure-html/unnamed-chunk-71-1.png){width=60%}\n:::\n:::\n\n\nHomoscedasticity\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(model_5.4, which = 1)\n```\n\n::: {.cell-output-display}\n![](BCB744_Final_Prac_Exam_2026_files/figure-html/unnamed-chunk-72-1.png){width=60%}\n:::\n\n```{.r .cell-code}\nbptest(model_5.4) # Breusch-Pagan test or any other suitable test\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tstudentized Breusch-Pagan test\n\ndata:  model_5.4\nBP = 16.228, df = 5, p-value = 0.006223\n```\n\n\n:::\n:::\n\n\nMulticollinearity Don't penalise students for not testing multicollinearity, but add a bonus two marks if included\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvif(model_5.4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                    GVIF Df GVIF^(1/(2*Df))\nyear        3.138942e+00  1        1.771706\nbolton      8.468999e+08  2      170.591747\nyear:bolton 8.466877e+08  2      170.581063\n```\n\n\n:::\n:::\n\n\nIndependence of residuals\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndwtest(model_5.4) # Durbin-Watson test\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tDurbin-Watson test\n\ndata:  model_5.4\nDW = 1.7605, p-value = 0.1114\nalternative hypothesis: true autocorrelation is greater than 0\n```\n\n\n:::\n:::\n\n\n\n***Results***\nThe ANCOVA model indicated a significant linear increase in mean kelp canopy area over time across all provinces (F${1,116}$ = 45.8, *p* < 0.001), with significant differences in temporal trends among provinces (year × province interaction: F${2,116}$ = 6.75, *p* = 0.0017). This suggests that both the direction and magnitude of temporal trends in canopy area are modulated by biogeographical province. Residuals exhibited slight right-skew (Shapiro–Wilk *W* = 0.93, *p* < 0.001), and heteroscedasticity was supported by a significant Breusch–Pagan test (BP = 16.23, df = 5, *p* = 0.006). No evidence of residual autocorrelation was detected (Durbin–Watson DW = 1.76, *p* = 0.11). Variance inflation factors indicated high collinearity between province and interaction terms, reflecting the nested structure of the provinces over time.\n\nPragmatic alternative to account for non-normality, heteroscedasticity, and collinearity: perform separate Spearman’s rank correlation tests between year and mean area within each province to assess monotonic trends, then compare slope magnitudes informally or using non-parametric trend tests like Mann–Kendall.\n\n\n#### 4.5 Seasonal Variation Across Provinces\n\nQuestion: Does the seasonal pattern in kelp canopy area differ between provinces?\n\n\n**Answer**\n\nHypotheses:\n\n- H₀₁ (Main effect of quarter): Mean kelp canopy area does not vary across seasons (quarters).\n- H₀₂ (Quarter × Province interaction): The pattern of seasonal variation is the same in all provinces — i.e., there is no interaction.\n- H₁ (Alternative): There are seasonal differences in kelp canopy area, and the shape or magnitude of the seasonal cycle differs by province.\n\nA two-way ANOVA is appropriate here, with:\n\n- `quarter` as a categorical predictor representing seasonal variation.\n- `bolton` as a categorical grouping variable for province.\n- An interaction term (`quarter` × `bolton`) to test whether seasonal cycles differ by region.\n\nThis model assesses both the amplitude and phase-shift of seasonal dynamics across spatial domains.\n\n\nEnsure quarter is treated as a categorical variable\n\n\n::: {.cell}\n\n```{.r .cell-code}\npixel_means <- pixel_means |>\n  mutate(quarter = as.factor(quarter))\n```\n:::\n\n\nGroup by year, quarter, and province to retain replication across years\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprovince_seasonal_replicated <- pixel_means |>\n  group_by(year, quarter, bolton) |>\n  summarise(mean_area = mean(weighted_area, na.rm = TRUE), .groups = \"drop\")\n```\n:::\n\n\nFit two-way ANOVA with interaction\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_5.5 <- aov(\n  mean_area ~ quarter * bolton,\n  data = province_seasonal_replicated\n)\n```\n:::\n\n\nModel summary\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(model_5.5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                Df  Sum Sq Mean Sq F value Pr(>F)    \nquarter          3   66835   22278   3.061 0.0281 *  \nbolton           2 1944753  972377 133.590 <2e-16 ***\nquarter:bolton   6  103175   17196   2.362 0.0295 *  \nResiduals      423 3078948    7279                   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nExtract residuals\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresid_5.5 <- residuals(model_5.5)\n```\n:::\n\n\nTest for normality of residuals\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshapiro.test(resid_5.5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  resid_5.5\nW = 0.95331, p-value = 1.7e-10\n```\n\n\n:::\n\n```{.r .cell-code}\nqqnorm(resid_5.5)\nqqline(resid_5.5)\n```\n\n::: {.cell-output-display}\n![](BCB744_Final_Prac_Exam_2026_files/figure-html/unnamed-chunk-80-1.png){width=60%}\n:::\n:::\n\n\nTest for homogeneity of variances across quarter × province combinations\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprovince_seasonal_replicated$group <- interaction(\n  province_seasonal_replicated$quarter,\n  province_seasonal_replicated$bolton\n)\nleveneTest(mean_area ~ group, data = province_seasonal_replicated)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLevene's Test for Homogeneity of Variance (center = median)\n       Df F value   Pr(>F)   \ngroup  11  2.3599 0.007804 **\n      423                    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nInteraction plot: mean kelp canopy area by quarter and province\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(\n  province_seasonal_replicated,\n  aes(x = quarter, y = mean_area, group = bolton, color = bolton)\n) +\n  stat_summary(fun = mean, geom = \"line\", size = 1) +\n  stat_summary(fun = mean, geom = \"point\", size = 2) +\n  theme_minimal(base_size = 11) +\n  scale_x_discrete(labels = c(\"Q1\", \"Q2\", \"Q3\", \"Q4\")) +\n  labs(\n    title = \"Interaction of Quarter and Province on Mean Kelp Canopy Area\",\n    x = \"Quarter\",\n    y = \"Mean Kelp Canopy Area (per pixel per year)\",\n    color = \"Province\"\n  ) +\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![](BCB744_Final_Prac_Exam_2026_files/figure-html/unnamed-chunk-82-1.png){width=60%}\n:::\n:::\n\n\n\n***Results***\nSeasonal variation in kelp canopy area differed significantly among provinces (two-way ANOVA: quarter × province interaction: F${6,423}$ = 2.36, p = 0.030). Both main effects were significant, with variation among quarters (F${3,423}$ = 3.06, *p* = 0.028) and among provinces (F${2,423}$ = 133.6, *p* < 0.001). Residuals exhibited mild non-normality (Shapiro–Wilk *W* = 0.95, *p* < 0.001), and homoscedasticity was violated across the interaction groups (Levene’s test: F${11,423}$ = 2.36, *p* = 0.008). Nevertheless, interaction plots indicated province-specific seasonal cycles in canopy area that were consistent across years.\n\nThere is no easy non-parametric alternative.\n\n\n#### General Guidance for Task 4 (above)\n\nFor each sub-question, above, consider:\n\n- formally state the null and alternative hypotheses;\n- justify your choice of model;\n- justify your choice of predictors;\n- justify your decision to aggregate or not aggregate the data at various levels;\n- discuss the assumptions involved and any violations you detect;\n- present the relevant model outputs and statistical tests;\n- include visualisations where appropriate (e.g. interaction plots, trend lines, diagnostic plots);\n- justify your choice of visualisation; and\n- present the results in a clear and concise manner, including tables and figures where appropriate, in a manner that would be appropriate for a scientific audience (e.g. a journal article).\n\nYou are not required to use the same modelling approach for all five sub-questions, though consistency across related questions is encouraged.\n\n### Task 5: Write-up\n\n- **[Task Weight: 10%]**\n\nWrite a short report (maximum 2 pages of text) that synthesises your findings across Tasks 2 through 5. This report should be written in the style of the Discussion section of a scientific paper, intended for an ecological audience.\n\nYour goal is to interpret the major patterns and relationships you have identified, and to comment meaningfully on their ecological significance. Your write-up should include:\n\n- Temporal Trends and Seasonality.\n- Spatial Structure and Biogeography.\n- Interaction Effects and Spatial–Temporal Coupling.\n- Limitations and Assumptions.\n- Ecological Interpretation.\n\nFormat and tone:\n\n- Aim for clarity and economy of expression.\n- Don't generate any new tables and figures. The tables and figures from Tasks 2 through 5 should be sufficient.\n- Write in complete paragraphs. Avoid bulleted summaries.\n- Add references to the tables and figures from Tasks 2 through 5 as needed.\n- Cite any additional references you use.\n\n\n**Answer**\n\n***Note to Assessor:*** Penalise all text that was clearly AI generated by subtracting 50% off the mark. \n\n*Discussion*\n\nOur analysis of long-term kelp canopy dynamics revealed strong spatio-temporal structuring in both the mean extent and variability of kelp forests across southern Africa. While the limitations of simple linear and ANOVA-based models prevent exhaustive ecological inference, the results consistently support our observations that kelp canopy cover is not uniformly variable in space or time, but instead shaped by regionally distinct seasonal regimes and long-term trends that interact with the underlying biogeographic patterns.\n\nAt the broadest temporal scale, the annual means (Task 2) show evidence for a long-term linear increase in kelp canopy area across the study period, although the strength and direction of this trend varied substantially by biogeographical province. The Benguela Marine Province (BMP) exhibited a relatively strong positive trend, while the Agulhas and Benguela-Agulhas Transition Zone (AMP and B-ATZ) showed weaker or inconsistent trajectories. These patterns likely reflect contrasting oceanographic influences, specifically the differing degrees of upwelling intensity and sea surface temperature variability across provinces. When the annual trends were disaggregated seasonally (Task 3), the signal became more complex. Seasonal means indicated a marked peak in kelp canopy area during austral summer and early autumn (quarters 1 and 2). This seasonal cycle was most pronounced in BMP, less so in B-ATZ, and relatively flat in AMP, suggesting that regional exposure to storm-driven disturbance, solar irradiance, or herbivore activity may modulate canopy recovery and loss at intra-annual scales.\n\nSpatial patterns in kelp canopy extent, assessed both at the bioregional level (Task 4.1) and at the finer spatial resolution of coastal sections (Task 5.1), reinforce the view that biogeographic context is a dominant driver of canopy variability. A large proportion of the overall variance in canopy area was attributable to differences among sections, but these differences were nested within broader provincial contrasts. The one-way and two-way ANOVAs demonstrated strong main effects of both spatial variables, although the interaction between section and province could not be statistically partitioned due to their hierarchical structure. Nonetheless, the magnitude of spatial variation suggests that local environmental factors (such as wave exposure, topographic complexity, and nutrient availability) likely modulate kelp dynamics on sub-provincial scales, even as broader provincial regimes exert overarching influence.\n\nWhere temporal and spatial effects intersect, the coupling of seasonal cycles with regional identity becomes ecologically meaningful. Task 5.5 illustrated this clearly: although all provinces experience some degree of seasonal fluctuation, the shape and amplitude of these cycles differed significantly. The interaction effect between quarter and province was significant despite the relatively simple model structure, indicating that the timing of canopy peaks and troughs is not synchronised coast-wide. This asynchrony complicates large-scale generalisations about kelp seasonality and underscores the importance of considering regional context in ecological forecasting. That the BMP, for instance, displays both the strongest seasonal cycle and the most pronounced long-term increase suggests a possible reinforcing interaction between natural seasonal pulses and long-term drivers such as ocean cooling (prevalent in the kelp's distributional range) or changing storm regimes.\n\nSeveral methodological limitations constrain the scope of these interpretations. First, violations of model assumptions (non-normality, heteroscedasticity, and the lack of full factorial design in spatial terms) limit the interpretive power of parametric tests. While non-parametric alternatives were noted where appropriate (e.g. Kruskal–Wallis, etc.), their implementation was outside the scope of this coursework. Secondly, while the data offer high temporal and spatial resolution, they lack covariates such as sea surface temperature, nutrient levels, or herbivore abundance that would allow causal inference. Finally, the use of mean canopy area as the primary response variable conceals potentially important variation in canopy fragmentation, persistence, or patch turnover.\n\nDespite these limitations, the ecological interpretation remains convincing: kelp canopy extent is increasing overall, but in a regionally specific manner that reflects underlying biogeographic structure. Seasonal variation is evident and substantial, but not temporally synchronised across the coastline. These findings align with previous studies that describe the interaction between physical forcing and biological response in kelp-dominated ecosystems (Dayton 1985; Wernberg et al. 2016). Future work should explore whether these spatial–temporal patterns correspond to known gradients in oceanographic regime or are indicative of broader shifts in coastal ecosystem functioning under climate change.\n\n*References*\n\nDayton, P. K. (1985). Ecology of kelp communities. Annual Review of Ecology and Systematics, 16, 215–245.\n\nWernberg, T., et al. (2016). Climate-driven regime shift of a temperate marine ecosystem. Science, 353(6295), 169–172.\n\n",
    "supporting": [
      "BCB744_Final_Prac_Exam_2026_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}