{
  "hash": "197194122a04b7327cded9338e230501",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Life Expectancy and Schooling\"\nsubtitle: \"A Simple Linear Regression Example Using the Kaggle Life Expectancy Data\"\nauthor: \"A. J. Smit\"\ndate: last-modified\ndate-format: \"YYYY/MM/DD\"\nformat:\n  html:\n    df-print: paged\nreference-location: margin\nparams:\n  hide_answers: false\n---\n\n\n\n:::: {.callout-important appearance=\"simple\"}\n## Self-Assessment Task 12-1\n\n**1. Question:**\n\nDoes **life expectancy** increase with **schooling** in the Kaggle life expectancy dataset?\n\nComplete a full simple linear regression analysis using life expectancy as the response and schooling as the predictor. Your job is not only to fit the model, but also to identify and justify the treatment of problematic observations.\n\nYou should do the following:\n\n1. Prepare the data by selecting the variables needed for the analysis and removing rows with missing values.\n2. Fit the initial simple linear regression model.\n3. Plot the data and show the fitted regression line.\n4. Check the initial model diagnostics graphically.\n5. Identify the issue in the dataset.\n6. Provide evidence for this issue as a table.\n7. Explain why these cases appear problematic for this analysis.\n8. Remove the problematic cases and refit the model.\n9. Recheck the diagnostics graphically for the revised model.\n10. Interpret the final model clearly and state whether it is an improvement over the initial fit. Tabulate the important model-fit statistics in support of your conclusion.\n11. End with a short scientific write-up containing Methods, Results, and Discussion sections.\n\n**2. Marking Rubric**\n\n| Component | Marks |\n|---|---:|\n| Data preparation | 3 |\n| Initial model fitting and figure | 3 |\n| Initial model diagnostics | 3 |\n| Identifying and explaining the issue | 3 |\n| Evidence for the issue presented as a table | 4 |\n| Removing the problematic cases appropriately | 2 |\n| Refitting the analysis | 3 |\n| Rechecking the diagnostics | 3 |\n| Interpreting the final model and comparing it with the initial model | 3 |\n| Scientific write-up (Methods, Results, Discussion) | 3 |\n\n**Total: 30 marks**\n\n\n\n**3. Data Preparation**\n\nI begin by reading the dataset and keeping only the variables needed for this analysis.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlife_raw <- read.csv(\n  \"../../data/BCB744/kaggle_life_expectancy_data.csv\",\n  check.names = FALSE\n)\n\nlife_dat <- life_raw |>\n  transmute(\n    Country,\n    Year,\n    life_expectancy = `Life expectancy`,\n    Schooling\n  ) |>\n  drop_na(life_expectancy, Schooling)\n\nnrow(life_dat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2768\n```\n\n\n:::\n:::\n\n\nThe working dataset contains 2,768 complete observations on life expectancy and schooling.\n\n**4. Diagnostics for the Initial Model**\n\nRegression assumptions should be checked graphically. I therefore inspect residuals versus fitted values, the normal Q-Q plot, the scale-location plot, and residuals versus leverage in @fig-full-diag.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfull_aug <- augment(mod_school_full)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_full_1 <- ggplot(full_aug, aes(x = .fitted, y = .resid)) +\n  geom_point(shape = 1, alpha = 0.4) +\n  geom_hline(yintercept = 0, linetype = \"dashed\", colour = \"red\") +\n  labs(x = \"Fitted values\", y = \"Residuals\", title = \"Residuals vs Fitted\")\n\np_full_2 <- ggplot(full_aug, aes(sample = .std.resid)) +\n  stat_qq(shape = 1, alpha = 0.5) +\n  stat_qq_line(colour = \"red\") +\n  labs(title = \"Normal Q-Q\", x = \"Theoretical quantiles\", y = \"Standardised residuals\")\n\np_full_3 <- ggplot(full_aug, aes(x = .fitted, y = sqrt(abs(.std.resid)))) +\n  geom_point(shape = 1, alpha = 0.4) +\n  labs(\n    x = \"Fitted values\",\n    y = \"Sqrt(|Standardised residuals|)\",\n    title = \"Scale-Location\"\n  )\n\np_full_4 <- ggplot(full_aug, aes(x = .hat, y = .std.resid)) +\n  geom_point(shape = 1, alpha = 0.4) +\n  labs(\n    x = \"Leverage\",\n    y = \"Standardised residuals\",\n    title = \"Residuals vs Leverage\"\n  )\n\n(p_full_1 + p_full_2) / (p_full_3 + p_full_4)\n```\n\n::: {.cell-output-display}\n![Diagnostic plots for the simple linear regression of life expectancy on schooling using all complete cases.](kaggle_life_expectancy_files/figure-html/fig-full-diag-1.svg){#fig-full-diag}\n:::\n:::\n\n\nThe initial diagnostics in @fig-full-diag suggest that the model captures the broad trend reasonably well, but there is evidence that the extreme low-schooling observations deserve scrutiny. The residual plots are not catastrophic, but the zero-schooling countries create a left-edge concentration that may be exerting unnecessary influence on the fitted line.\n\n**5. Countries With Zero Schooling**\n\nBefore fitting the model, I inspect the cases where schooling is recorded as zero. A zero value here is biologically and socially unusual for several countries in the dataset, so it is worth checking whether these cases should be treated with caution.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nschooling_zero <- life_dat |>\n  filter(Schooling == 0) |>\n  distinct(Country, Year, Schooling) |>\n  arrange(Country, Year)\n\nschooling_zero_counts <- schooling_zero |>\n  count(Country, name = \"Zero-schooling years\")\n```\n:::\n\n\n@tbl-zero-schooling lists the countries represented by one or more rows where schooling is coded as zero.\n\n\n::: {#tbl-zero-schooling .cell tbl-cap='Countries with one or more observations in which schooling is coded as zero.'}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"jospfioock\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#jospfioock table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#jospfioock thead, #jospfioock tbody, #jospfioock tfoot, #jospfioock tr, #jospfioock td, #jospfioock th {\n  border-style: none;\n}\n\n#jospfioock p {\n  margin: 0;\n  padding: 0;\n}\n\n#jospfioock .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#jospfioock .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#jospfioock .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#jospfioock .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#jospfioock .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#jospfioock .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jospfioock .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#jospfioock .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#jospfioock .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#jospfioock .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#jospfioock .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#jospfioock .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#jospfioock .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#jospfioock .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#jospfioock .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#jospfioock .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#jospfioock .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#jospfioock .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#jospfioock .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jospfioock .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#jospfioock .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#jospfioock .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#jospfioock .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jospfioock .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#jospfioock .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#jospfioock .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jospfioock .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jospfioock .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#jospfioock .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jospfioock .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#jospfioock .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jospfioock .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#jospfioock .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jospfioock .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#jospfioock .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jospfioock .gt_left {\n  text-align: left;\n}\n\n#jospfioock .gt_center {\n  text-align: center;\n}\n\n#jospfioock .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#jospfioock .gt_font_normal {\n  font-weight: normal;\n}\n\n#jospfioock .gt_font_bold {\n  font-weight: bold;\n}\n\n#jospfioock .gt_font_italic {\n  font-style: italic;\n}\n\n#jospfioock .gt_super {\n  font-size: 65%;\n}\n\n#jospfioock .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#jospfioock .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#jospfioock .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#jospfioock .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#jospfioock .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#jospfioock .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#jospfioock .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#jospfioock .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#jospfioock div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Country\">Country</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Zero-schooling-years\">Zero-schooling years</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Country\" class=\"gt_row gt_left\">Antigua and Barbuda</td>\n<td headers=\"Zero-schooling years\" class=\"gt_row gt_right\">6</td></tr>\n    <tr><td headers=\"Country\" class=\"gt_row gt_left\">Bosnia and Herzegovina</td>\n<td headers=\"Zero-schooling years\" class=\"gt_row gt_right\">1</td></tr>\n    <tr><td headers=\"Country\" class=\"gt_row gt_left\">Equatorial Guinea</td>\n<td headers=\"Zero-schooling years\" class=\"gt_row gt_right\">1</td></tr>\n    <tr><td headers=\"Country\" class=\"gt_row gt_left\">Micronesia (Federated States of)</td>\n<td headers=\"Zero-schooling years\" class=\"gt_row gt_right\">1</td></tr>\n    <tr><td headers=\"Country\" class=\"gt_row gt_left\">Montenegro</td>\n<td headers=\"Zero-schooling years\" class=\"gt_row gt_right\">4</td></tr>\n    <tr><td headers=\"Country\" class=\"gt_row gt_left\">South Sudan</td>\n<td headers=\"Zero-schooling years\" class=\"gt_row gt_right\">11</td></tr>\n    <tr><td headers=\"Country\" class=\"gt_row gt_left\">Timor-Leste</td>\n<td headers=\"Zero-schooling years\" class=\"gt_row gt_right\">1</td></tr>\n    <tr><td headers=\"Country\" class=\"gt_row gt_left\">Turkmenistan</td>\n<td headers=\"Zero-schooling years\" class=\"gt_row gt_right\">1</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\nThe detailed country-year rows are shown in @tbl-zero-schooling-years.\n\n\n::: {#tbl-zero-schooling-years .cell tbl-cap='Country-year observations in which schooling is coded as zero.'}\n\n```{.r .cell-code}\nschooling_zero |>\n  gt()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"rskavzfpap\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#rskavzfpap table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#rskavzfpap thead, #rskavzfpap tbody, #rskavzfpap tfoot, #rskavzfpap tr, #rskavzfpap td, #rskavzfpap th {\n  border-style: none;\n}\n\n#rskavzfpap p {\n  margin: 0;\n  padding: 0;\n}\n\n#rskavzfpap .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#rskavzfpap .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#rskavzfpap .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#rskavzfpap .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#rskavzfpap .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#rskavzfpap .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#rskavzfpap .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#rskavzfpap .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#rskavzfpap .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#rskavzfpap .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#rskavzfpap .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#rskavzfpap .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#rskavzfpap .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#rskavzfpap .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#rskavzfpap .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#rskavzfpap .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#rskavzfpap .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#rskavzfpap .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#rskavzfpap .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rskavzfpap .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#rskavzfpap .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#rskavzfpap .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#rskavzfpap .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rskavzfpap .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#rskavzfpap .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#rskavzfpap .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#rskavzfpap .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rskavzfpap .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#rskavzfpap .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#rskavzfpap .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#rskavzfpap .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#rskavzfpap .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#rskavzfpap .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rskavzfpap .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#rskavzfpap .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rskavzfpap .gt_left {\n  text-align: left;\n}\n\n#rskavzfpap .gt_center {\n  text-align: center;\n}\n\n#rskavzfpap .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#rskavzfpap .gt_font_normal {\n  font-weight: normal;\n}\n\n#rskavzfpap .gt_font_bold {\n  font-weight: bold;\n}\n\n#rskavzfpap .gt_font_italic {\n  font-style: italic;\n}\n\n#rskavzfpap .gt_super {\n  font-size: 65%;\n}\n\n#rskavzfpap .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#rskavzfpap .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#rskavzfpap .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#rskavzfpap .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#rskavzfpap .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#rskavzfpap .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#rskavzfpap .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#rskavzfpap .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#rskavzfpap div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Country\">Country</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Year\">Year</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Schooling\">Schooling</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Country\" class=\"gt_row gt_left\">Antigua and Barbuda</td>\n<td headers=\"Year\" class=\"gt_row gt_right\">2000</td>\n<td headers=\"Schooling\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"Country\" class=\"gt_row gt_left\">Antigua and Barbuda</td>\n<td headers=\"Year\" class=\"gt_row gt_right\">2001</td>\n<td headers=\"Schooling\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"Country\" class=\"gt_row gt_left\">Antigua and Barbuda</td>\n<td headers=\"Year\" class=\"gt_row gt_right\">2002</td>\n<td headers=\"Schooling\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"Country\" class=\"gt_row gt_left\">Antigua and Barbuda</td>\n<td headers=\"Year\" class=\"gt_row gt_right\">2003</td>\n<td headers=\"Schooling\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"Country\" class=\"gt_row gt_left\">Antigua and Barbuda</td>\n<td headers=\"Year\" class=\"gt_row gt_right\">2004</td>\n<td headers=\"Schooling\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"Country\" class=\"gt_row gt_left\">Antigua and Barbuda</td>\n<td headers=\"Year\" class=\"gt_row gt_right\">2005</td>\n<td headers=\"Schooling\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"Country\" class=\"gt_row gt_left\">Bosnia and Herzegovina</td>\n<td headers=\"Year\" class=\"gt_row gt_right\">2000</td>\n<td headers=\"Schooling\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"Country\" class=\"gt_row gt_left\">Equatorial Guinea</td>\n<td headers=\"Year\" class=\"gt_row gt_right\">2000</td>\n<td headers=\"Schooling\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"Country\" class=\"gt_row gt_left\">Micronesia (Federated States of)</td>\n<td headers=\"Year\" class=\"gt_row gt_right\">2000</td>\n<td headers=\"Schooling\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"Country\" class=\"gt_row gt_left\">Montenegro</td>\n<td headers=\"Year\" class=\"gt_row gt_right\">2000</td>\n<td headers=\"Schooling\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"Country\" class=\"gt_row gt_left\">Montenegro</td>\n<td headers=\"Year\" class=\"gt_row gt_right\">2001</td>\n<td headers=\"Schooling\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"Country\" class=\"gt_row gt_left\">Montenegro</td>\n<td headers=\"Year\" class=\"gt_row gt_right\">2002</td>\n<td headers=\"Schooling\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"Country\" class=\"gt_row gt_left\">Montenegro</td>\n<td headers=\"Year\" class=\"gt_row gt_right\">2003</td>\n<td headers=\"Schooling\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"Country\" class=\"gt_row gt_left\">South Sudan</td>\n<td headers=\"Year\" class=\"gt_row gt_right\">2000</td>\n<td headers=\"Schooling\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"Country\" class=\"gt_row gt_left\">South Sudan</td>\n<td headers=\"Year\" class=\"gt_row gt_right\">2001</td>\n<td headers=\"Schooling\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"Country\" class=\"gt_row gt_left\">South Sudan</td>\n<td headers=\"Year\" class=\"gt_row gt_right\">2002</td>\n<td headers=\"Schooling\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"Country\" class=\"gt_row gt_left\">South Sudan</td>\n<td headers=\"Year\" class=\"gt_row gt_right\">2003</td>\n<td headers=\"Schooling\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"Country\" class=\"gt_row gt_left\">South Sudan</td>\n<td headers=\"Year\" class=\"gt_row gt_right\">2004</td>\n<td headers=\"Schooling\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"Country\" class=\"gt_row gt_left\">South Sudan</td>\n<td headers=\"Year\" class=\"gt_row gt_right\">2005</td>\n<td headers=\"Schooling\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"Country\" class=\"gt_row gt_left\">South Sudan</td>\n<td headers=\"Year\" class=\"gt_row gt_right\">2006</td>\n<td headers=\"Schooling\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"Country\" class=\"gt_row gt_left\">South Sudan</td>\n<td headers=\"Year\" class=\"gt_row gt_right\">2007</td>\n<td headers=\"Schooling\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"Country\" class=\"gt_row gt_left\">South Sudan</td>\n<td headers=\"Year\" class=\"gt_row gt_right\">2008</td>\n<td headers=\"Schooling\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"Country\" class=\"gt_row gt_left\">South Sudan</td>\n<td headers=\"Year\" class=\"gt_row gt_right\">2009</td>\n<td headers=\"Schooling\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"Country\" class=\"gt_row gt_left\">South Sudan</td>\n<td headers=\"Year\" class=\"gt_row gt_right\">2010</td>\n<td headers=\"Schooling\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"Country\" class=\"gt_row gt_left\">Timor-Leste</td>\n<td headers=\"Year\" class=\"gt_row gt_right\">2000</td>\n<td headers=\"Schooling\" class=\"gt_row gt_right\">0</td></tr>\n    <tr><td headers=\"Country\" class=\"gt_row gt_left\">Turkmenistan</td>\n<td headers=\"Year\" class=\"gt_row gt_right\">2000</td>\n<td headers=\"Schooling\" class=\"gt_row gt_right\">0</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\nBecause several of these zero-schooling values are unlikely to be literal population-level measurements, I first fit the model with all complete cases and then refit it after excluding these countries.\n\n**6. Initial Model: All Complete Cases**\n\nI now fit the simple linear regression:\n\n$$\n\\text{Life expectancy}_i = \\beta_0 + \\beta_1 \\text{Schooling}_i + \\varepsilon_i\n$$\n\nIn this model, $\\beta_1$ is the expected change in life expectancy associated with a one-unit increase in schooling.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod_school_full <- lm(life_expectancy ~ Schooling, data = life_dat)\nsummary(mod_school_full)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = life_expectancy ~ Schooling, data = life_dat)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-25.8986  -2.8210   0.6186   3.8186  30.4911 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 44.10889    0.43676     101   <2e-16 ***\nSchooling    2.10345    0.03506      60   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 6.172 on 2766 degrees of freedom\nMultiple R-squared:  0.5655,\tAdjusted R-squared:  0.5653 \nF-statistic:  3599 on 1 and 2766 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nThe fitted relationship is shown in @fig-full-fit.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(life_dat, aes(x = Schooling, y = life_expectancy)) +\n  geom_point(shape = 1, alpha = 0.35, colour = \"grey35\") +\n  geom_smooth(\n    method = \"lm\",\n    se = TRUE,\n    colour = \"steelblue4\",\n    fill = \"lightblue\"\n  ) +\n  labs(\n    x = \"Schooling\",\n    y = \"Life expectancy\"\n  )\n```\n\n::: {.cell-output-display}\n![Life expectancy as a function of schooling using all complete observations. The line shows the fitted simple linear regression and the shaded band shows the 95% confidence interval for the mean fitted response.](kaggle_life_expectancy_files/figure-html/fig-full-fit-1.svg){#fig-full-fit}\n:::\n:::\n\n\n@fig-full-fit shows a clear positive trend: countries with higher schooling values tend to have higher life expectancy. The relationship is not perfectly tight, but it is strong enough to make a simple straight-line model a reasonable first approximation.\n\n**7. Refit After Removing Zero-Schooling Countries**\n\nI now remove every country that appears in @tbl-zero-schooling and refit the model. This is a more conservative filtering decision than simply dropping the rows where schooling equals zero, because it assumes that a country with obviously suspect schooling values may contribute additional problematic observations in other years as well.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlife_dat_filtered <- life_dat |>\n  filter(!Country %in% zero_countries)\n\nnrow(life_dat_filtered)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2640\n```\n\n\n:::\n:::\n\n\nAfter this filtering step, 2,640 observations remain.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod_school_filtered <- lm(life_expectancy ~ Schooling, data = life_dat_filtered)\nsummary(mod_school_filtered)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = life_expectancy ~ Schooling, data = life_dat_filtered)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-25.0048  -2.8498   0.7661   3.9261  15.3182 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 41.43868    0.45199   91.68   <2e-16 ***\nSchooling    2.31002    0.03602   64.14   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 5.871 on 2638 degrees of freedom\nMultiple R-squared:  0.6093,\tAdjusted R-squared:  0.6091 \nF-statistic:  4113 on 1 and 2638 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nThe refitted relationship is shown in @fig-filtered-fit.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(life_dat_filtered, aes(x = Schooling, y = life_expectancy)) +\n  geom_point(shape = 1, alpha = 0.35, colour = \"grey35\") +\n  geom_smooth(\n    method = \"lm\",\n    se = TRUE,\n    colour = \"steelblue4\",\n    fill = \"lightblue\"\n  ) +\n  labs(\n    x = \"Schooling\",\n    y = \"Life expectancy\"\n  )\n```\n\n::: {.cell-output-display}\n![Life expectancy as a function of schooling after removing countries with one or more zero-schooling observations.](kaggle_life_expectancy_files/figure-html/fig-filtered-fit-1.svg){#fig-filtered-fit}\n:::\n:::\n\n\nCompared with @fig-full-fit, @fig-filtered-fit shows a slightly cleaner linear pattern. The slope remains strongly positive, but the fit is less distorted by the extreme left-edge cases.\n\n**8. Diagnostics for the Filtered Model**\n\nI again inspect the standard regression diagnostics, now for the filtered model (@fig-filtered-diag).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfiltered_aug <- augment(mod_school_filtered)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_fil_1 <- ggplot(filtered_aug, aes(x = .fitted, y = .resid)) +\n  geom_point(shape = 1, alpha = 0.4) +\n  geom_hline(yintercept = 0, linetype = \"dashed\", colour = \"red\") +\n  labs(x = \"Fitted values\", y = \"Residuals\", title = \"Residuals vs Fitted\")\n\np_fil_2 <- ggplot(filtered_aug, aes(sample = .std.resid)) +\n  stat_qq(shape = 1, alpha = 0.5) +\n  stat_qq_line(colour = \"red\") +\n  labs(title = \"Normal Q-Q\", x = \"Theoretical quantiles\", y = \"Standardised residuals\")\n\np_fil_3 <- ggplot(filtered_aug, aes(x = .fitted, y = sqrt(abs(.std.resid)))) +\n  geom_point(shape = 1, alpha = 0.4) +\n  labs(\n    x = \"Fitted values\",\n    y = \"Sqrt(|Standardised residuals|)\",\n    title = \"Scale-Location\"\n  )\n\np_fil_4 <- ggplot(filtered_aug, aes(x = .hat, y = .std.resid)) +\n  geom_point(shape = 1, alpha = 0.4) +\n  labs(\n    x = \"Leverage\",\n    y = \"Standardised residuals\",\n    title = \"Residuals vs Leverage\"\n  )\n\n(p_fil_1 + p_fil_2) / (p_fil_3 + p_fil_4)\n```\n\n::: {.cell-output-display}\n![Diagnostic plots for the simple linear regression of life expectancy on schooling after removing countries with zero-schooling observations.](kaggle_life_expectancy_files/figure-html/fig-filtered-diag-1.svg){#fig-filtered-diag}\n:::\n:::\n\n\nThe filtered-model diagnostics in @fig-filtered-diag are more convincing. The residuals remain somewhat scattered, as expected in a large cross-country dataset, but the leverage pattern is less concerning and the model behaves more like a stable simple linear regression.\n\n**9. Comparing the Two Fits**\n\nTo make the comparison explicit, I summarise the key coefficients and fit statistics in @tbl-model-compare.\n\n\n::: {#tbl-model-compare .cell tbl-cap='Comparison of the simple linear regression fitted before and after removing countries with zero-schooling observations.'}\n\n```{.r .cell-code}\nmodel_compare <- tibble(\n  Model = c(\"All complete cases\", \"Zero-schooling countries removed\"),\n  N = c(nobs(mod_school_full), nobs(mod_school_filtered)),\n  Intercept = c(coef(mod_school_full)[1], coef(mod_school_filtered)[1]),\n  Slope = c(coef(mod_school_full)[2], coef(mod_school_filtered)[2]),\n  `95% CI lower` = c(confint(mod_school_full)[2, 1], confint(mod_school_filtered)[2, 1]),\n  `95% CI upper` = c(confint(mod_school_full)[2, 2], confint(mod_school_filtered)[2, 2]),\n  `R-squared` = c(summary(mod_school_full)$r.squared, summary(mod_school_filtered)$r.squared)\n)\n\nmodel_compare |>\n  mutate(\n    Intercept = round(Intercept, 3),\n    Slope = round(Slope, 3),\n    `95% CI lower` = round(`95% CI lower`, 3),\n    `95% CI upper` = round(`95% CI upper`, 3),\n    `R-squared` = round(`R-squared`, 3)\n  ) |>\n  gt()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"zifhnnmemn\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#zifhnnmemn table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#zifhnnmemn thead, #zifhnnmemn tbody, #zifhnnmemn tfoot, #zifhnnmemn tr, #zifhnnmemn td, #zifhnnmemn th {\n  border-style: none;\n}\n\n#zifhnnmemn p {\n  margin: 0;\n  padding: 0;\n}\n\n#zifhnnmemn .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#zifhnnmemn .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#zifhnnmemn .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#zifhnnmemn .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#zifhnnmemn .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#zifhnnmemn .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#zifhnnmemn .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#zifhnnmemn .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#zifhnnmemn .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#zifhnnmemn .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#zifhnnmemn .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#zifhnnmemn .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#zifhnnmemn .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#zifhnnmemn .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#zifhnnmemn .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#zifhnnmemn .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#zifhnnmemn .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#zifhnnmemn .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#zifhnnmemn .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zifhnnmemn .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#zifhnnmemn .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#zifhnnmemn .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#zifhnnmemn .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zifhnnmemn .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#zifhnnmemn .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#zifhnnmemn .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#zifhnnmemn .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zifhnnmemn .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#zifhnnmemn .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#zifhnnmemn .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#zifhnnmemn .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#zifhnnmemn .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#zifhnnmemn .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zifhnnmemn .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#zifhnnmemn .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zifhnnmemn .gt_left {\n  text-align: left;\n}\n\n#zifhnnmemn .gt_center {\n  text-align: center;\n}\n\n#zifhnnmemn .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#zifhnnmemn .gt_font_normal {\n  font-weight: normal;\n}\n\n#zifhnnmemn .gt_font_bold {\n  font-weight: bold;\n}\n\n#zifhnnmemn .gt_font_italic {\n  font-style: italic;\n}\n\n#zifhnnmemn .gt_super {\n  font-size: 65%;\n}\n\n#zifhnnmemn .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#zifhnnmemn .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#zifhnnmemn .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#zifhnnmemn .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#zifhnnmemn .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#zifhnnmemn .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#zifhnnmemn .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#zifhnnmemn .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#zifhnnmemn div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Model\">Model</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"N\">N</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Intercept\">Intercept</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Slope\">Slope</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"a95%-CI-lower\">95% CI lower</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"a95%-CI-upper\">95% CI upper</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"R-squared\">R-squared</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Model\" class=\"gt_row gt_left\">All complete cases</td>\n<td headers=\"N\" class=\"gt_row gt_right\">2768</td>\n<td headers=\"Intercept\" class=\"gt_row gt_right\">44.109</td>\n<td headers=\"Slope\" class=\"gt_row gt_right\">2.103</td>\n<td headers=\"95% CI lower\" class=\"gt_row gt_right\">2.035</td>\n<td headers=\"95% CI upper\" class=\"gt_row gt_right\">2.172</td>\n<td headers=\"R-squared\" class=\"gt_row gt_right\">0.565</td></tr>\n    <tr><td headers=\"Model\" class=\"gt_row gt_left\">Zero-schooling countries removed</td>\n<td headers=\"N\" class=\"gt_row gt_right\">2640</td>\n<td headers=\"Intercept\" class=\"gt_row gt_right\">41.439</td>\n<td headers=\"Slope\" class=\"gt_row gt_right\">2.310</td>\n<td headers=\"95% CI lower\" class=\"gt_row gt_right\">2.239</td>\n<td headers=\"95% CI upper\" class=\"gt_row gt_right\">2.381</td>\n<td headers=\"R-squared\" class=\"gt_row gt_right\">0.609</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n@tbl-model-compare shows that removing the zero-schooling countries increases the estimated slope from about 2.1 to about 2.31 years of life expectancy per unit schooling. At the same time, $R^2$ increases from 0.565 to 0.609, indicating a somewhat tighter linear association after filtering.\n\n**10. Write-up**\n\n**10.1 Methods**\n\nI analysed the relationship between life expectancy and schooling using the Kaggle life expectancy dataset. I retained country, year, life expectancy, and schooling, and removed rows with missing values for life expectancy or schooling. I first fitted a simple linear regression using all complete observations, with life expectancy as the response and schooling as the predictor. I then identified countries for which schooling was coded as zero (@tbl-zero-schooling and @tbl-zero-schooling-years). Because several of these zero values appeared implausible as literal measurements and were likely to represent coding anomalies or problematic records, I excluded all observations from those countries and refitted the regression. For both models, I examined the fitted relationship graphically (@fig-full-fit and @fig-filtered-fit) and assessed assumptions using residual-versus-fitted, normal Q-Q, scale-location, and residual-versus-leverage plots (@fig-full-diag and @fig-filtered-diag). Model coefficients and goodness-of-fit statistics were compared in Table @tbl-model-compare.\n\n**10.2 Results**\n\nUsing all complete observations, life expectancy increased strongly with schooling (@fig-full-fit). The fitted slope was positive, indicating that countries with greater schooling tended to have higher life expectancy, and the simple linear regression explained a substantial proportion of the variation in life expectancy ($R^2 = 0.565). Inspection of the data revealed a small group of countries with one or more observations in which schooling was coded as zero (@tbl-zero-schooling and @tbl-zero-schooling-years). After removing those countries, the positive relationship remained clear and became slightly stronger (@fig-filtered-fit). The estimated slope increased from 2.1 to 2.31, and model fit improved from $R^2 = 0.565 to $R^2 = 0.609 (@tbl-model-compare). The diagnostic plots for the filtered model (@fig-filtered-diag) suggested a cleaner and more stable fit than the initial model, with less concern about leverage from extreme low-schooling cases.\n\n**10.3 Discussion**\n\nThis analysis indicates a strong positive association between schooling and life expectancy in the dataset, and the relationship is well captured by a simple linear model after removing countries with zero-schooling records. The comparison between the two fits suggests that those zero-schooling cases were influential enough to weaken the apparent linear pattern and reduce overall fit. Their removal produced a steeper slope and more convincing diagnostics, which supports the decision to treat them as questionable observations for this teaching example.\n\nThe results should still be interpreted cautiously. These data are observational and cross-national, so the fitted slope should not be read as a direct causal effect of schooling on life expectancy. Many other factors, including wealth, healthcare access, infectious disease burden, governance, and conflict, may contribute to the observed pattern. Even so, the filtered model provides a useful example of simple linear regression because the predictor-response relationship is interpretable, the scatterplot shows a clear trend, and the diagnostics are broadly acceptable.\n\n\n::::",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}