{
  "hash": "4b5be5760ce5204f4f38d0e467884e3f",
  "result": {
    "engine": "knitr",
    "markdown": "---\ndate: last-modified\ntitle: \"13a (revised): Distance-Based Redundancy Analysis: Revisiting the β-Diversity Partition\"\nformat:\n  html:\n    code-link: false\n---\n\n\n::: {.cell}\n\n:::\n\n\n::: callout-tip\n## **Material Required for This Chapter**\n\n| Type        | Name                                     | Link                                                                                        |\n| :--- | :--- | :--- |\n| **Slides**  | Constrained ordination lecture slides    | [💾 `BCB743_12_constrained_ordination.pdf`](../slides/BCB743_12_constrained_ordination.pdf) |\n| **Reading** | Smit et al. (2017)                       | [💾 `Smit_et_al_2017.pdf`](../docs/Smit_et_al_2017.pdf)                                     |\n|             | Supp. to Smit et al. (2017)              | [💾 `Smit_the_seaweed_data.pdf`](../docs/Smit_the_seaweed_data.pdf)                         |\n| **Data**    | The seaweed environmental data           | [💾 `SeaweedEnv.RData`](../data/BCB743/seaweed/SeaweedEnv.RData)                                   |\n|             | The seaweed species data                 | [💾 `SeaweedSpp.csv`](../data/BCB743/seaweed/SeaweedSpp.csv)                                       |\n|             | The bioregions                           | [💾 `bioregions.csv`](../data/BCB743/seaweed/bioregions.csv)                                       |\n|             | The seaweed coastal section coordinates  | [💾 `SeaweedSites.csv`](../data/BCB743/seaweed/SeaweedSites.csv)                                   |\n:::\n\n## Why a Second Version of This Chapter?\n\nIn the [first version](constrained_ordination.qmd) of this db_RDA analysis I used the **turnover** component of Sørensen dissimilarity, extracted by the **betapart** package following @Baselga2010 and @baselga2018partitioning. That step applied one particular way of taking community dissimilarity apart, namely splitting the total into a *turnover* part ($\\beta_\\text{sim}$) and a *nestedness-resultant* part ($\\beta_\\text{sne}$) and keeping the turnover part. A decade of methodological work has questioned whether splitting $\\beta$-diversity in that way is the right one. Here I keep the ecological question, the data, and the db-RDA method exactly as they were, but change only the dissimilarity partition and ask whether the seaweed result changes materially with this change.\n\n::: {.callout-important}\n## Why?\n\nIf switching to the more defensible partition *changed* the ecological conclusion, then the original seaweed interpretation would have been based on a methodological choice rather than on the data. A result that holds only under one contested partition is weaker than one that survives a reasonable alternative, and this chapter exists to find out which kind of result I have here.\n:::\n\n@fig-v2-concept maps the experiment. The original chapter and this one share every step except the partition, and I run both to the end and compare.\n\n```{mermaid}\n%%| label: fig-v2-concept\n%%| echo: false\n%%| fig-cap: \"The original analysis and this re-analysis share the data, the predictors, and the db-RDA machinery; they differ only in which partition of Sørensen dissimilarity becomes the response. Running both to the end and comparing shows whether the ecological conclusion depends on that choice.\"\nflowchart TD\n  S[\"Sørensen dissimilarity\"]\n  S --> B[\"Baselga turnover<br/>(original chapter)\"]\n  S --> P[\"Podani replacement<br/>(this chapter)\"]\n  B --> DB[\"db-RDA\"]\n  P --> DP[\"db-RDA\"]\n  DB --> RB[\"temperature explains turnover\"]\n  DP --> RP[\"same answer?\"]\n  RB --> C[\"Compare:<br/>does the conclusion survive?\"]\n  RP --> C\n```\n\nThe plan involves:\n\n1. A plain-language statement of the problem and the fix.\n2. The algebra of the two partitions.\n3. The re-run, with a direct comparison against the original turnover analysis.\n\n::: {.callout-note appearance=\"simple\"}\n## My Thinking\n\nThe original analysis assumed that Baselga's $\\beta_\\text{sim}$ is \"pure turnover\", cleanly separated from differences in species richness. Critics raise two objections. First, the leftover $\\beta_\\text{sne}$ does not behave like nestedness [@almeidaneto2012rethinking]. Second, $\\beta_\\text{sim}$ and the total Sørensen dissimilarity are scaled by different denominators, so $\\beta_\\text{sim}$ is not a fraction of the total on a common scale [@podani2011new; @schmera2011comments]. @legendre2014interpreting offers an alternative that *is* additive and commensurably scaled, namely a split of dissimilarity into **replacement** and **richness difference**. I rebuild the db-RDA on the replacement component and compare.\n:::\n\n## The Original Assumption\n\nThe first version computed Sørensen dissimilarity and decomposed it with **betapart**:\n\n```r\nY.core <- betapart.core(spp)\nY.pair <- beta.pair(Y.core, index.family = \"sor\")\nY1 <- as.matrix(Y.pair$beta.sim)   # the turnover component, used as the response\n```\n\nThe response matrix `Y1` was $\\beta_\\text{sim}$, the Simpson dissimilarity, on the reasoning that it isolates spatial **turnover** (species replacing one another along the coast) from the **nestedness-resultant** dissimilarity $\\beta_\\text{sne}$ (assemblages at species-poor sites forming subsets of richer ones). The interpretation the chapter and the @smit2017seaweeds paper depended on $\\beta_\\text{sim}$ being a clean measure of replacement. That is the assumption now in question.\n\n## Alternative Views\n\n**Baselga's \"nestedness\" component is not nestedness.** @almeidaneto2012rethinking showed that $\\beta_\\text{sne}$ (and its multi-site form $\\beta_\\text{SNE}$) is only loosely related to nestedness. It responds to the size and fill of the data matrix and can rise or fall while the actual degree of nestedness is held constant; it can even take large values for matrices with no nestedness at all, so the name oversells what the quantity recovers. So, if $\\beta_\\text{sne}$ is not a clear measurement of nestedness, treating $\\beta_\\text{sne}$ as \"the nestedness component\" risks the user inferring a claim that cannot be supported.\n\n**The components are not commensurably scaled.** @podani2011new and @schmera2011comments make an algebraic point. Baselga's $\\beta_\\text{sim}$ is the Simpson index, scaled to its own denominator, while the total Sørensen dissimilarity is scaled to a different one. The two are therefore not fractions of a shared whole, and the partition is not an additive decomposition of the total onto a common scale. As a remedy they decompose presence–absence data into three additive, uniformly scaled fractions, namely shared species (similarity), species **replacement**, and **richness difference**.\n\n**A synthesis with a working implementation.** @legendre2014interpreting drew these ideas together and supplied a tidy decomposition for both the Jaccard and Sørensen approaches. He keeps the replacement and richness-difference idea of Podani and Schmera and of @carvalho2012determining, and provides it in the **adespatial** package [@dray2023adespatial] as `beta.div.comp()`.\n\n### The Math Behind the Dissimilarities\n\nFor two sites, write the shared and unique species counts the usual way:\n\n- $a$ = species present at **both** sites,\n- $b$ = species unique to the first site,\n- $c$ = species unique to the second site.\n\n::: {.callout-important}\n## Two Partitions of the Same Sørensen Dissimilarity\n\n**Total Sørensen dissimilarity**\n$$\\beta_\\text{sor} = \\frac{b+c}{2a+b+c}.$$\n\n**Baselga's equation** (by **betapart**; turnover + nestedness-resultant)\n$$\\beta_\\text{sim} = \\frac{\\min(b,c)}{a+\\min(b,c)}, \\qquad \\beta_\\text{sne} = \\beta_\\text{sor} - \\beta_\\text{sim}.$$\n\n**Podani's equation** (done by **adespatial** `coef = \"S\"`; replacement + richness difference)\n$$\\text{Repl} = \\frac{2\\,\\min(b,c)}{2a+b+c}, \\qquad \\text{RichDiff} = \\frac{\\lvert b-c\\rvert}{2a+b+c}.$$\n\nThe Podani components share the Sørensen denominator $2a+b+c$, so they are commensurable fractions of the same total:\n$$\\text{Repl} + \\text{RichDiff} = \\frac{2\\min(b,c) + \\lvert b-c\\rvert}{2a+b+c} = \\frac{b+c}{2a+b+c} = \\beta_\\text{sor}.$$\n\nBaselga's $\\beta_\\text{sim}$ uses the denominator $a+\\min(b,c)$ instead. That choice makes $\\beta_\\text{sim}$ **independent of the richness difference** $\\lvert b-c\\rvert$, but it also stops it from being a fraction of $\\beta_\\text{sor}$ on a shared scale.\n:::\n\n### Baselga's Defence\n\n@Baselga2012 argues in defence that independence from richness difference is the property a turnover measure *should* have, since $\\beta_\\text{sim}$ stays unchanged when sites differ only in how many species they hold, whereas the Podani replacement, with the richness difference in its denominator, still changes with richness gradients. @baselga2015comparing extends the argument and compares the indices on simulated and real data. The choice is a trade-off between properties, not a case of one index being wrong.\n\n| Property | Baselga $\\beta_\\text{sim}$ (betapart) | Podani Repl (adespatial `\"S\"`) |\n| :--- | :--- | :--- |\n| Independent of richness difference | **Yes** | No |\n| A fraction of $\\beta_\\text{sor}$ on a common scale | No | **Yes** |\n| Partner component tracks true nestedness | Disputed [@almeidaneto2012rethinking] | Measures richness difference, not nestedness |\n| Additive with its partner | Yes ($\\beta_\\text{sim}+\\beta_\\text{sne}=\\beta_\\text{sor}$) | Yes (Repl + RichDiff $=\\beta_\\text{sor}$) |\n\n### Which One for the db-RDA?\n\nThere is no universal answer. The right choice depends on the property you most need. For a db-RDA whose goal is to model how the *whole* community dissimilarity is structured by the environment, the case for the Podani–Legendre approach is justified, since it is a commensurable, additive piece of the total Sørensen dissimilarity whose partner component is named for what it measures. I adopt it here then check if the ecological interpretation changes materially.\n\n## Set-Up the Analysis Environment\n\nThe only new dependency is **adespatial**. Install it once if needed (`install.packages(\"adespatial\")`).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(betapart) # the original Baselga partition\nlibrary(adespatial) # the Podani / Legendre partition\nlibrary(vegan) # capscale(), anova.cca(), vif.cca(), protest()\n```\n:::\n\n\nLoad the seaweed species data ($Y$), 58 coastal sections × 847 macroalgal species recorded as presence–absence [@smit2017seaweeds].\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspp <- read.csv(here::here(\"data\", \"BCB743\", \"seaweed\", \"SeaweedSpp.csv\"))\nspp <- dplyr::select(spp, -1)\ndim(spp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]  58 847\n```\n\n\n:::\n:::\n\n\n## Two Partitions of the Same Dissimilarity\n\nFirst the original Baselga turnover, which I keep so that I can compare against it later:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nY.core <- betapart.core(spp)\nY.pair <- beta.pair(Y.core, index.family = \"sor\")\nbeta_sim <- as.matrix(Y.pair$beta.sim) # Baselga turnover (Simpson)\n```\n:::\n\n\nNow Podani's Sørensen decomposition. `beta.div.comp()` returns the replacement matrix (`$repl`), the richness-difference matrix (`$rich`), the total dissimilarity (`$D`), and a summary vector (`$part`):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nY.comp <- beta.div.comp(spp, coef = \"S\", quant = FALSE)\nrepl <- as.matrix(Y.comp$repl) # Podani / Legendre replacement -> the new response\nrich <- as.matrix(Y.comp$rich) # richness difference\nDsor <- as.matrix(Y.comp$D) # total Sorensen dissimilarity\nY.comp$part # whole-dataset shares of replacement and richness difference\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        BDtotal            Repl         RichDif    Repl/BDtotal RichDif/BDtotal \n     0.24779409      0.17081532      0.07697877      0.68934379      0.31065621 \n```\n\n\n:::\n:::\n\n\n**Podani's partition is additive on a common scale.** Replacement plus richness difference should reproduce the total Sørensen dissimilarity exactly:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrange(repl + rich - Dsor) # both numbers ~ 0\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -1.110223e-16  1.110223e-16\n```\n\n\n:::\n:::\n\n\n**Baselga's is reproduced by `coef = \"BS\"`.** This isolates the *method*, not the package. Asking **adespatial** for the Baselga Sørensen calculation returns betapart's $\\beta_\\text{sim}$ to numerical precision:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nY.bas <- beta.div.comp(spp, coef = \"BS\", quant = FALSE)\nrange(as.matrix(Y.bas$repl) - beta_sim) # ~ 0: BS replacement == betapart beta.sim\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0 0\n```\n\n\n:::\n:::\n\n\nNothing else differs between the two analyses. The data are the same, one package computes both partitions, and only the partition itself changes. How far apart, then, are the two response matrices? Do Mantel test to find out:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmantel(Y.comp$repl, Y.pair$beta.sim)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nMantel statistic based on Pearson's product-moment correlation \n\nCall:\nmantel(xdis = Y.comp$repl, ydis = Y.pair$beta.sim) \n\nMantel statistic r: 0.9384 \n      Significance: 0.001 \n\nUpper quantiles of permutations (null model):\n   90%    95%  97.5%    99% \n0.0506 0.0692 0.0856 0.0971 \nPermutation: free\nNumber of permutations: 999\n```\n\n\n:::\n:::\n\n\nI expect a high correlation, since both numerators are built on $\\min(b,c)$, but not equality, because the denominators differ. The test returns $r = 0.938$, i.e., the two response matrices are already very nearly the same *before any ordination is performed*, so switching the partition reshuffles the dissimilarities only slightly. Does such a small a difference change the db-RDA?\n\n## Environmental Predictors and Collinearity\n\nThe environmental variables are unchanged from the first version. Load the thermal data, keep the same nine variables, and convert to $z$-scores:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nload(here::here(\"data\", \"BCB743\", \"seaweed\", \"SeaweedEnv.RData\"))\nE1 <- dplyr::select(\n  env,\n  febMean,\n  febRange,\n  febSD,\n  augMean,\n  augRange,\n  augSD,\n  annMean,\n  annRange,\n  annSD\n)\nE1 <- decostand(E1, method = \"standardize\")\n\nbioreg <- read.csv(here::here(\"data\", \"BCB743\", \"seaweed\", \"bioregions.csv\"))\n```\n:::\n\n\n::: {.callout-note appearance=\"simple\"}\n## Why the Collinearity Step Is Identical to Version 1\n\nIn RDA and db-RDA the variance inflation factors depend on the **predictor matrix alone**, not on the response. Changing the response from $\\beta_\\text{sim}$ to the replacement matrix therefore cannot change the VIFs, so the same three variables drop out and I arrive at the same reduced predictor set $E4$. You can confirm this from the VIFs of the full model below, which match the first version.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvif.cca(capscale(repl ~ ., E1)) # same VIFs as the beta.sim model\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   febMean   febRange      febSD    augMean   augRange      augSD    annMean \n 91.129700   6.775959   7.734436  73.090382   8.486631  12.118914 233.400746 \n  annRange      annSD \n        NA   5.396343 \n```\n\n\n:::\n\n```{.r .cell-code}\n# iterative drop of annMean, then febMean, then augSD (as in version 1)\nE4 <- E1 |>\n  dplyr::select(-annMean, -febMean, -augSD)\nnames(E4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"febRange\" \"febSD\"    \"augMean\"  \"augRange\" \"annRange\" \"annSD\"   \n```\n\n\n:::\n:::\n\n\n## The db-RDA on the Replacement Component\n\nI fit the model on the replacement matrix, under the same niche-difference hypothesis, namely that the coastal thermal gradient sorts the seaweed flora by physiological tolerance.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncap_repl <- capscale(repl ~ ., E4)\ncap_repl\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall: capscale(formula = repl ~ febRange + febSD + augMean + augRange +\nannRange + annSD, data = E4)\n\n              Inertia Proportion Rank\nTotal          4.5096                \nRealTotal      4.9712     1.0000     \nConstrained    3.8122     0.7668    6\nUnconstrained  1.1591     0.2332   29\nImaginary     -0.4616                \n\nInertia is squared Unknown distance\n\nEigenvalues for constrained axes:\n  CAP1   CAP2   CAP3   CAP4   CAP5   CAP6 \n2.6497 1.0980 0.0538 0.0069 0.0023 0.0014 \n\nEigenvalues for unconstrained axes:\n  MDS1   MDS2   MDS3   MDS4   MDS5   MDS6   MDS7   MDS8 \n0.4933 0.2992 0.1138 0.0670 0.0482 0.0321 0.0249 0.0205 \n(Showing 8 of 29 unconstrained eigenvalues)\n```\n\n\n:::\n:::\n\n\nIs the fit significant overall, and which axes have signal?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(cap_repl, parallel = 4) # whole model\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPermutation test for capscale under reduced model\nPermutation: free\nNumber of permutations: 999\n\nModel: capscale(formula = repl ~ febRange + febSD + augMean + augRange + annRange + annSD, data = E4)\n         Df SumOfSqs      F Pr(>F)    \nModel     6   3.8122 27.957  0.001 ***\nResidual 51   1.1591                  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\nanova(cap_repl, by = \"axis\", parallel = 4) # which CAP axes\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPermutation test for capscale under reduced model\nForward tests for axes\nPermutation: free\nNumber of permutations: 999\n\nModel: capscale(formula = repl ~ febRange + febSD + augMean + augRange + annRange + annSD, data = E4)\n         Df SumOfSqs        F Pr(>F)    \nCAP1      1  2.64969 116.5898  0.001 ***\nCAP2      1  1.09800  49.2607  0.001 ***\nCAP3      1  0.05379   2.4599  0.432    \nCAP4      1  0.00693   0.3230  0.999    \nCAP5      1  0.00232   0.1100  1.000    \nCAP6      1  0.00142   0.0624           \nResidual 51  1.15906                    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nWhich thermal terms are significant?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(cap_repl_terms <- anova(cap_repl, by = \"terms\", parallel = 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPermutation test for capscale under reduced model\nTerms added sequentially (first to last)\nPermutation: free\nNumber of permutations: 999\n\nModel: capscale(formula = repl ~ febRange + febSD + augMean + augRange + annRange + annSD, data = E4)\n         Df SumOfSqs       F Pr(>F)    \nfebRange  1  1.25359 55.1595  0.001 ***\nfebSD     1  0.21602  9.5051  0.001 ***\naugMean   1  2.14328 94.3069  0.001 ***\naugRange  1  0.10175  4.4771  0.014 *  \nannRange  1  0.03511  1.5451  0.221    \nannSD     1  0.06241  2.7461  0.060 .  \nResidual 51  1.15906                   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\ncap_repl_ax <- which(cap_repl_terms[, 4] < 0.05)\ncap_repl_sign_ax <- colnames(E4[, cap_repl_ax])\ncap_repl_sign_ax\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"febRange\" \"febSD\"    \"augMean\"  \"augRange\"\n```\n\n\n:::\n:::\n\n\nThe adjusted $R^2$ and the share of inertia the constraints explain:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncap_repl_R2 <- RsquareAdj(cap_repl)$adj.r.squared\nround(cap_repl_R2, 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.74\n```\n\n\n:::\n\n```{.r .cell-code}\nround(sum(cap_repl$CCA$eig) / cap_repl$tot.chi * 100, 2) # % constrained\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 84.53\n```\n\n\n:::\n:::\n\n\n## Does the Choice of Partition Change the Result?\n\nTo answer this, I refit the **original** turnover model on the same reduced predictors and assess the two side by side.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncap_sim <- capscale(beta_sim ~ ., E4)\ncap_sim_R2 <- RsquareAdj(cap_sim)$adj.r.squared\ncap_sim_terms <- anova(cap_sim, by = \"terms\", parallel = 4)\ncap_sim_sign_ax <- colnames(E4[, which(cap_sim_terms[, 4] < 0.05)])\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncap_pct <- function(m) sum(m$CCA$eig) / m$tot.chi * 100\ncap1_pct <- function(m) m$CCA$eig[1] / sum(m$CCA$eig) * 100\n\ncomparison <- tibble::tibble(\n  Quantity = c(\n    \"Adjusted R-squared\",\n    \"Constrained inertia (%)\",\n    \"CAP1 share of constrained (%)\",\n    \"Significant thermal terms\"\n  ),\n  `Baselga's turnover (beta_sim)` = c(\n    sprintf(\"%.2f\", cap_sim_R2),\n    sprintf(\"%.1f\", cap_pct(cap_sim)),\n    sprintf(\"%.1f\", cap1_pct(cap_sim)),\n    paste(cap_sim_sign_ax, collapse = \", \")\n  ),\n  `Podani's replacement (Repl_S)` = c(\n    sprintf(\"%.2f\", cap_repl_R2),\n    sprintf(\"%.1f\", cap_pct(cap_repl)),\n    sprintf(\"%.1f\", cap1_pct(cap_repl)),\n    paste(cap_repl_sign_ax, collapse = \", \")\n  )\n)\nknitr::kable(comparison)\n```\n\n::: {.cell-output-display}\n\n\n|Quantity                      |Baselga's turnover (beta_sim)      |Podani's replacement (Repl_S)      |\n|:-----------------------------|:----------------------------------|:----------------------------------|\n|Adjusted R-squared            |0.85                               |0.74                               |\n|Constrained inertia (%)       |90.5                               |84.5                               |\n|CAP1 share of constrained (%) |82.5                               |69.5                               |\n|Significant thermal terms     |febRange, febSD, augMean, augRange |febRange, febSD, augMean, augRange |\n\n\n:::\n:::\n\n\nOnce the two ordinations are optimally rotated and scaled onto one another, how well do their site configurations agree? Do a Procrustes test:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npro <- protest(\n  scores(cap_sim, display = \"wa\", choices = 1:2),\n  scores(cap_repl, display = \"wa\", choices = 1:2),\n  permutations = 999\n)\npro\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nprotest(X = scores(cap_sim, display = \"wa\", choices = 1:2), Y = scores(cap_repl,      display = \"wa\", choices = 1:2), permutations = 999) \n\nProcrustes Sum of Squares (m12 squared):        0.02707 \nCorrelation in a symmetric Procrustes rotation: 0.9864 \nSignificance:  0.001 \n\nPermutation: free\nNumber of permutations: 999\n```\n\n\n:::\n:::\n\n\nThe numbers are *not* identical. The replacement partition explains somewhat less constrained variation (adjusted $R^2$ of 0.74 against 0.85 for the turnover model) and produces a less dominant first axis, with CAP1 capturing about 70% of the constrained variation against about 82% under turnover.\n\nBut the parts that tell me about the *ecology* do not change. The same four thermal terms stay significant, and once the two ordinations are optimally rotated onto one another their site configurations are almost coincident (Procrustes correlation 0.986, $p =$ 0.001). **The ecological conclusion holds under both partitions, even though the ordination is not numerically identical.** So, switching to Podani's cheme changes some numbers but not the answer, and had it changed the answer, that is something I would have wanted to know.\n\n### Seeing the Rotation\n\nThe Procrustes correlation is easier to trust once you can see it. In @fig-procrustes I rotate Baselga's turnover ordination onto Podani's replacement ordination and draw, for each of the 58 coastal sections, an arrow from its rotated turnover position to its replacement position. A section that the two partitions place identically would not have an arrow at all.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npro_rot <- procrustes(\n  X = scores(cap_repl, display = \"wa\", choices = 1:2), # Podani replacement = target\n  Y = scores(cap_sim, display = \"wa\", choices = 1:2) # Baselga turnover, rotated onto the target\n)\n\npro_df <- data.frame(\n  x_target = pro_rot$X[, 1], # replacement (target) positions\n  y_target = pro_rot$X[, 2],\n  x_rot = pro_rot$Yrot[, 1], # rotated turnover positions\n  y_rot = pro_rot$Yrot[, 2],\n  bioreg = bioreg$bolton,\n  section = seq_len(58)\n)\n\nggplot(pro_df) +\n  geom_segment(\n    aes(x = x_rot, y = y_rot, xend = x_target, yend = y_target),\n    arrow = arrow(length = unit(0.12, \"cm\"), type = \"closed\"),\n    colour = \"grey55\",\n    linewidth = 0.4\n  ) +\n  geom_point(\n    aes(x = x_target, y = y_target, colour = bioreg),\n    size = 4.5,\n    shape = 24,\n    fill = \"white\"\n  ) +\n  geom_text(\n    aes(x = x_target, y = y_target, label = section),\n    size = 2.6,\n    colour = \"black\"\n  ) +\n  coord_equal() +\n  xlab(\"Dimension 1\") +\n  ylab(\"Dimension 2\") +\n  ggtitle(\"Procrustes rotation: Baselga turnover onto Podani replacement\") +\n  theme_grey() +\n  theme(panel.grid.minor = element_blank(), legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![Procrustes rotation of Baselga's turnover ordination onto Podani's replacement ordination. Each triangle marks a coastal section at its replacement-ordination position, coloured by bioregion and numbered 1 (west) to 58 (east); the grey arrow runs from the section's rotated turnover position to its replacement position. The length of an arrow is the residual displacement between the two ordinations for that section.](constrained_ordination_v2_files/figure-html/fig-procrustes-1.svg){#fig-procrustes}\n:::\n:::\n\n\nThe figure makes the Procrustes correlation of 0.986 visible. The arrows are short over most of the coast, a little longer at the two ends of the gradient, and they point in no single direction. No section relocates to a different part of the ordination, and the bioregions keep their west-to-east order and their separation. The two partitions place the 58 sections in almost the same arrangement, and the small residual movement that remains has no spatial or ecological pattern. So, a change of partition leaves the ecological conclusion unchanged.\n\n## Ordination Diagram\n\nI draw the replacement-based model with **site (wa) scores**, coloured by bioregion, with arrows for the significant thermal constraints, using the same conventions as the first version so the two figures can be compared directly.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncap_repl_scrs <- scores(cap_repl, display = c(\"wa\", \"bp\"))\n\nsite_scores <- data.frame(cap_repl_scrs$sites)\nsite_scores$bioreg <- bioreg$bolton\nsite_scores$section <- seq_len(58)\n\nbiplot_scores <- data.frame(cap_repl_scrs$biplot)\nbiplot_scores$labels <- rownames(biplot_scores)\nbiplot_scores_sign <- biplot_scores[\n  biplot_scores$labels %in% cap_repl_sign_ax,\n]\n\nggplot(site_scores, aes(x = CAP1, y = CAP2, colour = bioreg)) +\n  geom_point(size = 5.0, shape = 24, fill = \"white\") +\n  geom_text(aes(label = section), size = 3.0, colour = \"black\") +\n  geom_label(\n    data = biplot_scores_sign,\n    aes(CAP1, CAP2, label = labels),\n    colour = \"black\"\n  ) +\n  geom_segment(\n    data = biplot_scores_sign,\n    aes(x = 0, y = 0, xend = CAP1, yend = CAP2),\n    arrow = arrow(length = unit(0.2, \"cm\"), type = \"closed\"),\n    colour = \"lightseagreen\",\n    alpha = 1,\n    linewidth = 0.7\n  ) +\n  xlab(\"CAP1\") +\n  ylab(\"CAP2\") +\n  ggtitle(\"Site (wa) scores and the replacement component\") +\n  theme_grey() +\n  theme(\n    panel.grid.minor = element_blank(),\n    legend.position = \"none\",\n    aspect.ratio = 0.8\n  )\n```\n\n::: {.cell-output-display}\n![db-RDA of the **Podani–Legendre replacement** component of seaweed dissimilarity, drawn with site (wa) scores. Each coastal section sits at the weighted average of the species recorded there, coloured by bioregion and numbered 1 (west) to 58 (east). Arrows mark the significant thermal constraints.](constrained_ordination_v2_files/figure-html/fig-cap-repl-1.svg){#fig-cap-repl}\n:::\n:::\n\n\nThe ecological interpretation is the same one the first version gave:\n\n- **CAP1 is still the west-to-east winter-temperature gradient.** The sections line up along it in geographic order, the bioregions separate cleanly from the cool Benguela sections at one end to the warm east-coast sections at the other, and the `augMean` arrow (August is austral winter) lies almost along the axis. This is the dominant pattern, just as before, though it now accounts for a smaller share of the constrained variation (about 70% rather than 82%), because the replacement partition spreads the structure across the axes a little more evenly.\n- **CAP2 still has the seasonal thermal variability.** The summer-range terms (`febRange`, `febSD`) load on the second axis, separating sections by how variable their warm-season temperatures are rather than by their mean.\n- **The arrows offer the niche-difference explanation.** Both mean warmth and thermal variability sort the flora into its regional assemblages.\n\nThe structure is the same and the drivers are the same, and the only thing that has changed is how the response variable is defined. So, seaweed dissimilarity along the South African coast is structured first by the mean winter thermal gradient and second by seasonal thermal variability.\n\n## Practical Guidance\n\n::: {.callout-note appearance=\"simple\"}\n## Choosing and Reporting a Partition\n\n- **State the family.** \"Turnover\" and \"replacement\" should not be seen as interchangeable labels. Name the index (Baselga's $\\beta_\\text{sim}$, or Podani/Legendre's replacement) and the package.\n- **For modelling community dissimilarity** (db-RDA, RDA on a component, variation partitioning), prefer the **Podani–Legendre replacement** (via `adespatial::beta.div.comp(coef = \"S\")` or `\"J\"`), which is a commensurable, additive fraction of the total whose partner component is named *richness difference*, for what it measures, rather than *nestedness*.\n- **If strict independence from richness difference is the property you need**, Baselga's $\\beta_\\text{sim}$ remains defensible, but do not call its complement *nestedness* without the caveat from @almeidaneto2012rethinking.\n- **Check that the conclusion rwmains unchanged.** Run both, then compare with a Mantel test on the matrices and a Procrustes test on the ordinations, as above. When the answer is stable, say so. When it is not, the partition has become part of your result and must be reported as such.\n:::\n\n## Summary\n\nThe first version of this chapter was not wrong so much as it rested on a contested choice that it never flagged. Here I made the choice explicit, set out the critique of the Baselga turnover / nestedness-resultant split [@almeidaneto2012rethinking; @podani2011new; @schmera2011comments], adopted the additive, commensurably scaled replacement component of @legendre2014interpreting, and re-ran the db-RDA. The thermal structuring of South African seaweed dissimilarity ramins invariant of the change. The partition of β-diversity is a modelling decision, to be made deliberately, reported, and checked against the conclusion.\n\nThe broadest lesson is the one to carry into your own work. **An ecological conclusion worth trusting is one that is robust acorss reasonable analytical alternatives.** A result that holds only under a single, contested choice is fragile, whether or not anyone notices. A result that you have tried to break and could not is one you can defend. \n\n## References\n\n::: {#refs}\n:::",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}