---
title: "Artificial Intelligence for Academic Integrity (AI4AI)"
format: html
---

# Artificial Intelligence for Academic Integrity (AI4AI)

## Prompts

In OpenAI Desktop Application, you can follow the menu path `Settings > Personlization > Customize ChatGPT` to set up a custom prompt for the AI model. This is useful for setting up a prompt that you use frequently, such as for a specific course or project.


## Reading and Summarising Papers

SciSpace is a platform that allows researchers to read and summarise papers. It is a great tool for keeping up to date with the latest research in your field. You can use it to search for papers, read abstracts, and generate summaries of papers that you find interesting.

## Multidocument Chat

NotebookLM

## Writing and Editing

ChatGPT canvas (o1), accessible only in the OpernAI web application, is a great tool for writing and editing text. You can use it to write essays, reports, and other documents, and it provides a distraction-free environment for focusing on your writing.

## Jenni AI



