---
date: "2023-04-24"
title: "Assessment theory"
number-sections: false
format: html
---


BCB744 and BCB743 thoroughly implement formative and summative assessments.

**Formative assessment** is 'academic speak' for **continuous assessment**. It provides you with ongoing feedback that you can use to track your performance and to self-evaluate your understanding. Formative assessment also lets me see your development as we progress from simple to more complex topics. Since this is done daily with feedback the next day, I can identify and address any hurdles before they become problematic and impede progression. Formative assessments may include quizzes, discussions, observations, group activities, or small focussed tasks. They are designed to gauge your progress and identify areas of strength or weakness. Continual monitoring and feedback allow me to modify and adapt my instructional strategies in real-time to meet your needs as students better. I intend for this dynamic approach to assessment to create a more engaging, interactive, collaborative, and supportive learning environment, ultimately promoting deeper understanding and long-term retention of knowledge.

**Summative assessment** is the second and final mode of assessment. It is designed to evaluate your understanding and mastery of subjects in their full complexity at the end of the learning period. These assessments are in the form of standardised tests or exams and may also comprise comprehensive integrative projects. This mode of assessment provides us (you, me, the BCB Department, and the UWC) with a view of attaining the desired teaching outcomes as stated in the modules' preambles. It is also a yardstick we use to rate and rank the effectiveness of my instructional methods and the extent to which you have acquired knowledge.

Formative and summative assessments must inform decisions regarding student advancement and future instructional needs. They contribute to the continuous improvement of the integrated educational program, the curriculum, and teaching practices.

Here's a summary of the two modes of assessment:

-   **Purpose** Formative assessment mainly monitors your progress and provides feedback during the learning process. In contrast, summative assessment evaluates your performance and understanding at the end of a learning period.

-   **Timing** Formative assessments frequently occur throughout a course or unit, allowing continuous feedback and adjustment. Summative assessments typically occur at the end of a course, unit, or semester.

-   **Feedback** Formative assessment offers real-time, actionable feedback that enables you and me to adjust learning and teaching strategies. Summative assessment provides a more comprehensive evaluation of your knowledge and skills, which can inform future instruction or determine advancement.

-   **Impact on grades** Formative assessments are often weighted less regarding how much tasks contribute to the final mark; it focuses instead on learning and improvement. Summative assessments typically count more towards the final grade and allow us to establish whether you have attained specific learning objectives.
