---
title: "Evolving AI and Information Literacy"
author: "AJ Smit"
---

Generative AI tools like ChatGPT, Google Gemini, and Claude Sonnet are transforming teaching, learning, and assessment practices in higher education. These technologies offer innovative opportunities to enhance education, but they also present challenges that need careful consideration. AI continues to evolve rapidly, and universities must help both faculty and students understand how to use these tools ethically and effectively within their specific disciplines. This includes recognising AI's limitations alongside its potential to improve educational outcomes.

::: callout-note
## There are three broad strategies for approaching AI in education:

**Avoid:** Ignore AI and hope it goes away. It won't and it is not a viable strategy. So, we can revert to in-person assessments where using AI is not possible. This is not a sustainable solution, as AI is here to stay and will continue to evolve. There are also many logistical constraints that prevent this from being tenable.

**Outpace:** Devise assessment approaches that AI cannot yet do. Again, this is not a sustainable solution, as AI will eventually catch up. This is a short-term solution at best.

**Embrace and adapt:** This is the most sustainable solution. We need to understand AI and how it can be used in education. We need to be agile and adapt our assessment practices to include AI, and we need to teach students how to use AI effectively and ethically. This blends AI with AI… Artificial Intelligence and Academic Integrity. This will also equip students with the skills they need to succeed in the workforce.
:::

The question is: How do we prepare students for a future where AI is ubiquitous? How do we ensure that students are AI literate and can use AI effectively and ethically? How do we ensure that students are not just using AI to cheat, but are using it to enhance their learning and understanding?

The answer is to embed AI literacy into the curriculum. This means teaching students how to:

- how to use AI effectively and ethically
- how to critically evaluate AI-generated content (being aware the risks and limitations of generative AI)
- create their own AI-generated content ('engineering' the most appropriate prompts for the desired output)
- use AI to enhance and augment their learning and understanding (scaffold into existing personal knowledge structures)
- maintain a sense of authenticity (how to stand out as an individual in a crowd of students all using the same generative AI tools)

To question:

- our relationship with knowledge
- how we think and solve problems
- ethical implications
- AI vs AI… Artificial Intelligence and Academic Integrity

## Survey of employees (LinkedIn and Microsoft)…

- 75% have adopted generative AI in the workplace (doubled in six months)
- 79% of company leaders admitted they needed to adopt gen AI tools to remain competitive
- there is an AI skills gap
- many reports of upwards adjusting salaries for those with gen AI skills/literacy

## Implications of a rapidly changing workforce on education

- if the workforce has new/different expectations of AI adoption, how does this affect tertiary education?
- we need to prepare students for life beyond graduation
- we need to reconsider the current curriculum and pedagogical approaches
- where does the AI competency fit within the science (or broader university) curriculum?
- what does AI literacy mean? what are the actual skills? 
- how do we bring this into the range of course offerings, and, considering it evolves so quickly (beyond the rate at which we can develop and redevelop modules), how do we manage teaching and learning within this shifting landscape?

## The writing process

- (Grammarly Authorship)

## How do students use generative AI tools?

We need to understand how students currently use generative AI tools for assessments. Common applications include summarising and paraphrasing lengthy readings, brainstorming ideas for assessment tasks, writing code, performing spelling and grammar checks (similar to Word or Grammarly), and creating practice questions for exam preparation.

- Assistance with assessments (cheating)
- Research and writing
- Coding

## Assessments

### MCQ quizzes and questions involving recall

Generative AI can readily and easily produce answers to fact-based or basic questions, particularly on commonly taught subjects. [Easy]{.my-highlight}

### Generic short written assignments

Generative AI can produce convincing broad-level responses to short written assignments, such as essays or reports. [Easy]{.my-highlight}
