---
date: "2023-04-24"
title: "Graduate attributes"
number-sections: false
format: html
---


Key graduate attributes I emphasise in my BDC334, BCB744, and BCB743 syllabi are:

**BCB334, BCB744, and BCB743:**

-   **Advanced subject knowledge** Deep understanding of the subject matter, its principles, and current research trends.
-   **Critical thinking** Ability to evaluate scientific literature, identify gaps in knowledge, and propose novel research questions.
-   **Communication skills** Effective presentation of scientific concepts and research findings, both in written and oral formats, to diverse audiences.
-   **Ethical awareness** Understanding and adhering to ethical guidelines and principles in research, including responsible conduct of research, data management, and intellectual property rights.

**BCB744 and BCB743 additionally develop:**

-   **Problem-solving** Capacity to develop innovative solutions for complex scientific challenges.
-   **Research skills** Proficiency in experimental design, data collection, analysis, interpretation, and reporting of scientific findings.
-   **Collaboration** Teamwork and interdisciplinary cooperation in research projects, fostering a productive scientific environment.
-   **Adaptability** Flexibility and openness to new ideas, methods, and technologies, enabling continuous growth and development in the ever-evolving scientific landscape.
-   **Project management** Planning, organising, and executing scientific projects while managing resources and time effectively.
-   **Professional development** Commitment to lifelong learning, networking, and career advancement through participation in conferences, workshops, and professional organisations.
