---
date: "2023-04-24"
title: "Notable heatwaveR citations"
number-sections: false
format: html
---

## Notable examples of high-impact publications {#sec-impact}

-   Smale, D. A., Wernberg, T., Oliver, E. C., Thomsen, M., Harvey, B. P., Straub, S. C., ... & Moore, P. J. (2019). Marine heatwaves threaten global biodiversity and the provision of ecosystem services. Nature Climate Change, 9(4), 306-312.
-   Barkhordarian, A., Nielsen, D. M., & Baehr, J. (2022). Recent marine heatwaves in the North Pacific warming pool can be attributed to rising atmospheric levels of greenhouse gases. Communications Earth & Environment, 3(1), 131.
-   Thoral, F., Montie, S., Thomsen, M. S., Tait, L. W., Pinkerton, M. H., & Schiel, D. R. (2022). Unravelling seasonal trends in coastal marine heatwave metrics across global biogeographical realms. Scientific Reports, 12(1), 7740.
-   Benedetti-Cecchi, L. (2021). Complex networks of marine heatwaves reveal abrupt transitions in the global ocean. Scientific Reports, 11(1), 1739.
-   Woolway, R. I., Jennings, E., Shatwell, T., Golub, M., Pierson, D. C., & Maberly, S. C. (2021). Lake heatwaves under climate change. Nature, 589(7842), 402-407.
-   García Molinos, J., Hunt, H. L., Green, M. E., Champion, C., Hartog, J. R., & Pecl, G. T. (2022). Climate, currents and species traits contribute to early stages of marine species redistribution. Communications biology, 5(1), 1329.
-   Smith, K. E., Burrows, M. T., Hobday, A. J., Sen Gupta, A., Moore, P. J., Thomsen, M., ... & Smale, D. A. (2021). Socioeconomic impacts of marine heatwaves: Global issues and opportunities. Science, 374(6566), eabj3593.

## Examples of cross-discipline research in marine heatwaves {#sec-cross}

-   Schlegel, R. W., Oliver, E. C., & Chen, K. (2021). Drivers of marine heatwaves in the Northwest Atlantic: The role of air--sea interaction during onset and decline. Frontiers in Marine Science, 8, 627970.
-   Hu, L. (2021). A global assessment of coastal marine heatwaves and their relation with coastal urban thermal changes. Geophysical Research Letters, 48(9), e2021GL093260.
-   Barkhordarian, A., Nielsen, D. M., & Baehr, J. (2022). Greenhouse Gas Forcing a Necessary Causation for Marine Heatwaves Over the Northeast Pacific Warming Pool.

## Use outside of the initially intended field of application {#sec-outside}

-   Tassone, S. J., Besterman, A. F., Buelo, C. D., Ha, D. T., Walter, J. A., & Pace, M. L. (2023). Increasing heatwave frequency in streams and rivers of the United States. Limnology and Oceanography Letters, 8(2), 295-304.
-   Diniz, F. R., Gonçalves, F. L. T., & Sheridan, S. (2020). Heat wave and elderly mortality: Historical analysis and future projection for metropolitan region of São Paulo, Brazil. Atmosphere, 11(9), 933.
-   Woolway, R. I., Albergel, C., Frölicher, T. L., & Perroud, M. (2022). Severe Lake Heatwaves Attributable to Human‐Induced Global Warming. Geophysical Research Letters, 49(4), e2021GL097031.
-   Reynaert, S., De Boeck, H. J., Verbruggen, E., Verlinden, M., Flowers, N., & Nijs, I. (2021). Risk of short‐term biodiversity loss under more persistent precipitation regimes. Global Change Biology, 27(8), 1614-1626.
-   Woolway, R. I., Anderson, E. J., & Albergel, C. (2021). Rapidly expanding lake heatwaves under climate change. Environmental Research Letters, 16(9), 094013.
-   Paton, E. (2022). Intermittency analysis of dry spell magnitude and timing using different spell definitions. Journal of Hydrology, 608, 127645.
-   Martinez-Baroja, L., Rey-Benayas, J. M., Perez-Camacho, L., & Villar-Salvador, P. (2022). Drivers of oak establishment in Mediterranean old fields from 25-year-old woodland islets planted to assist natural regeneration. European Journal of Forest Research, 141(1), 17-30.
-   Pappert, D., Barriendos, M., Brugnara, Y., Imfeld, N., Jourdain, S., Przybylak, R., ... & Brönnimann, S. (2022). Statistical reconstruction of daily temperature and sea level pressure in Europe for the severe winter 1788/89. Climate of the Past, 18(12), 2545-2565.
-   Ngoungue Langue, C. G., Lavaysse, C., Vrac, M., & Flamant, C. (2023). Heat wave monitoring over West African cities: uncertainties, characterization and recent trends. Natural Hazards and Earth System Sciences, 23(4), 1313-1333.

## Support of policy development around the management of marine living resources {#sec-policy}

-   Buenafe, K. C. V., Dunn, D. C., Everett, J. D., Brito-Morales, I., Schoeman, D. S., Hanson, J. O., ... & Richardson, A. J. (2022). A climate-smart spatial planning framework.
-   Wegscheider, B., Linnansaari, T., Monk, W., Ndong, M., Haralampides, K., St-Hilaire, A., ... & Allen, R. (2020). Quantitative modelling of fish habitat under future regulated and hydro-climatically driven flow regimes in the Saint John River (New Brunswick, Canada). Quantitative modelling of existing and future fish habitat in the Saint John River, NB, Canada, 184.
-   Buenafe, K. C. V., Dunn, D. C., Everett, J. D., Brito-Morales, I., Schoeman, D. S., Hanson, J. O., ... & Richardson, A. J. (2023). A metric-based framework for climate-smart conservation planning. Ecological Applications, e2852.
-   Muñoz-Pizza, D. M., Sanchez-Rodriguez, R. A., & Manzano, E. G. Linking Climate Change to Urban Planning Through Vulnerability Assessment: The Case of Two Cities at the Mexico-Us Border. Available at SSRN 4348277.

## Novel research questions and hypotheses {#sec-novel}

-   Leach, T. S., BuyanUrt, B., & Hofmann, G. E. (2021). Exploring impacts of marine heatwaves: paternal heat exposure diminishes fertilization success in the purple sea urchin (Strongylocentrotus purpuratus). Marine Biology, 168(7), 103.
-   Pegado, M. R., Santos, C. P., Raffoul, D., Konieczna, M., Sampaio, E., Maulvault, A. L., ... & Rosa, R. (2020). Impact of a simulated marine heatwave in the hematological profile of a temperate shark (Scyliorhinus canicula). Ecological Indicators, 114, 106327.
-   Kraufvelin, L. (2021). Identification of marine heatwaves in the Archipelago Sea and experimental testing of their impacts on the non-indigenous Harris mud crab.
-   Oliveira, H., Maulvault, A. L., Santos, C. P., Silva, M., Bandarra, N. M., Valente, L. M., ... & Anacleto, P. (2023). Can marine heatwaves affect the fatty acid composition and energy budget of the tropical fish Zebrasoma scopas?. Environmental Research, 224, 115504.
-   Leach, T. S. (2022). The Role of Pre-and Post-Spawning Temperature Stress on Fertilization Dynamics Within Santa Barbara Channel Sea Urchin Species. University of California, Santa Barbara.
-   Minuti, J. J., Byrne, M., Hemraj, D. A., & Russell, B. D. (2021). Capacity of an ecologically key urchin to recover from extreme events: Physiological impacts of heatwaves and the road to recovery. Science of the Total Environment, 785, 147281.
-   Clare, X. S., Kui, L., & Hofmann, G. E. (2022). Larval Thermal Tolerance of Kellet's Whelk (Kelletia kelletii) as a Window into the Resilience of a Wild Shellfishery to Marine Heatwaves. Journal of Shellfish Research, 41(2), 283-290.
-   Marochi, M. Z., De Grande, F. R., Pardo, J. C. F., Montenegro, Á., & Costa, T. M. (2022). Marine heatwave impacts on newly-hatched planktonic larvae of an estuarine crab. Estuarine, Coastal and Shelf Science, 278, 108122.
-   Van Der Walt, K. A., Potts, W. M., Porri, F., Winkler, A. C., Duncan, M. I., Skeeles, M. R., & James, N. C. (2021). Marine Heatwaves Exceed Cardiac Thermal Limits of Adult Sparid Fish (Diplodus capensis, Smith 1884). Frontiers in Marine Science, 8, 702463.

## Online trackers of marine heatwaves {#sec-trackers}

-   The [original marine heatwave tracker](http://www.marineheatwaves.org/tracker.html)
-   The [Physical Sciences Laboratory heatwave website](https://psl.noaa.gov/marine-heatwaves/)
-   [WhaleMap](http://whalemap.ocean.dal.ca/MHW/)
