---
title: "How to Learn"
author: "AJ Smit"
format: html
editor: visual
---

## How Does One Study to Understand?

This question was asked by 3rd years, but it is relevant here too.

I just need some advice from sir. I'm starting to study today and I just wanted to know what do you think is the best way to study for sir's exam. I'm asking because I studied really hard for the midterm tests but I still got low marks lol. So I just wanted to know if there is maybe a different approach that I can take.\
\
I was trying to memorise things for the midterm tests but I know sir said we must focus on understanding but when I focus on understanding then the work does not stick in my head😂.\
\
So far I've just read through the articles but is there any advice that sir can give me please?

### Answer

Thank you for your email. Hmmm, a tricky question to ask of someone who wrote their last exam in 1993!

I am the opposite to you. I cannot memorise things but I am able to understand things really well. Fortunately, in the process of figuring things out, the relevant bits of information/knowledge relating to the thing I am trying to understand also sticks in my mind, which is (for me) a useful side effect of figuring things out. For me, it is pointless having things to memorise unless I can apply it to something that needs figuring out. So, everything I know, I know because it is useful to me.

How does understanding come about? For me, I try and understand stuff because the challenge of a tricky problem is thrilling, so understanding is facilitated because the process aligns with what makes me 'tick.' Okay, so this does not answer how understanding comes about; it simply talks to who I am.

I can tell you is *how* you can test your understanding. Explain the thing you are trying to understand to a friend or family member. If your explanation of the topic brings about an understanding in the other person, then you yourself understand it. At least this process will tell you where your own understanding starts to fail. As Richard Feynman said, "If you cannot explain something to a 7-year old, you don't understand it yourself." Or something like that.

For someone who finds it easier to memorise stuff and more challenging to understand... I don't know what that feels like as I have no personal experience or frame of reference that allows me to place myself into your shoes. But here is the theory:

1.  Know what it is you already know, and build upon that (see point 2). At some point later on you will also know what you don't know...

    > "*Reports that say that something hasn't happened are always interesting to me, because as we know, there are known knowns; there are things we know we know. We also know there are known unknowns; that is to say we know there are some things we do not know. But there are also unknown unknowns---the ones we don't know we don't know. And if one looks throughout the history of our country and other free countries, it is the latter category that tends to be the difficult ones.*"
    >
    > \-- Donald Rumsfeld, February 12, 2002

2.  You already know things. Structure new and existing knowledge around the major concepts and principles of the module (broadly, the new concepts covered each week). This means that work done in your first and second years of your study, in ALL the modules you completed, remains relevant, and has to be used together with the new knowledge obtained in the new module, and structured around the broad concept and principle (there are many concepts and principles in a module).

3.  You need to develop and understand the language used to communicate the topic. At the very basic level, this requires that you understand in intricate detail the individual words (ALL of them) that form the foundational language of your study discipline (biology and science more broadly). Only once you understand the definitions of individual words will you be able to develop more complex understanding. I think this is the primary reason why students fail to develop a deep understanding of a topic that requires explanation in multiple paragraphs (long answers and essays).

4.  Another step involves knowing how all the steps that inform the thinking process are interrelated. This requires that you consider some of the following things: What does the assignment or task require me to do (i.e. unpack the problem)? What are the steps I need to follow to get there? What do I already know about it? What do I not understand and where do I get stuck? Why don't I know it already? What about the problem causes me to get stuck? Where do I get the knowledge about what I don't understand, and how can I use this to become unstuck? Okay, so now I am figuring things out... What does the problem remind me about? Have I encountered something similar before, and if so, how can I use that to develop further my current thinking about the problem? This whole process is called metacognition, which is thinking about thinking and learning. This kind of thing has to happen each time you see something new, come across a new piece of information, listen to someone speak, etc. It can be applied in your day to day life to the extent that it become implicit in how you approach life. Eventually, you'll find yourself saying more often, "I am wondering..." Then you will arrive at critical thinking, which is what makes science special.

5.  How well you are able to integrate the metacognitive skills in your life and learning depends unfortunately on your inherent abilities and prior experiences. It is easier for some than it is for others.

6.  A critical characteristic of good learning is that it informs your sense of self --- this means that once you value learning as one of the most important attributes which inform who you are as a person, the easier it will become to learn, the less effort it will take, and the more learning itself will become the motivator (as opposed to search for motivation externally, like some reward, for having to learn).

7.  The activities in your life, your friends, family and interests will also shape how much you learn, and what you learn.

8.  You need to mix with people who values learning to the same extent that you do, so this social reinforcement further 'snowballs' into life-long learning and understanding.

Step no. 4. is probably to most helpful.
