---
date: "2023-04-24"
title: "Ad Personam Promotion 2023: e-Portfolio"
number-sections: false
format: html
---

::: callout-note
## About the square bracket \`\[\]\` notation
A list of the links provided in my Case for Promotion document is provided here. The numbers in square brackets '\[\]' refer to the footnote in the Case for Promotion document.
:::

# Part 4.1. Learning and Teaching

Amidst the COVID-19 pandemic, I deftly navigated the situation by implementing innovative teaching methods, which I have been using since 2022. I now offer students a range of options to choose from, including pre-recorded video lectures on iKamva, traditional PowerPoint-type slides, detailed written materials, and in-person lectures. My undergraduate teaching approach revolves around utilising video lectures to deliver content and in-class sessions to stimulate discussion on complex topics while also exploring related subjects and problem-solving. To further engage BSc (Hons) students, I conduct interactive workshops, providing an immersive learning experience. In addition, I developed **The Tangled Bank**, a comprehensive website that functions both as an augmented online textbook and a learning guide. The website serves as a testament to my thorough teaching and learning approach and contains additional information about my teaching methodology, which can be found in the syllabi of specific modules (referenced as footnotes BDC334,  BCB744,  and BCB743 ). I take immense pride in being a lecturer who goes above and beyond the lecture theatre.

\[1\] [The Tangled Bank](https://tangledbank.netlify.app)

\[2\] Refer to the [BCB744 module syllabus and course outline](../BCB744/BCB744_index.qmd)

\[3\] The [BCB743 syllabus and course outline](../BCB743/BCB743_index.qmd)

\[4\] The [BDC334 syllabus and course outline](../BDC334/BDC334_index.qmd)

## 4.1.1. Develop Level-3 module BDC334, and BSc (Hons) modules BCB744 and BCB743 for the BCB Department

\[5\] I was instrumental in developing South Africa's first undergraduate Marine Biology curriculum at the University of KwaZulu-Natal in 2007 (with Profs. Perissinotto and Schoeman)

\[6\] See a [discussion](../pages/technology_infusion.qmd) about how I allow modern technologies to influence and shape my teaching

\[7\] Views on [collaborative learning](../BCB744/BCB744_index.qmd#sec-collab-learning)

\[8\] Example [exercises and bonus](../BCB744/intro_r/11-mapping_rnaturalearth.qmd#example), designed to reward and incentivise continued learning towards advanced skills

\[9\] [Assessment policy for BCB744](../BCB744/BCB744_index.qmd#sec-policy)

\[10\] Explanation of [modes of assessment](../pages/assessment_theory.qmd)

\[11\] [Module-specific graduate attributes](../pages/graduate_attributes.qmd)

\[12\] The difference between [science and data science](../BCB744/BCB744_index.qmd#sec-descr)

\[13\] Thoughts about the [learning process](../pages/how_to_learn.qmd)

\[14\] Access to [old test and exam questions](../BDC334/assessments/Class_tests.qmd)

## 4.1.2. Develop the Tangled Bank website in support of undergraduate and BSc (Hons) modules

\[15\] For an example of information rich text, see the [example page](../BCB744/basic_stats/02-summarise-and-describe.qmd)

\[16\] See the 'vignettes' menu at the top of The Tangled Bank.

\[17\] For example, the [FAQ page for BDC223](../BDC223/BDC223_FAQ.qmd)

\[18\] See [feedback from colleagues](../promotion_docs/Tangledbank_feedback.pdf) about The Tangled Bank

## 4.1.3. Feedback from external (peer) reviewers and students about above modules taught

\[19\] Prof. Sophie von der Heyden's [feedback about BCB743](../promotion_docs/course_evaluations/BCB743.pdf) in 2022

\[20\] Prof. Sophie von der Heyden's [feedback about BCB744](../promotion_docs/course_evaluations/BCB744.pdf) in 2022

\[21\] [BCB744 assessment policy](../BCB744/BCB744_index.qmd#sec-policy)

\[22\] [BCB743 assessment policy](../BCB743/BCB743_index.qmd#sec-policy)

\[23\] [BDC334 assessment policy](../BDC334/BDC334_index.qmd#sec-policy)

\[24\] Student feedback about BDC223, BDC334, BCB744, and BCB743 are available at the links below:

-   [BDC223](https://drive.google.com/drive/folders/1-daVKFX6_0adUFdqcGDkx2qe4dJwKNVB?usp=sharing)
-   [BDC334](https://drive.google.com/drive/folders/1-g75ZFDTUbkH67a7ezqSLEKfAtqSJkoG?usp=sharing)
-   [BCB744](https://drive.google.com/drive/folders/1-aT2H-yOrCO3CmO67ga-9IWwGTQENOS0?usp=sharing)
-   [BCB743](https://drive.google.com/drive/folders/1-c50c13Z2ICrqlZrpXE5uFC0FDxrSFac?usp=sharing)

## 4.1.4. Tangled Bank vignettes and reproducible research

\[25\] See my essay on eResearch and [reproducible research](../pages/reproducible_research.qmd)

\[26\] Dr [Robert Schlegel's GitHub](https://github.com/robwschlegel) page

\[27\] Ms [Amieroh Abrahams's GitHub](https://github.com/AmierohAbrahams) page

\[28\] Mr [Ross Coppin's GitHub](https://github.com/RossCoppin) page

\[29\] Examples of vignettes may be access at [The Tangled Bank](http://tangledbank.netlify.app) under the 'vignettes' menu at the top. For example:

-   [Retrieving Chlorophyll-a Data from ERDDAP Servers](https://tangledbank.netlify.app/vignettes/chl_erddap)
-   [Wavelet analysis of diatom time series](https://tangledbank.netlify.app/vignettes/elem_ts_methods.html)
-   [Event horizon plots](https://tangledbank.netlify.app/vignettes/mhw_mcs_horizonplots)

Other vignettes are at the [heatwaveR website](https://robwschlegel.github.io/heatwaveR/index.html) in the vignettes top menu.

# Part 4.2 Research

## 4.2.1. Successful and prolific funding attraction

\[30\] List of the more recent research funding received:

-   2020 -- 2022: Belmont Forum Collaborative Research Action on Transdisciplinary Research for Ocean Sustainability: Ecological and Economic impacts of the intensification of extreme events in the Benguela Upwelling System, Principal Investigator (EXEBUS) [PDF](../promotion_docs/research_funding/Belmont_Forum.pdf)

-   2019 -- 2021: SANOCEAN: Factors influencing the formation, fate and transport of microplastic in marine coastal ecosystems (FORTRAN) [PDF](../promotion_docs/research_funding/SANOCEAN_FORTRAN.pdf)

-   2019 -- 2021: SANOCEAN: Blue growth opportunities in changing kelp forests (BlueConnect) [PDF](../promotion_docs/research_funding/SANOCEAN_BlueConnect.pdf)

-   2019 -- 2023: Horizon 2020: iAtlantic, led by Prof. Murray Robert, own capacity as Regional Coordinator for the SE Atlantic [PDF](../promotion_docs/research_funding/iAtlantic.pdf)

\[31\] List of older nationally funded research

-   2019 -- 2021: NRF Global Change Grand Challenge: Earth System Science Research Programme --- Extreme Climatic Events in the Coastal Zone, Principal Investigator (ESS180920360856) [PDF](../promotion_docs/research_funding/NRF_ESSRP_2019.pdf)

-   NRF GRANT for 2018 -- 2020: Competitive Programme for Rated Researchers ---Upwelling dynamics in kelp beds: implications for trophic function [PDF](../promotion_docs/research_funding/NRF_CPRR_2018.pdf)

-   2017: CHEC/CCT Joint Research Programme 2017: What can kelp loss processes and beach cast patterns tell us about the sandy beach management? [PDF](../promotion_docs/research_funding/CHEC_CCT.pdf)

-   2015 -- 2017: NRF COMPETITIVE PROGRAMME FOR RATED RESEARCHERS (CPRR) --- Thermal characteristics of the South African nearshore: implications for biodiversity [PDF](../promotion_docs/research_funding/NRF_CPRR_2015.pdf)

-   2014 -- 2016: NRF COMPETITIVE PROGRAMME FOR RATED RESEARCHERS (CPRR) --- Kelps and climate change: South Africa in a global context [PDF](../promotion_docs/research_funding/NRF_CPRR_2014.pdf)

-   2014 -- 2016: NRF GRANT FOR 2014: INCENTIVE FUNDING FOR RATED RESEARCHERS (IPRR) Grant No. IFR14020764026 [PDF](../promotion_docs/research_funding/NRF_IFRR_2014.pdf)

\[32\] My thoughts about [the NRF rating system](NRF_ratings.qmd) and maintaining my own rating

## 4.2.2. Development of R packages in marine heatwave analysis

\[33\] The [RmarineHeatWaves](https://cran.r-project.org/web/packages/RmarineHeatWaves/RmarineHeatWaves.pdf) documentation.

\[34\] [heatwaveR](https://robwschlegel.github.io/heatwaveR/index.html). Also see the [GitHub](https://github.com/robwschlegel/heatwaveR/) page.

\[35\] This number is hard to track, but a search in Google Scholar for the term "heatwaveR" (inverted commas included) yields at least 150 citations. A shorter list of the citations is provided at https://robwschlegel.github.io/heatwaveR/CITATIONS.html. Notable examples of high-impact publications are provided here:

-   Smale, D. A., Wernberg, T., Oliver, E. C., Thomsen, M., Harvey, B. P., Straub, S. C., ... & Moore, P. J. (2019). Marine heatwaves threaten global biodiversity and the provision of ecosystem services. Nature Climate Change, 9(4), 306-312.
-   Barkhordarian, A., Nielsen, D. M., & Baehr, J. (2022). Recent marine heatwaves in the North Pacific warming pool can be attributed to rising atmospheric levels of greenhouse gases. Communications Earth & Environment, 3(1), 131.
-   Thoral, F., Montie, S., Thomsen, M. S., Tait, L. W., Pinkerton, M. H., & Schiel, D. R. (2022). Unravelling seasonal trends in coastal marine heatwave metrics across global biogeographical realms. Scientific Reports, 12(1), 7740.
-   Benedetti-Cecchi, L. (2021). Complex networks of marine heatwaves reveal abrupt transitions in the global ocean. Scientific Reports, 11(1), 1739.
-   Woolway, R. I., Jennings, E., Shatwell, T., Golub, M., Pierson, D. C., & Maberly, S. C. (2021). Lake heatwaves under climate change. Nature, 589(7842), 402-407.
-   García Molinos, J., Hunt, H. L., Green, M. E., Champion, C., Hartog, J. R., & Pecl, G. T. (2022). Climate, currents and species traits contribute to early stages of marine species redistribution. Communications biology, 5(1), 1329.
-   Smith, K. E., Burrows, M. T., Hobday, A. J., Sen Gupta, A., Moore, P. J., Thomsen, M., ... & Smale, D. A. (2021). Socioeconomic impacts of marine heatwaves: Global issues and opportunities. Science, 374(6566), eabj3593.

\[36\] Examples of cross-discipline research in marine heatwaves promoted by the heatwaveR package are provided here:

-   Schlegel, R. W., Oliver, E. C., & Chen, K. (2021). Drivers of marine heatwaves in the Northwest Atlantic: The role of air--sea interaction during onset and decline. Frontiers in Marine Science, 8, 627970.
-   Hu, L. (2021). A global assessment of coastal marine heatwaves and their relation with coastal urban thermal changes. Geophysical Research Letters, 48(9), e2021GL093260.
-   Barkhordarian, A., Nielsen, D. M., & Baehr, J. (2022). Greenhouse Gas Forcing a Necessary Causation for Marine Heatwaves Over the Northeast Pacific Warming Pool.

\[37\] Evidence of the application of the heatwaveR package outside of the initially intended field of application, marine science

-   Tassone, S. J., Besterman, A. F., Buelo, C. D., Ha, D. T., Walter, J. A., & Pace, M. L. (2023). Increasing heatwave frequency in streams and rivers of the United States. Limnology and Oceanography Letters, 8(2), 295-304.
-   Diniz, F. R., Gonçalves, F. L. T., & Sheridan, S. (2020). Heat wave and elderly mortality: Historical analysis and future projection for metropolitan region of São Paulo, Brazil. Atmosphere, 11(9), 933.
-   Woolway, R. I., Albergel, C., Frölicher, T. L., & Perroud, M. (2022). Severe Lake Heatwaves Attributable to Human‐Induced Global Warming. Geophysical Research Letters, 49(4), e2021GL097031.
-   Reynaert, S., De Boeck, H. J., Verbruggen, E., Verlinden, M., Flowers, N., & Nijs, I. (2021). Risk of short‐term biodiversity loss under more persistent precipitation regimes. Global Change Biology, 27(8), 1614-1626.
-   Woolway, R. I., Anderson, E. J., & Albergel, C. (2021). Rapidly expanding lake heatwaves under climate change. Environmental Research Letters, 16(9), 094013.
-   Paton, E. (2022). Intermittency analysis of dry spell magnitude and timing using different spell definitions. Journal of Hydrology, 608, 127645.
-   Martinez-Baroja, L., Rey-Benayas, J. M., Perez-Camacho, L., & Villar-Salvador, P. (2022). Drivers of oak establishment in Mediterranean old fields from 25-year-old woodland islets planted to assist natural regeneration. European Journal of Forest Research, 141(1), 17-30.
-   Pappert, D., Barriendos, M., Brugnara, Y., Imfeld, N., Jourdain, S., Przybylak, R., ... & Brönnimann, S. (2022). Statistical reconstruction of daily temperature and sea level pressure in Europe for the severe winter 1788/89. Climate of the Past, 18(12), 2545-2565.
-   Ngoungue Langue, C. G., Lavaysse, C., Vrac, M., & Flamant, C. (2023). Heat wave monitoring over West African cities: uncertainties, characterization and recent trends. Natural Hazards and Earth System Sciences, 23(4), 1313-1333.

\[38\] For studies that have used metrics calculated by heatwaveR in support of policy development around the management of marine living resources, see this list

-   Buenafe, K. C. V., Dunn, D. C., Everett, J. D., Brito-Morales, I., Schoeman, D. S., Hanson, J. O., ... & Richardson, A. J. (2022). A climate-smart spatial planning framework.
-   Wegscheider, B., Linnansaari, T., Monk, W., Ndong, M., Haralampides, K., St-Hilaire, A., ... & Allen, R. (2020). Quantitative modelling of fish habitat under future regulated and hydro-climatically driven flow regimes in the Saint John River (New Brunswick, Canada). Quantitative modelling of existing and future fish habitat in the Saint John River, NB, Canada, 184.
-   Buenafe, K. C. V., Dunn, D. C., Everett, J. D., Brito-Morales, I., Schoeman, D. S., Hanson, J. O., ... & Richardson, A. J. (2023). A metric-based framework for climate-smart conservation planning. Ecological Applications, e2852.
-   Muñoz-Pizza, D. M., Sanchez-Rodriguez, R. A., & Manzano, E. G. Linking Climate Change to Urban Planning Through Vulnerability Assessment: The Case of Two Cities at the Mexico-Us Border. Available at SSRN 4348277.

\[39\] Evidence of examples where such novel research questions and hypotheses have been addressed

-   Leach, T. S., BuyanUrt, B., & Hofmann, G. E. (2021). Exploring impacts of marine heatwaves: paternal heat exposure diminishes fertilization success in the purple sea urchin (Strongylocentrotus purpuratus). Marine Biology, 168(7), 103.
-   Pegado, M. R., Santos, C. P., Raffoul, D., Konieczna, M., Sampaio, E., Maulvault, A. L., ... & Rosa, R. (2020). Impact of a simulated marine heatwave in the hematological profile of a temperate shark (Scyliorhinus canicula). Ecological Indicators, 114, 106327.
-   Kraufvelin, L. (2021). Identification of marine heatwaves in the Archipelago Sea and experimental testing of their impacts on the non-indigenous Harris mud crab.
-   Oliveira, H., Maulvault, A. L., Santos, C. P., Silva, M., Bandarra, N. M., Valente, L. M., ... & Anacleto, P. (2023). Can marine heatwaves affect the fatty acid composition and energy budget of the tropical fish Zebrasoma scopas?. Environmental Research, 224, 115504.
-   Leach, T. S. (2022). The Role of Pre-and Post-Spawning Temperature Stress on Fertilization Dynamics Within Santa Barbara Channel Sea Urchin Species. University of California, Santa Barbara.
-   Minuti, J. J., Byrne, M., Hemraj, D. A., & Russell, B. D. (2021). Capacity of an ecologically key urchin to recover from extreme events: Physiological impacts of heatwaves and the road to recovery. Science of the Total Environment, 785, 147281.
-   Clare, X. S., Kui, L., & Hofmann, G. E. (2022). Larval Thermal Tolerance of Kellet's Whelk (Kelletia kelletii) as a Window into the Resilience of a Wild Shellfishery to Marine Heatwaves. Journal of Shellfish Research, 41(2), 283-290.
-   Marochi, M. Z., De Grande, F. R., Pardo, J. C. F., Montenegro, Á., & Costa, T. M. (2022). Marine heatwave impacts on newly-hatched planktonic larvae of an estuarine crab. Estuarine, Coastal and Shelf Science, 278, 108122.
-   Van Der Walt, K. A., Potts, W. M., Porri, F., Winkler, A. C., Duncan, M. I., Skeeles, M. R., & James, N. C. (2021). Marine Heatwaves Exceed Cardiac Thermal Limits of Adult Sparid Fish (Diplodus capensis, Smith 1884). Frontiers in Marine Science, 8, 702463.

\[40\] Various online trackers of marine heatwaves use heatwaveR as the underlying processing engine, some of which are reported on my ePortfolio

-   The [original marine heatwave tracker](http://www.marineheatwaves.org/tracker.html)
-   The [Physical Sciences Laboratory heatwave website](https://psl.noaa.gov/marine-heatwaves/)
-   [WhaleMap](http://whalemap.ocean.dal.ca/MHW/)

## 4.2.3. Student supervision

\[41\] Extract from the [NRFOnline system listing most of my post-graduate students](../promotion_docs/PG_supervision.pdf)

## 4.2.4. The South African Coastal Seawater Temperature Network (SACTN)

\[42\] The The South African Coastal Seawater Temperature Network [(SACTN) GitHub](https://github.com/ajsmit/SACTN) page from where data can be downloaded

\[43\] Smit, A. J., Roberts, M., Anderson, R. J., Dufois, F., Dudley, S. F., Bornman, T. G., ... & Bolton, J. J. (2013). A coastal seawater temperature dataset for biogeographical studies: large biases between in situ and remotely-sensed data sets around the coast of South Africa. [PLoS One, 8(12), e81944.](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0081944)

\[44\] A few personal well-cited publications that cite the SACTN:

-   Schlegel, R. W., Oliver, E. C., Wernberg, T., & Smit, A. J. (2017). Nearshore and offshore co-occurrence of marine heatwaves and cold-spells. [Progress in Oceanography, 151, 189-205.](https://www.sciencedirect.com/science/article/pii/S0079661116300830)
-   Schlegel, R. W., Oliver, E. C., Perkins-Kirkpatrick, S., Kruger, A., & Smit, A. J. (2017). Predominant atmospheric and oceanic patterns during coastal marine heatwaves. [Frontiers in Marine Science, 4, 323.](https://www.frontiersin.org/articles/10.3389/fmars.2017.00323/full)

## 4.2.5. Editorial contributions

\[45\] Associate Editor for [Aquatic Botany](https://www.sciencedirect.com/journal/aquatic-botany/about/editorial-board)

\[46\] My Reviewer's profile on Loop for editorial contributions to [Frontiers in Ecology & Evolution](https://loop.frontiersin.org/people/137774/overview)

## 4.2.6. Committees and programmes

# Part 4.3 Community Engagement

## 4.3.1. Academic Lead, Kelp Scientific Collaboration PPP

\[47\] [Kelp Scientific Collaboration mission statement](../promotion_docs/Kelp_collaboration/KelpCollaboration_MOI.pdf)

## 4.3.2. A research project, funded by SANOCEAN BlueConnect, about the perceived value of South African kelp

\[48\] [Perceived Value of Kelp](../promotion_docs/Akshata/GoldenForests2_AM.pdf)

\[49\] [Kelp, South Africa's Golden Forests on YouTube](https://www.youtube.com/watch?v=RuAO304Ip1s)

\[50\] [Akshata Mehta's MPhil thesis](../promotion_docs/Akshata/Thesis_AM.pdf)

## 4.3.3. BlueConnect engagements

\[51\] [Invitation letter to the GEAK workshop held in Norway](../promotion_docs/BlueConnect/GEAK-Blueconnect%20letter.pdf)

\[52\] [BlueConnect March 2020 Field Course](../promotion_docs/BlueConnect/Field_Course_combined.pdf)

## 4.3.4. Other community engagements and capacity-building contributions

\[53\] See most recent invitation to [participate in a capacity building initiative](../promotion_docs/Cape_Nature/Fishermen_capacity_building.pdf)

\[54\] Invitation quarterly [Kogelberg Marine Working Group meeting](../promotion_docs/Cape_Nature/Kogelberg_Marine_WG.pdf)

## 4.3.5. CoVID-19 Environmental Research Group

\[55\] [Smit et al (2020)](../promotion_docs/CERG/Smit_et%20al_2020.pdf) about CoVID-19

# Part 4.4 Professional Leadership

Please see Section 4.2.6 under "Part 4.2 Research."

# Part 4.5 Institutional Leadership

\[56\] Various [contributions](https://drive.google.com/drive/folders/12KbDb0JODFnuR6sWd45b4xmXZctXaDNS?usp=sharing) to initiatives that attempted to solve the PG administration process. See specifically my [latest plead to reinstate the planning and development process](https://drive.google.com/file/d/12Wy7Ou9u56dsroHVmgGQREd8Ymo-OACF/view?usp=sharing)
