---
date: "2023-04-24"
title: "National and international research grants"
number-sections: false
format: html
---

## International grants

-    2020 -- 2022: Belmont Forum Collaborative Research Action on Transdisciplinary Research for Ocean Sustainability: Ecological and Economic impacts of the intensification of extreme events in the Benguela Upwelling System, Principal Investigator (EXEBUS) [PDF](../promotion_docs/research_funding/Belmont_Forum.pdf)

-    2019 -- 2021: SANOCEAN: Factors influencing the formation, fate and transport of microplastic in marine coastal ecosystems (FORTRAN) [PDF](../promotion_docs/research_funding/SANOCEAN_FORTRAN.pdf)

-    2019 -- 2021: SANOCEAN: Blue growth opportunities in changing kelp forests (BlueConnect) [PDF](../promotion_docs/research_funding/SANOCEAN_BlueConnect.pdf)

-    2019 -- 2023: Horizon 2020: iAtlantic, led by Prof. Murray Robert, own capacity as Regional Coordinator for the SE Atlantic [PDF](../promotion_docs/research_funding/iAtlantic.pdf)

## National grants

-    2019 -- 2021: NRF Global Change Grand Challenge: Earth System Science Research Programme --- Extreme Climatic Events in the Coastal Zone, Principal Investigator (ESS180920360856) [PDF](../promotion_docs/research_funding/NRF_ESSRP_2019.pdf)

-    2018 -- 2020: NRF Competitive Programme for Rated Researchers ---Upwelling dynamics in kelp beds: implications for trophic function [PDF](../promotion_docs/research_funding/NRF_CPRR_2018.pdf)

-    2017: CHEC/CCT Joint Research Programme 2017: What can kelp loss processes and beach cast patterns tell us about the sandy beach management? [PDF](../promotion_docs/research_funding/CHEC_CCT.pdf)

-    2015 -- 2017: NRF Competitive Programme for Rated Researchers (CPRR) --- Thermal characteristics of the South African nearshore: implications for biodiversity [PDF](../promotion_docs/research_funding/NRF_CPRR_2015.pdf)

-    2014 -- 2016: NRF Competitive Programme for Rated Researchers (CPRR) --- Kelps and climate change: South Africa in a global context [PDF](../promotion_docs/research_funding/NRF_CPRR_2014.pdf)

-    2014 -- 2016: NRF Incentive Funding for Rated Researchers (IPRR) Grant No. IFR14020764026 [PDF](../promotion_docs/research_funding/NRF_IFRR_2014.pdf)
