---
date: "2023-04-24"
title: "Technology infusion and reproducible research"
number-sections: false
format: html
---


Coding skills supported by the intertwined technologies of [R](https://cran.r-project.org/), [RStudio IDE](https://posit.co/products/open-source/rstudio/), and [Quarto](https://quarto.org/) play a key role in my views on shaping modern-day learning and scientific processes. They equip students with the skills to become better collaborative learners and scientists. These technologies offer an extensive range of tools and libraries best known for data analysis, statistics, and visualisation. Coding skills and data analytical skills equip students to develop a deep understanding of complex data sets and derive meaningful insights from them, expanding their analytical thinking and problem-solving skills.

Recently, Quarto has become tightly integrated into the R 'ecosystem.' The website states that Quarto is "an open-source scientific and technical publishing system." At its heart, it is a dynamic document format based on R and Markdown. It enables students to create interactive, reproducible, well-documented reports, presentations, and websites that combine code, results, and narrative in a single document. **The Tangled Bank** was entirely developed within Quarto! This approach not only enhances students' communication skills by encouraging clear and concise explanations of their findings but also promotes transparency and reproducibility in research. By integrating code and results seamlessly, Quarto reduces errors, simplifies the updating process, and ensures that results remain consistent with the underlying data and methods. Quarto is the *de facto* mode of reporting and communication that students must adopt in BCB744 and BCB743. I am exploring the feasibility of introducing it into BDC334, as feedback indicates that students are keen to develop their coding skills earlier in their undergraduate degrees.

The collaborative potential of R and Quarto further empowers students to work effectively in interdisciplinary teams. Students can easily share their code, data, and findings using version control systems, such as Git (as implemented in [GitHub](https://github.com/)), alongside R and Quarto. This fosters a collaborative learning environment where students can collectively learn from each other's expertise, troubleshoot problems, and develop innovative solutions. Moreover, creating and sharing well-documented Quarto reports improves communication among team members, ensuring everyone is on the same page and facilitating smoother project execution.

Integrating these collaborative, open, transparent coding technologies into the teaching, learning, and scientific processes cultivates essential skills in students, such as critical thinking, problem-solving, communication, and collaboration. By leveraging these technologies, students become better equipped to tackle the challenges of today's data-driven research landscape, ultimately contributing to advancing science and developing innovative solutions to pressing global issues. These skills are also highly sought after in the workplace outside of science and academia and will significantly improve the employability of our graduates regardless of their future career paths.
