---
title: "Lecture 1: Worldmapper"
format:
  html:
    anchor-sections: true
    number-sections: true
    page-layout: article
  typst:
    toc: true
    section-numbering: 1.1.a
    columns: 1
---

::: callout-tip
## **Content**

- Limits to life in solar system.
- Earth is the only planet with life as far as we know.
- Life evolved and diversified.
- Our ancestors.
- Human societies developed during the Holocene.
- Modifcations to all life on Earth due to people’s impact.
- Exceeding planetary boundaries.
- Consequences for all life on Earth, including that of plants.
:::

::: callout-tip
## **Aims**

This lecture will provide students with an understanding of the concept of planetary boundaries and the significant role humans play in altering Earth’s environmental systems. I will offer a broad overview of how life on Earth has evolved over billions of years, and highlight the immense timescale involved in the diversification of life. I emphasise how humans, despite their relatively recent appearance, have profoundly affected the planet. By examining previous planetary-scale events, such as the Great Oxidation Event, we will explore how certain forms of life have historically altered Earth’s systems and contrast these with the current impact of human activity. This will lead to a discussion on the consequences of exceeding planetary boundaries, particularly focusing on how these changes affect plant life.
:::

::: callout-tip
## **Learning Outcomes**

By the end of this lecture, you will be able to:

1. Explain the concept of planetary boundaries and understand why they are critical for maintaining the stability of Earth’s systems, particularly those that support life.
2. Describe the evolutionary timeline of life on Earth, highlighting the immense time it took for life to diversify and comparing it to the brief period in which humans have existed.
3. Identify key planetary-scale events, such as the Great Oxidation Event, that were caused by the super-abundance of certain life forms, and explain their impact on Earth’s atmosphere and ecosystems.
4. Understand how human activity differs from natural events in terms of its rapid and wide-reaching impact on planetary systems, especially through the capacity for knowledge, learning, and technology.
5. Evaluate the impact of exceeding planetary boundaries on all life, with particular emphasis on the implications for plant ecophysiology and the survival of diverse ecosystems.
6. Reflect on the role of human societies in shaping Earth’s current environment, particularly during and after the Holocene, and recognise the critical need for sustainability to prevent further ecological damage.
:::

## Worldmapper
Today we'll get into the actual, the first portion of our real lecture content. Yesterday was an introduction to the module. Today we need to talk a little bit about setting the scene within which we're going to contextualise the plant ecophysiology component of your ecophysiology module. Generally, the way that I like to do this is to start by giving you a brief overview of the state of the world and the place of people in it, as it is often because of people that the various stresses that plants experience exist. People, because they are so numerous (as the argument often goes), are exerting a whole range of different influences on the planet, and I'd like to give you a brief overview of how that came to be. I'll call this set of lectures, or this set of slides, "the limits to life," because there are certain boundaries within which life can operate smoothly, and as we move outside of those boundaries (if we exceed some of those limits) then life is going to become increasingly difficult for all of us, including the plants that we are mostly interested in in this module. But the limits are exceeded because of people's influence on the planet.

As you know, Earth is the third planet from the Sun, and that's of major significance. The importance and the relevance of our position in the solar system, in between Venus and Mars, is because it creates a perfect set of conditions where everything is just right for life to exist. This is not true for Venus, which is the second planet from the Sun, and it's not true for Mars, either, which is the fourth planet from the Sun. The reason is that Venus is closer to the Sun, so it's just too hot. Mars is farther from the Sun, so it's just too cold. So, just like Goldilocks, Earth is just right. It's just right because water can exist in three phases that are necessary for the existence of life on the planet: water as liquid, as ice, and as water vapour (clouds). Without the ability of water to be present in all three of those phases, the hydrological cycle, as we know it, cannot operate. So this sets a series of limits within which life is easily able to exist. The limits are defined by the magnitude, the range of temperatures present on the planet. Even though water exists in liquid form between zero degrees Celsius and 100 degrees Celsius, life is constrained to only a smaller subset of that total range of temperatures. That's one set of limits.

That particular set of limits is shifting. It's changing. It's not constant. It hasn't been constant forever. But now, in more recent times, at least since the Industrial Revolution starting in the 1700s, the rate at which those limits are changing is accelerating. That's called anthropogenically-driven climate change. I'll talk a little bit about that later on in the module. And on Thursday, when I see you again, there's a whole module on just climate change, if I remember correctly.

In 1977, [Carl Sagan](https://en.wikipedia.org/wiki/Carl_Sagan) decided to take the spaceship [Voyager 1](https://science.nasa.gov/mission/voyager/voyager-1/) and rotate it to look back at Earth. That's the first time in human history that people could see Earth in its entirety from outside. Sagan called Earth "The Pale Blue Dot". When they looked back, it became evident that Earth is really quite unique as far as our knowledge of the entire solar system is concerned. Looking back to Earth from space (in this instance, this photograph is showing a view of Earth across the moon landscape) it showed that Earth is the only place we know of where life is able to exist. As we have explained before, it's because of the ability of water to be present as gas, liquid, and ice. You can see that in that particular image of Earth. You can see gas (the white bits: the clouds), you can see water, and on the polar regions, there's ice. There's Australia on the left-hand side and the big ocean is the Pacific Ocean. That was the first time it made people realise that Earth is the only place where life exists, and because there is only one such place that we know of, it's actually quite fragile. So we need to take care of it. We need to be aware that this is the only place where people can live.

There's a beautiful, very poetic piece of text that Carl Sagan wrote about how fragile life is on the planet; I'll send you a link that you can find on [YouTube](https://youtu.be/wupToqz1e2g?si=zbcVFy5o5QjQBHRw). Anyway, this is where this particular module is going to be looking at the Earth as a whole system and not necessarily at individual plants and animals, but at the whole Earth as a system; at how it is able to sustain life and the conditions necessary for life to persist. That's us again, that's Earth, looking down onto South Africa, with most of Africa in the top left-hand side. You can see Antarctica at the bottom, some clouds, and some swirling around in the atmosphere (the big atmospheric gyres that move water vapour and air around, which are the climate systems). The important thing about Earth, and it's critically important, is that without the oceans, life wouldn't exist as we know it. 70.8% of Earth's surface is covered in water, ocean water. It's because of that ocean water that conditions are just right for life to persist on the rest of the planet, because the oceans produce about 50% of the global supply of oxygen. The oceans are also very important in maintaining a very even temperature gradient across the entire planet. Without the oceans, Earth would be far hotter than we experience it today. The oceans buffer the fluctuations between day and night in temperatures. Ideally, we shouldn't call the planet Earth; we should call it 'Planet Ocean', because it's predominantly comprised of ocean water.

Now, let's look at some figures that I took from a website called [Worldmapper](https://worldmapper.org/). Worldmapper creates interesting images of typical maps, which are distorted based on the density of certain processes operating there. This is the normal map you know: a Mercator projection of the world. It's a familiar thing you've seen from a very young age at school. Everything seems to be in proportion to each other. But it's not. Mapping itself creates distortion in terms of land surface area. But this is familiar to you. As soon as we start changing the size of individual countries based on the number of people present there, or the amount of education present in the population, or carbon emissions per capita, then it distorts the whole view and puts emphasis on the places that have the biggest effect regionally and for the entire planet.

If we rewind the map to 2,000 years ago (year one on the modern calendar), this is where most of the people were. You can see how bloated some of the continents have become, especially Southeast Asia and Europe. There's also some distortion in South America due to the Inca and Maya populations, but mostly, most of the people then were present in Southeast Asia, Northern Asia, and Europe. Far fewer people in North America. New Zealand at the time wouldn't have had any people living on it. And if we roll forward 1,500 years, you can see how the populations are changing. Asia and Northern Europe stay about the same, though Asia expands a little. Look at North America 500 years ago -- see how much it's growing. That means that's when people started to become more abundant in North America. Places like Colombia also started to expand, but predominantly Africa is increasing in size. So, during the last 500 years or so, Africa has become very dominated by people. This is interesting and important because continuous population expansion is having a huge effect on the biodiversity of the planet, regionally as well as globally. This is the way by which people have an effect on the environment: by virtue of having a large number of people.

At the beginning of the previous century (1900), there were 1.56 billion people on the planet. Now, roll forward another 30 years from now, and we will have 9.8 billion people. Most of those people are going to be in Africa. See how big Africa is now compared to the rest of the world. Two years ago, Africa was already quite large, very bloated, and in 30 years from now, it will be even bigger: 4.11 billion people in Africa. That's possibly not a terribly good thing. But what's the reason for this? Why is Africa becoming so densely populated? Now we can look forward to the year 2100 and see how much more populated Africa will be. At the same time, many other places (like Europe and North America) are decreasing in population size. Especially in Canada, Australia, and New Zealand, there's negative population growth. But this continues to not be the case for South Africa and some places in Southeast Asia. Why is that? Why do Southeast Asia, South America, and Africa continue to grow faster and faster?

There has to be a reason for that. If we look at the demographics, in Southeast Asia and Africa. Those two places undergoing rapid population growth, there's an overabundance of very young people (between ages 0–4). That means people are actively being born all the time. If you look at older populations in countries where populations are actively growing, there are far fewer old people, whereas places like Northern Europe and North America have far more old people compared to very young people. That kind of demographic shows that the number of people on the planet is actually decreasing in some places, but not so in Southeast Asia and Africa.

In Africa and Southeast Asia, most people live in rural areas still, because urban development hasn't proceeded at the pace it has in North America and Europe. People continue to live in rural, impoverished (or so it is perceived by those who value urbanisation as a sign of progress) places in those countries. South Africa is an exception; people have managed to make a living in cities, and that continues to be a problem today as people leave rural areas for cities, which creates additional environmental problems. For the rest of Africa, people tend to be associated with rural areas, as urban and industrial development hasn't progressed much and it remains undeveloped.

In Africa and Southeast Asia, the bulk of the people live in absolute poverty, defined by the World Bank as an income of less than $1.90 (US) per day. Is it as simple as putting a statistics like an income value on people and then calling them poor if they fall below a certain threshold? No. But, according to this definition, most people in Southeast Asia and Africa live below the global poverty line; they can be classified as absolutely poor. It seems evident that the places where population growth is the fastest are also the places where people are poorest. This requires explanation: what is so unique about Southeast Asia and Africa that can explain both absolute poverty and the large populations? It seems counterproductive. If you know you are poor, why have more children if you cannot sustain them? It doesn't seem logical to most people.

Looking further, the places with high absolute poverty and high rates of population growth are also places where most women are not educated, compared to men. The crux of the explanation for rapid population growth is that, when women are not educated, the number of children they have tends to increase. As soon as education increases, women are empowered to have fewer children and the amount of money available to sustain families increases. But why are women less educated in those places?

For many years, especially in North America and Europe, because of the Industrial Revolution, a large amount of energy and effort went into sustaining economic wealth in those countries. As a result, there was excessive combustion of fossil fuels (coal, gas, oil) primarily in the global North, where industrialisation and education allowed economies to develop around these resources. Unfortunately, this came at a cost: excessive carbon dioxide went into the atmosphere. Countries in the North, where industrialisation is greatest, have been most instrumental in causing climate change since the 1900s. Africa—South Africa, in particular, is also one of these countries. Despite our developing status, South Africa is the most industrialised country in Africa, ranking among the highest global contributors to carbon emissions.

It seems that in countries actively developing their economies (Africa, including South Africa; North Africa; Saudi Arabia and the Middle East; China; Japan; Southeast Asia), carbon emissions are rising much faster, whereas in North America and Europe, emissions are decreasing a little. People have become aware of climate change in Europe, especially in the Scandinavian countries, and have done what they can to minimise their impact, and much of their electricity is from renewables. The United States, due to various political reasons, hasn't reduced emissions as much, but there have been reductions.

Healthcare: the poorest, fastest-growing places have the lowest healthcare, the highest child mortality, and the highest rates of HIV/AIDS. Greenhouse gases are greatest in already industrialised places. Most carbon dioxide sources are transportation, generation of heat and electricity, other fuel combustion, industry, and land use practices (deforestation, afforestation, reforestation, harvest management). Deforestation (removing forests from the landscape) causes a net positive gain of carbon dioxide. Agriculture, needed to sustain people, is a dangerous process in terms of greenhouse gas emissions, particularly methane and nitrous oxide, which are very potent greenhouse gases warming the atmosphere. As a result of rapid population growth in developing countries like Southeast Asia and Africa, agriculture has had to increase, which increased methane and nitrous oxide flow, and changes in land use to sustain agriculture and waste recycling have contributed further to carbon dioxide in the atmosphere.

That's why I emphasise population numbers and reasons for increase or decrease; they are strongly linked to greenhouse gas emissions. It's important in biology to understand what people are doing on the planet. Again, similar graphs show that if you look at methane and nitrous oxide, Southeast Asia and South America are anomalous in terms of their emissions. Why? In South America, a lot of cattle are produced... cattle release methane into the atmosphere. In Southeast Asia and China, rice production predominates, and rice cultivation releases large amounts of methane, as it is grown in saturated soils where anaerobic processes produce methane. We'll cover some of those processes later in the module.

Regarding sewage collection: in Africa and South America (the developing world) places with fastest-growing populations do not have the infrastructure needed to collect human waste, which goes directly into the environment, causing pollution. In Europe and North America, infrastructure is there to recycle and repurpose pollutants. In the global South, collection is inefficient and pollution from nitrogenous waste is increasing.

We can continue to talk about these processes—there are more slides, and you can look at them; please go to the Worldmapper website for more information, data sources, and explanations. Again, don't believe everything I say. Find secondary sources to support what I've explained.

Undernourishment: again, places where population growth is greatest are where people are undernourished, as they lack resources to sustain rapidly growing families. It seems counterintuitive to have more children when you are poor, but if you are not educated because you are prevented from being educated due to religious reasons, people don't think that way, and are perhaps discouraged from thinking critically.

Fish exports and forest depletion: in Southeast Asia, China, South Africa, North Africa, Brazil, Colombia, Panama, etc., there's significant deforestation to make land available for agriculture, agronomy, development of residential areas and cities. In Africa, forests are also cleared for biomass burning for heat and cooking.

Scientific research: the places with the highest GDP growth also have the most scientific research. South Africa stands out as unique in Africa for this, though not nearly to the extent of the global North.

## Planetary Boundaries
To set the scene for Thursday's talk: I need you to read the paper called "The Safe Operating Space for Humanity" by Johan Rockström and his team. I placed the paper on iKamva. Please read it, as it discusses boundaries we should not exceed for a habitable planet. I've spoken at length about climate change; there's also the nitrogen cycle and phosphorus cycle—these result from countries’ inability to properly capture and recycle waste. The limits to the nitrogen cycle have already been exceeded, and climate change is approaching dangerous levels. The biggest threat facing the planet now is biodiversity loss, which happens directly as a result of there being too many people—a problem that ties back to education and its other proximal causes.

That's where I'll stop now. For the rest of the module, I'll talk about climate change, ocean acidification, the nitrogen and phosphorus cycles, global freshwater use, and biodiversity loss—because each has consequences for how stressed plants are within the environment. Since people are affecting all these boundaries, people are indirectly responsible for the amount of stress that plants feel. So, how do plants perceive stress? What happens when they become stressed? What do they do to cope? That's what we'll discuss for the rest of the module.
