---
title: "Lecture 1. Plantetary Boundaries"
format:
  html:
    anchor-sections: true
    number-sections: true
    page-layout: article
---

# Content

- Limits to life in solar system.
- Earth is the only planet with life as far as we know.
- Life evolved and diversified.
- Our ancestors.
- Human societies developed during the Holocene.
- Modifcations to all life on Earth due to people’s impact.
- Exceeding planetary boundaries.
- Consequences for all life on Earth, including that of plants.

# Aims

This lecture will provide students with an understanding of the concept of planetary boundaries and the significant role humans play in altering Earth’s environmental systems. I will offer a broad overview of how life on Earth has evolved over billions of years, and highlight the immense timescale involved in the diversification of life. I emphasise how humans, despite their relatively recent appearance, have profoundly affected the planet. By examining previous planetary-scale events, such as the Great Oxidation Event, we will explore how certain forms of life have historically altered Earth’s systems and contrast these with the current impact of human activity. This will lead to a discussion on the consequences of exceeding planetary boundaries, particularly focusing on how these changes affect plant life.

# Learning Outcomes

By the end of this lecture, students will be able to:

1. Explain the concept of planetary boundaries and understand why they are critical for maintaining the stability of Earth’s systems, particularly those that support life.
2. Describe the evolutionary timeline of life on Earth, highlighting the immense time it took for life to diversify and comparing it to the brief period in which humans have existed.
3. Identify key planetary-scale events, such as the Great Oxidation Event, that were caused by the super-abundance of certain life forms, and explain their impact on Earth’s atmosphere and ecosystems.
4. Understand how human activity differs from natural events in terms of its rapid and wide-reaching impact on planetary systems, especially through the capacity for knowledge, learning, and technology.
5. Evaluate the impact of exceeding planetary boundaries on all life, with particular emphasis on the implications for plant ecophysiology and the survival of diverse ecosystems.
6. Reflect on the role of human societies in shaping Earth’s current environment, particularly during and after the Holocene, and recognise the critical need for sustainability to prevent further ecological damage.
