---
title: "Lecture 2: Surface Area to Volume (SA/V) Ratios in Biology"
format:
  html:
    anchor-sections: true
    number-sections: true
    page-layout: article
---

::: callout-tip
## This Lecture is Accompanied by the Following Lab

- [Lab 1: Surface Area to Volume (SA/V) Ratios in Biology](Lab1_SA_V.qmd)
:::

# Content

- Surface Area to Volume Ratio, a universal law in biology.
- Understanding the plant (and algal) body plan.
- The major 'functions' of plants that are affected by SA:V ratio.
- Littler and Litter's (1980) and Littler and Arnold's (1982) functional form model (in seaweeds).
- Extending the functional form model to seagrasses (distribution, ecophysiology, and ecological interactions).

# Aims

In this lecture, I will introduce students to the concept of the surface area to volume (SA:V) ratio as a fundamental biological principle that influences the structure and function of all living organisms. You will explore how this ratio affects the body plan and physiological processes of plants and algae,and how it shapes key functions such as nutrient absorption, gas exchange, and growth. We will delve into Littler and Littler’s (1980) and Littler and Arnold’s (1982) functional form model for seaweeds, which illustrates the ecological relevance of SA:V ratios in marine environments. Additionally, we will extend this model to seagrasses, and focus on their distribution, ecophysiology, and ecological interactions. The overarching goal is to equip you with the ability to connect this universal biological law to plant form and function in a variety of ecosystems.

# Learning Outcomes

By the end of this lecture, you will be able to:

1. Define the surface area to volume (SA:V) ratio and explain why it is a universal biological principle that governs the form and function of living organisms.
2. Understand the relationship between the SA:V ratio and plant body plans, with specific reference to how this ratio affects the structure and function of plants and algae.
3. Describe the major physiological functions of plants that are influenced by the SA:V ratio, such as nutrient uptake, gas exchange, and water balance.
4. Explain Littler and Littler’s (1980) and Littler and Arnold’s (1982) functional form model for seaweeds, identifying how the SA:V ratio plays a role in determining the ecological strategies of marine macroalgae.
5. Extend the functional form model to seagrasses, analysing how their SA:V ratio influences their distribution, physiological adaptations, and ecological interactions in marine ecosystems.
6. Apply the concept of SA:V ratios to broader ecological contexts, demonstrating an understanding of how this principle affects organismal form and function across terrestrial and marine environments.
