---
title: "Lecture 4. Perturbation to the Carbon Cycle"
format:
  html:
    anchor-sections: true
    number-sections: true
    page-layout: article
---

# Content

- The carbon cycle and climate change: a brief overview and history of our understanding of climate change.
- The contributions of key historical figures such as Arrhenius, Callendar, and Keeling.
- The role of the carbon cycle in climate change.
- Atmospheric response in heat content.
- The role and response of the ocean in the carbon cycle.
- Future scenarios for Earth.

# Aims

This lecture aims to provide you with a comprehensive understanding of the carbon cycle and its central role in driving climate change. You will explore the history of climate science, focusing on key figures like Svante Arrhenius, Guy Callendar, and Charles Keeling, whose contributions shaped our current understanding of global warming and atmospheric carbon. In the lecture, we will also cover how the carbon cycle influences the Earth’s heat content, the atmospheric and oceanic responses to increased carbon levels, and how these processes contribute to global change. Finally, you will briefly look at some future climate scenarios so as to develop insight into the potential consequences for Earth’s ecosystems, with a particular focus on the implications for plant ecophysiology.

# Learning Outcomes

After you've mastered this lecture's content, you will be able to:

1. Provide an overview of the carbon cycle and explain its importance in the context of climate change, particularly how carbon moves between the atmosphere, biosphere, oceans, and lithosphere.
2. Recall the contributions of key historical figures—Svante Arrhenius, Guy Callendar, and Charles Keeling—in shaping the science of climate change and the importance of their work in modern climate models.
3. Explain the role of the carbon cycle in driving climate change, including how anthropogenic carbon emissions disrupt natural carbon processes and contribute to global warming.
4. Explain the atmospheric response to increased carbon dioxide, focusing on the increase in heat content and the subsequent changes in global temperature and weather patterns.
5. Describe the role of the ocean in the carbon cycle, including its ability to act as a carbon sink, how it moderates global temperatures and pH, and the long-term consequences of oceanic carbon absorption on marine ecosystems.
6. Evaluate future climate change scenarios, discussing the potential impacts of continued carbon emissions on Earth’s climate, ecosystems, and plant ecophysiology, and the importance of mitigation strategies.
