---
title: "Lecture 5: Light"
format:
  html:
    anchor-sections: true
    number-sections: true
    page-layout: article
---

# Content

- Explain what light is, and explore concepts of frequency, wavelength, and energy.
- Describe the electromagnetic spectrum and the different types of light.
- Define the ideas of light quality and quantity.
- Explain how light is measured and the different units used.
- Focus on the quantum nature of light and the concept of photons.
- Discuss the importance of light in ecosystems.
- Explain photochemical equivalence.
- Explain the concept of photosynthetically active radiation (PAR) and its importance.
- Describe the different types of light sensors and their applications.
- Describe the Beer-Lambert Law and its applications.
- Explore the properties of the ocean that affect light penetration and variability.
- Explore the properties of the atmosphere and terrestrial systems that affect light availability and variability.

# Aims

Here I provide you with a thorough understanding of light as a critical factor in ecosystems, particularly its role in plant ecophysiology. The lecture will explore the physical properties of light, including its frequency, wavelength, and energy, and how these aspects interact with biological systems. You will gain insight into how light is measured, the concept of photosynthetically active radiation (PAR), and the quantum nature of light through the idea of photons. Finally, you will explore how the properties of terrestrial, atmospheric, and oceanic systems affect light availability and variability, including applications of the Beer-Lambert Law.

# Learning Outcomes

1. Explain the nature of light by understanding its frequency, wavelength, and energy, and how these properties relate to the electromagnetic spectrum.
2. Describe the electromagnetic spectrum and identify different types of light, including visible, ultraviolet, and infrared, and their relevance to biological systems.
3. Define the concepts of light quality and light quantity, explaining how each affects biological processes in plants and ecosystems.
4. Understand how light is measured and the units used, including those related to light intensity and energy, such as lumens, watts, and photons.
5. Explain the quantum nature of light and the concept of photons. This includes demonstrating an understanding of the additive nature of quantum light measurements.
6. Explain the concept of photochemical equivalence, and how it applies to the efficiency of light-driven processes in biological systems.
8. Understand Photosynthetically Active Radiation (PAR), its importance to photosynthesis, and how PAR is measured and applied in ecophysiological studies.
9. Identify different types of light sensors and their applications in measuring light quantity and quality in various environments.
10.	Describe the Beer-Lambert Law and its applications in understanding light attenuation in different media, such as water and plant canopies.
11.	Explore the properties of the ocean and atmosphere that affect light penetration, variability, and availability in both aquatic and terrestrial ecosystems, emphasising the environmental factors that influence light absorption and transmission.

