---
date: "2021-01-01"
title: "5. Species Dissimilarities"
subtitle: "Revisiting Dissimilarity Measures"
bibliography: ../references.bib
csl: ../marine-biology.csl
---

```{r code-brewing-opts, echo=FALSE}
knitr::opts_chunk$set(
  comment = "R>", 
  warning = FALSE, 
  message = FALSE,
  fig.width = 4.5,
  fig.height = 2.625,
  out.width = "75%",
  fig.asp = NULL, # control via width/height
  dpi = 300
)

ggplot2::theme_set(
  ggplot2::theme_minimal(base_size = 8)
)
ggplot2::theme_set(
  ggplot2::theme_bw(base_size = 8)
)
```

<!-- # Topic 5: Species dissimilarities -->

::: callout-tip
## **Material Required for This Chapter**

| Type        | Name                                     | Link                                                                           |
| --- --- --- --- -| --- --- --- --- --- --- --- --- --- --- --- --- --- --- | --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --|
| **Data**    | The Doubs River data                     | [💾 `Doubs.RData`](../data/BCB743/NEwR-2ed_code_data/NeWR2-Data/Doubs.RData)          |
:::

We have already covered all the necessary theory in BDC334 (see Labs [1](../BDC334/Lab-01-introduction.qmd), [2b](../BDC334/02b-env_dist.qmd), and [3 & 4](../BDC334/03-04-biodiversity.qmd)). The dissimilarity matrices that capture α-diversity and the contemporary measures of β-diversity are in fact *the same species dissimilarity matrices I refer to here under species dissimilarities*, and on which we will continue to rely on in the subsequent topics as input to many of the ordination techniques.

So, refer back to these Labs and remind yourselves what that is all about.

To test your understanding of this important topic, please address the following questions and submit next week Monday at 17:00 via GitHub.

:::{.callout-important}
## Lab 1

Using the Doubs River species data in [Numerical Ecology with R](http://adn.biol.umontreal.ca/~numericalecology/numecolR/):

1. Look at the dataset and explain its structure in words.

2. Would we use Bray-Curtis or Jaccard dissimilarities?

3. Apply the calculation.

4. Explain the meaning of the results in broad terms.

5. Examine it more closely: what general pattern comes out?

6. Plot this pattern (hint, it is best seen in the 1st column of the dissimilarity matrix).

7. What explanation can you offer for this pattern?

8. Using the `decostand()` function, create presence/absence data, and apply the appropriate `vegdist()` function to obtain a suitable dissimilarity matrix.

9. Create another plot and explain the pattern.
:::

:::{.callout-important}
## Submission Instructions

Submit a R script wherein you provide answers to Questions 1--9 by no later than
8:00 tomorrow.

Provide a **neat and thoroughly annotated** Rmarkdown file which
outlines the graphs and all calculations and which displays the
resultant distance matrix. Use separate tabs for the different
questions.

Please label the Rmarkdown and resulting HTML files as follows:

-   `BCB743_<first_name>_<last_name>_Lab_1.Rmd`, and

-   `BCB743_<first_name>_<last_name>_Lab_1.html`

(the `<` and `>` must be omitted as they are used in the example as
field indicators only).

Failing to follow these instructions carefully, precisely, and
thoroughly will cause you to lose marks, which could cause a significant
drop in your score as formatting counts for 15% of the final mark (out
of 100%).

Submit your Labs on iKamva when ready.
:::

## References

::: {#refs}
:::
