---
title: "BCB743"
subtitle: "Integrative Assignment"
author: 
  - "AJ Smit"
date: '2020/06/28 (updated: `r Sys.Date()`)'
title-block-banner: false
toc: false
format:
  html:
    toc: false
---

## The Assignment

In the light of all the possible analyses of the Doubs River study (i.e. the earlier PCA and CA analyses as well as the nMDS, RDA, CCA, and clustering techniques in the coming week), provide a full analysis of the Doubs River fish community structure study, focusing on:

1.  the environmental drivers,

2.  the fish community composition, and

3.  an integrative view of the environmental structuring of the fish community.

## Additional Information

You are welcome to suggest your own analyses, as necessary, to support the approaches already taken in the module. Your analysis must include one or several ordination techniques (with a justification for why they were selected), as well as a clustering approach. The more novelty you bring to the analysis the better for your marks.

Critically discuss your findings in the context of the work initially done by Verneaux et al. (2003). Note that a critical discussion necessitates looking at all major findings of Verneaux et al. (2003) in the light of what your own analyses tell you. In doing so, you must support your own reasoning for agreeing or disagreeing by providing substantiating rational reasoning.

A completely novel (and correct) data and theoretical analysis can earn you marks in excess of 100%.

## Instructions

Submit a R markdown script and the knitted output for the Integrative Assignment by no later than 11:59 on Friday 4 August 2023. Label the script as follows: **`BCB743_<Name>_<Surname>_Integrative_Assignment.qmd`** and **`BCB743_<Name>_<Surname>_Integrative_Assignment.html`** (or use MS Word format).

Unlike previous work in the module, this assignment will be submitted as a professionally formatted MS Word document that follows the author guidelines of South African Journal of Botany.

Your analysis must be structured as follows: Introduction (with Aims and Objectives), Methods, Results, Discussion, References (minimum 10 references, all of which were published *after* 2003).

The page limit for the full body of work must not exceed 20 pages (minimum 13 pages), with the Figures/Tables not occupying more than 25% of the total page count. In order to professionally arrange the figures (multiple figures per page, and liberal use of subplots), please make use of the **ggarrange** package.
