---
title: "9. Correspondence Analysis (CA)"
subtitle: "Task E"
author: 
  - "AJ Smit"
date: '2020/06/28 (updated: `r Sys.Date()`)'
title-block-banner: false
toc: false
format:
  html:
    toc: false
---

## Task E

1. How would you explain the patterns seen in the last four panels in the Correspondence Analysis Chapter?

2. Apply approaches taken from the analysis in the Correspondence Analysis Chapter to these datasets:
    i. [bird communities along elevation gradient in Yushan Mountain, Taiwan](https://www.davidzeleny.net/anadat-r/doku.php/en:data:ybirds);
    ii. [alpine plant communities in Aravo, France](https://www.davidzeleny.net/anadat-r/doku.php/en:data:aravo).

3. Discuss the patterns observed, and explain the ordination diagrams with particular reference to how the species are influenced by the major environmental drivers.

4. **(Bonus)** For bonus marks that could earn you 120/100, please see if you can recreate the bottom right figure for the species 'Cogo' using **ggplot2**. This will require digging deep into the ordination and ordisurf objects, creating dataframes for each layer of data, and assembling the graph manually.

::: callout-important
## Submission instructions

Submit a Quorto HTML document wherein you provide answers to Questions 1--4 by no later than 23:59 on 24 June 2024.

Provide a **neat and thoroughly annotated** Quarto/html files which outlines the graphs and all calculations and which displays the resultant distance matrix. Use separate tabs for the different questions.

Please label the Quarto and resulting HTML files as follows:

-   `BCB743_<first_name>_<last_name>_Task_E.qmd`, and

-   `BCB743_<first_name>_<last_name>_Task_E.html`

(the `<` and `>` must be omitted as they are used in the example as field indicators only).

Failing to follow these instructions carefully, precisely, and thoroughly will cause you to lose marks, which could cause a significant drop in your score as formatting counts for 15% of the final mark (out of 100%).

Submit your Labs to me by email.
:::
