---
title: "5. Correlations and Associations"
subtitle: "Task B"
author: 
  - "AJ Smit"
---

## Task B

1.  Using the Doubs River environmental data, create a plot of pairwise correlations.

2.  Name to two top positive and two top negative *statistically-significant* correlations.

3.  For each, discuss the mechanism behind the relationships. Why do these relationships exist?

4.  Why do we need to transpose the data? Demonstrate what happens when you don't transpose the data (use the species data).

5.  What are the properties of a transposed species table?

6.  What are the properties of an association matrix? How do these properties differ from that of a i) species dissimilarity matrix and from a ii) correlation matrix?

7.  What is the difference between `spp_assoc1` and `spp_assoc2`? Is the information contained in each markedly different from the other?

8.  Explain the kind of insight we are able to glean from a species association matrix.

::: callout-important
## Submission instructions

Submit a R script wherein you provide answers to Questions 1--8 by the deadline in the syllabus schedule.

Provide a **neat and thoroughly annotated** Quarto/html files which outlines the graphs and all calculations and which displays the resultant distance matrix. Use separate tabs for the different questions.

Please label the Quarto and resulting HTML files as follows:

-   `BCB743_<first_name>_<last_name>_Task_B.qmd`, and

-   `BCB743_<first_name>_<last_name>_Task_B.html`

(the `<` and `>` must be omitted as they are used in the example as field indicators only).

Failing to follow these instructions carefully, precisely, and thoroughly will cause you to lose marks, which could cause a significant drop in your score as formatting counts for 15% of the final mark (out of 100%).

Submit your Labs on iKamva when ready.
:::
