---
title: "Task G"
subtitle: "Integrative Assessment"
author: 
  - "AJ Smit"
date: '2024/07/02 (updated: `r Sys.Date()`)'
title-block-banner: false
toc: false
format:
  html:
    toc: false
---

This task uses the data described at the start of the Chapter 5 about [Multiple Regression](../../docs/The-Biostatistics-Book-Ch-3-5.pdf) in The Biostatistics Book. The data can be downloaded [here](../../data/seaweed/spp_df2.csv).

Please also refer to the chapter [Deep Dive into Gradients](../deep_dive.qmd) for the data description, and the chapter on [Seaweeds in Two Oceans: Beta-Diversity (Appendices)](../Seaweed_in_Two_Oceans_v2/two_oceans_appendices.qmd) for more information about the analyses that went into the paper.

In this task, you will develop a comprehensive data analysis, undertake model building, and provide an interpretation of the findings. In Questions a--d, your goal is to explore, analyse, and discuss the species composition and assembly processes of the seaweed flora around the coast of South Africa. For more information about the data and analysis, refer to @smit2017seaweeds. Question e is a reflection and assessment of some of the theory concepts covered in the course, and a test of some critical thinking about variable and model selection.

Begin by thoroughly reading the chapter on [Model Building](../model_building.qmd), then complete the following tasks:

a. **Unconstrained Ordinations:** Use an unconstrained analysis of your choice to explore the data in various meaningful ways. In typical exploratory data analysis (EDA), unconstrained methods can be helpful. You might also want to include various univariate maps that highlight the distribution of the species composition along the coast of South Africa or indicate the existence of spatial gradients.
b. **MLR Analyses:** Develop multiple linear regression models for the seaweed species composition ($\beta_\text{sim}$ and $\beta_\text{sne}$, represented by columns `Y1` and `Y2` in the dataset) using all the predictors available. Present the final model(s) that best describe the species assembly processes along the South African coast. The final model may or may not include all the predictors, and you must justify your variable and model selection.
c. **Constrained Ordination:** Apply a suitable constrained ordination technique to the data and compare the results with the multiple regression models. Discuss the differences and similarities between the two approaches.

To complete tasks a), b), and c), you will need to follow the model-building process outlined in the chapter (and in the [Model Building](../model_building.qmd) chapter). This includes:

- Guiding the reader through your approach and rationale for the study, commenting on how and why certain methods are used.
- Providing a detailed explanation of what the results mean in the context of the specific methodology employed (not in terms of the ecological theory, which is covered in task d)).
- Describing which variables are used in your analyses and why.
- Conducting data exploration and visualisation (EDA).
- Building models (including hypothesis statements, variable selection using VIF and forward selection, comparisons of nested models, and justifications for variable and model selection).
- Performing model diagnostics (when appropriate).
- Explaining the outputs of `summary()` and `anova()` (as applicable).
- Producing a Results section suitable for a scientific publication.
- **[40%]**

d. **Interpretation:** Integrate your results (from both the unconstrained ordination, MLR, and constrained ordination) with ecological theory. Discuss your findings in light of the appropriate ecological hypotheses that might explain the relationships between the predictors and the seaweed species composition. This section should be written as if for a peer-reviewed publication and must include references. Draw insights from the analysis of $\beta_\text{sør}$ developed in the Multiple Regression chapter and rely on the theory from the lecture material presented in Task A2.

- Task d) focuses on model interpretation and discussing the ecological relevance of the results.
- **[40%]**

e. **Additional questions:** To follow.

- **[20%]**

::: callout-important
## Submission instructions

Submit a R script wherein you provide answers to the questions by no later than 23:59 on 8 July 2024.

Provide a **neat and thoroughly annotated** Quarto/html files which outlines the graphs and all calculations and which displays the resultant distance matrix. Use separate tabs for the different questions.

Please label the Quarto and resulting HTML files as follows:

-   `BCB743_<first_name>_<last_name>_Task_G.qmd`, and

-   `BCB743_<first_name>_<last_name>_Task_G.html`

(the `<` and `>` must be omitted as they are used in the example as field indicators only).

Failing to follow these instructions carefully, precisely, and thoroughly will cause you to lose marks, which could cause a significant drop in your score as formatting counts for 15% of the final mark (out of 100%).

Submit your Labs on iKamva when ready.
:::
