---
title: "11a. non-Metric Multidimensional Scaling (nMDS)"
subtitle: "Task F"
author: 
  - "AJ Smit"
date: '2020/06/28 (updated: `r Sys.Date()`)'
title-block-banner: false
toc: false
format:
  html:
    toc: false
---

## Task F

1. Using two unconstrained ordination techniques of your choice, analyse the mite data in the **vegan** package. Provide a brief description and discussion of what you have found, and produce the R code.

2. Using two unconstrained ordination techniques of your choice (not already used in 1, above) analyse the dune data in the **vegan** package. Provide a brief description and discussion of what you have found, and produce the R code.

::: callout-important
## Submission instructions

Submit a R script wherein you provide answers to Questions 1--2 by no later than 8:00 tomorrow.

Provide a **neat and thoroughly annotated** Quarto/html files which outlines the graphs and all calculations and which displays the resultant distance matrix. Use separate tabs for the different questions.

Please label the Quarto and resulting HTML files as follows:

-   `BCB743_<first_name>_<last_name>_Task_F.qmd`, and

-   `BCB743_<first_name>_<last_name>_Task_F.html`

(the `<` and `>` must be omitted as they are used in the example as field indicators only).

Failing to follow these instructions carefully, precisely, and thoroughly will cause you to lose marks, which could cause a significant drop in your score as formatting counts for 15% of the final mark (out of 100%).

Submit your Labs on iKamva when ready.
:::
