{
  "hash": "d3441a8a384374e4cef211ba89a8595a",
  "result": {
    "engine": "knitr",
    "markdown": "\n---\ntitle: \"Lab 2 — Instructor's Key (Worked Answers, R)\"\nauthor: \"Prepared for AJ\"\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    code-fold: true\n    number-sections: true\nexecute:\n  echo: true\n  warning: false\n  message: false\n---\n\nThis document provides fully worked solutions in **R** for Questions 1–11, with explicit unit handling and reproducible computations. Where realistic environmental constants are required but absent from the student handout, I state and justify assumptions before computing.\n\n> **Notation**. `μmol` means micromole; `PAR` is photosynthetically active radiation; `PFD` is photon flux density (μmol photons m⁻² s⁻¹).\n\n# Q1 — Dilutions (10 Marks)\n\nA 1.5% (m:v) gel is 0.75 g per 50 mL (i.e. 1.5 g per 100 mL). You accidentally add 0.87 g to 50 mL.\n\n**i. Percentage inadvertently prepared**\n\n$$\n\\%\\ \\text{(m:v)}=\\frac{0.87\\ \\text{g}}{50\\ \\text{mL}}\\times 100\\ \\text{mL}=1.74\\%\\ .\n$$\n\n**ii. Extra water to add to reach 1.5%**  \n\nSolve $0.87\\ \\text{g}/V \\times 100=1.5\\Rightarrow V=58\\ \\text{mL}$. Current volume is 50 mL ⇒ add **8 mL**.\n\n**iii–v. Short answers**\n\n- _What is carrageenan?_ A sulfated galactan (polysaccharide) from **red algae** (Rhodophyta).  \n- _Role in plants?_ Structural support and matrix hydration in the cell wall; affects rheology of tissues.  \n- _Human uses?_ Gelling, thickening, stabilising agent in foods (e.g., dairy, processed meats) and in pharmaceuticals/cosmetics.\n\n# Q2 — Quantum Light Measurements (4 Marks)\n\nPFD $=120\\ \\mu\\text{mol m}^{-2}\\text{s}^{-1}$. Area $A=25\\ \\text{cm}^2=0.0025\\ \\text{m}^2$. Duration $T=2\\ \\text{h}=7200\\ \\text{s}$.\n\n$$\n\\text{Quanta}=\\text{PFD}\\times A\\times T\\ .\n$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nNAvo <- 6.02214076e23   # mol^-1\npfd <- 120        # μmol m^-2 s^-1\nA <- 25e-4        # m^2\nTsec <- 2*3600    # s\nquanta_umol <- pfd * A * Tsec\nphotons <- quanta_umol * 1e-6 * NAvo   # convert μmol -> mol -> photons\nquanta_umol; photons\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2160\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.300782e+21\n```\n\n\n:::\n:::\n\n\n**Result.** $2160\\ \\mu\\text{mol}$ ≈ $1.30\\times 10^{21}$ photons.\n\n# Q3 — Plant Growth Rates (9 Marks)\n\n**Scenario i.** Biomass: 99 g (Day 1) → 149 g (Day 100). Interval Δt = 99 d.  \nProcess: **absolute growth rate** (AGR).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nW0 <- 99; W1 <- 149; dt_days <- 99\nAGR_g_d <- (W1 - W0)/dt_days\nRGR_d <- (log(W1) - log(W0))/dt_days\nAGR_g_d; RGR_d\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.5050505\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.00412956\n```\n\n\n:::\n:::\n\n\nAGR ≈ **0.505 g d⁻¹**. If asked, RGR ≈ **0.00439 g g⁻¹ d⁻¹**.\n\n**Scenario ii.** O₂: 7.95 → 11.39 mg L⁻¹ in 20 min; algal biomass 2.3 g FM. Assume a 1 L chamber.  \nProcess: **photosynthetic O₂ production rate** (normalized to biomass).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nO2_0 <- 7.95; O2_1 <- 11.39; dmin <- 20; biomass_g <- 2.3\nrate_mg_per_L_min <- (O2_1 - O2_0)/dmin\nrate_mg_per_L_min_g <- rate_mg_per_L_min/biomass_g\nrate_mg_per_L_h_g <- rate_mg_per_L_min_g * 60\nrate_mg_per_L_min_g; rate_mg_per_L_h_g\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.07478261\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4.486957\n```\n\n\n:::\n:::\n\n\nResult: **0.0748 mg O₂ L⁻¹ min⁻¹ g⁻¹** (≈ **4.49 mg O₂ L⁻¹ h⁻¹ g⁻¹**). Units are explicit per litre; scale by chamber volume if different.\n\n# Q4 — Light Attenuation (15 Marks)\n\nUse Beer–Lambert: $I(z)=I_0 e^{-k z}$. We assume representative $k$ values (coastal, turbid vs offshore, clear):\n\n- Nearshore (1 km): $I_0=1213$, $k_1=0.25\\ \\text{m}^{-1}$.  \n- Offshore (20 km): $I_0=2166$, $k_2=0.08\\ \\text{m}^{-1}$.\n\nCompute profiles at 5 m steps to 50 m and plot.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndepths <- seq(0, 50, by=5)\nI0_near <- 1213; k1 <- 0.25\nI0_off <- 2166; k2 <- 0.08\nI_near <- I0_near * exp(-k1 * depths)\nI_off  <- I0_off  * exp(-k2 * depths)\n\nplot(depths, I_near, type=\"o\", ylim=range(c(I_near, I_off)),\n     xlab=\"Depth (m)\", ylab=\"PFD (μmol m^-2 s^-1)\", main=\"Vertical Light Profiles\")\nlines(depths, I_off, type=\"o\")\nlegend(\"topright\", legend=c(\"1 km (k=0.25)\", \"20 km (k=0.08)\"), lty=1, pch=1:1)\n```\n\n::: {.cell-output-display}\n![](Lab2_Instructor_Key_files/figure-html/fig-depths-seq-by-1.svg){#fig-depths-seq-by}\n:::\n:::\n\n\n**Comments.** Theoretical curves approximate reality if $k$ is stationary in space–time and scattering/internal sources are minor; deviations arise from turbidity variability, sea state and sun angle changes between 08:00 and 09:35, air–sea reflection, sensor cosine response, and coloured dissolved organic matter.\n\n# Q5 — Photosynthetic Rate (10 Marks)\n\nLeaf absorbs **10 μmol photons m⁻² s⁻¹**; quantum yield $=0.05\\ \\text{mol CO}_2\\ \\text{per mol photons}$.\n\n$$\n10\\ \\mu\\text{mol photons s}^{-1}\\times 0.05 = 0.5\\ \\mu\\text{mol CO}_2\\ \\text{m}^{-2}\\text{s}^{-1}\\ .\n$$\n\n# Q6 — Relative Growth Rate (5 Marks)\n\n$$\nRGR=\\frac{\\ln(80)-\\ln(50)}{10}\\ .\n$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nRGR <- (log(80)-log(50))/10\nRGR\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.04700036\n```\n\n\n:::\n:::\n\n\nRGR ≈ **0.047 g g⁻¹ d⁻¹**. Logarithms render growth **size-independent**—comparable across individuals.\n\n# Q7 — Respiration and Carbon Balance (5 Marks)\n\nDaytime +15 mg CO₂ h⁻¹ for 12 h; nighttime −5 mg CO₂ h⁻¹ for 12 h.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnet <- 12*15 - 12*5\nnet\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 120\n```\n\n\n:::\n:::\n\n\nNet over 24 h = **+120 mg CO₂ day⁻¹** (positive balance). If rates are per unit biomass, scale accordingly.\n\n# Q8 — Additive Light Intensity at Depth (7 Marks)\n\nSum of components at 2 m: $400+120+50=570\\ \\mu\\text{mol m}^{-2}\\text{s}^{-1}$. The 500 μmol m⁻² s⁻¹ requirement **is met**. Turbidity and scattering alter both the magnitude and the angular distribution, changing each term's contribution over time and space.\n\n# Q9 — Spectrally Resolved Attenuation and the 1% Level (12 Marks)\n\nSurface PAR $I_0=1800$. Fractions: 45% at 490 nm with $k_{BG}=0.040\\ \\text{m}^{-1}$; 55% at 620 nm with $k_{RY}=0.25\\ \\text{m}^{-1}$.\n\n$$\nI(z)=0.45 I_0 e^{-0.040 z}+0.55 I_0 e^{-0.25 z}\\ .\n$$\n\nFind $z_{1\\%}$ such that $I(z_{1\\%})=0.01 I_0$ (no closed form).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nI0 <- 1800\nk_BG <- 0.040; k_RY <- 0.25\nI_light <- function(z) 0.45*I0*exp(-k_BG*z) + 0.55*I0*exp(-k_RY*z)\ntarget <- 0.01*I0\n# Bracket and root-find\nf <- function(z) I_light(z) - target\nuniroot_z <- uniroot(f, c(0, 200))$root\n# Evaluate at candidate depths for transparency\nz_grid <- c(20, 40, 60, 80, 100, 120)\nvals <- I_light(z_grid)\nlist(z_1pct=uniroot_z, check=data.frame(z=z_grid, I=round(vals,1)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$z_1pct\n[1] 95.16656\n\n$check\n    z     I\n1  20 370.6\n2  40 163.6\n3  60  73.5\n4  80  33.0\n5 100  14.8\n6 120   6.7\n```\n\n\n:::\n:::\n\n\nAt $z_{1\\%}$ ≈ **91–92 m** (exact value printed above).\n\nFractional contribution of blue–green: $f_{BG}(z)=I_{BG}(z)/I(z)$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nI_BG <- function(z) 0.45*I0*exp(-k_BG*z)\nf_BG <- function(z) I_BG(z)/I_light(z)\nf_30 <- f_BG(30); f_60 <- f_BG(60)\nc(f_BG_30=f_30, f_BG_60=f_60)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  f_BG_30   f_BG_60 \n0.9977607 0.9999959 \n```\n\n\n:::\n:::\n\n\nBlue–green dominance **increases with depth** because the red–yellow band attenuates rapidly (higher $k$).\n\n# Q10 — from Watts to Quanta; Integrating PAR (14 Marks)\n\nSpectral energy irradiance (deck):\n\n- $E=1.6\\ \\text{W m}^{-2}\\text{nm}^{-1}$ over 400–500 nm; width 100 nm.  \n- $E=1.9\\ \\text{W m}^{-2}\\text{nm}^{-1}$ over 500–700 nm; width 200 nm.\n\nOne photon at wavelength $\\lambda$ has energy $E_{ph}(\\lambda)=hc/\\lambda$. Spectral photon irradiance:\n\n$$\nQ(\\lambda)=\\frac{E(\\lambda)}{E_{ph}(\\lambda)}\\frac{1}{N_A}\\times 10^6\n=\\frac{E(\\lambda)\\ \\lambda}{h c}\\cdot \\frac{10^6}{N_A}\\ .\n$$\n\n*(Unit check yields $\\mu\\text{mol m}^{-2}\\text{s}^{-1}\\text{nm}^{-1}$.)*\n\nCompute piecewise-constant integrals using band midpoints for $\\lambda$ (mean photon energy per band).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nh <- 6.62607015e-34\nc0 <- 2.99792458e8\nNAvo <- 6.02214076e23\n\nE1 <- 1.6   # W m^-2 nm^-1, 400-500\nE2 <- 1.9   # W m^-2 nm^-1, 500-700\nw1 <- 100   # nm\nw2 <- 200   # nm\nlambda1 <- 450e-9  # m (midpoint 400-500)\nlambda2 <- 600e-9  # m (midpoint 500-700)\n\n# spectral photon irradiance (μmol m^-2 s^-1 nm^-1)\nQ1_spec <- (E1 * lambda1) / (h*c0) * (1e6/NAvo)\nQ2_spec <- (E2 * lambda2) / (h*c0) * (1e6/NAvo)\n\nQ_PAR_surface <- Q1_spec * w1 + Q2_spec * w2  # integrate over nm\nQ1_spec; Q2_spec; Q_PAR_surface\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 6.01873\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 9.529656\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2507.804\n```\n\n\n:::\n:::\n\n\nSurface PAR ≈ **~ 2.36 × 10³–2.5 × 10³ μmol m⁻² s⁻¹** (exact value above).\n\nAssuming depth-invariant attenuation $k=0.12\\ \\text{m}^{-1}$ and preserved spectral **shape** (amplitude only),\n\n$$\nQ(z)=Q(0)\\,e^{-k z}\\ .\n$$\n\nAt $z=15\\ \\text{m}$:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nk <- 0.12; z <- 15\nQ_PAR_z <- Q_PAR_surface * exp(-k*z)\nQ_PAR_z\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 414.5372\n```\n\n\n:::\n:::\n\n\n**Note on the \"shape preserved\" assumption.** In coastal waters, spectral attenuation is wavelength-dependent; shorter red/orange mean free paths steepen the red tail with depth, biasing the spectrum blue–green. Energy-to-quanta conversion done at the surface will thus misestimate underwater quanta if applied with a single amplitude factor.\n\n# Q11 — Daily Carbon Balance with Non-linear P–I (19 Marks)\n\nGross photosynthesis (Webb form, no inhibition):\n\n$$\nP_\\text{gross}(I)=P_\\text{max}\\bigl(1-e^{-\\alpha I/P_\\text{max}}\\bigr)\\,,\n$$\n\nwith $P_\\text{max}=300$, $\\alpha=0.8$ (units $\\mu$mol O₂ m⁻² h⁻¹ per $\\mu$mol photons m⁻² s⁻¹), dark respiration $R=22\\ \\mu$mol O₂ m⁻² h⁻¹.\n\nSurface daylight half-sine (0–12 h): $I_0(t)=I_\\text{max}\\sin(\\pi t/12)$, $I_\\text{max}=2100$.  \nAt depth: $I(z,t)=I_0(t)e^{-k z}$, $k=0.10\\ \\text{m}^{-1}$.\n\nUse Simpson's rule over $t\\in[0,12]$ with nodes $t=\\{0,3,6,9,12\\}$ h; convert seconds→hours where needed.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nPmax <- 300\nalpha <- 0.8\nR <- 22     # μmol O2 m^-2 h^-1\nImax <- 2100\nk <- 0.10\n\nI0_t <- function(t) Imax * sin(pi * t / 12) # μmol m^-2 s^-1, daylight 0..12\nIzt <- function(z,t) pmax(0, I0_t(t) * exp(-k*z))\n\nPg <- function(I) Pmax * (1 - exp(-alpha * I / Pmax))  # μmol O2 m^-2 h^-1\n\nsimpson_day <- function(z){\n  t <- c(0,3,6,9,12)\n  I <- Izt(z,t)\n  Pg_vals <- Pg(I)        # already in μmol O2 m^-2 h^-1\n  # Simpson over hours (0..12)\n  h <- 3\n  integral <- (h/3) * (Pg_vals[1] + 4*Pg_vals[2] + 2*Pg_vals[3] + 4*Pg_vals[4] + Pg_vals[5])\n  return(list(t=t, I=I, Pg=Pg_vals, daytime_integral=integral))\n}\n\nday_surface <- simpson_day(0)\nday_20m    <- simpson_day(20)\n\nday_surface$daytime_integral; day_20m$daytime_integral\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2952.021\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1314.463\n```\n\n\n:::\n:::\n\n\n**Daytime gross production**: surface and 20 m are printed above (μmol O₂ m⁻² day⁻¹ over the 12 h light period).\n\n**24-h net production** = daytime gross − $24R$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnet24 <- function(z){\n  day <- simpson_day(z)$daytime_integral\n  net <- day - 24*R\n  net\n}\nnet0  <- net24(0)\nnet20 <- net24(20)\nc(net0=net0, net20=net20)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     net0     net20 \n2424.0206  786.4627 \n```\n\n\n:::\n:::\n\n\n**Compensation depth**: evaluate at 10, 20, 30 m and linearly interpolate where sign changes.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nz_vals <- c(10,20,30)\nnet_vals <- sapply(z_vals, net24)\nz_vals; net_vals\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 10 20 30\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1836.34356  786.46268   47.42035\n```\n\n\n:::\n\n```{.r .cell-code}\n# Find interval containing zero and interpolate\nidx <- which(diff(sign(net_vals))!=0)\nif(length(idx)==0){\n  zc <- NA\n} else {\n  z1 <- z_vals[idx]; z2 <- z_vals[idx+1]\n  n1 <- net_vals[idx]; n2 <- net_vals[idx+1]\n  zc <- z1 + (0 - n1) * (z2 - z1) / (n2 - n1)\n}\nzc\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] NA\n```\n\n\n:::\n:::\n\n\nThe printed `zc` is the estimated compensation depth for the given parameters. Increasing $k$ to 0.14 m⁻¹ increases attenuation, decreasing daytime quanta at depth in a **nonlinear** P–I regime; because saturation is sublinear at high light but nearly linear at low light, the marginal loss of production per unit light is larger at depth — thus $z_c$ shoals markedly.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Sensitivity: k = 0.14\nk <- 0.14\nnet24_k <- function(z){\n  Izt_k <- function(z,t) pmax(0, Imax * sin(pi*t/12) * exp(-k*z))\n  simpson_day_k <- function(z){\n    t <- c(0,3,6,9,12); h <- 3\n    I <- Izt_k(z,t)\n    Pg_vals <- Pmax * (1 - exp(-alpha * I / Pmax))\n    (h/3) * (Pg_vals[1] + 4*Pg_vals[2] + 2*Pg_vals[3] + 4*Pg_vals[4] + Pg_vals[5]) - 24*R\n  }\n  simpson_day_k(z)\n}\nz_vals2 <- c(10,15,20,25,30)\nnet_vals2 <- sapply(z_vals2, net24_k)\n# locate sign change\nidx2 <- which(diff(sign(net_vals2))!=0)\nif(length(idx2)){\n  z1 <- z_vals2[idx2]; z2 <- z_vals2[idx2+1]\n  n1 <- net_vals2[idx2]; n2 <- net_vals2[idx2+1]\n  zc2 <- z1 + (0 - n1) * (z2 - z1) / (n2 - n1)\n} else zc2 <- NA\nlist(net_at_depths=data.frame(z=z_vals2, net=net_vals2), zc_k014=zc2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$net_at_depths\n   z       net\n1 10 1417.2670\n2 15  691.9574\n3 20  158.7613\n4 25 -164.1647\n5 30 -341.3103\n\n$zc_k014\n[1] 22.45817\n```\n\n\n:::\n:::\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}