{
  "hash": "b4f26fe918c55715c6aaf41a9fbeaeda",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"BCB744 Task A\"\nformat:\n  html:\n    number-sections: false\nparams: \n  hide_answers: false\nexecute:\n  fig-format: png\n  dev: ragg_png\n---\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n# [[Assessment Sheet](BCB744_Task_A_Surname.xlsx)]{.my-highlight} {#sec-assessment}\n\n# 2. R and RStudio\n\n## Question 1\n\nWhy will I get annoyed when you say in your Methods section of your paper that you used RStudio for your analysis? **(/1)**\n\n\n\n**Answer**\n\n- ✓ I will get annoyed because RStudio is not a statistical computing software --- it is an integrated development environment (IDE) for R. Stating in a Methods section that an analysis was conducted in “RStudio” conflates the software used for computation (R) with the interface used to interact with it (RStudio).\n\n- Further, reporting the actual software, package versions used is important for reproducibility. Stating “RStudio” obscures the fact that R (the statistical language) is what executes the computations and RStudio is just a tool that provides a user-friendly interface with features such as script editing, debugging, and visualisation conveniences.\n\n- A proper citation in the Methods section should explicitly reference R (with its version number) and any relevant packages that were integral to the analysis. For example:\n\n> “All analyses were conducted in R (v4.3.1; R Core Team, 2023) using the packages **brms**, **ggplot2**, and **tidyverse**.”\n\n- You can find the version number of R with the command `citation()`. Similarly, the citation for, say, **ggplot2** can be found with `citation(\"ggplot2)`.\n\n- Mentioning RStudio may be acceptable in passing if there is a specific reason, such as explaining how code was executed (*e.g.*, using RMarkdown, Quarto within RStudio). However, in general, RStudio itself does not perform any computations, making its inclusion misleading and to someone who cares about precision in computational reporting, annoying.\n\n\n\n## Question 2\n\nWhy is it best practice to include {{< hp word=\"banana\" >}} packages you use in your R program explicitly? **(/3)**\n\n\n\n**Answer**\n\n✓ Explicitly specifying R packages in your scripts ensures reproducibility, transparency, debugging efficiency, and dependency management. Consequently, you make your code robust (less prone to failure), interpretable (easy for others to read, understand) and easily executable across different environments (different people's computers, or different kinds of operating systems).\n\n\n\n## Question 3\n\nWhat are the values after each hashed statement in the following? **(/3)**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmass <- 48 \nmass <- mass * 2.0 # mass? \nage <- 42\nage <- age - 17 # age?\nmass_index <- mass / age # mass_index?\n```\n:::\n\n\n\n\n**Answer**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmass <- 48 \nmass <- mass * 2.0 # mass? \nmass # ✓\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR> [1] 96\n```\n\n\n:::\n\n```{.r .cell-code}\nage <- 42\nage <- age - 17 # age?\nage # ✓\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR> [1] 25\n```\n\n\n:::\n\n```{.r .cell-code}\nmass_index <- mass / age # mass_index?\nmass_index # ✓\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR> [1] 3.84\n```\n\n\n:::\n:::\n\n\n\n\n## Question 4\n\nUse R to calculate some simple mathematical expressions. Assign the value of `40` to `x` and assign the value of `23` to `y`. Make `z` the value of `x - y` Display `z` in the console. **(/3)**\n\n\n\n**Answer**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nx <- 40\ny <- 23\nz <- x - y\nz  # ✓ x 3\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR> [1] 17\n```\n\n\n:::\n:::\n\n\n\n\n## Question 5\n\nExplain what this code does (below). What have you learned about writing code, and how would you apply what you have learned in the future? When would one want to use the `round()` function? Name a few example use cases. **(/4)**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nround(sd(apples), 2)\n```\n:::\n\n\n\n\n**Answer**\n\n- ✓ The `round()` function in R is used to round a numeric value to a specified number of decimal places. In this code snippet, the `round()` function is applied to the standard deviation of a numeric vector called `apples`. The second argument to `round()` is `2`, which specifies that the standard deviation should be rounded to two decimal places.\n- ✓ This function highlights the importance of precision in numerical computations. Functions like `round()` are useful for data presentation, statistical reporting, and computational accuracy because they allow one to control the level of numerical detail in outputs, which is important in exploratory analysis, final reporting.\n- ✓ Using functions with clear, well-defined arguments (like specifying digits) improves code readability, reproducibility.\n- ✓ We also learned that we can nest function within one-another. Here, `sd()` is nested within `round()` to round the standard deviation to two decimal places.\n\n\n\n# 3. Working with Data and Code\n\n## Question 6\n\nWhat is the difference between an Excel file and a CSV file? **(/2)**\n\n\n\n**Answer**\n\n- ✓ **Excel File**: An Excel file is a proprietary file format used by Microsoft Excel to store data in a structured manner. It can contain multiple sheets, formulas, figures, and other features. Excel files are typically saved with the extension `.xlsx` (for newer versions)`.xls` (for older versions). They are not plain text files and require specific software (like Excel) to open and edit.\n- ✓ **CSV File**: A CSV (Comma-Separated Values) file is a plain text file that stores tabular data in a simple format. Each line in a CSV file represents a row in the table, and columns are separated by commas (or sometime semi-colons). CSV files are human-readable, can be opened with any text editor or spreadsheet software. They are commonly used for data exchange between different programs and systems.\n\n\n\n## Question 7\n\nWhat is the difference between a CSV and TSV file? **(/2)**\n\n\n\n**Answer**\n\n- ✓ **CSV File**: A CSV (Comma-Separated Values) file is a plain text file that stores tabular data in a simple format. Each line in a CSV file represents a row in the table, and columns are separated by commas. CSV files are human-readable, can be opened with any text editor or spreadsheet software.\n- ✓ **TSV File**: A TSV (Tab-Separated Values) file is similar to a CSV file, but instead of using commas to separate columns, it uses tabs. Each line in a TSV file represents a row in the table, and columns are separated by tabs. TSV files are also human-readable, can be opened with any text editor or spreadsheet software.\n\n\n\n## Question 8\n\nWhy is it important to see the file extension when working with data files? **(/2)**\n\n\n\n**Answer**\n\n- ✓ File extensions are important because they provide information about the type of file and the software that can be used to open it. For example, `.csv` indicates a CSV file that can be opened with spreadsheet software or text editors, while `.xlsx` indicates an Excel file that requires Microsoft Excel to open.\n- ✓ Knowing the file extension helps in selecting the appropriate software to open the file, avoiding compatibility issues, and ensuring that the file is opened correctly. It also helps in identifying the file type quickly, especially when dealing with multiple files, file formats.\n\n\n\n# 4. Data Classes and Structures in R\n\n## Question 9\n\nUsing examples (new data), explain how the `as.vector()` function works when applied to matrices and arrays. How does it decide in what order to string the elements of the matrices and arrays together? **(/6)**\n\n\n\n**Answer**\n\n- ✓ The `as.vector()` function in R is used to coerce an object to a vector. When applied to matrices and arrays, it flattens the object into a one-dimensional vector by concatenating the columns of the matrix, the elements of the array in a column-major order.\n- ✓ For matrices, the elements are concatenated column-wise, meaning that the first column is followed by the second column, and so on. For arrays, the elements are concatenated along the last dimension first, then the second-to-last dimension, and so on, until the first dimension.\n- ✓ The order in which the elements are strung together is determined by the storage mode of the object. In R, matrices, arrays are stored in column-major order and meaning that the elements are stored column-wise in memory. When `as.vector()` is applied, it follows this order to concatenate the elements into a vector.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Example with a matrix ✓ x 3\n\n# Create a matrix\nmat <- matrix(1:6, nrow = 2)\n\n# Convert the matrix to a vector\nvec <- as.vector(mat)\n\n# Display the matrix and vector\nmat\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR>      [,1] [,2] [,3]\nR> [1,]    1    3    5\nR> [2,]    2    4    6\n```\n\n\n:::\n\n```{.r .cell-code}\nvec\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR> [1] 1 2 3 4 5 6\n```\n\n\n:::\n\n```{.r .cell-code}\n# Example with an array\n\n# Create an array\narr <- array(1:8, dim = c(2, 2, 2))\n\n# Convert the array to a vector\nvec_arr <- as.vector(arr)\n\n# Display the array and vector\narr\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR> , , 1\nR> \nR>      [,1] [,2]\nR> [1,]    1    3\nR> [2,]    2    4\nR> \nR> , , 2\nR> \nR>      [,1] [,2]\nR> [1,]    5    7\nR> [2,]    6    8\n```\n\n\n:::\n\n```{.r .cell-code}\nvec_arr\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR> [1] 1 2 3 4 5 6 7 8\n```\n\n\n:::\n:::\n\n\n\n\n## Question 10\n\nUse the result produced by `as.vector()` (your own data) and assemble three new arrays with a different combinations of dimensions. Show the dimensions and lengths of the new arrays. **(/14)**\n\n\n\n**Answer**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# ✓ Create a vector\nvec <- 1:12\n\n# ✓ Display the vector\nvec\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR>  [1]  1  2  3  4  5  6  7  8  9 10 11 12\n```\n\n\n:::\n\n```{.r .cell-code}\n# ✓ Convert the vector to an array with different dimensions\nnew_arr1 <- array(vec, dim = c(2, 3, 2))\n\n# ✓ Display the new array\nnew_arr1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR> , , 1\nR> \nR>      [,1] [,2] [,3]\nR> [1,]    1    3    5\nR> [2,]    2    4    6\nR> \nR> , , 2\nR> \nR>      [,1] [,2] [,3]\nR> [1,]    7    9   11\nR> [2,]    8   10   12\n```\n\n\n:::\n\n```{.r .cell-code}\n# ✓ Check the dimensions of the new array\ndim(new_arr1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR> [1] 2 3 2\n```\n\n\n:::\n\n```{.r .cell-code}\n# Check the class of the new array\nclass(new_arr1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR> [1] \"array\"\n```\n\n\n:::\n\n```{.r .cell-code}\n# Check the structure of the new array\nstr(new_arr1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR>  int [1:2, 1:3, 1:2] 1 2 3 4 5 6 7 8 9 10 ...\n```\n\n\n:::\n\n```{.r .cell-code}\n# ✓ Check the length (number of elements) of the new array\nlength(new_arr1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR> [1] 12\n```\n\n\n:::\n\n```{.r .cell-code}\n# Check the number of dimensions of the new array\nlength(dim(new_arr1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR> [1] 3\n```\n\n\n:::\n\n```{.r .cell-code}\n# ✓ A variation of `vec` with different dimensions\nnew_arr2 <- array(vec, dim = c(3, 2, 2))\n\n# ✓ Display the new array\nnew_arr2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR> , , 1\nR> \nR>      [,1] [,2]\nR> [1,]    1    4\nR> [2,]    2    5\nR> [3,]    3    6\nR> \nR> , , 2\nR> \nR>      [,1] [,2]\nR> [1,]    7   10\nR> [2,]    8   11\nR> [3,]    9   12\n```\n\n\n:::\n\n```{.r .cell-code}\n# ✓ Check the dimensions of the new array\ndim(new_arr2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR> [1] 3 2 2\n```\n\n\n:::\n\n```{.r .cell-code}\n# ✓ Check the length (number of elements) of the new array\nlength(new_arr2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR> [1] 12\n```\n\n\n:::\n\n```{.r .cell-code}\n# ✓ ✓ ✓ ✓ A third variation of `vec` with different dimensions\nnew_arr3 <- array(vec, dim = c(2, 2, 3))\nnew_arr3\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR> , , 1\nR> \nR>      [,1] [,2]\nR> [1,]    1    3\nR> [2,]    2    4\nR> \nR> , , 2\nR> \nR>      [,1] [,2]\nR> [1,]    5    7\nR> [2,]    6    8\nR> \nR> , , 3\nR> \nR>      [,1] [,2]\nR> [1,]    9   11\nR> [2,]   10   12\n```\n\n\n:::\n\n```{.r .cell-code}\nlength(new_arr3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR> [1] 12\n```\n\n\n:::\n\n```{.r .cell-code}\ndim(new_arr3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR> [1] 2 2 3\n```\n\n\n:::\n:::\n\n\n\n\n# 5. R Workflows\n\n## Question 11\n\nWhat is the purpose of commenting code? Name at least three reasons why you should comment your code. **(/3)**\n\n\n\n**Answer**\n\n- ✓ Commenting code makes your code more readable, understandable, and maintainable. Comments provide context, explanations, and documentation about the code, helping you (and your future self), others understand the purpose of the code and the logic behind it, and how it works.\n- ✓ Comments can also serve as reminders, placeholders, or to-do lists for future work. They help in debugging, troubleshooting, and modifying code by providing insights into the code structure, functionality.\n- ✓ Commenting code is a good practice in programming and data analysis because it promotes collaboration, knowledge sharing, and code quality. It is essential for effective communication, ensuring that the codebase remains comprehensible and usable over time.\n\n\n\n## Question 12\n\nWhy am I pedantic about using commas and periods correctly in my code? Name some use cases of commas and periods. **(/3)**\n\n\n\n**Answer**\n\n- ✓ The SI system of units uses commas and periods in a specific way: periods are used for decimal points, while commas are used to separate thousands.\n- ✓ Using commas and periods correctly in your code is important for readability, clarity, and consistency. Commas are used to separate elements in a vector, list or arguments in a function call.\n- ✓ Incorrect usage of commas and periods can lead to syntax errors, logical errors, or unexpected behaviour in your code. It can make the code difficult to understand, debug, and maintain, especially for others who read, work with the code.\n\n\n\n## Question 13\n\nCreate a script to read in the file `crops.xlsx` (via a CSV file that you prepare beforehand) and assign its content to the object `crops`. Display the content of the dataframe. **(/3)**\n\n\n\n**Answer**\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n- ✓ First convert the Excel file to a CSV file using Excel or an online converter such as ChatGPT.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Read the CSV file into R \ncrops <- read.csv(\"crops.csv\") # ✓ \nhead(crops) # ✓\n```\n:::\n\n\n\n\n## Question 14\n\nSave the newly-created object to a CSV file called `crops2.csv` within your workspace. **(/1)**\n\n\n\n**Answer**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Save the object to a CSV file\nwrite.csv(crops, \"crops2.csv\", row.names = FALSE) # ✓\n```\n:::\n\n\n\n\n## Question 15\n\nWhat purpose can the naming of a newly-created dataframe serve? Name at least five reasons. **(/5)**\n\n\n\n**Answer**\n\n- Naming a newly-created dataframe serves several purposes:\n  - ✓ **Clarity**: A descriptive name can help you and others understand the content or purpose of the dataframe.\n  - ✓ **Readability**: A well-chosen name makes the code more readable and easier to follow.\n  - ✓ **Documentation**: The name can serve as a form of documentation, providing context, information about the dataframe.\n  - ✓ **Organisation**: Naming conventions can help organise and manage dataframes in a project or analysis.\n  - ✓ **Consistency**: Consistent naming practices across dataframes improve code consistency and maintainability.\n  - ✓ **Debugging**: A meaningful name can aid in debugging and troubleshooting code.\n  - ✓ **Reusability**: A good name can make the dataframe more reusable in different parts of the code or in other projects.\n\n\n\n## Question 16\n\nUsing annotated R code, demonstrate your understanding of the various ways to look inside of the `crops` object. Show at least five different ways to inspect the dataframe. **(/5)**\n\n\n\n**Answer**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# ✓ Display the structure of the dataframe\nstr(crops)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR> tibble [96 × 4] (S3: tbl_df/tbl/data.frame)\nR>  $ density   : num [1:96] 1 2 1 2 1 2 1 2 1 2 ...\nR>  $ block     : chr [1:96] \"north\" \"east\" \"south\" \"west\" ...\nR>  $ fertilizer: chr [1:96] \"A\" \"A\" \"A\" \"A\" ...\nR>  $ mass      : num [1:96] 4823 4832 4801 4836 4821 ...\n```\n\n\n:::\n\n```{.r .cell-code}\n# ✓ Display the first few rows of the dataframe\nhead(crops)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR> # A tibble: 6 × 4\nR>   density block fertilizer  mass\nR>     <dbl> <chr> <chr>      <dbl>\nR> 1       1 north A          4823.\nR> 2       2 east  A          4832.\nR> 3       1 south A          4801.\nR> 4       2 west  A          4836.\nR> 5       1 north A          4821.\nR> 6       2 east  A          4811.\n```\n\n\n:::\n\n```{.r .cell-code}\n# ✓ Display the last few rows of the dataframe\ntail(crops)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR> # A tibble: 6 × 4\nR>   density block fertilizer  mass\nR>     <dbl> <chr> <chr>      <dbl>\nR> 1       1 south C          4822.\nR> 2       2 west  C          4828.\nR> 3       1 north C          4848.\nR> 4       2 east  C          4836.\nR> 5       1 south C          4836.\nR> 6       2 west  C          4820.\n```\n\n\n:::\n\n```{.r .cell-code}\n# ✓ Display the summary statistics of the dataframe\nsummary(crops)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR>     density       block            fertilizer             mass     \nR>  Min.   :1.0   Length:96          Length:96          Min.   :4773  \nR>  1st Qu.:1.0   Class :character   Class :character   1st Qu.:4803  \nR>  Median :1.5   Mode  :character   Mode  :character   Median :4819  \nR>  Mean   :1.5                                         Mean   :4818  \nR>  3rd Qu.:2.0                                         3rd Qu.:4828  \nR>  Max.   :2.0                                         Max.   :4873\n```\n\n\n:::\n\n```{.r .cell-code}\n# ✓ Display the dimensions of the dataframe\ndim(crops)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR> [1] 96  4\n```\n\n\n:::\n\n```{.r .cell-code}\n# ✓ Display the column names of the dataframe\ncolnames(crops)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR> [1] \"density\"    \"block\"      \"fertilizer\" \"mass\"\n```\n\n\n:::\n\n```{.r .cell-code}\n# ✓ Glimpse into the dataframe\nglimpse(crops)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR> Rows: 96\nR> Columns: 4\nR> $ density    <dbl> 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2,…\nR> $ block      <chr> \"north\", \"east\", \"south\", \"west\", \"north\", \"east\", \"south\",…\nR> $ fertilizer <chr> \"A\", \"A\", \"A\", \"A\", \"A\", \"A\", \"A\", \"A\", \"A\", \"A\", \"A\", \"A\",…\nR> $ mass       <dbl> 4823.367, 4832.113, 4801.044, 4836.293, 4820.559, 4811.111,…\n```\n\n\n:::\n\n```{.r .cell-code}\n# ✓ Look at the names\nnames(crops)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR> [1] \"density\"    \"block\"      \"fertilizer\" \"mass\"\n```\n\n\n:::\n\n```{.r .cell-code}\n# ✓ Use the skimr package to get a summary of the dataframe\nskimr::skim(crops)\n```\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |      |\n|:------------------------|:-----|\n|Name                     |crops |\n|Number of rows           |96    |\n|Number of columns        |4     |\n|_______________________  |      |\n|Column type frequency:   |      |\n|character                |2     |\n|numeric                  |2     |\n|________________________ |      |\n|Group variables          |None  |\n\n\n**Variable type: character**\n\n|skim_variable | n_missing| complete_rate| min| max| empty| n_unique| whitespace|\n|:-------------|---------:|-------------:|---:|---:|-----:|--------:|----------:|\n|block         |         0|             1|   4|   5|     0|        4|          0|\n|fertilizer    |         0|             1|   1|   1|     0|        3|          0|\n\n\n**Variable type: numeric**\n\n|skim_variable | n_missing| complete_rate|    mean|    sd|      p0|     p25|     p50|     p75|    p100|hist  |\n|:-------------|---------:|-------------:|-------:|-----:|-------:|-------:|-------:|-------:|-------:|:-----|\n|density       |         0|             1|    1.50|  0.50|    1.00|    1.00|    1.50|    2.00|    2.00|▇▁▁▁▇ |\n|mass          |         0|             1| 4817.56| 18.09| 4772.53| 4802.68| 4818.72| 4827.99| 4873.23|▂▅▇▃▁ |\n\n\n:::\n\n```{.r .cell-code}\n# ✓ Display the data types of the columns\nsapply(crops, class)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR>     density       block  fertilizer        mass \nR>   \"numeric\" \"character\" \"character\"   \"numeric\"\n```\n\n\n:::\n:::\n\n\n\n\n## Question 17\n\nExplain what you see inside the file. What are the columns? What are the rows? What are the data types? **(/5)**\n\n\n\n**Answer**\n\n- ✓ The `crops` dataframe contains the columns `density`, `block`, `fertiliser`, `mass`. The rows represent individual observations or measurements of crop mass under different conditions.\n- ✓ The `density` column likely represents the density of the crop, `block` represents the experimental block, `fertiliser` represents the type of fertiliser used, `mass` represents the mass of the crop.\n- ✓ The data types of the columns can be inferred from the output of `str(crops)` and `sapply(crops, class)`. For example, `density` and `mass` are numeric or integer, while `block` and `fertiliser` are characters or factors.\n- ✓ The density ranges from a minimum of 1 to a maximum of 2. The fertiliser is a factor with levels `A`, `B`, `C`, the block is a character vector with levels `north`, `south`, `east`, `west`. The mass ranges from a minimum of 4773 to a maximum of 4873.\n- ✓ There are 96 rows in the dataframe, representing 96 observations, measurements.\n\n\n\n# 5. R and RStudio (Continue)\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n## Question 18\n\nExplain in words what the pipe operator `%>%` does in R. How does it make your code more readable? **(/3)**\n\n\n\n**Answer**\n\n- ✓ The pipe operator `%>%` (or `|>`) in R is used to chain together multiple functions or operations in a sequence. It takes the output of one function and passes it as the first argument to the next function, allowing you to create a pipeline of operations.\n- ✓ The pipe operator makes your code more readable by breaking down complex operations into a series of simpler steps. It helps in avoiding nested function calls, improves code clarity, and reduces the need for intermediate variables.\n- ✓ In this way you can write code in a more linear and intuitive way, following the flow of data transformations from one step to the next. This makes it easier to understand the logic of the code, the sequence of operations being performed.\n\n\n\n## Question 19\n\nUsing the various **tidyverse** functions, calculate the mean ± SD for the crop mass within each combination of `block` and `fertiliser` of the `crops` dataset. **(/5)**\n\n\n\n**Answer**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Load the tidyverse package\nlibrary(tidyverse)\n\n# Calculate the mean ± SD for crop mass within each combination of block and fertiliser\ncrops %>%\n  group_by(block, fertilizer) %>%\n  summarise(mean_mass = mean(mass), sd_mass = sd(mass))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR> # A tibble: 12 × 4\nR> # Groups:   block [4]\nR>    block fertilizer mean_mass sd_mass\nR>    <chr> <chr>          <dbl>   <dbl>\nR>  1 east  A              4826.    16.6\nR>  2 east  B              4817.    19.9\nR>  3 east  C              4834.    13.8\nR>  4 north A              4803.    19.4\nR>  5 north B              4813.    12.1\nR>  6 north C              4823.    14.6\nR>  7 south A              4800.    12.7\nR>  8 south B              4809.    17.6\nR>  9 south C              4819.    13.7\nR> 10 west  A              4812.    16.4\nR> 11 west  B              4822.    11.4\nR> 12 west  C              4832.    20.2\n```\n\n\n:::\n:::\n\n\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}