{
  "hash": "d6afd32da96f7220dbe288bf528453fb",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"16. Collinearity, Confounding, and Measurement Error\"\nsubtitle: \"Three Threats to Interpretable Regression Models\"\ndate: last-modified\ndate-format: \"YYYY/MM/DD\"\nreference-location: margin\n---\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n::: {.callout-note appearance=\"simple\"}\n## In This Chapter\n\n-   what collinearity is and why it matters;\n-   how confounding differs from collinearity;\n-   why measurement error weakens inference;\n-   how proxy variables complicate interpretation;\n-   what a practical response looks like when these problems appear.\n:::\n\n::: {.callout-important appearance=\"simple\"}\n## Tasks to Complete in This Chapter\n\n-   None\n:::\n\n# Introduction\n\nRegression models are often taught as though the difficult part is fitting the correct formula and reading the summary table. In practice, some of the hardest challenges come afterwards. Predictors may overlap strongly, causal roles may be confused, and the variables we fit may be noisy measurements or only rough proxies for the processes we care about.\n\nIn this chapter, I bring together three closely related but distinct problems:\n\n1. **collinearity**, where predictors share too much information;\n2. **confounding**, where a third variable distorts interpretation; and\n3. **measurement error**, where the variables in the model are noisy versions of the quantities we would really like to observe.\n\nAll three problems must be thought about because they impair interpretation. A model may still run and produce seemingly believable coefficients, but those coefficients may no longer mean what we would like them to mean.\n\nIn multiple regression and other multivariate models, we generally hope that the predictor variables provide distinct information. When they do not, our models can become unstable and difficult to interpret. This issue, known as **collinearity** or **multicollinearity**, is a common challenge in biological research, where environmental variables are often highly correlated. It is especially common in ecology because many environmental variables are linked through shared physical and biological processes. Temperature, oxygen, and productivity, for example, often co-vary.\n\nIn this chapter, I explain what collinearity is, why it is problematic, and how to diagnose and address it. I also explain why collinearity differs from confounding, and why measurement error and proxy variables create further limitations even when the fitted model looks statistically sound. While no single paper is as singularly famous here as Hurlbert's work on pseudoreplication, discussed in [Chapter 18](18-pseudoreplication.qmd), a foundational and highly recommended review of multicollinearity is that of Graham -@Graham2003.\n\n# Key Concepts\n\nKeep the following distinctions clear.\n\n-   **Collinearity / Multicollinearity** is a condition in multiple regression where two or more predictor variables are highly correlated, making it difficult for the model to separate their individual effects.\n-   **Problem of interpretation, not prediction** The main drawback of collinearity is that it makes the model's coefficients unreliable and difficult to interpret, even when the model predicts the outcome well.\n-   **Variance Inflation Factor (VIF)** is the standard diagnostic tool for detecting multicollinearity. A high VIF indicates that the variance of a coefficient is being inflated by overlap with other predictors.\n-   **Confounding**, on the other hand, is a problem of attribution.\n-   **Measurement error** weakens inference and can bias estimated effects, often towards zero.\n-   **Proxy variables** can be very useful, but they come with interpretive limits.\n-   **Good design and good variable choice** solve more of these problems than software does.\n\n# Why These Problems are Serious\n\nIt is useful to state the broader issue clearly. In the regression chapters so far, we have assumed that the predictors in a model can be interpreted as though each one contributes something identifiable to the response. But, that assumption is often too optimistic since several things can go wrong:\n\n-   Two predictors may describe almost the same underlying process.\n-   A variable may appear important only because another, unmeasured variable has been omitted.\n-   A predictor may be measured with enough error that its effect is weakened and unstable.\n-   A fitted coefficient may describe a proxy rather than a mechanism.\n\nThese affect what the model allows us to say biologically.\n\n# R Functions\n\nThe most useful functions in this chapter are:\n\n-   `cor()` and plots of predictor relationships for identifying overlap;\n-   `car::vif()` for diagnosing collinearity in a fitted model;\n-   `lm()` for comparing models that omit or include potentially confounding variables;\n-   `broom::tidy()` for comparing coefficients across models.\n\n# Collinearity\n\n## What Is Collinearity?\n\n**Collinearity** occurs when two predictor variables in a multiple regression model are highly correlated. **Multicollinearity** is the more general term, referring to a situation where one predictor variable can be linearly predicted from one or more of the other predictor variables with a substantial degree of accuracy.\n\nFor example, in a marine environment, you might measure water temperature, salinity, and dissolved oxygen. It is very likely that temperature and dissolved oxygen are strongly negatively correlated, because colder water holds more oxygen. If you include both in a model to predict the abundance of a fish species, the predictors share information, which introduces multicollinearity.\n\nIn ecology and environmental biology, this is common because many variables co-vary through shared physical or biological processes. Examples include:\n\n-   altitude and temperature;\n-   nitrate and phosphate;\n-   temperature and dissolved oxygen;\n-   rainfall and river flow.\n\n## Why Is It a Problem?\n\nUnlike pseudoreplication, collinearity does not necessarily invalidate the entire model in terms of its predictive power. A model with collinear predictors may still produce good predictions. However, it severely compromises the **interpretation** of the model's coefficients. The primary problems are:\n\n1. **Unstable coefficient estimates** The estimated regression coefficients can vary wildly depending on which other variables are in the model. The standard errors of the coefficients become inflated, making it difficult to determine the true effect of each predictor.\n2. **Incorrect signs** A coefficient might appear to have the \"wrong\" sign, such as a positive effect where a negative one is expected biologically. This happens because the model is trying to partition shared variation between correlated predictors, and the results can become nonsensical.\n3. **Loss of statistical significance** Because the standard errors are inflated, a predictor that is truly important may appear statistically non-significant. The model cannot confidently attribute the effect to any single one of the correlated predictors.\n\nThese effects arise because the model must estimate multiple coefficients from overlapping information. When two predictors are strongly correlated, the model cannot cleanly separate their individual contributions because they explain the same variation in the response.\n\nSo, the central message is that collinearity is usually a **problem of interpretation rather than raw prediction**.\n\n# Example 1: Predicting Plant Growth\n\nSuppose you model plant growth using:\n\n-   `mean_annual_temperature`, a mechanistic driver of metabolic rates; and\n-   `altitude`, a composite variable that correlates with temperature, oxygen, and radiation.\n\nThese variables are strongly correlated because altitude influences temperature. The model then attempts to assign separate effects to two variables that describe overlapping processes. As a result:\n\n-   coefficients become unstable;\n-   standard errors increase;\n-   biological interpretation becomes unclear.\n\nAltitude is acting as a **proxy variable**. It is easy to measure but does not represent a single causal mechanism. Including both altitude and temperature asks the model to separate a proxy from the process it represents, which it often cannot do reliably.\n\nBetter modelling choices would include:\n\n-   using temperature if the hypothesis concerns physiology;\n-   using altitude if the question concerns broad spatial gradients;\n-   avoiding both in the same model unless their distinct roles are explicitly justified.\n\n# Example 2: Nutrient Limitation in Coastal Systems\n\nSuppose you model phytoplankton biomass using:\n\n-   nitrate; and\n-   phosphate.\n\nThese nutrients often co-vary because they are supplied by the same water masses. The outcome may be that:\n\n-   the model fits well overall;\n-   individual coefficients are unstable or non-significant.\n\nThe model cannot separate the effect of nitrate from phosphate because both track the same underlying process: nutrient supply.\n\nPossible resolutions include:\n\n-   using one nutrient based on ecological theory, for example the limiting nutrient;\n-   using a ratio such as N:P if the hypothesis concerns stoichiometry;\n-   using PCA or another dimension-reduction method to represent a broader \"nutrient gradient\" if prediction is the main goal.\n\nThis example shows that collinearity can arise even when all the variables are mechanistically meaningful. The decision is therefore about how to handle collinearity *and* whether the goal is explanation or prediction.\n\n# Diagnosing Collinearity\n\nThe most common way to diagnose multicollinearity is by calculating the **Variance Inflation Factor (VIF)** for each predictor variable:\n\n$$\\text{VIF}_j = \\frac{1}{1 - R_j^2}$$ {#eq-vif}\n\nIn @eq-vif, $R_j^2$ is the coefficient of determination obtained by regressing predictor $X_j$ on all the remaining predictors in the model.\n\n-   A VIF of 1 means there is no correlation.\n-   A VIF between about 1 and 5 is often manageable.\n-   A VIF above about 5 or 10 suggests substantial multicollinearity that should be considered carefully.\n\nVIF does not diagnose a problem on its own. It indicates that a coefficient reflects shared variation with other predictors. The decision to act depends on whether the model needs interpretable coefficients.\n\n# Example 3: Worked Collinearity Example\n\nUsing the seaweed example from the previous chapter, we can inspect the candidate climate predictors for overlap.\n\n## Inspect the Predictor Set\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsw <- read.csv(here::here(\"data\", \"BCB743\", \"seaweed\", \"spp_df2.csv\"))\nsw_ectz <- sw |>\n  filter(bio == \"ECTZ\") |>\n  select(Y, augMean, febRange, febSD, augSD, annMean)\n\ncor(sw_ectz[, -1])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           augMean  febRange     febSD     augSD   annMean\naugMean  1.0000000 0.6678245 0.5039666 0.4603614 0.9711458\nfebRange 0.6678245 1.0000000 0.9212490 0.5415907 0.6860398\nfebSD    0.5039666 0.9212490 1.0000000 0.5744316 0.5533197\naugSD    0.4603614 0.5415907 0.5744316 1.0000000 0.5851171\nannMean  0.9711458 0.6860398 0.5533197 0.5851171 1.0000000\n```\n\n\n:::\n:::\n\n\nThe correlation matrix already shows that several of the candidate predictors overlap strongly.\n\n## Diagnose the Overlap with VIF\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncol_mod <- lm(Y ~ augMean + febRange + febSD + augSD + annMean,\n              data = sw_ectz)\n\nvif(col_mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  augMean  febRange     febSD     augSD   annMean \n27.947767 10.806635  8.765732  2.497739 31.061900 \n```\n\n\n:::\n:::\n\n\nThe VIF values show that some predictors overlap strongly. The model is not necessarily mathematically invalid; it simply means that the separate interpretation of those coefficients becomes hard to defend.\n\nWe can make the consequences more concrete by comparing the simple slopes for each predictor to the coefficients in the multiple regression.\n\n## Compare Simple and Multiple-Regression Slopes\n\n\n::: {.cell}\n\n```{.r .cell-code}\npreds <- c(\"augMean\", \"febRange\", \"febSD\", \"augSD\", \"annMean\")\n\nsimple_models <- purrr::map(preds, ~ lm(as.formula(paste(\"Y ~\", .x)),\n                                        data = sw_ectz))\n\nsimple_slopes <- purrr::map2_dfr(simple_models, preds, \\(mod, nm) {\n  tidy(mod) |>\n    filter(term != \"(Intercept)\") |>\n    mutate(model = \"Simple regression\",\n           predictor = nm)\n})\n\nmultiple_slopes <- tidy(col_mod) |>\n  filter(term != \"(Intercept)\") |>\n  mutate(model = \"Multiple regression\",\n         predictor = term)\n\nbind_rows(simple_slopes, multiple_slopes) |>\n  select(model, predictor, estimate, std.error, statistic, p.value)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 6\n   model               predictor estimate std.error statistic   p.value\n   <chr>               <chr>        <dbl>     <dbl>     <dbl>     <dbl>\n 1 Simple regression   augMean    0.346     0.0109     31.7   6.68e- 96\n 2 Simple regression   febRange   0.182     0.00890    20.4   8.31e- 58\n 3 Simple regression   febSD      0.172     0.0124     13.8   1.56e- 33\n 4 Simple regression   augSD      0.0879    0.00720    12.2   6.68e- 28\n 5 Simple regression   annMean    0.332     0.00867    38.3   6.82e-115\n 6 Multiple regression augMean   -0.0799    0.0426     -1.87  6.18e-  2\n 7 Multiple regression febRange   0.113     0.0159      7.08  1.14e- 11\n 8 Multiple regression febSD     -0.0572    0.0166     -3.45  6.37e-  4\n 9 Multiple regression augSD      0.00302   0.00489     0.619 5.36e-  1\n10 Multiple regression annMean    0.323     0.0416      7.76  1.59e- 13\n```\n\n\n:::\n:::\n\n\nThis comparison is useful because it shows the practical effect of collinearity. Predictors that look obvious and seem strongly positive in isolation may become weaker, unstable, or even change sign once the overlapping predictors are entered together. The does multiple regression might not be wrong, but the coefficients are being estimated under much greater uncertainty because the model is trying to assign separate effects to partially redundant variables.\n\n## Interpret the Collinearity Problem\n\nThe key message is that the difficulty lies in attribution, not in the mere existence of a fitted model. Once several predictors describe much the same underlying climatic gradient, the model can struggle to assign a stable partial effect to any one of them. This is why collinearity is so often an interpretive problem rather than a purely computational one.\n\n## Reporting\n\n::: {.callout-note appearance=\"simple\"}\n## Write-Up\n\n**Methods**\n\nCandidate climate predictors were screened for overlap using both a correlation matrix and variance inflation factors. Simple and multiple regressions were then compared to assess how strongly collinearity altered the apparent slopes of individual predictors.\n\n**Results**\n\nSeveral climate predictors in the seaweed model were strongly correlated, and the VIF analysis showed substantial overlap among them. Predictors that showed clear positive slopes in isolation became weaker or less stable once the overlapping variables were fitted together, demonstrating that the apparent partial effects were sensitive to collinearity.\n\n**Discussion**\n\nThe model is not necessarily invalid, but coefficient-level interpretation becomes difficult when predictors represent overlapping components of the same underlying gradient. That is the key discussion point for a collinearity analysis.\n:::\n\n# Addressing Collinearity\n\nCommon responses include:\n\n-   removing one of the correlated predictors;\n-   choosing one variable over another based on theory;\n-   combining correlated predictors into a single index or ordination axis;\n-   accepting some overlap if prediction is the main goal, but avoiding strong causal language;\n-   using regularisation methods such as ridge regression, lasso, or elastic net when the objective is predictive stability rather than simple coefficient interpretation.\n\nThere is obvious threshold that solves the problem automatically. But, is the overlap is small enough that the coefficients still mean something defensible?\n\n# Confounding\n\nConfounding is a different problem. The two predictors may or may not overlap, and, more importantly, a third variable was accidentally excluded from assessment, or it inadvertently distorts the apparent relationship between a predictor of interest and the response.\n\nA confounder is a variable that influences both:\n\n-   the predictor of interest; and\n-   the response.\n\nThis can create a spurious association or distort a real one. For example, if you relate abundance to temperature but nutrient supply is associated with both temperature and abundance, the temperature coefficient may partly absorb nutrient effects.\n\nThese ideas are related but not identical.\n\n-   **Collinearity** is about overlap among predictors in the data.\n-   **Confounding** is about mistaken attribution of an effect.\n\nTwo variables can be highly collinear without one being a confounder. Equally, a confounder can matter even when the correlation structure does not look especially dramatic.\n\n# Example 4: Worked Confounding Example\n\nWe can see the logic of confounding clearly with a small biological-look-alike example. Suppose we want to know whether seawater temperature affects algal abundance along a coastal gradient, but nutrient concentration also varies with temperature and itself influences abundance. In that case, a temperature-only model risks attributing nutrient-related variation to temperature.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(144)\n\nn <- 120\nnutrient <- rnorm(n, mean = 10, sd = 2)\ntemperature <- 15 + 0.9 * nutrient + rnorm(n, sd = 1.2)\nabundance <- 4 + 1.4 * nutrient + 0.15 * temperature + rnorm(n, sd = 1.5)\n\nconf_dat <- tibble(\n  nutrient = nutrient,\n  temperature = temperature,\n  abundance = abundance\n)\n```\n:::\n\n\n## Do an Exploratory Data Analysis (EDA)\n\nWe begin by inspecting the scale of the variables and the pairwise relationships among them.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconf_dat |>\n  summarise(\n    mean_temperature = mean(temperature),\n    sd_temperature = sd(temperature),\n    mean_nutrient = mean(nutrient),\n    sd_nutrient = sd(nutrient),\n    mean_abundance = mean(abundance),\n    sd_abundance = sd(abundance)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 6\n  mean_temperature sd_temperature mean_nutrient sd_nutrient mean_abundance\n             <dbl>          <dbl>         <dbl>       <dbl>          <dbl>\n1             23.7           2.26          9.84        2.04           21.3\n# ℹ 1 more variable: sd_abundance <dbl>\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor(conf_dat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             nutrient temperature abundance\nnutrient    1.0000000   0.8403428 0.9035191\ntemperature 0.8403428   1.0000000 0.8066436\nabundance   0.9035191   0.8066436 1.0000000\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\np1 <- ggplot(conf_dat, aes(x = temperature, y = abundance)) +\n  geom_point(alpha = 0.7, colour = \"dodgerblue4\") +\n  geom_smooth(method = \"lm\", se = FALSE, colour = \"magenta\") +\n  labs(x = \"Temperature\", y = \"Algal abundance\") +\n  theme_grey()\n\np2 <- ggplot(conf_dat, aes(x = nutrient, y = abundance)) +\n  geom_point(alpha = 0.7, colour = \"dodgerblue4\") +\n  geom_smooth(method = \"lm\", se = FALSE, colour = \"magenta\") +\n  labs(x = \"Nutrient concentration\", y = \"Algal abundance\") +\n  theme_grey()\n\np3 <- ggplot(conf_dat, aes(x = nutrient, y = temperature)) +\n  geom_point(alpha = 0.7, colour = \"dodgerblue4\") +\n  geom_smooth(method = \"lm\", se = FALSE, colour = \"magenta\") +\n  labs(x = \"Nutrient concentration\", y = \"Temperature\") +\n  theme_grey()\n\nggarrange(p1, p2, p3, ncol = 3)\n```\n\n::: {.cell-output-display}\n![A confounding situation where nutrient concentration is associated with both temperature and abundance.](16-collinearity-confounding-measurement-error_files/figure-html/fig-confounding-1.svg){#fig-confounding}\n:::\n:::\n\n\nThe EDA in @fig-confounding already suggests a confounding structure. Temperature and nutrient concentration are strongly positively correlated ($r = 0.84$), and both appear positively related to algal abundance. That means a temperature-only model would be at risk of absorbing part of the nutrient effect.\n\n## State the Model Question and Hypotheses\n\nThe biological question is not simply whether temperature and abundance are associated. It is whether temperature still explains abundance **after nutrient concentration has been accounted for**.\n\n$$H_{0}: \\beta_{\\text{temperature}} = 0$$\n$$H_{a}: \\beta_{\\text{temperature}} \\ne 0$$\n\nHere $\\beta_{\\text{temperature}}$ refers to the partial effect of temperature in the model that also includes nutrient concentration. If the temperature coefficient changes strongly when nutrient is added, that is evidence that the original temperature-only result was confounded.\n\n## Fit Competing Models\n\nWe first fit a temperature-only model, and then a second model that also includes nutrient concentration:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod_temp_only <- lm(abundance ~ temperature, data = conf_dat)\nmod_with_nutrient <- lm(abundance ~ temperature + nutrient, data = conf_dat)\n\nconf_compare <- bind_rows(\n  tidy(mod_temp_only) |>\n    filter(term != \"(Intercept)\") |>\n    mutate(model = \"Temperature only\"),\n  tidy(mod_with_nutrient) |>\n    filter(term != \"(Intercept)\") |>\n    mutate(model = \"Temperature + nutrient\")\n) |>\n  select(model, term, estimate, std.error, statistic, p.value)\n\nconf_compare\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 6\n  model                  term        estimate std.error statistic  p.value\n  <chr>                  <chr>          <dbl>     <dbl>     <dbl>    <dbl>\n1 Temperature only       temperature    1.27     0.0854     14.8  1.02e-28\n2 Temperature + nutrient temperature    0.253    0.112       2.25 2.61e- 2\n3 Temperature + nutrient nutrient       1.33     0.124      10.7  3.99e-19\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(mod_temp_only, mod_with_nutrient)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nModel 1: abundance ~ temperature\nModel 2: abundance ~ temperature + nutrient\n  Res.Df    RSS Df Sum of Sq     F    Pr(>F)    \n1    118 522.57                                 \n2    117 263.30  1    259.26 115.2 < 2.2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n## Interpret the Results\n\nIf we ignored nutrient concentration, we would conclude that temperature had a very strong positive effect on algal abundance ($\\beta = 1.27$, SE = 0.09, $p < 0.001$). But once nutrient concentration is included, the estimated temperature effect shrinks sharply to about 0.25 (SE = 0.11, $p = 0.026$), while nutrient itself has a strong positive effect ($\\beta = 1.33$, SE = 0.12, $p < 0.001$).\n\nThe larger model shows that the apparent temperature effect in the simpler model was badly exaggerated because temperature was standing in for nutrient variation. Both predictors remain statistically detectable, but adding nutrient improves the model very strongly (`p < 0.001` in the nested model comparison), which confirms that the one-predictor model was omitting an important process-linked variable.\n\nThis is why confounding is fundamentally a problem of attribution: we are trying to decide whether the apparent effect of one variable is actually partly due to another.\n\n## Practical Implications of Confounding\n\nConfounding often arises because:\n\n-   a variable of biological importance was omitted;\n-   the variable was measured but not included;\n-   the design did not separate the process of interest from another correlated process.\n\nThe best remedy for confounding effects is to avoid it altogether through good subject knowledge, better experimental or sampling design, better measurement, and more careful model specification.\n\n## Reporting\n\n::: {.callout-note appearance=\"simple\"}\n## Write-Up\n\n**Methods**\n\nA simulated coastal algal-abundance dataset was used to examine confounding by nutrient concentration in a temperature-abundance relationship. A simple linear regression of abundance on temperature alone was compared with a multiple regression that included both temperature and nutrient concentration, and the fitted temperature coefficient was evaluated for change between the two models.\n\n**Results**\n\nIn the temperature-only model, algal abundance appeared to increase strongly with temperature ($\\beta = 1.27 \\pm 0.09$ SE, $t = 14.83$, $p < 0.001$). However, once nutrient concentration was included, the fitted temperature effect decreased markedly to $\\beta = 0.25 \\pm 0.11$ SE ($t = 2.25$, $p = 0.026$), while nutrient concentration had a strong positive effect on abundance ($\\beta = 1.33 \\pm 0.12$ SE, $t = 10.73$, $p < 0.001$). Temperature and nutrient concentration were also strongly correlated ($r = 0.84$), indicating that the simple temperature-abundance relationship was substantially confounded by nutrient availability.\n\n**Discussion**\n\nThe temperature-only model answered the wrong biological question because it mixed the effect of temperature with the effect of nutrient supply. In a real ecological analysis, that would make any strong mechanistic claim about temperature unreliable unless the nutrient process had also been considered.\n:::\n\n# Measurement Error\n\nStandard linear regression assumes that predictors are measured without serious error. That assumption is rarely exactly true in field biology.\n\nWhen a predictor is noisy, its estimated effect is often biased towards zero. This is called **attenuation bias**. In practical terms, a real effect may appear weaker and less stable than it truly is. This matters because:\n\n-   field instruments are imperfect;\n-   environmental conditions fluctuate;\n-   biological measurements can be imprecise;\n-   some important variables are difficult or expensive to measure directly.\n\n# Example 5: Worked Measurement-Error Example\n\nSuppose a response truly depends on temperature, but our observed temperature values are noisy because of instrument error or sampling mismatch.\n\n## Simulate the True and Noisy Predictors\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(414)\n\nn <- 150\ntrue_temp <- runif(n, min = 8, max = 24)\nobserved_temp <- true_temp + rnorm(n, sd = 2.5)\ngrowth <- 1.2 + 0.55 * true_temp + rnorm(n, sd = 2.0)\n\nme_dat <- tibble(\n  true_temp = true_temp,\n  observed_temp = observed_temp,\n  growth = growth\n)\n\nmod_true <- lm(growth ~ true_temp, data = me_dat)\nmod_observed <- lm(growth ~ observed_temp, data = me_dat)\n\nbind_rows(\n  tidy(mod_true) |> mutate(model = \"True predictor\"),\n  tidy(mod_observed) |> mutate(model = \"Observed noisy predictor\")\n) |>\n  filter(term != \"(Intercept)\") |>\n  select(model, term, estimate, std.error, statistic, p.value)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 6\n  model                    term          estimate std.error statistic  p.value\n  <chr>                    <chr>            <dbl>     <dbl>     <dbl>    <dbl>\n1 True predictor           true_temp        0.558    0.0350      16.0 5.38e-34\n2 Observed noisy predictor observed_temp    0.501    0.0362      13.8 1.77e-28\n```\n\n\n:::\n:::\n\n\n## Compare the Fitted Relationships\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\np3 <- ggplot(me_dat, aes(x = true_temp, y = growth)) +\n  geom_point(alpha = 0.7, colour = \"dodgerblue4\") +\n  geom_smooth(method = \"lm\", se = FALSE, colour = \"magenta\") +\n  labs(x = \"True temperature\", y = \"Growth\") +\n  theme_grey()\n\np4 <- ggplot(me_dat, aes(x = observed_temp, y = growth)) +\n  geom_point(alpha = 0.7, colour = \"dodgerblue4\") +\n  geom_smooth(method = \"lm\", se = FALSE, colour = \"magenta\") +\n  labs(x = \"Observed temperature\", y = \"Growth\") +\n  theme_grey()\n\nggarrange(p3, p4, ncol = 2)\n```\n\n::: {.cell-output-display}\n![Measurement error weakens the apparent relationship between the predictor and the response.](16-collinearity-confounding-measurement-error_files/figure-html/fig-measurement-error-1.svg){#fig-measurement-error}\n:::\n:::\n\n\nThe contrast in @fig-measurement-error shows that the model using the noisy predictor typically produces a weaker slope than the model using the true predictor. This is the practical effect of attenuation bias: measurement error can make a real effect appear smaller than it is.\n\nMeasurement error therefore matters because it adds noise and because it can systematically weaken the estimated effect.\n\n## Interpret the Measurement-Error Problem\n\nThe important point is that the weaker fitted relationship is not necessarily evidence of weaker biology. It may instead reflect poorer measurement. If the predictor is noisy, the model is forced to relate the response to an imperfect version of the underlying process, and the slope is therefore pulled towards zero.\n\n## Reporting\n\n::: {.callout-note appearance=\"simple\"}\n## Write-Up\n\n**Methods**\n\nA simulation was used to examine the effect of measurement error in a predictor variable by comparing the fitted relationship obtained from the true predictor with that obtained from a noisy observed version of the same predictor.\n\n**Results**\n\nAdding measurement error to the predictor reduced the apparent slope of the fitted relationship and weakened the visual strength of the association. The analysis therefore showed the characteristic attenuation effect expected when predictors are measured with error.\n\n**Discussion**\n\nWeak fitted effects do not always imply weak biology, because poor measurement or poor proxies can systematically flatten otherwise meaningful relationships. That is the key interpretive warning to carry into a Discussion section.\n:::\n\n# Proxy Variables\n\nMany biological models use proxy variables because the true mechanistic variables are unavailable.\n\nExamples include:\n\n-   altitude as a proxy for temperature or radiation;\n-   distance from shore as a proxy for exposure;\n-   chlorophyll as a proxy for productivity;\n-   depth in the ocean as a proxy for light intensity;\n-   body size as a proxy for age or condition.\n\nProxy variables are often convenient, they may seem reasonable, and sometimes they are even unavoidable. However, they *do* create interpretive limits. A proxy coefficient should not be inprepreted as if it identified one clean mechanism.\n\nThis is why the examples above matter. In the plant-growth example, altitude is a broad spatial proxy, while temperature is closer to the mechanism. In the nutrient example, nitrate and phosphate are both mechanistically meaningful but may still function as overlapping representations of nutrient supply. In both cases, interpretation depends on whether the question is explanatory or predictive.\n\n::: {.callout-note appearance=\"simple\"}\n## Mechanism Versus Proxy\n\nIf the question is physiological, use physiological drivers where possible. If the question is broad-scale pattern, a proxy may be perfectly acceptable. The important thing is that the variable should match the scale and aim of the question.\n:::\n\n# A Practical Workflow\n\nWhen building and interpreting a regression model:\n\n1. state the biological hypothesis first;\n2. identify which predictors are mechanistic and which are proxies;\n3. ask which variables could confound the relationship of interest;\n4. inspect predictor correlations and calculate VIF where appropriate;\n5. compare simpler and richer models when confounding is plausible;\n6. remove or combine redundant predictors when interpretation is the goal;\n7. be honest about causal limits when important variables are missing or poorly measured.\n\nThis workflow also forces an important distinction that connects directly to the regularisation chapter that follows later in the sequence.\n\n-   If the main goal is **explanation**, then unstable coefficients, proxies, confounding, and overlap are serious problems because they weaken the biological interpretation.\n-   If the main goal is **prediction**, some overlap may be tolerable if predictive performance is strong, although the coefficients may still not support strong mechanistic claims.\n\nSo the decision is not only \"is there collinearity?\" It is also \"what is the model for?\"\n\n# Summary\n\n-   Collinearity makes coefficients unstable because predictors share information.\n-   Confounding is a problem of attribution rather than simple overlap.\n-   Measurement error weakens inference and can bias estimated effects, often towards zero.\n-   Proxy variables are often useful, but they limit what a coefficient can be said to mean.\n-   These problems are handled best through strong biological reasoning, careful design, and honest interpretation rather than by software alone.\n\nIn the next chapter, I go from model construction to the question of whether a fitted model is actually behaving well: diagnostics, comparison, and evaluation.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}