{
  "hash": "814215d96f5ec9441e2a40486907b9da",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"10: Principal Coordinates Analysis (PCoA)\"\nsubtitle: \"Task F\"\nformat:\n  html:\n    code-fold: true\n    code-summary: \"Show the answers\"\n---\n\n\n::: {.cell}\n\n:::\n\n\n## Practice Task\n\nWork through these exercises after reading the [Principal Coordinates Analysis](../PCoA.qmd) chapter. The point of PCoA is that you choose the dissimilarity, so the task explores how much that choice matters, using the Doubs fish and environmental data. Four exercises are hands-on calculations and two are short conceptual questions. A worked answer is given under each exercise; try it yourself before opening it.\n\n1. Compute a Bray-Curtis dissimilarity on the Doubs fish data and run a PCoA with `capscale(spe ~ 1, distance = \"bray\")`. Report the proportion of variation captured by the first two axes, and check the eigenvalues for negative (\"imaginary\") values.\n\n::: {.callout-note collapse=\"true\"}\n## Show the answer\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nlibrary(tidyverse)\nlibrary(vegan)\n\nload(here::here(\n  \"data\",\n  \"BCB743\",\n  \"NEwR-2ed_code_data\",\n  \"NEwR2-Data\",\n  \"Doubs.RData\"\n))\nkeep <- rowSums(spe) > 0\nspe <- spe[keep, ]\nenv <- env[keep, ]\n\nd_bray <- vegdist(spe, method = \"bray\")\npcoa_bray <- capscale(spe ~ 1, distance = \"bray\") # PCoA (capscale keeps the real axes)\n\nvar_pcoa <- round(\n  100 * eigenvals(pcoa_bray)[1:2] / sum(eigenvals(pcoa_bray)),\n  1\n)\nvar_pcoa # % variation on MDS1, MDS2 (real axes)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMDS1 MDS2 \n52.4 15.6 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"false\"}\n# the full PCoA spectrum reveals the negative (\"imaginary\") eigenvalues capscale drops\neig_full <- cmdscale(d_bray, k = nrow(spe) - 1, eig = TRUE)$eig\nn_neg <- sum(eig_full < -1e-8)\nn_neg # number of negative eigenvalues\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 11\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"false\"}\nordiplot(pcoa_bray, type = \"text\", main = \"PCoA on Bray-Curtis\")   # sites + species labelled\n```\n\n::: {.cell-output-display}\n![](Task_F_files/figure-html/task-f-q1-1.svg)\n:::\n:::\n\n\nMDS1 captures 52.4% of the variation and MDS2 15.6% on the real axes, with MDS1 again ordering the sites along the river. `capscale()` returns only the real axes, but the full PCoA spectrum (from `cmdscale()`) contains 11 **negative** (\"imaginary\") eigenvalues: Bray-Curtis is not a Euclidean distance, so it cannot be embedded perfectly in real coordinate space, and the leftover, non-embeddable part shows up as those negative eigenvalues. This is why the proportion of variation from a non-Euclidean PCoA has to be read with care, and why the corrections in Exercise 5 are sometimes applied.\n:::\n\n2. Repeat the PCoA with a presence-absence dissimilarity (Jaccard or Sørensen). Compare the two ordinations: how sensitive is the site configuration to the choice between an abundance-based and a presence-absence dissimilarity?\n\n::: {.callout-note collapse=\"true\"}\n## Show the answer\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\npcoa_jac <- capscale(spe ~ 1, distance = \"jaccard\", binary = TRUE)\n\npar(mfrow = c(1, 2))\nordiplot(pcoa_bray, display = \"sites\", type = \"text\", main = \"Bray-Curtis (abundance)\")\nordiplot(pcoa_jac, display = \"sites\", type = \"text\", main = \"Jaccard (presence-absence)\")\n```\n\n::: {.cell-output-display}\n![](Task_F_files/figure-html/task-f-q2-1.svg)\n:::\n:::\n\n\nBoth ordinations recover the same dominant upstream-downstream gradient, so the broad story is robust to the choice of dissimilarity. The configurations differ in detail: the abundance-based Bray-Curtis ordination is pulled by the dominant species and spaces sites by how much their abundant taxa differ, whereas the presence-absence Jaccard ordination weights every species equally and is driven by which species are gained or lost. Sites that share their common species but differ in rare ones move between the two pictures. The choice of dissimilarity is therefore an ecological decision, not a technical default.\n:::\n\n3. Use a Gower dissimilarity (`cluster::daisy(..., metric = \"gower\")`) on a table that mixes variable types --- for example the Doubs environmental data together with one or more categorical variables of your own making. Run a PCoA on the result and explain why PCA and CA could not have analysed this table directly.\n\n::: {.callout-note collapse=\"true\"}\n## Show the answer\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nenv_mixed <- env |>\n  mutate(reach = cut(dfs, breaks = 3, labels = c(\"upper\", \"middle\", \"lower\"))) # a categorical variable\n\ngower <- cluster::daisy(env_mixed, metric = \"gower\")\npcoa_gower <- capscale(gower ~ 1)\nround(eigenvals(pcoa_gower)[1:2] / sum(abs(eigenvals(pcoa_gower))) * 100, 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMDS1 MDS2 \n69.3 13.2 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"false\"}\nordiplot(\n  pcoa_gower,\n  display = \"sites\",\n  type = \"text\",\n  main = \"PCoA on Gower (mixed-type table)\"\n)\n```\n\n::: {.cell-output-display}\n![](Task_F_files/figure-html/task-f-q3-1.svg)\n:::\n:::\n\n\nThe Gower coefficient combines standardised numeric variables with the categorical `reach` factor into a single dissimilarity, and PCoA then ordinates that matrix. PCA could not handle this table because it works on Euclidean distances of numeric variables and has no way to use a factor; CA could not either, because it expects a frequency/abundance table of non-negative counts. PCoA's strength is exactly this flexibility: choose a dissimilarity appropriate to the data (here one that accepts mixed types), and PCoA will ordinate it.\n:::\n\n4. Run an nMDS on the same Bray-Curtis matrix from Exercise 1. Compare the PCoA and nMDS configurations, citing the appropriate goodness measure for each (eigenvalue-based fit for PCoA, stress for nMDS).\n\n::: {.callout-note collapse=\"true\"}\n## Show the answer\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nnmds_bray <- metaMDS(spe, distance = \"bray\", trace = FALSE)\nnmds_bray$stress # nMDS goodness: stress\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.07429342\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"false\"}\npar(mfrow = c(1, 2))\nordiplot(pcoa_bray, display = \"sites\", type = \"text\", main = \"PCoA (Bray-Curtis)\")\nordiplot(\n  nmds_bray,\n  display = \"sites\",\n  type = \"text\",\n  main = paste0(\"nMDS (stress = \", round(nmds_bray$stress, 3), \")\")\n)\n```\n\n::: {.cell-output-display}\n![](Task_F_files/figure-html/task-f-q4-1.svg)\n:::\n:::\n\n\nThe two configurations are very similar, both showing the river gradient, but they answer different optimisation problems. PCoA finds axes that reproduce the dissimilarities *metrically* and reports its fit through the eigenvalues (the proportion of variation on the first axes). nMDS reproduces only the *rank order* of the dissimilarities and reports its fit through **stress** (here 0.074, indicating a faithful two-dimensional representation). When a low-stress nMDS and a high-variance PCoA agree, as here, that agreement is itself reassuring: the gradient is strong enough that the method choice barely matters.\n:::\n\n5. Explain what negative (\"imaginary\") eigenvalues are in PCoA, why they arise from non-Euclidean dissimilarities, and the corrections available (for example the Lingoes or Cailliez adjustments).\n\n::: {.callout-note collapse=\"true\"}\n## Show the answer\n\nPCoA seeks a set of real Euclidean coordinates whose pairwise distances reproduce the input dissimilarities. That is only possible if the dissimilarity is itself Euclidean. Many ecologically sensible measures (Bray-Curtis, Jaccard) are **not** Euclidean: there is no arrangement of points in real space whose straight-line distances equal them exactly. The part that cannot be embedded shows up as **negative eigenvalues**, the \"imaginary\" axes. Two standard fixes add a constant to the dissimilarities (the **Cailliez** correction) or to their squares (the **Lingoes** correction) so that the adjusted matrix becomes Euclidean and all eigenvalues turn non-negative. The alternative is simply to report proportions against the sum of absolute eigenvalues and to keep the negative values in view, which is what `capscale` does by default.\n:::\n\n6. On the basis of the above, when would you choose PCoA over PCA, CA, or nMDS?\n\n::: {.callout-note collapse=\"true\"}\n## Show the answer\n\nChoose **PCoA** when the dissimilarity measure is the thing you care about and you want a metric, eigenvalue-based ordination of it: it accepts any distance, including non-Euclidean ones (Bray-Curtis, Jaccard) and Gower distances on mixed-type data, which PCA and CA cannot. Choose **PCA** when the data are continuous variables with roughly linear relationships and Euclidean distance is appropriate. Choose **CA** when the data are an abundance table with unimodal species responses along a long gradient. Choose **nMDS** when you care more about preserving the rank order of dissimilarities than about metric axes, and are willing to trade eigenvalue interpretability for a lower-stress, flexible two-dimensional map. PCoA is the natural choice whenever the right description of difference is a specific dissimilarity rather than raw variables.\n:::\n\n## Assessment Criteria\n\nThis Task is not formally assessed. It is built around four hands-on analyses (Exercises 1--4) and two short conceptual questions (Exercises 5--6); work through all six and bring your annotated Quarto document to class for discussion.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}