{
  "hash": "a62d7c919bbe670f9fd666400a092174",
  "result": {
    "engine": "knitr",
    "markdown": "---\ndate: \"2026-08-19\"\ndate-modified: \"last-modified\"\ntitle: \"Lab 2b. Environmental Distance\"\nformat:\n  html:\n    anchor-sections: true\n    code-tools: false\n    date-format: long\n    date-modified: last-modified\n    date-modified-title: \"Last updated\"\n    number-sections: false\n    page-layout: article\nparams:\n  hide_answers: false\n#   typst:\n#     fontsize: 12pt\n#     hyphenate: true\n#     lang: en\n#     mainfont: \"Minion Pro\"\n#     section-numbering: 1.1.1.1\n#     toc: true\n---\n\n::: callout-note\n## BCB743\n\n**This material must be reviewed by BCB743 students in Week 1 of Quantitative Ecology.**\n:::\n\n::: callout-tip\n## This Lab Accompanies the Following Lecture\n\n-   [Lecture 4: Biodiversity Concepts](Lec-04-biodiversity.qmd)\n:::\n\n::: callout-tip\n## Data for This Lab\n\n-   Example xyz data -- [`Euclidean_distance_demo_data_xyz.csv`](../data/BDC334/Euclidean_distance_demo_data_xyz.csv)\n-   Example env data -- [`Euclidean_distance_demo_data_env.csv`](../data/BDC334/Euclidean_distance_demo_data_env.csv)\n-   The seaweed environmental data [@smit2017seaweeds] -- [`SeaweedEnv.RData`](../data/BCB743/seaweed/SeaweedEnv.RData)\n-   The seaweed coastal sections (sites) -- [`SeaweedSites.csv`](../data/BCB743/seaweed/SeaweedSites.csv)\n-   The Doubs River environmental data -- [`DoubsEnv.csv`](../data/BCB743/DoubsEnv.csv)\n:::\n\n> \"It's not that I'm so smart, it's just that I stay with problems longer.\"\n>\n> --- Albert Einstein\n\n\n::: {#tbl-data-frame .cell}\n\n:::\n\n\n# Set up the Analysis Environment\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(vegan)\nlibrary(ggplot2)\nlibrary(geodist) # to calculate geographic distances between lats/lons\nlibrary(ggpubr) # to arrange the multipanel graphs\n```\n:::\n\n\n# Revisiting Euclidean Distance\n\nThe toy data have arbitrary columns to demonstrate the Euclidean distance calculation:\n\n$$ d(a,b) = \\sqrt{(a_x - b_x)^2 + (a_y - b_y)^2 + (a_z - b_z)^2} $$\n\nThe distance is found between every pair of sites named ***a*** to ***g*** whose locations are marked by the 'coordinates' $x$, $y$, and $z$---i.e. this is an example of 3-dimensional data (a space or volume, as opposed to 2D data situated on a $x$, $y$ place). We might also call each coordinate a 'variable' (sometimes called a 'dimension') and hence we have multivariate or multidimensional data.\n\nLet's load the dataset and find the size of the dataframe:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# xyz <- read.csv(\"../data/BDC334/Euclidean_distance_demo_data_xyz.csv\")\nxyz <- read.csv(here::here(\"data\", \"BDC334\", \"Euclidean_distance_demo_data_xyz.csv\"))\ndim(xyz)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 7 4\n```\n\n\n:::\n:::\n\n\nThere are seven rows and four columns.\n\nThe data look like:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nxyz\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  site x y z\n1    a 4 1 3\n2    b 5 5 5\n3    c 6 6 4\n4    d 1 4 9\n5    e 2 3 8\n6    f 8 3 1\n7    g 9 1 5\n```\n\n\n:::\n:::\n\n\nThe first column contains the site names and it must be excluded from subsequent calculations. The remaining three columns will be used below.\n\nCalculate the Euclidean distance using **vegan**'s `vegdist()` function and view the lower triangle with the diagonal:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nxyz_euc <- round(\n    vegdist(xyz[, 2:4], method = \"euclidian\", upper = FALSE, diag = TRUE),\n    4\n)\n# selected only cols 2, 3 and 4\nxyz_euc\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        1       2       3       4       5       6       7\n1  0.0000                                                \n2  4.5826  0.0000                                        \n3  5.4772  1.7321  0.0000                                \n4  7.3485  5.7446  7.3485  0.0000                        \n5  5.7446  4.6904  6.4031  1.7321  0.0000                \n6  4.8990  5.3852  4.6904 10.6771  9.2195  0.0000        \n7  5.3852  5.6569  5.9161  9.4340  7.8740  4.5826  0.0000\n```\n\n\n:::\n:::\n\n\nConvert to a dataframe and view it:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nxyz_df <- as.data.frame(as.matrix(xyz_euc))\nxyz_df\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       1      2      3       4      5       6      7\n1 0.0000 4.5826 5.4772  7.3485 5.7446  4.8990 5.3852\n2 4.5826 0.0000 1.7321  5.7446 4.6904  5.3852 5.6569\n3 5.4772 1.7321 0.0000  7.3485 6.4031  4.6904 5.9161\n4 7.3485 5.7446 7.3485  0.0000 1.7321 10.6771 9.4340\n5 5.7446 4.6904 6.4031  1.7321 0.0000  9.2195 7.8740\n6 4.8990 5.3852 4.6904 10.6771 9.2195  0.0000 4.5826\n7 5.3852 5.6569 5.9161  9.4340 7.8740  4.5826 0.0000\n```\n\n\n:::\n:::\n\n\nDistance matrices have the same properties as dissimilarity matrices, i.e.:\n\ni.  The distance matrix is square (number rows = number columns).\n\nii. The diagonal is filled with 0.\n\niii. The matrix is symmetrical---it is comprised of symmetrical upper and lower triangles.\n\nIn terms of the meaning of the cell values, their interpretation is also analogous with that of the species dissimilarities. A value of 0 means the properties of the sites (or sections, plots, transects, quadrats, etc.) in terms of their environmental conditions are identical (this is always the case the the diagonal). The larger the number (which may be \\>1) the more different sites are in terms of their environmental conditions.\n\nSince each column, $x$, $y$, and $z$, is a variable, we can substitute them for *actual* variables or properties of the environment within which species are present. Let's load such data (again fictitious):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nenv_fict <- read.csv(here::here(\"data\", \"BDC334\", \"Euclidean_distance_demo_data_env.csv\"))\nhead(env_fict, 2) # print first two rows only\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  site temperature depth light\n1    a           4     1     3\n2    b           5     5     5\n```\n\n\n:::\n:::\n\n\nThese are the same data as in `Euclidean_distance_demo_data_xyz.csv` but I simply renamed the columns to names of the variables temperature, depth, and light intensity. I won't repeat the analysis here as the output remains the same.\n\nNow apply `vegdist()` as before. The resultant distances are called 'environmental distances'.\n\nLet us now use some real data.\n\n# A Look at the Seaweed Environmental Data\n\nThese data accompany the analysis of the South African seaweed flora [@smit2017seaweeds].\n\n\n::: {.cell}\n\n```{.r .cell-code}\nload(here::here(\"data\", \"BCB743\", \"seaweed\", \"SeaweedEnv.RData\"))\n\n# lets look at the data\ndim(env)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 58 18\n```\n\n\n:::\n:::\n\n\nWe see that the data have 58 rows and 18 columns... the same number of rows as the `seaweed.csv` data. What is in the first five rows?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nround(env[1:5, 1:5], 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  febMean  febMax  febMed  febX95 febRange\n1 13.0012 18.7204 12.6600 16.8097   6.0703\n2 13.3795 18.6190 13.1839 17.0724   5.8893\n3 13.3616 17.8646 13.2319 16.6111   5.4314\n4 13.2897 17.1207 13.1028 16.1214   5.0490\n5 12.8113 16.3783 12.4003 15.5324   4.9779\n```\n\n\n:::\n:::\n\n\nAnd the last five rows?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nround(env[(nrow(env) - 5):nrow(env), (ncol(env) - 5):ncol(env)], 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   annRange  febSD  augSD annChl augChl febChl\n53   4.3707 1.0423 0.7735 4.3420 4.3923 4.6902\n54   4.3358 1.1556 0.9104 1.6469 2.2654 1.6930\n55   4.4104 1.1988 0.8427 0.2325 0.6001 0.5422\n56   4.6089 1.1909 0.6631 0.1321 0.4766 0.3464\n57   4.9693 1.1429 0.4994 0.1339 0.5845 0.3185\n58   5.5743 1.0000 0.3494 0.1486 0.7363 0.4165\n```\n\n\n:::\n:::\n\n\nSo, each of the rows corresponds to a site (i.e. each of the coastal sections), and the columns each contains an environmental variable. The names of the environmental variables are:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncolnames(env)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"febMean\"  \"febMax\"   \"febMed\"   \"febX95\"   \"febRange\" \"augMean\" \n [7] \"augMin\"   \"augMed\"   \"augX5\"    \"augRange\" \"annMean\"  \"annSD\"   \n[13] \"annRange\" \"febSD\"    \"augSD\"    \"annChl\"   \"augChl\"   \"febChl\"  \n```\n\n\n:::\n:::\n\n\nAs we have seen, there are 18 variables (or dimensions). These data are truly multidimensional in a way that far exceeds our brains' limited ability to spatially visualise. For mathematicians these data define an 18-dimensional space, but all we can do is visualise 3-dimensions.\n\nWe select only some of the thermal variables; the rest are collinear with some of the ones I import:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nenv1 <- dplyr::select(\n    env,\n    febMean,\n    febRange,\n    febSD,\n    augMean,\n    augRange,\n    augSD,\n    annMean,\n    annRange,\n    annSD\n)\n```\n:::\n\n\nLet us make a quick graph of `annMean` as a function of distance along the coast (@fig-seawater-temp).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(env1, aes(x = 1:58, y = annMean)) +\n    geom_line(colour = \"indianred\", size = 1.2) +\n    labs(x = \"Coastal section (west to east)\", y = \"Temperature (°C)\") +\n    theme_linedraw()\n```\n\n::: {.cell-output-display}\n![Line plot showing the trend in the mean annual seawater temperature along the coast from the west at Section 1 to Section 58 in the East.](Lab-02b-env_dist_files/figure-html/fig-seawater-temp-1.svg){#fig-seawater-temp}\n:::\n:::\n\n\n# *z*-Scores\n\nHere we need to do something new that was not necessary with the toy data. We calculate *z*-scores, and the process is called 'standardisation'. Standardisation is necessary when the variables are measured in different units---e.g. the unit for temperature is °C whereas Ch-*a* is measured in mg Chl-*a*/m^3^.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nE1 <- round(decostand(env1, method = \"standardize\"), 4)\nE1[1:5, 1:5]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  febMean febRange   febSD augMean augRange\n1 -1.4915  -0.0443 -0.2713 -1.3765  -0.4735\n2 -1.4014  -0.1432 -0.1084 -1.4339  -0.0700\n3 -1.4057  -0.3932 -0.1720 -1.5269   0.0248\n4 -1.4228  -0.6020 -0.3121 -1.5797  -0.0508\n5 -1.5368  -0.6408 -0.4096 -1.5464  -0.0983\n```\n\n\n:::\n:::\n\n\nFor comparison with the previous plot showing the raw data, let us now plot the standardised `annMean` data (@fig-std-ann-mean).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(E1, aes(x = 1:58, y = annMean)) +\n    geom_line(colour = \"indianred\", size = 1.2) +\n    labs(x = \"Coastal section (west to east)\", y = \"Standardised temperature\") +\n    theme_linedraw()\n```\n\n::: {.cell-output-display}\n![Line plot showing the trend in the standardised mean annual seawater temperature along the coast from the west at Section 1 to Section 58 in the East.](Lab-02b-env_dist_files/figure-html/fig-std-ann-mean-1.svg){#fig-std-ann-mean}\n:::\n:::\n\n\n# Euclidean Distance\n\n\n::: {.cell}\n\n```{.r .cell-code}\nE1_euc <- round(vegdist(E1, method = \"euclidian\", upper = TRUE), 4)\nE1_df <- as.data.frame(as.matrix(E1_euc))\nE1_df[1:10, 1:10]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        1      2      3      4      5      6      7      8      9     10\n1  0.0000 0.7040 1.0006 1.1132 0.9902 0.9124 0.7849 0.7957 2.7901 2.0327\n2  0.7040 0.0000 0.3769 0.6126 0.6553 0.7726 0.6291 0.5565 2.2733 1.7509\n3  1.0006 0.3769 0.0000 0.2818 0.4729 0.7594 0.7164 0.7939 2.2692 1.8055\n4  1.1132 0.6126 0.2818 0.0000 0.3662 0.7566 0.7911 0.9708 2.4523 1.9019\n5  0.9902 0.6553 0.4729 0.3662 0.0000 0.4094 0.5261 0.9860 2.4847 2.1376\n6  0.9124 0.7726 0.7594 0.7566 0.4094 0.0000 0.2862 1.0129 2.4449 2.3483\n7  0.7849 0.6291 0.7164 0.7911 0.5261 0.2862 0.0000 0.7678 2.3035 2.1656\n8  0.7957 0.5565 0.7939 0.9708 0.9860 1.0129 0.7678 0.0000 2.2251 1.5609\n9  2.7901 2.2733 2.2692 2.4523 2.4847 2.4449 2.3035 2.2251 0.0000 2.8476\n10 2.0327 1.7509 1.8055 1.9019 2.1376 2.3483 2.1656 1.5609 2.8476 0.0000\n```\n\n\n:::\n:::\n\n\nWe already know how to read this matrix. Let's plot it as a function of the coastal section's number (@fig-env-dist).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = E1_df, (aes(x = 1:58, y = `1`))) +\n    geom_line(colour = \"indianred\", size = 1.2) +\n    xlab(\"Coastal section, west to east\") +\n    ylab(\"Environmental distance\") +\n    theme_linedraw()\n```\n\n::: {.cell-output-display}\n![Line plot showing the trend in environmental distance along the coast from the west at Section 1 to Section 58 in the East.](Lab-02b-env_dist_files/figure-html/fig-env-dist-1.svg){#fig-env-dist}\n:::\n:::\n\n\n::: callout-important\n## Lab 2\n\n(To be reviewed by BCB743 student but not for marks)\n\nUse the Doubs River environmental data for this exercise.\n\n**Total: 14 marks for BDC334 students.** Marks are assigned only to the\ncomponents listed below and under Question 8.\n\n1.  **(/ 2)** Standardise these data using R and display a portion of the resultant standardised data file.\n    - **Mark allocation:** 1 mark for the correct code; 1 mark for the correct portion of output.\n2.  **(/ no marks)** Discuss why standardisation was necessary for these data. Use the content of the actual 'raw' data file in your discussion.\n3.  **(/ 2)** Using R, calculate the Euclidean distances for these data and display a portion of the resultant distance matrix.\n    - **Mark allocation:** 1 mark for the correct code; 1 mark for the correct portion of output.\n4.  **(/ 6)** Discuss the ecological conclusions you are able to draw from these Euclidean distances. Provide two graphs to substantiate your answer.\n    - **Mark allocation:** 2 marks for the code for two graphs (1 per graph); 2 marks for two correct, publication-quality graphs (1 per graph), including full axis labels, units where applicable and readable presentation; 2 marks for correct explanations (1 per explanation), for example a gradient and a local perturbation.\n:::\n\n\n\n::: {.callout-tip appearance=\"simple\"}\n## Model answers: Tasks 1--4\n\nThese answers use **all 30 Doubs River sites and all 11 environmental\nvariables**. Lab 1 used only the odd-numbered sites for its distance and\ncorrelation matrices. Do not carry that selection into this exercise.\n\n### 1. Standardise the Doubs data\n\n**Marking: 2 marks — 1 for the code and 1 for the correct portion of output.**\n\nRead the site numbers as row names. They identify the samples and must\nnot become an extra environmental variable. The `dfs` column is\ndifferent: it records distance from the river's source and is retained\nhere to match the 11-variable analysis in Lab 1.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Read the downloaded DoubsEnv.csv in your working directory with:\n# doubs <- read.csv(\"DoubsEnv.csv\", row.names = 1)\n# This course website uses the same file at its repository location:\ndoubs <- read.csv(here::here(\"data\", \"BCB743\", \"DoubsEnv.csv\"),\n    row.names = 1\n)\n\n# Subtract each column's mean and divide by its sample SD.\ndoubs_z <- scale(doubs)\nknitr::kable(doubs_z[1:5, 1:6], digits = 3, row.names = TRUE)\n```\n\n::: {.cell-output-display}\n\n\n|   |    dfs|   alt|    slo|    flo|     pH|    har|\n|:--|------:|-----:|------:|------:|------:|------:|\n|1  | -1.350| 1.667|  5.141| -1.180| -0.864| -2.437|\n|2  | -1.336| 1.660| -0.057| -1.171| -0.288| -2.733|\n|3  | -1.279| 1.594|  0.023| -1.127|  1.439| -2.022|\n|4  | -1.219| 1.373| -0.034| -1.087| -0.288| -0.836|\n|5  | -1.197| 1.354| -0.138| -1.081|  0.288| -0.125|\n\n\n:::\n:::\n\n\nOnly a portion is displayed; `doubs_z` contains all 30 rows and 11\ncolumns. Each column should now have a mean of zero and a sample SD of\none, allowing for tiny numerical rounding errors:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nround(rbind(\n    mean = colMeans(doubs_z),\n    SD = apply(doubs_z, 2, sd)\n), 6)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     dfs alt slo flo pH har pho nit amm oxy bod\nmean   0   0   0   0  0   0   0   0   0   0   0\nSD     1   1   1   1  1   1   1   1   1   1   1\n```\n\n\n:::\n:::\n\n\n`vegan::decostand(doubs, method = \"standardize\")` gives the same\nstandardisation. Keep the full precision for subsequent calculations;\nround only what you display.\n\n### 2. Why standardisation matters here\n\n**No marks are assigned to this question.**\n\nLook at the actual scales in the file. Altitude ranges from 172 to 934,\nwhereas pH ranges from 7.7 to 8.6 and ammonium from 0 to 1.8. Squaring\nthe raw differences would let a variable with large numerical values,\nsuch as altitude, dominate the distance. That would reflect its scale\nof measurement rather than an explicit ecological decision about its\nimportance. Even changing altitude from metres to kilometres would\nchange the raw distances.\n\nStandardisation expresses each difference relative to the variation in\nthat variable across these 30 sites. A difference of one standard\ndeviation then makes the same contribution whichever variable it comes\nfrom. It does **not** make the variables biologically equally important,\nremove outliers, or remove correlations. Several correlated nutrient\nvariables can still give extra weight to a shared water-quality gradient.\n\n### 3. Calculate and inspect environmental distances\n\n**Marking: 2 marks — 1 for the code and 1 for the correct portion of output.**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate distances among sites, not among columns.\ndoubs_dist <- dist(doubs_z, method = \"euclidean\")\ndoubs_D <- as.matrix(doubs_dist)\nknitr::kable(doubs_D[1:5, 1:5], digits = 3, row.names = TRUE)\n```\n\n::: {.cell-output-display}\n\n\n|   |     1|     2|     3|     4|     5|\n|:--|-----:|-----:|-----:|-----:|-----:|\n|1  | 0.000| 5.319| 5.686| 5.498| 6.293|\n|2  | 5.319| 0.000| 1.924| 1.976| 3.142|\n|3  | 5.686| 1.924| 0.000| 2.201| 2.669|\n|4  | 5.498| 1.976| 2.201| 0.000| 2.173|\n|5  | 6.293| 3.142| 2.669| 2.173| 0.000|\n\n\n:::\n:::\n\n\nThe complete matrix is 30 × 30. Its diagonal is zero and its two\ntriangles mirror one another. Sites 2 and 3 have a distance of about\n1.924; Sites 1 and 5 have a distance of about 6.293. The second pair is\nmore different in the selected, standardised environmental variables.\nThese are not kilometres, percentages or probabilities, and a value\ngreater than one is perfectly possible.\n\n### 4. Describe the pattern, then consider its causes\n\n**Marking: 6 marks — 2 for the code for two graphs, 2 for two correct,\npublication-quality graphs, and 2 for correct explanations. Each graph\ncan earn 1 code mark, 1 presentation/output mark and 1 explanation mark.**\n\nA distance tells us how different two sites are overall. To explain\nthat difference, return to the variables that went into it. Plotting\nthem against distance from the source also respects the unequal spacing\nof the sampling sites. The two examples below show a broad altitude\ngradient and a local oxygen decline. Other suitable graphs and\nwell-supported explanations are acceptable.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(doubs, aes(dfs, alt)) +\n    geom_line(colour = \"indianred\", linewidth = 0.7) +\n    geom_point(size = 2) +\n    labs(x = \"Distance from source (km)\", y = \"Altitude (m)\") +\n    theme_linedraw(base_size = 12)\n```\n\n::: {.cell-output-display}\n![Altitude along the Doubs River. Points are the 30 sampled sites, positioned by their distance from the source.](Lab-02b-env_dist_files/figure-html/fig-lab2-answer-doubs-gradients-1.svg){#fig-lab2-answer-doubs-gradients}\n:::\n:::\n\n\n**Explanation 1:** Altitude decreases downstream, showing a broad\nlongitudinal gradient. Sites far apart along that gradient can have\nlarge environmental distances partly because they differ in altitude.\nThis is a description of river position and topography; it does not\nestablish that altitude caused every other environmental change.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(doubs, aes(dfs, oxy)) +\n    annotate(\"rect\",\n        xmin = doubs$dfs[23], xmax = doubs$dfs[25],\n        ymin = -Inf, ymax = Inf, fill = \"goldenrod\", alpha = 0.15\n    ) +\n    geom_line(colour = \"indianred\", linewidth = 0.7) +\n    geom_point(size = 2) +\n    labs(\n        x = \"Distance from source (km)\",\n        y = expression(\"Dissolved oxygen (mg \" * L^{\n            -1\n        } * \")\")\n    ) +\n    theme_linedraw(base_size = 12)\n```\n\n::: {.cell-output-display}\n![Dissolved oxygen along the Doubs River. Shading locates Sites 23--25, where oxygen is particularly low; concentrations rise again farther downstream.](Lab-02b-env_dist_files/figure-html/fig-lab2-answer-oxygen-perturbation-1.svg){#fig-lab2-answer-oxygen-perturbation}\n:::\n:::\n\n\n**Explanation 2:** The oxygen decline around Sites 23--25, followed by\nhigher concentrations downstream, is consistent with a local\nperturbation superimposed on the river gradient. Increased microbial\noxygen consumption after organic inputs is one possible explanation.\nThe high biological oxygen demand at these sites supports investigating\nthat explanation, but oxygen supply and reaeration must also be measured.\n\nThe wider dataset helps us interpret these two graphs:\n\n- **There is a broad downstream gradient.** Altitude decreases and flow\n  generally increases. Accumulating drainage and tributary inputs could\n  help explain increasing flow. Neighbouring sites often have similar\n  environments, but being neighbours does not guarantee similarity.\n- **Sites 23--25 show a marked water-quality change.** Phosphate,\n  ammonium and biological oxygen demand are high, while oxygen is low.\n  Sites 1 and 25 are the most different pair in this matrix, with a\n  distance of about 12.145. Site 1 also has an unusually steep slope,\n  which contributes to this difference. Sites 11 and 13 are much more\n  similar, with a distance of about 0.968.\n- **Some water-quality variables move back towards earlier values below\n  Site 25.** Oxygen rises while ammonium and biological oxygen demand\n  fall. Dilution, reaeration, uptake and processing of organic material\n  are possible explanations to investigate. The measurements do not\n  establish which process was responsible.\n\nOrganic inputs followed by microbial respiration offer one explanation\nfor the combination of high oxygen demand and low dissolved oxygen.\nHowever, a distance matrix cannot identify a discharge source, establish\ncausation or demonstrate a change in fish composition. Those conclusions\nrequire additional measurements. Also remember that `dfs` itself is in\nthis distance calculation: part of the spatial pattern is included by\nconstruction. Task 8 shows how to check the result without it.\n:::\n\n\n\nWe will explore distance and dissimilarity matrices in more detail in later sections.\n\n# Pairwise Correlations\n\nIt is easy to calculate pairwise correlation matrices for the above data:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nenv1_cor <- round(cor(env1), 2)\nenv1_cor\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         febMean febRange febSD augMean augRange augSD annMean annRange annSD\nfebMean     1.00    -0.27 -0.28    0.90    -0.10 -0.16    0.98     0.74  0.41\nfebRange   -0.27     1.00  0.79   -0.32     0.14  0.14   -0.29    -0.08  0.48\nfebSD      -0.28     0.79  1.00   -0.16     0.35  0.46   -0.26    -0.33  0.31\naugMean     0.90    -0.32 -0.16    1.00    -0.01 -0.05    0.96     0.37  0.13\naugRange   -0.10     0.14  0.35   -0.01     1.00  0.91   -0.10    -0.20  0.06\naugSD      -0.16     0.14  0.46   -0.05     0.91  1.00   -0.17    -0.27  0.08\nannMean     0.98    -0.29 -0.26    0.96    -0.10 -0.17    1.00     0.60  0.29\nannRange    0.74    -0.08 -0.33    0.37    -0.20 -0.27    0.60     1.00  0.68\nannSD       0.41     0.48  0.31    0.13     0.06  0.08    0.29     0.68  1.00\n```\n\n\n:::\n:::\n\n\n::: callout-important\n## Lab 2 (Continue)\n\n(To be reviewed by BCB743 student but not for marks)\n\n5.  **(/ no marks)** Explain in a short (1/3 page paragraph) what is meant by 'environmental distance'.\n6.  **(/ no marks)** Describe to your grandmother how to interpret the above correlation matrix, and also mention what the major conclusions are that can be drawn from studying the matrix. Add a mechanistic explanation to demonstrate to her what your thought processes are for reaching your conclusion.\n7.  **(/ no marks)** Explain why the same general trend is seen in the raw or standardised environmental data for `annMean` (Figure 1 and 2) and that of environmental distance (Figure 3).\n:::\n\n\n\n::: {.callout-tip appearance=\"simple\"}\n## Model answers: Tasks 5--7\n\n**No marks are assigned to Questions 5--7.**\n\n### 5. What is environmental distance?\n\nEnvironmental distance describes how different two sites are in a\nspecified set of environmental measurements. Imagine describing each\nsite by its altitude, flow, oxygen and other measured conditions. For\neach variable, take the difference between the two sites. Euclidean\ndistance squares these differences, adds them and takes the square\nroot. We standardise the Doubs variables first so that different units\nand numerical scales do not determine their contributions. Zero means\nthe sites have identical values for the variables included; larger\nvalues mean greater overall difference. Two geographically distant\nsites can therefore have a small environmental distance, while two\nnearby sites can have a large one. The result depends on which variables\nwe select and how we scale them. It summarises the measured environment;\nit is not a complete measure of habitat quality, species composition or\necological importance.\n\n### 6. Read the coastal correlation matrix\n\n**This question refers to the nine seaweed thermal variables in\n`env1_cor` immediately above, not to the Doubs distance matrix.**\n\nThink of each entry as asking whether two measurements tend to move\ntogether across the 58 coastal sections. A number close to +1 means\nsections with high values of one usually have high values of the other.\nA number close to −1 means high values of one usually accompany low\nvalues of the other. A value close to zero means little *linear*\nassociation; it does not rule out a curved relationship. The diagonal\nis all ones because each measurement is being compared with itself.\nThe repeated triangle contains the same information twice.\n\nHere are some examples from this matrix:\n\n| Comparison | Pearson's *r* | What it shows |\n|---|---:|---|\n| February mean and annual mean | 0.98 | Sections that are warm in February also tend to be warm over the year. |\n| August mean and annual mean | 0.96 | Much of that ordering persists in August. |\n| February mean and August mean | 0.90 | Warm and cool sections retain a broad seasonal consistency. |\n| August range and August SD | 0.91 | The two measures of within-month variability tend to increase together. |\n| February range and February SD | 0.79 | The same broad association occurs in February. |\n| Annual mean and August range | −0.10 | Mean warmth tells us little about August's range in a simple linear comparison. |\n\nDifferences in the source and mixing of coastal water could maintain\nrelatively cool and warm sections across seasons. Changes in water\nmovement or episodic upwelling could also produce temperature\nfluctuations within a month. To test those explanations, we would need\ntemperature time series together with information about water movement\nand upwelling. The matrix alone does not show which mechanism operates.\nThere is also a simpler reason for some correlations: annual and monthly\nmeans share underlying temperature observations, while range and SD\nboth describe variation. They are not independent lines of evidence.\n\n### 7. Why do the three coastal plots look broadly similar?\n\nThe raw and standardised `annMean` plots have **exactly the same shape**.\nStandardisation subtracts one constant and divides by another positive\nconstant. It changes the vertical scale but preserves the ordering,\npeaks and troughs.\n\nThe environmental-distance plot asks a different question. Its column\n`1` gives the distance of every section **from Section 1**, using all\nnine standardised thermal variables:\n\n$$\nd(1,j) = \\sqrt{\\sum_{k=1}^{9}(z_{1k}-z_{jk})^2}.\n$$\n\nSection 1 is a cool western reference section. Mean annual temperature\nrises broadly towards the east, and the February and August means\nchange with it. Many eastern sections therefore differ from Section 1\nin several variables at once, increasing their environmental distance.\nThis explains the broad resemblance. The curves need not match:\ntemperature range and variability also contribute, and environmental\ndistance has no sign. Choosing another reference section would change\nthe distance curve without changing the `annMean` curve. Do not\ninterpret Figure 3 as distance from each section's immediate neighbour,\nor as a geographic distance.\n:::\n\n\n\n# Euclidean Distance of Geographical Data\n\nWhen we calculate Euclidean distances between geographic lat/lon coordinate, the relationship between sections will be the same (but scaled) as actual geographic distances.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngeo <- read.csv(here::here(\"data\", \"BCB743\", \"seaweed\", \"SeaweedSites.csv\"))\ndim(geo)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 58  2\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(geo)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Latitude Longitude\n1 -28.98450  16.72429\n2 -29.38053  16.94238\n3 -29.83253  17.08194\n4 -30.26426  17.25928\n5 -30.67874  17.47638\n6 -31.08580  17.72167\n```\n\n\n:::\n:::\n\n\n<!--- The first column contains nonsense and must be removed: --->\n\nCalculate geographic distances (in meters) between coordinate pairs (@fig-geodist).\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndists <- geodist(geo, paired = TRUE, measure = \"geodesic\")\ndists_df <- as.data.frame(as.matrix(dists))\ncolnames(dists_df) <- seq(1:58)\ndists_df[1:5, 1:5]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          1         2         3         4         5\n1      0.00  48752.45 100201.82 151021.75 201380.00\n2  48752.45      0.00  51894.01 102638.03 152849.90\n3 100201.82  51894.01      0.00  50822.71 101197.22\n4 151021.75 102638.03  50822.71      0.00  50457.53\n5 201380.00 152849.90 101197.22  50457.53      0.00\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplt1 <- ggplot(data = dists_df, (aes(x = 1:58, y = `1` / 1000))) +\n    geom_line(colour = \"indianred\", size = 1.2) +\n    xlab(\"Coastal section, west to east\") +\n    ylab(\"Distance (km)\") +\n    ggtitle(\"Actual geographic distance\") +\n    theme_linedraw()\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndists_euc <- vegdist(geo, method = \"euclidian\")\ndists_euc_df <- round(as.data.frame(as.matrix(dists_euc)), 4)\ndists_euc_df[1:5, 1:5]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       1      2      3      4      5\n1 0.0000 0.4521 0.9204 1.3871 1.8537\n2 0.4521 0.0000 0.4731 0.9388 1.4037\n3 0.9204 0.4731 0.0000 0.4667 0.9336\n4 1.3871 0.9388 0.4667 0.0000 0.4679\n5 1.8537 1.4037 0.9336 0.4679 0.0000\n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplt2 <- ggplot(data = dists_euc_df, (aes(x = 1:58, y = `1`))) +\n    geom_line(colour = \"indianred\", size = 1.2) +\n    xlab(\"Coastal section, west to east\") +\n    ylab(\"Euclidean distance\") +\n    ggtitle(\"Euclidean distance\") +\n    theme_linedraw()\n\nggarrange(plt1, plt2, ncol = 2)\n```\n\n::: {.cell-output-display}\n![Line plots showing the relationship between Euclidean and geographical distance.](Lab-02b-env_dist_files/figure-html/fig-geodist-1.svg){#fig-geodist fig-align='center'}\n:::\n:::\n\n\n::: callout-important\n## Lab 2 (Continue)\n\n(To be reviewed by BCB743 student but not for marks)\n\n8.  **(/ 4)** Do a full analysis of the Doubs River environmental data using Euclidean distances and correlations. Demonstrate graphically any clear spatial patterns that you might find, and offer a full suite of mechanistic explanations for the patterns you see. It is sufficient to submit a fully annotated R script (not a MS Word or Excel file).\n    - **Mark allocation:** 1 mark for the Euclidean distance code; 1 mark for the correct visualisation of Euclidean distance; 1 mark for the correlations code; 1 mark for the correct pairwise correlations.\n:::\n\n\n\n::: {.callout-tip appearance=\"simple\"}\n## Model answer: Task 8\n\n### 8. Put the Doubs analysis together\n\n**Marking: 4 marks — 1 for the Euclidean distance code, 1 for its correct\nvisualisation, 1 for the correlations code, and 1 for the correct\npairwise correlations. No additional marks are assigned to the\ninterpretation or sensitivity check below.**\n\nA complete answer combines the calculations with an explanation of what\nthe figures show. The plots for Task 4 are part of that evidence. First\ninspect the full distance table, then its visualisation. Scroll within\nthe table to see all 30 site columns. Values are rounded for display;\nthe calculations retain full precision.\n\n```{=html}\n<style>\n#lab2-full-distance-table .cell-output-display { overflow: visible; }\n</style>\n```\n\n::: {#lab2-full-distance-table .table-responsive tabindex=\"0\" role=\"region\" aria-label=\"Euclidean distances among all 30 Doubs sites\" style=\"max-height: 28rem; overflow: auto;\"}\n\n::: {.cell}\n\n```{.r .cell-code}\ndoubs_D <- as.matrix(dist(scale(doubs), method = \"euclidean\"))\nknitr::kable(doubs_D, digits = 3, row.names = TRUE)\n```\n\n::: {.cell-output-display}\n\n\n|   |      1|      2|      3|      4|     5|     6|      7|     8|     9|    10|    11|    12|    13|    14|     15|    16|    17|    18|    19|    20|    21|    22|    23|    24|     25|    26|    27|    28|    29|    30|\n|:--|------:|------:|------:|------:|-----:|-----:|------:|-----:|-----:|-----:|-----:|-----:|-----:|-----:|------:|-----:|-----:|-----:|-----:|-----:|-----:|-----:|-----:|-----:|------:|-----:|-----:|-----:|-----:|-----:|\n|1  |  0.000|  5.319|  5.686|  5.498| 6.293| 5.391|  5.584| 6.740| 6.584| 5.380| 6.483| 6.289| 6.699| 7.139|  7.707| 6.650| 7.113| 7.035| 7.053| 7.231| 7.197| 7.288| 9.833| 8.885| 12.145| 8.585| 8.210| 8.911| 8.900| 9.249|\n|2  |  5.319|  0.000|  1.924|  1.976| 3.142| 1.669|  3.003| 3.978| 3.542| 3.537| 4.177| 3.676| 4.316| 4.729|  5.187| 4.061| 4.594| 4.490| 4.419| 4.761| 4.738| 4.819| 8.024| 6.767| 10.637| 6.487| 5.978| 6.791| 7.132| 7.309|\n|3  |  5.686|  1.924|  0.000|  2.201| 2.669| 2.430|  2.515| 3.438| 3.380| 4.203| 3.690| 3.803| 3.828| 3.755|  3.751| 3.925| 4.398| 4.348| 4.073| 4.665| 4.825| 4.430| 7.635| 6.497| 10.541| 6.422| 5.633| 6.130| 7.155| 6.772|\n|4  |  5.498|  1.976|  2.201|  0.000| 2.173| 1.437|  1.213| 2.939| 2.406| 2.481| 2.632| 2.263| 2.708| 3.334|  4.276| 2.812| 3.444| 3.328| 3.402| 3.805| 3.821| 3.826| 7.514| 6.071| 10.275| 5.751| 5.215| 5.903| 6.047| 6.282|\n|5  |  6.293|  3.142|  2.669|  2.173| 0.000| 2.190|  1.955| 0.990| 1.018| 2.960| 2.829| 3.081| 3.160| 3.317|  4.187| 2.929| 3.195| 3.281| 3.347| 3.756| 3.660| 3.434| 6.038| 4.625|  8.939| 4.774| 4.426| 5.176| 5.811| 5.730|\n|6  |  5.391|  1.669|  2.430|  1.437| 2.190| 0.000|  2.252| 2.864| 2.435| 2.237| 3.295| 2.634| 3.442| 4.018|  4.993| 3.171| 3.645| 3.634| 3.694| 4.039| 3.805| 3.963| 7.115| 5.710|  9.873| 5.460| 5.181| 6.156| 6.119| 6.515|\n|7  |  5.584|  3.003|  2.515|  1.213| 1.955| 2.252|  0.000| 2.515| 2.236| 2.700| 2.092| 2.253| 2.143| 2.647|  3.712| 2.656| 3.224| 3.160| 3.228| 3.711| 3.796| 3.550| 7.239| 5.804| 10.138| 5.598| 4.968| 5.490| 5.795| 5.825|\n|8  |  6.740|  3.978|  3.438|  2.939| 0.990| 2.864|  2.515| 0.000| 1.078| 3.207| 3.096| 3.424| 3.399| 3.508|  4.456| 3.151| 3.312| 3.496| 3.605| 3.973| 3.714| 3.421| 5.843| 4.269|  8.842| 4.571| 4.306| 5.104| 5.679| 5.568|\n|9  |  6.584|  3.542|  3.380|  2.406| 1.018| 2.435|  2.236| 1.078| 0.000| 2.531| 2.643| 2.825| 3.025| 3.371|  4.461| 2.480| 2.750| 2.836| 3.062| 3.325| 3.038| 3.003| 5.915| 4.195|  8.732| 4.187| 3.937| 4.818| 5.163| 5.293|\n|10 |  5.380|  3.537|  4.203|  2.481| 2.960| 2.237|  2.700| 3.207| 2.531| 0.000| 2.843| 2.016| 3.052| 4.012|  5.520| 2.500| 2.906| 2.910| 3.327| 3.316| 2.846| 3.425| 6.786| 5.101|  9.379| 4.599| 4.536| 5.640| 4.814| 5.780|\n|11 |  6.483|  4.177|  3.690|  2.632| 2.829| 3.295|  2.092| 3.096| 2.643| 2.843| 0.000| 1.602| 0.968| 1.347|  3.036| 1.193| 1.561| 1.479| 1.538| 2.049| 2.382| 2.061| 6.228| 4.721|  9.115| 4.243| 3.446| 3.806| 4.261| 4.248|\n|12 |  6.289|  3.676|  3.803|  2.263| 3.081| 2.634|  2.253| 3.424| 2.825| 2.016| 1.602| 0.000| 1.374| 2.498|  4.097| 1.613| 2.069| 1.952| 2.195| 2.499| 2.381| 2.535| 6.753| 5.139|  9.595| 4.564| 4.043| 4.823| 4.232| 4.828|\n|13 |  6.699|  4.316|  3.828|  2.708| 3.160| 3.442|  2.143| 3.399| 3.025| 3.052| 0.968| 1.374| 0.000| 1.337|  3.041| 1.724| 2.096| 1.974| 2.015| 2.564| 2.753| 2.336| 6.697| 5.162|  9.679| 4.724| 3.904| 4.285| 4.308| 4.332|\n|14 |  7.139|  4.729|  3.755|  3.334| 3.317| 4.018|  2.647| 3.508| 3.371| 4.012| 1.347| 2.498| 1.337| 0.000|  1.958| 2.178| 2.321| 2.296| 1.986| 2.726| 3.170| 2.359| 6.325| 5.018|  9.407| 4.736| 3.700| 3.701| 4.735| 4.137|\n|15 |  7.707|  5.187|  3.751|  4.276| 4.187| 4.993|  3.712| 4.456| 4.461| 5.520| 3.036| 4.097| 3.041| 1.958|  0.000| 3.628| 3.810| 3.694| 3.152| 3.954| 4.464| 3.427| 6.963| 5.895| 10.032| 5.743| 4.456| 4.076| 5.961| 4.680|\n|16 |  6.650|  4.061|  3.925|  2.812| 2.929| 3.171|  2.656| 3.151| 2.480| 2.500| 1.193| 1.613| 1.724| 2.178|  3.628| 0.000| 0.913| 0.791| 1.089| 1.279| 1.384| 1.492| 5.911| 4.209|  8.712| 3.587| 2.839| 3.532| 3.901| 4.142|\n|17 |  7.113|  4.594|  4.398|  3.444| 3.195| 3.645|  3.224| 3.312| 2.750| 2.906| 1.561| 2.069| 2.096| 2.321|  3.810| 0.913| 0.000| 0.640| 1.018| 0.867| 1.192| 1.336| 5.283| 3.629|  8.083| 3.036| 2.299| 3.013| 3.465| 3.710|\n|18 |  7.035|  4.490|  4.348|  3.328| 3.281| 3.634|  3.160| 3.496| 2.836| 2.910| 1.479| 1.952| 1.974| 2.296|  3.694| 0.791| 0.640| 0.000| 0.737| 0.780| 1.187| 1.334| 5.442| 3.819|  8.168| 3.118| 2.386| 3.049| 3.408| 3.637|\n|19 |  7.053|  4.419|  4.073|  3.402| 3.347| 3.694|  3.228| 3.605| 3.062| 3.327| 1.538| 2.195| 2.015| 1.986|  3.152| 1.089| 1.018| 0.737| 0.000| 1.007| 1.526| 1.184| 5.412| 3.912|  8.247| 3.264| 2.314| 2.826| 3.703| 3.550|\n|20 |  7.231|  4.761|  4.665|  3.805| 3.756| 4.039|  3.711| 3.973| 3.325| 3.316| 2.049| 2.499| 2.564| 2.726|  3.954| 1.279| 0.867| 0.780| 1.007| 0.000| 1.214| 1.541| 5.352| 3.815|  7.962| 3.047| 2.164| 2.767| 3.450| 3.669|\n|21 |  7.197|  4.738|  4.825|  3.821| 3.660| 3.805|  3.796| 3.714| 3.038| 2.846| 2.382| 2.381| 2.753| 3.170|  4.464| 1.384| 1.192| 1.187| 1.526| 1.214| 0.000| 1.256| 5.432| 3.495|  8.124| 2.598| 2.006| 3.171| 2.980| 3.542|\n|22 |  7.288|  4.819|  4.430|  3.826| 3.434| 3.963|  3.550| 3.421| 3.003| 3.425| 2.061| 2.535| 2.336| 2.359|  3.427| 1.492| 1.336| 1.334| 1.184| 1.541| 1.256| 0.000| 5.319| 3.449|  8.319| 2.864| 1.751| 2.632| 3.249| 2.983|\n|23 |  9.833|  8.024|  7.635|  7.514| 6.038| 7.115|  7.239| 5.843| 5.915| 6.786| 6.228| 6.753| 6.697| 6.325|  6.963| 5.911| 5.283| 5.442| 5.412| 5.352| 5.432| 5.319| 0.000| 2.494|  3.563| 3.542| 4.329| 4.718| 5.990| 5.640|\n|24 |  8.885|  6.767|  6.497|  6.071| 4.625| 5.710|  5.804| 4.269| 4.195| 5.101| 4.721| 5.139| 5.162| 5.018|  5.895| 4.209| 3.629| 3.819| 3.912| 3.815| 3.495| 3.449| 2.494| 0.000|  5.419| 1.587| 2.479| 3.465| 4.174| 4.040|\n|25 | 12.145| 10.637| 10.541| 10.275| 8.939| 9.873| 10.138| 8.842| 8.732| 9.379| 9.115| 9.595| 9.679| 9.407| 10.032| 8.712| 8.083| 8.168| 8.247| 7.962| 8.124| 8.319| 3.563| 5.419|  0.000| 6.006| 7.063| 7.259| 8.259| 8.233|\n|26 |  8.585|  6.487|  6.422|  5.751| 4.774| 5.460|  5.598| 4.571| 4.187| 4.599| 4.243| 4.564| 4.724| 4.736|  5.743| 3.587| 3.036| 3.118| 3.264| 3.047| 2.598| 2.864| 3.542| 1.587|  6.006| 0.000| 1.736| 2.952| 3.085| 3.351|\n|27 |  8.210|  5.978|  5.633|  5.215| 4.426| 5.181|  4.968| 4.306| 3.937| 4.536| 3.446| 4.043| 3.904| 3.700|  4.456| 2.839| 2.299| 2.386| 2.314| 2.164| 2.006| 1.751| 4.329| 2.479|  7.063| 1.736| 0.000| 1.637| 3.007| 2.491|\n|28 |  8.911|  6.791|  6.130|  5.903| 5.176| 6.156|  5.490| 5.104| 4.818| 5.640| 3.806| 4.823| 4.285| 3.701|  4.076| 3.532| 3.013| 3.049| 2.826| 2.767| 3.171| 2.632| 4.718| 3.465|  7.259| 2.952| 1.637| 0.000| 3.729| 2.451|\n|29 |  8.900|  7.132|  7.155|  6.047| 5.811| 6.119|  5.795| 5.679| 5.163| 4.814| 4.261| 4.232| 4.308| 4.735|  5.961| 3.901| 3.465| 3.408| 3.703| 3.450| 2.980| 3.249| 5.990| 4.174|  8.259| 3.085| 3.007| 3.729| 0.000| 2.356|\n|30 |  9.249|  7.309|  6.772|  6.282| 5.730| 6.515|  5.825| 5.568| 5.293| 5.780| 4.248| 4.828| 4.332| 4.137|  4.680| 4.142| 3.710| 3.637| 3.550| 3.669| 3.542| 2.983| 5.640| 4.040|  8.233| 3.351| 2.491| 2.451| 2.356| 0.000|\n\n\n:::\n:::\n\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlab2_pairs <- expand.grid(\n    site_a = seq_len(nrow(doubs)),\n    site_b = seq_len(nrow(doubs))\n)\nlab2_pairs$distance <- as.vector(doubs_D)\nggplot(lab2_pairs, aes(site_a, site_b, fill = distance)) +\n    geom_tile() +\n    coord_equal() +\n    scale_fill_viridis_c(name = \"Distance\") +\n    scale_x_continuous(breaks = c(1, 5, 10, 15, 20, 25, 30)) +\n    scale_y_continuous(breaks = c(1, 5, 10, 15, 20, 25, 30)) +\n    labs(x = \"Site\", y = \"Site\") +\n    theme_linedraw()\n```\n\n::: {.cell-output-display}\n![Euclidean distances among all 30 Doubs sites, using 11 variables standardised across all 30 sites. The axes are site identities in river order, not evenly spaced geographic positions.](Lab-02b-env_dist_files/figure-html/fig-lab2-answer-distance-map-1.svg){#fig-lab2-answer-distance-map}\n:::\n:::\n\n\nUse correlations to examine relationships **among variables**, rather\nthan differences among sites. These are Pearson correlations across all\n30 sites; standardising each column leaves them unchanged.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndoubs_cor <- cor(doubs, method = \"pearson\")\nknitr::kable(doubs_cor, digits = 2)\n```\n\n::: {.cell-output-display}\n\n\n|    |   dfs|   alt|   slo|   flo|    pH|   har|   pho|   nit|   amm|   oxy|   bod|\n|:---|-----:|-----:|-----:|-----:|-----:|-----:|-----:|-----:|-----:|-----:|-----:|\n|dfs |  1.00| -0.94| -0.38|  0.95|  0.01|  0.70|  0.48|  0.75|  0.41| -0.51|  0.39|\n|alt | -0.94|  1.00|  0.44| -0.87| -0.04| -0.74| -0.44| -0.76| -0.38|  0.36| -0.34|\n|slo | -0.38|  0.44|  1.00| -0.34| -0.22| -0.53| -0.19| -0.31| -0.17|  0.31| -0.18|\n|flo |  0.95| -0.87| -0.34|  1.00|  0.02|  0.70|  0.39|  0.61|  0.29| -0.36|  0.25|\n|pH  |  0.01| -0.04| -0.22|  0.02|  1.00|  0.09| -0.08| -0.05| -0.12|  0.18| -0.15|\n|har |  0.70| -0.74| -0.53|  0.70|  0.09|  1.00|  0.36|  0.51|  0.29| -0.38|  0.34|\n|pho |  0.48| -0.44| -0.19|  0.39| -0.08|  0.36|  1.00|  0.80|  0.97| -0.72|  0.89|\n|nit |  0.75| -0.76| -0.31|  0.61| -0.05|  0.51|  0.80|  1.00|  0.80| -0.63|  0.64|\n|amm |  0.41| -0.38| -0.17|  0.29| -0.12|  0.29|  0.97|  0.80|  1.00| -0.72|  0.89|\n|oxy | -0.51|  0.36|  0.31| -0.36|  0.18| -0.38| -0.72| -0.63| -0.72|  1.00| -0.84|\n|bod |  0.39| -0.34| -0.18|  0.25| -0.15|  0.34|  0.89|  0.64|  0.89| -0.84|  1.00|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlab2_panel_cor <- function(x, y, ...) {\n    old_usr <- par(\"usr\")\n    on.exit(par(usr = old_usr))\n    par(usr = c(0, 1, 0, 1))\n    text(0.5, 0.5, sprintf(\"%.2f\", cor(x, y)), cex = 0.9)\n}\npairs(doubs,\n    upper.panel = lab2_panel_cor,\n    pch = 16, cex = 0.5, cex.labels = 0.9, gap = 0.4,\n    col = ifelse(seq_len(nrow(doubs)) %in% 23:25,\n        \"indianred\", \"grey35\"\n    )\n)\n```\n\n::: {.cell-output-display}\n![Pairwise relationships among all 11 Doubs environmental variables. Lower panels show the 30 sites, with Sites 23--25 highlighted in red. Upper panels give Pearson's r; diagonal labels identify the variables. Each scatterplot uses the column variable on x and the row variable on y.](Lab-02b-env_dist_files/figure-html/fig-lab2-answer-pairwise-correlations-1.svg){#fig-lab2-answer-pairwise-correlations}\n:::\n:::\n\n\nAn ecological interpretation should connect three things: a measured\npattern, a possible mechanism, and evidence that could test it.\n\n| Measured pattern | Possible explanation | What else would help test it? |\n|---|---|---|\n| Altitude falls and flow rises downstream; `dfs`–`alt` *r* = −0.94 and `dfs`–`flo` *r* = 0.95. | The river descends through the catchment while drainage and tributaries add water. | Catchment area, tributary locations and repeated discharge measurements. |\n| Phosphate and ammonium rise together (*r* = 0.97), especially at Sites 23--25. | Shared nutrient inputs could affect both. Their common downstream setting could also contribute. | Measurements above and below suspected inputs, including input concentrations and flows. |\n| Biological oxygen demand is negatively associated with oxygen (*r* = −0.84). | Microbial processing of organic inputs can consume oxygen; the oxygen balance also depends on supply and reaeration. | Organic loading, temperature, oxygen through time, discharge and reaeration measurements. |\n| Hardness generally increases downstream (`dfs`–`har` *r* = 0.70). | Changes in geology, groundwater or tributary inputs could change dissolved mineral concentrations. | Catchment geology and the chemistry of groundwater and tributaries. |\n| Several water-quality indicators improve below Site 25. | Dilution, reaeration and biological or chemical processing could contribute. | Nutrient and oxygen budgets with repeated upstream, input and downstream sampling. |\n\nThese are explanations to test, not causes established by a correlation\ncoefficient. Site 1's steep slope and the high values at Sites 23--25\nalso warrant inspection in the raw plots. Pearson's *r* can be strongly\naffected by unusual observations and shared downstream trends. The\nriver sites are spatially connected, so they should not automatically\nbe treated as 30 independent replicates of a process.\n\nFor a useful sensitivity check, repeat the environmental distances\nwithout `dfs`. We are then asking about differences in measured\nconditions without including longitudinal position as one of those\nconditions. Sites 11 and 13 remain similar (about 0.957), but every\ndistance must be recalculated. Standardisation still uses all 30 sites.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndoubs_conditions <- doubs[, names(doubs) != \"dfs\"]\ndoubs_D_conditions <- as.matrix(dist(scale(doubs_conditions)))\nround(c(\n    with_dfs = doubs_D[\"11\", \"13\"],\n    without_dfs = doubs_D_conditions[\"11\", \"13\"]\n), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   with_dfs without_dfs \n      0.968       0.957 \n```\n\n\n:::\n:::\n\n\nThe [annotated model R script](resources/BDC334_Lab_2b_model_answers.R)\nrecreates the full Doubs analysis, including the two labelled Q4 graphs,\nsupplementary raw-variable plots, the distance table and figure, the\ncorrelation table and pairwise plot, and the check without\n`dfs`. Save it alongside `DoubsEnv.csv` and run it from that directory.\nThe comments show how to keep observations separate from proposed\nmechanisms. Other well-supported explanations are acceptable; a list\nof correlation coefficients alone is not an ecological explanation.\n:::\n\n\n\n::: callout-important\n## Submission Instructions\n\nThe Lab 2b assignment on Environmental Distance is due at **08:00 on Monday, 14 September 2026**.\n\nProvide a **neat and thoroughly annotated** R file which can recreate all the graphs and all calculations. Written answers must be typed in the same file as comments.\n\nPlease label the R file as follows:\n\n-   `BDC334_<first_name>_<last_name>_Lab_2.R`\n\n(the `<` and `>` must be omitted as they are used in the example as field indicators only).\n\nUpload your appropriately named R document to iKamva by the stated deadline.\nThis requirement applies to both pre-assessed and self-assessed submissions.\nIf this Lab is self-assessed, complete and upload the self-assessment to iKamva\nby 23:59 on the same day. See the\n[Lab submission and self-assessment policy](BDC334_syllabus.qmd#sec-lab-self-assessment)\nfor the checking and penalty rules.\n\nThe marked components total **14 marks**. Questions 2 and 5--7 remain\nlearning exercises without marks. Figure presentation is assessed\nwithin Question 4; there is no separate formatting mark.\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}