---
title: "BDC334"
subtitle: "Practical Assessment"
author: 
  - "AJ Smit"
date: "2024-08-29"
title-block-banner: false
toc: false
format:
  html:
    toc: false
---

You have been provided with three files:

- [`BarentsFish.xls`](../../data/BarentsFish.xls) (a Microsoft Excel file with the full dataset and a description of the content on the first sheet)
- [`BarentsFish_env.csv`](../../data/BarentsFish_env.csv) (a CSV file with the environmental data)
- [`BarentsFish_spp.csv`](../../data/BarentsFish_spp.csv) (a CSV file with the species data)

Import the CSV files into R and answer the questions below.

The assessment is out of a total of **50 marks** and you have **2 hours** to complete it.

You are welcome to use **any** online resources to help you complete the test, but you may not communicate with anyone else during the assessment.

## Question 1

a. List the three pairs of sites that are furthest apart in terms of the **geographical distance** between them. For each pair, also provide the temperature and depth associated with each member of the pair.

b. List three pairs of sites that are closest together in terms of the **geographical distance** between them. For each pair, also provide the temperature and depth associated with each member of the pair.

Communicate the above output in a clear and concise manner, for example, using a table. The same applies to the rest of the questions.

**(/10)**

## Question 2

a. List the three pairs of sites that are furthest apart in terms of the **environmental distance** between them. For each pair, also state the environmental distance between them.

b. List three pairs of sites that are closest together in terms of the **environmental distance** between them. For each pair, also state the environmental distance between them.

**(/10)**

## Question 3

Is there a relationship between the environmental variables? Produce the code for this analysis and the evidence (both graphical and statistical) for the nature of this relationship. If a relationship is present, describe it.

**(/10)**

## Question 4

a. List the three pairs of sites that are furthest apart in terms of **species composition** between them. For each pair, also state the species dissimilarity between them.

b. List three pairs of sites that are closest together in terms of **species composition** between them. For each pair, also state the species dissimilarity between them.

**(/10)**

## Question 5

Using all the answers given above to support your reasoning, discuss the implications of these findings in the light of the theory covered in the BDC334 module.

**(/10)**

**TOTAL /50**

## Instructions

Submit a R script onto iKamva at the end of the test period. Label the script as follows:

**`BDC334_<Surname>_<Student_no.>_Practical_Assessment.R`**.

Within the R script, ensure that all code:

- necessary to accomplish an answer is neatly and clearly associated with the question heading,
- works as intended, and that each line of code is properly accompanied by a comment explaining the purpose of the code,
- is well-structured and easy to follow, and
- is free of errors and warnings.

You are also welcome (encouraged, in fact) to add comments to your script to explain your reasoning or thought process.
