{
  "hash": "173a4e3ca671dbd417767f23dcc5039f",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"22. Quantile Regression\"\nsubtitle: \"Modelling the Whole Response Distribution\"\ndate: last-modified\ndate-format: \"YYYY/MM/DD\"\nreference-location: margin\n---\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n::: {.callout-note appearance=\"simple\"}\n## In This Chapter\n\n-   why modelling only the mean can hide important ecological structure;\n-   what quantile regression estimates and how it differs from ordinary least squares;\n-   when quantile regression is appropriate, and what its assumptions are;\n-   how to fit, compare, and visualise quantile regressions in R with `quantreg::rq()`;\n-   how to interpret lower, median, and upper quantile slopes biologically;\n-   how to report a quantile regression analysis in journal style.\n:::\n\n::: {.callout-important appearance=\"simple\"}\n## Tasks to Complete in This Chapter\n\n-   None\n:::\n\n# Introduction\n\nMost regression chapters so far have focused on the **conditional mean** of the response: ordinary least squares regression describes the average value of $Y$ expected at each value of $X$.\n\nFocussing on the mean may not always be enough. In ecology, the most interesting pattern may lie at the **edges** of the data cloud rather than through its centre. A predictor may place a strong upper limit on performance without explaining why some individuals or populations fall well below that limit. In such cases, a mean regression line can flatten over a broad wedge of points and miss the biological implication.\n\nInstead of modelling only the mean, **quantile regression** models one or more conditional quantiles of the response distribution. This allows us to ask whether a predictor has the same effect on the lower, middle, and upper parts of the response.\n\nThis may be useful when:\n\n-   variance changes across the predictor gradient;\n-   upper or lower boundaries are biologically important;\n-   outliers make mean-based summaries unstable;\n-   the ecological question is about constraints, limits, or heterogeneous responses rather than only about the average trend.\n\n# Key Concepts\n\n-   **Quantile regression models conditional quantiles**, not the conditional mean.\n-   **Quantiles** divide a distribution into cumulative proportions such as the 10th, 50th, or 90th percentile.\n-   **The median is the 0.5 quantile**, so median regression is a special case of quantile regression.\n-   **Tau ($\\tau$)** denotes the target quantile and ranges from 0 to 1.\n-   **Inference can differ across quantiles**, meaning that the same predictor may be weak at the lower boundary but strong at the upper boundary.\n-   **Quantile regression is robust to heteroscedasticity** and does not require normally distributed residuals in the way ordinary least squares does.\n\n# When This Method Is Appropriate\n\nQuantile regression is useful when:\n\n-   the response spread changes along the predictor gradient;\n-   the data form a wedge, funnel, or boundary pattern;\n-   upper or lower limits are biologically meaningful;\n-   you want a robust model of the median rather than the mean;\n-   the same predictor may affect slow-growing, average, and high-performing organisms differently.\n\nQuantile regression is not a substitute for every nonlinear or hierarchical model. If the relationship is curved, use polynomial or additive extensions where needed. If the data are clustered by site, year, or individual, the dependence structure is still important and should not be ignored just because the model is quantile-based.\n\n# Nature of the Data and Assumptions\n\nQuantile regression is more flexible than ordinary least squares, but it is not assumption-free.\n\nThe main requirements are:\n\n1. independent observations;\n2. a response variable that is continuous or at least ordered on a meaningful scale;\n3. a predictor-response relationship that is appropriately specified for the quantile model being fitted;\n4. enough data across the predictor range to estimate the chosen quantiles sensibly.\n\nUnlike ordinary least squares, quantile regression does **not** assume normally distributed residuals or constant variance. In fact, it is most useful exactly when spread changes with the predictor.\n\nWhat we need to consider is model form. If the relationship is curved, then a straight-line quantile model may be inadequate. It is also important to check that fitted quantile lines do not behave implausibly or cross in the range of interest.\n\n# The Core Equations\n\nFor a simple linear quantile regression, the conditional quantile of the response can be written as:\n\n$$Q_{Y}(\\tau \\mid X) = \\beta_{0}(\\tau) + \\beta_{1}(\\tau)X$$ {#eq-qr}\n\nIn @eq-qr, $Q_{Y}(\\tau \\mid X)$ is the $\\tau$-th conditional quantile of the response, $\\beta_{0}(\\tau)$ is the intercept for that quantile, and $\\beta_{1}(\\tau)$ is the slope for that quantile. The principle idea is that the coefficients are allowed to change with $\\tau$.\n\nOrdinary least squares chooses coefficients by minimising squared residuals. Quantile regression instead minimises an asymmetrically weighted sum of absolute residuals:\n\n$$\\min_{\\beta} \\sum_{i=1}^{n} \\rho_{\\tau}\\left(y_{i} - x_{i}^{T}\\beta\\right)$$ {#eq-check}\n\nwhere the check-loss function is:\n\n$$\\rho_{\\tau}(u) = u\\left[\\tau - I(u < 0)\\right]$$ {#eq-rho}\n\nYou do not need to memorise @eq-check and @eq-rho, but they explain why quantile regression behaves differently from mean regression. Residuals above and below the fitted line are weighted differently depending on the target quantile. For the median, positive and negative residuals are weighted equally; for the 90th quantile, underprediction is penalised more strongly than overprediction.\n\n# R Functions\n\nThe main function is `quantreg::rq()`.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrq(y ~ x, tau = 0.5, data = df)                     # median regression\nrq(y ~ x, tau = 0.9, data = df)                     # upper quantile\nrq(y ~ x, tau = c(0.1, 0.5, 0.9), data = df)        # several quantiles at once\nsummary(model, se = \"nid\")                          # coefficient summaries\nanova(model_multi_tau)                              # compare slopes across quantiles\n```\n:::\n\n\nThe syntax is similar to `lm()`, which makes quantile regression easy to adopt once you are comfortable with ordinary regression.\n\n# Example 1: Blade-Length Envelopes in *Laminaria pallida*\n\n## Example Dataset\n\nWe use the `laminaria.csv` dataset from the course data folder. These data come from a morphometric sampling campaign on the kelp *Laminaria pallida* at 13 sites along the Cape Peninsula, spanning the west coast and False Bay regions. The sampled plants were large adult kelps, and several blade and stipe measurements were recorded for each individual.\n\nHere we focus on the relationship between `stipe_length` and `blade_length`.\n\nThe biological question is simply, **does increasing stipe length shift the whole distribution of blade length in the same way, or is the effect stronger for the upper envelope of blade length than for the lower envelope?**\n\n\n::: {.cell layout-align=\"center\" tbl-cap='A subset of the `laminaria.csv` data used in the quantile-regression example.'}\n\n```{.r .cell-code}\nlaminaria <- read_csv(file.path(\"..\", \"..\", \"data\", \"BCB744\", \"laminaria.csv\"),\n                      show_col_types = FALSE) |>\n  select(region, site, blade_length, stipe_length) |>\n  filter(is.finite(blade_length), is.finite(stipe_length))\n\ngt(head(laminaria, 10))\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"kcezqwfcgq\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#kcezqwfcgq table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#kcezqwfcgq thead, #kcezqwfcgq tbody, #kcezqwfcgq tfoot, #kcezqwfcgq tr, #kcezqwfcgq td, #kcezqwfcgq th {\n  border-style: none;\n}\n\n#kcezqwfcgq p {\n  margin: 0;\n  padding: 0;\n}\n\n#kcezqwfcgq .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#kcezqwfcgq .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#kcezqwfcgq .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#kcezqwfcgq .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#kcezqwfcgq .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#kcezqwfcgq .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#kcezqwfcgq .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#kcezqwfcgq .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#kcezqwfcgq .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#kcezqwfcgq .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#kcezqwfcgq .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#kcezqwfcgq .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#kcezqwfcgq .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#kcezqwfcgq .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#kcezqwfcgq .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#kcezqwfcgq .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#kcezqwfcgq .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#kcezqwfcgq .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#kcezqwfcgq .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#kcezqwfcgq .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#kcezqwfcgq .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#kcezqwfcgq .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#kcezqwfcgq .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#kcezqwfcgq .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#kcezqwfcgq .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#kcezqwfcgq .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#kcezqwfcgq .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#kcezqwfcgq .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#kcezqwfcgq .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#kcezqwfcgq .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#kcezqwfcgq .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#kcezqwfcgq .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#kcezqwfcgq .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#kcezqwfcgq .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#kcezqwfcgq .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#kcezqwfcgq .gt_left {\n  text-align: left;\n}\n\n#kcezqwfcgq .gt_center {\n  text-align: center;\n}\n\n#kcezqwfcgq .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#kcezqwfcgq .gt_font_normal {\n  font-weight: normal;\n}\n\n#kcezqwfcgq .gt_font_bold {\n  font-weight: bold;\n}\n\n#kcezqwfcgq .gt_font_italic {\n  font-style: italic;\n}\n\n#kcezqwfcgq .gt_super {\n  font-size: 65%;\n}\n\n#kcezqwfcgq .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#kcezqwfcgq .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#kcezqwfcgq .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#kcezqwfcgq .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#kcezqwfcgq .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#kcezqwfcgq .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#kcezqwfcgq .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#kcezqwfcgq .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#kcezqwfcgq div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"region\">region</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"site\">site</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"blade_length\">blade_length</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"stipe_length\">stipe_length</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"region\" class=\"gt_row gt_left\">WC</td>\n<td headers=\"site\" class=\"gt_row gt_left\">Kommetjie</td>\n<td headers=\"blade_length\" class=\"gt_row gt_right\">160</td>\n<td headers=\"stipe_length\" class=\"gt_row gt_right\">120</td></tr>\n    <tr><td headers=\"region\" class=\"gt_row gt_left\">WC</td>\n<td headers=\"site\" class=\"gt_row gt_left\">Kommetjie</td>\n<td headers=\"blade_length\" class=\"gt_row gt_right\">120</td>\n<td headers=\"stipe_length\" class=\"gt_row gt_right\">149</td></tr>\n    <tr><td headers=\"region\" class=\"gt_row gt_left\">WC</td>\n<td headers=\"site\" class=\"gt_row gt_left\">Kommetjie</td>\n<td headers=\"blade_length\" class=\"gt_row gt_right\">110</td>\n<td headers=\"stipe_length\" class=\"gt_row gt_right\">97</td></tr>\n    <tr><td headers=\"region\" class=\"gt_row gt_left\">WC</td>\n<td headers=\"site\" class=\"gt_row gt_left\">Kommetjie</td>\n<td headers=\"blade_length\" class=\"gt_row gt_right\">159</td>\n<td headers=\"stipe_length\" class=\"gt_row gt_right\">167</td></tr>\n    <tr><td headers=\"region\" class=\"gt_row gt_left\">WC</td>\n<td headers=\"site\" class=\"gt_row gt_left\">Kommetjie</td>\n<td headers=\"blade_length\" class=\"gt_row gt_right\">149</td>\n<td headers=\"stipe_length\" class=\"gt_row gt_right\">146</td></tr>\n    <tr><td headers=\"region\" class=\"gt_row gt_left\">WC</td>\n<td headers=\"site\" class=\"gt_row gt_left\">Kommetjie</td>\n<td headers=\"blade_length\" class=\"gt_row gt_right\">107</td>\n<td headers=\"stipe_length\" class=\"gt_row gt_right\">161</td></tr>\n    <tr><td headers=\"region\" class=\"gt_row gt_left\">WC</td>\n<td headers=\"site\" class=\"gt_row gt_left\">Kommetjie</td>\n<td headers=\"blade_length\" class=\"gt_row gt_right\">104</td>\n<td headers=\"stipe_length\" class=\"gt_row gt_right\">110</td></tr>\n    <tr><td headers=\"region\" class=\"gt_row gt_left\">WC</td>\n<td headers=\"site\" class=\"gt_row gt_left\">Kommetjie</td>\n<td headers=\"blade_length\" class=\"gt_row gt_right\">111</td>\n<td headers=\"stipe_length\" class=\"gt_row gt_right\">136</td></tr>\n    <tr><td headers=\"region\" class=\"gt_row gt_left\">WC</td>\n<td headers=\"site\" class=\"gt_row gt_left\">Kommetjie</td>\n<td headers=\"blade_length\" class=\"gt_row gt_right\">178</td>\n<td headers=\"stipe_length\" class=\"gt_row gt_right\">176</td></tr>\n    <tr><td headers=\"region\" class=\"gt_row gt_left\">FB</td>\n<td headers=\"site\" class=\"gt_row gt_left\">Bordjiestif North</td>\n<td headers=\"blade_length\" class=\"gt_row gt_right\">145</td>\n<td headers=\"stipe_length\" class=\"gt_row gt_right\">82</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n## Do an Exploratory Data Analysis (EDA)\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlaminaria |>\n  summarise(\n    n = n(),\n    n_sites = n_distinct(site),\n    min_stipe = min(stipe_length),\n    max_stipe = max(stipe_length),\n    mean_stipe = mean(stipe_length),\n    mean_blade = mean(blade_length),\n    sd_blade = sd(blade_length)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR> # A tibble: 1 × 7\nR>       n n_sites min_stipe max_stipe mean_stipe mean_blade sd_blade\nR>   <int>   <int>     <dbl>     <dbl>      <dbl>      <dbl>    <dbl>\nR> 1   140      13        34       224       111.       139.     23.9\n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(laminaria, aes(x = stipe_length, y = blade_length)) +\n  geom_point(alpha = 0.65) +\n  labs(\n    x = \"Stipe length (cm)\",\n    y = \"Blade length (cm)\"\n  )\n```\n\n::: {.cell-output-display}\n![Blade length as a function of stipe length in adult _Laminaria pallida_ collected across 13 sites.](22-quantile-regression_files/figure-html/fig-laminaria-scatter-1.svg){#fig-laminaria-scatter fig-align='center' width=1200}\n:::\n:::\n\n\nThe scatterplot does not suggest a single, uniform linear effect. Blade length generally increases with stipe length, but the spread also changes across the predictor range. In particular, the upper edge of the point cloud steepens more strongly than the lower edge. That is exactly the kind of pattern for which quantile regression is useful.\n\n## State the Model Question and Hypotheses\n\nWe want to know whether stipe length affects the lower, median, and upper parts of the blade-length distribution differently.\n\nFor any fitted quantile, a useful hypothesis pair is:\n\n$$H_{0}: \\beta_{1}(\\tau) = 0$$\n$$H_{a}: \\beta_{1}(\\tau) \\ne 0$$\n\nThis asks whether stipe length has any association with blade length at the chosen quantile.\n\nBecause the chapter is about comparing quantiles, we also care about whether the slopes differ among quantiles:\n\n$$H_{0}: \\beta_{1}(0.1) = \\beta_{1}(0.5) = \\beta_{1}(0.9)$$\n$$H_{a}: \\text{not all quantile slopes are equal}$$\n\n## Fit the Models\n\nWe fit one ordinary least squares regression for comparison, and then three quantile regressions for the 10th, 50th, and 90th quantiles.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfit_ols <- lm(blade_length ~ stipe_length, data = laminaria)\n\nfit_rq10 <- rq(blade_length ~ stipe_length, tau = 0.1, data = laminaria)\nfit_rq50 <- rq(blade_length ~ stipe_length, tau = 0.5, data = laminaria)\nfit_rq90 <- rq(blade_length ~ stipe_length, tau = 0.9, data = laminaria)\n\nfit_rq_all <- rq(blade_length ~ stipe_length,\n                 tau = c(0.1, 0.5, 0.9),\n                 data = laminaria)\n```\n:::\n\n\nThe coefficient summaries are:\n\n\n::: {.cell layout-align=\"center\" tbl-cap='Coefficient summaries for the ordinary least squares fit and the 0.1, 0.5, and 0.9 quantile-regression fits.'}\n\n```{.r .cell-code}\ncoef_tbl <- bind_rows(\n  as.data.frame(summary(fit_ols)$coefficients) |>\n    rownames_to_column(\"term\") |>\n    mutate(model = \"OLS mean\"),\n  as.data.frame(summary(fit_rq10, se = \"nid\")$coefficients) |>\n    rownames_to_column(\"term\") |>\n    mutate(model = \"tau = 0.1\"),\n  as.data.frame(summary(fit_rq50, se = \"nid\")$coefficients) |>\n    rownames_to_column(\"term\") |>\n    mutate(model = \"tau = 0.5\"),\n  as.data.frame(summary(fit_rq90, se = \"nid\")$coefficients) |>\n    rownames_to_column(\"term\") |>\n    mutate(model = \"tau = 0.9\")\n) |>\n  rename(\n    estimate = 2,\n    std_error = 3,\n    t_value = 4,\n    p_value = 5\n  ) |>\n  mutate(across(c(estimate, std_error, t_value), round, 3))\n\ngt(coef_tbl)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"rwltpncenr\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#rwltpncenr table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#rwltpncenr thead, #rwltpncenr tbody, #rwltpncenr tfoot, #rwltpncenr tr, #rwltpncenr td, #rwltpncenr th {\n  border-style: none;\n}\n\n#rwltpncenr p {\n  margin: 0;\n  padding: 0;\n}\n\n#rwltpncenr .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#rwltpncenr .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#rwltpncenr .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#rwltpncenr .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#rwltpncenr .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#rwltpncenr .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#rwltpncenr .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#rwltpncenr .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#rwltpncenr .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#rwltpncenr .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#rwltpncenr .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#rwltpncenr .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#rwltpncenr .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#rwltpncenr .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#rwltpncenr .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#rwltpncenr .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#rwltpncenr .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#rwltpncenr .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#rwltpncenr .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rwltpncenr .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#rwltpncenr .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#rwltpncenr .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#rwltpncenr .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rwltpncenr .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#rwltpncenr .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#rwltpncenr .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#rwltpncenr .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rwltpncenr .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#rwltpncenr .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#rwltpncenr .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#rwltpncenr .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#rwltpncenr .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#rwltpncenr .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rwltpncenr .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#rwltpncenr .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rwltpncenr .gt_left {\n  text-align: left;\n}\n\n#rwltpncenr .gt_center {\n  text-align: center;\n}\n\n#rwltpncenr .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#rwltpncenr .gt_font_normal {\n  font-weight: normal;\n}\n\n#rwltpncenr .gt_font_bold {\n  font-weight: bold;\n}\n\n#rwltpncenr .gt_font_italic {\n  font-style: italic;\n}\n\n#rwltpncenr .gt_super {\n  font-size: 65%;\n}\n\n#rwltpncenr .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#rwltpncenr .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#rwltpncenr .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#rwltpncenr .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#rwltpncenr .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#rwltpncenr .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#rwltpncenr .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#rwltpncenr .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#rwltpncenr div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"std_error\">std_error</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"t_value\">t_value</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p_value\">p_value</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"model\">model</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Value\">Value</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">114.967</td>\n<td headers=\"std_error\" class=\"gt_row gt_right\">5.699</td>\n<td headers=\"t_value\" class=\"gt_row gt_right\">20.172</td>\n<td headers=\"p_value\" class=\"gt_row gt_right\">5.492740e-43</td>\n<td headers=\"model\" class=\"gt_row gt_left\">OLS mean</td>\n<td headers=\"Value\" class=\"gt_row gt_right\">NA</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">stipe_length</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">0.217</td>\n<td headers=\"std_error\" class=\"gt_row gt_right\">0.048</td>\n<td headers=\"t_value\" class=\"gt_row gt_right\">4.482</td>\n<td headers=\"p_value\" class=\"gt_row gt_right\">1.537502e-05</td>\n<td headers=\"model\" class=\"gt_row gt_left\">OLS mean</td>\n<td headers=\"Value\" class=\"gt_row gt_right\">NA</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">NA</td>\n<td headers=\"std_error\" class=\"gt_row gt_right\">5.948</td>\n<td headers=\"t_value\" class=\"gt_row gt_right\">16.537</td>\n<td headers=\"p_value\" class=\"gt_row gt_right\">0.000000e+00</td>\n<td headers=\"model\" class=\"gt_row gt_left\">tau = 0.1</td>\n<td headers=\"Value\" class=\"gt_row gt_right\">98.3600000</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">stipe_length</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">NA</td>\n<td headers=\"std_error\" class=\"gt_row gt_right\">0.059</td>\n<td headers=\"t_value\" class=\"gt_row gt_right\">2.023</td>\n<td headers=\"p_value\" class=\"gt_row gt_right\">4.504584e-02</td>\n<td headers=\"model\" class=\"gt_row gt_left\">tau = 0.1</td>\n<td headers=\"Value\" class=\"gt_row gt_right\">0.1200000</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">NA</td>\n<td headers=\"std_error\" class=\"gt_row gt_right\">6.458</td>\n<td headers=\"t_value\" class=\"gt_row gt_right\">17.023</td>\n<td headers=\"p_value\" class=\"gt_row gt_right\">0.000000e+00</td>\n<td headers=\"model\" class=\"gt_row gt_left\">tau = 0.5</td>\n<td headers=\"Value\" class=\"gt_row gt_right\">109.9299363</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">stipe_length</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">NA</td>\n<td headers=\"std_error\" class=\"gt_row gt_right\">0.073</td>\n<td headers=\"t_value\" class=\"gt_row gt_right\">3.488</td>\n<td headers=\"p_value\" class=\"gt_row gt_right\">6.523367e-04</td>\n<td headers=\"model\" class=\"gt_row gt_left\">tau = 0.5</td>\n<td headers=\"Value\" class=\"gt_row gt_right\">0.2547771</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">NA</td>\n<td headers=\"std_error\" class=\"gt_row gt_right\">10.231</td>\n<td headers=\"t_value\" class=\"gt_row gt_right\">12.770</td>\n<td headers=\"p_value\" class=\"gt_row gt_right\">0.000000e+00</td>\n<td headers=\"model\" class=\"gt_row gt_left\">tau = 0.9</td>\n<td headers=\"Value\" class=\"gt_row gt_right\">130.6538462</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">stipe_length</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">NA</td>\n<td headers=\"std_error\" class=\"gt_row gt_right\">0.055</td>\n<td headers=\"t_value\" class=\"gt_row gt_right\">6.242</td>\n<td headers=\"p_value\" class=\"gt_row gt_right\">4.979948e-09</td>\n<td headers=\"model\" class=\"gt_row gt_left\">tau = 0.9</td>\n<td headers=\"Value\" class=\"gt_row gt_right\">0.3461538</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\nTo compare the quantile slopes directly, we test whether the fitted slopes are equal across $\\tau = 0.1$, $0.5$, and $0.9$:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nanova(fit_rq_all)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR> Quantile Regression Analysis of Deviance Table\nR> \nR> Model: blade_length ~ stipe_length\nR> Joint Test of Equality of Slopes: tau in {  0.1 0.5 0.9  }\nR> \nR>   Df Resid Df F value  Pr(>F)  \nR> 1  2      418  4.3359 0.01368 *\nR> ---\nR> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n## Test Assumptions / Check Diagnostics\n\nQuantile regression does not require homoscedasticity or normal residuals, so diagnostics focus more on whether the fitted lines are sensible and whether the model form is adequate.\n\nThe first check is visual: do the fitted quantile lines follow the structure of the data, and do they avoid pathological crossing?\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nline_df <- tibble(\n  model = c(\"Mean (OLS)\", \"tau = 0.1\", \"tau = 0.5\", \"tau = 0.9\"),\n  intercept = c(coef(fit_ols)[1], coef(fit_rq10)[1], coef(fit_rq50)[1], coef(fit_rq90)[1]),\n  slope = c(coef(fit_ols)[2], coef(fit_rq10)[2], coef(fit_rq50)[2], coef(fit_rq90)[2])\n)\n\nggplot(laminaria, aes(x = stipe_length, y = blade_length)) +\n  geom_point(alpha = 0.45) +\n  geom_abline(\n    data = line_df,\n    aes(intercept = intercept, slope = slope, colour = model, linetype = model),\n    linewidth = 0.8\n  ) +\n  scale_colour_manual(\n    values = c(\n      \"Mean (OLS)\" = \"black\",\n      \"tau = 0.1\" = \"dodgerblue4\",\n      \"tau = 0.5\" = \"firebrick3\",\n      \"tau = 0.9\" = \"darkgreen\"\n    ),\n    name = \"Model\"\n  ) +\n  scale_linetype_manual(\n    values = c(\n      \"Mean (OLS)\" = \"dashed\",\n      \"tau = 0.1\" = \"solid\",\n      \"tau = 0.5\" = \"solid\",\n      \"tau = 0.9\" = \"solid\"\n    ),\n    name = \"Model\"\n  ) +\n  labs(\n    x = \"Stipe length (cm)\",\n    y = \"Blade length (cm)\"\n  )\n```\n\n::: {.cell-output-display}\n![Ordinary least squares and quantile-regression fits for the 10th, 50th, and 90th quantiles.](22-quantile-regression_files/figure-html/fig-qr-lines-1.svg){#fig-qr-lines fig-align='center' width=1500}\n:::\n:::\n\n\nThe second useful check is whether the fitted slope itself changes smoothly across a wider range of quantiles.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntau_grid <- seq(0.1, 0.9, by = 0.1)\n\nslope_grid <- map_dfr(\n  tau_grid,\n  \\(tau_now) {\n    fit_now <- rq(blade_length ~ stipe_length, tau = tau_now, data = laminaria)\n    sum_now <- summary(fit_now, se = \"nid\")$coefficients\n    tibble(\n      tau = tau_now,\n      slope = sum_now[\"stipe_length\", 1],\n      se = sum_now[\"stipe_length\", 2]\n    )\n  }\n) |>\n  mutate(\n    lo = slope - 1.96 * se,\n    hi = slope + 1.96 * se\n  )\n\nggplot(slope_grid, aes(x = tau, y = slope)) +\n  geom_ribbon(aes(ymin = lo, ymax = hi), alpha = 0.2) +\n  geom_line(linewidth = 0.8) +\n  geom_point(size = 1.5) +\n  labs(\n    x = expression(tau),\n    y = \"Estimated slope\"\n  )\n```\n\n::: {.cell-output-display}\n![Estimated slope of blade length on stipe length across quantiles from 0.1 to 0.9.](22-quantile-regression_files/figure-html/fig-qr-slopes-1.svg){#fig-qr-slopes fig-align='center' width=1200}\n:::\n:::\n\n\nIn this example the fitted lines do not cross in the observed data range, and the slope increases steadily towards the upper quantiles. That is consistent with a biologically meaningful quantile effect rather than a numerical artefact.\n\n## Interpret the Results\n\nThe ordinary least squares fit gives the average change in blade length with stipe length. In these data that mean slope is positive, but it understates what is happening at the upper edge of the distribution.\n\nThe quantile regressions show that the relationship is not constant across the response distribution. This is clearest in @fig-qr-lines and is reinforced by the slope-by-quantile summary in @fig-qr-slopes:\n\n-   at $\\tau = 0.1$, the fitted slope is about `0.12`;\n-   at $\\tau = 0.5$, the fitted slope is about `0.255`;\n-   at $\\tau = 0.9$, the fitted slope is about `0.346`.\n\nThis means that longer stipes are associated with modest increases in blade length near the lower boundary of the data, but much larger increases near the upper boundary. In other words, stipe length is a much stronger predictor of the **longest** blades than of the **shortest** blades.\n\nThe joint quantile comparison must also be considered. The quantile ANOVA indicates that the slopes are not all the same across $\\tau = 0.1$, $0.5$, and $0.9$ (`F = 4.34`, `p < 0.05`), and gives formal statistical support to what the figure already suggests visually.\n\nBiologically, the result reveals that increasing stipe length appears to raise the upper potential for blade elongation more strongly than it shifts the lower end of the distribution. That is the kind of edge-case ecological pattern that mean ordinary least squares regression can hide; it is visible directly in @fig-qr-lines.\n\n## Reporting\n\n::: {.callout-note appearance=\"simple\"}\n## Write-Up\n\n**Methods**\n\nBlade length was analysed as a function of stipe length in adult _Laminaria pallida_ sampled across 13 sites on the Cape Peninsula. To assess whether stipe length affected only the mean blade length or different parts of the blade-length distribution, we fitted an ordinary least squares regression and quantile regressions for the 10th, 50th, and 90th quantiles using `rq()` from the **quantreg** package in R. We then tested whether the fitted slopes differed among quantiles.\n\n**Results**\n\nBlade length increased with stipe length in the mean model, but the fitted quantile slopes showed that this relationship was not constant across the response distribution (see @fig-qr-lines and @fig-qr-slopes). The estimated slope was weakest at the 10th quantile (`0.12`), intermediate at the median (`0.255`), and strongest at the 90th quantile (`0.346`). A joint test across the fitted quantiles indicated that the slopes were not all equal (`F = 4.34`, `p < 0.05`). Thus, increasing stipe length was associated with a much stronger increase in upper-bound blade length than in lower-bound blade length.\n\n**Discussion**\n\nThe quantile regression reveals a biologically important pattern that would be muted in a mean-only analysis. Stipe length appears to influence the upper potential for blade development more strongly than the lower end of the blade-length distribution. This suggests that while longer stipes may permit greater blade elongation, shorter blades can still occur across much of the stipe-length range, presumably because other unmeasured factors also constrain morphology.\n:::\n\n# What to Do When Assumptions Fail / Alternatives\n\n-   If the fitted straight quantile lines are clearly inadequate, extend the model with polynomial terms or quantile smoothers rather than forcing a linear form.\n-   If quantile lines cross implausibly, reduce model complexity and inspect whether sparse data at extreme predictor values are driving the problem.\n-   If observations are not independent because of repeated measures, sites, or years, then the dependence structure must be addressed explicitly; ordinary `rq()` is not enough.\n-   If the scientific question is still about the conditional mean, ordinary least squares remains simpler and easier to interpret.\n\n# Summary\n\n-   Quantile regression models the response distribution more completely than mean regression.\n-   It is especially useful for wedge-shaped ecological data and for questions about limits or constraints.\n-   It does not require constant variance or normally distributed residuals, but it still requires sensible model specification and independent observations.\n-   In the _Laminaria_ example, stipe length had a much stronger effect on the upper quantiles of blade length than on the lower quantiles.\n-   The main biological gain is not mathematical novelty, but a clearer view of how predictors shape the whole distribution of ecological responses.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}